### PR TITLE
Optimize `cgen.addIndent`

### PR DESCRIPTION
**Pull request by AmjadHD**

### CODE REVIEW

**Comment by metagn** [comment]
How is this faster?

**Comment by AmjadHD** [comment]
It preallocates the space required.

**Comment by Araq** [comment]
It's not necessarily faster this way as it creates a temporary string. Instead you need to do some dance like

```nim
let oldLen = s.len
s.setLen oldLen + IndentationLen
for i in 0..<IndentationLen: s[i+oldLen] = '\t'
```

**Comment by AmjadHD** [comment]
I assumed some `sink` magic would work here, but I guess it's not how it works.

**Comment by Araq** [comment]
It does `sink`, but a `sink` does not avoid a temporary.

**Pull request merged**
