### PR TITLE
Fail quickly if re or nre module is attempted to be compiled with js [backport]

### LINKED ISSUE #14338: nre throws internal error (only) when used with the js backend
I have a fairly simple nim program compiled with **Nim 1.2.0** . Neither `nim js -r "[...]/code.nim"` nor my `nimble build` work - they're throwing the same error, once I use the js backend instead of the c or cpp one: 
```
/home/me/.choosenim/toolchains/nim-1.2.0/lib/impure/nre.nim(255, 25) Error: internal error: expr(nkBracketExpr, tyUncheckedArray)

No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp js <file>
```

I didn't manage to install koch unfortunately and I don't think that this will help a lot since this error itself is not very descriptive. This seems to be the problematic line in nre.nim by the way:
```
let num = (int(table[pos]) shl 8) or int(table[pos + 1]) - 1
```

and I'm just using such nre functions:
```
input = input.replace(re"(?m)\#.*$", "")        # remove comments
```

I hope you will be able to fix this error. Thank you in advance!

### PR DESCRIPTION
**Pull request by kaushalmodi**
Fixes https://github.com/nim-lang/Nim/issues/14338

### CODE REVIEW

**Comment by timotheecour** [comment]
Poor objc backend :) Maybe c-like backend?

**Comment by kaushalmodi** [comment]
@timotheecour Glad you pinged here :)

My first attempt was `when not defined(c) and not defined(cpp):` but that failed when running `nim doc ..`.

**Update**: I understood what you meant (I have never used objc).. force-pushed an update to that error message.

**Comment by Araq** [comment]
Code should come after the obligatory copyright header. As it's done in every other file I ever looked at in my entire life.

**Comment by kaushalmodi** [comment]
@Araq 

> Code should come after the obligatory copyright header. As it's done in every other file I ever looked at in my entire life.

Done

**Review by timotheecour — APPROVED** [review]

**Pull request merged**
