### PR TITLE
this ensures libp2p continues to compile [backport]

### PR DESCRIPTION
**Pull request by Araq**

### CODE REVIEW

**Comment by arnetheduck** [comment]
what's the error / is there a minimal repro to add to the nim test suite?

**Comment by Araq** [comment]
I don't know, extracting minimal test cases has proven to be quite difficult for us. We're thinking about a bug-reducer-tool based on the compiler's parser.

**Comment by arnetheduck** [comment]
even working backwards from the fix and constructing a test case?

**Comment by Araq** [comment]
Yes, it's very time consuming regardless.

**Pull request merged**
