### PR TITLE
fix #10433

### LINKED ISSUE #10433: Regression in sequtils
```nim
import sequtils

let
  nums = @[1, 2, 3, 4]
  strings = nums.mapIt(string, $(4 * it))
assert strings == @["4", "8", "12", "16"]
```

Now results in:

```
a1.nim(5, 38) Error: undeclared identifier: 'it'
```

We have runnable examples for this, so I'm not sure what happened here. Maybe only when importing the module?

### PR DESCRIPTION
**Pull request by narimiran**

### CODE REVIEW

**Comment by Araq** [comment]
Did you test for the better error message?

**Comment by narimiran** [comment]
> Did you test for the better error message?

Yes, now the example in #10433 produces
```
Error: Use 'mapIt(seq1, op)' - without specifying the type of the returned seqence; usage of 'mapIt' is a user-defined error
```

**Comment by Vindaar** [comment]
The implementation of this `mapIt` can be removed, no?

**Comment by Araq** [comment]
@Vindaar yes but it's good enough.

**Pull request merged**
