### PR TITLE
Fix typo and improve in code-block of 'lib/pure/parseutils.nim'

### PR DESCRIPTION
**Pull request by albmelon**

### CODE REVIEW

**Comment by kaushalmodi** [comment]
For bonus, can you upgrade this PR to make that example in the docstring auto-checking i.e. using `runnableExamples` and `doAssert` instead of keeping that example passive in a doc string block.

To see an example of how to do that, see this recent commit: https://github.com/nim-lang/Nim/commit/bc14453f69b9bde449cb52655eb6ffe571d6a28b

image

**Comment by kaushalmodi** [comment]
To test if you changes are correct, cd to the lib/pure/ directory and run `nim doc parseutils.nim`. If the runnableExamples doesn't compile or pass a doAssert, you will see that failure at the end of `nim doc ..` run.

**Comment by narimiran** [comment]
> For bonus, can you upgrade this PR to make that example in the docstring auto-checking i.e. using `runnableExamples`

...which makes the produced HTML uglier, as it wrongly parses the block after `runnableExample` as some quoted/indented block.

The original commit was just fine as it was, and `.. code-block` is used regularly in the top-level documentation.

----

@albmoron can you please remove/revert your second commit?

**Comment by kaushalmodi** [comment]
> The original commit was just fine as it was, and .. code-block is used regularly in the top-level documentation.

But that won't be auto-checking.

If you prefer `.. code-block`, it should have a `:test:` on the next line to make it auto-checking.

Example: https://github.com/kaushalmodi/std_vector/blob/9504f02caa87fe96b89f670615977a64f847e2cd/src/std_vector.nim#L25-L38

**Comment by kaushalmodi** [comment]
> which makes the produced HTML uglier, as it wrongly parses the block after runnableExample as some quoted/indented block.

The `runnableExamples` needed to be at the end of the docstring to avoid that. It cannot be used inbetween a docstring. @albmoron Sorry about this ping-pong.

@narimiran is one of the Nim dev team members, so go as per his suggestion. But I will strongly encourage to have the example autochecking. i.e. do one of the below:

1. If using `.. code-block::`, add `:test:` to the next line
2. If using `runnableExamples:`, put that at the end of the doc string

**Pull request closed without merging**
