### PR TITLE
io: fix SetHandleInformation signature to match Windows'

### LINKED ISSUE #14980: SetHandleInformation wrong 'int' to 'HANDLE' casts with VC++ using cpp mode.
### Repro case
```
nim cpp --cc:vcc .\src\main.nim
```
```nim
import net

let socket = newSocket(
  Domain.AF_INET,
  SockType.SOCK_DGRAM,
  Protocol.IPPROTO_UDP,
  buffered = false
)
```

### Current Output
```
C:\Users\me\.choosenim\toolchains\nim-#devel\lib\system\io.nim(342): error C2664: 'BOOL SetHandleInformation(HANDLE,DWORD,DWORD)': cannot convert argument 1 from 'int' to 'HANDLE'
C:\Users\me\.choosenim\toolchains\nim-#devel\lib\system\io.nim(342): note: Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
C:\Program Files (x86)\Windows Kits\8.1\include\um\handleapi.h(88): note: see declaration of 'SetHandleInformation'
```

### Expected Output
It compiles.

### Possible Solution

If you just do `c` it works fine:
```
nim c --cc:vcc .\src\main.nim
```
```
Hint: 64214 lines; 9.882s; 75.609MiB peakmem; Debug build; ... [SuccessX]
```

Maybe a special case for cpp vs c when using --c:vcc is needed? Casting rules between C and C++ are more strict?

These PRs touched this area recently:
* https://github.com/nim-lang/Nim/pull/14550 @alaviss 
* https://github.com/nim-lang/Nim/pull/14548 @timotheecour
* https://github.com/nim-lang/Nim/pull/14551 @alaviss 

### Additional Information

```
nim -v
Nim Compiler Version 1.3.5 [Windows: amd64]
Compiled at 2020-07-14
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by alaviss**
Fixes #14980

We might want to add VCC to our test matrix in the future.

### CODE REVIEW

**Comment by Varriount** [comment]
Isn't there already a handle type in the Windows module file?

**Comment by alaviss** [comment]
> Isn't there already a handle type in the Windows module file?

Yes, but I can't import winlean here since this is the `system` module.

**Comment by timotheecour** [comment]
> Yes, but I can't import winlean here since this is the system module.

as I recommended in https://github.com/nim-lang/Nim/issues/14980#issuecomment-658439498, add a new `winlean_basics` that both io and winlean import, with the minimal definitions needed.

modules are cheap (see https://github.com/nim-lang/Nim/pull/14614), code duplication is costly (in terms of maintenance, bugs etc)

**Comment by Varriount** [comment]
I would rather that the module system was improved, such that sensible imports would be possible.

In any case, I'm merging this now because it's an ABI bug that causes memory corruption, and future improvements can be made without fear of breaking backwards compatibility.

**Comment by timotheecour** [comment]
> In any case, I'm merging this now because it's an ABI bug that causes memory corruption, and future improvements can be made without fear of breaking backwards compatibility.

ok

> I would rather that the module system was improved, such that sensible imports would be possible.

what do you mean by that, and what are you suggesting concretely? `import winlean` from `io` doesn't make sense (would carry too much dependencies for every program) at least not until nim has cyclic / lazy imports

**Comment by Araq** [comment]
> Yes, but I can't import winlean here since this is the system module.

system.nim can and does import other modules but I agree winlean shouldn't be imported, instead common definitions should move to somewhere else.

**Pull request merged**
