### PR TITLE
fixes #20426; remove `maincommand` and `m` options since they are a no op since 2014

### LINKED ISSUE #20426: -mm flag is ignored on latest Nim 1.7.1 be4bd8
### What happened?

Compiling a program with `-mm` flag ignores the instruction.

In the output below, I am instructing the compiler to use `orc` memory management but we see that it uses `refc`.

```bash
nim c -d:release -mm:orc --threads:off -o:ananim ana.nim
Hint: mm: refc; opt: speed; options: -d:release
43992 lines; 2.694s; 61.184MiB peakmem; proj: /tmp/ana.nim; out: /tmp/ananim [SuccessX]
```

### Nim Version

```bash
pouriya@DESKTOP-2EOD7PM:/tmp$  nim --version
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-09-23
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: be4bd8a0edd527b24679372b8cb9d2afa548056d
active boot switches: -d:release
```

### Current Standard Output Logs

```shell
pouriya@DESKTOP-2EOD7PM:/tmp$  nim --version
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-09-23
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: be4bd8a0edd527b24679372b8cb9d2afa548056d
active boot switches: -d:release
pouriya@DESKTOP-2EOD7PM:/tmp$  nim c -d:release -mm:orc --threads:off -o:ananim ana.nim
command line(1, 2) Warning: 'm' is deprecated, now a noop [Deprecated]
command line(1, 2) Warning: 'm' is deprecated, now a noop [Deprecated]
Hint: used config file '/home/pouriya/.choosenim/toolchains/nim-#devel/config/nim.cfg' [Conf]
Hint: used config file '/home/pouriya/.choosenim/toolchains/nim-#devel/config/config.nims' [Conf]
...............................................................................
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/std/private/digitsutils.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/std/assertions.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/system/dollars.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/std/syncio.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/system.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/pure/hashes.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/pure/math.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/pure/algorithm.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/pure/collections/tables.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/pure/parseutils.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/pure/unicode.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/pure/strutils.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/pure/strformat.nim
CC: ana.nim
Hint:  [Link]
Hint: mm: refc; opt: speed; options: -d:release
43992 lines; 2.694s; 61.184MiB peakmem; proj: /tmp/ana.nim; out: /tmp/ananim [SuccessX]
```

### Expected Standard Output Logs

```shell
nim c -d:release -mm:orc --threads:off -o:ananim ana.nim
command line(1, 2) Warning: 'm' is deprecated, now a noop [Deprecated]
command line(1, 2) Warning: 'm' is deprecated, now a noop [Deprecated]
Hint: used config file '/home/pouriya/.choosenim/toolchains/nim-#devel/config/nim.cfg' [Conf]
Hint: used config file '/home/pouriya/.choosenim/toolchains/nim-#devel/config/config.nims' [Conf]
...............................................................................
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/std/private/digitsutils.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/std/assertions.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/system/dollars.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/std/syncio.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/system.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/pure/hashes.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/pure/math.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/pure/algorithm.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/pure/collections/tables.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/pure/parseutils.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/pure/unicode.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/pure/strutils.nim
CC: ../home/pouriya/.choosenim/toolchains/nim-#devel/lib/pure/strformat.nim
CC: ana.nim
Hint:  [Link]
Hint: mm: **orc**; opt: speed; options: -d:release
43992 lines; 2.694s; 61.184MiB peakmem; proj: /tmp/ana.nim; out: /tmp/ananim [SuccessX]
console
```

### Possible Solution

use `-gc` instead of `-mm` on the latest version.

### Additional Information

If you specify `-gc:orc` instead of `-mm:orc`, the compiler uses the right memory management algorithm.

### PR DESCRIPTION
**Pull request by ringabout**
Fixes #20426

https://github.com/nim-lang/Nim/commit/7f7b13a45f73c6d9dcca3ce8388833189d77426c#diff-d949f8c356fd2dc9ceedc6f3dbbd01e2c806269dd0a8ad6516facf589fa2c99a made it a no op, but it causes a regression because it should have added `expectArg(switch, arg, pass, info)` before the discard statement. It causes https://github.com/nim-lang/Nim/issues/20426 to happen. Without `expectArg(switch, arg, pass, info)`, `-mm:orc` is wrongly interpreted as `-m` and compiler, which doesn't make sense. It should either abort compilation or prints `argument for command line option expected: '-m'` message. Since they are a no op since 2014, let's remove it to clear the confusion and wait and see whether it breaks something.

### CODE REVIEW

**Comment by Varriount** [comment]
Does this require any documentation changes?

**Comment by ringabout** [comment]
> Does this require any documentation changes?

No, there is no documentation for them since they are a no op since long, long ago. In case of confusion, I add a changelog now.

**Comment by narimiran** [comment]
@ringabout should we backport this?

**Comment by ringabout** [comment]
Imo, it hardly breaks anything and is not a big deal. Yeah, backport please, thank you!

**Pull request merged**
