### PR TITLE
fixes #18146; fixes #19372; disable tlsEmulation on windows;  static link pthreads with mingw

### LINKED ISSUE #15392: ARC/ORC loop string allocation slowdown
My proof of work function encounters a bug when running it under arc/orc. I'm using a [libsodium wrapper](https://github.com/FedericoCeratto/nim-libsodium) but if you replace `crypto_generichash()` with SHA1 in the standard library or a SHA2 library (or any other hashing library I think) the bug is also triggered. It runs fine for the default refc gc but when I enable arc or orc I only get ~50% cpu usage instead of 100% with refc. Something weird must be happening under the hood since while htop reports ~90% cpu usage, only ~50% of the load bars are green while the other half is red. This means ~50% of cpu time is used for user processes and ~50% is used for kernel processes. The refc version uses 100% cpu (all green user time) and takes 2.1 seconds to complete while arc/orc takes 17.5 seconds on my Haswell cpu.

### Example
Edit: removed unnecessary code and added SHA1 version in comments.
```nim
import threadpool, strutils
import libsodium/sodium
# import std/sha1

let
  payload = "just testing?0!7801"
#  initialHashHex = $secureHash(payload)
  initialHashHex = crypto_generichash(payload, 16)
  target = 0xFFFFFFFFFF'u64

func pow(target: uint64, initialHashHex: string, nonce: uint64): (uint64, string) {.thread.} =
  var
    trialValue = high(uint64)
    nonceThread = nonce
    resultHash = newStringOfCap(64)
  while trialValue > target:
#    resultHash = $secureHash($nonceThread & initialHashHex)
    resultHash = crypto_generichash(crypto_generichash($nonceThread, 32, initialHashHex).bin2hex, 32, initialHashHex).bin2hex
    trialValue = fromHex[uint64](resultHash[0..15])
    inc(nonceThread)
  return (nonceThread-1, resultHash)

proc multithread(totalThreads: range[1..256], thread: range[1..256], initialHashHex: string, target: uint64): uint64 {.thread.} =
  let nonce = high(uint64) div uint64(totalThreads) * uint64(thread-1)
  echo "thread: ", thread, " initialNonce: ", nonce.toHex  # Debugging
  let (finalNonce, finalHash) = pow(target, initialHashHex, nonce)
  echo "thread: ", thread, " finalNonce: ", finalNonce.toHex, " finalHash: ", finalHash  # Debugging
  result = finalNonce

proc callMulti(threads: range[0..256], initialHashHex: string, target: uint64) =
  var responses = newSeq[FlowVarBase](threads)
  for thread in 1..threads:
    responses[thread-1] = spawn multithread(threads, thread, initialHashHex, target)
  var index = blockUntilAny(responses)

let threads = 4
callMulti(threads, initialHashHex, target)
```

### Current Output
Used `time <program>`
```
thread: 1 initial-nonce: 0000000000000000
thread: 2 initial-nonce: 3FFFFFFFFFFFFFFF
thread: 3 initial-nonce: 7FFFFFFFFFFFFFFE
thread: 4 initial-nonce: BFFFFFFFFFFFFFFD
thread: 3 finalNonce: 8000000000149A1E finalHash: 000000a571afd62996c32001f8f84ecc1d178d1e4937f64bd2db65d840e76fa5

real    0m17.544s
user    0m38.656s
sys     0m25.423s
```

### Expected Output
Used `time <program>`
```
thread: 1 initial-nonce: 0000000000000000
thread: 2 initial-nonce: 3FFFFFFFFFFFFFFF
thread: 3 initial-nonce: 7FFFFFFFFFFFFFFE
thread: 4 initial-nonce: BFFFFFFFFFFFFFFD
thread: 3 finalNonce: 8000000000149A1E finalHash: 000000a571afd62996c32001f8f84ecc1d178d1e4937f64bd2db65d840e76fa5

real    0m2.058s
user    0m7.896s
sys     0m0.009s
```

### Possible Solution

I posted this on the [forum](https://forum.nim-lang.org/t/6817) and mratsim chimed in saying:
* crypto_generichash($nonceThread, 32, initialHashHex), this converts (and so allocate) to a Nim string, and then convert to C-string implicitly as libsodium is using a C backend. It's possible that ARC/ORC is then reclaiming this somehow.

While that might be the case, it still happens when using a hash algorithm implemented in nim.

### Additional Information
The bug exists in the latest devel and 1.2.6.
```
$ nim -v
Nim Compiler Version 1.3.7 [Linux: amd64]
Compiled at 2020-09-22
git hash: 4b9eea2fcc5d030393ca9020fbbee33fcb48d41a
```

### LINKED ISSUE #18146: Combine --gc:arc with --threads:on slow down the performance heavily.
I wrote a [reversi](https://github.com/khchen/wNim/blob/master/examples/reversi.nim) game with [Monte Carlo AI engine](https://github.com/khchen/wNim/blob/master/examples/mcts/mcts.nim) as an example for [wNim](https://github.com/khchen/wNim). I found that combining --gc:arc with --threads:on would impact the performance. 

Here is my test. Test file is https://github.com/khchen/wNim/blob/master/examples/mcts/mcts.nim. I only paste the result of first round, adding a break to the loop will get the same result.

| Compiling Command | Result |
| ------------- | ------------- |
| `nim r -d:danger --opt:speed mcts` | rounds: 1724  |
| `nim r -d:danger --opt:speed --gc:arc mcts` | rounds: 1782 |
| `nim r -d:danger --opt:speed --threads:on mcts` | rounds: 1715 |
| `nim r -d:danger --opt:speed --threads:on --gc:arc mcts` | rounds: 1239 |

In conclusion, adding --gc:arc will speed up a little. However, combine --gc:arc with --threads:on will slow down the performance heavily. The most strange thing is that mcts.nim is just a single thread program!  Is there a bug of compiler? or the bug is in my code?

### LINKED ISSUE #19372: tlsEmulation:on doesn't work with IC
*test.nim*
```nim
echo "Yes"
```

`nim c -r --incremental:on --threads:on -d:nimIcIntegrityChecks test.nim` gives 

```
Traceback (most recent call last)
test.nim(1)  main
io.nim(827)              echoBinSafe
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

The symbol is a Lock object.

```nim
acquireSys echoLock
```

### PR DESCRIPTION
**Pull request by ringabout**
fixes #18146
fixes #19372

### CODE REVIEW

**Comment by ringabout** [comment]
I tested it by deleting `libwinthreads.dll`. I assume it's the only dep that is affected when disabling tlsemulation.

**Comment by rockcavera** [comment]
> I tested it by deleting `libwinthreads.dll`. I assume it's the only dep that is affected when disabling tlsemulation.

@ringabout I tested it here, after this PR, but it keeps dynamically linking pthread. Tested with the gcc compilers provided by Nim.

How did I test and verify that I needed "libwinpthread-1.dll"? Steps to reproduce:
- 1: open Windows cmd
- 2: nim c some_nim_code
- 3: set PATH=""
- 4: some_nim_code

When trying to run it will give an error saying that it needs "libwinpthread-1.dll".

**Comment by ringabout** [comment]
Like this ?

image

**Comment by ringabout** [comment]
Looking into it

**Comment by ringabout** [comment]
It seems that apart from the direct use of `libpthread`, there is another shared dll using `libwinpthread` since `{.passl: "-Wl,-Bstatic -lpthread".}` works.

**Comment by rockcavera** [comment]
> It seems that apart from the direct use of `libpthread`, there is another shared dll using `libwinpthread` since `{.passl: "-Wl,-Bstatic -lpthread".}` works.

Yes, it works. That's how I was able to link statically. I'm just not sure it will force static link to all the other -lLibs passed as well. Perhaps a way to add `-Wl,-Bstatic -lpthread` as the last link parameter on Windows?

**Comment by ringabout** [comment]
Here is the link parameter

```
-Bstatic -lpthread -Bdynamic -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt -lkernel32 -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt -lkernel32 c:/users/blue/desktop/exe/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.1.0/crtend.o
```

It seems that `-lpthread` will be passed twice so the first one is canceled.

**Comment by ringabout** [comment]
It seems that if `-Bstatic -lpthread` is added in config, it will be appended after user configs.

**Pull request merged**
