### PR TITLE
strformat: add the possibility to insert thousands separators into numbers

### PR DESCRIPTION
**Pull request by skilchen**
I am making an attempt to add the possibility to insert thousands separators into numbers via `strformat`. My attempt is inspired by the similar feature in python's f-strings but my implementation is much more simple minded. I am unable to reimplement the locale support available in python, therefore my attempt offers the possibility to use one of `{',', '\'', '.'}` as the separator char. And i don't insert thousands separators into the zero-padding. Please give it a try and let me know what you think...

Examples:
```nim
echo fmt("{high(int32):#,d}")
echo fmt("{high(int32):#,x}")
echo fmt("{high(int32):#,b}")
echo fmt("{high(int32):#,o}")
echo fmt("{-1:+015,d}")
echo fmt("{-123:+015,d}")
echo fmt("{-1234:+015,d}")
echo fmt("{12345:+015,d}")
echo fmt("{123456: 15,d}")
echo fmt("{1234567: 15,d}")
echo fmt("{12345678:+015'd}")
echo fmt("{123456789:+015'd}")
echo fmt("{1234567890:+015'd}")
echo fmt("{12345678901:+015,d}")
echo fmt("{123456789012:+015,d}")
echo fmt("{1234567890123:+015,d}")

echo fmt("{float(low(int32)) - 1.1e10:+30'.20e}")
echo fmt("{float(low(int32)) - 0.1:+30'.11g}")
echo fmt("{float(high(int32))+0.1234567: 30,.6f}")
```
should produce:
```
2,147,483,647
0x7fff_ffff
0b111_1111_1111_1111_1111_1111_1111_1111
0o17_777_777_777
-00000000000001
-00000000000123
-0000000001,234
+0000000012,345
        123,456
      1,234,567
+000012'345'678
+000123'456'789
+01'234'567'890
+12,345,678,901
+123,456,789,012
+1,234,567,890,123
   -1.31474836480000000000e+10
              -2'147'483'648.1
          2,147,483,647.123457
```

### CODE REVIEW

**Comment by Araq** [comment]
The problem is that this way I cannot use a locale specific separator at all (correct me if I'm wrong). We need a syntax for that too...

**Comment by dom96** [comment]
Nice, I was looking for this recently for one of my projects.

Locale awareness is definitely something we need to consider.

**Comment by data-man** [comment]
> Locale awareness is definitely something we need to consider.

We can reanimate osinfo in stdlib and add there the localeSettings.

**Comment by skilchen** [comment]
> @Araq: The problem is that this way I cannot use a locale specific separator at all (correct me if I'm wrong). We need a syntax for that too...

My proposal is intentionally simple minded (maybe somewhat similar to [PEP 378](https://www.python.org/dev/peps/pep-0378/) in Python). IMHO it is a minimally viable solution. Now that i understand, why '_' did not work before, you have to choice between `{',', '\'', '.', '_', ' '}` as thousand separators. 

Python's f-strings have `,` and `_` as possible separators, but Python has `n` as a conversion character to get locale aware number formats. In Python you can use either the simple separator chars or the locale aware number conversion, but not both at the same time. 

My proposal only offers the simple separator chars, but it does not prevent someone else from implementing the `n` conversion. I am not good enough at localization issues to come up with a proposal to implement locale aware number formatting. Maybe your wrapping specialist @genotrance could try to wrap [ICU - International Components for Unicode](http://icu-project.org/apiref/icu4c/). IMHO it would be a waste of time to go the old way of `setlocale`/`localeconv` to get locale aware number formats. This would be particularly problematic for the js backend. AFAIK JavaScript is also moving in the direction to standardize something along the lines of ICU.

**Comment by skilchen** [comment]
Ok, thats not something that i will try to implement.

**Pull request closed without merging**
