### PR TITLE
fixes #8037, json.to support object with distinct types

### LINKED ISSUE #8037: json.nim macro `to` does not support objects with distinct types
To replicate:

```nim
import json

type
    String = distinct string
    Email = distinct string
    Toot = object
      name*: String
      email*: Email

var tJson = parseJson("""{"name":"Bongo", "email":"bongo@bingo.com"}""")

var t = to(tJson, Toot)

```

### PR DESCRIPTION
**Pull request by jangko**

### CODE REVIEW

**Comment by dom96** [comment]
What happens when I have a ``distinct seq[T]``? or a ``distinct Option[T]`` or any of the other types ``json.to`` supports in a special way?

**Comment by jangko** [comment]
distinct seq[T] will works. but distinct Option[T] and some other specially supported types need to overhaul createConstructor and processType

**Comment by dom96** [comment]
Could you add tests for those types and fix it for ``Option[T]`` as well as other types that may fail? I'd rather ensure this functionality is solid than come back to it in 3 months when someone tries to use it with something we didn't test.

**Comment by jangko** [comment]
okay, but I'll fix some inconsistencies in macros module first, because that would be needed to ease the pain when fixing this.

**Comment by jangko** [comment]
although I have a plan to fix #7737, looks like I have found a workaround using getTypeInst and getTypeImpl together to detect distinct types. #7737 can wait.

**Comment by dom96** [comment]
Looks good.

**Pull request merged**
