### PR TITLE
nativesockets: add missing inheritable pass-through

### PR DESCRIPTION
**Pull request by alaviss**

### CODE REVIEW

**Comment by timotheecour** [comment]
@Araq has anything changed in the way this PR was merged? every other PR was merged by squash-and-merge to avoid tangled git history (refs https://github.com/nim-lang/Nim/issues/8664)

image

**Comment by Clyybber** [comment]
Githubs mobile site UI does that by default AFAIR, so thats probably why.

**Comment by timotheecour** [comment]
even on mobile phone UI it gives you the option to pick squash and merge; hence https://github.com/nim-lang/Nim/issues/8664 which proposed to disable other options by default to prevent such mistakes:

> in nim-lang/Nim/settings, disable "Allow merge commits", as follows:

and in the < 1% cases where a squash+merge is not desirable, this option can be temporarily re-enabled.

The damage here was limited (merged commit had recent common ancestor) but it can be more damaging in other cases when ppl merge instead of rebase their PR's and common ancestor is old.

**Comment by Araq** [comment]
Well nothing changed but I was not cautious enough this time.

**Pull request merged**
