### PR TITLE
fixes #14126 [backport:1.2]

### LINKED ISSUE #14126: RVO not exception safe
### Example
```nim
type X = object
  a, b, c: string

proc f(): X =
  result.a = "a"
  result.b = "b"
  raise (ref ValueError)()

var x: X
x.a = "1"
x.b = "2"
x.c = "3"

try:
  x = f()
except:
  discard

echo x
doAssert x.c == "3", "shouldn't modify x if f raises"

```

### Current Output
```
(a: "a", b: "b", c: "")
```

### Expected Output
```
(a: "1", b: "2", c: "3")
```

```
[arnetheduck@tempus nim-beacon-chain]$ nim -v
Nim Compiler Version 1.3.1 [Linux: amd64]
Compiled at 2020-04-21
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: b4e9f8e814373fc38741736197d88475663ce758
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by Araq**

### CODE REVIEW

**Comment by timotheecour** [comment]
although safer, can that cause performance regressions? (refs: https://github.com/nim-lang/Nim/issues/14126#issuecomment-619827991)

**Comment by Araq** [comment]
We can do better and only pessimize inside a ``try`` statement.

**Comment by timotheecour** [comment]
that would just be a rather weird one-off special case and wouldn't help when popping up the try/catch handler 1 level:
```nim
type X = object
  a, c: string

proc f(): X =
  result.a = "a"
  raise (ref ValueError)()

proc main(x: var X) =
  x.a = "1"
  x.c = "3"
  x = f()

var x: X
try:
  main(x)
except:
  echo "caught"
echo x
doAssert x.c == "3", "this assert will fail"
```

even if we were to track exceptions to only disable nrvo when inside some try/catch ancestor, given that `try/catch` can happen very far from where exception is thrown (eg at application root, say in some main loop), it'd imply that every single `x = fun()` would have NRVO disabled.

IMO that's potentially a performance killer. I'm honestly not convinced https://github.com/nim-lang/Nim/issues/14126 is a real problem to begin with, once you acknowledge existence of NRVO.

We could instead embrace current behavior as spec, have a nice speed benefit over equivalent C++ code, document it well, and provide a good opt-in option for code that must rely on NRVO-safe behavior; eg:
```nim
x = f()
=>
let xAux = f()
x = xAux
```

**Comment by Clyybber** [comment]
@timotheecour Simple location analysis will do. Only disable the RVO for raising procs when we are in a try, or the result is assigned to a global, upvalue or var parameter.

**Pull request merged**
