### PR TITLE
Implements BackwardsIndex `[]` for deque.

### PR DESCRIPTION
**Pull request by dom96**

### CODE REVIEW

**Comment by krux02** [comment]
If this PR here would have been merged: https://github.com/nim-lang/Nim/pull/7265 then this PR would not be necessary in the first place. But it seems like there is a concepts bug that prevents this general solution to be introduced.

**Comment by dom96** [comment]
> Needs one more overload? proc `[]`*[T](deq: Deque[T], i: BackwardsIndex): T

The non-var return type? I don't think that's necessary.

**Comment by Araq** [comment]
Needs one more overload: ``proc `[]`*[T](deq: Deque[T], i: BackwardsIndex): T``

(Yes, I know it sucks, but it is what it is.)

**Comment by dom96** [comment]
Done

**Pull request merged**
