### PR TITLE
[Docs] Attribute citation to Richard Gabriel

### PR DESCRIPTION
**Pull request by Clyybber**

### CODE REVIEW

**Comment by Araq** [comment]
Got a link to show it's from him? I googled for "Richard Gabriel quotes" but haven't found this quote.

**Comment by Yardanico** [comment]
I found this:
image
So it's in the file made by Richard Gabriel (https://extravagaria.com/Files/ObjectsHaveFailed.pdf), but it seems that Richard is not the author

**Comment by Clyybber** [comment]
@Yardanico I think rpg stands for Richard P. Gabriel

**Comment by Clyybber** [comment]
@Araq In addition to the source @Yardanico provided, I found this: http://www.gungfu.de/zitate/author/Richard_P._Gabriel.html

**Comment by Araq** [comment]
Alright.

**Pull request merged**
