### PR TITLE
simplify toHex

### PR DESCRIPTION
**Pull request by timotheecour**
no need for 3 overloads refs https://github.com/nim-lang/Nim/pull/15770

### CODE REVIEW

**Comment by Araq** [comment]
We considered this solution but we don't know if ``toHex`` is passed around as a callback, so this can break code. We simply won't win with the current Nim that lacks the ``.procvar`` feature. I regret removing ``.procvar`` from Nim, people are in love with FP and pass all procs that they can around as first class entities.

**Comment by timotheecour** [comment]
> we don't know if toHex is passed around as a callback, so this can break code

how so?
toHex was already overloaded so `let fn = toHex` (nor `const`) would not have worked prior this PR;
this works both before and after this PR:
```nim
import strutils
let f: proc(x: int, len: Positive): string = toHex
echo f(-8,4)
  
proc goo(a: proc(x: int, len: Positive): string) = echo a(3,4)
goo(toHex)
```

>  I regret removing .procvar from Nim, people are in love with FP and pass all procs that they can around as first class entities

that's what https://github.com/nim-lang/Nim/pull/11992 is for, which makes this work, among other things:
```nim
when true:
  import pure/lambdas
  proc z[T](a: T) = discard
  proc z(a: int) = discard
  proc z(a: float) = discard
  proc algo(fn: auto) =
    fn(1.1)
    fn(1)
    fn('x')
  algo(alias2 z)
```

**Comment by Araq** [comment]
> how so? toHex was already overloade

It wasn't overloaded in 1.2 and was overloaded in 1.4. At least that's how I remember it. And the rules for passing an overloaded proc to a procvar are different from the rules of passing a generic proc to a procvar.

> that's what #11992 is for, which makes this work, among other things:

Ha, you win. Good point.

**Comment by timotheecour** [comment]
> It wasn't overloaded in 1.2 and was overloaded in 1.4. At least that's how I remember

it was already backported to 1.2.x, see https://github.com/nim-lang/Nim/commit/b5c90a34314b3ad6da6d563da0b204117c6797a7
so 1.2.x => 1.2.y would have been the place where a breaking change occurred, which confirms that every bugfix is a potential breaking change, and the main thing that matters is being pragmatic in each case.

>  And the rules for passing an overloaded proc to a procvar are different from the rules of passing a generic proc to a procvar.

can you please elaborate or point me to where this is described, and does it impact code that uses toHex being an overload vs a generic?

**Comment by Araq** [comment]
> can you please elaborate or point me to where this is described, and does it impact code that uses toHex being an overload vs a generic?

The compiler is smarter than I remember it so I cannot create an example where the behaviours differ.

**Pull request merged**
