### PR TITLE
Bisect Bugs

### PR DESCRIPTION
**Pull request by juancarlospaco**
- See https://github.com/juancarlospaco/nimrun-action/issues/3#issuecomment-1607344901 (ideas/PR welcome).
- Git bisect like for bug repro code on issue comments against Nim versions >`1.0` using Github Actions.
- More debug tooling without adding more code to any Nim repos.
- Does not add more time to main CI runs, even if it breaks wont affect CI, its only for new issue comments.

# Use

Collaborators can create a new comment with the reduced repro code sample:

temp

# Setup for Admins

- Go to https://github.com/nim-lang/Nim/settings/actions
- Find "Workflow permissions" section.
- Enable "Read and write permissions".

### CODE REVIEW

**Comment by Araq** [comment]
Does it slow down the CI?

**Comment by ringabout** [comment]
It doesn't because it triggers by comments. But it's hardly useful to me because I have installed Nim versions from 0.20.0 to devel locally. Except that, it is supposed to cause no harm.

**Comment by juancarlospaco** [comment]
Soon it will find which commit introduces the bug:

temp

**Comment by ringabout** [comment]
@juancarlospaco https://github.com/nim-lang/Nim/issues/19076#issuecomment-1616282441 why it didn't work?

**Comment by ringabout** [comment]
@github-actions nim c

```nim
doAssert NimMinor > 5
```

**Comment by ringabout** [comment]
@github-actions nim c
```nim
doAssert NimMinor < 5
```

**Comment by juancarlospaco** [comment]
@ringabout Fixed https://github.com/juancarlospaco/nimrun-action/commit/cfab26ee048c3d22fccb64a655f6990eb81b0bba

Now it should work. 🙂

**Comment by ringabout** [comment]
@github-actions nim c
```nim
doAssert NimMinor < 5
```

**Comment by ringabout** [comment]
@github-actions nim c
```nim
import tables
var tested:Table[string,int]

template `[]`[V](t:Table[string,V],key:string):V =
  echo V
  tables.`[]`(t,key)
discard tested["three"]
```

**Comment by juancarlospaco** [comment]
`Error: internal error: expr(skType); unknown symbol. No stack traceback available`
https://github.com/nim-lang/Nim/actions/runs/5437138472/jobs/9887478111#step:4:18

**Comment by juancarlospaco** [comment]
@ringabout I Unlocked it for all Github users to Bisect, seeing this https://github.com/nim-lang/Nim/issues/19076#issuecomment-964910695

Maybe is useful if users can Bisect their own bugs on their own issues,
and core devs already have the breaking commit when you read the issue.

If it gets too much spam/trolls/etc let me know and we can revert to Locked to Admins-only.

(You can still ban/limit users from [the repo admin settings anyway](https://github.com/nim-lang/Nim/settings/interaction_limits) ).

[It can find which specific commit introduces the bug already.](https://github.com/juancarlospaco/nimrun-action/commit/92bd9d4a73be1e8e1b2c63ff11ca4d9bc00d30fe)

**Comment by ringabout** [comment]
> I Unlocked it for all Github users to Bisect, seeing this https://github.com/nim-lang/Nim/issues/19076#issuecomment-964910695

That's cool. 

@github-actions nim c
```nim
import tables
var tested:Table[string,int]

template `[]`[V](t:Table[string,V],key:string):V =
  echo V
  tables.`[]`(t,key)
discard tested["three"]
```

**Comment by juancarlospaco** [comment]
It matches that the comment starts with "@github-actions nim":
https://github.com/juancarlospaco/nimrun-action/blob/nim/index.js#L286

https://github.com/juancarlospaco/nimrun-action/blob/nim/index.js#L145-L146

🙂

**Comment by ringabout** [comment]
How about

```
!bisect nim c
```
? It's shorter and more relevant to its functionality.

Or `!eval` which is consistent with the command on the Discord.

```
!eval nim c
```

**Comment by juancarlospaco** [comment]
Theres https://github.com/bisect
`@github-actions` is like "convention" to know you are referring to a Bot.

**Comment by ringabout** [comment]
@github-actions nim c
```nim
import tables
var tested:Table[string,int]

template `[]`[V](t:Table[string,V],key:string):V =
  echo V
  tables.`[]`(t,key)
discard tested["three"]
```

**Comment by juancarlospaco** [comment]
`Error: internal error: expr(skType); unknown symbol. No stack traceback available.`
https://github.com/nim-lang/Nim/actions/runs/5440016221/jobs/9892529097#step:4:92

Yeah when its an internal compiler error with no stack traceback available, it cant report yet, I need to improve that. 
(That sample is crashing all compilers from devel to 1.0 basically, 
it needs 1 working commit and 1 non-working commit, 
then it bisects between that range of commits to find the breaking commit) 😐

**Comment by juancarlospaco** [comment]
The point of the `@` was the autocomplete:

temp

But yeah it can be changed.

**Comment by juancarlospaco** [comment]
@ringabout I changed it to match `"!nim "` **at the start of the first line**, 
so like `"!nim c"` or `"!nim cpp"` or `"!nim js"` and the Nim code,
also now it should work OK when the compiler crashes with no output:

https://github.com/juancarlospaco/nimrun-action/commit/6b953847887e6d3f8c594c7823ca96a70ca8ee2a

Need to update readme docs.

**Comment by ringabout** [comment]
Excellent work!

**Pull request merged**
