### PR TITLE
Nimdoc hide nonexported fields

### PR DESCRIPTION
**Pull request by johnperry-math**
This is my attempt to solve [Issue 19396](https://github.com/nim-lang/Nim/issues/19396).

### CODE REVIEW

**Comment by johnperry-math** [comment]
This fails several tests in CI, but in my opinion it should. The failures are caused by comparing (new) correct output to (old) incorrect output.

In particular, all the failures I've seen so far surround this code:
```nim
object
  arr: array[0 .. 3, float32]
```
The current output is simply `object`; the expected output is
```
object
  arr: array[0 .. 3, float32]
```
However, `arr` isn't exported, so the expected output is incorrect.

**Comment by johnperry-math** [comment]
Thinking about it some more, I suppose this could be fixed by changing the test so that it runs `nim doc --showNonExports`. Thoughts?

**Comment by johnperry-math** [comment]
Oddly enough, that would not fix it. I tried a few different ways of doing this, and the problem seems somewhat deeper. I also tried reversing the default behavior, so that non-exported fields are shown, whereas the option enables their hiding. I really don't know what's going on here.

**Comment by johnperry-math** [comment]
The CI failures turned out to be an issue in the VM code. I've pushed a one-line commit that fixes that error.

Curious that an invalid Nim program is used as a CI test for documenting macros. (? if that's what it is)

**Comment by johnperry-math** [comment]
Current failures appear to arise in an imported nimble package, `bump`. Like the previous failure, it seems to be related to macros.

**Comment by johnperry-math** [comment]
Two current failures. One of them is due to an outdated nim documentation test; that's been updated. The other is due to a test on nimterop that I have confirmed was failing with the code I checked out of master.

**Comment by Araq** [comment]
@ringabout please rebase and take over, it's a nice patch.

**Pull request closed without merging**
