### PR TITLE
Add runnableExamples for strmisc procs and a better doc for expandTabs

### PR DESCRIPTION
**Pull request by recloser**

### CODE REVIEW

**Comment by Araq** [comment]
Ready to be merged once appveyor is green.

**Comment by timotheecour** [comment]
@Araq 
> Ready to be merged once appveyor is green.

shows as green in https://travis-ci.org/nim-lang/Nim/builds/447835300?utm_source=github_status&utm_medium=notification

even though "The Travis CI build is in progress" is shown here ( as was mentioned here: https://github.com/nim-lang/Nim/pull/9552#issuecomment-434086003)

**Comment by timotheecour** [comment]
(closed and re-opened to retrigger CI)

**Comment by krux02** [comment]
hmm, I feel there is some bad luck involved. Or the runable examples significantly increase the compilation time.

**Comment by recloser** [comment]
Yeah, right now devel itself is failing CI on that test (`tasyncssl`), so that affects every recently checked PR. I wonder why it only fails on AppVeyor, though.

**Pull request merged**
