### PR TITLE
fixes #15688; handle `strongSpace` overflow issues

### LINKED ISSUE #15688: Nim compiler crashes when trailing whitespace are too many (>=128)
### Example
```nim
type 
  PointXY*[T: SomeNumber] = object of RootObj                                                                                                                                                                                                                               
    x*, y*: T 
  PointXYZ*[T: SomeNumber] = object of PointXY[T]                                     
    z*: T                                                                         
  PointXYM*[T: SomeNumber] = object of PointXY[T]                                     
    m*: T 
  PointXYZM*[T: SomeNumber] = object of PointXY[T]
    z*, m*: T                                                                     
  Point*[T] = PointXY[T] | PointXYZ[T] | PointXYM[T] | PointXYZM[T]

type  
  LineString*[P: Point] = object of RootObj                                                                                                                                                                                                                             
    lineSeq: seq[P]


var linez: LineString[PointXYZ[int]]

echo linez.P
echo linez.P is PointXYZ
echo linez.P is PointXYZ[int]
```
https://play.nim-lang.org/#ix=2BHk

### Current Output

```
Hint: used config file '/playground/nim/config/nim.cfg' [Conf]
Hint: used config file '/playground/nim/config/config.nims' [Conf]
....fatal.nim(49)            sysFatal
Error: unhandled exception: over- or underflow [OverflowDefect]
```

### Expected Output
```
Hint: used config file '/usr/local/etc/nim/nim.cfg' [Conf]
Hint: 314 LOC; 0.151 sec; 4.191MiB peakmem; Debug build; proj: /usr/home/lbartoletti/test_crash.nim; out: /usr/home/lbartoletti/test_crash [SuccessX]
Hint: /usr/home/lbartoletti/test_crash  [Exec]
PointXYZ[system.int]
true
true
```

### Possible Solution

> the error is fixed by removing trailing whitespace (>= 128 spaces at the end of any line causes it)

Thanks to mipri on IRC.

### Additional Information

Tested on 1.0.0, 1.2.6, 1.2.8 and latest

### PR DESCRIPTION
**Pull request by ringabout**
fixes #15688

### CODE REVIEW

**Comment by metagn** [comment]
Do we even need strong space counters to have a value higher than 1

**Comment by Araq** [comment]
I don't remember if there is meaning in values > 1. If not, turn it into a bool.

**Comment by ringabout** [comment]
There is a meaning with `-1` for `strongSpaceB` which marks the end of the file

```nim
  if L.buf[pos] in {CR, LF, nimlexbase.EndOfFile}:
    tok.strongSpaceB = -1
  ```

I can change the type of `strongSpaceA` in this PR.

**Comment by metagn** [comment]
Not to keep changing things but an alternative is to use `type TokenSpacing = enum Left, Right, Eof` then `spacing*: set[TokenSpacing]`

**Comment by ringabout** [comment]
Nice idea! I can do that refactoring later. It is a bug fix, after all.

**Pull request merged**
