### PR TITLE
Void as a "real" type

### PR DESCRIPTION
**Pull request by SirOlaf**
Make a bunch of new things possible

```nim
type G[T] = object
  x: T
if G[void]().x is void: # true
  echo "It's a void"

proc `$`(x: void): string = "()"
var x: void
echo x # '()'
echo typeof(x) # 'void'
```

Also an alternative to #20385 and #20603

### CODE REVIEW

**Comment by Varriount** [comment]
So, what is a void-typed variable? How is it represented in backend code?

**Comment by SirOlaf** [comment]
Should stay as tyVoid until it disappears in cgen

**Comment by beef331** [comment]
Does this have any repercussions on `offsetOf` or `sizeOf` magics?

**Comment by SirOlaf** [comment]
If I do it right by some miracle, it's just a compiletime construct, so doesn't do anything but let you compare types (or use them in weird ways). 
Best case I make it work, worst case it's out there so someone else might get inspired to try as well.

Edit:
addr for this says x and z are 8 bytes apart (64bit system), so it's like y doesn't exist while letting you "use" it
```nim
type H = object
    x: int
    y: void
    z: int
```

**Comment by Araq** [comment]
This is covered by https://github.com/nim-lang/RFCs/issues/437

However it says

>  "Void type" -- We should optimize away the "empty tuple" type in the backend and remove this feature.

But fixing it instead is the better solution surely.

**Comment by SirOlaf** [comment]
Probably a controversial thing, these all work. Void gets treated as so optional you can skip it entirely
```nim
proc foo(voidparam: void, intparam: int) = echo intparam
foo(intparam=2)
foo(55)
var x: void
foo(x, 22)
foo(x, intparam=33)
foo(voidparam=x, 44)
```

**Pull request closed without merging**
