### PR TITLE
Multy-bytes UTF-8 chars in JavaScript. Fixes #2917

### LINKED ISSUE #2917: Invalid UTF-8 strings in JavaScript
```
echo "Привет!"
```
will output in browser as 
```
ÐÑÐ¸Ð²ÐµÑ!
```
I think it's because it cant understand multi-bite encodings.

### PR DESCRIPTION
**Pull request by wirbi7**
Not so optimized as was.

### CODE REVIEW

**Comment by yglukhov** [comment]
This doesn't look right. Please keep in mind that Nim's representation of strings is an array of utf-8 bytes. So actually the opposite `toJSStr` should be fixed.

**Comment by wirbi7** [comment]
You right.

**Comment by yglukhov** [comment]
Nice! No new failed JS tests?
```sh
$ ./koch test c js
```

**Comment by Araq** [comment]
'toJSStr' is performance critical, so please special case the case when there are Ascii only strings. (Every char < 128).

**Comment by yglukhov** [comment]
@wirbi7, sorry for taking over. Thought you might need a hand, because of 3 days of silence.

**Comment by wirbi7** [comment]
Thank you!

**Pull request closed without merging**
