### PR TITLE
Fix #8538

### LINKED ISSUE #8538: Compiler SIGSEGV crash with closure on first build
Because I had some trouble with closure iterator in [zero_functional](https://github.com/zero-functional/zero-functional) I created a [test repository ](https://github.com/michael72/nim-compile-crash).

So when cloning the repo and building it with nim everything is fine.
Running the build with a "clean" nim - so to say a nim that is used for the first time - the build crashes with SIGSEGV.
This is what actually happens when using travis-ci here - nim sources are checked out, compiled and then my source code is compiled with the nim compiler.

The nim code leading to the bug is located [here](https://github.com/michael72/nim-compile-crash/edit/master/closure_iterator.nim)
A failed build log is [here](https://travis-ci.org/michael72/nim-compile-crash/builds/412241873)

I could maybe help, but I don't really know how to debug the nim compiler

### PR DESCRIPTION
**Pull request by michael72**
not sure how this would work without initializing seq

### CODE REVIEW

**Comment by BarelyMalicious** [comment]
Sorry if I am misunderstanding this fix but -
on Devel branch, initializing seqs and strings is not required, they are automatically initialized to empty. The issue you are getting is because [csources](https://github.com/nim-lang/csources) are for v0.18 and not devel. So the compiler built using those csources crashes and require this fix. 
But if you use `koch` in your travis then it works because it builds devel compiler using devel compiler and hence this issue is not present.

**Comment by Araq** [comment]
What @BarelyMalicious is true but if the tests are green I might still merge it as it makes bootstrapping more robust.

**Comment by michael72** [comment]
Oh - we can close this and the issue.
I wasn't aware that this is legal code now:

```nim
  var x: seq[int]
  x.add(1)
```

so when using initSeq additionally there would be some additional garbage collected, right?

Could someone point me to some documentation - is it only sequences that are now automatically created or is this a more general new feature?

**Comment by BarelyMalicious** [comment]
@michael72 
> Could someone point me to some documentation
  
No documentation yet I think, but some discussion on github issues and nim forum.

> is it only sequences that are now automatically created or is this a more general new feature?
  
Only for `string` and `seq`. AFAIK, they will internally use `nil` for optimization purposes but won't expose them to the users. So `nil`, and `isNil` will stop to compile for them. You do not need to explicitly initialize them now, they will automatically be initialized to empty seq and empty string (which may internally use `nil` state).

> so when using initSeq additionally there would be some additional garbage collected, right?
  
I don't think anything changes wrt this.

**Comment by michael72** [comment]
Ah OK - that's cool. I also found some "safeAdd" deprecation warnings which could have pointed me in the right direction (in system.nim)
But: good to know 😃

**Pull request closed without merging**
