### PR TITLE
Fixed negative enum values not getting stringified.

### PR DESCRIPTION
**Pull request by gmpreussner**

### CODE REVIEW

**Comment by Varriount** [comment]
Is it expected for the Travis build to fail?

**Comment by gmpreussner** [comment]
No idea. I can't repro it locally.

**Comment by gmpreussner** [comment]
Actually, I can. Hmm... I'll take a look.

**Comment by gmpreussner** [comment]
Definitely caused by my change. I have no idea what the problem is :(

**Pull request merged**
