### PR TITLE
fix #16033 nim js --gc:arc works and ignores --gc:arc

### LINKED ISSUE #16033: `nim js --gc:arc` gives bad error:  undeclared identifier: '+!'
Function `echo` outputs the wrong string.

### Example
```nim
# can be an empty file
```

### Current Output
nim js --gc:arc --skipparentcfg --skipusercfg main.nim
lib/system/arc.nim(84, 42) Error: undeclared identifier: '+!'

### Expected Output
* either make `--gc:arc` a noop (and code should work)
* or give error `--gc:arc` not supported with js backend

### Additional Information
devel 1.5.1 87d3e5331a7838aa255deca8a840c2080b5424ce

this (or fixing it by making it not work with js backend) would prevent things like this in testament:
```nim
discard """
  targets: "c cpp js"
  matrix: ";--gc:arc"
"""
```
but testament could also be made smart about this and skip `js --gc:arc` combination, although this isn't trivial to do it cleanly

### note
curiously, this works:
```nim
# main2.nim:
echo compileOption("gc", "arc")

# cmd:
nim r -b:js --gc:arc main2.nim
false
```
likewise with `nim js -r -b:js --gc:arc main2.nim`

but this doesn't:
```
nim js -r --gc:arc main2.nim
Error: undeclared identifier: '+!'
```

### PR DESCRIPTION
**Pull request by timotheecour**
fix #16033

### CODE REVIEW

**Comment by Araq** [comment]
This is madness. So you have a random choice of X flags in your config and then it bites with some other flags on the command line and the solution is to ignore some of these flags?

**Comment by timotheecour** [comment]
> This is madness

but you've merged https://github.com/nim-lang/Nim/pull/15059 recently to do exactly that, and there is already logic in place, except it doesnt' work reliably (see https://github.com/nim-lang/Nim/issues/16033#issuecomment-729879669), and didn't actually fix https://github.com/nim-lang/Nim/issues/14684; this PR works, eg with:
```
nim js --gc:arc main
nim r -b:js --gc:arc main
```

> So you have a random choice of X flags in your config and then it bites with some other flags on the command line and the solution is to ignore some of these flags?

that's basically what #14684 or #16033 is about, yes.
and also to make this work:
```nim
discard """
  targets: "c cpp js"
  matrix: ";--gc:arc"
"""
```
(workarounds are possible but awkward)

it's also consistent with `-d:useNimRtl` being ignored for js backend.
(I'd be ok with issuing a warning though)

**Comment by Araq** [comment]
> (I'd be ok with issuing a warning though)

That was what I was trying to get at. But ok, you're argued convincingly.

**Comment by Clyybber** [comment]
@timotheecour IMO the proper way to fix this is to set `conf.backend` earlier, is there a reason you chose this way instead?

**Pull request merged**
