### PR TITLE
Packaging fixes

### LINKED ISSUE #2128: Use standard compiler flags in build script
`build.sh` should honour standard flags, namely `LDFLAGS`, `CFLAGS` instead of its own custom forms. Also, they should accept changes from the environment, e.g.:

~~~~
[..]
CFLAGS="${CFLAGS:-} -w -O3 -fno-strict-aliasing"
LDFLAGS="${LDFLAGS:-}"
[..]
case $uos in
  *linux* ) 
    myos="linux" 
    LDFLAGS="$LDFLAGS -ldl -lm"
~~~~

This would make it easier for distributions to make tweaks such as https://wiki.debian.org/Hardening.

(This would also obsolete the need for `--extraBuildArgs`)

### PR DESCRIPTION
**Pull request by infinity0**
Fixes #2128 and #3113

### CODE REVIEW

**Comment by Araq** [comment]
Rather than SOURCE_DATE_EPOCH you should disable timestamps via  --timestamps:on|off or something like that. I don't think lying about the timestamp just to get reproducible builds is wise.

**Comment by infinity0** [comment]
Does `timestamps:off` make `CompileDate` reproducible? This information is counterproductive, since the build timestamp does not otherwise affect the results of the build (in *any* system, not just Nim). If some sort of "time" indicator is wanted, it is much better to use the *source timestamp*, which is precisely what `SOURCE_DATE_EPOCH` does. It is not a "lie"; it gives more accurate information than "compile timestamp".

**Comment by Araq** [comment]
Well the timestamp of the generated documentation is one thing, system.CompileDate another. If our users ask for system.CompileDate, they should get the compile-time not some Debian specific environment variable hack. What if my system has an unrelated SOURCE_DATE_EPOCH  environment variable?

**Comment by infinity0** [comment]
This is not a Debian-specific hack, it's a standard in-development that we're getting various tools, not just Nim, to implement for the purposes of making binaries reproducible. It's highly unlikely that your system will have a random variable lying around like this, but I could also have this feature enabled behind a command-line flag if you that's worth the effort.

The whole point is that "compile date" is not a useful concept to encode in any build result; it is the "source date" that one actually wants, in mostly practical circumstances. I'd be more than happy to extend the patch to rename `CompileDate` to `SourceDate`.

(In fact I am a little amazed that `koch boot` ever manages to reach convergence with this thing.)

**Comment by reactormonk** [comment]
I'd go for checking if `.git` exists, then use the git hash / git commit date and pass that information over to the compiler some way... maybe via files?

**Comment by infinity0** [comment]
Why files, why not just `SOURCE_DATE_EPOCH` the environment variable?

**Comment by reactormonk** [comment]
Because reading from env vars during compile time is messy. Maybe not anymore, you could check.

**Comment by infinity0** [comment]
I don't know why you say it's "messy", compared to any other approach, especially files. It's a very common thing to do, e.g. `make` populates all its variables first from the environment. if they're used but not defined anywhere in the file.

All the issues that are being brought up here, have already been thought through by us doing reproducible builds at Debian, and there is consensus that `SOURCE_DATE_EPOCH` is a good general mechanism for tools to adopt.

**Comment by Araq** [comment]
> All the issues that are being brought up here, have already been thought through by us doing reproducible builds at Debian, and there is consensus that SOURCE_DATE_EPOCH is a good general mechanism for tools to adopt.

We are not Debian nor is a meta argument like "there is consensus" convincing. There is also a consensus that C and C++ are good systems programming languages but I beg to differ and invented Nim.

**Comment by infinity0** [comment]
So what argument do you have for keeping `CompileDate` as in its current form, with no alternatives to make the build reproducible? Will you accept a patch to just get rid of it?

**Comment by Xe** [comment]
It is always possible for Debian to maintain its own distribution-specific patch.

**Comment by infinity0** [comment]
That is exactly what I'm already doing. However, reproducible builds is a useful general issue, of importance for security, that other distributions are also making efforts towards. So resolving this in Nim would benefit everyone.

I still haven't see any arguments towards keeping `CompileDate` in its current form. I welcome actual points, instead of sticking your heads in the sand ignoring this issue and passing it off (incorrectly) as something "Debian-specific".

**Comment by Xe** [comment]
I personally am all for your first commit in this pull request. That seems like a very sane thing to me.

However, the bigger problem here (in my view) is that you are trying to solve the "trusting trust" problem to an already self-hosting compiler* the wrong way. You're trying to introduce a badly documented *standard* to apply the wrong fix to the problem. GCC also has the `__DATE__` and `__TIME__` macros (the date and time when the file was compiled by GCC) predefined when compiling things, but that is a different topic.

The first commit seems fine, the other may need its own pull request, further investigation, or to remain downstream from the Nim compiler core. This would need the C sources to be regenerated.

* This means that you have to have a version of the Nim compiler to make a version of the Nim C sources to make a version of the Nim compiler. Frankly I'm surprised Debian is packaging Nim at all because of that.

**Comment by infinity0** [comment]
Why is it "the wrong fix to the wrong problem"? GCC has 

~~~~
       -Wdate-time
           Warn when macros "__TIME__", "__DATE__" or "__TIMESTAMP__" are encountered as they might prevent bit-wise-identical reproducible compilations.
~~~~

and we're also trying to get them to [adopt this standard](https://gcc.gnu.org/ml/gcc-patches/2015-06/msg02210.html).

Yes, I am aware of the issue with the csources. That is a separate problem from this pull request, and I brought it up in nim-lang/csources#12 a while ago.

**Comment by Araq** [comment]
> However, reproducible builds is a useful general issue, of importance for security, that other distributions are also making efforts towards. 

I disagree. In my opinion it has nothing to do with security. Your failure to put slightly more logic into ``memcmp`` has nothing to do with security.

Whether or not to use system.CompileTime should be left to the Nim programmers to decide. If we don't provide it, sooner rather than later people hack around the lack of it via ``staticExec`` anyway.

**Comment by infinity0** [comment]
Why should we put more special-case logic into a simple `memcmp` for reproducible builds? This issue is not special; if there should be "slightly more logic" for this, then this could be extended to many other things. Then, one will eventually a pointlessly complex tool to determine if two binaries are "identical", and one would have to write an even longer special standard for that. No, much better to remove it at the source.

The reason I am debating this issue, is to try to persuade you that `CompileDate` does more harm than good. There is no constructive reason to include it. Yes, it is for "Nim programmers to decide" since I have no moral or legal authority over you, but that does not mean it is a good idea! You have not offered any arguments on why it is a good idea; "I will do it because I can" is not a good argument. You can make that choice, for sure, but that is not a constructive attitude for open source projects to take.

We are trying to persuade people that no, *compile-time timestamps are really not a good idea*, including `__DATE__` and `__TIME__` in C code. It encodes no useful information, and the concept of `SOURCE_DATE_EPOCH` is always superior, even if you disagree with its implementation in this pull request. If Nim users hack around it, that is a cost they have to incur on their projects, and is a good incentive to not do it.

**Comment by Araq** [comment]
> Why should we put more special-case logic into a simple memcmp for reproducible builds? 

Because that's a single fix and so the superior solution over fixing each and every build tool or in our words your whole infrastructure and then *patronizing* everybody to adhere to your ideas.

I won't discuss it further.

**Comment by infinity0** [comment]
It's not a single fix - build tools don't generally offer a contract to say "we'll only put non-reproducible stuff here, on these byte positions", and we can't rely on the fact that you won't add other non-reproducible things to the output. There is no common standard for this. So, in any solution, we have to talk to upstream build tools about this issue. How could we not?

I've offered several lines of argument on why this approach is superior. This wording is not meant to be patronising, in the same way that you probably freely argue that Nim is superior to various other programming languages.

Why is this a "bad solution"? What other solution do you propose?

**Comment by ReneSac** [comment]
I think that SourceDate (plus maybe compiler version and options) is much more useful/informative/less misleading than CompileDate. Making this switch would be an improvement in itself. 

And it sure is nice bonus to be able to check for equality using any standard tool, like comparing sha1 hashes, w/o having to devise specific low-level hacks for every different program.

**Comment by Araq** [comment]
Well I don't like it and you failed to convince me.

**Comment by dom96** [comment]
@Araq not even the first commit?

**Pull request closed without merging**
