### PR TITLE
require kind and ident for gensym in macros

### PR DESCRIPTION
**Pull request by disruptek**
We'll see how much stuff this breaks.

### CODE REVIEW

**Comment by Araq** [comment]
Maybe ``gensym`` shouldn't have default arguments if they don't work? :-)

**Comment by disruptek** [comment]
That's the nature of my "fix".  It does identify some broken code.  Or, at least, code similar to the code I wrote that didn't work.  Of course, all of these cases fail to compile with my change; they are 100% broken now. :wink:

**Comment by Araq** [comment]
And now you broke array-mancer. The way to fix this is in ``of opcGenSym`` inside ``vm.nim``. However, it seems to have logic for the empty name already, I wonder what's going on here.

**Comment by timotheecour** [comment]
what bug is this fixing? this seems to work:
```nim
import macros
macro bar()=
  let a1 = genSym()
  let a2 = genSym()
  result = quote do:
    let `a1` = 1
    let `a2` = 2
    echo (`a1`, `a2`)
  echo result.repr
bar()
bar()
```

=>
```
let :tmp_36631049 = 1
let :tmp_36631050 = 2
echo (:tmp_36631049, :tmp_36631050)

let :tmp_36638216 = 1
let :tmp_36638217 = 2
echo (:tmp_36638216, :tmp_36638217)

```

(but perhaps changing `:tmp_36631049` to `gensym__36631049` would be less weird)

**Comment by disruptek** [comment]
Removing `"key"` and `"val"` from the following breaks the code despite no semantic change to the AST.

```nim
      var key = gensym(nskForVar, "key")             # loop var for key
      var val = gensym(nskForVar, "val")             # loop var for val
  
      var body = nnkStmtList.newNimNode              # make body of a loop
      body.add composeWithComma(result, js)          # maybe add a separator
      body.add adder.newCall(js, key.jason)          # "somekey" (json)
      body.add adder.newCall(js, json":")            # : (json)
      body.add adder.newCall(js, val.jason)          # someval (json)
  
      var loop = nnkForStmt.newNimNode               # make for loop
      loop.add key                                   # add key to the loop
      loop.add val                                   # add val to the loop
      loop.add newCall(ident"fieldPairs", o)         # object fieldPairs
      loop.add body                                  # loop body
```

https://github.com/disruptek/jason/blob/master/jason.nim#L129

**Pull request closed without merging**
