### PR TITLE
Revert sub-second randomize(). Fixes randomize for JS backend.

### LINKED ISSUE #9999: JS backend overflows when adding two int64s
```nim
import random, debugjs

proc foo(): int64 =
  var uwiheys = 1544890622000000000
  var y: range[0..999_999_999] = 66000000
  return uwiheys + y
console.log(foo())
```

(Replace debugjs with jsconsole)

Results in `Error: unhandled exception: over- or underflow [OverflowError]` because the JS code is using addInt instead of addInt64 (?).

This is also reproducible by trying to call ``randomize()`` in JS code and blocks me :(

Possibly related or duplicate of #6752.

### PR DESCRIPTION
**Pull request by dom96**
Fixes #9999.

### CODE REVIEW

**Comment by Araq** [comment]
This doesn't fix #9999 for me. For me it fails in your code, not in ``randomize``. Besides, the patch should look more like

```nim

  proc randomize*() {.benign.} =
    ## Initializes the random number generator with a "random"
    ## number, i.e. a tickcount. Note: Does not work for NimScript.
    when defined(js):
      let time = int64(times.epochTime() * 1_000_000_000)
      randomize(time)
    else:
      let now = times.getTime()
      randomize(convert(Seconds, Nanoseconds, now.toUnix) + now.nanosecond)
```

Because that nanosecond stuff was a bugfix too!

**Comment by dom96** [comment]
> For me it fails in your code, not in randomize

Of course it does. My code doesn't call ``randomize``, it shows the problem though.

But yeah, alright, I can put it in a when defined.

**Comment by Araq** [comment]
> Of course it does. My code doesn't call randomize, it shows the problem though.

I think I work too much. :P

**Comment by dom96** [comment]
Failures seem unrelated:

```
fatal: unable to access 'https://github.com/nim-lang/nimble.git/': Could not resolve host: github.com
```

**Pull request merged**
