### PR TITLE
fixed PHP variable generation

### PR DESCRIPTION
**Pull request by enthus1ast**
fixed PHP variable generation

### CODE REVIEW

**Comment by dom96** [comment]
The PHP backend is deprecated IIRC

**Comment by Araq** [comment]
@enthus1ast Do you use the PHP backend for anything? I would like to remove it.

**Comment by enthus1ast** [comment]
@Araq i do not use it currently. 
I wanted to hack a (very) little cms backend and it would be a good feature to just dump it to a php freehoster.

**Comment by Araq** [comment]
Sorry, the PHP backend is dead.

**Comment by treeform** [comment]
My version of PHP removal: #7606

**Pull request closed without merging**
