### PR TITLE
remove decades-deprecated Win32 API *A function support

### PR DESCRIPTION
**Pull request by tersec**

### CODE REVIEW

**Comment by slangmgh** [comment]
Why? Does the nim support unicode string natively like L"中文"?

**Comment by tersec** [comment]
https://github.com/nim-lang/Nim/blob/devel/changelogs/changelog_0_20_0.md
```
- The switch ``-d:useWinAnsi`` is not supported anymore.
```

More generally, https://learn.microsoft.com/en-us/windows/win32/learnwin32/working-with-strings notes
> Internally, the ANSI version translates the string to Unicode. The Windows headers also define a macro that resolves to the Unicode version when the preprocessor symbol `UNICODE` is defined or the ANSI version otherwise.
>
> ...
>
> New applications should always call the Unicode versions. Many world languages require Unicode. If you use ANSI strings, it will be impossible to localize your application. The ANSI versions are also less efficient, because the operating system must convert the ANSI strings to Unicode at run time. Depending on your preference, you can call the Unicode functions explicitly, such as **SetWindowTextW**, or use the macros. The example code on MSDN typically calls the macros, but the two forms are exactly equivalent. Most newer APIs in Windows have just a Unicode version, with no corresponding ANSI version.

It's not primarily a function of what Nim does, but rather of what Windows does. All the NT-based Windows versions have been natively Unicode, and Microsoft documents that they *A functions are at least sometimes just wrappers.

**Comment by ringabout** [comment]
Yeah, it should have been removed, but surprisingly `useWinAnsi` got many patches since 1.0.

**Comment by tersec** [comment]
> Yeah, it should have been removed, but surprisingly `useWinAnsi` got many patches since 1.0.

Well, and https://github.com/nim-lang/Nim/issues/21071 might indicate that it's finally truly "a dead switch". This PR implements that statement.

**Comment by slangmgh** [comment]
I don't think we should do so radically before the windows os deprecate ansi version API. There is still lots of program use ansi version, and most of all, I even don't know how to convert my program to unicode version, it is not only it may take my lots of time, but because of I don't konw how to do it.

**Comment by slangmgh** [comment]
If the PR is merged, I will not update the NIM anymore till I find way to use the unicode version finally.

**Comment by tersec** [comment]
This PR in itself eliminates only usage of the ANSI Win32 functions which Nim's Unicode mode already automatically converts arguments for:
```nim
  var wSrc = newWideCString(src)
```
for example. Any Windows functions you've declared yourself can still work, just using `char` rather than `WinChar` if you'd been doing so.

**Comment by slangmgh** [comment]
> This PR in itself eliminates only usage of the ANSI Win32 functions which Nim's Unicode mode already automatically converts arguments for:
> 
> ```nim
>   var wSrc = newWideCString(src)
> ```
> 
> for example. Any Windows functions you've declared yourself can still work, just using `char` rather than `WinChar` if you'd been doing so.

1. All the string const with DBCS need to wrapper with newWideCString.
2. string.len may not correct, so I don't know how to output them correctly.
3. strformat may not usable.
4. All the string from other source may need to convert to unicode.
5. There is some dll function use ansi string, and I need to convert the unicode back to ansi version.
6. Nim itself not use unicode string, so it's weird when DBCS combine with ascii.
7. etc

I really don't know how much bug will exist to convert ansi version to unicode version.

**Comment by slangmgh** [comment]
Window os native treat the char sequence as ANSI, rather than unicode in CJK version OS.

**Comment by tersec** [comment]
Other concerns aside, "string.len may not correct" and "strformat may not usable" don't relate directly to this PR, being pure Nim issues.

I'm not sure how "Nim itself not use unicode string, so it's weird when DBCS combine with ascii." relates either -- this isn't changing how Nim handles strings pervasively, it's changing how Nim interacts with the Win32 API. To the extent combining DBCS with ASCII was ever weird, it already is.

For the other non-"etc" ones, see comments already made.

**Comment by slangmgh** [comment]
> Other concerns aside, "string.len may not correct" and "strformat may not usable" don't relate directly to this PR, being pure Nim issues.
> 
> I'm not sure how "Nim itself not use unicode string, so it's weird when DBCS combine with ascii." relates either -- this isn't changing how Nim handles strings pervasively, it's changing how Nim interacts with the Win32 API. To the extent combining DBCS with ASCII was ever weird, it already is.
> 
> For the other non-"etc" ones, see comments already made.

Yes, your are right, it noly related Nim interacts with Win32 API, I had thought too much. :)

**Comment by slangmgh** [comment]
Sorry, the newWideCString(s) doesn't convert the DBCS char to UNICODE, it convert utf-8 string to UNICODE, so Nim's os module code doesn't support ANSI string, only support utf-8 string after remove the ansi mode.

**Comment by tersec** [comment]
> Sorry, the newWideCString(s) doesn't convert the DBCS char to UNICODE, it convert utf-8 string to UNICODE, so Nim's os module code doesn't support ANSI string, only support utf-8 string after remove the ansi mode.

https://nim-lang.org/docs/encodings.html#convert%2CEncodingConverter%2Cstring already handle this. On Windows, they use https://learn.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-multibytetowidechar which can do DBCS to Unicode conversions.

**Comment by slangmgh** [comment]
@tersec 
Need some work to do, but I think I could be fix them, thank you.

**Comment by Araq** [comment]
> Need some work to do, but I think I could be fix them, thank you.

Please tell me what you needed to fix.

**Comment by slangmgh** [comment]
> > Need some work to do, but I think I could be fix them, thank you.
> 
> Please tell me what you needed to fix.

Thank you. I need to fix something for my program, and it is already done. :)

**Pull request merged**
