### PR TITLE
Assert small efficiency improvement

### PR DESCRIPTION
**Pull request by cooldome**
Please ignore commits history, only file changes are relevant

Changelist adds unlikely() to if statement of assert, nothing else

### CODE REVIEW

**Comment by Yardanico** [comment]
well I'm not against this change, but I'm not sure if it will make any noticeable performance gain. but maybe it can be useful sometimes...

**Comment by cooldome** [comment]
Exactly, many cases it doesn't make a difference, but you care about performance and how optimal your generated assembly is. Definitely not going to cause any harm.

**Comment by Yardanico** [comment]
@cooldome well we can annotate whole stdlib with likely and unlikely then

**Comment by Araq** [comment]
Sorry, I don't like this improvement. ``assert`` is optimized away anyway.

**Comment by yglukhov** [comment]
As a side node, the compiler could automatically infer unlikeliness of branches with imminent raises.

**Pull request closed without merging**
