### PR TITLE
In typeinfo's doc comment, warned that rtti will evolve and suggested alternative approaches.

### PR DESCRIPTION
**Pull request by deansher**
See forum discussion: [pros/cons of dissecting types via getTypeInfo() vs getTypeImpl()?](https://forum.nim-lang.org/t/4622)

### CODE REVIEW

**Comment by timotheecour** [comment]
that typeinfo and RTTI can evolve is fine, but don't deprecate it.
I rely on typeinfo.nim for a lldb plugin that allows to use nim plugins during debugging time to help with debugging (and can do more stuff then nim-gdb python plugin)

**Comment by deansher** [comment]
In the forum post linked above, @Araq said "In the longer run I would like to deprecate runtime type information." Unless/until he firmly changes his mind, I think it's helpful to Nim programmers to document that this "may eventually be deprecated".

**Comment by timotheecour** [comment]
None of the alternatives you write in that PR would work.
During debug session, via a nim plugin, I convert an arbitrary expression (address+type provided by debugger) to a `typeinfo.Any`, from which I can call arbitrary code (eg pretty printing of nested data structures, among other)

This would obviously not work with macros or compile time type manipulation, since the pre-compiled nim debugger plugin has no knowledge of the types for the application I'm debugging.

**Comment by deansher** [comment]
Let me say that I have no personal opinion about the future of RTTI in Nim. I am just trying to contribute by -- every time I have to put significant effort into figuring something out -- PR'ing a documentation improvement for the next person. In this case, I figured out that RTTI may eventually be deprecated.

That said, I'm pretty sure `typeinfo.Any` isn't as different in capability from something like `macros.getTypeImpl` as you are hoping it is. I would be very interested if you show me I'm wrong, @timotheecour, but it appears to my inexpert reading that the (magic) implementation of
```
proc toAny[T](x: var T): Any
```
depends on compile-time information about `T` just as much as 
```
proc getTypeImpl(n: NimNode): NimNode
```
I'm not yet able to picture how your (hypothetical?) precompiled Nim debugger plugin has enough RTTI in Nim today to navigate through arbitrary data structures.

**Comment by timotheecour** [comment]
> That said, I'm pretty sure `typeinfo.Any` isn't as different in capability from something like `macros.getTypeImpl` as you are hoping it is
> [...] depends on compile-time information about `T` just as much as

no.

* `macros.getTypeImpl` depends on `NimNode` which exists only at CT (ie, at runtime for nim compiler)
* `typeinfo.Any` depends on `TNimType` which is available at RT (see `dumpHeapInstances` for an example that iterates over types on heap: that's done at RT), thanks to cgen serializing those types so they're available at RT (serialization done in `compiler/ccgtypes.nim` `genTypeInfoAuxBase`)

> I'm not yet able to picture how your (hypothetical?)

it's not hypothetical, I already implemented it and it works, and is 100% dependent on RTTI.

**Comment by deansher** [comment]
Moving this discussion back to the forum: [pros/cons of dissecting types via getTypeInfo() vs getTypeImpl()?](https://forum.nim-lang.org/t/4622)

**Comment by Araq** [comment]
I'm merging this now. It's not deprecated yet but it's good that the docs mention the possibility just to be on the safe side.

**Pull request merged**
