### PR TITLE
renderer letAux fix only for octal literal

### LINKED ISSUE #11131: Nim doc mangles signed octal literals
Generating examples with `nim doc` mangles octal signed integer literals that have highest bit set. It changes `0o377'i8` to `0o777'i8`, or `0o277'i8` to `0o677'i8`, or `0o177777'i16` to `0o777777'i16` when generating example files from `runnableExamples:` block and then fails test with `Error: number out of range: '0o777'i8'` or similar.

### Example
in file `sample.nim`:
```nim
proc someProc* =
  runnableExamples:
      let a = 0o377'i8
      doAssert a == 0o377'i8
  discard
```

### Current Output
in `runnableExamples/sample_examples1.nim`
```nim
block:
  let a = 0o777'i8
  doAssert a == 0o777'i8
```

### Expected Output
```nim
block:
  let a = 0o377'i8
  doAssert a == 0o377'i8
```

### Additional Information
This does not happen with unsigned integers. `0o377'u8` is transfered correctly as is.
```
$ nim -v
Nim Compiler Version 0.19.4 [MacOSX: amd64]
Compiled at 2019-02-01
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: b6d96cafc8bcad1f3d32f2910b25cd11a93f7751
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by ridho9**
Only uses the special fix from 69658ad for negative octal literals, fixes #11131 and #12287

### CODE REVIEW

**Comment by Araq** [comment]
Can we get a test case for this?

**Comment by ridho9** [comment]
I would like to create the test case, but I can't figure out where the testcase is supposed to be

**Comment by Araq** [comment]
``nimdoc/testproject``

**Comment by Clyybber** [comment]
Test failure is unrelated.

**Pull request merged**
