### PR TITLE
Fix issue with long wait for passed timer [bugfix]

### PR DESCRIPTION
**Pull request by PMunch**
This fixes a small issue where a timer that had been completed while
code executed would still wait for more events before being considered
completed. This would in some scenarios incur a 500ms delay to the
completion of a timer.

### CODE REVIEW

**Comment by PMunch** [comment]
Yeah I thought about that initially, but `adjustTimers` don't take the dispatcher as an argument and hence don't have easy access to the `timers` list. I could change it to take it as an argument if you want, or use the `getGlobalDispatcher` procedure (though it would probably be better to pass it in).

Sure, I can reuse the scenarios I used when creating this fix (but instead of echoing actually compare it to something):

``` Nim
import asyncdispatch, os, times

proc doubleSleep(hardSleep: int) {.async.} =
  await sleepAsync(100)
  sleep(hardSleep)

# The first sleepAsync completes after 50ms, then doubleSleep starts hard sleeping at 100ms, at 140ms it wakes up and the second sleepAsync fires at 150ms
var start = epochTime()
waitFor sleepAsync(50) and sleepAsync(150) and doubleSleep(40)
echo "Execution took ", (epochTime() - start)*1000, "ms"

# The first sleepAsync completes after 50ms, then doubleSleep starts hard sleeping at 100ms, at 160ms it wakes up and the second sleepAsync is delayed until 660ms for unknown reasons
start = epochTime()
waitFor sleepAsync(50) and sleepAsync(150) and doubleSleep(60)
echo "Execution took ", (epochTime() - start)*1000, "ms"

# The first sleepAsync completes after 50ms, then doubleSleep starts hard sleeping at 100ms, at 140ms it wakes up and the second sleepAsync fires at 150ms and the last sleepAsync fires at 200ms
start = epochTime()
waitFor sleepAsync(50) and sleepAsync(150) and doubleSleep(40) and sleepAsync(200)
echo "Execution took ", (epochTime() - start)*1000, "ms"

# The first sleepAsync completes after 50ms, then doubleSleep starts hard sleeping at 100ms, at 160ms it wakes up the second sleepAsync and the last sleepAsync both fires at 200ms (bit hard to see from this example, but that is what happens)
start = epochTime()
waitFor sleepAsync(50) and sleepAsync(150) and doubleSleep(60) and sleepAsync(200)
echo "Execution took ", (epochTime() - start)*1000, "ms"

# The first sleepAsync completes after 50ms, then doubleSleep starts hard sleeping at 100ms, at 140ms it wakes up and the second sleepAsync fires at 150ms, this completes the first block and the last sleepAsync is not waited for
start = epochTime()
waitFor (sleepAsync(50) and sleepAsync(150) and doubleSleep(40)) or sleepAsync(700)
echo "Execution took ", (epochTime() - start)*1000, "ms"

# The first sleepAsync completes after 50ms, then doubleSleep starts hard sleeping at 100ms, at 140ms it wakes up and the second sleepAsync fires at 550ms for some unknown reason, this completes the first block and the last sleepAsync is not waited for
start = epochTime()
waitFor (sleepAsync(50) and sleepAsync(150) and doubleSleep(60)) or sleepAsync(700)
echo "Execution took ", (epochTime() - start)*1000, "ms"
```

**Comment by dom96** [comment]
Yes, please pass the dispatcher to that function.

**Comment by PMunch** [comment]
There refactored it into `adjustTimeouts` and added a test case

**Comment by dom96** [comment]
This implementation is better, but the test is far too flaky. Maybe there is a way to test for this without measuring how much time the operations took?

**Comment by PMunch** [comment]
Yeah testing like that isn't the best.. But I can't think of another way of doing it.

**Pull request merged**
