### PR TITLE
Add an error message when creating a thread from a ref type

### PR DESCRIPTION
**Pull request by vanyle**
This PR is based on this conversation: https://forum.nim-lang.org/t/11374

The idea is to detect if the param passed to `createThread` is a ref and to produce an error if that's the case.

Feedback is welcome! I'm trying to better understand threading in Nim as I feel like documentation on the topic is lacking.

### CODE REVIEW

**Comment by vanyle** [comment]
Closing this PR as this looks impossible as `thread` is imported by `system` and `macros` needs system.
After some trials, I think the cycle cannot be broken, even by putting `NimNode` into its own file as some "magic" happens and I'm getting `..\..\lib\std\typedthreads.nim(252, 18) Error: system module needs: NimNode`

**Comment by beef331** [comment]
Whilst you did use a macro you can just do `when TArg is ref` or even `[TArg: not ref]` in the generic parameters. Whether that'd be an accepted PR is another thing I cannot answer.

**Comment by vanyle** [comment]
My goal was to have something that would recursively check that the type contains no `ref` with this macro being the first simple step. But you are right, simply testing that the top type is not a `ref` is better than nothing.

**Comment by beef331** [comment]
This does not work on objects that contain a `distinct ref T` but here it's done two ways without macros(nor object variant support):
```nim
proc containsRef(typ: typedesc): bool =
  typ is ref

proc containsRef(typ: typedesc[object or tuple]): bool =
  for field in default(typ).fields:
    if containsRef(typeof(field)):
      return true

    
when not defined(conceptMethod):
  proc createThrd(val: auto) =
    when typeof(val).containsRef:
      {.error: "Supplied a type that contains a ref".}
      
  createThrd (new int,)
else:
  type NoRefs = concept n
    not containsRef(n)
  proc createThrd(val: NoRefs) = discard
  createThrd (new int,)
```

**Comment by vanyle** [comment]
@beef331 Can I message you? I have a question about this file specifically and I'm getting a weird type error when:
1. Renaming `createThread` to `createThreadImpl` (for the different platform implementations)
2. Calling `createThreadImpl` from a newly created `createThread` function.

**Pull request closed without merging**
