### PR TITLE
fix not flushing stdout in `MSYS`

### PR DESCRIPTION
**Pull request by hamidb80**
discussed here https://forum.nim-lang.org/t/8975

### CODE REVIEW

**Comment by drkameleon** [comment]
Thanks! Looks fine! 😉 (I've already made the change "internally")

**Comment by ringabout** [comment]
Hello @hamidb80 , why is it added to the 1.6 branch instead of devel branch?

**Comment by hamidb80** [comment]
> why is it added to the 1.6 branch instead of devel branch?

Hey, I just click the link `source` in the documentation and forked the repo.
next time I'll be more careful. 
Sorry

**Comment by hamidb80** [comment]
should I do it on `devel` branch again?

**Comment by ringabout** [comment]
yeah

**Pull request merged**
