### PR TITLE
[Vote, please] Elapsed time for unittests and/or bench template

### PR DESCRIPTION
**Pull request by data-man**
## Task list
- [x] Elapsed time for a tests & suites
- [ ] Overall elapsed time

### CODE REVIEW

**Comment by Araq** [comment]
Looks good to me but how come no tests had to adapted due to the changed output?

**Comment by data-man** [comment]
I'm not sure what I understood correctly, but what tests should be adapted?

**Comment by data-man** [comment]
The environment variable "NIMTEST_NO_BENCH" added.

**Comment by data-man** [comment]
I want to implement a MarkdownOutputFormatter (or RstOutputFormatter?) with beautiful headers, tables, syntax highlighting and so on. :)
This will be useful for posting messages on the forum and on the Issues.
Have any thoughts and suggestions?

**Comment by FedericoCeratto** [comment]
@data-man Some ideas in #5114
Also, FYI as the unittest module is not aware of multiple test files, I'm implementing output gathering and reporting in https://github.com/FedericoCeratto/nim-testrunner

**Comment by FedericoCeratto** [comment]
Some other unittest changes in #6725

**Comment by couven92** [comment]
I am doing HTML output for testament (PR #6667) and the result page looks like this: http://uit-no-fra006.azurewebsites.net/testresults.html

**Comment by data-man** [comment]
Ready to review.

----
I made a calculation of a passed time by using addQuitProc and a global variable, but this is so ugly that I removed it.

**Comment by dom96** [comment]
So I think that a better way of implementing this would be to offer a ``timeIt`` template in the unittest module instead of integrating the timings deep into unittest.

Something like this:

```nim
test "essential truths":
    timeIt:
      foobar()
```

**Comment by data-man** [comment]
A hybrid of unittests and NimBench?
Then it's better to have a new benchmark.nim module based on unittest.nim.

**Comment by data-man** [comment]
Some ideas:

 - I'll add a new bench template (but I do not promise it will be soon)
 - A new environment variable NIMTEST_BENCH_HLAYOUT will be added
 - If this variable is not specified, the results of the benchmarks will look like this:

| suite name | bench name | relative | time/iter | iters/s |
|--|--|--|--|--|
|Suite 1| | |15.00ns|300.0M|
|  |Bench 1|100.00%|10.0ns|100.0M|
|  |Bench 2|200.00%|5.0ns|200.0M|
|Suite 2| | |12.5ns|500.0M|
|  |Bench 3|100.00%|10.0ns|100.0M|
|  |Bench 4|400.00%|2.5ns|400.0M|
|All  | | |27.5ns|800.0M|

- If this variable is specified, the results of the benchmarks will look like this:

| Name |  | Bench 1 | Bench 2 | Bench 3 | Bench 4 |
|--|--|--|--|--|--|
||Suite 1| | | | | 
|relative||100.00%|200.00%|||
|time/iter|15.00ns|10.0ns|5.0ns||||
|iters/s|300.0M|100.0M|200.0M|||
||Suite 2| | | | | 
|relative|| | |100.00%|400.00%|
|time/iter|12.5ns| ||10.0ns|2.5ns|
|iters/s|500.0M| | |100.0M|400.0M|

**Comment by data-man** [comment]
## №1 Close this PR and add a bench template ##

**Comment by data-man** [comment]
## №2 Merge this PR and add a bench template ##

**Comment by data-man** [comment]
## №3 Add the new benchmark module ##

**Comment by data-man** [comment]
## №4 None of this is needed ##

**Pull request closed without merging**
