### PR TITLE
Fixes #3186

### LINKED ISSUE #3186: Defer statement at the end of a block produces ICE
```nim
block:
    defer:
        echo "hi"
```
```
test1.nim(2, 5) Error: internal error: expr(nkDefer); unknown node kind
```

### PR DESCRIPTION
**Pull request by yglukhov**

### CODE REVIEW

**Comment by Araq** [comment]
Meh, I don't like 'var PNode' solutions. Plus it's not obvious why this fixes the bug...

**Comment by Araq** [comment]
The real question is why it worked before, 'defer' was always required to be in a stmt list.

**Comment by yglukhov** [comment]
semStmtList reduces result to single child:
https://github.com/nim-lang/Nim/blob/devel/compiler/semstmts.nim#L1443
Should that be fixed?

**Comment by Araq** [comment]
Yeah, don't eliminate it when the content is a nkDefer.

**Comment by yglukhov** [comment]
Done

**Pull request merged**
