### PR TITLE
produce better lineinfo for qualified symbols

### PR DESCRIPTION
**Pull request by alaviss**
Previously, nimsuggest highlighter will erronously highlight qualified
symbols starting from the dot like this (the highlighted part is marked
below):

```
system.echo()
      ^~~~
```

This commit fixes that.

### CODE REVIEW

**Comment by Araq** [comment]
Seems arbitrary, technically speaking the dot is correct, right?

**Comment by alaviss** [comment]
This PR introduces the following changes:

- Template calls within template now introduces it's own instantiation context, for example, this code:

   ```nim
   template getInfo(): untyped =
     const ins = instantiationInfo()
     ins
   
   template getInstInfo(): untyped = getInfo()
   
   echo getInstInfo().line
   ```

   Previously produces:

         7 # This is the `echo` line

   Now produces:

         5 # This is the `getInfo()` line in `getInstInfo()` template

   I'm unsure if this change would be desirable. /cc @Araq 

- Templates now got their line info at the beginning of the identifier instead of the end, for example:

   ```nim
   template getInfo(): untyped = instantiationInfo()

   echo getInfo().column
   ```

   Previously produces:

         12 # echo getInfo().column
            #            ^

   Now produces:

         5 # echo getInfo().column
           #      ^

**Comment by alaviss** [comment]
> > I'm unsure if this change would be desirable.
> 
> `instantiationInfo()` has an optional parameter to influence this behaviour. But with your variant there is no possibility to access line 7 anymore. Please don't change it.

It's still possible, you just have to call `instantiationInfo(-2)` instead. `assert()` relies on this and still work fine after this change with minor tweaks.

**Comment by Araq** [comment]
Well these "Minor tweaks" are a breaking change we need to be careful about.

**Comment by alaviss** [comment]
The "Minor tweaks" was literally adding `-1` to the current index of `instantiationInfo` call, see https://github.com/nim-lang/Nim/pull/10361/commits/2540c5a54d7c2f0f6ccd6e29287d5e3848a9ce85#diff-5cfdfeab79c2d2b7bbc78af7060c38c3.

But yes, this is certainly a breaking change. I'll split this PR into smaller pieces for faster upstreaming if needed.

**Pull request closed without merging**
