### PR TITLE
fix #9376: old changelogs should be kept instead of erased

### LINKED ISSUE #9376: old changelogs should be kept instead of erased
/cc @araq in 7f81519f4114dbb49fcd68ca2361920bf374fb1c the changelog for v0.19.X was removed to start the new changelog for v0.20.X; it's useful to keep around these old changelogs and they should be in the git repo, not somewhere else

# proposal

* changelog.md always points to latest changelog (as is already the case)
* everytime a new version is tagged, `git mv changelog.md changelog.version.md' (eg: changelog.0.19.md) ; optionally, in a changelog subdirectory 
* introduce back older changelogs using above naming scheme

### PR DESCRIPTION
**Pull request by timotheecour**
* fix https://github.com/nim-lang/Nim/issues/9376

* commands used to revive old changelogs:
  - git show 86c3832201d5705463dfd7f33736385402cabdfc^:changelog.md > changelogs/changelog_0_18_1.md
  - git show 7f81519f4114dbb49fcd68ca2361920bf374fb1c^:changelog.md > changelogs/changelog_0_19_0.md
  (versions older than that were not in git)

* Also added links to changelogs (including older ones) stored in https://github.com/nim-lang/website

### CODE REVIEW

**Comment by dom96** [comment]
Really? A changelogs directory?

Why don't we just keep it all in one file? That's how a traditional changelog works.

**Comment by timotheecour** [comment]
> Why don't we just keep it all in one file? That's how a traditional changelog works.

https://github.com/nim-lang/Nim/issues/9376#issuecomment-429679310

**Comment by dom96** [comment]
And why do we need this duplication? Why is it not enough to have them on the website?

**Comment by timotheecour** [comment]
I don't like this duplication either ; ideally the website would pull the changelogs from nim repo instead of other way around. it makes more sense this way since changelogs are part of nim repo (and are changed alongside other code changes in PR's) ; the problem (until now) was that they got deleted at every release instead of doing as proposed here.

**Comment by dom96** [comment]
Why is that a problem?

**Comment by timotheecour** [comment]
having changelog kept in the place where it originated (Nim git repo) instead of moved over is convenient when you're grepping through the repo, eg if you grep/nimgrep for `future` now, you'll see it 
```nim
changelogs/changelog_0_19_0.md:5:23:- The stdlib module ``future`` has been renamed to ``sugar``.
```
instead of having it search grep through another repo

**Pull request merged**
