### PR TITLE
deprecates `newSeqUninitialized` replaced by `newSeqUninit`

### PR DESCRIPTION
**Pull request by ringabout**
ref #19727
closes #22586

https://github.com/nim-lang/Nim/issues/22554 needs it to move on. `newSeqUnsafe` can be introduced later.

### CODE REVIEW

**Comment by ringabout** [comment]
@mratsim Hi, https://github.com/mratsim/Arraymancer/blob/875ee6bf595a220a08827adeaee8a89722d2c8f2/src/arraymancer/autograd/autograd_common.nim#L247 gives

> Error: The type T cannot contain managed memory or have destructors

Would you mind renaming the private function `newSeqUninit` instead?

It seems that https://github.com/mratsim/Arraymancer/blob/875ee6bf595a220a08827adeaee8a89722d2c8f2/src/arraymancer/laser/tensor/datatypes.nim#L37 uses refs, which is not supported by `newSeqUninit`.

**Comment by ringabout** [comment]
It's ready for review

**Comment by arnetheduck** [comment]
why not a separate module? this would avoid breaking code that has a proc named `newSeqUninit` already because they would now have to `import sequtils` (or whatever) to create the name conflict (ie no existing code would break).

**Comment by arnetheduck** [comment]
fwiw, this is how C/C++ does it - they require the use of `#include <complex>` for example to access the `complex` "keyword", otherwise you have to use `_Complex` which is reserved from the beginning, in order not to conflict with "user code" - nim could adopt this same strategy and document it in the manual so that in the future, we have a "simple" and regular way to add things to stdlib without causing name conflicts.

**Comment by Araq** [comment]
Well adding it to sequtils.nim would also break things and a new module seems rather excessive.

**Comment by arnetheduck** [comment]
> a new module seems rather excessive.

I wouldn't say so, this is a fringe use case that we don't want to encourage anyway - I imagine there exists a future where the compiler can detect cases where uninit is possible and not require the separate function at all - I think of `newSeqUninit` as a manual workaround until then.

**Pull request merged**
