### PR TITLE
niminst - emulates multi-threaded csource construction on Windows

### PR DESCRIPTION
**Pull request by rockcavera**
The modifications emulate a multi-threaded build according to the processor running it.

Here the current batch script builds the csource at: 101.53s

The new script I built:
```
 ------------------------------
| nº threads | Time (s) |  X   |
|------------------------------|
| 1          | 126.29   | 1.24 |
| 2          | 68.00    | 0.67 |
| 3          | 54.42    | 0.54 |
| 4          | 48.90    | 0.48 |
| 5          | 43.94    | 0.43 |
| 6          | 41.37    | 0.41 |
| 7          | 38.81    | 0.38 |
| 8          | 37.62    | 0.37 |
| 16         | 35.88    | 0.35 |
 ------------------------------
X is the fraction with respect to the current script
```

My settings are:
Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz x64
Microsoft Windows 10 Pro 64 bits build 19043 (10.0.19043)
gcc version 11.2.0 (MinGW-W64 x86_64-posix-seh, built by Brecht Sanders)

It can be noted that the performance is better whenever the build takes place with more than one thread.

I tested this new batch script on Windows 10 and Windows XP.

### CODE REVIEW

**Comment by Varriount** [comment]
I'm unsure as to whether this is really worth the additional complexity. Compiling csources is something that is usually done only once, and even then, only by compiler developers.

**Comment by Araq** [comment]
Sorry, rejected. Hardly anybody builds csources anyway, not even compiler developers.

**Comment by arnetheduck** [comment]
We build `csources` in CI for all builds - this is how we get a nim compiler into the CI environment where only a C compiler exists (the result is then cached, but that's a separate story) - we do so also because we need to precisely control the version of Nim - it's rare that more than one Nim version at any given moment is able to compile our project due to breaking changes between versions (including point releases).

**Comment by Araq** [comment]
To build C sources you need a working Nim so I don't understand. And why not build Nim the way that's actually officially supported? Version 1.2, 1.4, 1.6, they all build from csources_v1, at least that's how we build these versions for everybody else to download.

**Comment by arnetheduck** [comment]
> To build C sources you need a working Nim so I don't understand.

I might have missed something here, but generally, we download `csources_v1`, use that to build a bootstrap `nim`, then build whatever version of nim we want to build with that bootstrap nim - this doesn't rely on a preexisting nim installation or "official" binary  - this way, we can build our version of Nim on whatever platform we want that has a C compiler - doing the first step with all cores generally speeds up the process quite a bit (https://github.com/status-im/nimbus-build-system/blob/master/scripts/build_nim.sh#L147)

**Comment by Araq** [comment]
This patch is about speeding up the building of csources_v1 so it should have no impact on your CIs whatsoever.

**Pull request closed without merging**
