### PR TITLE
json serialization of tuples

### PR DESCRIPTION
**Pull request by onqtam**
we already have `initFromJson[T: object|tuple]`

### CODE REVIEW

**Comment by planetis-m** [comment]
I think the reason for not having them is that json objects are unordered. At least unnamed tuples should be [disallowed](https://github.com/nim-lang/Nim/blob/devel/lib/pure/json.nim#L1102)

**Comment by onqtam** [comment]
> I think the reason for not having them is that json objects are unordered.

I think that's precisely why even for objects (and not just tuples) we serialize/deserialize based on the key - we iterate over all the fields and we don't assume any order - we can't.

**Comment by b3liever** [comment]
ok

**Comment by onqtam** [comment]
I might be wrong - I haven't inspected the deserialization path in detail - actually I'm using my own deserialization and just wanted to reuse the serialization (`%`) from `json.nim`.

**Comment by timotheecour** [comment]
See jsonutils

**Comment by dom96** [comment]
Getting "{field1: 42, field2: 55}" for `%((42, 55))` may be a bit confusing. But I don't personally have strong feelings either way.

**Comment by timotheecour** [comment]
again, see std/jsonutils and how it handles named vs unnamed tuples

**Comment by onqtam** [comment]
sorry for the inactivity on this, I'll come back to it at some point - it isn't urgent in any way.

**Comment by timotheecour** [comment]
instead, this PR should simply revert https://github.com/nim-lang/Nim/commit/f8e720fda90fcd3cabedc1adf055d14d69df82ba as was argued here: https://github.com/nim-lang/Nim/pull/15420#issuecomment-749705087 and for consistency with jsonutils

**Pull request closed without merging**
