### PR TITLE
[WIP] Deploy devel docs at https://nim-lang.github.io/Nim/devel

### PR DESCRIPTION
**Pull request by kaushalmodi**
This fixes the dochack.js location too.

Fixes https://github.com/nim-lang/Nim/issues/9104.

### CODE REVIEW

**Comment by kaushalmodi** [comment]
Don't merge this if based on this comment: https://github.com/nim-lang/Nim/issues/9104#issuecomment-425508998, if the decision is to change `../dochack.js` to `dochack.js` i.e. copy the dochack.js to `/doc/html/.` instead of to `/doc/.`.

**Comment by Araq** [comment]
I want to keep ``../dochack.js`` but don't mind much either way.

**Comment by kaushalmodi** [comment]
> but don't mind much either way.

So OK from you to switch to `dochack.js`. That will prevent unnecessary dir nesting, and make the generated docs more portable.. need to copy just one dir instead of "one dir plus dochack.js in parent dir".

**Comment by kaushalmodi** [comment]
https://github.com/nim-lang/Nim/pull/9110 supercedes this PR.

**Pull request closed without merging**
