### PR TITLE
Export trace member of exception type to allow custom stack trace entries

### PR DESCRIPTION
**Pull request by zevv**
Add the proc insertStackTraceEntry() to allow code to insert custom stack trace entries in an exception.

My particular use case is providing a better user experience for NPeg, but this can be of value for any code that adds flow control on top of the Nim language.

For the NPeg use case: when an exception is raised during the parsing of an grammar, the stack trace is augmented with the call stack frames of the NPeg parser virtual machine, giving the user a nice overview of where in the grammar the exception happened. 

The resulting stack trace looks something like this: the last 5 entries in the trace are added by Npeg and refer to the grammar rules in which the exception happened:

```
/home/ico/sandbox/prjs/npeg/main.nim(30) main
/home/ico/sandbox/prjs/npeg/main.nim(27) flap
/home/ico/sandbox/prjs/npeg/src/npeg.nim(135) match
/home/ico/sandbox/prjs/npeg/src/npeg/patt.nim(90) fn`gensym46
/home/ico/sandbox/prjs/npeg/src/npeg/patt.nim(90) fn
/home/ico/sandbox/prjs/npeg/main.nim(11) nodes <- *(node * (' ' | !1))
/home/ico/sandbox/prjs/npeg/main.nim(12) node <- extraWord | word
/home/ico/sandbox/prjs/npeg/main.nim(13) extraWord <- word * extra * dash
/home/ico/sandbox/prjs/npeg/main.nim(19) extra <- number | dot
/home/ico/sandbox/prjs/npeg/main.nim(20) number <- +Digit
```

### CODE REVIEW

**Comment by Araq** [comment]
Maybe instead make the `trace` field public in system.nim. But I'm not sure.

**Comment by zevv** [comment]
Making `trace` public is fine with me too, but I think this might be slightly nicer since it ends up in the documentation and makes things more explicit.

**Comment by Araq** [comment]
Well you insert into the stack trace, others might want to remove entries.

**Comment by zevv** [comment]
Fair enough; PR updated to export trace instead.

**Pull request merged**
