### PR TITLE
fix https://github.com/dom96/choosenim/issues/256 WSL CRLF

### LINKED ISSUE #256: `choosenim devel --latest` fails build
Hello,

I saw `choosenim devel --build` fail on a Travis CI run, and then was also able to reproduce that same issue on Windows 10.

[Here's the Travis failure](https://travis-ci.org/github/kaushalmodi/aoc2019/jobs/772325553).

```
... /home/travis/.choosenim/toolchains/nim-#devel/compiler/semtypes.nim(259, 78) Error: undeclared field: 'isNaN' for type system.BiggestFloat [declared in /home/travis/.choosenim/toolchains/nim-#devel/lib/system.nim(1397, 3)] 
... FAILURE
```

### PR DESCRIPTION
**Pull request by timotheecour**
fix https://github.com/dom96/choosenim/issues/256 pending confirmation by @dom96

### CODE REVIEW

**Comment by dom96** [comment]
With this I'm getting:

```
$ cd /tmp
$ git clone https://github.com/timotheecour/Nim.git
$ cd Nim
$ git checkout -b timotheecour-pr_fix_crlf_WSL_bash devel
$ git pull https://github.com/timotheecour/Nim.git pr_fix_crlf_WSL_bash
$ sh build_all.sh

 csources_v1hub.com/nim-lang/csources_v1.git
warning: Could not find remote branch master? to clone.
fatal: Remote branch master? not found in upstream origin
```

**Comment by timotheecour** [comment]
@dom96 see last commit; please retry

**Comment by timotheecour** [comment]
ping @dom96

**Review by dom96 — APPROVED** [review]
Just tested, works, thanks!

**Pull request merged**
