### PR TITLE
.github/workflows: new CI pipeline

### PR DESCRIPTION
**Pull request by alaviss**
As Azure Pipelines went offline, this will be our (temporary?)
replacement. This pipeline covers everything that Azure Pipelines does.

Refs #13653

EDIT: Since I've got a working walkaround for Azure Pipelines (#13657), I've disabled this CI pipeline, it can be re-enabled at any time by removing the `.disabled` suffix from the file name.

### CODE REVIEW

**Comment by alaviss** [comment]
Looks like this won't work until we merge it, so for now you can track this pipeline in my fork: https://github.com/alaviss/Nim/actions

**Comment by alaviss** [comment]
@Araq need your attention on this: https://github.com/alaviss/Nim/runs/509594178?check_suite_focus=true#step:13:61

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/pull/13657 seems to supersede this PR right?
However, this PR seems useful to merge even then, in case this issue happens again, maybe add something to disable it with a doc comment on how to re-enable it?

**Comment by ghost** [comment]
master + PRs are failing with the new CI.

**Pull request merged**
