### PR TITLE
Add `random` Nimble package to stdlib.

### PR DESCRIPTION
**Pull request by dom96**
**Please do not merge this yet**

After seeing that the current ``random`` module is effectively broken (or its logic is at least non-intuitive) I decided to create this. This shouldn't be merged yet (or perhaps not at all), I want to see what everyone thinks.

This PR adds @BlaXpirit's excellent random module to the standard library. This is a straight copy and paste job, it remains a Nimble package and the compiler should treat it as such. This was accomplished by adding ``$lib/packages`` to the compiler's Nimble path. It's a simple way to get it into the standard library and gives us great flexibility.

There are many options with this approach, and we can discuss other approaches as well. Mainly I just want to know what everyone else thinks. I'm hoping that most (if not all) are happy with adding this package into the standard library, the only question is how.

Some questions in regards to this approach:

* What should the role of @BlaXpirit's repo be?
  * If the approach I took (copy and pasting the code) should remain, then I think @BlaXpirit's repo should be removed or at least deprecated in some way (via a big warning in the readme or something).
  * Otherwise, we could maybe add a submodule and allow @BlaXpirit's repo to remain separate. (This may simplify development of the random package, but may otherwise be rather confusing).
* Should ``$lib/packages`` be the canonical global Nimble package path? (I see that ``/opt/nimble/pkgs`` is in the config, perhaps it should be removed in favour of this?).
* Should the ``docutils`` package which is also in the ``packages`` directory be turned into a Nimble package for consistency? not turning it into a Nimble package may in fact break it(!).

@BlaXpirit I recall that you wanted this package in the standard library, so I hope you won't mind me taking the initiative and creating this PR.

Please let me know what you guys think.

### Tasks before this can be merged

- [ ] Add documentation from ``random``'s readme into the ``random.nim`` module.

### CODE REVIEW

**Comment by Araq** [comment]
No, for several reasons:

1. The current random module was designed to be compatible with what ``math.nim`` used to offer while at the same time to not depend on the underlying C library. A name clash with the other random out there is unfortunate but needs perhaps a general solution. Replacing the current random module with a totally different random module is insane. No deprecation path, no nothing.
2. BlaXpirit's code is larger and I am not sure we will be able to maintain it.
3. The stdlib should become smaller, not larger.

**Comment by dom96** [comment]
Ahh, so a complete "No" to this idea. Pity, I thought this is what we wanted in the long run.

**Comment by BlaXpirit** [comment]
The standard library surely needs a solid base for random number generation but I don't feel confident about this implementation. Hardly maintainable and has some known problems.

I've actually tried [reworking](https://github.com/BlaXpirit/nim-random/compare/dev) it (to copy the improved behavior that was merged to another language's stdlib) which would consequently allow it to be shrunk to a manageable size, but Nim just doesn't cooperate with me :/

**Comment by vegansk** [comment]
> The stdlib should become smaller, not larger.

@Araq, I'm totally disagreed with you, when it's about such standard things. Here is the example, there ara two libraries in scala implementing almost the same things: scalaz and cats. And what do we get, two incompatible implementation of typeclasses, monads, etc. Ok, I choose scalaz for my project for example. Then I add some external library to my project, but wait. It uses cats. What should I do: find another implementation or write the converters from/to scalaz <-> cats? And it's all about unwillingness to add this damned typeclasses, monads, etc to scala's standard library.

**Comment by endragor** [comment]
I think the current random module is unusable for something beyond a toy project, so having a better standard random library is a must. The minimal requirements from the top of my head are:

1. Use of size-specific types, so that you know how many random bits you're getting.
2. Support for polymorphism so that a code that uses random can switch between random types easily if needed.
3. A generic version generating value of a type depending on its size.
4. A quick and low-memory option suitable for basic use cases that don't require security (some variation of XorShift would do).
5. Cryptographically secure implementation (I recently implemented [ISAAC in pure Nim](https://github.com/pragmagic/isaac), it should do).
6. convenience procs for basic random use cases: selecting from collection, shuffling, etc.
7. (optional) built-in way to obtain thread-local secure random instance. This is a common use-case in multi-threaded apps.
8. (optional) urandom wrapper for getting true random values from OS. It should be used internally to seed secure random instance, but I'm not sure if it should be exposed.

@BlaXpirit's lib conforms to most of these, but perhaps can be trimmed. public-API-wise there shouldn't be too much exposed to the user, and user shouldn't probably know about exact kinds of random being used. The API should just provide a way to create a random that's fast and simple, and a secure version. Then there are procs that generate values of certain types from any random instance.

**Comment by Araq** [comment]
Closing. We need to assimilate a battle tested Nimble package once we have one.

**Comment by dom96** [comment]
Isn't that what @oprypin's package is?

**Comment by andreaferretti** [comment]
Yes, especially if everyone agrees on the API. @oprypin package exposes RNG as a concept, which is nice because everyone can expand support for other random number generators - such as [Isaac](https://github.com/pragmagic/isaac)

**Comment by oprypin** [comment]
The library has multiple outstanding implementation issues

**Comment by andreaferretti** [comment]
@oprypin Thank you for letting us know. Could you go in more detail on what you think are the issues?

**Pull request closed without merging**
