### PR TITLE
make global variables static when possible

### PR DESCRIPTION
**Pull request by cooldome**
Attempt to address multiple complains that top level code is significantly slower then the same code put in proc

### CODE REVIEW

**Comment by Araq** [comment]
Can't we instead in a prepass move top level statements from the main module into an automatic ``proc main``? The only problem is that it might introduce closures where previously there weren't any...

**Comment by cooldome** [comment]
the only real problem is how to handle top level variables that are not explicitly exported, but can be used in the other modules via hygienic templates and bindSym. I though I can track such sym usage in sempass and add a flag on the sym for codegen. However, it turned out that it is too late to track sym usage in other modules, the codegen of these variables already happened so I can't go back reemit them as not `static`.

**Comment by zah** [comment]
@cooldome, the problem you are describing happens only because Nim tries to execute all the compiler passes on a statement-by-statement basis (nowadays, it's actually a bit a more complex and the statements are grouped into larger chunks). Nevertheless, this "streaming" property is not enforced in all scenarios and it's questionable whether it brings much value.

I've been advocating for an alternative approach where the sem pass is executed for the whole program before the codegen pass begins. With such a scheme, it would be possible to have more sophisticated codegen steps that take advantage of information derived from the whole program. These will simplify some some of the book-keeping logic related to dead-code elimination, multi-methods, the order of initialization of `.global.` and other problems. It would also potentially allow us to do multi-threaded codegen in the future and it will pave the way for more sophisticated support for multi-stage meta-programming that will support a common code generation pattern that I call "[gather and generate](https://github.com/nim-lang/RFCs/issues/46#issuecomment-395686265)".

Your example here is just another case of codegen logic that needs complete sem knowledge for the module before the codegen starts.

**Comment by cooldome** [comment]
Thanks Zah for a good summary.

I see three potential ways forward:

1. Introduced new mandatory pragma for the not exported but used across modules global variables. This is breaking change though simple to do and minimum code changes.
2. Delay codegen until the semantic pass has finished across all modules and automatically deduce across module usage of global variables. Potential compilation time increase or possibly not. Did anyone measure? 
3. Leave things the way they are now.

@Araq, do you have a preference?

**Comment by Araq** [comment]
Can we do (3)? What problem does it even solve? Is the problem still a problem with linktime optimizations?

**Pull request closed without merging**
