### PR TITLE
fix: InotifyEvent.name should be UncheckedArray[char]

### PR DESCRIPTION
**Pull request by tdely**

### CODE REVIEW

**Comment by Araq** [comment]
This is not correct, see https://man7.org/linux/man-pages/man7/inotify.7.html

It is an array of unspecified size at the end of the struct, but not a pointer!

**Comment by tdely** [comment]
You're right, but cstring is working for me; it hasn't failed yet. Can the module be used in its present state with char to get the name?

**Comment by beef331** [comment]
Are you actively using the name? Cause `cstring` and `UncheckedArray[char]` have vastly different semantics. For reference <https://github.com/beef331/reflector/blob/master/reflector/inotifyevents.nim> are more correctly Nimified bindings for Inotify.

**Comment by tdely** [comment]
> Are you actively using the name? Cause `cstring` and `UncheckedArray[char]` have vastly different semantics. For reference https://github.com/beef331/reflector/blob/master/reflector/inotifyevents.nim are more correctly Nimified bindings for Inotify.

Yes. I need the name to add watches on created files, and remove and re-add watches when files get replaced without the original being removed or moved first. I'm happy enough with the C-style bindings, but `UncheckedArray[char]` as you've done works just as well as cstring.. do want me to update the PR with this change?

**Comment by beef331** [comment]
It should be a `UncheckedArray[char]` yes, the fact cstring works for you astounds me :smile:

**Pull request merged**
