### PR TITLE
Add inverse hyperbolic, and cot, sec and csc; and their hyperbolic, inverse, inverse hyperbolic, and change to use defined functions in C or JS for logs and hyperbolics.

### PR DESCRIPTION
**Pull request by Paalon**

### CODE REVIEW

**Comment by data-man** [comment]
Related RFC #3745.

**Comment by Paalon** [comment]
I don't know why JavaScript's implementation of sinh, cosh and tanh use direct computation from exp. JavaScript has Math.sinh, Math.cosh and Math.tanh. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math

**Comment by Paalon** [comment]
What I have done:

- Add inverse hyperbolic functions: `arcsinh`, `arccosh`, `arctanh`
- Add cotangent, secant and cosecant: `cot`, `sec`, `csc`
- Add (cot, sec, csc)'s related functions: `coth`, `sech`, `csch`, `arccot`, `arcsec`, `arccsc`, `arccoth`, `arcsech`, `arccsch`
- Change to use defined functions in C or JS: `log10`, `log2`, `sinh`, `cosh`, `tanh`

**Comment by data-man** [comment]
Wow, thank you!

Please, update the changelog. Maybe the PR's name too?

**Comment by dom96** [comment]
Looks good. Thanks!

**Pull request merged**
