### PR TITLE
removal of seq spam in generated C/C++ code and Module.typeStack cleanup

### PR DESCRIPTION
**Pull request by heterodoxic**
by "seq spam" I mean instances of this:
```C
#ifndef tySequence__3sDunbHrOeea9buCGufYbfg_Content_PP
#define tySequence__3sDunbHrOeea9buCGufYbfg_Content_PP
struct tySequence__3sDunbHrOeea9buCGufYbfg_Content { NI cap; tyObject_StackTraceEntry__yxA4wv9c5cGrN4VGeJiBXmw data[SEQ_DECL_SIZE];};
#endif
```
aiming for:
```C
struct tySequence__3sDunbHrOeea9buCGufYbfg_Content { NI cap; tyObject_StackTraceEntry__yxA4wv9c5cGrN4VGeJiBXmw data[SEQ_DECL_SIZE];};
```

Apparently, the need for these macro guards arose because of redundant pushes of a seq's concrete type to Module.typeStack for the seqv2 implementation.

This simple change seems to take care of that issue.

### CODE REVIEW

**Comment by juancarlospaco** [comment]
Nice, much less code to generate, because thats the point of the mangling whatsoever.

**Comment by heterodoxic** [comment]
> Nice, much less code to generate, because thats the point of the mangling whatsoever.

Thanks, this trims it down a bit, as basically every module that makes use of seqv2 had to include those guards, AFAIU.

**Comment by juancarlospaco** [comment]
I was thinking this is not used for hot code reloads ?. 🤔

**Comment by heterodoxic** [comment]
> I was thinking this is not used for hot code reloads ?. 🤔

I don't think so, it merely prevented redefinitions of the same generated C/C++ struct that the C/C++ compiler would complain about.

**Pull request merged**
