### PR TITLE
Fix broken async httpclient example

### PR DESCRIPTION
**Pull request by 0atman**
As the async httpclient is almost certainly the first async example beginners will want to try, we OWE it to them to give them a real example.

Example repeated here for clarity:

```nim
import asyncdispatch, httpclient

proc asyncProc(): Future[string] {.async.} =
  var client = newAsyncHttpClient()
  return await client.getContent("http://example.com")

echo waitFor asyncProc()
```

This is my first Nim contribution, please let me know if the code is right. (it runs on my machine, but may not be the best example)

### CODE REVIEW

**Comment by 0atman** [comment]
This certainly tripped me up when I was trying to learn Nim (last month!)

**Comment by 0atman** [comment]
Question: Why don't the Nim docs use the awesome `runnableExample` feature? That way this bug would never would have happened, as the docs wouldn't have compiled.

**Comment by ghost** [comment]
Well I wouldn't say that it's "broken", the docs tell you that you need to run async stuff in async procedures

**Review by dom96 — APPROVED** [review]

**Comment by 0atman** [comment]
@Yardanico I think the gold standard for code examples is if the *compiler* thinks it's broken! :laughing: 

Working examples should be our default, but I'd be interested to hear alternative viewpoints.

**Comment by 0atman** [comment]
Thanks for merging this in, @dom96 :ok_hand:

**Comment by Araq** [comment]
> Question: Why don't the Nim docs use the awesome runnableExample feature? That way this bug would never would have happened, as the docs wouldn't have compiled.

Because some code predates the runnableExample feature.

**Comment by 0atman** [comment]
@Araq Can't argue with that. Is this the right way to fix that? https://github.com/nim-lang/Nim/pull/14045

**Pull request merged**
