### PR TITLE
rename case statement macro from match to `case`

### LINKED ISSUE #332: Rename case statement macro from match to `case`
https://nim-lang.github.io/Nim/manual_experimental.html#case-statement-macros

The macro required to implement a custom case statement has to be named `match`. This is a very common name for macros and is usually used directly instead of via `case`. Nim allows stropping keywords for routine names. So, I propose `match` should be changed to `` `case` ``. The example becomes:

```nim
{.experimental: "caseStmtMacros".}

import macros

macro `case`(n: tuple): untyped =
  result = newTree(nnkIfStmt)
  let selector = n[0]
  for i in 1 ..< n.len:
    let it = n[i]
    case it.kind
    of nnkElse, nnkElifBranch, nnkElifExpr, nnkElseExpr:
      result.add it
    of nnkOfBranch:
      for j in 0..it.len-2:
        let cond = newCall("==", selector, it[j])
        result.add newTree(nnkElifBranch, cond, it[^1])
    else:
      error "custom 'case' for tuple cannot handle this node", it
  echo repr result

case ("foo", 78)
of ("foo", 78): echo "yes"
of ("bar", 88): echo "no"
else: discard
```

This experimental feature seems to be seldom used as people prefer to just use custom matching macros. This would help outline the difference and rid any incompatibilities (`n: tuple` is not actually AST of a tuple, it's the AST of a case statement). Further improvements could be done to this feature, for example changing the arguments `(n: tuple)` to `(n: tuple, branches: varargs[untyped])`, but I think renaming `match` to `` `case` `` first will make further changes much more straightforward.

Relevant line in compiler:

https://github.com/nim-lang/Nim/blob/25c75752d07fccc00682890875f3ce6c13f61d90/compiler/semstmts.nim#L867

### PR DESCRIPTION
**Pull request by metagn**
closes https://github.com/nim-lang/RFCs/issues/332

Mostly to see what breaks

### CODE REVIEW

**Comment by metagn** [comment]
CI seems fine. Maybe don't merge yet, PRs could be made to fusion etc in anticipation of this first, also could lift from experimental as said in the RFC but PRs for that would have to be after the merge

**Comment by juancarlospaco** [comment]
But what about https://github.com/nim-lang/RFCs/issues/332#issuecomment-772391157 ? :thinking:

**Comment by timotheecour** [comment]
* @hlaaftana after running git bisect, this seems to cause a regression, fusion/matching now doesn't work:
```nim
when true:
  import fusion/matching
  {.experimental: "caseStmtMacros".}
  case (1, 2):
    of (3, 4), (1, 2):
      discard
    else:
      discard
```

works before this PR, fails after
```
Error: attempting to call undeclared routine: 'case'
    case (1, 2):
```

* I also notice we don't even have `fusion` in important_packages; we should add it; having it would've prevented this regression. Note that fusion CI is green but would be red the next time it runs

**Comment by metagn** [comment]
> after running git bisect, this seems to cause a regression, fusion/matching now doesn't work:

The change to rename `match` to `` `case` `` in fusion is in https://github.com/nim-lang/fusion/pull/61, so yes fusion HEAD is broken for now. The change could be made in a separate PR but that PR seemed like it was about to be merged so I commented on it.

**Comment by timotheecour** [comment]
* but https://github.com/nim-lang/fusion/pull/61 does a whole lot of other things, why not have a hot-fix that just renames it to unbreak fusion/matching?
* also, how about adding `nimHasRenamedMatchCase` to condsyms.nim so that you can write code that works both before and after this change? (eg, so that 1.4.2 can write caseStmtMacros too)

**Comment by metagn** [comment]
> * but [nim-lang/fusion#61](https://github.com/nim-lang/fusion/pull/61) does a whole lot of other things, why not have a hot-fix that just renames it to unbreak fusion/matching?
> 
> * also, how about adding `nimHasRenamedMatchCase` to condsyms.nim so that you can write code that works both before and after this change? (eg, so that 1.4.2 can write caseStmtMacros too)

Would be fine with both of these getting done, just initially neither seemed necessary to me.

**Pull request merged**
