### PR TITLE
Fix typo in re module: PRCE -> PCRE

### PR DESCRIPTION
**Pull request by kaushalmodi**
Spotted the typo on https://nim-lang.org/docs/re.html

### CODE REVIEW

**Comment by Yardanico** [comment]
This was created against `master` branch, please re-create the PR against `devel` :)

**Comment by kaushalmodi** [comment]
Interesting I am unable to push to GitHub because of this error:


*Looks like master has gone AWOL :P*

If you know how to apply a patch traditional style using command line, here it is, based off 959b6354c:

```patch
From 0321ea36c987c88a757879cfee0eb571ff908b73 Mon Sep 17 00:00:00 2001
From: Kaushal Modi <kaushal.modi@gmail.com>
Date: Tue, 5 Jun 2018 12:58:23 -0400
Subject: [PATCH] Fix typo: PRCE -> PCRE

---
 lib/impure/re.nim | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/lib/impure/re.nim b/lib/impure/re.nim
index 34d55b7b0..201c490f3 100644
--- a/lib/impure/re.nim
+++ b/lib/impure/re.nim
@@ -10,11 +10,11 @@
 ## Regular expression support for Nim.
 ##
 ## This module is implemented by providing a wrapper around the
-## `PRCE (Perl-Compatible Regular Expressions) <http://www.pcre.org>`_
-## C library. This means that your application will depend on the PRCE
+## `PCRE (Perl-Compatible Regular Expressions) <http://www.pcre.org>`_
+## C library. This means that your application will depend on the PCRE
 ## library's licence when using this module, which should not be a problem
 ## though.
-## PRCE's licence follows:
+## PCRE's licence follows:
 ##
 ## .. include:: ../../doc/regexprs.txt
 ##
-- 
2.17.0.rc0
```

**Comment by kaushalmodi** [comment]
@Yardanico Looks like the master branch just got restored.. but it is lagging behind.. my fork is 4 commit ahead of it:

image

**Comment by Yardanico** [comment]
@kaushalmodi yeah, and that is a mistake anyway (latest master commit should always be the release one).
And someone deleted master branch, that's why it was restored.

**Pull request merged**
