### PR TITLE
Mysterious fix for #8550

### PR DESCRIPTION
**Pull request by LemonBoy**
Replacing the `for` body with a nkEmpty node is not the right thing to
do.

Waiting for CI run, don't merge yet.

### CODE REVIEW

**Comment by timotheecour** [comment]
wondering whether it also fixes https://github.com/nim-lang/Nim/issues/7787 ?

**Comment by michael72** [comment]
Wondering when it's going to be integrated? Because it is working!!

@timotheecour No unfortunately it doesn't - it hits the line 
```nim 
localError(g.config, routine.info, "internal error: could not find env param for " & routine.name.s)"
```
[here](https://github.com/nim-lang/Nim/blob/1fc3a68205697c2ad33b2f0e1cfcb526e73b0677/compiler/lambdalifting.nim#L177)

**Comment by michael72** [comment]
@Araq 
This is mysteriously ready to be integrated - maybe not even that mysterious
As mentioned in #8550 this would countermand the following 2 commits:
9c6d3e2
and
813f98f
The latter is supposed to fix tforum.nim, but that's still working after the change... 🤔 (I tried it and it looks like appveyor does too!
:bowtie:

**Comment by Araq** [comment]
Seems to improve the situation merging. The original ``tooEarly`` code path is covered by tests anyway.

**Pull request merged**
