### PR TITLE
appveyor: attempt to setup a 32 bit environment

### PR DESCRIPTION
**Pull request by Araq**

### CODE REVIEW

**Comment by genotrance** [comment]
This is good, but is this really needed for every PR? AppVeyor already takes an hour. With this, it will become 1.5.

We already have Windows and Linux 32-bit being tested in nightlies now.

**Comment by Araq** [comment]
Shouldn't it run in parallel? Why would it become 1.5 hours? And nightlies don't test everything that the daily CIs test.

**Comment by genotrance** [comment]
Nope, AppVeyor runs only 1 job at a a time for Nim. Though you are right, nightlies do not run a full 32-bit test.

**Comment by Araq** [comment]
Ok, then I won't bother with it anymore.

**Pull request closed without merging**
