### PR TITLE
fix #4165(static parameters + emit)

### LINKED ISSUE #4165: static[T] argument is not substituted properly in .emit pragma
Sample:
```nim
proc printStr(s: static[string]) =
  {.emit: "puts(`s`->data);" .}
printStr("hello static")

# sample.cpp:52:7: error: use of undeclared identifier 's0'
#         puts(s0->data);
#              ^
```

### PR DESCRIPTION
**Pull request by ringabout**
fix #4165

### CODE REVIEW

**Comment by timotheecour** [comment]
this should be legal IMO, static should be no different from const here.

```nim
when true:
  proc printStr(s: static float) =
    const s2 = s
    # {.emit: """printf("%g\n", `s`);""" .} # bug but should be fixed instead of disallowing
    {.emit: """printf("%g\n", `s2`);""" .} # works
  printStr(1.23)
```

a fix similar to https://github.com/nim-lang/Nim/pull/17590 should be possible

**Comment by ringabout** [comment]
It seems a bit different. Variable `s` disappears at runtime. But `s2` still can be accessed at runtime.

**Comment by timotheecour** [comment]
the semantics should be:
* a const gets inlined wherever it's being used
* a static should act as if a const was defined with the static's value

Try this:
```nim
          if e.kind == skParam and e.typ != nil and e.typ.kind == tyStatic:
            result.add e.typ.n
          else:
            result.add newSymNode(e)
          incl(e.flags, sfUsed)
```

This seems to work, in at least the cases where a const would work eg:
```nim
when defined case5:
  proc printStr(s: static float) =
    const s2 = s
    {.emit: """printf("%g\n", `s`);""" .} # works
    {.emit: """printf("%g\n", `s2`);""" .} # works
  printStr(1.23)
```

as for the example in the bug report, it also wouldn't work with a const:
```nim
when true:
  proc printStr() =
    const s = "foo"
    # would not work, because a const gets inlined upon use
    {.emit: "puts(`s`->data);" .}
  printStr()
```
so that's a separate issue, and would be possible via https://github.com/timotheecour/Nim/issues/553:
`let a {.rom.} = constExpr`

note that this works though, with my above patch:
```nim
when true:
  proc printStr(s: static string) =
    {.emit: """printf("%s\n", "`s`");""" .}
  printStr("abc")
```

## EDIT
on 2nd though, the way you did it is probably simpler/more general; the error message could include something like suggesting to define a `let s2 = s` runtime variable before accesssing it
* note that IMO the problem is identical for static and const, so whatever is done should apply to both

## EDIT
but maybe it's still useful (eg performance reasons or simplicity) to support this use case:
```nim
when true:
  proc printStr(s: static string) =
    {.emit: """printf("%s\n", "`s`");""" .}
  printStr("abc")
```
which, ugly as it is, works in cases like this.

**Review by timotheecour — APPROVED** [review]
LGTM

in future work we should also disable accessing a const inside an emit, for the same reasons.

instead of this:
```nim
when true:
  proc printStr(s: static string) =
    # now illegal for static after this PR, but not yet for const or generic static param
    {.emit: """printf("%s\n", "`s`");""" .}
  printStr("abc")

  proc printStr2[N: static string]() =
    # ditto: this still "works" after this PR but in future work should give CT error
    {.emit: """puts("`N`");""" .}
  printStr2["Hello, Nim"]()
```


users should turn the const or static into a codegen'd value via for eg:
```nim
when true:
  proc printStr(s: static string) =
    let s2 = s # now s2 is codegen'd
    {.emit: """printf("%s\n", `s2`->data);""" .}
    # or this:
    let s3 = s.cstring
    {.emit: """printf("%s\n", `s3`);""" .}
  printStr("abc")
```

**Pull request closed without merging**
