### PR TITLE
put top-level docs in a separate file

### PR DESCRIPTION
**Pull request by narimiran**
As discussed with @Araq, long top-level introductions and examples should be put in a separate file (named `..._doc.nim`).

### CODE REVIEW

**Comment by kaushalmodi** [comment]
Syntax:

```rst
## .. include:: ./docs/strfmt.rst
```

[Ref](https://github.com/kaushalmodi/strfmt/blob/master/strfmt.nim)

Benefit:

- The whole document can be typed quicker without the `##` prefix. 

Also, may be all docs should go in a `docs/` subfolder to reduce files in flat hierarchy?

**Comment by Vindaar** [comment]
> > The whole document can be typed quicker without the ## prefix.
> 
> You can do it like this:
> 
> ```
> ##[
> A normal unindented
> text without
> any prefixes
> ]##
> ```

Maybe you could convert the remaining half of the doc files, which do not already do this to that format?

**Comment by kaushalmodi** [comment]
> The idea is to have runnableExamples, which make .rst unsuitable.

Understood. 

But why not a separate docs/ dir? I missed the discussion. 

> You can do it like this:

> ##[
> ..
> ]##

That looks great! I didn't know that would work. Why not use that format in this and future doc updates?

**Comment by narimiran** [comment]
> Maybe you could convert the remaining half of the doc files, which do not already do this to that format?

Your wish is my command ;)

Pushed those changes, now everything uses `##[` and `]##`.

**Comment by narimiran** [comment]
After some discussions on IRC, I think it is the best to put this on hold, i.e. continue to write the documentation in the same file.

**Pull request closed without merging**
