### PR TITLE
Generate populationCount const at compile time

### PR DESCRIPTION
**Pull request by GULPF**
As requested in #7558

### CODE REVIEW

**Comment by cooldome** [comment]
Looks great, but isn’t it easier to use popcount function from bitops module

**Comment by Araq** [comment]
``` nim
import bitops
echo popcount(cast[int](0b11111111'i8)) # force zero extend
```

**Comment by GULPF** [comment]
@Araq Still doesn't work. Doesn't look like `cast[int](...)` does zero extend:
```nim
doAssert cast[int32](0b11111111'i8) == 0b11111111111111111111111111111111'i32
```

**Comment by Araq** [comment]
It has to, that's what the spec says. :-/

**Comment by cooldome** [comment]
This seams to work:
```
import bitops
const populationCount = block:
  var arr: array[low(int8)..high(int8), int8]
  for it in low(int8)..high(int8):
    arr[it] = popcount(cast[uint8](it)).int8
  arr
```

I'll submit  ``echo popcount(0b11111111'i8) # 32`` as bug report

**Pull request merged**
