### PR TITLE
add collect macro

### PR DESCRIPTION
**Pull request by b3liever**
assumes init call has generic parameters

### CODE REVIEW

**Comment by Araq** [comment]
Needs a ``{.since: (1, 1).}`` annotation and a changelog entry.

**Comment by alehander92** [comment]
why no `collect(code: untyped)` default version which default to seq/table

**Comment by b3liever** [comment]
I forgot to ask if it should open a new scope, wrap the body in a block.

**Comment by SolitudeSF** [comment]
@b3liever, i tried to test how the symbol would leak with this snippet
```nim
echo collect(newSeq, (var a = 1; for d in [1, 2]: d))
```
but it fails with `Error: redefinition of 'a';`. And when using nimsuggest it shows warning about redifinition of `a`.
but if i wrap it in block manually like
```nim
echo collect(newSeq, block: (var a = 1; for d in [1, 2]: d))
```
it just throws two warning about redifinion from the same location
```
/home/solitude/test.nim(2, 34) Hint: 'a' is declared but not used [XDeclaredButNotUsed]
/home/solitude/test.nim(2, 34) Hint: 'a' is declared but not used [XDeclaredButNotUsed]
```
when using expand macro the varible, surely is declared only once.

**Comment by b3liever** [comment]
@SolitudeSF yep definitely some weird compiler bug going on, can you try the [original](https://gist.github.com/b3liever/0a5b80abb0ca1d24c64d81ea89be12c5)

**Comment by SolitudeSF** [comment]
first snippet, compiles, but gives same double warning

**Comment by Araq** [comment]
Unrelated compiler glitch, has nothing to do with this lovely macro. ;-)

**Comment by b3liever** [comment]
> why no `collect(code: untyped)` default version which default to seq/table

It can't be done unfortunately because of untyped

**Comment by b3liever** [comment]
> why no `collect(code: untyped)` default version which default to seq/table

It can't be done unfortunately because of ``untyped`` and i think its pretty good as it is, writting ``newSeq`` is not much trouble.

**Comment by Araq** [comment]
@b3liever Actually it can be done since both macros would agree on the ``untyped`` parameters positions...

**Comment by bluenote10** [comment]
Wouldn't it have been possible to implement collect functionality actually within the type system like in Rust, avoiding yet another `untyped` args macro that messes up overloading? It feels strange that Nim has iterators, but functionality that is iterative in nature is never defined in terms of iterators. Basically it is the `toSeq` issue again.

Specifically this has broken some of my code including NimData, because I rely on `sugar` for `=>` almost everywhere and I sometimes use `collect` as a proc name. In particular in NimData, `collect` is part of the data frame API, which now gets messed up because there is a `collect(untyped, untyped)` in scope. Of course, it can be worked around with selective imports, but somehow it is annoying that a basic stdlib import can so easily mess up an entire library API.

**Comment by Araq** [comment]
Maybe it "would have been possible" but it would have been much more expensive to develop and the ``untyped`` problem is an existing problem we need to fix anyway. I think I know how to do that but it takes an RFC and an implementation in the compiler. Much more effort.

**Pull request merged**
