### PR TITLE
Fix https://github.com/nim-lang/Nim/issues/7120 by changing all

### PR DESCRIPTION
**Pull request by c-blake**
arithmetic to 64-bit, generalizing msbit to 64-bit inputs, and
bumping MaxFli to 40.  Program like example in issue now works
for much larger allocations..I tested up to (1 shl 35) bytes.

### CODE REVIEW

**Comment by c-blake** [comment]
I believe the remaining test errors in test/concepts are unrelated to this PR.  Those errors also happen for me with regular devel branch.

**Comment by cooldome** [comment]
Useful change. IMO, 32bit targets should remain on 32bit arithmetic and 64bit targets use 64bit arithmetic. IMO, it makes sense to use int/uint types and``when`` statement if logic diverge.

**Comment by c-blake** [comment]
@cooldome - Well, the code should work on 32-bit targets as long as the double-wide integer types do.  It will not be quite as fast as if we did all those `when`s or some top-level type aliases.

I did mention the option in the issue I raised on this, proposed just doing pure 64, and didn't get any pushback from Araq. So, I went with "simple".  I tend to think there are a great many places in Nim not truly optimized for 32-bit targets.

**Comment by Araq** [comment]
IMO The allocator should instead use a 3rd branch when allocating sizes bigger than 2GB. These could be returned back to the OS immediately, skipping all the TLSF logic (which over allocates quite a bit for these allocation requests iirc).

**Comment by c-blake** [comment]
@Araq - I did run some tests on overallocation..basically just `for size in ...: discard newSeq` type stuff and the max virtual memory footprint was about 2..3X the max array size memory footprint which is a fairly typical multiplier.  I didn't test all the GC variants..default, markAndSweep, refc.  Anyway, I don't disagree with this 3rd (or 2nd, really) branch idea (nor the 32-bit optimization).

However, my intent with this PR was not to optimize speed/memory use completely, but rather to fix the regression and just get things working again for large allocations.  Optimizing it more is a more open-ended project which I very much encourage, but personally I probably do not have the time to fully engage in right now.

Anyway, I don't think the current PR is a bad compromise.  To the extent you believed such large allocations were rare enough to not imagine/support initially, these optimizations we speak of are not common cases.  To the extent large allocator programs run into memory overuse, they could still memory map/manage their own few giant regions.  I almost did that myself for the singleton giant vector I was allocating when I first ran into this problem.

**Comment by Araq** [comment]
> However, my intent with this PR was not to optimize speed/memory use completely, but rather to fix the regression and just get things working again for large allocations. Optimizing it more is a more open-ended project which I very much encourage, but personally I probably do not have the time to fully engage in right now.

That is not an issue, I can do it. It was merely a question of whether this would be welcome for your use cases.

**Comment by c-blake** [comment]
Very welcome!  My current use case was just one to a few several-GB arrays per process and your optimization idea would work well.  That _should_ be true of most very large allocation users right now since most people only have so much RAM.

"Big" memory systems are proliferating, though.  NVMe flash storage has really taken off the past few years leaving a *lot* of people (most even?) with potentially on the order of several to many 100s of GB of only somewhat slower virtual memory. That Intel Optane nvDIMM stuff is also becoming available.  Nim has great performance characteristics for "big" calculations and big-ish data is all in vogue these days.  So, it seems important for the compiler to support big allocations somehow.

Anyway, all that is pretty obvious.  Also pretty obvious is that if you do it the way you suggest then there is no need for the 64-bit arithmetic changes in this PR or a branch for 32-bit.  You can leave the 32-bit stuff for the <=1..2GB allocations as is and just need a 2nd branch for giant allocations as you were outlining.  You don't need to support the giant allocations at all on 32-bit platforms.  I just took a stab at the approach that I suggested.

**Pull request closed without merging**
