### PR TITLE
renamed new std/pragmas.nim to std/byaddr.nim

### PR DESCRIPTION
**Pull request by Araq**

### CODE REVIEW

**Comment by timotheecour** [comment]
can you please pick any other name to avoid name clash? it has caused bugs before when module name matches symbol name.
also, this can be home to things like `evalonce` or `bycopy`, so `byaddr.nim` isn't the right name.
how about (I can do a followup PR):
`std/declpragmas` ?

**Comment by Araq** [comment]
how about ``std/vardecls``?

**Comment by timotheecour** [comment]
Id be ok with that, but note that it should be applicable for const, var, let sections (yes const is not yet enabled but can, and i have at least one important use case for that, see other rfc)

Im even thinking it could be the new home for `since` pragma, optionally.

**Comment by Araq** [comment]
it's only a name and "var" here stands for var/let/const.

**Comment by Araq** [comment]
Since the release build is already processing, we decided std/byaddr is good enough for 1.2, it's experimental anyway. We can add ``std/decls`` later.

**Pull request merged**
