### PR TITLE
strict thread raises

### PR DESCRIPTION
**Pull request by arnetheduck**
Raising uncaught exceptions in threads causes the application to crash making it a generally bad idea.

This PR takes the opportunity to restrict the errors raised by thread proc's to only `Defect`, avoiding a common pitfall and source of crashes.

The mode can be turned off for backwards compatibility in a transition period and a warning will be printed instead (useful for the version-1-6 version of this patch that will be posted later, should it be adopted).

Code that already doesn't raise won't be affected by this change - code that potentially raises will see a compile error instead.

The PR has been updated to enable the strict mode together with `nimPreviewSlimSystem`.

> Regarding default on/off, a more backwards-compatible option is to enable thread raise checking together with `nimPreviewSlimSystem` which already causes compile errors for thread-using apps.

> This PR disables strict raises checking in a number of places and does not attempt to fix the lack of error handling, ie the uncaught exception crashes in `nimgrep` are not fixed - the compatibility mode can help pinpoint them however.

> As can be seen in test suite changes, many functions are already raises-free but need to be explicitly annotated as Nim is not smart enough to figure this out in forward declarations and proc types.

In an ideal world, this would not require a global define - ie something like `Thread[TArg; noraises: static bool = true]` would be nice but I couldn't get that to work.

### CODE REVIEW

**Comment by Araq** [comment]
What about a new `createThreadStrict` that takes a callback that is `.raises: []`. Then we wouldn't need yet another switch.

**Comment by arnetheduck** [comment]
> What about a new createThreadStrict

the downside here is that the callback declaration in `Thread` itself will have to remain lenient which prevents reasoning further about it (ie removing try/except around the runner for example and instead using the "normal" unhandled exception handler, perform static analysis of the control flow etc).

This code is based on a similar transition we've made for `chronos` where we use a more strict declaration by default an allow a backwards-compatibility "escape hatch" in order to allow an extended "adjustment time" so as not to break all the working code out there.

> Then we wouldn't need yet another switch.

I see it as a temporary backwards compat switch, to be removed together with `nimPreviewSlim...` - that said, yeah, I don't like switches either - it's certainly not ideal.

`createThreadStrict` isn't great UX - it is more difficult to spell than the less safe version which is a problem for newcomers that are more likely to miss the nuance. One option would be `createThread2` and simply deprecate `createThread`.


Here's how that would look:

```nim
proc ehwrapper(p: proc() {.nimcall....}): proc() {.noraises.} =
  return proc() = 
    try:
      p()
    except:
      logandquit()


createThread2(p: proc() {.noraises.}) = ...

createThread(p: proc()) {.depcreated.} =
  createThread(ehwrapper(p))
```

With this strategy we can actually make Thread have a good signature, avoid the flag at the expense of `2` in the name, which I have no qualms about.

**Comment by Araq** [comment]
> createThreadStrict isn't great UX

It's just the first name I came up with, `startThread`, `summon` etc etc are all possible too.

**Comment by arnetheduck** [comment]
here's a `startThread` version without the compile-time flag

**Comment by arnetheduck** [comment]
this is now green, build fail unrelated: https://github.com/nim-lang/Nim/issues/22186

**Pull request closed without merging**
