### PR TITLE
isolate the build process from external configuration files

### PR DESCRIPTION
**Pull request by stefantalpalaru**

### CODE REVIEW

**Comment by Araq** [comment]
While I don't mind this change, it's a breaking change and I'm sure some people like the fact that their config is picked up. @timotheecour @kaushalmodi

**Comment by timotheecour** [comment]
I'm a bit agnostic on this one; maybe we could support forwarding arguments (on both build_all.bad and build_all.sh):
```
sh build_all.sh --skipUserCfg --skipParentCfg --skipTools
# --skipTools would skip building tools; other flags would be forwarded
```
but obviously goes against goal of keeping bash/bat scripts as simple as possible

**Comment by stefantalpalaru** [comment]
> it's a breaking change

Is it? If you have `--passC:"-march=native"` in some external configuration file, the Nim compiler won't build (weird error in the third stage, when processing the macros module).

That's not the kind of surprise behaviour you want when building a compiler.

**Comment by Araq** [comment]
You're only moving the problem around. Now it's surprising behaviour that some commands do not pick up your "default" nim.cfg file.

>  the Nim compiler won't build (weird error in the third stage, when processing the macros module).

So it's a workaround for a different problem.

**Comment by stefantalpalaru** [comment]
> So it's a workaround for a different problem.

It's generic project building hygiene. Do you really want to deal with bug reports for whatever people put in their four supported external configuration files that are read by default?

**Comment by kaushalmodi** [comment]
@Araq 

> I'm sure some people like the fact that their config is picked up

This is true when I am building my Nim projects. But when building the nim compiler, having just **one way** would make the builds consistently reproducible on any machine. E.g. you make the call if nim should be built with `-d:danger` or `-d:release`.. someone's config.nims shouldn't decide that.

**Comment by disruptek** [comment]
The default is that no such files exist and the build is not impacted.  Users that want such behavior can produce it by adding such files.  You are one such user.  If you don't want this behavior, maybe rename the file or add a command-line option to overlook it?

**Comment by Araq** [comment]
> Do you really want to deal with bug reports for whatever people put in their four supported external configuration files that are read by default?

No but I also don't really want to deal with bug reports where users complain that their config isn't acknowledged when they bootstrap the Nim compiler. I simply don't want to deal with bug reports either way. ;-)

**Comment by Araq** [comment]
We can shorten the discussion though: I merged it but we won't backport it. And it should have had a changelog entry but we can do that later in the release process.

**Comment by timotheecour** [comment]
after https://github.com/nim-lang/Nim/pull/13516 you have a perfect workaround:
```
# will honor --hint:cc:off or --hint:processing:off or any other flag in user configs
./koch boot -d:release --skipUserCfg:off

# other example that now works:
./koch --nim:pathto/nim boot -d:release -d:nimUseLinenoise --hint:cc:off
```

**Pull request merged**
