### PR TITLE
make get for options use lent T

### LINKED ISSUE #14420: VM and js backend require `result` for lent or var annotations to work
Most of the standard library is working at compile-time and there are checks to ensure that.

Unfortunately from https://github.com/nim-lang/Nim/pull/14417#issuecomment-632125417, `lent` is not supported in the VM.

For example the JSON test will fail with

```Nim
Error: limited VM support for 'addr'
```

This would prevent using `lent` to optimize arrays, sequences, options, "result" types, object variants. All of which have a typical no-copy use-case.

The easy fallback would be to make lent a no-op in the VM.

### PR DESCRIPTION
**Pull request by cooldome**
fixes #14420

### CODE REVIEW

**Comment by timotheecour** [comment]
I'm confused; what about https://github.com/nim-lang/Nim/pull/14417#issuecomment-632125417 ? at very least this needs a test at RT and CT
also the title of https://github.com/nim-lang/Nim/issues/14420 is `The VM doesn't support `lent` annotation`, so unless you're fixing that (which doesn't look like it from PR content), I'd remove `fixes #14420` from PR msg

**Comment by cooldome** [comment]
@mratsim tried adding `lent T` to `get()` function of `Option[T]` and received error `Error: limited VM support for 'addr'` and thought that VM has no support for `lent T`. It turned out that VM has full  support of lent T/var T and the issue is caused not by `lent T` but by temporary variable introduced by vmgen to handle stmtListExpr. One miinor change to `get()` was needed to avoid stmtListExpr.

`Option[T]` is already extensively covered by tests.

**Comment by mratsim** [comment]
Is the temporary introduced by the VM needed?

Otherwise maybe we should add "Try returning via the implicit `result`" to the error message.

`unsafeGet` should also be updated in this PR.

**Comment by timotheecour** [comment]
* ok thanks for explanation; I've added a reduced example for this in https://github.com/nim-lang/Nim/issues/14420#issuecomment-633463012

We should fix https://github.com/nim-lang/Nim/issues/14420#issuecomment-633463012 before closing that issue, so I still don't think your PR should close that issue as it remains an incompatibility between RT and VM


* @mratsim can you re-evaluate https://github.com/nim-lang/Nim/issues/14420#issuecomment-632886274 after the changes in this PR?
> As a potential impact, I tried to use options in my RayTracer, but they were 5x slower (not just a couple dozen percents like the iterator issue in #14421) than passing mutable parameter + bool
> Well nobody claimed Option[T] is a lightweight abstraction.

* > Option[T] is already extensively covered by tests.

there's 0 VM test

**Comment by arnetheduck** [comment]
this doesn't fix the issue though, just works around it for `Option` specifically - ie `result = self.val` is just a hack, the same construct exists in lots and lots of other code.

**Pull request merged**
