### PR TITLE
add plausibleAnalytics support for koch docs[backport:1.6]

### PR DESCRIPTION
**Pull request by ringabout**
Ref https://github.com/nim-lang/website/pull/339

Though Google Analytics is not used for `koch docs` (it is used for deprecated docs0 instead).

### CODE REVIEW

**Comment by ringabout** [comment]
@pietroppeter Hello, is it correct? Or I need to use `nim-lang.org/docs`?

**Comment by ringabout** [comment]
Unrelated CI failures are fixed by https://github.com/nim-lang/Nim/pull/20455

**Comment by pietroppeter** [comment]
> @pietroppeter Hello, is it correct? Or I need to use `nim-lang.org/docs`?

Hi, it should be correct as it is

**Comment by pietroppeter** [comment]
I think I got it wrong and it is something else (not necessarily with only docs added). We now have in plausible logs for non existent links such as https://nim-lang.org/Nim/koch.html

**Comment by ringabout** [comment]
I thought only URLs under `nim-lang.org` is counted. It seems that `nim-lang.github.io/Nim/koch.html` is counted too.

**Comment by pietroppeter** [comment]
Ah that is where it comes from! I thought it was a more convoluted error that was being logged by nim-lang.org/docs/koch.html

Yes, as far as I know plausible does not makes a check on base url. The base url in the script is used to count that under the nim-lang.org. I guess it just takes relative url and attaches it to it.

**Pull request merged**
