### PR TITLE
Expose more OpenSSL methods.

### PR DESCRIPTION
**Pull request by treeform**
Add:
* sha types 
* hamc function
* RSA key functions

Sorry about the cdecl crap from before.

### CODE REVIEW

**Comment by shirleyquirk** [comment]
@treeform, how are these supposed to be used?  they don't have {.dynlib.}, was that an oversight or am I missing something?

**Comment by timotheecour** [comment]
should be fixed like this: https://github.com/timotheecour/Nim/issues/64#issuecomment-744722473

**Comment by treeform** [comment]
Here is how I use them, they work for me:
https://github.com/treeform/quickjwt/blob/master/src/quickjwt/crypto.nim

**Comment by timotheecour** [comment]
@treeform it's still wrong, as you can see in this example:
```nim
import std/openssl
discard EVP_sha224()
```
nim r -d:ssl --lib:lib t12185.nim

Undefined symbols for architecture x86_64:
  "_EVP_sha224", referenced from:


and it works after:
```
diff --git a/lib/wrappers/openssl.nim b/lib/wrappers/openssl.nim
index 1a8893957..1930b3450 100644
--- a/lib/wrappers/openssl.nim
+++ b/lib/wrappers/openssl.nim
@@ -693,7 +693,7 @@ proc EVP_sha1*(): EVP_MD      {.cdecl, importc.}
 proc EVP_dss*(): EVP_MD       {.cdecl, importc.}
 proc EVP_dss1*(): EVP_MD      {.cdecl, importc.}
 proc EVP_ecdsa*(): EVP_MD     {.cdecl, importc.}
-proc EVP_sha224*(): EVP_MD    {.cdecl, importc.}
+proc EVP_sha224*(): EVP_MD    {.cdecl, importc, dynlib: DLLUtilName .}
 proc EVP_sha256*(): EVP_MD    {.cdecl, importc.}
 proc EVP_sha384*(): EVP_MD    {.cdecl, importc.}
 proc EVP_sha512*(): EVP_MD    {.cdecl, importc.}
```

the fact that it works for you could be due to some other reason (eg some other proc forcing a dlopen of ssl, and then `dlsym` being resolved globally) which isn't robust

**Comment by treeform** [comment]
You right they should have dynlib added.

**Pull request merged**
