### PR TITLE
Add the hasKey proc to the sharedTable

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by cheatfate** [comment]
`hasKey` and `contains` procedures for shared tables will generate race condition. Its why this procedures not present in `SharedList`.

**Comment by data-man** [comment]
@cheatfate 
Thanks!
I added the try / finally block.
So is it correct?

**Comment by Araq** [comment]
In a concurrent setting you cannot use ``hasKey`` for much, it just invites race conditions. Think about it.

**Comment by data-man** [comment]
```nim
import sharedtables

var
  thr: array[0..4, Thread[tuple[a,b: int]]]
  t: SharedTable[int, int]
  
t.init

proc threadFunc(interval: tuple[a,b: int]) {.thread.} =
  for i in interval.a..interval.b:
    if i notin t:
      t[i] = i

for i in 0..high(thr):
  createThread(thr[i], threadFunc, (i*10, i*10+5))

joinThreads(thr)

for i in 0..high(thr):
  if i in t:
    echo i
```

Works as expected.
What's wrong?

**Comment by Araq** [comment]
Contrived example: since you know the intervals are disjoint you don't need the 'notin' check at all anyway.

**Comment by data-man** [comment]
Ok, other test.
```nim
import sharedtables, threadpool

const
  N = 50
  
var
  t: SharedTable[int, int]
  
t.init

proc add(a, b: int) =
  for i in a..b:
    if i notin t:
      t[i] = i

spawn add(0, N)
spawn add(5, N - 1)
spawn add(10, N - 5)
spawn add(20, N - 10)
  
for i in 0..N:
  if i in t:
    echo i
```

**Comment by dom96** [comment]
On a side note, why don't we just have a ``get`` proc that returns an ``Option[T]`` instead of this weird ``withKey`` stuff?

**Comment by Araq** [comment]
Because an Option[T] is slower and more tedious to work with.

**Comment by Araq** [comment]
> Ok, other test.

That's the logical races we don't want to encourage, yes. Note that 

```nim

if i notin t:
      t[i] = i
```

Is **not atomic** since the lock covers the ``notin`` and then the lock is grabbed again for ``[]=``.

**Comment by data-man** [comment]
@Araq 
Implementation of hasKey is correct or not? :-)

**Comment by cheatfate** [comment]
Implementation is correct, but there no use-case for it in multi-threaded environment, even your tests are wrong.
Problem can be happen between calls to `hasKey()` and `[]=()`. When you got result from `hasKey()` this result become unreliable, just because `thread switch` can happen and other thread can update instance of your shared table with same key.

**Comment by data-man** [comment]
@cheatfate 
Thanks for explanation!
I need this proc for my PR #6936.

**Comment by data-man** [comment]
@cheatfate 
Of course, I saw this template, but I think that for the API's consistency the sharedTable should have as much more in common with the Table.

**Comment by RedBeard0531** [comment]
> but there no use-case for it in multi-threaded environment

@cheatfate  Isn't this still useful if there is separate synchronization to ensure there are no concurrent writers? For example, if it is part of a larger structure that already needs locking. Or is this still unsafe in that scenario?

Also, doesn't mget have the same problem? mget actually seems worse since if someone deletes the key you'd be working with a dangling pointer. It seems like it is only safe to use mget if you have external synchronization.

**Comment by cheatfate** [comment]
@RedBeard0531,

> @cheatfate Isn't this still useful if there is separate synchronization to ensure there are no concurrent writers? For example, if it is part of a larger structure that already needs locking. Or is this still unsafe in that scenario?

Of course if you have separate synchronization you will be safe, but not everybody around is so smart, so to be safe its better not to have `armed rifles` in shared tables.

> Also, doesn't mget have the same problem? mget actually seems worse since if someone deletes the key you'd be working with a dangling pointer. It seems like it is only safe to use mget if you have external synchronization.

`mget` returns you copy of `value` stored inside of shared table, and it obtaining it in safe manner. So even if it got deleted, `value` will still be reliable.

**Comment by cheatfate** [comment]
@data-man,

> @cheatfate
> Of course, I saw this template, but I think that for the API's consistency the sharedTable should have as much more in common with the Table.

Sometimes its impossible to save API consistency... and this is right this case. Because its better to give API which is safe and don't allow others to do `logic mistakes/bugs`.

**Comment by RedBeard0531** [comment]
> mget returns you copy of value stored inside of shared table

No it doesn't, it uses `var` return which is basically a pointer: https://github.com/data-man/Nim/blob/9b8c4457cb8e0a462923c020fe92cd5453ead04e/lib/pure/collections/sharedtables.nim#L120

Also, I think my initial reading was wrong and just *inserting* is enough to cause a dangling pointer if [enlarge](https://github.com/data-man/Nim/blob/9b8c4457cb8e0a462923c020fe92cd5453ead04e/lib/pure/collections/sharedtables.nim#L32-L46) is called.

I guess I see the main advantage of SharedFoo is that they use the shared heap so it is safe to write to them from any thread *once synchronization has been established*. The fact that they are self-synchronizing may be a benefit, but at least in my experience, that is rarely enough so you usually end up needing external synchronization anyway. The exception to this is a table that can be read without locking. But that doesn't apply to SharedTable. That said, most of my multithreading experience is in C++, so maybe the situation is different in nim.

**Comment by cheatfate** [comment]
Then, you are right and SharedTables already has `armed rifles`.

P.S.
I'm not recommend to use `SharedTable[T]`, its better to make your own implementation...
1. `shared heap` uses single lock to allocate/deallocate memory for you.
2. SharedTable[T] uses single lock to insert/modify/delete.
3. You need to implement one more lock to use `mget`, `hasKey` safely.
Looks not very effective, imho.

**Comment by Araq** [comment]
``mget`` or ``var T`` as a return type in general are unsafe in today's Nim (and will get safer eventually). So it's not a valid remark. The fact remains that ``contains`` is a harmful addition to SharedTable. Shared datastructures that use the shared heap but delegate the locking are more useful, yes, but that's not what SharedTable or SharedList are about. Such a data structure should maybe be called ``UnlockedTable`` to emphasize that you need to do the locking on your own.

**Comment by RedBeard0531** [comment]
FWIW, I think naming is part of what makes the purpose of these types confusing to me. I thought SharedTable was a table that uses the *shared* heap. I'd expect a self-synchronizing table to be named something like ThreadSafeTable. But maybe that ship has sailed.

**Comment by data-man** [comment]
@Araq 
If you think that hasKey can't be useful, I'll close this PR. 
I did as was suggested @cheatfate.

**Comment by Araq** [comment]
> But maybe that ship has sailed.

Maybe not sailed, but come on -- a "shared table" which does no syncronization out of the box would be error-prone. Note that the most common racy constructs have been avoided with the stdlib's design of providing ``containsOrIncl`` etc.

**Comment by Araq** [comment]
Closing since it only invites races.

**Pull request closed without merging**
