### PR TITLE
add wasm32 platform

### PR DESCRIPTION
**Pull request by arnetheduck**
helps nlvm, can be used to add support in std lib

### CODE REVIEW

**Comment by dom96** [comment]
Will there be/is there a `wasm64`?

**Comment by arnetheduck** [comment]
yes: https://webassembly.org/docs/c-and-c++/

**Comment by dom96** [comment]
Add it too?

**Comment by arnetheduck** [comment]
no: "The MVP <https://webassembly.org/docs/mvp/> will support only wasm32;
support for wasm64 will be added in the future to support 64-bit address
spaces [image: :unicorn:]
<https://webassembly.org/docs/future-features/#linear-memory-bigger-than-4-gib>
."

**Pull request merged**
