### PR TITLE
Fixed #4065

### LINKED ISSUE #4065: Wrong result of sort in VM
Code:
```nim
import algorithm

proc ctProc(): int =
    var s = @[488780230'i32, 1932284137'i32, 69951615'i32]
    s.sort(proc (a, b: int32): int = a - b)
    echo s

    assert(s[0] < s[1])
    assert(s[1] < s[2])

const a = ctProc()
```
Compile:
```
nim c --cpu:i386 test.nim
```
or
```
nim js test.nim
```
Result:
```
@[69951615, 1932284137, 488780230]
stack trace: (most recent call last)
test.nim(11)
test.nim(9)              ctProc
lib/system.nim(3351)     failedAssertImpl
lib/system.nim(3343)     raiseAssert
lib/system.nim(2529)     sysFatal
lib/system.nim(2529, 7) Error: unhandled exception: s[1] < s[2]
```

### PR DESCRIPTION
**Pull request by yglukhov**
Please review carefully.

### CODE REVIEW

**Comment by jangko** [comment]
suspiciously looks like very similar with this [one](https://github.com/nim-lang/Nim/pull/3654/files)

**Comment by Araq** [comment]
I fixed it differently, please have a look.

**Comment by Araq** [comment]
Ping @yglukhov

**Comment by yglukhov** [comment]
Indeed, thanks a lot.

**Pull request closed without merging**
