### PR TITLE
fix #20995 Regression in int64 type matching since #20829

### LINKED ISSUE #20995: Regression in `int64` type matching since #20829
### Description

The recent PR #20829 caused a regression in how `int64` is type matched:

```nim
echo int64 is (SomeNumber and not(uint32|uint64|uint|int))
echo int64 is SomeNumber
echo int64 is ((uint32|uint64|uint|int))
echo int64 is (not(uint32|uint64|uint|int))
```

### Nim Version

```nim
Nim Compiler Version 1.7.3 [Linux: amd64]
Compiled at 2022-12-02
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 10b6e4f5b4a119a8fa42f82a24ae7e4b08b2c103
active boot switches: -d:release -d:danger
```

### Current Output

```text
false
true
false
false
```

### Expected Output

```text
true
true
false
true
```

### Possible Solution

_No response_

### Additional Information

_No response_

edit: oops, that new issue form made me _forget_ about the title. :see_no_evil:

### PR DESCRIPTION
**Pull request by bung87**
fix #20995

### CODE REVIEW

**Comment by Araq** [comment]
Please rebase.

**Comment by Menduist** [comment]
I think #20829 also broke our 32 bits CI
https://github.com/status-im/nim-libp2p/actions/runs/3607392800/jobs/6079383156
Will this PR fix it?

**Comment by bung87** [comment]
it will not,  `toUleb` need to be generic proc accept both `uint` and `uint64`

**Comment by bung87** [comment]
> I think #20829 also broke our 32 bits CI https://github.com/status-im/nim-libp2p/actions/runs/3607392800/jobs/6079383156 Will this PR fix it?

yes, I tested locally.

**Comment by bung87** [comment]
I think I'll re map `BiggestInt` `BiggestUInt` to target bit width type in next PR

**Comment by metagn** [comment]
> I think I'll re map `BiggestInt` `BiggestUInt` to target bit width type in next PR

Does this mean they would be equal to `int` and `uint`? I don't think that's what they're meant to be

**Comment by arnetheduck** [comment]
> Does this mean they would be equal to int and uint? I don't think that's what they're meant to be

on 32-bit platforms in particular, it's common to nonetheless have access to a 64-bit type (ditto smaller platforms and 128 bit on 64-bits etc)

**Comment by Araq** [comment]
Don't patch the standard library. Fix the regression. And if it doesn't work, undo the patch until it does. 16bit targets are not as important as keeping freaking `json.nim` working as always.

**Comment by bung87** [comment]
tried in https://github.com/nim-lang/Nim/pull/21019 the problem is smaller type `int32` typerel result to `isConvertible` match to `int` or `int64` or `BiggestInt` cause ambiguous call

**Comment by ringabout** [comment]
Succeeded by https://github.com/nim-lang/Nim/pull/21019

**Pull request closed without merging**
