### PR TITLE
Added icons support for Visual Studio compiler

### PR DESCRIPTION
**Pull request by couven92**

### CODE REVIEW

**Comment by cheatfate** [comment]
Why only for VCC, why not for MinGW too?

**Comment by couven92** [comment]
MinGW is already there

**Comment by dom96** [comment]
What are these res files for?

**Comment by couven92** [comment]
Thats the compiled object file containing the icon, like the koch.res and nim.res files that are already there, but incompatible with VCC

**Comment by couven92** [comment]
Created using `RC /v /fokoch-amd64-windows-vcc.res koch.rc` and similar for nim

**Pull request merged**
