### PR TITLE
exportable pragmas (v2)

### PR DESCRIPTION
**Pull request by timotheecour**
same goal as https://github.com/nim-lang/Nim/pull/13016  but different implementation

```nim
# this PR:
{.pragma: foo, gcsafe, exportc: "bar".}
export foo

# PR 13016
template foo* = {.gcsafe, exportc: "bar".}
```

pros: works with existing user defined pragmas; all that's needed is `export foo`, whereas https://github.com/nim-lang/Nim/pull/13016 required all sons to be of the form `template pragma` eg:
```nim
template myfoo0* = {.exportc: "myfoo0_in_c".} # ok
# {.pragma: myfoo0, exportc: "myfoo0_in_c".} # not ok
template myfoo6* = {.myfoo0, discardable.}
```

## future work (can be done in subsequent PR's):
- [ ]  support directly:
```nim
{.pragma: foo*, gcsafe, exportc: "bar".}
```
- [ ]  allow exporting a pragma even if its sons are not exported
- [ ]  nim doc should show the exported pragmas

### CODE REVIEW

**Comment by Araq** [comment]
Your implementation is rather painless but I worry about the design and the usefulness of this idea. Why not write an RFC? Why do we need this? How should it look like? (Btw we could also have ``.exportPragma`` instead, that wouldn't require a parser change.)

**Comment by timotheecour** [comment]
example use case: avoid `include` (which has many issues, eg see https://github.com/nim-lang/Nim/pull/11865: `why not use include?`); for example, simply adding `proc fun(): int {.exportc.} = 123` in  inclrtl.nim makes nim un-compilable due to multiply defined symbols; there are many other different kinds of issues that have already been discussed.

after this PR and another one to update inclrtl.nim you'd be alble to replace:
```nim
include system/inclrtl
```
by:
```nim
import system/inclrtl
```
or:
```
from system/inclrtl import rtl
```

> Btw we could also have .exportPragma instead, that wouldn't require a parser change.)

that'd be a weird special case that one has to learn; I'd rather wait for a subsequent PR that adds support for `{.pragma: foo*, bar .}` and in the meantime `export foo` is available; furthermore, allowing `export foo` is needed anyways for DRY reasons as was mentioned recently in another issue

**Comment by Varriount** [comment]
> I'd rather wait for a subsequent PR that adds support for {.pragma: foo*, bar .}

Then why not implement that, or wait for an implementation? If possible, it's better to implement the final design, rather than go through multiple work-around implementations.

**Comment by timotheecour** [comment]
merged what I needed inside https://github.com/nim-lang/Nim/pull/13016, closing

**Pull request closed without merging**
