### PR TITLE
fix #22492

### LINKED ISSUE #22492: docs: Search CSS broken on devel
### Description

This occurs on https://nim-lang.github.io/Nim, not on https://nim-lang.org/docs/, and appears to be a recent regression.

### Nim Version

N/A

### Current Output

_No response_

### Expected Output

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by hamidb80**
remove `position: sticky` for `div.search_results`

### CODE REVIEW

**Comment by ringabout** [comment]
Seems to be a regression => https://github.com/nim-lang/Nim/pull/22394
You need to change the testproject as well.

**Comment by hamidb80** [comment]
it's now much better

**Comment by bung87** [comment]
why the issue says "css broken" ?

**Comment by bung87** [comment]
I see, it should disappear when clear input box or click outside and give a `x` button. I'd suggest just revert that PR if want to back to before other than improve current implementation.

**Comment by hamidb80** [comment]
> it should disappear when clear input box

it disappears when input is empty

> or click outside and give a `x` button

I guess the people who come to the documentation are not ordinary people,
they are programmers, so I think this is acceptable as a quick fix

**Comment by bung87** [comment]
> it disappears when input is empty

no, it only handled keyboard event, not when user click the search box cancel button.

so the original issue is about it not displayed the way as before

**Comment by ringabout** [comment]
@hamidb80 Hi, would you please show some screen shots or recording of what it actually works like? Thanks!

**Comment by hamidb80** [comment]
> would you please show some screen shots?

Hey

https://github.com/nim-lang/Nim/assets/33871336/56275e02-2083-403a-a77d-2339a035a97d

**Pull request merged**
