### PR TITLE
Less ropes

### PR DESCRIPTION
**Pull request by krux02**
after I did performance measurements I got confirmed, that ropes are causing a lot of performance problems and memory overhead. I already tried once to get rid of ropes locally, but it did not work out. Formatting ropes requires all arguments to be ropes as well. So everything that is passed to rope formatting needs to be wrapped in a rope object as well. And this is also where I want to break the dependency of ropes. I started to transform ropecg, that it can handle both rope arguments and string arguments without requiring the string argument to be wrapped in a temporary rope object. For this I transformed ropecg into a macro that works very similar to the macro used in `strformat`. This macro however requires that all format strings are known at compile time. For the most part this was already the case, but the way the format string was forwarded made the compiler complain. So most changes in the diff here are there to make the ropecg macro know about the format string argument at compile time. Here and there are things left that can be made prettier.

## improvements

 * format strings are checked at compile time
 * ropecg allows arguments of strings integers and ropes
 * an overload of ``cgFormatValue`` can extend ropecg for any type.
 * many intermediate ropes are not allocated anymore.

## new constraints

 * ropecg needs to know the format string at compile time

### CODE REVIEW

**Comment by disruptek** [comment]
If it's not too much trouble, is there a way for us to inspect or reproduce the performance measurements?

**Comment by cooldome** [comment]
Not sure if this option was considered:

It is possible to define move constructors for ropes to avoid multiple stringcopies, for example there is:
```nim
proc rope*(s: string): Rope
```
add move equivalent:
```nim
proc rope*(s: string{call}): Rope
```
and use `shallowCopy` inside.

There is
```proc `&`*(a: Rope, b: string)```
add
```proc `&`*(a: Rope, b: string{call})```


All of the codegen would benefit

**Comment by krux02** [comment]
> If it's not too much trouble, is there a way for us to inspect or reproduce the performance measurements?

```
echo 'passC:"-fno-omit-frame-pointer"' >> compiler/nim.cfg
koch boot -d:release
perf record -g nim c --compileOnly compiler/nim
# then one of the following commands
perf report -g "graph,0.5,callee"
perf report -g "graph,0.5,caller"
```

@cooldome 
>It is possible to define move constructors for ropes to avoid multiple string copies

But that doesn't help a lot. You cannot move the content out of string literals, and that is what we have a lot of. Many ropes are ropes like the following ``rope"NIM_NIL"`` or ``rope"{"``. A lot of ropes are also temporary ropes converted from an ``int``. Whith my chages I enable it to circumvent the temporary ropes entirely.

> Do we have any codegen performance numbers before and after this improvement change?

For current performance numbers, look into perf above. It will tell you where all the new objects come from. But there are no numbers for after this patch, because I don't expect any performance improvement yet. All this PR does right now is to provide a foundation so that more efficient string processing can be used.

Don't get me wrong here, ropes are a very powerful type of string that has it's use case, but using rope everywhere for everything has it's price. All I want with these changes is to allow strings to be used when it makes sense. Don't force every part of the code generator to use ropes for everything.

**Comment by Araq** [comment]
> If it ever worked, hot code reloading is now broken. The patch that was merged into devel changed the carfully created format constants into runtime values -> not compatible.

Sure it worked, there are test cases for it...

**Comment by krux02** [comment]
CI complains about the following error:
```
Error: unhandled exception: /Users/andreasrumpf-mac/projects/nim/compiler/sigmatch.nim(2236, 18) `n.sons[a].sons[0].kind == nkEmpty and n.sons[a].sons[1].kind == nkArgList and
408    len(n.sons[a].sons[1]) == 0`  [AssertionError]
```

but I cannot reproduce this error on my machine. I also only touched the code generator, not nothing that changes the AST.

**Pull request merged**
