### PR TITLE
`outparam`: allows to call in-place a proc with `var result` ; fixes #RFCs/issues/62

### PR DESCRIPTION
**Pull request by timotheecour**
* fix https://github.com/nim-lang/RFCs/issues/62; see motivation + examples in that RFC

* see unittests: toutparams.nim

here's the simplest example: the `result` param is "lifted" into a return value:
```nim
proc normalizePath*(result: var string) {.outparam.} = ... # in osproc.nim
doAssert normalizePath("//foo") == "/foo"

proc addQuoted(s: var string, suffix: string) {.outparamAs(s).} = ...
var s = "beginning"
addQuoted(s, "foo")
doAssert s == "beginningfoo"

# can now be also used as:
doAssert addQuoted("beginning", "foo") == "beginningfoo"
doAssert addQuoted(suffix = "foo bar") == "\"foo bar\""
```

it should work with every parameter combination, eg parameter groups, with generics, with custom name instead of `result`
```
proc fun8*(a, b, path, c: var string, d, e = 13) {.outparamAs(path).} = result.add $(a, b, c, d, e)
```

### CODE REVIEW

**Comment by GULPF** [comment]
> addQuoted(s, "foo")
> doAssert addQuoted("beginning", "foo") == "beginningfoo"

I don't like having different semantics depending on the argument being `T` or `var T`. The stdlib explicitly avoids it by using proc pairs like ` normalizePath`/`normalizedPath`. The stdlib shouldn't encourage this kind of overloading imo.

**Comment by Araq** [comment]
The stdlib gets criticized a lot. If a feature like this doesn't require a language change, it should be first published as a Nimble package and then see some serious usage in some projects before we can consider it for the stdlib.

**Comment by Wh1teDuke** [comment]
It is more useful to make it work akin to the old .this pragma. In practice, naming the out variable as "result" is more than enough.
```nim
{.outparam:result.}
proc normalizePath*(result: var string) = ...
proc addQuoted(result: var string, suffix: string) = ...
```

**Comment by Araq** [comment]
We now have ``sugar.outplace`` that can do a comparable thing.

**Pull request closed without merging**
