### PR TITLE
fixes #21704; remove nfIsRef for genLit in VM

### LINKED ISSUE #21704: [nimscript] local variable is a hidden global with strformat and conditional branch and string in-place append &=
It's a bit hard to describe this bug, but somehow a combination of strformat + if/else when initializing a variable + `&=` (string in-place append) accesses a hidden global.

This can be reproduced in nimble. The file needs to be a `.nims`. In a `.nim` there is no issue.

```nim
import std/strformat

const testDesc: seq[string] = @[
  "tests/t_hash_sha256_vs_openssl.nim",
  "tests/t_cipher_chacha20.nim"
]
const benchDesc = [
  "bench_sha256",
  "bench_hash_to_curve",
  "bench_ethereum_bls_signatures"
]

proc setupTestCommand(flags, path: string): string =
  return "nim c -r " &
    flags &
    &" --nimcache:nimcache/{path} " & # Commenting this out also solves the issue
    path

proc testBatch(commands: var string, flags, path: string) =
  commands &= setupTestCommand(flags, path) & '\n'

proc setupBench(benchName: string): string =
  var runFlags = if false: " -r "
                 else: " " # taking this branch is needed to trigger the bug

  echo runFlags # Somehow runflags isn't reset in corner cases
  runFlags &= " --passC:-Wno-stringop-overflow --passL:-Wno-stringop-overflow "
  echo runFlags

  return "nim c " &
       runFlags &
       &" benchmarks/{benchName}.nim"

proc buildBenchBatch(commands: var string, benchName: string) =
  let command = setupBench(benchName)
  commands &= command & '\n'

proc addTestSet(cmdFile: var string) =
  echo "Found " & $testDesc.len & " tests to run."

  for path in testDesc:
    var flags = "" # This is important
    cmdFile.testBatch(flags, path)

proc addBenchSet(cmdFile: var string) =
  echo "Found " & $benchDesc.len & " benches to compile."
  for bd in benchDesc:
    cmdFile.buildBenchBatch(bd)

proc task_bug() =
  var cmdFile: string
  cmdFile.addTestSet() # Comment this out and there is no bug
  cmdFile.addBenchSet()

task_bug()
```

Output is
image

```
Found 2 tests to run.
Found 3 benches to compile.
 
  --passC:-Wno-stringop-overflow --passL:-Wno-stringop-overflow 
  --passC:-Wno-stringop-overflow --passL:-Wno-stringop-overflow 
  --passC:-Wno-stringop-overflow --passL:-Wno-stringop-overflow  --passC:-Wno-stringop-overflow --passL:-Wno-stringop-overflow 
  --passC:-Wno-stringop-overflow --passL:-Wno-stringop-overflow  --passC:-Wno-stringop-overflow --passL:-Wno-stringop-overflow 
  --passC:-Wno-stringop-overflow --passL:-Wno-stringop-overflow  --passC:-Wno-stringop-overflow --passL:-Wno-stringop-overflow  --passC:-Wno-stringop-overflow --passL:-Wno-stringop-overflow
```

As you can see `--passC:-Wno-stringop-overflow --passL:-Wno-stringop-overflow` is duplicated 3 times

There are many changes that avoid this bug:
- `    &" --nimcache:nimcache/{path} " & # Commenting this out also solves the issue`
- `runFlags = runFlags & " --passC:-Wno-stringop-overflow --passL:-Wno-stringop-overflow "`
- commenting out `cmdFile.addTestSet() # Comment this out and there is no bug`
- removing the `flags` parameters from `setupTestCommand`

### PR DESCRIPTION
**Pull request by ringabout**
fixes #21704

### CODE REVIEW

**Comment by ringabout** [comment]
The problem is that the same constant has the same store address in VM. For an assignment: var x = "whatever" (`copyValue` is called to assign "whatEver" strLits Node to `x`), if `copyValue` doesn't create a new Node in this case, `x` will use the address of the constant, which gives it the power to change the value of the constant. Either it needs to copy the data at the time of the assignment, or it needs to copy the data at writting, which should be more troublesome.

**Comment by ringabout** [comment]
Wait, I forgot the node is created by newNode in macros, which has nfIsRef included in it's flag, I need to check a little more.

**Comment by Araq** [comment]
Why is it `nfIsRef` to begin with? Strings are not refs...

**Comment by ringabout** [comment]
> Why is it nfIsRef to begin with? Strings are not refs...

I think it is from `newNimNode` and it should be removed from `genLit` since literals are not refs.

**Comment by ringabout** [comment]
```nim
import std/macros

proc foo: NimNode =
  result = newLit("f")

macro fmt(): string =
  result = foo()

static:
  let s0 = fmt()
  var s = "f"
  s.add "u"
  echo (s, s0)
```
In the first phase, `newLit("f")` creates a Node which has the `nfIsRef` flag before the VM evaluates the macros. When expanding the macros into code and runs it, `genLit` takes this node with the `nfIsRef` flag and adds it to the constants, which affects all the constants used at the compile time.

We might remove the flags within the `genLit` proc.

**Comment by ringabout** [comment]
Removing `nfIsRef` from the output of macros seems to make more senses because the NimNode has turned into the actual PNode which shouldn't keep the `nfIsRef` flag, which will be evaluated at the static envs.

**Comment by ringabout** [comment]
Removing `nfIsRef` for the output of macros is harder than I thought.

**Pull request merged**
