### PR TITLE
faster CountTable sort(), optional SortOrder

### PR DESCRIPTION
**Pull request by disruptek**
As long as we are importing algorithm, it seemed reasonable to let the user override the sort order without redefining cmp.  The defaults have not changed.  I'd like to add a test or two for this functionality, but first...

Attempts to modify a CountTable after a sort() don't go well.  In my experiment, with many items, my program appeared to hang.  What about adding an `unsafe` boolean or similar and raising a runtime error in the event of a misbehaving mutate?

### CODE REVIEW

**Comment by disruptek** [comment]
I guess no other changes, then.  Ready for review.

**Comment by Araq** [comment]
Iirc the only thing allowed after ``sort`` is iterating over it since it destroyed the hashing structure. We need a flag that enforces this at runtime. Right? (Not necessarily tied to your PR, of course.)

**Comment by disruptek** [comment]
I think you're right.  A runtime error on anything but iteration is of course a breaking change although misbehaving code is arguably already broken. I think it should go in a separate PR and get a changelog entry, etc.

**Comment by Araq** [comment]
CIs are red because:

[Examples] failed: see /home/travis/.cache/nim/tables_d/runnableExamples/tables_examples.nim

**Comment by disruptek** [comment]
CI passing on Linux and OSX/C++ but not OSX/C?  Sounds unlikely.

**Comment by c-blake** [comment]
Good job @disruptek.  I was just complaining about this ( https://forum.nim-lang.org/t/4738 ) but I should have fixed it instead of just complaining.

I don't know if anyone else would want it, but I was also just in a situation where the keys I was histogramming were ``int``, and I wanted to sort by the key, not by the count to print the distribution "along a numerical axis" the way a graph or chart would look.

Since we're expanding the API (and since ``data`` is private and callers cannot do it themselves) we might want to expand the API to allow sorting ascending/descending by either ``key`` or by ``val`` maybe more along the lines of how the interface to ``proc sort*[A, B](t: var OrderedTable[A, B],..`` is but with a default ``ctCmp`` that does descending by ``val`` the way the old ``CountTable`` worked.

**Comment by disruptek** [comment]
Right, that LLVM word-counting challenge caused the discovery of the performance issue.  In thinking about how to improve the speed of that toy problem, I ran up against the private `data` variable.  I think we should have a general solution to exposing the `data` underlying tables -- it could be as simple as `data*` -- in order to allow for broader use of the structure than envisioned.  Or maybe we just have a separate version of Table designed for hacking, like `UserDict` in Python?  IIRC, sorting `data` via named tuple field accessor was about 3x slower. :frowning_face: 

Maybe `sort` operations on `CountTable` apply the `immutable` flag we discussed above, and subsequently `expose` the data for twiddling by the user.  That `expose` could be callable without regard to sort, too, in the event that you're ready to dispense with table accesses, turn the lights down low, and get intimate with your tuples. :wink: 

I feel like the failure of `CountTable` here was sorta inexplicable and disappointing from the perspective of a novice coder trying to see what Nim is capable of.  Your analysis in the forum post is pretty detailed -- nice work! -- but to me, it's just one of many performance concerns we should be trying to balance and optimize.  I guess Nim might not be at a point where speed holds greater sway over design than semantics, but that doesn't mean we couldn't be aware of these things.  Is it worthwhile to build a simple performance testing suite and start watching for regressions?  I've just begun playing with `nimprof`, but it's pretty cool and should make an easy base for an automated performance monitor.

I'll add an overload to specify `cmp` as in `OrderedTable` and we can bikeshed it in _that_ PR. :+1:

**Comment by c-blake** [comment]
All sounds good to me.  Do that PR and we'll take it over there.

About the other things, honestly, I often just do `inc(mgetOrPut(key, 0))` with a regular `Table`.  `CountTable` does exactly two things better - one is the sorting and the other is using the counter itself to indicate "empty" vs "occupied" instead of a hash code slot which saves memory.  You've worked on the first thing.

That second thing is a little more of a mixed bag depending on keys. For large keys (or any key where `==` costs a lot), the hash code field in regular `Table` serves as a "comparison prefix".  This can save a lot of work.  You only call `==` if the full 64-bit hash codes are equal.  To a very good first approximation, you only call `==` on the key once per successful find because *full* hash code collisions, while possible, are super rare unless you have a truly terrible hash function. ("Reduced to table address space" indices are different since they are only a small subset of the 64 bits.)  Inserts are typically unsuccessful finds that do zero `==` calls (unless you are `add`ing a key that exists).  (Like most search algos, a failed lookup for a key tells you where it belongs.)

So, in light of all that, it should be clear that a regular `Table` could easily outperform `CountTable` in time but not in memory on keys with expensive `==`, such as URIs, lines of text in files, etc.  But only `CountTable` has `sort`. :-(

Personally, in mostly non-closed-source code bases like Nim, I am in favor of public by default and only very judicious hiding of visibility when you think you might want to change internals.  In this case, it seems VERY unlikely that the backing object for any of the tables will ever be something besides a `seq[]`.  If it were, performance characteristics would change too much.  Giving client code the access rights to `data` (& responsibility to know what its doing!) seems right to me, either just via `*` or elsewise.  I don't know what people might want to do besides `sort` or iterate, though.   Maybe some "forensics" might want to map out lengths of empty gaps in the table?  Generality would argue for `data*`, but if @Araq objects, you could also just add a `sort` to regular `Table`, too.  Then you could easily compare performance instead of listening to my overlong theoretical explanations.  [ And I didn't even mention eliding the hash code entirely for `int`-like keys until now! ;-)  I think per-instance Robin Hood would be more helpful.  I have a Nim impl of that in a different context I can contribute if desired. ]

**Comment by disruptek** [comment]
FWIW (not much!), I'd suggest that if there's an application in the compiler where a RH hash would yield a performance benefit, we should take this opportunity to introduce it to the stdlib, use it in the compiler (and stdlib, if it helps), and monitor its performance.  Otherwise, I'm for making it an optional library.  But, this is based upon my stdlib-is-for-the-compiler ideology, which I'm aware is unpopular and not the direction @Araq wants to go...  :grin:

In the absence of other feedback, the patch that adds immutability to (certain) sorted tables (in certain states) can also add sorting to regular tables and we can consider exposing `data` in a separate change, if that subsequently meets a concern that we cannot better meet otherwise.

**Comment by c-blake** [comment]
Another thing you might consider is enabling immutability (i.e. disabling mutation) transiently during iteration as that leads to undefined results.  Python raises an exception. I think that you might want to guard all that immutability checking stuff with a `when defined(release)` or something similar.

RH-applicability-wise, in tests I've done it tends to cost about 10-15% in successful searches (get/delete) and save about 45% in unsuccessful searches (insert/resizing).  That makes total sense since the probe sequence winds up sorted by hash code and you can stop about halfway on average.  It also makes the probe length close to the same for all keys.  So, hot spot bad hashes get helped, but generally bad hashes still slow everything down.  There are plenty of well mixing 5..6 cycles + (< 0.25 cycles/byte)*len hashes around, though.  So, I think of RH as mostly as an optimization for insert/resize workloads.  So, a per instance flag (perhaps defaulting to RH on) makes sense to me.  Then heavy RO loads don't get penalized.

**Comment by c-blake** [comment]
One other thing of interest, if worried about too weak hash functions, is a test (perhaps also guarded by a `when defined`) of the probe sequence length.  For the regular linear probing we do now, there is a 1987 paper by Pittel that derives a formula.  I use said formula in `proc find` in my https://github.com/c-blake/suggest/suggest.nim and rate limit warnings by only spewing at new maxes.  Could also just have a counter and never emit more than one message per instance.  There could still be a lot of instances, though.  It's not clear where they should be sent, e.g. stderr.  Without messages things just get slow in a way probably hard for lot of people to analyze, but messages from core library constructs can be iffy for other reasons.

**Comment by Araq** [comment]
> Generality would argue for data*, but if @Araq objects, you could also just add a sort to regular Table, too. 

The ``data: seq[tuple]`` might be changed into ``data: tuple[seq, seq, seq]`` for better memory usage and so it seems unwise to export this field directly. We could have a template accessor though and explicitly mention in the docs that it's an unstable API.

In general I'm a fan of Python's newer "insertion ordered dicts by default" implementation. A standard library does not have to be about the "fastest table implementation ever" (for which workloads?), it should be about correctness, convenience, safety.

**Comment by c-blake** [comment]
Fair enough Re: data export.  Re: correctness/safety, any thoughts on overlong probe sequence messages ("performance safety" for lack of a better phrase) or immutability during iterations?  Re: priorities, the efficiency of programming languages are often judged by their stdlib efficiency, rightly or wrongly.

**Comment by Araq** [comment]
> any thoughts on overlong probe sequence messages 

We tried to get away with BTrees as the goto default "table" data structure but according to @krux02 their performance simply isn't there (yeah, I know, @c-blake could have told me ;-) ) so I'm afraid we need to follow the others and do something like Robin hood hashing or similar. 

> immutability during iterations?

Also something we need to do, yes.

> the efficiency of programming languages are often judged by their stdlib efficiency, rightly or wrongly.

True and we might want to have a properly documented  debug/performance/safety split instead of our current debug/release split. Whether performance is worth trading for "safety" depends on the application.

**Pull request merged**
