### PR TITLE
complete future only once in `or` (fixes #8982)

### LINKED ISSUE #8982: Operator `or` causes a future to be completed more than once
Following code:
```nim
import asyncdispatch

proc failingAwaitable(p: int) {.async.} =
    await sleepAsync(500)
    if p > 0:
        raise newException(Exception, "exception")

proc main() {.async.} =
    let fut = failingAwaitable(1)
    try:
        await fut or sleepAsync(100)
        if fut.finished:
            echo "finished"
        else:
            echo "timeout"
    except:
        echo "failed"

asyncCheck main()
runForever()
```
uses operator `or` defined in [here](https://github.com/nim-lang/Nim/blob/devel/lib/pure/asyncfutures.nim#L366). When one of the future fails (like in above test case) the result future is complete twice - once using `complete()` and once using `fail()`. I propose following implementation of operator `or`:
```nim
proc `or`*[T, Y](fut1: Future[T], fut2: Future[Y]): Future[void] =
    ## Returns a future which will complete once either ``fut1`` or ``fut2``
    ## complete.
    var retFuture = newFuture[void]("asyncdispatch.`or`")
    proc cb[X](fut: Future[X]) =
      if not retFuture.finished:
        if fut.failed: retFuture.fail(fut.error)
        else: retFuture.complete()
    fut1.callback = cb[T]
    fut2.callback = cb[Y]
    return retFuture
```

### PR DESCRIPTION
**Pull request by narimiran**
Analogous to `and`.
Credits to @k0zmo for proposing the solution.

fixes #8982

### CODE REVIEW

**Comment by krux02** [comment]
can you add a test please? if you can by appending to an existing test in a nice way.

**Comment by narimiran** [comment]
> can you add a test please? if you can by appending to an existing test in a nice way.

Well this still raises an error in the original example (#8982), but now it is nicer :) So I cannot append to an existing test, but I should definitely make tests.

**Comment by krux02** [comment]
@dom96 I didn't work with futers yet so I can't review these changes, but I would like to have a decision here. I don't quite understand what the `or` operator on futures is supposed to do, especially since the result is of type ``Future[void]``

**Comment by dom96** [comment]
> I don't quite understand what the or operator on futures is supposed to do

I'm not sure what else to say to elaborate on the proc's doc string. 

But yeah, please add a test.

**Comment by dom96** [comment]
Thanks!

**Pull request merged**
