### PR TITLE
Remove duplicate type aliases and redundant inclusions of tyTypeDesc.

### PR DESCRIPTION
**Pull request by mbaulch**

### CODE REVIEW

**Comment by Araq** [comment]
Seems to go into the wrong direction. Usually we like to remove tyTypeDesc from abstractInst but keep it for typedescInst.

**Comment by mbaulch** [comment]
What purpose does typedescInst serve? It's exactly the same value as abstractInst; and typedescPtrs for that matter.

**Comment by Araq** [comment]
typedescInst means "I thought about it and tyTypedesc really needs to be skipped here".
abstractInst means "it predates the tyTypedesc introduction and perhaps should skip tyTypedesc" (but really needs to be reviewed).

**Comment by mbaulch** [comment]
Thanks @Araq, I think I sort of understand. A review may be worthwhile, but could we replace `typedescInst`,  `typedescPtrs` and `abstractInst` with a single const? They add unnecessary complexity, in my view. If a review finds them necessary, they can always be reintroduced: though with separate values of course.

While `abstractPtrs`, `abstractVar`, `abstractRange`, ...etc still exist, `abstractInst` seems to fit in. Perhaps we could add the comment(?):
```nim
# TODO: Review the role of abstractInst. Should it be specialised in some cases?
```

**Comment by Araq** [comment]
As a first step I would remove tyTypeDesc from ``abstractInst`` and see what breaks.

**Comment by mbaulch** [comment]
Okay. Looking at how `abstractInst` is used more generally, I can see that this is quite a big and (thus far) long term task. Your original comments now make sense to me. `abstractX` should stay, but (eventually) without `tyTypeDesc`. `typedescX` versions should be deployed where necessary. I've summarised this discussion [here](https://github.com/nim-lang/Nim/pull/4634) for future reference.

**Pull request closed without merging**
