### PR TITLE
Cleanup interval and timeout procs

### PR DESCRIPTION
**Pull request by planetis-m**
clear/setTimeout procs were using ref ref Timeout. Added more interval overloads. Corrections.

### CODE REVIEW

**Review by dom96 — APPROVED** [review]

**Comment by timotheecour** [comment]
> clear/setTimeout procs were using ref ref Timeout. Added more interval overloads. Corrections.

can you split into 2 PRs:
* 1st one introduces new APIs without introducing a breaking change (non-controversial)
* 2nd one that introduces breaking change to be evaluated separately

**Comment by planetis-m** [comment]
So code that uses ref Interval, will be ref ref object from now on, but since ref Timeout (which was also ref ref object) was used already with not a single complaint, I don't think it breaks anything. Either way, the wrapper was incorrect and needed to be fixed.

**Comment by timotheecour** [comment]
> I don't think it breaks anything

how so? this compiles before PR and doesn't after PR

```nim
import std/dom
var b: ref Interval
b = window.setInterval("console.log(2);", 3)
```
I'm not saying we shouldn't introduce a breaking change here, but I'm saying it's preferable to separate out the non-controversial change (fixing the ref ref issue and API additions) from the breaking change you've introduced, and assess that separately.

Also, breaking changes require at least a changelog entry

**Comment by planetis-m** [comment]
ok I will do it.

**Comment by dom96** [comment]
My understanding is that this code would have been broken at runtime anyway, so breaking its compilation is fine.

**Comment by timotheecour** [comment]
> My understanding is that this code would have been broken at runtime anyway

how so?

**Pull request merged**
