### PR TITLE
[feature] add `unsafeColumnAt` procs, that returns unsafe cstring from InstantRow

### PR DESCRIPTION
**Pull request by ba0f3**
In order to handle binary data returned by `instantRows` iterartors, `InstantRow[]` should return `cstring`

### CODE REVIEW

**Comment by Araq** [comment]
I like it but it's a breaking change. How about we introduce a new ``rowAt`` proc that does the same? Or maybe something with a better name...

**Comment by ba0f3** [comment]
I agree, lemme deal with it lol

**Comment by ba0f3** [comment]
@Araq are `InstantRow{}` operators ok?

**Comment by Araq** [comment]
IMO yes, but let's see what @dom96 says...

**Comment by ba0f3** [comment]
how about `unsafeColumnAt`?

**Comment by Araq** [comment]
There is nothing particulary unsafe about it, when you use it you want a ``cstring`` which is unsafe by definition.

**Comment by dom96** [comment]
> when you use it you want a cstring which is unsafe by definition.

yes, which is why we should reflect that in the function name.

**Comment by ba0f3** [comment]
so what's your opinion?

**Comment by Araq** [comment]
``unsafeColumnAt`` is fine.

**Comment by ba0f3** [comment]
alright, @dom96 please check again. thank you!

**Comment by Araq** [comment]
Needs ``[feature]`` in the commit message as well as a changelog entry.

**Comment by Araq** [comment]
Still needs  a changelog entry.

**Comment by ba0f3** [comment]
I modified the commit message

**Comment by narimiran** [comment]
@ba0f3 you need to mention the changes in https://github.com/nim-lang/Nim/blob/devel/changelog.md

**Comment by ba0f3** [comment]
I did, thank you!

**Pull request merged**
