### PR TITLE
Implemented customizable growth rate to string streams

### PR DESCRIPTION
**Pull request by beef331**
Based off the conversation had here at https://github.com/nim-lang/RFCs/issues/247 and some quick testing on my end threw together this PR. Allows users to specify a growth rate to a `StringStream` to speed up writing.

Probably need to decide on a `float` or `int` growth rate for more control.

### CODE REVIEW

**Comment by Araq** [comment]
What?! "Fewer if statements and caught 1 growth rate [skip ci]"  

Please don't skip ci for crucial things like these!

**Comment by beef331** [comment]
> Please don't skip ci for crucial things like these!

I'm still uncertain if we should use a float or int, which is why I skipped it, did not feel like there was much reason to use the CI in the case of ambiguity.

**Comment by Araq** [comment]
Well "int" of course, what if you're on a CPU that lacks a floating point unit. And then you could not use our precious string streams, pure horror. ;-)

**Comment by timotheecour** [comment]
this needs a reasonable benchmark added to tests/benchmarks/ to justify this
(see tests/benchmarks/readme.md)

**Comment by beef331** [comment]
It does not seem there is presently a benchmarking library, so I've got to ask if it's ok i make the benchmark depend on https://github.com/treeform/benchy , reallistically all the benchmarks could use it unless there is a more prefered library. Atleast it makes sense to have a standard benchmarking library to not require rewritting the timing code for future benchmarks.

**Comment by Araq** [comment]
>  it's ok i make the benchmark depend on https://github.com/treeform/benchy 

Sure, no problems with that.

**Pull request closed without merging**
