### PR TITLE
Added readLink function to the os module

### PR DESCRIPTION
**Pull request by filcuc**
@Varriount 
as you said you can complete it with the windows version

### CODE REVIEW

**Comment by Varriount** [comment]
Please turn the if statement into a while loop with a break - there is a (small) possibility that the size of readlink's result will change between the two calls.

**Comment by Araq** [comment]
@Varriount Totally unrealistic, let's not go down this path.

**Comment by Araq** [comment]
``readLink`` is not a good name for this. My suggestion: ``expandSymLink``

**Comment by kirbyfan64** [comment]
@Araq `readlink` is actually the name of the UNIX tool with same functionality.

**Comment by Varriount** [comment]
@Araq It's not like the fix is anything complicated, and out guards against an otherwise hard-to-trace race condition.

**Comment by filcuc** [comment]
@Araq +1 for expandSymLink

**Comment by Araq** [comment]
@kirbyfan64 Yes, I am well aware that no name in Unix land makes any sense. ``os.nim`` uses proper names everywhere, ``getCurrentDir`` instead of ``pwned``.

**Comment by reactormonk** [comment]
@Araq yes, you're a windows developer and you'd look for `expandSymlink`. But ever Linux developer here would look for readlink, and that's the part that matters more, there aren't too many Windows developers interested in readlink. Also: https://docs.python.org/2/library/os.html#os.readlink and http://ruby-doc.org/core-2.2.2/File.html#method-c-readlink

**Comment by Araq** [comment]
Not every Linux developer knows 1001 Unix commands. Python is more successful than Perl because it is less Unix'y.

**Comment by reactormonk** [comment]
Yet python still uses `readlink`.

**Comment by Araq** [comment]
So then we have posix.readlink which takes a cstring and doesn't throw exceptions and os.readlink which takes a string and throws. Not wise.

**Comment by Araq** [comment]
Also this name clearly predates the internet. 'readlink' makes people think about http requests.

**Comment by reactormonk** [comment]
Imo `readline` should return an `Option[string]` in case it isn't a link.

**Comment by Araq** [comment]
No, in Nim we really use exceptions instead of reinventing exceptions poorly via monads.

**Comment by reactormonk** [comment]
No reinventing here. That's how C did it. The Option/Either monads just add the information that there's an error to the type system, and that you have to check for it instead of silently passing you a `-1` or similar.

I don't have any problems if the wrapper to the `readlink` behaves differently than the `readlink` C function. That's the idea of a warpper.

**Comment by dom96** [comment]
We can still add ``readLink`` to the index even if the procedure is named something else. Let's stop arguing and listen to @Araq.

**Comment by Araq** [comment]
So why do you have a problem if we improve upon the name as well? readlink has nothing do with reading nor with links.

**Comment by kirbyfan64** [comment]
@Araq

It *read*s the contents of a sym*link*...

**Comment by filcuc** [comment]
To be honest i didn't know that the posix module had a readLink function already. If i knew that i wouldn't had written this merge 

However why can we arrive at a compromise. What do you think about "readSymLink'. It think it's already easy for a C unix dev to find it (because it starts with "read") but at the same time it doesn't brake the current naming convention of the module (where procs that handle symbolic links contain "Sym").

For the implementation, given that you made me discover the readLink proc, i think that this function should basically forward to that function. For the same reason the "when" branch should forward to the windows version.

What do you think?

**Comment by Araq** [comment]
> To be honest i didn't know that the posix module had a readLink function already. If i knew that i wouldn't had written this merge

Good.

**Comment by reactormonk** [comment]
Yes, it doesn have `readlink`, the one you used to implement your readlink. But it sucks, because it's C api.

**Comment by filcuc** [comment]
@reactormonk 
i think that's pretty clear where this gonna end

**Comment by dom96** [comment]
I don't think this is the way to handle this.

**Pull request closed without merging**
