### PR TITLE
Make --backend:cpp|js work for :test: code-blocks as well

### LINKED ISSUE #13129: Allow specifying/forcing the compilation backend in Nim for `nim doc`
### Summary

Allow forcing the compilation backend that get enforced on the usual library compilations and also the code block evaluations done by `nim doc` invocations.

### Description

Certain Nim libraries cannot be compiled in _any_ backend the user wants.

A very good example is a wrapper Nim library for a backend-specific library.. e.g. a Nim wrapper for C++ `std::vector`. For such Nim libraries one can force the user to always compile using the `cpp` backend using something like:

```nim
when not defined(cpp):
  {.error: "This library needs to be compiled with the cpp backend.".}
```

But there is not way to force the `cpp` backend when running the `nim doc` command on that library.

For example, this will always fail right now if I run `nim doc` on it.. because `nim doc` is always using the `c` backend to evaluate the code blocks in doc strings:

```nim
when not defined(cpp):
  {.error: "This library needs to be compiled with the cpp backend.".}

{.push header: "<vector>".}

type
  Vector*[T] {.importcpp: "std::vector".} = object

proc newVector*[T](): Vector[T] {.importcpp: "std::vector<'*0>()", constructor.}

# https://en.cppreference.com/w/cpp/container/vector/size
proc size*(v: Vector): int {.importcpp: "#.size()".}
  ## Return the number of elements in the Vector.
  ##
  ## .. code-block::
  ##    :test:
  ##    var
  ##      v = newVector[int]()
  ##    doAssert v.size() == 0
  ##
  ##    v.add(100)
  ##    v.add(200)
  ##    doAssert v.len() == 2

{.pop.}
```

### Failed attempts

I tried putting this in the project's `config.nims`, but the `nim doc` still uses the `c` backend:

```nim
if getCommand() == "c":
  setCommand("cpp")
```

### Suggestion

Make the above NimScript code affect the `nim doc` command too.

### Additional Information
- I was trying to improve my `std::vector` Nim wrapper library [**std_vector**][1], but stumbled upon this limitation where `nim doc` always uses the `c` backend.
- Slightly related issue: https://github.com/nim-lang/Nim/issues/6201
- https://forum.nim-lang.org/t/3089

[1]: https://github.com/kaushalmodi/std_vector

### PR DESCRIPTION
**Pull request by kaushalmodi**
Continues
https://github.com/nim-lang/Nim/commit/9502e39b634eea8e04f07ddc110b466387f42322

Ref:
- https://github.com/nim-lang/Nim/commit/9502e39b634eea8e04f07ddc110b466387f42322#commitcomment-39087584
- https://github.com/nim-lang/Nim/pull/14278

Fixes https://github.com/nim-lang/Nim/issues/13129 .

/cc @Araq @timotheecour Can you please review this?

### CODE REVIEW

**Comment by Araq** [comment]
Well if I write ``nim c`` in the tests, I expect ``nim c``. How about supporting ``nim $backend`` instead?

**Comment by kaushalmodi** [comment]
@Araq May be I wasn't clear.. it is hardcoded to `nim c` here:

https://github.com/nim-lang/Nim/blob/5ce30e0938bdae607fc4b12e0ee6a1bed1e17b4f/lib/packages/docutils/rstgen.nim#L868

**Comment by kaushalmodi** [comment]
If you intend to use the c backend for those tests, this PR won't change anything.

**Comment by Araq** [comment]
It's hardcoded, yes, but I think if I write it down myself your code will be applied anyhow.

**Comment by kaushalmodi** [comment]
> I think if I write it down myself your code will be applied anyhow

Hmm, yes. But are there real use cases where in the same .nim file, you have a mix of `nim c ..` and `nim cpp ..` `:test:` code blocks?

**Comment by kaushalmodi** [comment]
I'll close this PR. I will update my std_vector wrapper with:

```nim
.. code-block:: nim
    :test: "nim cpp -r $1"
```

**Pull request closed without merging**
