### PR TITLE
Remove testutils

### PR DESCRIPTION
**Pull request by Clyybber**

### CODE REVIEW

**Comment by narimiran** [comment]
Note: this should also receive `[backport]` tag when merging.

**Comment by timotheecour** [comment]
If you really are worried about bloating stdlib, you could simply write this patch:
```
## Unstable, experimental API
```
=>
```
## Unstable, experimental API, for internal use only.
```
and avoid having to duplicate/inline its functionality like you did in all the tests where I was using it.

Note that I was intending to use `testutils` in additional test files (eg needed once https://github.com/nim-lang/Nim/pull/13418 is generalized to other table-like modules eg strtabs.nim, compiler/astalgo.nim, compiler/treetab.nim, system/cellsets), and removing `testutils` would just make things a little bit harder. I don't see the point of removing this.

**Comment by Clyybber** [comment]
@timotheecour Its just bloat. It doesn't even save you one line. No such thing should be in the sdtlib or in the codebase generally IMO

**Comment by Araq** [comment]
Sorry but I have to agree with clyybber.

**Pull request merged**
