### PR TITLE
Decode path of HTTP request

### PR DESCRIPTION
**Pull request by yglukhov**
Fixed handling of url-encoded paths.

### CODE REVIEW

**Comment by dom96** [comment]
I would prefer if the ``decodeUrl`` was done in the ``uri`` module. That way it's consistent.

**Comment by yglukhov** [comment]
I was thinking the same, and looked into python's urlparse, and it doesn't do decoding for some reason. So i assumed that they have a reason not to do it (some RFC or something). If you're really confident, that URIs should always contain unescaped paths, then I'll move it to uri. Otherwise i suggest leaving it as is, narrowing affected area.

**Comment by yglukhov** [comment]
Just checked ruby URI parsing, and it behaves the same in python. The path is not escaped.

**Comment by dom96** [comment]
The Go standard libraries' ``url`` type ([defined here](https://golang.org/pkg/net/url/#URL)) specifies both a Path and a RawPath.

I don't see a reason why the ``path`` field in the Nim version cannot contain a decoded path. I don't think a ``rawPath`` field is necessary (it adds complications when stringifying the URL). That being said, a ``getRawPath`` proc addition may be useful (together with that a ``setRawPath`` procedure should also be added).

I also just looked at [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt), it defines "percent-encoding" and has a section titled "2.4.  When to Encode or Decode". I skimmed that section and couldn't find anything which tells us whether we should be decoding the path or not. The fact that it defines "percent-encoding" supports the idea that we should be able to decode the URL in the ``uri`` module.

What do you think?

**Comment by yglukhov** [comment]
dom96, you may be right. But changing existing uri.path property to decoded is a breaking change, and i can't really say that current behavior is somehow inconsistent to justify this change. What we could do is add a `decodedPath` and `decodedPath=` accessors, but again I can't see any pros or cons here, just a matter of taste.

**Comment by dom96** [comment]
You're right. But then we may as well use ``url.path.decodeUrl``, question is whether it's worth a breaking change because of users' expectations. But perhaps users don't expect the path to be decoded. I think most won't even consider it (I certainly didn't :P).

@Araq what do you think?

**Comment by yglukhov** [comment]
> But perhaps users don't expect the path to be decoded.

Did you mean "encoded"?

In any case, users concerned about that will likely expect parsed uri path to remain encoded. Because, thats the behavior of python, ruby, and as i've just checked - php :)

**Comment by Araq** [comment]
I think we should do what the others do.

**Comment by yglukhov** [comment]
Alrighty! Lets merge it then? =)

**Comment by dom96** [comment]
The problem with this PR is that stringifying the resulting URI will result in an incorrect URI being generated because ``uri.$`` does not encode the path.

**Comment by yglukhov** [comment]
Does http server depend on stringifying the uri?

**Comment by dom96** [comment]
@yglukhov Don't think so, but the URI is depended on by users of the asynchttpserver module.

**Comment by yglukhov** [comment]
So then it has to be fixed in jester, right?

**Comment by yglukhov** [comment]
Closing in favour of https://github.com/dom96/jester/pull/50

**Pull request closed without merging**
