### PR TITLE
add SinglyLinkedList.append procs

### PR DESCRIPTION
**Pull request by pacien**

### CODE REVIEW

**Comment by timotheecour** [comment]
isnt everything else called add instead of append?

**Comment by pacien** [comment]
@timotheecour It's called `append` for `DoublyLinkedList` and `*LinkedRing` too, presumably to avoid any ambiguity with `prepend`.

**Comment by pacien** [comment]
[An unrelated test](https://travis-ci.org/nim-lang/Nim/jobs/459738943#L3100) seems to fail on OSX.
Not sure why.

**Comment by Araq** [comment]
Sorry this took so long to merge!

**Comment by timotheecour** [comment]
/cc @pacien @Araq 
> @timotheecour It's called append for DoublyLinkedList and *LinkedRing too, presumably to avoid any ambiguity with prepend.

 I don't see how there'd be ambiguity with `add` and `prepend` ; `add` does always the obvious thing of appending in all other cases.
I suggest we use `add` as the main thing (in DoublyLinkedList and LinkedRing) and keep `append` as a (maybe deprecated) alias

**Comment by Araq** [comment]
You can always add your own ``add`` template/proc for the generic code though. Also ``append`` for singly linked lists should usually be O(n), our singly linked list is a strange beast...

**Comment by timotheecour** [comment]
@pacien 
actually my recommendation was explicitly laid out in docs of system.add: 
```
proc add*[T](x: var seq[T], y: openArray[T]) {.noSideEffect.} =
  ## Generic proc for adding a data item `y` to a container `x`.
  ## For containers that have an order, `add` means *append*. New generic
  ## containers should also call their adding proc `add` for consistency.
  ## Generic code becomes much easier to write if the Nim naming scheme is
  ## respected.
  ##
  ## .. code-block:: nim
  ##   var s: seq[string] = @["test2","test2"]
  ##   s.add("test") #=> @[test2, test2, test]
  let xl = x.len
  setLen(x, xl + y.len)
  for i in 0..high(y): x[xl+i] = y[i]
```

**Pull request merged**
