### PR TITLE
fixes #10200

### LINKED ISSUE #10200: nimpretty doesn't put space around operators like `a<b` => `a < b`
input/output
```nim
proc main() =
  var a = "asdf"
  var i = 0
  while i<a.len and i<a.len:
    return

main()
```

expected output:
```nim
proc main() =
  var a = "asdf"
  var i = 0
  while i < a.len and i < a.len:
    return

main()
```

### PR DESCRIPTION
**Pull request by otofu-tofu**
fixed #10200

### CODE REVIEW

**Comment by Araq** [comment]
Nimpretty doesn't change the spacing around the operators too much but if we agree on https://github.com/nim-lang/Nim/issues/10200 being a bug than this rule should cover every comparison operator and not just "<" and ">".

**Comment by otofu-tofu** [comment]
I made the rule to cover `<=`, `>=`, `==`. But I'm not sure the issue is a bug.

**Comment by narimiran** [comment]
> I made the rule to cover <=, >=, ==.

And there's `!=` too ;)

> But I'm not sure the issue is a bug.

Me neither.

**Comment by Araq** [comment]
It's ready to go if you can please add a test snippet to ``nimpretty/tests/exhaustive.nim``?

**Comment by otofu-tofu** [comment]
Sure. I'll work on it soon!

**Comment by Araq** [comment]
Excellent, thank you!

**Pull request merged**
