### PR TITLE
ctermid missing in android

### PR DESCRIPTION
**Pull request by freevryheid**
seems it's not only android 4 - but also still android 8

### CODE REVIEW

**Comment by Araq** [comment]
ping @couven92

**Comment by couven92** [comment]
According to https://github.com/termux/termux-packages/issues/104#issuecomment-167005228 we could implement `ctermid` as `return "/dev/tty"` for android...

**Comment by Araq** [comment]
@couven92 I don't know what that means nor do I want to know. Please fix it or merge it or close the PR.

**Comment by freevryheid** [comment]
Let's try as suggested. I'll resubmit PR later to address this.

**Pull request closed without merging**
