### PR TITLE
db_odbc - row reading bug fix

### PR DESCRIPTION
**Pull request by jlp765**
Fix row reading procs to not use SQLRowCount, but SQLFetch/SqlGetData until returns SQL_NO_DATA

change SqlCheck() and SqlGetDBMS() to sqlCheck() and sqlGetDBMS() (camelCase consistency)

### CODE REVIEW

**Comment by Araq** [comment]
@coffeepots Please review.

**Comment by dom96** [comment]
Seems #3865 is stepping on this PRs toes.

**Comment by Araq** [comment]
I cannot review this patch. In the past we merged PRs like these but they caused serious regressions. Note that db_odbc is also used for SqlServer, not only for Oracle. Maybe we need to split it into db_oracle and db_sqlserver. @dom96 opinions welcome.

**Comment by dom96** [comment]
See my comment here: https://github.com/nim-lang/Nim/pull/3988#issuecomment-200330495

**Comment by Araq** [comment]
Manually merged.

**Pull request merged**
