### PR TITLE
Fix issue #2245

### PR DESCRIPTION
**Pull request by rogercloud**

### CODE REVIEW

**Comment by Araq** [comment]
Love your work! :-) Can you please also add test-cases and get familiar with our testing infrastructure?

**Comment by rogercloud** [comment]
Yes, of course. 

Actually I'm suffering getting test run on Win10 64-bits system (my develop environment), it keeps reporting "could not load: XXX64.dll". I'm adding them one by one. It's better to include them Nim windows installation package when detecting 64-bit system.

**Comment by Araq** [comment]
Yeah, sorry, I recently changed the DLL names for ultimately a better user experience. We need to get 0.12.0 out that will ship with these DLLs.

**Comment by rogercloud** [comment]
Glad to hear that. : )

I've got the tester running but some tests fail, need I identify and correct them before adding mine tests? 
I guess build status failure on project's front page (windows-64-bit) is caused by this.

**Comment by Araq** [comment]
> I've got the tester running but some tests fail, need I identify and correct them before adding mine tests? 

No. We diff the test results for better or worse. It seems impossible to keep **all** the tests in shape.

**Comment by rogercloud** [comment]
@Araq I don't know any easy way to track memory usage by current thread, so test case for #2367 is missing. If there's some way that I don't know, please tell me. I'll add it later.

**Comment by Araq** [comment]
Check the GC tests, they do track memory usage via getOccupiedMem() iirc.

**Comment by rogercloud** [comment]
Thank you for the advice, add test case for #2367

**Comment by rogercloud** [comment]
@Araq Is the test case meet the requirement?

**Pull request merged**
