### PR TITLE
implement for `index,name in tup.fieldsIndexed` 

### PR DESCRIPTION
**Pull request by timotheecour**
## motivation: see https://forum.nim-lang.org/t/3750

Also, allows a workaround for https://github.com/nim-lang/Nim/issues/7590

## example usage:
```
proc doInit[T]():auto=
  var a: T
  return a

proc len(T: typedesc[tuple]):auto=
  const t=doInit[T]()
  var n=0
  for _ in t.fields:
    inc n
  return n

proc fieldNames[T]():auto=
  const t=doInit[T]()
  var names: array[T.len, string]
  for ind,field in t.fieldsIndexed:
    names[ind]=field
  return names

proc test1()=
  let a=(bar1:1,bar2:2)
  const names=fieldNames[a.type]()
  doAssert names == ["bar1", "bar2"]

  let a2=(foo1:1.4,foo2:"baz")
  const names2=fieldNames[a2.type]()

  ## this would be hard to do without this PR
  for ind,field in a.fieldsIndexed:
    echo (ind,field,a[ind],names2[ind],a2[ind])

test1()
```

## NOTE: this implements `tupInstance.fieldsIndexed` instead of `TupType.fieldsIndexed` 
help welcome to make `TupleType.fieldsIndexed` work, but this could be done in subsequent PR; this is already a big improvement

## NOTE: subtle issue related to bootstrapping:
locally as well as on CI, I'm getting this error:
```
lib\system.nim(2454, 8) Warning: unknown magic 'FieldsIndexed' might crash the compiler [UnknownMagic]
lib\system.nim(2453, 1) Error: implementation of 'fieldsIndexed' expected
```

that's because `FieldsIndexed` isn't considered magic yet;

to make it work locally, i had to comment this from system.nim:
```
iterator fieldsIndexed*[T: tuple|object](x: T): RootObj {.
  magic: "FieldsIndexed", noSideEffect.}
```
then rebuild ./bin/nim, then uncomment, the rebuild.

@Araq  @dom96  Is there a better way?

As for CI, what's the recommended approach? will submitting 2 subsequent PR's (one with `fieldsIndexed` commented, second one uncommented) ?

### CODE REVIEW

**Comment by data-man** [comment]
You need to add new defines to compiler/condsyms.nim
E.g.:
```nim
defineSymbol("nimNewTupFields")
```
And to add:
```nim
when defined(nimNewTupFields):
... there is new iterators
```
to system.nim

**Comment by Araq** [comment]
Yeah what @data-man said, but this is not a good solution, will give you something much better.

**Comment by timotheecour** [comment]
@data-man 

> You need to add new defines to compiler/condsyms.nim

done (with `defined(nimHasFieldsIndexed)`)

@Araq
> Yeah what @data-man said, but this is not a good solution, will give you something much better.

could you elaborate on why that is not a good solution, and what is your proposed solution?

Also, see https://forum.nim-lang.org/t/3750/1#23352 which adds a more general but less convenient `for index in n.rangeCT: body` (with n, index ints known at compile time)
We could have both, as `rangeCT` is indeed more general but less convenient for the common case

**Comment by Araq** [comment]
> could you elaborate on why that is not a good solution, and what is your proposed solution?

It's yet another compiler builtin. With the same effort in the compiler I can make ``for x in mymacro`` work, where ``mymacro`` gets to visit the entire for loop's AST. Then it can rewrite the for loop to whatever it requires, including what you did here. Then these things are all "just a macro away", Nim's inofficial slogan.

**Comment by timotheecour** [comment]
great, would love to try it out once you have something workable (then I'll close this PR)
* so it'll require a (single) compiler builtin right? 

* will it allow to reimplement the following as regular macros?

* fields
* fieldPairs
* fieldsIndexed (this PR's)
* `for index in n.rangeCT: body` (from https://forum.nim-lang.org/t/3750/1#23352)
* regular iterator for loop
* allow arbitrary number of iteration arguments (eg: `for index, key, val in my_custom_macro(arg1, ..., argn) : body`) ?
* allow both runtime loops and unrolled for loops?
* do this with same compile speed and generating as efficient code as current builtins
* avoid current renaming hacks in instFieldLoopBody which cause bugs (eg https://github.com/nim-lang/Nim/issues/7533 and https://github.com/nim-lang/Nim/issues/7590) 

My guess is it would allow all of the above but just asking

**Comment by Araq** [comment]
> My guess is it would allow all of the above but just asking

Yes, it would allow all of these. Some of these will have complex implementations, of course. :-)

**Comment by Araq** [comment]
> great, would love to try it out once you have something workable (then I'll close this PR)

Oh btw, I think you can do that too, you seem to know everything required for that.

**Comment by Araq** [comment]
I implemented an initial version of for-loop macros, please check it out.

**Comment by Araq** [comment]
No feedback. Closing.

**Comment by Araq** [comment]
https://github.com/nim-lang/Nim/blob/devel/doc/manual.rst#L5428

**Comment by andreaferretti** [comment]
Cool!

**Pull request closed without merging**
