### PR TITLE
adds compiler support for object construction shorthand (full fields initializer)

### LINKED ISSUE #418: Object init shorthand
Consider the following object type:

```nim
type
  User = object
    name: string
    age: int
    last_online: float
```

It's very common to write a constructor for such types, some may have many more fields than the above, having to write the name of each field gets tedious:

```nim
proc initUser(name: string, age: int): User =
  User(
    name: name,
    age: age,
    last_online: epochTime()
  )
```

This RFC proposes to implement a short-hand syntax for the object construction syntax to simplify this code:

```nim
proc initUser(name: string, age: int): User =
  User(
    name,
    age,
    last_online: epochTime()
  )
```

The variable names have to match that of the field name, so `User(foo, age)` won't work even if `foo` is a string.

### LINKED ISSUE #517: compiler support for object construction shorthand
## Motivation

The Nim language supports named field names with values to construct an object. It works perfectly fine and is unambiguous, since it's different from function calls or type conversions syntactically.

```nim
type
  Vector = object
    x, y, z: int

var x = Vector(x: 1, y: 2, z: 3)
```

However, compared to function calls which support both named and positional parameters, this way of construction seems not to be succinct and looks redundant. Indeed, it is. The field names are not actually needed, which means we can construct the object using unnamed field values. `var x = Vector(1, 2, 3)` just works. Why not add a shorthand for the object construction and call it a day?

## Description

This RFC proposes a new way of object construction, which makes it handy to construct objects. You can mix it with named field values.

```nim
type
  Vector = object
    x, y, z: int

var x = Vector(1, 2, 3)
var y = Vector(1, y: 2, z)
```

All the fields need to be initialized in order. It means all cases below should give a proper error messages (it might be relaxed in the future).

```nim
var x = Vector(1, 2)
var y = Vector(1, z: 3)
var y = Vector(1, y: 2)
var y = Vector(1, z: 3, y: 2)
```

As to object variants, the discriminator must be known at the compile time because the compiler needs to get hold of the exact selected branch. In the case below, the value of `flag` should be a constant.

```nim
type
  Ciao = object
    id: int
    case flag: bool
    of true:
      num: int
    of false:
      done: bool
    name: string

var x = Ciao(12, true, 1, "123")
```

For historic reasons, an object with a single field cannot be initialized with an unnamed field value. It should always be interpreted as type conversions. The field name needs to be written explicitly in order to construct an object.

```nim
type
  Single = object
    id: int

# var s = Single(12) # which gives type mismatch errors
var s = Single(id: 12)
```

## Backwards Compatibility

It can start from an experimental feature. It might disturb function calls with the same name as the type from other modules, which means the object construction shorthand might take precedence over function calls.

### PR DESCRIPTION
**Pull request by ringabout**
closes https://github.com/nim-lang/RFCs/issues/418
closes https://github.com/nim-lang/RFCs/issues/517

- [x] testing with defaults
- [x] object variants
- [x] private fields visible issues (still doesn't work with the last issue: private fields with generics)
- [x] mixing up with named fields
- [x] proper error messages
- [x] documentation
- [x] refactor `replaceObjConstr` and `filterObjConstr` into one proc returns enums
- [x] retry after failing the construction

```nim
type
  Vector = object
    a: int = 999
    b, c: int

block: # positional construction
  var x = Vector(1, 2, 3)
  echo x

block: # mixed with named parameters
  block:
    var x = Vector(a: 1, 2, 3)
    echo x

  block:
    var x = Vector(1, b: 2, 3)
    echo x

  block:
    var x = Vector(1, 2, c: 3)
    echo x

when false: # not allowed
  block:
     var x = Vector(b: 2, 3)
     echo x

type
  Color = enum
    Red, Blue, Yellow
  Factor = object
    id: int
    case flag: Color
    of Red:
      num: int
    of Blue, Yellow:
      done: bool
    name: string

block:
  var x = Factor(1, Red, 2, "1314")
  echo x

block:
  var x = Factor(1, Blue, true, "1314")
  echo x

block:
  var x = Factor(1, Yellow, false, "1314")
  echo x


type
  Ciao = object
    id: int
    case flag: bool = false
    of true:
      num: int
    of false:
      done: bool
    name: string

block:
  var x = Ciao(12, false, false, "123")
  echo x

block:
  var x = Ciao(12, flag: true, 1, "123")
  echo x

when false:  ## not allowed
  block:
    var x = Ciao(flag: true, 1, "123")
    echo x
```

## Warning

Object constructions with a single unamed field will be interpreted as type conversions, which means

```nim
type
  Vector = object
    a: int

var x = Vector(1)
```

will get a type mismatch error.

### CODE REVIEW

**Comment by AngelEzquerra** [comment]
It would be great to also support the shorthand proposed in this forum post: https://forum.nim-lang.org/t/10018#66156

```
let name = "Jim"
let group = "alpha group"
let p = Person( :name, :group )
```
This would be equivalent to:
```
let name = "Jim"
let group = "alpha group"
let p = Person(name: name, group: group )
```
The idea is to avoid the repetition of the parameter and variable names when they match, which is a pretty common pattern.

**Comment by ringabout** [comment]
```nim
let p = Person( :name, :group )
```
It is not a valid Nim syntax, which means it needs a new syntax support or parser rewrites.

**Comment by Araq** [comment]
`let p = Person( :name, :group )` is also quite ugly. Which is subjective, however colons in written natural language are neither postfix nor prefix but infix.

**Comment by AngelEzquerra** [comment]
> `let p = Person( :name, :group )` is also quite ugly. Which is subjective, however colons in written natural language are neither postfix nor prefix but infix.

The original proposal in the thread was to use equals rather than colons (i.e. `let p = Person( =name, =group )`). Would that be better? It would be not very different to the similar pattern in the strformat "syntax". If not, is there any alternative syntax that you'd like?

I find that assigning a variable to a parameter of the same name is a relatively common pattern in my code, and every time I do it the repetition feels somewhat wrong. It would be nice to be able to avoid it if possible.

**Comment by Araq** [comment]
> Would that be better? 

No, that looks even worse. :-)

> It would be not very different to the similar pattern in the strformat "syntax". If not, is there any alternative syntax that you'd like?

As this PR does it is fine. You can simply leave out the `fieldname: ` and then the object field order is used, for example:

`Vec3(1, 2, 3)` or `Vec3(1, y: 2, 3)` etc. Named fields can be mixed with unnamed fields as you see fit, just like named arguments inside function calls.

**Comment by zedeus** [comment]
The RFC mentioned proposes automatic mapping of variables to fields with the same name, like in JavaScript. This PR however is a different kind of shorthand that ignores field names and cares only about position (unless explicitly specified). These are two different, probably incompatible, solutions. Why was this chosen instead of the proposed solution in the RFC? That solution is closer to the current object construction syntax, e.g. `User(name: name)` becomes `User(name)`. This also wouldn't break if the field order changes due to an optimization or refactoring which could silently break programs in cases where fields of the same type are switched around.

**Comment by ZoomRmc** [comment]
Sorry for writing everywhere at once, but doesn't this change require its own RFC? 

I have some doubts about this syntax which I expressed in [#418](https://github.com/nim-lang/RFCs/issues/418) this PR links to, even though this implementation is of a wider scope than the RFC.

PS: I deeply respect the hard work @ringabout has been doing for a while, so don't take it personally, the criticism has nothing to do with the quality of what's offered here.

**Comment by treeform** [comment]
I think this is a great addition to the language. I know I will use it as soon as its available. I think it will really complement the default object values we have going out as well.

**Comment by Araq** [comment]
I guess this should be enabled via another `--experimental` switch but other than that, it would be nice to have for 2.0.

**Comment by Araq** [comment]
@ZoomRmc You're right that it needs an official RFC but please be assured that I've read every concern carefully.

**Comment by ringabout** [comment]
**Edited**
done => https://github.com/nim-lang/RFCs/issues/517

Sure thing, I will write the RFC.

**Pull request closed without merging**
