### PR TITLE
I64 magics gone

### PR DESCRIPTION
**Pull request by r-ku**
As Araq gave it a go here is I64 magics cleanup. They were removed because they are identical to non-I64 versions.

One thing to note that i did not touch mUnaryMinusI64 due to this:

      mUnaryMinusI: "((NI$2)-($1))",
      mUnaryMinusI64: "-($1)",

Was not exactly sure if that needs touching. If it does please give instructions what change is needed exactly.

Also i did not run tests as for some reason that is broken:

    ./koch tests
    <...>
    <...>/Nim/tests/testament/tester.nim(15, 22) Error: cannot open 'compiler/nodejs'

That happens to nim's devel branch so my changes are not at fault. Assistance on getting tests running would be appreciated. Yes, i tried to delete repository and check out new one and run tests without any thing done to repo, no love.

### CODE REVIEW

**Comment by Araq** [comment]
> Also i did not run tests as for some reason that is broken

Well guess what. Don't install 'nim', but add it to your PATH like we suggest anyway.

**Comment by Varriount** [comment]
@araq What do you mean by 'install'?

**Comment by Araq** [comment]
@Varriount Copying crap into /usr/bin so the compiler cannot resolve 'compiler/' properly.

**Comment by r-ku** [comment]
Ohh so thats the culprit. None of the docs outline these problems. Well good to know how to do it the right way.

I also ran tests. Test results produced by devel and I64-magics-gone branches are identical.

**Comment by ozra** [comment]
Hmm, that compiler/nodejs might be a fault of mine - I'll check.

**Comment by r-ku** [comment]
No it was my fault of installing nim. File was there and nothing wrong with it at all. Uninstalling compiler and putting Nim/bin on path fixes problem.

**Pull request merged**
