### PR TITLE
documents changes on byref and bycopy

### PR DESCRIPTION
**Pull request by jmgomez**

### CODE REVIEW

**Comment by Araq** [comment]
Pre-existing issue: It is actually unsound to use these pragmas on tuples.

**Comment by jmgomez** [comment]
> Pre-existing issue: It is actually unsound to use these pragmas on tuples.

Do you mind to elaborate a bit more on it? Maybe I can do something about it.

**Comment by Araq** [comment]
Something like:

```nim

type
  TupA = (string, int, float, int)
  TupB {.bycopy.} = (string, int, float, int)

var x: HashSet[TupA]
x.incl ("a", 3, 4.4, 4)

var y: HashSet[TupB]
y.incl ("a", 3, 4.4, 4) # watch the .bycopy disappear for this `incl` because the compiler likes to merge generic instantiations


```

**Comment by jmgomez** [comment]
I see, thanks. Will create an issue to keep track of it.

**Pull request merged**
