### PR TITLE
allow setting template/macro recursive evaluation limits

### PR DESCRIPTION
**Pull request by jcosborn**

### CODE REVIEW

**Comment by Araq** [comment]
That seems to create a set of Nim dialects. Is this really necessary? :-(

**Comment by jcosborn** [comment]
I am hitting the template eval limit, so having some way to set it is useful.

**Comment by data-man** [comment]
I'd prefer this parameters in nim.cfg

**Comment by jcosborn** [comment]
Yes, it works in nim.cfg and from nimscript configs too.

**Comment by Araq** [comment]
I'd rather increase it to 500 instead of making it configurable.

**Comment by jcosborn** [comment]
Ok, I used 1000 as a limit just to be safe.

**Pull request merged**
