### PR TITLE
Add timeout for asyncdipatch

### PR DESCRIPTION
**Pull request by tulayang**
Add timeout check for `asyncdipatch.poll`. The default timeout is 120 seconds. Every poll, look up the expired descriptors from an efficient doubly link list that sorted by `timeout`. The link list always sorted by timeout, like:

```
fd1, 1000001
fd2, 1000001
fd3, 1000002
...
```

And, `asyncdipatch.acceptAddr` call proc `setTimeout` to register a descriptor to the link list. 

```
proc acceptAddr*...
  register(client.AsyncFD)
  setTimeout(client.AsyncFD)
```

Every poll, check it:

```
proc poll*(timeout = 500) =
  ...
  if EvRead in info.events:
    if p.timeline.contains(data.fd):           # reset timeout
      data.fd.updateTimeout()
  ...
  processTimeout(p)

proc processTimeout*(p: PDispatcher) = 
    let now = epochTime()
    for t in p.timeline.timeouts.items():     # look up the link list
      if now < t.timeout:                                 
        break
      if now >= t.timeout:                            
        echo "Timeout: fd ", repr t.fd
        t.fd.closeSocket()                           
        p.timeline.unregister(t.fd)               
```

Test example:

```
import asyncdispatch, asynchttpserver, os, net, threadpool

proc server() =
  proc cb(req: Request) {.async.} = discard
    
  var server = newAsyncHttpServer()
  asyncCheck server.serve(Port(8000), cb)
  runForever() 

proc client() =
  var socket = newSocket()
  socket.connect("127.0.0.1", Port(8000)) 
  socket.send("POST /path HTTP/1.1\r\L")

{.experimental.}
proc main() =
  parallel: 
    spawn server()
    sleep(100)
    spawn client()

main()
```

### CODE REVIEW

**Comment by dom96** [comment]
Does this just reimplement ``sleepAsync``?

**Comment by tulayang** [comment]
@dom96 

No, It's no relationship with `sleepAsync`. This  ensures that the expired client descriptor is cleared:

```
--- newAsyncSocket, create server descriptor
--- acceptAddr, create client descriptor
       addRead, add  client descriptor to selector of global dispatch
       setTimeout, add client descriptor to timeline of global dispatch
--- poll
       for in select:
         EvRead: 
           updateTimeout, update the timeout of client descriptor
       processTimers, for sleepAsync
       processTimeout, check timeline of global dispatch, clear client descriptor that been timeout  
```

I found `asyncdipatch` has not timeout check in current version. If client just

```
socket.send("POST /path HTTP/1.1\r\L")
```

and then there's no longer any message from this client, the client descriptor will always stay in the selector of global dispatch.

**Comment by dom96** [comment]
The client descriptor is removed whenever the client socket is closed though, or at least it should be?

**Comment by tulayang** [comment]
When calling `asynchttpserver.serve` to create a server, I feel unable to control the client's read timeout, (I found that the client descriptor will not be `closeSocket()`  from the global dipatcher if the client does not send message intentionally. ), so there is the idea of the above.

**Comment by dom96** [comment]
If I understand you correctly the way you should be doing this is like so:

```
var client: AsyncSocket # Some client that connected to our server.
let recvFut = client.recvLine()
await sleepAsync(5000) or recvFut
if recvFut.finished:
  echo(recvFut.read)
else:
  echo("Timeout reached")
  client.close() # Close the socket manually.
```

**Comment by tulayang** [comment]
@dom96

This is a very clever way. I will try it. But it seems to need to build more infrastructure for the async http. :)

**Comment by exetoc** [comment]
Neat. That will serve as a good async example as it wasn't obvious to me how `sleepAsync` could be used for this purpose.

**Comment by dom96** [comment]
@exetoc PRs to improve the docs are always welcome ;)

**Comment by Araq** [comment]
So what's the status of this? Merge or reject?

**Comment by dom96** [comment]
I'm afraid reject.

**Pull request closed without merging**
