### PR TITLE
toJson: add option to write empty strings as null

### PR DESCRIPTION
**Pull request by nc-x**
```nim
type
  A = object
    name: string

echo $A().toJson
echo $A().toJson(ToJsonOptions(emptyStringMode: joptEmptyStringAsNull))
echo to(parseJson("""{"name":""}"""), A)
echo to(parseJson("""{"name":null}"""), A)
```
```
{"name":""}
{"name":null}
(name: "")
(name: "")
```

### CODE REVIEW

**Comment by juancarlospaco** [comment]
But why?, both Nim and JSON have a concrete standard documented representation of Null. 😐

**Comment by nc-x** [comment]
because - 
- strings in nim are non nullable 
- to(parseJson(..)) converts null to empty string 
- so toJson should have a way to do the same

also at the time of creating this pull request i needed this. but i don't anymore. so feel free to close.

[also options can and probably should be used for this but i don't see people using it much in nim]

**Comment by juancarlospaco** [comment]
> to(parseJson(..)) converts null to empty string

Then this should be fixed instead IMHO.

**Comment by nc-x** [comment]
I don't think that is a something that needs fixing. Json does not have non-nullable types and `null` is valid (and widely used) for emptiness and it is on the parsers to read it up correctly based on the schema (if any) or the api usage etc.

**Comment by RSDuck** [comment]
wouldn't something ilke `Option[string]` be a better representation of this?

**Comment by Araq** [comment]
> also at the time of creating this pull request i needed this. but i don't anymore. so feel free to close.

Ok.

**Pull request closed without merging**
