### PR TITLE
[cleanup] remove `xmldom` and `xmldomparser`

### PR DESCRIPTION
**Pull request by narimiran**
As discussed in #8238:

> We can remove xmldom and xmldomparser, it precedes xmltree/xmlparser and is replaced by those modules. AFAIK nobody really uses them anyway.

### CODE REVIEW

**Comment by dom96** [comment]
Might be nice to create a Nimble packages for the few that use this module :)

**Comment by kaushalmodi** [comment]
@dom96 But who will take the ownership of those? Shouldn't the original author of those create the nimble packages?

**Comment by kaushalmodi** [comment]
@dom96 umm. OK. So you are the original author of those. :P

**Comment by kaushalmodi** [comment]
Speaking from my experience with Emacs project, should Nim create an "obsolete" repo? Packages obsoleted in stdlib can be moved to that repo as nimble packages. That way no one has to take up the ownership responsibility.

If someone *wants* to take up the responsibility, they can claim it, and then only the URL in the nimble packages json needs to change.

Ref: [Emacs `lisp/obsolete`][1]

[1]: http://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/obsolete

**Comment by kaushalmodi** [comment]
So a question, looks like there's some agreement about obsolete packages. Let's say the repo is named "obsolete-packages", and its URL is https://github.com/nim-lang/obsolete-packages.

Then within that repo, we will have:

```
./
├── obsolete-pkg1/
│  ├ ..
│  └── obsolete-pkg1.nimble
└── obsolete-pkg2/
   ├ ..
   └── obsolete-pkg2.nimble
```

So, can we have Nimble packages be pointed to different subdirs from the same repo? @dom96?

**Comment by Araq** [comment]
@kaushalmodi yeah I know for certain that Nimble supports that.

**Comment by kaushalmodi** [comment]
>  I know for certain that Nimble supports that.

Got it: https://github.com/nim-lang/nimble#package-urls

**Comment by Araq** [comment]
Btw web/website.ini is dead and should be removed.

**Pull request merged**
