### PR TITLE
Added pragmas to ignore warnings in Nim-generated files

### PR DESCRIPTION
**Pull request by endragor**

### CODE REVIEW

**Comment by yglukhov** [comment]
:thumbsup:

**Comment by yglukhov** [comment]
@endragor, for some reason android compiler doesn't respect your pragmas, and now produces even more warnings %)
```
/Users/yglukhov/Projects/nim/lib/nimbase.h:28:11: warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]
 #  pragma GCC diagnostic ignored "-Wwritable-strings"
           ^
/Users/yglukhov/Projects/nim/lib/nimbase.h:29:11: warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]
 #  pragma GCC diagnostic ignored "-Winvalid-noreturn"
           ^
/Users/yglukhov/Projects/nim/lib/nimbase.h:31:11: warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]
 #  pragma GCC diagnostic ignored "-Wlogical-not-parentheses"
           ^
/Users/yglukhov/Projects/nim/lib/nimbase.h:32:11: warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]
 #  pragma GCC diagnostic ignored "-Wlogical-op-parentheses"
           ^
/Users/yglukhov/Projects/nim/lib/nimbase.h:37:11: warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]
 #  pragma GCC diagnostic ignored "-Wtautological-compare"
           ^
/Users/yglukhov/Projects/nim/lib/nimbase.h:38:11: warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]
 #  pragma GCC diagnostic ignored "-Wswitch-bool"
           ^
/Users/yglukhov/Projects/nim/lib/nimbase.h:39:11: warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]
 #  pragma GCC diagnostic ignored "-Wmacro-redefined"
           ^
/Users/yglukhov/Projects/nim/lib/nimbase.h:40:11: warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]
 #  pragma GCC diagnostic ignored "-Wincompatible-pointer-types-discards-qualifiers"
           ^
```

**Comment by endragor** [comment]
@yglukhov Does Android NDK use `clang` on OS X? Could you please check if splitting the GCC pragmas works? Change the added code to:
```nim
/* ------------ ignore typical warnings in Nim-generated files ------------- */
#if defined(__GNUC__)
#  pragma GCC diagnostic ignored "-Wwritable-strings"
#  pragma GCC diagnostic ignored "-Winvalid-noreturn"
#  pragma GCC diagnostic ignored "-Wformat"
#  pragma GCC diagnostic ignored "-Wlogical-not-parentheses"
#  pragma GCC diagnostic ignored "-Wlogical-op-parentheses"
#  pragma GCC diagnostic ignored "-Wshadow"
#  pragma GCC diagnostic ignored "-Wunused-function"
#  pragma GCC diagnostic ignored "-Wunused-variable"
#  pragma GCC diagnostic ignored "-Winvalid-offsetof"
#  pragma GCC diagnostic ignored "-Wtautological-compare"
#  pragma GCC diagnostic ignored "-Wswitch-bool"
#  pragma GCC diagnostic ignored "-Wmacro-redefined"
#  pragma GCC diagnostic ignored "-Wincompatible-pointer-types-discards-qualifiers"
#endif

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wwritable-strings"
#  pragma clang diagnostic ignored "-Winvalid-noreturn"
#  pragma clang diagnostic ignored "-Wformat"
#  pragma clang diagnostic ignored "-Wlogical-not-parentheses"
#  pragma clang diagnostic ignored "-Wlogical-op-parentheses"
#  pragma clang diagnostic ignored "-Wshadow"
#  pragma clang diagnostic ignored "-Wunused-function"
#  pragma clang diagnostic ignored "-Wunused-variable"
#  pragma clang diagnostic ignored "-Winvalid-offsetof"
#  pragma clang diagnostic ignored "-Wtautological-compare"
#  pragma clang diagnostic ignored "-Wswitch-bool"
#  pragma clang diagnostic ignored "-Wmacro-redefined"
#  pragma clang diagnostic ignored "-Wincompatible-pointer-types-discards-qualifiers"
#endif

#if defined(_MSC_VER)
#  pragma warning(disable: 4005 4100 4101 4189 4191 4200 4244 4293 4296 4309)
#  pragma warning(disable: 4310 4365 4456 4477 4514 4574 4611 4668 4702 4706)
#  pragma warning(disable: 4710 4711 4774 4800 4820 4996)
#endif
/* ------------------------------------------------------------------------- */
```
Before submitting PR, I verified that `clang` and `gcc` don't produce warnings on OS X with `-Wall` and no additional flags. Perhaps Android NDK adds some flags so that GCC pragmas don't work.

**Comment by yglukhov** [comment]
Tried your code, and the warnings are the same + some unknown pragmas. It seems a lot like some kind of GCC. Added one more ignore:
```c
#  pragma GCC diagnostic ignored "-Wpragmas"
```
The pragma warnings now disappeared, but unfortunately some warnings still stay, specifically:
```
warning: passing argument 1 of 'logi_705006' discards 'const' qualifier from pointer target type [enabled by default]
```
and
```
warning: passing argument 3 of 'HEX5BHEX5D_1127484' from incompatible pointer type [enabled by default]
```

It seems like these warnings can not be disabled, so I would say thats a gcc issue. At the end of the day `-Wpragmas` seems to be last missing thing in this PR.

**Pull request merged**
