### PR TITLE
sets minor improvement

### PR DESCRIPTION
**Pull request by ringabout**

### CODE REVIEW

**Comment by timotheecour** [comment]
* carefully reviewed, merging.
(was: assert => doAssert + a move)

* note:
these maybe(didn't check) correspond to builtin sets:
tests/sets//t2669.nim
tests/sets//tsets_various.nim
tests/sets//tsets.nim

- [ ] right now we have:

tests/collections/tcollections.nim
tests/collections/tcollections_to_string.nim
tests/collections/thashsets.nim
tests/collections/tseq.nim
tests/collections/ttables.nim
tests/collections/ttablesthreads.nim

given that the stdlib name is `sets.nim` (different from builtin sets), it'd be more logical to have
the test for sets.nim be under 
tests/collections/tsets.nim
instead of
tests/collections/thashsets.nim

note that nim now allows multiple module with same name in same project, so 
having these:
tests/collections/tsets.nim
tests/sets//tsets.nim

shouldn't cause conflicts even if merged via megatest.

**Comment by ringabout** [comment]
If you see the commits before, you could find the CI failures due to name conflicts(`tsets`)

**Comment by timotheecour** [comment]
I can't find the logs? https://github.com/nim-lang/Nim/runs/1435593398
curious why it'd fail

but how about this: we could rename tests/sets//tsets.nim to tests/sets//tbuiltin_sets.nim and tests/collections/thashsets.nim to tests/collections/tsets.nim

**Comment by ringabout** [comment]
`tests/collections/thashsets.nim` exists before, I'm just moving tests to them.

CI failures:
```
megatest.nim(910, 8) Error: redefinition of 'tsets'; previous declaration here: stdlib/tsets.nim(1, 2)
```
https://builds.sr.ht/~araq/job/348186

**Pull request merged**
