### PR TITLE
foldl supports default value when sequence is empty.

### PR DESCRIPTION
**Pull request by gogolxdong**
```nim
import sequtils,strutils

while true:
    readLine(stdin).splitWhitespace.filterIt(it in "0".."9").mapIt(parseFloat it).foldl(a+b).echo
```

### CODE REVIEW

**Comment by krux02** [comment]
Nope. If you want to support a fold that works on an empty set, it must be a fold that takes an initial value. `foldl(a*b)` becoming 0 for an empty input is a bad thing.

**Comment by gogolxdong** [comment]
> Sorry but no. If you want to support a fold that works on an empty set, it must be a fold that takes an initial value. `foldl(a*b)` becoming 0 for an empty input is a bad thing.

What you mean by initial value is the value foldl returns when input is invalid value or nothing ?

**Comment by krux02** [comment]
Nim foldL is not rust sum. Nim `foldl` is more scala `reduceLeft`:

Example:

```scala
scala> val x = Seq(1,2,3)
x: Seq[Int] = List(1, 2, 3)

scala> x.sum
res3: Int = 6

scala> x.reduceLeft( _ + _ )
res7: Int = 6

scala> val y = Seq[int]()
                   ^
       error: not found: type int

scala> val y = Seq[Int]()
y: Seq[Int] = List()

scala> y.reduceLeft( _ + _ )
java.lang.UnsupportedOperationException: empty.reduceLeft
  at scala.collection.IterableOnceOps.reduceLeft(IterableOnce.scala:744)
  at scala.collection.IterableOnceOps.reduceLeft$(IterableOnce.scala:741)
  at scala.collection.AbstractIterable.reduceLeft(Iterable.scala:904)
  ... 29 elided

scala> y.sum
res9: Int = 0
```


scala>

**Comment by gogolxdong** [comment]
Found sum in math.nim, it's what he needs.

**Pull request closed without merging**
