### PR TITLE
asynchttpserver.listen can specify socket's domain (ipv6 support)

### PR DESCRIPTION
**Pull request by inv2004**

### CODE REVIEW

**Comment by Q-Master** [comment]
Just pass the socket to the listen proc and that's all. It might be created anywhere else (including inherited socket type) e.x.
Orelse pass there all the params which could be changed during socket creation.

**Comment by Q-Master** [comment]
No additional flags should be changed if someone passed the already configured socket to listen proc. Flags should be modified only on default sockets.

**Comment by inv2004** [comment]
> No additional flags should be changed if someone passed the already configured socket to listen proc. Flags should be modified only on default sockets.

Not sure, because It will create conflict between `reuseAddr` and `reusePort` parameters if you passed your own socket. At least it should be covered in documentation

**Comment by Q-Master** [comment]
> Not sure, because It will create conflict between `reuseAddr` and `reusePort` parameters if you passed your own socket. At least it should be covered in documentation

Just mention this in documentation. 
Changing implicitly something in pre-configured socket leads to big problems.

**Comment by rockcavera** [comment]
The way you plan to add support for IPv6, in my opinion, is bad. You are introducing something that will break everyone's code using `listen()`.

As I see it, you should do it like this:
```nim
proc listen*(server: AsyncHttpServer; port: Port; address = "", domain: Domain = AF_INET) =
  [...]
  server.socket = newAsyncSocket(domain = domain)
  [...]
```

**Comment by inv2004** [comment]
@rockcavera 
I do not see how it will break the code, but anyway it is exactly I wanted to do in my first commit. Until @Q-Master added the comment

**Comment by rockcavera** [comment]
> @rockcavera
> I do not see how it will break the code, but anyway it is exactly I wanted to do in my first commit. Until @Q-Master added the comment

I was wrong about. There will be no break.

**Comment by inv2004** [comment]
Reverted it back to `domain` parameter to not overcomplicate the fast-fix

**Review by dom96 — APPROVED** [review]
LGTM. Although can we fix tests? Not sure how important they are, someone more familiar with CI can merge if those are flaky.

**Comment by ringabout** [comment]
Succeeded by https://github.com/nim-lang/Nim/pull/18706

**Pull request closed without merging**
