### PR TITLE
gens: match ast handle to node kind name better

### PR DESCRIPTION
**Pull request by arnetheduck**

### CODE REVIEW

**Comment by Araq** [comment]
Let's please use ``nkX``  --> ``genX``, not ``genNodeX``.

**Comment by arnetheduck** [comment]
tried that first, but it causes a fair bit of conflicts with existing names  that are used in a non-nodekind context, meaning one cannot rely on `genX` to exclusively deal with ast code.. 

also, the second part of this refactoring is to change the magics as well - in `nlvm` I call these `genMagicX` though I've been thinking of shortening that to `magicX` - it's often nice however to tell the two apart

**Comment by Araq** [comment]
So let's use ``generateX``

**Comment by zah** [comment]
How useful is this refactoring? It will create major conflicts with @onqtam's work on hot code reloading.

**Comment by onqtam** [comment]
This refactoring should be fine - It doesn't look that problematic for my work :)

**Comment by arnetheduck** [comment]
See #9870 for `generate` - what would you like to call magics then? in `nlvm` I do `genMagicX`

Maybe because I'm used to it, but `genNode` looks better..  anyway, both are improvements over the status quo - pick and choose, it's easy to change :)

or we could go with `handleX` and `magicX` - those are not taken either..

**Comment by arnetheduck** [comment]
> How useful is this refactoring?

it's very helpful when comparing implementations / improving `nlvm` so I imagine it will help keep jsgen and vmgen in sync as well - it's a common enough complaint as well that the compiler code is full of cruft so I'd say every step that uncrufts it a bit is a good one

**Comment by Araq** [comment]
Well I'm used to ``genX``, what conflicts does it cause? Can't we remove them? ``magicX`` is fine with me.

**Comment by arnetheduck** [comment]
eh, quite a few: 
```
[arnetheduck@tempus compiler]$ grep  'proc gen[A-Z]' c* | wc
    163    1309   11087
```
this is just the cgen files, after the `generate` rename (so the ast handlers are not counted)

**Comment by Araq** [comment]
Let's use ``genX`` and ``magicX``.

**Pull request closed without merging**
