### PR TITLE
Make Nim gdb pretty print friendly

### PR DESCRIPTION
**Pull request by cooldome**
I need couple of days to finish gdb script, it will support:

- Type pretty printing
- $ command to invoke nim's dollar operator, quite handly if it is not removed by dead code elimination 
- $dollar function does the same as command, but can be used in expressions
- Value pretty printing 

The following could be in the next versions:
- Filter out frames from temporary variables not seen in user code
- Add methods to types like len, compare, contains. It is possible use added methods in conditional breakpoints and expressions.
- Reduce debugging stepping jitter by adding more #line directives, they are missed in a couple of places confusing gdb.

It is possible to inject gdb script into a custom section in executable/shared library that will be automatically detected by gdb. I recommend enabling that by default.

### CODE REVIEW

**Comment by cooldome** [comment]
Ignore commit history, just look at the changes made

**Comment by krux02** [comment]
Well I celebrate everything that makes Nim debugging better, and I think this will make improvements possible, but can you show us your gdb script, so we can test it?

**Comment by dom96** [comment]
> Ignore commit history, just look at the changes made

That's your cue to squash commits :)

**Comment by cooldome** [comment]
I have first usable version of gdb script ready at https://github.com/cooldome/Nim-gdb
Please give it a try, it depends on this pull request

**Comment by cooldome** [comment]
IMO, this pull request is ready for review. The gdb script did it job in demonstrating that everything is now possible with this PR, you just need to write python gdb script to make it happen.

If we get this one submitted I will look into further way to improve debugging like xmethods.

**Comment by dom96** [comment]
Yay, squashed, nice job @Araq :)

**Pull request merged**
