### PR TITLE
Fix issue #10358

### PR DESCRIPTION
**Pull request by demotomohiro**

### CODE REVIEW

**Comment by nc-x** [comment]
@demotomohiro
while i kind of agree with using the latest available version of msvc compiler, but that would still be an issue if you have a broken latest version. 
  
Maybe it would be better to show a hint/error that says "vcvarsall.bat detected but cl.exe not found. broken msvc install?" for this case.
  
(also since my PR has been already merged, please rebase yours on top of devel.)

**Comment by demotomohiro** [comment]
@nc-x 
Comment of `vccEnvVcVarsAllPath` in tools/vccexe/vccenv.nim says:

> If the `version` parameter is omitted or set to `vsUndefined`, `vccEnvVcVarsAllPath` searches 
> for the latest recognizable version of the VCC tools it can find.
> 

I added a code that check existance of vcvarsall.bat.
If there is a error like cl.exe not found, that means vcvarsall.bat is exist but msvc is broken or vccexe has bug.

**Comment by nc-x** [comment]
I am not sure (and need to verify) but I think that raising error here is wrong because currently it also works if vcvarsall.bat if not found but cl.exe is in path (for eg. vs2017 is not supported by vccexe but you can manually run vcvarsall.bat)

**Comment by Araq** [comment]
@nc-x, please tell us when it's mergable. I haven't really followed this code / issue.

**Comment by demotomohiro** [comment]
I deleted the commit that raise error when vcvarsall.bat was not found.
I dont have vs2017 and this is not tested with it.
But it should be able to run `cl.exe` when nim is executed after `vcvarsall.bat` of vs2017 called.

There are some problems besides it doesn't supports vs2017.
When I run `vccexe` on vs2013 x64 Native tools command Prompt, `vccexe` found `vcvarsall.bat` of vs2015 and called `cl.exe` of vs2015.
In the same way, I think `cl.exe` of vs2015 would be called by `vccexe` when it is executed on vs2017 command prompt if both vs2015 and vs2017 are installed.
I think this problem will be fixed if `vccexe` can find `cl.exe` before calling `vcvarsall.bat`, just call cl.exe without finding `vcvarsall.bat`.

`vccexe` has command line parameter that specify msvc version.
Current code try to find specified version of `vcvarsall.bat` and if none of them found, continue to try finding `vcvarsall.bat` and call `cl.exe`.
But I think it should raise error if it cannot find specified version.
Whats do you think about it?

It seems there is no tests for `vccexe`.
It would be nice if existing tests are executed with `--cc:vcc` option.
I don't know much about appveyor but it seems they have vs2013, 2015 and 2017.
Can we run some tests for `vccexe` on it?

**Comment by nc-x** [comment]
@demotomohiro please open issues for any bugs you find.

@Araq this looks good to merge.

**Pull request merged**
