### PR TITLE
Allow binding to ports >= 32768, fixes #3484

### LINKED ISSUE #3484: lib/pure/net: Can't bind to ports >= 32768
This fails:

```nim
import net
import nativesockets

var s = newSocket(AF_INET, SOCK_DGRAM, IPPROTO_UDP)
bindAddr(s, Port(32768))
```
with ```Error: unhandled exception: value out of range: 32768 [RangeError]```

### PR DESCRIPTION
**Pull request by jsanjuas**

### CODE REVIEW

**Comment by Araq** [comment]
ping @dom96

**Comment by dom96** [comment]
I think ``htons`` and other similar procs should take a ``uint16``. Do you agree @Araq?

**Comment by Araq** [comment]
Yes.

**Comment by dom96** [comment]
Could you do this @jsanjuas?

**Comment by jsanjuas** [comment]
I don't find the end result completely satisfactory because a cast to int16 is still necessary. Maybe InPort should be defined as uint16 rather than int16 (lib/posix/posix.nim).

**Comment by dom96** [comment]
Yeah, I think it should be.

**Comment by dom96** [comment]
Also, could you deprecate the int16 templates/procs?

**Comment by jsanjuas** [comment]
Deprecated for int32 and int16.

**Comment by jsanjuas** [comment]
I'm realizing changing port numbers to uint16 breaks a ton of code. For example, tests/async/tasyncawait does not pass.

    Error: type mismatch: got (int16) but expected 'InPort'

Is there a way to implicitly convert these to uints? I tried defining a (deprecated) htons(int16): uint16 in nativesockets, but this creates ambiguous calls because the compiler (as I understand) does not disambiguate based on return types (would be cool if it did).

Awaiting your (@dom96, @araq) input.

**Comment by dom96** [comment]
I don't think a converter is the way to go here. You simply need to change everything that expected the Port to be an int16 to a uint16 now.

Please add a doc comment to the templates your deprecated, explaining why and what should be used instead, like for example ``**Warning**: This template is deprecated since 0.13.0, use blah instead.``.

**Comment by jsanjuas** [comment]
That should be it @dom96

**Comment by dom96** [comment]
@jsanjuas looks good! Could you squash the commits into one please?

**Comment by jsanjuas** [comment]
Done @dom96

**Comment by dom96** [comment]
@jsanjuas Thank you!

**Pull request merged**
