### PR TITLE
fixes #19607

### LINKED ISSUE #19607: nim doc crashes when processing comment with an asterisk
### Example
```nim
const
  PixelformatUncompressedGrayAlpha* = 2 ## 8*2 bpp (2 channels)
```

### Current Output
```
test.nim(3, 7) Error: '*' expected
lineinfos.nim(289)       raiseRecoverableError
Error: unhandled exception: '*' expected [ERecoverableError]
```

### Additional Information
Remove the asterisk in the comment to make it compile

```
$ nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-03-09
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 6773ffa63d0b3ab8b8894e84ed417f4eaced9122
active boot switches: -d:release --gc:markAndSweep
```

### PR DESCRIPTION
**Pull request by Araq**

### CODE REVIEW

**Comment by Araq** [comment]
@ringabout Do you think the CI is "conceptually" green for this one?

**Comment by ringabout** [comment]
I think it's fine.

**Comment by a-mr** [comment]
@Araq ,

Is the idea of this PR to leave documentation empty in the case of a parsing failure?

Also when I run `nim doc` on e.g.
```nim
const
  PixelformatUncompressedGrayAlpha* = 2 ## 8*2 bpp (2 channels)
```
it does save `.html` file but reports an error twice
```
(2, 7) Error: '*' expected
(2, 7) Error: '*' expected
```
and exits with error code 1.
Is this behavior intended?

**Comment by Araq** [comment]
No, it's not and I suppose my patch is not good enough. It did fix the crash though. :-)

**Pull request merged**
