### PR TITLE
Revert "once C++, always C++ [backport]" [backport]

### PR DESCRIPTION
**Pull request by ringabout**
Reverts nim-lang/Nim#19938

It breaks existing package, ref https://forum.nim-lang.org/t/9495

```nim
{.compile("webview/webview-unix.cc","-std=c++11").}
{.passC: "-DWEBVIEW_COCOA=1".}
{.passL: "-lstdc++ -framework WebKit".}
```

After this change

```
clang -c  -w -ferror-limit=3 -DNDEBUG -fvisibility=hidden -I"/Users/drkameleon/Documents/Code/OpenSource/arturo-lang/arturo/src/extras/mimalloc/include" -I/Users/drkameleon/Documents/Code/OpenSource/arturo-lang/arturo/src/extras -DWEBVIEW_COCOA=1 -O3  -std=c++11  -I/Users/drkameleon/.choosenim/toolchains/nim-1.6.6/lib -I/Users/drkameleon/Documents/Code/OpenSource/arturo-lang/arturo/src/extras -I/Users/drkameleon/Documents/Code/OpenSource/arturo-lang/arturo/src/extras -I/Users/drkameleon/Documents/Code/OpenSource/arturo-lang/arturo/src -o /Users/drkameleon/Documents/Code/OpenSource/arturo-lang/arturo/.cache/webview-unix.cc.o /Users/drkameleon/Documents/Code/OpenSource/arturo-lang/arturo/src/extras/webview/webview-unix.cc
```
becomes
```
clang++ -c -std=gnu++14 -funsigned-char  -w -ferror-limit=3 -DNDEBUG -fvisibility=hidden -I"/Users/drkameleon/Documents/Code/OpenSource/arturo-lang/arturo/src/extras/mimalloc/include" -I/Users/drkameleon/Documents/Code/OpenSource/arturo-lang/arturo/src/extras -DWEBVIEW_COCOA=1 -O3  -std=c++11  -I/Users/drkameleon/.choosenim/toolchains/nim-1.6.8/lib -I/Users/drkameleon/Documents/Code/OpenSource/arturo-lang/arturo/src/extras -I/Users/drkameleon/Documents/Code/OpenSource/arturo-lang/arturo/src/extras -I/Users/drkameleon/Documents/Code/OpenSource/arturo-lang/arturo/src -o /Users/drkameleon/Documents/Code/OpenSource/arturo-lang/arturo/.cache/webview-unix.cc.o /Users/drkameleon/Documents/Code/OpenSource/arturo-lang/arturo/src/extras/webview/webview-unix.cc
```

`clang your.cpp -lstdc++` works according to https://stackoverflow.com/questions/9148488/how-do-i-compile-c-with-clang

cc @arnetheduck

### CODE REVIEW

**Comment by drkameleon** [comment]
This PR is a very important one for [Arturo](https://github.com/arturo-lang/arturo). I hope it gets merged soon (and before 1.6.10 is released)

@ringabout Thanks!! 😄

**Comment by arnetheduck** [comment]
This looks more like a problem in the Arturo package than anything else: the canonical way to call a C++ compiler is through `clang++` (and `g++` respectively). `clang` is for `C` files and while it's possible to add flags to make it behave closer to a C++ compiler, it's not the "normal" way of doing things.

Using `clang` for C++ files, as the stackoverflow issue points out, requires OS-specific flags - the goal of `clang++` is to abstract away those OS-specific flags - reverting this patch is not a good long-term solution.

**Comment by arnetheduck** [comment]
In particular, `clang -lstdc++` will link the wrong C++ library on many systems (if they are using `libc++` and not `libstdc++`) - this is why we use `clang++`: it's configured such that linking and compiling uses the same lookup paths, the same c++ library and so on.

**Comment by ringabout** [comment]
The alternative is to give `compile` an optional parameter to override the current compile settings.

**Comment by arnetheduck** [comment]
> The alternative is to give compile an optional parameter to override the current compile settings.

Well, the logic is pretty simple: if you compile a C++ file, that will result in C++ symbols being used - the C++ symbols require linking to the correct C++ library and the only (portable) way to do that is to call the same "driver" as was used during compilation and this is really the best Nim can do. 

This will work in 99% of cases - indeed, removing this PR will break other packages instead, those that correctly don't pass `-x objective-c` when compiling a C++ file. 

There is indeed a 1% case that needs to link _both_ objective-c and C++ - for those cases, overriding `clang.cpp.linker.exe` in `nim.cfg` is the way to go: in addition to using `clang` they will also need to figure out which library to link to and this will be different for every platform, and sometimes installation, so they will need more custom options.

**Comment by arnetheduck** [comment]
> The alternative is to give compile an optional parameter to override the current compile settings.

One problem is that Nim injects its own, additional parameters to make use of novel C++ features - `-std=gnu++17` or `-std=gnu++14` in particular are problematic mainly because they're both fairly new - specially 17 is not yet available on many LTS distributions - this adds to the complexity of supporting a wide range of C++ compilers and the jungle of their options

**Comment by ringabout** [comment]
Wrong place to discuss this

> GCC has almost full support for the previous revision of the C++ standard, which was published in 2017. Some library features are missing or incomplete, as described in [the library documentation](https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2017).

> C++17 features are available since GCC 5. This mode is the default in GCC 11; it can be explicitly selected with the -std=c++17 command-line flag, or -std=gnu++17 to enable GNU extensions as well.

Nim hardly uses novel C++17 features. It bumps the version to fix a bug on the C++ compiler. Old GCC doesn't completely implement C++ 17 features. But as the documentation says, C++17 features are available since [GCC 5](https://stackoverflow.com/questions/31230201/whats-the-status-of-c17-support-in-gcc).  I suppose it means `-std=c++17` can be enabled for GCC 5.x. it will be reverted if it causes regressions for 2.0.

**Comment by arnetheduck** [comment]
> Wrong place to discuss this

Well, it's relevant in this particular case, for users that include flags such as `-x objective-c` that forces the compiler to treat files as being a particular language and therefore giving an error on, in this case, C++ flags - Nim "forcing" the inclusion of certain flags prevents other flags from working - it's not a problem with an easy solution, but in general, the more flags Nim includes, the more constraints it puts on the user of Nim - with fewer flags and the usage of a conservative feature set in C++,  things tend to work better overall.

This is the same reason why `-lstdc++` cannot work: it will work on some systems and break on others.

**Comment by drkameleon** [comment]
So, @arnetheduck, what do you suggest in my case?

Basically, I want the whole project transpiled to C (not C++), but there happen to be three files that depend on C++:

- https://github.com/arturo-lang/arturo/blob/master/src/extras/webview.nim
- https://github.com/arturo-lang/arturo/blob/master/src/extras/pfd.nim
- https://github.com/arturo-lang/arturo/blob/master/src/extras/window.nim

Again, this has been a struggle to get it to work and seeing it messed up is not nice at all...

**Comment by arnetheduck** [comment]
> whole project transpiled to C

The project is still _compiled_ to C, and the C files are still compiled using the `c` compiler. The only difference this PR makes is that it uses the C++ compiler for _linking_ the project - ie taking all those files and putting them together.

Since there exists _one_ C++ file in the project, the whole project must be linked with C++ libraries - the portable way to do that is to use the `C++` driver for linking  in that case. The non-portable way is to use the C driver and add flags.

In your case, something is adding `-x objective-c` to the compiler command line - you need to find what is doing that: `-x` tells the compiler to use objective-c (and neither of c nor c++).

Since you're using `passC` and `passL`, those flags get passed to _all_ compilation units (all files being compiled, C and C++) - you can try putting flags in compile instead, like so: https://nim-lang.org/docs/manual.html#implementation-specific-pragmas-compile-pragma

**Comment by arnetheduck** [comment]
you can also add `clang.cpp.linkerexe = "clang"` to your nim.cfg - this will appear to make things work for a while, ie you can kick the can of making sure the right flags get passed to the right part of the compilation process down the road

**Comment by drkameleon** [comment]
@arnetheduck Thanks a lot for your input and the elaborate explanation!

I'll give it a try and will let you know! 😉

**Comment by drkameleon** [comment]
As I mentioned in the forum... the issue seems to be fixed after converting -x objective-c to -x objective-c++ (that was relevant only for macOS builds).

See: https://github.com/arturo-lang/arturo/pull/793

Thanks @ringabout and @arnetheduck for the help! 😄

**Pull request closed without merging**
