### PR TITLE
add matutils.nim

### PR DESCRIPTION
**Pull request by gogolxdong**
A simple matutils.nim module makes scientific computation about matrix operations handy. Some basic operations are covered  and more will be enriched in futrue. A nim implementation of NumPy would be the path.

### CODE REVIEW

**Comment by trustable-code** [comment]
The list of changes looks like something got messed up.

**Comment by krux02** [comment]
Well I tried to define a Matrix type simply as an array. I am not sure if that is a good idea. It means every array is a Vector/Matrix type. It creates conflicts with other operations, especially the ``$`` proc that I introduced [here for arrays](https://github.com/nim-lang/Nim/pull/5910).

It would be very nice if you could provide a good matrix library in nimble and when when you think that it is very stable in the api, has little to no conflics and generally is very usable. Then it might become a recommendation and maybe at some point part of the standard library. This matutils package feels very raw. It only have very few matrix operations. Compare it to for example the matrix library I wrote: 

https://github.com/krux02/nim-glm

**Comment by andreaferretti** [comment]
I am not sure whether you are trying to recreate what exists in [linalg](https://github.com/unicredit/linear-algebra).

Also, if you are looking for other alternatives (with no static checks on dimensions), there are [neo](https://github.com/unicredit/neo) and [Arraymancer](https://github.com/mratsim/Arraymancer).

We are experimenting with matrices library, but I don't think the stdlib is the right place for this

**Comment by dom96** [comment]
Indeed, as @johnnovak said, the standard library is no place for this. Please help other developers with the development of their Nimble package or create your own.

**Pull request closed without merging**
