### PR TITLE
refact: Remove assertion effect hiding workaround

### PR DESCRIPTION
**Pull request by quantimnot**
There was a code comment to remove after bootstrapping with `nim >= 1.4.0`.

### CODE REVIEW

**Comment by metagn** [comment]
Is there a need for `useVersion` anymore? (`--useVersion:1.0` makes this fail)

**Comment by quantimnot** [comment]
I can't find the 2.x compiler backwards compatibility rules. So, I don't know when specific version emulations are to removed. If someone has a clue, please give it to me.

**Comment by metagn** [comment]
It's defects being tracked as exceptions. Specifically [in this line](https://github.com/nim-lang/Nim/blob/7837e57e93b1cb89f5a80a779e853bad070de777/compiler/sempass2.nim#L399).

If removing this is too much of a hassle, you can also do:

```nim
proc failedAssertImpl*(msg: string) {.raises: [], tags: [].} =
  when defined(nimDoesntTrackDefects):
    raiseAssert(msg)
  else:
    type Hide = proc (msg: string) {.noinline, raises: [], noSideEffect, tags: [].}
    cast[Hide](raiseAssert)(msg)
```

**Comment by quantimnot** [comment]
That looks fine, but:

1. Is there a benefit to not using the cast until 1.0 emulation is no longer supported?
2. If 1.0 emulation is removed, is it obvious to a contributor that this conditional can be removed? It may be best to use `when defined(optNimV1Emulation)`, so that it will be included in any future `optNimV1Emulation` removal.

Before making any changes here, I want to understand the depreciation/removal rules for version emulation.

**Comment by Araq** [comment]
> Before making any changes here, I want to understand the depreciation/removal rules for version emulation.

Good question, to the best of my knowledge version emulation is not used by many people, if anybody at all. Version 2.0 should not support it.

**Comment by metagn** [comment]
Should work now after #21626 was merged

**Comment by ringabout** [comment]
Small additions, merging

**Pull request merged**
