### PR TITLE
output byref types into --header file [backport: 1.6]

### LINKED ISSUE #19445: {.byref,exportc.} types are not output into --header file
When an object type is made available to C code via {.exportc.} in combination with the `--header` option, the full type definition doesn't appear in the generated `<project>.h`. _(unless the type is small, or is explicitly annotated with {.bycopy.})_

Previously this worked fine as long as you also had an {.exportc.}'d procedure that made use of the type, see https://github.com/nim-lang/Nim/issues/7448#issuecomment-711437477.

### Example

Compile with `nim c -r --nimcache:nimcache --cincludes:nimcache --header main.nim`

```nim
# main.nim
type
  Foo* {.exportc.} = object
    a*, b*, c*, d*: int

proc dummy(): Foo {.exportc.} = discard

{.compile:"bar.c".}
```
```c
// bar.c
#include "main.h"

const Foo f = {10, 20, 30, 40};
```

### Current Output

```
Hint: used config file 'C:\Users\exelotl\Dev\nim-current\config\nim.cfg' [Conf]
Hint: used config file 'C:\Users\exelotl\Dev\nim-current\config\config.nims' [Conf]
.........................................................
CC: bar
CC: stdlib_digitsutils.nim
CC: stdlib_assertions.nim
CC: stdlib_dollars.nim
CC: stdlib_io.nim
CC: stdlib_system.nim
CC: main.nim
C:\Users\exelotl\Dev\nim-tests\exportc-type\bar.c:3:1: error: variable 'f' has initializer but incomplete type
    3 | const Foo f = {10, 20, 30, 40};
      | ^~~~~
C:\Users\exelotl\Dev\nim-tests\exportc-type\bar.c:3:11: error: storage size of 'f' isn't known
    3 | const Foo f = {10, 20, 30, 40};
      |           ^
Error: execution of an external compiler program 'C:\Users\exelotl\Dev\nim-1.6.2\dist\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields   -IC:\Users\exelotl\Dev\nim-current\lib -IC:\Users\exelotl\Dev\nim-tests\exportc-type\nimcache -IC:\Users\exelotl\Dev\nim-tests\exportc-type -o C:\Users\exelotl\Dev\nim-tests\exportc-type\nimcache\bar.c.o C:\Users\exelotl\Dev\nim-tests\exportc-type\bar.c' failed with exit code: 1
```

The generated `main.h`:

```c
/* Generated by Nim Compiler v1.6.2 */
#ifndef __main__
#define __main__
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct Foo Foo;                             //  <---- Type is declared but not defined.
N_LIB_PRIVATE N_NOCONV(void, signalHandler)(int sign);
N_LIB_PRIVATE N_NIMCALL(NI, getRefcount)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, printFoo)(Foo* f);
N_CDECL(void, NimMain)(void);
#endif /* __main__ */
```

### Expected Output

Program should compile.

### Additional Information

The issue occurs on 1.6.2 and the 1.6.4 RC, but not on 1.6.0 or earlier.

```
$ nim -v
Nim Compiler Version 1.6.2 [Windows: amd64]
Compiled at 2021-12-17
```

### PR DESCRIPTION
**Pull request by ringabout**
fix #19445

### CODE REVIEW

**Comment by xflywind** [comment]
Karax seems to be broken caused by the breaking changes of https://github.com/euantorano/dotenv.nim

**Comment by ringabout** [comment]
It is broken with `nim cpp` but it never works (Unrelated to my PR).

**Comment by ringabout** [comment]
interesting:

```
2022-02-09T04:59:11.0552322Z d:/a/1/
s/dist/mingw64/bin/../lib/gcc/x86_64-w
64-mingw32/11.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe:
cannot open output file D:\a\1\s\tests\gc\gcbench.exe: Permission denied
```

**Comment by ringabout** [comment]
Karax seems to be broken caused by the breaking changes of https://github.com/euantorano/dotenv.nim

**Pull request merged**
