### PR TITLE
pass platform argument only if vccexe is used

### PR DESCRIPTION
**Pull request by cooldome**
I am not using `vccexe` tool to run `cl` compiler so got tired of compilation and link warnings:
```
warning: unknown argument  `--platform:amd64` is ignored
```

### CODE REVIEW

**Comment by demotomohiro** [comment]
This PR fix https://github.com/nim-lang/Nim/issues/12297

**Comment by cooldome** [comment]
@demotomohiro: thanks, useful info

**Comment by Araq** [comment]
I don't understand this PR.

**Comment by cooldome** [comment]
I am flattered. Here is the explanation.

Function `vccplatform` is called for every compiler, but its output is used only for `vcc`. Default executable for `vcc` is `cl` not the `vccexe`. `vccexe` is specified in nim.cfg.

`cl` produces warnings if output of `vccplatform` gets added to command line so it needs to be added only if `vccexe.exe` is used in the config.

**Pull request merged**
