### PR TITLE
Add os.pathMatches proc

### PR DESCRIPTION
**Pull request by data-man**
I don't have Windows installed, so ...

### CODE REVIEW

**Comment by data-man** [comment]
Maybe it's need to add to the description that the pattern is OS specific.

**Comment by data-man** [comment]
To new module? What else will be in this module?
Maybe to ```ospaths```? (but it's anyway imported in ```os```)

**Comment by data-man** [comment]
@Araq 

Let's merge it, as is?

**Comment by Varriount** [comment]
PathMatchSpec isn't equivalent to fnmatch. Additionally, the function lacks any documentation or examples detailing exactly what "pattern" should be.

**Comment by data-man** [comment]
> Nobody asked for this feature.

Isn't true.
https://github.com/citycide/glob

**Comment by data-man** [comment]
It's useful.

**Comment by data-man** [comment]
It's useless..

**Comment by dom96** [comment]
Sorry @data-man but I agree with @Araq. Create a Nimble package for this.

**Comment by data-man** [comment]
Well, closed.
I planned use this for other stdlib's PRs and compiler.

**Pull request closed without merging**
