### PR TITLE
fix #14254

### LINKED ISSUE #14254: Cross-module refusal of method call syntax for type conversion in generic
```nim
# importme.nim
type Foo = int32
proc baz*[T](y :int) =
  echo y.Foo
```
```nim
# main.nim
import importme
baz[float](1'i8)
```
`baz[float](1'i8)` can be called in `importme` just fine, but not in `main`, giving the error:
```
Error: undeclared field: 'Foo' for type system.int [declared in c:\dev\fork\Nim\lib\system\basic_types.nim(2, 3)] 
```
Using the normal call syntax allows the code to compile fine, however:
```nim
proc baz*[T](y :int) =
  echo Foo(y)
```

### PR DESCRIPTION
**Pull request by metagn**
fixes #14254

Not super clean but can't think of a better solution

### CODE REVIEW

**Comment by metagn** [comment]
Package failure is because 

```nim
proc T(x: int): float = x.float

proc foo[T](x: int) =
  echo x.T

foo[uint](123) # 123.0
```

now behaves like

```nim
proc T(x: int): float = x.float

block:
  type T = uint
  proc foo(x: int) =
    echo x.T

  foo(123) # 123
```

which to me seems like the more consistent behavior. We either patch [the package](https://github.com/andreaferretti/neo/blob/6f015e4252bfd111dc522ac8d3f9919bad66b0b7/neo/dense.nim#L1224) (to use a different name for the generic param) or we don't fix this bug I think.

**Comment by metagn** [comment]
Ok yep, this is an inconsistency

```nim
proc T(x: int): float = x.float

proc foo[T](x: int) =
  echo typeof T(x) # uint
  echo typeof x.T # float

foo[uint](123)
```

Made a PR to the package: https://github.com/andreaferretti/neo/pull/53

**Comment by Araq** [comment]
Feel free to fork the package and delegate "important_packages" to the fork or to disable the package for testing so that we can move on with this bugfix. It's pretty nice to have for v2.0.

**Comment by metagn** [comment]
Done, CI failure unrelated

**Pull request merged**
