### PR TITLE
fix #14655 setLen(seq) now zeros memory

### LINKED ISSUE #14655: seq.setLen sometimes doesn't zero memory
Sometimes the seq.setLen method leaves garbage without zeroing it which is probably wrong.

### Example
```nim
for i in 0..10000:
  var test = newSeqOfCap[uint32](1)
  test.setLen(1)
  echo test
```

### Output
Output is big but contains things like
```
...
@[0]
@[0]
@[0]
@[52]
@[0]
@[0]
@[0]
@[875912000]
@[1563450176]
@[0]
@[0]
@[0]
@[0]
@[0]
@[54]
@[0]
@[0]
...
```
I've looked into the setLen code and it seems like it should set memory to zero always. Also for some reason comparisons like `test[0] != 0` always fail (optimization?), and the amount of garbage changes depending on the other code with no obvious pattern. Also about 150 of the first iterations are always correctly zeroed out. The amount of garbage seems to be the biggest for sequences with length = 4 but completely disappears for all lengths >=5.

### Additional Information
Bug was spotted in 1.2.0 version installed via choosenim, unfortunately couldn't test it on devel channel because it won't compile.
```
$ nim -v
Nim Compiler Version 1.2.0 [Windows: i386]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 7e83adff84be5d0c401a213eccb61e321a3fb1ff
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by timotheecour**
* fix #14655
1st commit is just a refactor
2nd commit is the bugfix

## after PR
implement proposal in  https://github.com/nim-lang/Nim/issues/14655#issuecomment-643671397

### CODE REVIEW

**Comment by timotheecour** [comment]
@araq any word on proposal https://github.com/nim-lang/Nim/issues/14655#issuecomment-643671397 ?

**Comment by c-blake** [comment]
If you are going to zero by default (which is fine), you should either soon or someday provide a `noInit=false` that if flipped to `true` skips the zeroing.  Then these `setLen`s will work a lot like the regular variable decl with/without the `noInit` pragma..initialized by default with an optimization escape hatch.  I realize the opposite `isInit` was proposed in that linked PR, but I think consistency with regular variables makes the most sense.  There also seems value in having only one name (`noInit`) to remember.  Just my two cents.

**Comment by timotheecour** [comment]
I'm fine with noInit, the only downside being that double negation is less readable than noInit. The important thing is we have that optimization escape hatch available.

**Comment by Araq** [comment]
> @Araq any word on proposal #14655 (comment) ?

Somehow my reply got lost. Here is it again: I think an unsafe setLen is important but should be a different API.

**Comment by Araq** [comment]
Additional remark: A better design for ``setLen`` would be two separate procs; ``grow`` and ``shrink``. Available with ``--gc:arc``.

**Comment by timotheecour** [comment]
what would be benefits (besides the intent one where you call shrink if you expect it to shrink, but I haven't run into a case where this mattered)? honest question

**Comment by c-blake** [comment]
At the implementation level, less safe `growNoInit` (and maybe super unsafe `shrinkNoDestruct`) make sense.  At the user-level, I think people mostly think about the length/legal addressable range.  Nothing wrong with *both* grow/shrink and a wrapper setLen API.

While you might balk at `shrinkNoDestruct`, I have personally seen quite a few real life circumstances where it was taking an hour for a C++ program to `quit()` because giant arrays had to be swapped into RAM from spinning rust to run destructors.  Swapping may/may not be preventable at an admin level, but any OS can always reclaim all (local) resources for a dying process in a far more efficient manner (where "far" could equate to "billions of times faster").  Something to consider.

I agree the double negative is *slightly* more cognitive load than ideal, but initialized is safer than uninitialized.  So, we are stuck with `var foo {.noInit.}`. Cognitive load reduction from maximum Nim-global concept/naming consistency helps more than trying to "fix" it locally.  Initted by default with an escape seems to be the concept/names we should stick with.

Similarly, whatever is done, it should be "similar", for `newSeq[T](...)`, `newSeqOfCap[T](...)` which is why I thought "named parameter `noInit=false`" would be the simple way to go.  `setLenNoInit` is not so bad and does force a clarity that the named parameter `noInit=false` would not (people could just pass "true" and then code readers might be WTF is that for? or even copy-paste errors).  But consistency then means `newSeqNoInit[T]`, `newSeqOfCapNoInit[T]` and all that.  People could also just be "encouraged" to pass `noInit=true` not merely `true`.

All just food for thought.  Not sure what the best answers are.

**Comment by Araq** [comment]
> what would be benefits (besides the intent one where you call shrink if you expect it to shrink, but I haven't run into a case where this mattered)? honest question

You don't need ``default(T)`` to exist for shrinking but for growing.

**Pull request merged**
