### PR TITLE
define sparc64 platform

### PR DESCRIPTION
**Pull request by avsej**

### CODE REVIEW

**Comment by avsej** [comment]
To generate csources, I need nim, but to compile nim with new platform, I need csources

for example when calling `nim c -r ./koch csources -d:release` (where nim is the current stable release), I'm getting

```
...
nim compile -f --symbolfiles:off --compileonly --gen_mapping --cc:gcc --skipUserCfg --os:windows --cpu:sparc64 -d:release compiler/nim.nim
command line(1, 2) Error: unknown CPU: 'sparc64'
```

**Comment by Araq** [comment]
Apparently niminst doesn't support more than 10 different CPUs (yay!) can you also patch tools/niminst/niminst.nim line 21?

**Comment by avsej** [comment]
yes, I can. Shall I also make PR to csources (I can switch to stable tag, apply this sparc64 patch and regenerate csources)

**Comment by Araq** [comment]
no, I will re-generate csource for the next release.

**Pull request merged**
