### PR TITLE
Revert "fixes #20699; generate an empty struct for void type"

### LINKED ISSUE #20699: Default value of object parameterized with a RootRef generates incorrect C
### What happened?

The following code:
```nim
type
  Either[A,B] = object
    case kind:bool
    of false:
      b: B
    of true:
      a: A

  O = object of RootRef

proc oToEither(o:O):Either[O,void] =
  Either[O,void](kind:true,a: o)

discard oToEither(O())
```
fails to compile with:
```
/home/deech/.cache/nim/test_d/@mtest.nim.c:73:107: error: ‘union <anonymous>’ has no member named ‘_kind_1’; did you mean ‘_kind_2’?
   73 | static NIM_CONST tyObject_Either__D9a6Bf9aw0xiqmc0h0TIPoaw TM__ipcYmBC9bj9a1BW35ABoB1Kw_2 = {NIM_FALSE, {._kind_1 = {}}}
      |                                                                                                           ^~~~~~~
      |                                                                                                           _kind_2
```

Seems the default value of the `Either` tries to use a struct parameter that doesn't exist.

### Nim Version

```
Nim Compiler Version 1.7.3 [Linux: amd64]
Compiled at 2022-10-29
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 534c97edc54ffb6d55baa5084f8c426a451c9244
active boot switches: -d:release
```

### Current Standard Output Logs

_No response_

### Expected Standard Output Logs

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Araq**
Reverts nim-lang/Nim#20790

Looking for a better solution. Work in progress.

### CODE REVIEW

**Comment by deech** [comment]
FYI, the first solution I had was to simply produce an empty union on initialization, eg. for the type:
```
      type
        Either[A,B] = object
          case kind:bool
          of false:
            b: B
          of true:
              a: A
        O = object of RootRef
```
instead of an empty struct initialization:
```
static NIM_CONST Either ... = {NIM_FALSE, {._kind_1 = {}}};
```

I had:
```
static NIM_CONST Either ... = {NIM_FALSE, {}};
```
and that worked for the test case but that caused problems with the `nimly` package.

**Comment by bung87** [comment]
please merge, break booting from devel
```
generated_not_to_break_here: In function ‘atmdotdotatslibatssystematsexceptionsdotnim_DatInit000’:
generated_not_to_break_here:999999:192: error: ‘TNimTypeV2’ {aka ‘struct TNimTypeV2’} has no member named ‘name’
generated_not_to_break_here:1000001:180: error: ‘TNimTypeV2’ {aka ‘struct TNimTypeV2’} has no member named ‘name’
generated_not_to_break_here:1000003:180: error: ‘TNimTypeV2’ {aka ‘struct TNimTypeV2’} has no member named ‘name’

```

**Comment by ringabout** [comment]
It is not necessarily related to this PR. I didn't see any breaking on the devel branch. See also the CI on the branch which works well. How to reproduce it?

**Comment by bung87** [comment]
> It is not necessarily related to this PR.

where is the cause?

**Comment by ringabout** [comment]
Looks like to me that it is caused by ARC/ORC removing the type name, which isn't a bug though.

Two solution: 
- clearing the nimcache and pre-built binary (mostly likely to work).
- compile it with `-d:nimTypeNames`. 

It that's the cause.

**Comment by bung87** [comment]
thanks! works.

**Pull request merged**
