### PR TITLE
 Remove libuv from standard library wrappers.

### PR DESCRIPTION
**Pull request by treeform**
I was excited to see libuv in the standard library and wanted to play with it. But it does not work. It turns out it is 7 years out of date. Yeah, wow 7 years. It was alpha back then. Also it turns out Araq wanted it deleted 3 years ago: https://github.com/nim-lang/Nim/pull/2076

I want to save people like me from running into this broken thing and making nim standard library look bad. If some one needs this they can get it as a 3 years out of date package here: https://github.com/huodon/libuv

I believe the backward compatibility impact going to be very minimal as the code here is broken, and exists as a package if they somehow for some strange reason need some thing this old.

### CODE REVIEW

**Comment by lcrees** [comment]
https://github.com/nim-lang/packages/pull/606

**Comment by dom96** [comment]
Looks good :)

but please also add your change in here: https://github.com/nim-lang/Nim/blob/devel/changelog.md

**Comment by treeform** [comment]
I have added my change log changes as requested but lcrees also did it here https://github.com/nim-lang/Nim/pull/6627 . I think we should just take that version.

**Comment by dom96** [comment]
huh, but @lcrees' PR doesn't remove the module unless I am missing something.

**Comment by treeform** [comment]
That PR only changes the change log.  I have updated my change log.

**Comment by treeform** [comment]
Anything else I should do on this PR?

**Pull request merged**
