### PR TITLE
fixes #19101; zero initialization union casts

### LINKED ISSUE #19101: Casting from smaller type to bigger type can produce random bits
When `cast[T]` is used to cast smaller size value to bigger size value, a part of the resulting value contains random bits.

Example code:
```nim
import std/[strutils]

type
  Small = object
    a: int

  Big = object
    a, b, c, d: int

proc main =
  var
    n = 1'i8
    f = 2.0
    s = Small(a: 1)
    b = Big(a: 12345, b: 23456, c: 34567, d: 45678)

  echo cast[int](f).toBin(64)
  f = cast[float](n)
  echo cast[int](f).toBin(64)

  echo b
  b = cast[Big](s)
  echo b
main()
```

Output:
```
0100000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000010000000011010000000001
(a: 12345, b: 23456, c: 34567, d: 45678)
(a: 1, b: 16, c: 4260937, d: 11)
```

Expected output:
```
0100000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000001
(a: 12345, b: 23456, c: 34567, d: 45678)
(a: 1, b: 0, c: 0, d: 0)
```
(Result of casting `int8` to `float` depends on endianness)

This is a part of C code generated by Nim:
```c
N_LIB_PRIVATE N_NIMCALL(void, main__testcast_9)(void) {
  NI8 n;
  NF f;
  ...
  union { NI8 source; NF dest; } LOC3;
  ...
  LOC3.source = n;
  f = LOC3.dest;
```

Nim uses C's union to implement `cast[T]` but that union variable is used without initialization and it can contains any value.
So if a source of `cast[T]` is smaller than the union variable, a part of the union variable is unchanged when the source value is copied to it.
If your code reads these random value, it can cause a bug randomly happens.

Possible solutions:
1. Fix C/C++ code gen so that random value is never generated
   - Initialize a C union with zero like Nim variables.
   - Implement it with `memcpy` or `memmove` and copy only sizeof(source value) bytes

2. Show warning or error when `cast[T](s)` is used and sizeof(T) > sizeof(s) (or sizeof(T) != sizeof(s))
   - std::bit_cast in C++20 looks similar to Nim's `cast` but it compiles only if sizeof(To) == sizeof(From)
     - https://en.cppreference.com/w/cpp/numeric/bit_cast
   - Making it compile error is a breaking change?

3. It is not an issue as manual says "Type casts are inherently unsafe"

Nim version
```
Nim Compiler Version 1.7.1 [Windows: amd64]
Compiled at 2021-11-04
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by ringabout**
fixes https://github.com/nim-lang/Nim/issues/19101

### CODE REVIEW

**Comment by arnetheduck** [comment]
I'm not sure this is worth fixing this way - ie casts inherently have many of these effects, consider casting between to object instances whose members have alignment padding - a similar situation will ensue and you'd have many similar holes to plug if cast is to be made safe..

**Comment by ringabout** [comment]
Yeah, it might be worth keeping the warning. I have no strong opinion. `cast` is meant to be dangerous anyway.

**Comment by Araq** [comment]
These warnings have been super annoying and somewhat hard to fix. This solution is much better.

**Comment by arnetheduck** [comment]
> This solution is much better.

this is not a "solution" though in that the complex ways in which cast can fail is still present while a trivial way is made to work - `cast` would have to be rearchitected substantially to move it away from "reinterpret-these-bits-as-another-type" to "take the bits of this type and superimpose them on an otherwise correctly initialized type"

**Comment by Araq** [comment]
It fills one hole for code that has always been accepted by the compiler. Nothing more, nothing less.

**Comment by arnetheduck** [comment]
it changes the meaning of cast from being a "free" operation to being a zero-memmed heavy operation

**Comment by Araq** [comment]
It is a "heavy" operation only if the sizes don't match. But we can bring on the warning and make it opt-in.

**Comment by arnetheduck** [comment]
yeah, but it's now "sometimes heavy" - as a follow-up consequence, it's now "sometimes zeroes padding bytes" ... that's a few too many "sometimes" turning cast into essentially random behavior (because field order and padding etc, per nim ABI, isn't fixed and we want to keep it this way) - with _no_ zeromem, it's predictable and easy to explain: you're responsible always for the extra bytes no matter where they appear and fixing such cases is _also_ easy: you convert the type to a larger type _then_ cast - this is easy to teach.

**Comment by arnetheduck** [comment]
this can be fixed by always zeroing the target: then we get back into predictable territory that at least can humanely be explained - it's still a different beast than the original cast though.

**Comment by Araq** [comment]
There is nothing unpredictable about `xor eax, eax # zero it first` and you're always free to look at the produced assembler. Hyperbole is not convincing.

**Comment by arnetheduck** [comment]
the unpredictability pertains to `cast` it self - it's definition now becomes "sometimes zeroes the destination, but not always" - this is difficult to reason about and a regression in the langauge

**Pull request merged**
