### PR TITLE
[FIX] Update fusion master commit hash

### PR DESCRIPTION
**Pull request by haxscramper**

### CODE REVIEW

**Comment by ringabout** [comment]
When bumping fusion commits, fusion CI fialed.

```
bin/nim doc  --errormax:3 --hint:Conf:off --hint:Path:off --hint:Processing:off --hint:XDeclaredButNotUsed:off --warning:UnusedImport:off -d:boot --putenv:nimversion=1.5.1 --git.commit:devel --git.url:https://github.com/nim-lang/Nim --outdir:web/upload/1.5.1 --index:on lib/fusion/js/jsxmlserializer.nim
/home/runner/work/Nim/Nim/lib/js/dom.nim(14, 10) Error: This module only works on the JavaScript platform
/home/runner/work/Nim/Nim/lib/fusion/js/jsxmlserializer.nim(9, 51) Error: `importjs` pragma requires the JavaScript target
/home/runner/work/Nim/Nim/lib/fusion/js/jsxmlserializer.nim(12, 77) Error: `importjs` pragma requires the JavaScript target
```

https://github.com/nim-lang/Nim/runs/1664234402

**Comment by haxscramper** [comment]
@xflywind I'm not familiar enough with CI build process to fix this, but from looking at the build log and build for `dom.nim` (which contains explicit `{.error.}` that causes CI fail) I think this is caused by missing `--backend:js` when compiling `fusion/js/*` modules. This option is present for `lib/js`, but not for `lib/fusion/js`.

**Comment by ringabout** [comment]
it is hopeful to be fixed by this PR https://github.com/nim-lang/fusion/pull/64

**Comment by alaviss** [comment]
> it is hopeful to be fixed by this PR [nim-lang/fusion#64](https://github.com/nim-lang/fusion/pull/64)

It won't. It's a bug in `koch`.

**Comment by timotheecour** [comment]
indeed, I'm fixing it in https://github.com/nim-lang/Nim/pull/16645

**Pull request merged**
