### PR TITLE
Fixes #17755 [backport:1.4]

### LINKED ISSUE #17755: OpenSSL 1.0.x library naming issue on windows
The library/dll naming on windows for OpenSSL 1.0.x is incorrect. There's a `nimOldDlls` switch, but it tries to load OpenSSL 1.1.x libraries first.

I read multiple times that old dll names are `ssleay32.dll` and `libeay32.dll`; and changed with OpenSSL 1.1.x.
I read that 64bit builds are named with 32-suffix too (at least when compiling with mingw: https://github.com/openssl/openssl/issues/2383).
I would like to create a pull request which checks if `openssl10` is defined and remove the `nimOldDlls` switch.

I'm currently on branch [version-1-4](/nim-lang/Nim/tree/version-1-4), therefore I need a backport and don't know how you do this and if breaking changes are allowed (removing `nimOldDlls` switch); I guess it's not?

### Current code
```nim
elif useWinVersion:
  when not defined(nimOldDlls) and defined(cpu64):
    const
      DLLSSLName* = "(libssl-1_1-x64|ssleay64|libssl64).dll"
      DLLUtilName* = "(libcrypto-1_1-x64|libeay64).dll"
  else:
    const
      DLLSSLName* = "(libssl-1_1|ssleay32|libssl32).dll"
      DLLUtilName* =  "(libcrypto-1_1|libeay32).dll"
```

### Possible Solution 1
```nim
elif useWinVersion:
  when defined(openssl10):
    const
      DLLSSLName* = "ssleay32.dll"
      DLLUtilName* = "libeay32.dll"
  elif defined(cpu64):
    const
      DLLSSLName* = "(libssl-1_1-x64|ssleay64|libssl64).dll"
      DLLUtilName* = "(libcrypto-1_1-x64|libeay64).dll"
  else:
    const
      DLLSSLName* = "(libssl-1_1|ssleay32|libssl32).dll"
      DLLUtilName* = "(libcrypto-1_1|libeay32).dll"
```

### Possible Solution 2
```nim
elif useWinVersion:
  when defined(openssl10):
    when defined(cpu64):
      const
        DLLSSLName* = "(ssleay32|ssleay64).dll"
        DLLUtilName* = "(libeay32|libeay64).dll"
    else:
      const
        DLLSSLName* = "ssleay32.dll"
        DLLUtilName* = "libeay32.dll"
  elif defined(cpu64):
    const
      DLLSSLName* = "(libssl-1_1-x64|ssleay64|libssl64).dll"
      DLLUtilName* = "(libcrypto-1_1-x64|libeay64).dll"
  else:
    const
      DLLSSLName* = "(libssl-1_1|ssleay32|libssl32).dll"
      DLLUtilName* = "(libcrypto-1_1|libeay32).dll"
```

### Possible Solution 3
```nim
elif useWinVersion:
  when defined(openssl10) or defined(nimOldDlls):
    when defined(cpu64):
      const
        DLLSSLName* = "(ssleay32|ssleay64).dll"
        DLLUtilName* = "(libeay32|libeay64).dll"
    else:
      const
        DLLSSLName* = "ssleay32.dll"
        DLLUtilName* = "libeay32.dll"
  elif defined(cpu64):
    const
      DLLSSLName* = "(libssl-1_1-x64|ssleay64|libssl64).dll"
      DLLUtilName* = "(libcrypto-1_1-x64|libeay64).dll"
  else:
    const
      DLLSSLName* = "(libssl-1_1|ssleay32|libssl32).dll"
      DLLUtilName* = "(libcrypto-1_1|libeay32).dll"
```

### PR DESCRIPTION
**Pull request by Dankr4d**

### CODE REVIEW

**Comment by Araq** [comment]
Instead please tell @narimiran what to backport, PRs are only created against Nim devel. (He's in holidays but will back this week.)

**Comment by Dankr4d** [comment]
How do you do this the usual way? Just tagging him in the issues/pull requests, like you did, and asking then for a backport?

**Comment by ringabout** [comment]
see https://nim-lang.github.io/Nim/contributing.html#the-git-stuff-general-commit-rules

tags the pull request which solves the problems

I tagged your pull request.
https://github.com/nim-lang/Nim/pull/17766

**Comment by Dankr4d** [comment]
Thank you!
Next time I'll tag it in the commit message then too.
Hopefully this time it's enough when just the pr title is changed.

**Pull request closed without merging**
