### PR TITLE
Fix #13573 and #13574

### LINKED ISSUE #13573: newHttpHeaders does not accept repeated headers
In `httpcore`, the constructor `newHttpHeaders` does not accept repeated headers. `httpcore` was recently refactored to add support for repeated headers - in particular we have types `HttpHeaders` and `HttpHeaderValues`, where before headers were just a `stringTable`.

Still, the constructor `newHttpHeaders` assumes that each header is passed a single time, as seen [here](https://github.com/nim-lang/Nim/blob/devel/lib/pure/httpcore.nim#L106-L112):

```nim
proc newHttpHeaders*(keyValuePairs:
    openArray[tuple[key: string, val: string]]): HttpHeaders =
  var pairs: seq[tuple[key: string, val: seq[string]]] = @[]
  for pair in keyValuePairs:
    pairs.add((pair.key.toLowerAscii(), @[pair.val]))
  new result
  result.table = newTable[string, seq[string]](pairs)
```

To check this behaviour it is enough to do

```nim
import httpcore, strutils

let h = newHttpHeaders({"a": "1", "a": "2"})

assert seq[string](h["a"]).join(",") == "1,2"
```

### PR DESCRIPTION
**Pull request by andreaferretti**

### CODE REVIEW

**Comment by andreaferretti** [comment]
I added a small test for httpcore - I couldn't find testament tests for asynchttpclient

**Comment by mrhdias** [comment]
I don't know if it's correct. I think that according to the specifications the following headers with the same field-name that already exist, the values must be concatenated and separated by commas.

https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. **It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma.** The order in which header fields with the same field-name are received is therefore significant to the interpretation of the combined field value, and thus a proxy MUST NOT change the order of these field values when a message is forwarded.

**Comment by andreaferretti** [comment]
@mrhdias If I understand correctly, this means that the semantics of

```
Field1: Val1
Field1: Val2
Field1: Val3
```

is the same as

```
Field1: Val1,Val2,Val3
```

but I am not really an expert. If this was the case, the implementation should be ok. I would like to add tests for asynchttpserver, but I couldn't find any in testament.

Semi-related to this: I see some failures in CI, but I made sure to pass tests before pushing. What is the correct way to check that everything is ok with koch? I did

```
./koch boot
./koch test
```

**Comment by Araq** [comment]
> What is the correct way to check that everything is ok with koch? I did

Seems fine. I use ``koch boot -d:release`` since all the checks are still in the resulting compiler.

**Comment by disruptek** [comment]
No, RFC7230 _obsoletes_ 2616.  You should not refer to 2616 at all.

**Comment by mrhdias** [comment]
https://tools.ietf.org/html/rfc7230#page-24

Basically the text is the same, it just creates an exception for the "Set-Cookie" header.

   header section is received, since later header fields might include
   conditionals, authentication credentials, or deliberately misleading
   duplicate header fields that would impact request processing.

   A sender MUST NOT generate multiple header fields with the same field
   name in a message unless either the entire field value for that
   header field is defined as a comma-separated list [i.e., #(values)]
   or the header field is a well-known exception (as noted below).

   A recipient MAY combine multiple header fields with the same field
   name into one "field-name: field-value" pair, without changing the
   semantics of the message, by appending each subsequent field value to
   the combined field value in order, separated by a comma.  The order
   in which header fields with the same field name are received is
   therefore significant to the interpretation of the combined field
   value; a proxy MUST NOT change the order of these field values when
   forwarding a message.

      Note: In practice, the "Set-Cookie" header field ([RFC6265]) often
      appears multiple times in a response message and does not use the
      list syntax, violating the above requirements on multiple header
      fields with the same name.  Since it cannot be combined into a
      single field-value, recipients ought to handle "Set-Cookie" as a
      special case while processing header fields.  (See Appendix A.2.3
      of [Kri2001] for details.)

**Comment by disruptek** [comment]
Right.  See also #12211 for more backstory.  Point being that

```
Field1: Val1
Field1: Val2
Field1: Val3
```

is not the same as
```
Field1: Val1,Val2,Val3
```
simply because the second is permitted by 7230 while the first is not.  :wink:

**Comment by andreaferretti** [comment]
Ok, so #13574 was not a bug after all. I am going to change this PR to only fix #13573

**Review by dom96 — APPROVED** [review]
LGTM

**Pull request merged**
