### PR TITLE
cgen: join ccgstmts,ccgliterals into ccgexprs

### PR DESCRIPTION
**Pull request by arnetheduck**
since expressions and statements no longer that much different, might as well join these files and keep all ast node processing in one file.. the next step is to name each node handler after its kind

### CODE REVIEW

**Comment by krux02** [comment]
The big problem is that changes like this cause pain in other PRs with changes in those parts that you moved. So don't expect excitement for this to be merged.

**Comment by arnetheduck** [comment]
yeah. will you do it anyway though? that is the better question - that's a balance you'll have to decide - whether refactoring should take precedence over convenience and simple history. 

this branch took me about 3 minutes to produce so it can be done any time (ie if you do a bunch of merges of PR's, after that might be a good time, possibly with a preannouncement.

It looks like I did something silly since there's a build fail - how that happened is anybody's guess since I just copypasted things over.. oh well. LMK if you wanna merge and I can clean up.

**Comment by Araq** [comment]
I don't like this merge, I think it makes things worse. There is nothing wrong with ``include``.

**Comment by arnetheduck** [comment]
> There is nothing wrong with include.

this is not to remove includes - it's to put logically related code in the same context. there used to be a division between expressions and statements - this no longer exists as strongly so having two files for it only makes things confusing when trying to find where stuff is or should go - I say this as someone who tries to look at the current code often, and not being the author. 

it's simply difficult because there's no evident red line as to why things are divided the way they are. improving this in any way would help greatly, though it doesn't necessarily have to be this exact merge.

**Pull request closed without merging**
