### PR TITLE
fixes #20699; generate an empty struct for void type

### LINKED ISSUE #20699: Default value of object parameterized with a RootRef generates incorrect C
### What happened?

The following code:
```nim
type
  Either[A,B] = object
    case kind:bool
    of false:
      b: B
    of true:
      a: A

  O = object of RootRef

proc oToEither(o:O):Either[O,void] =
  Either[O,void](kind:true,a: o)

discard oToEither(O())
```
fails to compile with:
```
/home/deech/.cache/nim/test_d/@mtest.nim.c:73:107: error: ‘union <anonymous>’ has no member named ‘_kind_1’; did you mean ‘_kind_2’?
   73 | static NIM_CONST tyObject_Either__D9a6Bf9aw0xiqmc0h0TIPoaw TM__ipcYmBC9bj9a1BW35ABoB1Kw_2 = {NIM_FALSE, {._kind_1 = {}}}
      |                                                                                                           ^~~~~~~
      |                                                                                                           _kind_2
```

Seems the default value of the `Either` tries to use a struct parameter that doesn't exist.

### Nim Version

```
Nim Compiler Version 1.7.3 [Linux: amd64]
Compiled at 2022-10-29
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 534c97edc54ffb6d55baa5084f8c426a451c9244
active boot switches: -d:release
```

### Current Standard Output Logs

_No response_

### Expected Standard Output Logs

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by deech**

### CODE REVIEW

**Comment by deech** [comment]
If there aren't any issues any chance this can be merged soon? It's currently blocking my use of `results` in `nim-stew` which defines `type Opt[T] = Result[T,void]`.

**Comment by Araq** [comment]
Merged for now but I doubt it's a complete solution for this problem and might have made things worse.

**Comment by arnetheduck** [comment]
@narimiran backport pls

**Comment by Araq** [comment]
That could backfire... As I said, it's a risky patch.

**Comment by arnetheduck** [comment]
any better ideas how to approach it? ie it's a real problem we're hitting

**Comment by Araq** [comment]
There was something odd going on in ccgexprs.getNullValueAux the case for `nkRecCase`. But I think the real fix is a fix in the frontend. The caching of generic instantiations might be off for `void` or we don't remove the fields of type `void` consistently enough in the frontend.

**Comment by Araq** [comment]
I know it's a real problem, already spent hours on it. :-)

**Comment by metagn** [comment]
Can't we opt-in to using an empty struct with `tuple[]`?

**Pull request merged**
