### PR TITLE
Improved unittest check macro, fixes #5784

### LINKED ISSUE #5784: unittest.check does not perform short-circuit evaluation
The sample below segfaults. `check` macro rewrites the boolean expressions so that **all** parts of the expressions are evaluated, instead of performing short-circuit evaluation, like Nim does.
```nim
import unittest

type
  SomeObj = ref object
    field: int

var obj: SomeObj
echo(obj.isNil or obj.field == 0) # true
check:
  obj.isNil or obj.field == 0 # SIGSEGV
```
Git hash: 2e7320fa1f0b8fa67bc9c1bf26c5c9a1dcb04b04

### PR DESCRIPTION
**Pull request by GULPF**
- `check` no longer attempts to break out expressions from `or` & `and` to avoid messing up short circuiting (fixes #5784)
- checkpoints are generated for more expression types (e.g `foo.len == 3` and `foo[0] == 3` will now generate checkpoints)
- some general cleanup (prefer `let` over `var`, prefer returning a tuple over mutating outer variables, prefere `quote do` over `getAst(tmpl(...))`)

`check a.isNil or a.field == 3` is still not very useful, since it won't generate a checkpoint for `a.field`'s value. I don't think it's a good idea to attempt to generate checkpoints for that case, because it would make an already complex macro much more complex.

Perhaps there should be a different template/macro for running some checks iff an expression evaluates to true, and otherwise fail immediately.

### CODE REVIEW

**Comment by cooldome** [comment]
Looks very useful, I'll do some testing tomorrow as I was suffering from unittest framework limitations

**Comment by cooldome** [comment]
I haven't looked on the code itself, rather gave it a try on my code base, fixed the problem with m.len and m[0] not printing the failing check value. Also checked and/or is now working properly.
Really useful improvement.

**Comment by GULPF** [comment]
It seems like `tests/stdlib/tunittest.nim` is only compiled by the tester and never executed, but it's content seems to imply that it should be executed. Should it be changed? I don't really understand nims test system.

**Comment by dom96** [comment]
Yeah, it likely should be changed.

**Comment by dom96** [comment]
Here are some docs https://github.com/nim-lang/Nim/tree/devel/tests#specs

**Pull request merged**
