### PR TITLE
closes #19969; add testcase for #19969 #15952 #16306

### LINKED ISSUE #19969: `cannot generate code for: mSlice` with `toOpenArray`
Attempting to assign to a slice in the compile-time VM from the result of a `toOpenArray` fails with `cannot generate code for: mSlice`.

### Example
```nim
proc f(): array[1, byte] =
  var a: array[1, byte]
  result[0..0] = a.toOpenArray(0, 0)
 
echo static(f())
```

### Current Output
```
Error: cannot generate code for: mSlice
```

Tested with:
```
Nim Compiler Version 1.2.16 [Linux: amd64]
Compiled at 2022-07-03
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: c6a9f27b3e36bae9aacec1bd6c37893fb98fd33f
active boot switches: -d:release
```

```
Nim Compiler Version 1.6.6 [Linux: amd64]
Compiled at 2022-05-14
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

```
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-07-05
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: d2d8f1342b3125aac8e0592da25df61e6feb95b2
active boot switches: -d:release
```

### Expected Output
```
[0]
```
which, e.g., `echo f()` outputs.

### PR DESCRIPTION
**Pull request by ringabout**
follow up #20586
closes #19969
add testcase for #19969 #15952 #16306

### CODE REVIEW

**Comment by arnetheduck** [comment]
backport pls

**Comment by arnetheduck** [comment]
@narimiran ^

**Comment by ringabout** [comment]
Wrong place, it is https://github.com/nim-lang/Nim/pull/20586 that should be backported.

**Comment by narimiran** [comment]
> Wrong place, it is https://github.com/nim-lang/Nim/pull/20586 that should be backported.

Backported both #20586 and this one.

**Pull request merged**
