### PR TITLE
Merge pull request #2 from nim-lang/devel

### PR DESCRIPTION
**Pull request by gemath**
Update from base.

### CODE REVIEW

**Comment by Yardanico** [comment]
@gemath you probably wanted to create this against your Nim fork, not main repo :)

**Comment by gemath** [comment]
I wanted to update my fork's devel from nim-lang main's devel. Me wrong?

**Comment by Yardanico** [comment]
@gemath yeah, you created a PR to the main Nim repo :)

**Comment by gemath** [comment]
Oh, err, sry... :o/

**Pull request closed without merging**
