### PR TITLE
Nim-1.4: style fix

### PR DESCRIPTION
**Pull request by stefantalpalaru**
this allows "--styleCheck:usages --styleCheck:error"

### CODE REVIEW

**Comment by ringabout** [comment]
It is encouraged to add "backport" tag to the commit message or PR title instead of directly contributing to the corresponding branches.


> Important, critical bugfixes that have a tiny chance of breaking somebody's code should be backported to the latest stable release branch (currently 1.4.x) and maybe also all the way back to the 1.0.x branch. The commit message should contain the tag [backport] for "backport to the latest stable release" and the tag [backport:$VERSION] for backporting back to the given $VERSION (and all newer releases).

Ref https://nim-lang.github.io/Nim/contributing.html#the-cmdgit-stuff-general-commit-rules


> i'd rather if people pinged me. and/or marked their PRs as [backport]

Ref https://discord.com/channels/371759389889003530/763409397716090902/922005741806690365

**Comment by stefantalpalaru** [comment]
It's not possible to backport in this scenario, because the culprit type name is only present in the "version-1-4" branch.

It's the same with the similar "devel" PR: https://github.com/nim-lang/Nim/pull/19318 - the misspellings there are only present in that branch.

**Comment by ringabout** [comment]
Sorry, I read it wrongly.

**Comment by ringabout** [comment]
Unrelated CI failure => https://github.com/nim-lang/Nim/pull/19320

**Review by ringabout — APPROVED** [review]

**Pull request merged**
