### PR TITLE
add `toBits` and `fromBits` to math

### PR DESCRIPTION
**Pull request by ringabout**
It's not easy to support JS backend.

Todo in the following PR:
- [x] signbits
- [x] copysign

### CODE REVIEW

**Comment by Clyybber** [comment]
I don't think this should be in `math.nim` or in the stdlib at all because I don't see how it's better than writing the cast yourself.

**Comment by ringabout** [comment]
It's the basis of `signbits` and `copysign` function(Though I could not export them or use C ffi instead)
`signbits` and `copysign` are C99 function which are not in Nim yet. (copysign/signbits exists in many programming languages such as C/C++, Golang, Crystal, Zig, D etc)

As to `toBits/fromBits`

`@bitCast` in Zig

Float64bits in GoLang/VLang
https://golang.org/src/math/unsafe.go

toBits in Rust
https://doc.rust-lang.org/std/primitive.f64.html#method.to_bits

**Comment by ringabout** [comment]
So which is better?
```nim
func toBits*(x: float64): uint64 =
  ## Returns the IEEE 754 binary representation of float64.
  cast[ptr uint64](unsafeAddr x)[]

func toBits2*(x: float64): uint64 =
  ## Returns the IEEE 754 binary representation of float64.
  cast[uint64](x)

echo toBits(12.4)
echo toBits2(12.4)
```

```c
N_LIB_PRIVATE N_NIMCALL(NU64, toBits)(NF x) {
	NU64 result;
	result = (NU64)0;
	result = (*((NU64*) ((&x))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU64, toBits2)(NF x) {
	NU64 result;
	union { NF source; NU64 dest; } LOC1;
	result = (NU64)0;
	LOC1.source = x;
	result = LOC1.dest;
	return result;
}
```
I prefer `cast` which looks more clear.

**Comment by timotheecour** [comment]
@xflywind 
> So which is better?

can you check generated asm in both cases? if `cast[ptr uint64](unsafeAddr x)[]` leads to better/more performant code than `cast[uint64](x)` then maybe there's a case for adding `toBits`

**Comment by ringabout** [comment]
@timotheecour 
>> cast[ptr uint64](unsafeAddr x)[]   
- Error: opcCastIntToPtr: regs[rb].kind: rkNodeAddr

This doesn't work in VM
but `cast[uint64](x)` works

**Comment by timotheecour** [comment]
@xflywind 
> It's not easy to support JS backend.

we can probably do something similar to `toBitsImpl` (https://github.com/nim-lang/Nim/pull/16592) for js backend, either returning a BigInt or returning `array[2, uint32]`

maybe this can be unified with a custom type:
```nim
when defined js:
  type Bits = array[2, uint32]
else:
  type Bits = uint

proc toBits(x: float): Bits =
  # now we can support c,vm,js
```

EDIT: see also `asBigInt` and `BigUint64Array`
```nim
  proc asBigInt(x: float): int64 =
    # result is a `BigInt` type in js, but we cheat the type system
    # and say it is a `int64` type.
    # TODO refactor it using bigInt once jsBigInt is ready, pending pr #1640
    asm """
    const buffer = new ArrayBuffer(8);
    const floatBuffer = new Float64Array(buffer);
    const uintBuffer = new BigUint64Array(buffer);
    floatBuffer[0] = `x`;
    `result` = uintBuffer[0];"""
```
(with safari support caveat for `BigUint64Array` https://github.com/timotheecour/Nim/discussions/509)

**Pull request closed without merging**
