### PR TITLE
#Fixes #24536 building nimble 0.16.4 fails when running build_all.sh

### LINKED ISSUE #24536: building nimble 0.16.4 fails when running `build_all.sh`
### Description

building nimble 0.16.4 fails when running `build_all.sh`

### Nim Version

Nim Compiler Version 2.3.1 [Linux: amd64]
Compiled at 2024-12-14
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: d31cce557bc800f61664b7b67faae3ef8d789505
active boot switches: -d:release

### Current Output

```text
./build_all.sh
...
...
...
cmd: ./koch tools --skipUserCfg --skipParentCfg --hints:off
...
...
...
deps.cmd: git checkout -q 4e7e646b9819b72044e5262c2800e9f7ccfd1b16
deps.cmd: git submodule update --init
Submodule 'vendor/checksums' (https://github.com/nim-lang/checksums.git) registered for path 'vendor/checksums'
Submodule 'vendor/sat' (https://github.com/nim-lang/sat.git) registered for path 'vendor/sat'
Submodule 'vendor/zippy' (https://github.com/guzba/zippy.git) registered for path 'vendor/zippy'
Cloning into '/home/.../nim/dist/nimble/vendor/checksums'...
Cloning into '/home/.../nim/dist/nimble/vendor/sat'...
Cloning into '/home/.../nim/dist/nimble/vendor/zippy'...
Submodule path 'vendor/checksums': checked out 'f8f6bd34bfa3fe12c64b919059ad856a96efcba0'
Submodule path 'vendor/sat': checked out 'faf1617f44d7632ee9601ebc13887644925dcc01'
Submodule path 'vendor/zippy': checked out 'a99f6a7d8a8e3e0213b3cad0daf0ea974bf58e3f'
bin/nim c -o:bin/nimble -d:release --noNimblePath --skipUserCfg --skipParentCfg --hints:off dist/nimble/src/nimble.nim
/home/.../nim/dist/nimble/src/nimble.nim(11, 11) Error: cannot open file: sat/sat
FAILURE
```

### Expected Output

```text
build successful
```

### Known Workarounds

`./koch nimble` and `./koch tools --hints:off` can successfully build nimble.
So maybe `--skipUserCfg --skipParentCfg` options should be removed from `build_all.sh` and `build_all.bat`?

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by jmgomez**

### CODE REVIEW

**Comment by Araq** [comment]
These scripts were generated:

> DO NO EDIT DIRECTLY! auto-generated by `nim r tools/ci_generate.nim`

**Comment by jmgomez** [comment]
> These scripts were generated:
> 
> > DO NO EDIT DIRECTLY! auto-generated by `nim r tools/ci_generate.nim`

ups

**Comment by narimiran** [comment]
This is still not properly fixed.

**Comment by ringabout** [comment]
@narimiran  What is the error message?

**Comment by ringabout** [comment]
@narimiran What's the error message?

**Comment by ringabout** [comment]
I will fix it for nightlies

**Comment by ringabout** [comment]
it works for nightlies now https://github.com/nim-lang/nightlies/actions/runs/12372413439

**Pull request merged**
