### PR TITLE
abuse osx to test cpp

### PR DESCRIPTION
**Pull request by krux02**

### CODE REVIEW

**Comment by dom96** [comment]
What's the rationale for this?

**Comment by Araq** [comment]
If we simply enabled the C++ tests on all CIs they would timeout even more often.

**Comment by dom96** [comment]
> If we simply enabled the C++ tests on all CIs they would timeout even more often.

So create a separate run on Linux. Enabling C++ tests on macOS (which is under a high risk of becoming backlogged on Travis) sounds like a bad idea.

**Comment by Araq** [comment]
> So create a separate run on Linux. Enabling C++ tests on macOS (which is under a high risk of becoming backlogged on Travis) sounds like a bad idea.

Huh, I don't understand this remark.

**Comment by dom96** [comment]
Here is what I mean: https://docs.travis-ci.com/user/customizing-the-build/#build-matrix

You just use:

```
env:
  NIM_COMPILE_TO_CPP=false
  NIM_COMPILE_TO_CPP=true
```

Then check that env var and call either `nim cpp` or `nim c` in travis. Travis will start two jobs: a C and CPP job (in parallel).

**Pull request closed without merging**
