### PR TITLE
added lib/std/diff.nim

### PR DESCRIPTION
**Pull request by krux02**
this is a direct port [from C#](http://www.mathertel.de/Diff/ViewSrc.aspx)

### CODE REVIEW

**Comment by timotheecour** [comment]
wouldn't that make a perfect nimble package instead?

unless it's expected to be used in compiler (and even a bootstrapping could be used in that case, where source code from a specified package version is copied over to compiler sources)

**Comment by data-man** [comment]
> wouldn't that make a perfect nimble package instead?

+1

I prefer generic implementation, like [dtl](https://github.com/cubicdaiya/dtl) or [diff-match-patch-cpp-stl](https://github.com/leutloff/diff-match-patch-cpp-stl).
And put it to algorithm or sequtils.

**Comment by Araq** [comment]
> wouldn't that make a perfect nimble package instead?

Well we want to use it in ``testament``, that's why. ``unittest`` might also want to use it. It's better that Nim stays without dependencies to Nimble packages. Ymmv.

**Comment by dom96** [comment]
> Well we want to use it in testament, that's why. unittest might also want to use it. It's better that Nim stays without dependencies to Nimble packages. Ymmv.

If testament wants to use it then it shouldn't be in the stdlib. It can be moved to stdlib once unittest needs it (which frankly I would have never put in the stdlib in the first place :P)

**Comment by cooldome** [comment]
I agree it is good addition to testing infrastructure of any project. I would use it to display difference in my project that is using unittest module for example

**Comment by timotheecour** [comment]
I would also like to be able to use it (via nimble) ; do you have any plan on creating a nimble package?

**Pull request merged**
