### PR TITLE
added seq methods

### PR DESCRIPTION
**Pull request by HaCk3Dq**
``` Nim
import sequtils

let a = @[1, 2, 3, 4, 5]

echo a.reversed()
echo a.shuffled()
```

Output:

```
@[5, 4, 3, 2, 1]
@[4, 3, 1, 5, 2]
```

### CODE REVIEW

**Comment by dom96** [comment]
``reversed`` is already in the ``algorithm`` module: http://nim-lang.org/docs/algorithm.html#reversed,openArray[T],Natural,Natural

**Comment by dom96** [comment]
@Araq what's the rationale for having both ``algorithm`` and ``sequtils``, could we merge them?

**Comment by HaCk3Dq** [comment]
@dom96 Yeah, definetely

**Comment by Araq** [comment]
``shuffle`` is essential.

@dom96  algorithm is not restricted to 'seq'. Also I use algorithm and never sequtils, so I don't like to merge them.

**Comment by HaCk3Dq** [comment]
@Araq Should i PL only `shuffle` then?

**Comment by dom96** [comment]
@Araq I think merging them would be a good idea. There is no clear guideline set for what should go into the algorithm module and what should go into the sequtils module.

**Comment by Araq** [comment]
shuffled depends on the random number generator from math which is to be deprecated.
Also it should NOT call randomize()!
So ... it should be in a new random module or in its own module.

**Comment by HaCk3Dq** [comment]
@Araq but if its not calling `randomize`, then the result will be the same
Btw, `shuffled` is related to `seq`, not random module or smth else.
Do u think that creating a new module just for `shuffled` is better then adding it to `sequtils`? Then close this PR plz...

**Comment by Araq** [comment]
Ok, added 'reversed' manually.

> Do u think that creating a new module just for shuffled is better then adding it to sequtils? Then close this PR plz...

I think it should be part of a random number generator module since 'math.random' is about to become deprecated too.

**Comment by HaCk3Dq** [comment]
why, if `shuffled` is not related to `random`?
this `proc` works with seq, then it should be in `sequtils`
btw, if `math.random` will be deprecated, so we would need to change only one line with import of `random` proc.

**Comment by Araq** [comment]
> why, if shuffled is not related to random?

Shuffling is related to random number generation since it uses a random number generator. Sorry, I don't know what more to say. "Shuffle" is *fundamentally* different from "reverse" for this very reason.

**Comment by HaCk3Dq** [comment]
@Araq 
Hah, `shuffled` is not related to the random number generator, its just uses `random` proc, but is related to seqs, coz it is working with seqs.

**Pull request closed without merging**
