### PR TITLE
marshal now can handle binary strings

### PR DESCRIPTION
**Pull request by endragor**

### CODE REVIEW

**Comment by Araq** [comment]
This is slower than the old way and produces unreadable stuff. Better patch Json to support ``toBlob`` and ``fromBlob`` and use that here.

**Comment by endragor** [comment]
What would `toBlob` and `fromBlob` do, exactly?

**Comment by Araq** [comment]
Produce strings like  ``"AScii\x09"``

**Comment by endragor** [comment]
JsonParser currently tries to properly convert Unicode escapes (`\uXXXX`) into UTF-8 immediately when returning string token. Working with binary data doesn't really seem to belong to `json` module.

I have changed the approach to do encoding/decoding inside `marshal` so that random binary data turns into valid UTF-8 string (will use 2 bytes for non-ASCII chars). It now produces JSON strings which are human-readable in their ASCII parts.

**Pull request merged**
