### PR TITLE
bump to ubuntu-22.04 and swicth to docker ubuntu 18.04 i386

### PR DESCRIPTION
**Pull request by ringabout**
##[error]The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04 or ubuntu-22.04 (ubuntu-latest). For more details, see https://github.com/actions/runner-images/issues/6002

### CODE REVIEW

**Comment by ringabout** [comment]
Two solutions I might try later:

- removing imcompatible deps for 20.04 i386
- set up a 18.04 i386 images

**Comment by ringabout** [comment]
For the record

```
cmd: sudo apt-fast install --no-install-recommends --allow-downgrades -yq g++-multilib gcc-multilib libcurl4-openssl-dev:i386 libgc-dev:i386 libsdl1.2-dev:i386 libglib2.0-dev:i386 libffi-dev:i386
[apt-fast 13:49:55]
[apt-fast 13:49:55]Working... this may take a while.
E: Unable to correct problems, you have held broken packages.
[apt-fast 13:49:55]Package manager quit with exit code.
```

**Comment by metagn** [comment]
SSL test fixes could be:

https://github.com/nim-lang/Nim/blob/814d3e6818b6c4ed976818ecf525a599502e080e/tests/untestable/thttpclient_ssl_remotenetwork.nim#L111

Change this to just `"bad dh"`

https://github.com/nim-lang/Nim/blob/814d3e6818b6c4ed976818ecf525a599502e080e/tests/async/tasyncssl.nim#L69

Remove `and int.sizeof == 8`

And maybe just `disabled: i386` for [thttpclient_ssl](https://github.com/nim-lang/Nim/blob/devel/tests/stdlib/thttpclient_ssl.nim). The whole test depends on what It says is a "bogus" certificate, which the new default SSL version on the new ubuntu versions must not like. I'm guessing the timeout is also because one of these tests didn't close a server due to failing.

For SFML just `disabled: i386` in [sfml_test](https://github.com/nim-lang/Nim/blob/devel/tests/niminaction/Chapter8/sfml/sfml_test.nim) should be enough.

**Comment by ringabout** [comment]
The problem is that is it really the 32 bits system? According to https://askubuntu.com/questions/1334608/ubuntu-20-04-32-bit, ubuntu 22.04 obviously doesn't support native 32 bits. So the CI doesn't make sense to me.

**Comment by metagn** [comment]
https://canonical.com/blog/statement-on-32-bit-i386-packages-for-ubuntu-19-10-and-20-04-lts

It doesn't seem completely dropped. Also:

> We will also work with the WINE, Ubuntu Studio and gaming communities to use container technology to address the ultimate end of life of 32-bit libraries; it should stay possible to run old applications on newer versions of Ubuntu. Snaps and LXD enable us both to have complete 32-bit environments, and bundled libraries, to solve these issues in the long term.

So apparently they still support it for containers?

**Comment by ringabout** [comment]
> So apparently they still support it for containers?

Yeah, containers might be the best way out. I'm following instructions from https://forum.nim-lang.org/t/10069#66543.

**Comment by ringabout** [comment]
> So apparently they still support it for containers?

I cannot use `i386/ubuntu:latest` containers on Azure pipelines. While Github action support ``i386/ubuntu:latest` but it doesn't support i386 CPU. The host system doesn't support 64bits CPU, how the docker system build the csource?

```
cmd: make -C csources_v2 -j 4 -l 2 CC=gcc ucpu=
make: Entering directory '/__w/Nim/Nim/csources_v2'
makefile:186: *** unknown CPU architecture:  See makefile.nimf.  Stop.
make: Leaving directory '/__w/Nim/Nim/csources_v2'
```

**Comment by metagn** [comment]
Is there really a problem with the same azure pipelines setup but with ubuntu 22 and SFML removed? I can't find anything that implies that ubuntu 22 doesn't work on 32 bits, only that no one is working on supporting 32 bit (whether this is important or not). Was it checked if it was actually 32 bits?

**Comment by ringabout** [comment]
> Is there really a problem with the same azure pipelines setup but with ubuntu 22 and 
  SFML removed? I can't find anything that implies that ubuntu 22 doesn't work on 32 bits, 
  only that no one is working on supporting 32 bit (whether this is important or not). Was 
  it checked if it was actually 32 bits?

I don't think it is 32 bits.

> Linux fv-az457-794 5.15.0-1035-azure #42-Ubuntu SMP Tue Feb 28 19:41:23 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

https://www.quora.com/What-happens-if-you-install-a-64-bit-OS-in-a-32-bit-processor

> You cannot install a 64-bit operating system on a 32-bit computer, it won’t even boot up.

**Comment by ringabout** [comment]
Anyway succeeded by https://github.com/nim-lang/Nim/pull/21637

**Pull request closed without merging**
