### PR TITLE
add proc to check if directory can be read

### PR DESCRIPTION
**Pull request by a-mr**
`walkDir` does not check whether opening directory succeeded or not, `existsDir` is not enough because it does not check permissions that the directory can be opened.
Partially addresses #10309 & forum https://forum.nim-lang.org/t/4546.
Manually tested on Linux & Windows.

### CODE REVIEW

**Comment by demotomohiro** [comment]
Calling `checkDir` before calling `walkDir` is LBYL (Look Before You Leap) as cumulonimbus explained [here](https://forum.nim-lang.org/t/4546#28509).

I think adding `checkError` parameter with default value `false` to `walkDir` (and it check errors only when `checkError` is true) would works without breaking change.
Or add `walkDirSafe` that is same to `walkDir` but it check errors.

**Comment by a-mr** [comment]
Alternatively, Nim can expose a function for zeroing the last error, say `clearOsError`, and use it in the old fashion:
```nim
clearOsError()
for sub in walkDir(dir):
  echo sub
if osLastError() != OSErrorCode(0):
  echo "status: ", osErrorMsg(osLastError())
```

**Comment by Araq** [comment]
- Add a ``.since: (1, 1)`` declaration.
- Indentation uses 2 spaces everywhere else.

**Comment by disruptek** [comment]
`checkDir` just doesn't seem like a good name.  How does it differ from checking to see if the directory is traversable?

I'd rather these checks (LBYL) were opt-in versus opt-out.

**Comment by narimiran** [comment]
> * Add a `.since: (1, 1)` declaration.
> * Indentation uses 2 spaces everywhere else.

@a-mr, what's the status of this PR? Is it superseded by #13163? If so, can it be closed? If not, can you make the requested changes?

**Comment by alehander92** [comment]
ok guys, what is the usage of this? as @demotomohiro's comment seems very correct in that many usages of this (check if can be read, then read it .. oops now it cant be read as something changed) can lead to subtle bugs. 
probably this is still useful for stuff like filesystem listings/file managers etc, but still a note in the docs might be good

**Comment by a-mr** [comment]
Well, I don't understand TOCTOU w.r.t. to directories. Both wiki page and CERT C coding standards only mention TOCTOU of file access.

But it's true that #13163 will supersede this one. `checkDir` can be easily implemented using #13163.
I close this unless someone thinks it can still be useful.

**Pull request closed without merging**
