### PR TITLE
Mark some constructors as not nil.

### PR DESCRIPTION
**Pull request by philip-wernersbach**
By definition constructors cannot return nil, so mark them as such. This only marks a few that I use in my code as not nil, there's so many that we'll probably have to go case-by-case.

### CODE REVIEW

**Comment by reactormonk** [comment]
I always fancy whitespace changes in separate commits, but I'm not sure what the general policy on that is.

**Comment by Araq** [comment]
Can we make github/git shut up about whitespace changes? This is pathetic, git knows perfectly well it's dealing with text. Heck, it doesn't even work well with binary blobs anyway.

**Comment by def-** [comment]
https://stackoverflow.com/questions/4449834/commit-without-whitespace-changes-on-github

**Comment by dom96** [comment]
You just need to append ``?w=1`` to the URL after clicking the "Files Changed" tab: https://github.com/Araq/Nim/pull/2064/files?w=1

**Comment by philip-wernersbach** [comment]
Is this pull request in the merge queue, or do I need to do more work on it?

**Comment by Araq** [comment]
No, I think we should delay this "not nil" business until version 1.0 is out. We don't want to open another can of worms.

**Comment by dom96** [comment]
I'm going to reopen this so that we can merge it post-1.0.

**Comment by Araq** [comment]
This is now seriously outdated, closing.

**Pull request closed without merging**
