### PR TITLE
ref #23333; fixes AF_INET6 value on Linux

### PR DESCRIPTION
**Pull request by ringabout**
ref #23333

### CODE REVIEW

**Comment by arnetheduck** [comment]
the fix is to remove the values entirely - they shouldn't practically be used since all usages should go via https://github.com/nim-lang/Nim/blob/devel/lib/pure/nativesockets.nim#L128 (`toInt`) which translates to the platform-specific int - it was wrong to add any explicit numbers to this enum to begin with

**Comment by arnetheduck** [comment]
key takeaway: _all_ of these enum values, not just AF_INET6, are wrong on some platforms - I just used linux and AF_INET6 as an example (freebsd is 28 etc)

**Comment by Araq** [comment]
Merging because it improves the situation but in another breaking release we should do what @arnetheduck suggested.

**Comment by arnetheduck** [comment]
> breaking

nothing breaks really - this could not have worked because the values were incorrect in most cases.

**Pull request merged**
