### PR TITLE
Patch/fix whitespace

### PR DESCRIPTION
**Pull request by nanoant**
This PR realizes whitespace trimming proposed in https://github.com/nim-lang/Nim/issues/2967

The changes are split into separate commits:
* separate per each root directory: `compiler`, `lib`, `examples`, ...
* separate per each extension: `nim`, `txt`

This is done on OS X via:

    find . -name '*.nim' -exec sed -i '' -E 's/[[:space:]]+$//' {} +

Since `sed` RE above treats `CR` (from Windows `CR+LF`) as trailing whitespace too, this makes all line endings to be `LF` only (Unix).

### CODE REVIEW

**Comment by strcmp** [comment]
I am almost certain you said you did not want tons of commits for just whitespace changes, and yet here we are :laughing:

**Comment by reactormonk** [comment]
@strcmp one whitespace change to rule them all.

**Comment by nanoant** [comment]
@strcmp Let me quote my precious words :smiling_imp: from https://github.com/nim-lang/Nim/issues/2967

> I would either go for single commit fixing automatically trailing space, or one commit per each project folder, that is compiler, lib, tests, doc, examples. I don't think we should do separate commit per each file, this will just flood the history.

So I went for one commit per top level directory.

**Comment by nanoant** [comment]
> As usual, this will most likely break a lot of PRs.

@reactormonk Yeah, certainly these with whitespace changes. Show some faith to amazing Git technology, it can handle merge on whitespace changes. Anyway I can see only 14 PRs open, so this isn't really thrilling number.

**Pull request merged**
