### PR TITLE
fix a tiny formatting issue in `doc/destructors.rst`

### PR DESCRIPTION
**Pull request by derekdai**

### CODE REVIEW

**Comment by a-mr** [comment]
This markdown syntax is not yet supported by `rst.nim`:

image

Though there is a proposal to support it: https://github.com/nim-lang/RFCs/issues/355 . Even if it is implemented it probably won't support syntax highlighting for uniformity reasons because the current Nim convention is that anything between double backticks is not highlighted.

The current way to do it is either use double back-ticks:

```
``proc `=destroy`[T](f: var Foo[T])``
```

image

or even better with escaping, which supports syntax highlighting:

```
`proc \`=destroy\`[T](f: var Foo[T])`
```

image

though the latter is not quite standard RST.

**Comment by derekdai** [comment]
@a-mr Thank you for the information, there is indeed a problem with the rendering of [`Nim/destructors.html`](https://nim-lang.github.io/Nim/destructors.html#hook-generation). I checked it locally before issuing the PR, and the results are as follows
image

There are probably some differences between CI and my local environment that I did not notice. I will use double ticks instead, thank you.

**Comment by a-mr** [comment]
@derekdai ,

I feel very uncomfortably when different set-ups behave differently.
Do you remember how you ran the local version, with `nim rst2html`, `./koch docs` or ...?

**Comment by derekdai** [comment]
@a-mr I didn’t install nodejs and the doc generation process ended in error, but I didn’t notice it. When I confirmed the result, the format in my local old `doc/html/destructors.html` was actually correct (I haven’t found the reason yet) In the end, I mistakenly thought that the correct syntax was used. So it was completely a problem of my own development environment.

**Pull request merged**
