### PR TITLE
Alternative move analyser that avoids the expensive creation of …

### PR DESCRIPTION
**Pull request by Araq**
…a control flow graph

Todo:

- [x] fix the bug "break" does not leave the loop that owns the variable in question.
- [x] fix the bug which prevents `lastUse(obj.field)` from working
- [x] fix the remaining `result` false negatives
- [x] fix false positive in `symObj` for `proc fieldVisible`.
- [x] the move analyser must be smarter for this pattern: 

```nim
  if cond:
    let a = result
    result = newNodeI(nkPragmaBlock, a.info)
```

- [x] figure out why the algorithm doesn't understand closures properly
- [x] use the algorithm from sempass2 to set `nfFirstWrite`.
- [x] enable the new analysers and make tests green again

### CODE REVIEW

**Comment by planetis-m** [comment]
Issue with the last change: doesn't work in JS backend, Code:

```js
result_469762054 = (next_603979819(state_603979789[0]) < 0);
```
returns always false. The mod 2 worked. Any ideas?

**Comment by Araq** [comment]
While it's nowhere near correct, here are numbers to justify its existence:

Old move analyser:

nim c --gc:orc --compileOnly compiler\nim.nim
162289 lines; 20.660s; 1.016GiB peakmem;

New move analyser:

nim c --gc:orc --compileOnly compiler\nim.nim
162094 lines; 13.596s; 1.016GiB peakmem;

Unfortunately no reduction in memory consumption was achieved. However, more than 6 seconds of compile-time improvement is nothing to complain about.

**Comment by ringabout** [comment]
The bootstrap failed because the compiler now bootstraps with `-d:nimPreviewSystem`. If you are using assert/doAssert, you need to add
```nim
when defined(nimPreviewSlimSystem):
  import std/assertions
```

When doing local bootstrap, disabled nimPreviewSlimSystem or use `--lib:lib`.

**Comment by Araq** [comment]
Succeeded by https://github.com/nim-lang/Nim/pull/20471 which has fewer weird special cases, produces slightly better results and runs just as fast.

**Pull request closed without merging**
