### PR TITLE
Faster binary gcd algorithm

### PR DESCRIPTION
**Pull request by Paalon**
See these.
[Binary GCD algorithm - Wikipedia](https://en.wikipedia.org/wiki/Binary_GCD_algorithm)
https://qiita.com/SatoshiTerasaki/items/a7ada593560747354a43 (Japanese)
[Julia's gcd](https://github.com/JuliaLang/julia/blob/d386e40c17d43b79fc89d3e579fc04547241787c/base/intfuncs.jl#L28-L49)
[Nim's gcd](https://github.com/nim-lang/Nim/blob/master/lib/pure/math.nim#L447)
[Julia's trailing_zeros](https://github.com/JuliaLang/julia/blob/d386e40c17d43b79fc89d3e579fc04547241787c/base/int.jl#L240-L249)
[Julia's thread when binary GCD is implimented](https://github.com/JuliaLang/julia/pull/8410)
[Stein's (binary) GCD algorithm (iterative version) - Nim Forum](https://forum.nim-lang.org/t/3659)
Current Nim's gcd uses Euclidean algorithm but Binary GCD algorithm is faster in expected time for random numbers.

The following script is a rough performance checker run on Nim 0.18.0.

```nim
import math
import times
import random

proc trailingZeros[T](n: T): T =
    var order = 0
    var n = n
    while (n and 1) == 0:
        inc(order)
        n = n shr 1
    order

proc binary_gcd[T](x, y: T): T =
    if x == 0:
        return abs(y)
    if y == 0:
        return abs(x)
    let zx = trailingZeros(x)
    let zy = trailingZeros(y)
    let k = min(zx, zy)
    var u = abs(x shr zx)
    var v = abs(y shr zy)
    while u != v:
        if u > v:
            swap u, v
        v -= u
        v = v shr trailingZeros(v)
    u shl k

randomize()

const size = 1000000
const n = 10000000
var xs: array[n, array[2, int]]
for i in 1..n:
    let x = rand(size)
    let y = rand(size)
    xs[i] = [x, y]

var startTime = cpuTime()
for i in 1..n:
    discard binary_gcd(xs[i][0], xs[i][1])
var endTime = cpuTime()
var time = endTime - startTime
echo "binary gcd"
echo time

startTime = cpuTime()
for i in 1..n:
    discard gcd(xs[i][0], xs[i][1])
endTime = cpuTime()
time = endTime - startTime
echo "gcd"
echo time

startTime = cpuTime()
for i in 1..n:
    discard binary_gcd(xs[i][0], xs[i][1])
endTime = cpuTime()
time = endTime - startTime
echo "binary gcd"
echo time

startTime = cpuTime()
for i in 1..n:
    discard gcd(xs[i][0], xs[i][1]) # Current Nim's gcd
endTime = cpuTime()
time = endTime - startTime
echo "gcd"
echo time

for i in 1..n:
    if not(binary_gcd(xs[i][0], xs[i][1]) == gcd(xs[i][0], xs[i][1])):
        echo "doesn't match"

# Results

# const size = 1000000
# const n = 10000000
# binary gcd
# 1.628978
# gcd
# 1.898572000000001
# binary gcd
# 1.611073999999999
# gcd
# 1.881994000000001

# const size = 100
# const n = 10000000
# binary gcd
# 0.5495460000000001
# gcd
# 0.6971379999999998
# binary gcd
# 0.5495590000000001
# gcd
# 0.6747879999999999
```

### CODE REVIEW

**Comment by data-man** [comment]
@Paalon 
Thanks!

Please compare with [fastest-way-to-compute-the-greatest-common-divisor](https://lemire.me/blog/2013/12/26/fastest-way-to-compute-the-greatest-common-divisor/)
Nim has built-in countTrailingZeroBits proc (in the bitops module).

**Comment by data-man** [comment]
Also, I think it will not be superfluous to add a few words to the docs about the algorithm.
This will be useful for novice programmers. :)

**Comment by Paalon** [comment]
Built in `countTrailingZeroBits` makes faster.
```nim
import math
import times
import random
import bitops

proc binary_gcd1[T](x, y: T): T =
    if x == 0:
        return abs(y)
    if y == 0:
        return abs(x)
    let zx = countTrailingZeroBits(x)
    let zy = countTrailingZeroBits(y)
    let k = min(zx, zy)
    var u = abs(x shr zx)
    var v = abs(y shr zy)
    while u != v:
        if u > v:
            swap u, v
        v -= u
        v = v shr countTrailingZeroBits(v)
    u shl k

proc binary_gcd2[T](x, y: T): T =
    if x == 0:
        return abs(y)
    if y == 0:
        return abs(x)
    let shift = countTrailingZeroBits(x or y)
    var u = x shr countTrailingZeroBits(x)
    var v = y shr countTrailingZeroBits(y)
    while v != 0:
        if u > v:
            swap u, v
        v -= u
        v = v shr countTrailingZeroBits(v)
    u shl shift

randomize()

const size = 1000000
const n = 10000000
var xs: array[n, array[2, int]]
for i in 1..n:
    let x = rand(size)
    let y = rand(size)
    xs[i] = [x, y]

# prevent optimization due to discard
var dummy = 0

var startTime = cpuTime()
for i in 1..n:
    dummy = binary_gcd1(xs[i][0], xs[i][1])
var endTime = cpuTime()
var time = endTime - startTime
echo "binary gcd1"
echo time

startTime = cpuTime()
for i in 1..n:
    dummy = binary_gcd2(xs[i][0], xs[i][1])
endTime = cpuTime()
time = endTime - startTime
echo "binary gcd2"
echo time

startTime = cpuTime()
for i in 1..n:
    dummy = gcd(xs[i][0], xs[i][1])
endTime = cpuTime()
time = endTime - startTime
echo "gcd"
echo time

for i in 1..n:
    if not(binary_gcd1(xs[i][0], xs[i][1]) == binary_gcd2(xs[i][0], xs[i][1])):
        echo "doesn't match"

# Results

# const size = 1000000
# const n = 10000000

# binary gcd1
# 0.469072
# binary gcd2
# 0.511906
# gcd
# 1.886872
```

The proposed URL's code is `binary_gcd2` but `binary_gcd1` is a bit faster.

**Comment by Paalon** [comment]
I have noticed that Nim's shift operators are not symmetric againts signed. https://github.com/nim-lang/Nim/issues/6255 This means we need to calculate abs(x) and abs(y) before gcd unless Nim support C-like bit shift operators.

**Comment by andreaferretti** [comment]
@data-man 
>  gcd works for floats also.

What would that even mean? Real numbers are a field

**Comment by data-man** [comment]
@andreaferretti 

I didn't invent it. :)
It's current implementation. For which counting bits for floats does not make sense.
Only therefore I have paid to this attention.

**Comment by data-man** [comment]
Shorter version:
```nim
proc gcd*(x, y: SomeInteger): SomeInteger =
  ## Computes the greatest common (positive) divisor of ``x`` and ``y``.
  ## Using binary GCD (aka Stein's) algorithm.
  when x is SomeSignedInt:
    let x = abs(x)

  when y is SomeSignedInt:
    let y = abs(y)

  if x == 0:
    return y

  if y == 0:
    return x

  let zx = countTrailingZeroBits(x)
  let zy = countTrailingZeroBits(y)
  let k = min(zx, zy)
  var u = x shr zx
  var v = y shr zy

  while u != v:
    if u > v:
      swap u, v
    v -= u
    v = v shr countTrailingZeroBits(v)
  u shl k
```

**Comment by Paalon** [comment]
I tested the following code and binary_gcd2 seems faster than binary_gcd1.
```nim
import bitops

proc euclidean_gcd*[T](x, y: T): T =
  ## Computes the greatest common (positive) divisor of ``x`` and ``y``.
  ## Note that for floats, the result cannot always be interpreted as
  ## "greatest decimal `z` such that ``z*N == x and z*M == y``
  ## where N and M are positive integers."
  var (x, y) = (x, y)
  while y != 0:
    x = x mod y
    swap x, y
  abs x

proc binary_gcd1*(x, y: SomeInteger): SomeInteger =
  ## Computes the greatest common (positive) divisor of ``x`` and ``y``.
  ## Using binary GCD (aka Stein's) algorithm.
  # Nim's bit shift right is logical shift (not arithmetic shift)
  # therefore x > 0 and y > 0 are required.
  when x is SomeSignedInt:
    let x = abs(x)
  when y is SomeSignedInt:
    let y = abs(y)

  if x == 0:
    return y
  if y == 0:
    return x

  let zx = countTrailingZeroBits(x)
  let zy = countTrailingZeroBits(y)
  let k = min(zx, zy)
  var u = x shr zx
  var v = y shr zy
  while u != v:
    if u > v:
      swap u, v
    v -= u
    v = v shr countTrailingZeroBits(v)
  u shl k

proc binary_gcd2*(x, y: SomeInteger): SomeInteger =
  ## Computes the greatest common (positive) divisor of ``x`` and ``y``.
  ## Using binary GCD (aka Stein's) algorithm.
  # Nim's bit shift right is logical shift (not arithmetic shift)
  # therefore x > 0 and y > 0 are required.
  when x is SomeSignedInt:
    var x = abs(x)
  else:
    var x = x
  when y is SomeSignedInt:
    var y = abs(y)
  else:
    var y = y

  if x == 0:
    return y
  if y == 0:
    return x

  let shift = countTrailingZeroBits(x or y)
  y = y shr countTrailingZeroBits(y)
  while x != 0:
    x = x shr countTrailingZeroBits(x)
    if y > x:
      swap y, x
    x -= y
  y shl shift
```

```nim
import gcd
import times
import random

randomize()

const size = 10000000
const n = 10000000
var xs: array[n, array[2, int]]
for i in 1..n:
    let x = rand(size)
    let y = rand(size)
    xs[i] = [x, y]

var dummy = 0
var startTime = epochTime()
for i in 1..n:
    dummy = binary_gcd1(xs[i][0], xs[i][1])
var endTime = epochTime()
echo "binary gcd1"
echo endTime - startTime

startTime = epochTime()
for i in 1..n:
    dummy = binary_gcd2(xs[i][0], xs[i][1])
endTime = epochTime()
echo "binary gcd2"
echo endTime - startTime

startTime = epochTime()
for i in 1..n:
    dummy = euclidean_gcd(xs[i][0], xs[i][1])
endTime = epochTime()
echo "euclidian gcd"
echo endTime - startTime

startTime = epochTime()
for i in 1..n:
    dummy = binary_gcd1(xs[i][0], xs[i][1])
endTime = epochTime()
echo "binary gcd1"
echo endTime - startTime

startTime = epochTime()
for i in 1..n:
    dummy = binary_gcd2(xs[i][0], xs[i][1])
endTime = epochTime()
echo "binary gcd2"
echo endTime - startTime

startTime = epochTime()
for i in 1..n:
    dummy = euclidean_gcd(xs[i][0], xs[i][1])
endTime = epochTime()
echo "euclidian gcd"
echo endTime - startTime
```

```bash
binary gcd1
0.6412460803985596
binary gcd2
0.5928440093994141
euclidian gcd
2.321835994720459
binary gcd1
0.6052498817443848
binary gcd2
0.5690431594848633
euclidian gcd
2.313611030578613
```

**Comment by data-man** [comment]
<details><summary>The code:</summary>

```nim
import nimbench, math, random, bitops

const
  n = 10000000

let
  size = 10000000

var
  xs: array[n, array[2, int]]

for i in 0..xs.high:
    var x = rand(size)
    var y = rand(size)
    xs[i] = [x, y]

proc euclidean_gcd*[T](x, y: T): T =
  ## Computes the greatest common (positive) divisor of ``x`` and ``y``.
  ## Note that for floats, the result cannot always be interpreted as
  ## "greatest decimal `z` such that ``z*N == x and z*M == y``
  ## where N and M are positive integers."
  var (x, y) = (x, y)
  while y != 0:
    x = x mod y
    swap x, y
  abs x

proc binary_gcd1*(x, y: SomeInteger): SomeInteger =
  ## Computes the greatest common (positive) divisor of ``x`` and ``y``.
  ## Using binary GCD (aka Stein's) algorithm.
  # Nim's bit shift right is logical shift (not arithmetic shift)
  # therefore x > 0 and y > 0 are required.
  when x is SomeSignedInt:
    let x = abs(x)
  when y is SomeSignedInt:
    let y = abs(y)

  if x == 0:
    return y
  if y == 0:
    return x

  let zx = countTrailingZeroBits(x)
  let zy = countTrailingZeroBits(y)
  let k = min(zx, zy)
  var u = x shr zx
  var v = y shr zy
  while u != v:
    if u > v:
      swap u, v
    v -= u
    v = v shr countTrailingZeroBits(v)
  u shl k

proc binary_gcd2*(x, y: SomeInteger): SomeInteger =
  ## Computes the greatest common (positive) divisor of ``x`` and ``y``.
  ## Using binary GCD (aka Stein's) algorithm.
  # Nim's bit shift right is logical shift (not arithmetic shift)
  # therefore x > 0 and y > 0 are required.
  when x is SomeSignedInt:
    var x = abs(x)
  else:
    var x = x
  when y is SomeSignedInt:
    var y = abs(y)
  else:
    var y = y

  if x == 0:
    return y
  if y == 0:
    return x

  let shift = countTrailingZeroBits(x or y)
  y = y shr countTrailingZeroBits(y)
  while x != 0:
    x = x shr countTrailingZeroBits(x)
    if y > x:
      swap y, x
    x -= y
  y shl shift


bench(euclidean_gcd):
  var
    dummy = 0

  for i in 0..xs.high:
    dummy = euclidean_gcd(xs[i][0], xs[i][1])
  
  doNotOptimizeAway(dummy)


benchRelative(binary_gcd1):
  var
    dummy = 0

  for i in 0..xs.high:
    dummy = binary_gcd1(xs[i][0], xs[i][1])

  doNotOptimizeAway(dummy)

benchRelative(binary_gcd2):
  var
    dummy = 0

  for i in 0..xs.high:
    dummy = binary_gcd2(xs[i][0], xs[i][1])

  doNotOptimizeAway(dummy)

runBenchmarks()
```
</details>

GlobalBenchmark                            |          |  263.80ps |   3.79G|
--------------------------|----|----|------------------------------------------
bench.nim                                  | relative | time/iter | iters/s|
euclidean_gcd                              |          |     1.66s | 601.59m|
binary_gcd1                                |  236.83% |  701.87ms |    1.42|
binary_gcd2                                |  227.04% |  732.13ms |    1.37|

for me.

**Comment by mratsim** [comment]
As [mentioned in GMP](https://gmplib.org/manual/Binary-GCD.html) it's important to check if the performance improvement is also there if there is a large bit-distance between the most significant bit of both operands.

Here is a modified bench on my machine.

```Nim
import gcd
import times
import random

randomize()

const n = 10000000
var xs: array[n, array[2, int]]
for i in 1..n:
    let x = rand(0..100)
    let y = rand(100_000_000..1_000_000_000)
    xs[i] = [x, y]

var dummy = 0
var startTime = epochTime()
for i in 1..n:
    dummy = binary_gcd1(xs[i][0], xs[i][1])
var endTime = epochTime()
echo "binary gcd1"
echo endTime - startTime

startTime = epochTime()
for i in 1..n:
    dummy = binary_gcd2(xs[i][0], xs[i][1])
endTime = epochTime()
echo "binary gcd2"
echo endTime - startTime

startTime = epochTime()
for i in 1..n:
    dummy = euclidean_gcd(xs[i][0], xs[i][1])
endTime = epochTime()
echo "euclidian gcd"
echo endTime - startTime

startTime = epochTime()
for i in 1..n:
    dummy = binary_gcd1(xs[i][0], xs[i][1])
endTime = epochTime()
echo "binary gcd1"
echo endTime - startTime

startTime = epochTime()
for i in 1..n:
    dummy = binary_gcd2(xs[i][0], xs[i][1])
endTime = epochTime()
echo "binary gcd2"
echo endTime - startTime

startTime = epochTime()
for i in 1..n:
    dummy = euclidean_gcd(xs[i][0], xs[i][1])
endTime = epochTime()
echo "euclidian gcd"
echo endTime - startTime
```

For instance I noticed that the threshold where division starts to be faster than bitshift is about when `clz(b) - clz(a) ~= 8` on big ints. See [here](https://github.com/status-im/nim-stint/blob/8e25b30209e951bcabfc2d1cd97ef0b971554648/stint/private/uint_div.nim#L229). Note that for uint32/uint64 the threshold is probably higher, shifts on big ints is not costless.

Here are the results on i5-5257U (dual core Broadwell 2.7Ghz, turbo 3.1Ghz)

```
binary gcd1
0.6207358837127686
binary gcd2
0.590688943862915
euclidian gcd
1.19217586517334
binary gcd1
0.6806910037994385
binary gcd2
0.6890521049499512
euclidian gcd
0.9818718433380127
```

**Comment by Paalon** [comment]
We need to choose which implementation of binary gcd is best.

**Comment by data-man** [comment]
@Paalon 

Thanks!

**Pull request merged**
