### PR TITLE
Use module actual file instead of PSym.info

### PR DESCRIPTION
**Pull request by yyoncho**
After this you can do goto module from module import

### CODE REVIEW

**Comment by Araq** [comment]
Nice but why is the CI failing?

**Comment by narimiran** [comment]
Note to myself: This one should be backported to 1.6.

**Comment by yyoncho** [comment]
> Nice but why is the CI failing?

Fixed.

**Comment by yyoncho** [comment]
@Araq thanks.

@narimiran let me know if you are going to backport to 1.6 . Ditto for https://github.com/nim-lang/Nim/pull/19944

**Comment by narimiran** [comment]
> @narimiran let me know if you are going to backport to 1.6 . Ditto for https://github.com/nim-lang/Nim/pull/19944

Both are now backported to 1.6.

**Pull request merged**
