### PR TITLE
Fix backwards array indexing.

### PR DESCRIPTION
**Pull request by solo989**
No clutter this time.
#14497

### CODE REVIEW

**Comment by solo989** [comment]
I have no idea why it's failing. System seems a bit fragile. Works fine on my local copy.

**Comment by alaviss** [comment]
You can try closing and reopening the PR to restart the CI.

**Comment by timotheecour** [comment]
> I have no idea why it's failing. System seems a bit fragile. Works fine on my local copy.

you have to look at the actual errors in the logs; just restarting CI is not gonnafix those; eg:
2020-06-06T13:59:32.4582070Z /Users/runner/runners/2.169.1/work/1/s/lib/pure/pathnorm.nim(96, 35) Error: attempt to access a nil address kind: rkInt

**Comment by solo989** [comment]
I'm closing this. Backwards index seems to have some bugs associated with it. If someone else wants to take a crack at getting strings to return var chars be my guest.

**Pull request closed without merging**
