### PR TITLE
sequtils - doco fix & tests moved to test suite

### PR DESCRIPTION
**Pull request by jlp765**
Files added/modified in the collections test directory.  Tests are from the bottom of sequtils.nim
(tests of collections category all passed on my PC.)

Fix doco for apply() which had map rather than apply (had been copied, but not changed).

### CODE REVIEW

**Comment by dom96** [comment]
What is the reasoning for the movement of those tests?

**Comment by jlp765** [comment]
To have tests in the test suites.  

I assumed that all tests should be in the test suite, rather than have the tests spread across two different locations.

**Comment by dom96** [comment]
I think it's better to keep tests for a specific module as close to the module as possible. Spreading them out like this will make finding them difficult.

**Comment by jlp765** [comment]
Sort of negates the purpose of a test suite  (I don't care either way, its more a question of what the standard/methodology is).

If the standard is to go the test suite way, then the issue is that the ``stdlib`` test category holds more than just the system.nim tests.  If the category matches (at least) the lib module, then it is easier to identify tests that are associated with a specific lib.  Of course, tests for a lib module can still be spread wider through the test suite if they are part of testing some other functionality.

Or, 
the test suite does NO real testing of a module, just higher level testing of concepts ???
(and each lib module has a heap of testing code at its bottom, reducing its "cleanness" of code, and testing is NOT independent of compiling.  Regression testing needs a force compile of all modules to test inter-module dependencies)

Or,
a hodge-podge of both :wink:

**Comment by Araq** [comment]
I take the hodge-podge over an ever increasing set of arbitrary rules and policies, thanks. ;-)

**Comment by dom96** [comment]
Seeing as me and @Araq agree I will close this.

Sorry @jlp765!

**Pull request closed without merging**
