### PR TITLE
Fix nimdoc generation for lib/pure/selectors.nim

### PR DESCRIPTION
**Pull request by avsej**

### CODE REVIEW

**Comment by avsej** [comment]
@Araq yes it works

**Comment by Araq** [comment]
Why didn't it work before? and how does that fix it?

**Comment by avsej** [comment]
@Araq `when defined(nimdoc)` the object does not have property `fds`, so there was compilation error

```
lib/pure/selectors.nim(298, 27) Error: undeclared field: 'fds'
lib/pure/selectors.nim(298, 27) Error: expression '.' cannot be called
```

**Comment by dom96** [comment]
Ugh, I dislike these workarounds. They add noise to the code.

**Pull request merged**
