### PR TITLE
removed coro prefixes from coro.nim

### PR DESCRIPTION
**Pull request by reactormonk**
We did away with the type prefixes a while back, let's not introduce new ones.

### CODE REVIEW

**Comment by yglukhov** [comment]
Are those deprecations really needed? o_O

**Comment by dom96** [comment]
They are not.

**Comment by reactormonk** [comment]
No more deprecations.

**Comment by dom96** [comment]
@r-ku will this cause any issues?

**Comment by Varriount** [comment]
Hm. A few of those identifiers seem very contextually ambiguous to me, especially "sleep" and "start". Although I dislike prefixes, I dislike ambiguity more.

**Comment by r-ku** [comment]
Renaming ``coroYield()`` to ``sleep()`` is technically incorrect. Primary purpose of proc is to give up execution and let something else execute which is not sleeping at all. Sleep functionality is a convenience addon if you will and it is completely optional. Thats why default sleep time value is 0.

@Varriount is very correct about ambiguity. I added prefixes for that very reason even though i dont like them either. It also nicely solved collision with ``yield`` keyword. Besides currently importing ``os`` and ``coro`` in same module will create ambiguity between ``coro.sleep()`` and ``os.sleep()``.

All in all i think having no prefixes is good but current suggested names most likely do more harm than good. It would probably be ok (aside from ``sleep()``) if we could mandate calling functions with module prefix thus avoiding ambiguity problems as opposed to directly importing them into current module scope and confusing compiler what to call. But its probably not possible (yet?) right?

**Comment by dom96** [comment]
Yeah. I didn't notice the change from ``coroYield`` to ``sleep``. If it wasn't for the fact that ``yield`` is a keyword then this would work.

**Comment by reactormonk** [comment]
Yeah, I don't like the part where `yield` is a keyword either. I figured sleep is the closest thing, because it sleeps the current execution. Also, I'd prefer `coro.start` over `coroStart`.

**Comment by Araq** [comment]
Get rid of the prefixes and document people should use ``from coroutines import nil``.

**Comment by r-ku** [comment]
Using ``from .. import ..`` does not solve ambiguity problems though.

**Comment by reactormonk** [comment]
With `import nil` you will have to specify `coro.start` etc, so that should solve the ambiguity problem.

**Comment by r-ku** [comment]
Oh oh, was not aware of that, thank you for clarification. And well.. Its also cumbersome thing to do dont you think? IMHO ``import module`` should do what ``from module import nil`` does, and there should be explicit "import all" kind of statement. Then we would not have these problems and it would be immediately obvious where from procs come (you know calling functions like ``os.sleep()`` and ``coro.sleep()``)..

**Comment by Varriount** [comment]
@Araq Requiring "from coroutines import nil" is a workaround at best. It complicates UFC syntax, and is rather non-standard.

**Comment by reactormonk** [comment]
But that's only on `sleep`, the other procs don't conflict.

**Comment by r-ku** [comment]
You cant use this module without ``sleep``/``yield``. It is core of the feature.

**Comment by dom96** [comment]
You don't need ``from coro import nil``, you can disambiguate when ambiguities happen instead of always providing the module qualification.

**Comment by Araq** [comment]
> IMHO import module should do what from module import nil does, and there should be explicit "import all" kind of statement.

This has been argued to death, is independent of this PR, and it's only a good idea when you never ever look at the results.

**Comment by reactormonk** [comment]
@r-ku You can still fully qualify names, even if you don't `from x import nil`. So even with `import coro` you can still `coro.sleep`.

**Comment by Araq** [comment]
Also ``coroYield`` should become ``yld``, not ``sleep``.

**Comment by Varriount** [comment]
@Araq Eeew. Why not "suspend" instead?

**Comment by r-ku** [comment]
Initially i had it named ``yields``. What do you think about that variant?

**Comment by reactormonk** [comment]
`yields` sounds good to me. FYI, you can make a PR against my PR via https://github.com/reactormonk/nim/compare/coro-remove-prefix

**Comment by Araq** [comment]
yields and suspend are fine too.

**Comment by r-ku** [comment]
@reactormonk im pretty sure you would take by far less time changing one name and committing as opposed to me going through the trouble of figuring out how to send PR to PR ;)

**Comment by r-ku** [comment]
Oh or in the spirit of python - ``yieldFrom`` maybe?

**Comment by reactormonk** [comment]
@r-ku you're right on that. I'll just push whatever we decide on.

**Comment by Araq** [comment]
Just name it 'suspend', ensure the docs mention `yield`:idx:  with the index annotation and call it a day.

**Comment by dom96** [comment]
Yeah, what @Araq said :)

**Comment by reactormonk** [comment]
Suspend sounds good. How do I do the `:idx:` part?

**Comment by dom96** [comment]
Like this: https://github.com/nim-lang/Nim/blob/devel/doc/manual/compiler_msgs.txt#L5

**Pull request merged**
