### PR TITLE
added support for openArray's for 'gcd' & 'lcm'

### PR DESCRIPTION
**Pull request by drkameleon**

### CODE REVIEW

**Comment by Araq** [comment]
Requires the upcoming ``.since`` pragma. Stay tuned.

**Comment by drkameleon** [comment]
> Requires the upcoming `.since` pragma. Stay tuned.

Can you please elaborate? Is there sth I can do now? (Just searched for the pragma you mentioned but still not sure)

**Comment by Araq** [comment]
No, please wait for a couple of hours. ;-)

**Comment by Araq** [comment]
Annotate this procs please with ``.since: (1, 1)``

**Pull request closed without merging**
