### PR TITLE
Revert "Fixes #12187"

### LINKED ISSUE #12187: questionable `csize` definition in `system.nim`
I'm sure the story of `csize` is different from `cstring`.

## Current definition

```Nim
csize* {.importc: "size_t", nodecl.} = int
    ## This is the same as the type ``size_t`` in *C*.
```

what interesting is the comment claims `csize` has the same type as ``size_t`` in *C*.
in reality, when we take a look at C or CPP header file, especially stddef.h, they agree it should be an unsigned int.

[CPP doc](https://en.cppreference.com/w/cpp/types/size_t) and [GNU C doc](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html) also agree `size_t` should be unsigned int.

if `csize` is an `int`, it implies csize can be negative or cannot exceed `high(int)` which is questionable.

also if it is used in FFI, it can be a subtle bug, very difficult to track down.

### PR DESCRIPTION
**Pull request by Araq**
Reverts nim-lang/Nim#12321

### CODE REVIEW

**Comment by Clyybber** [comment]
To be honest, I don't quite see the issue here. The packages have been fixed, this change has caused no real issues. The ecosystem has adapted to the breakage and now we revert this?
I think that will piss off a lot of pkg maintainers. (Also this change was a correction, not an opinionated change)

**Comment by Araq** [comment]
It does break wrappers not covered by "important packages" and also the change should have been something like:

```nim

type 
  csize {.deprecated: "use csize_t instead".}
  csize_t = <correct definition here>

```

Also, the fact that you had to add overloads that do the same "lie" about signedness means that the old ``csize``'s definition actually was better.

**Comment by krux02** [comment]
Here, this compiles with your rever applied

```nim
proc main() =
  var x: csize = -1
  var y: csize = 123
  echo x, " < ", y, ": ", x < y

main()
```

output:
```
-1 < 123: false
```

**Comment by Araq** [comment]
3 replies, all managed to miss the point entirely. Good job.

**Comment by krux02** [comment]
> 3 replies, all managed to miss the point entirely. Good job.

I guess we are all stupid then. It is all our fault.

> It does break wrappers not covered by "important packages" and also the change should have been something like: [...]

That is not what this PR does either.

**Comment by bluenote10** [comment]
> 3 replies, all managed to miss the point entirely.

An explanation would really help. I don't see why that is a step forward either. So far the argument for keeping this bug (to me that's a bug) is that running into problems has a low probability, but doesn't that make it even more ugly?

**Comment by Araq** [comment]
Reverted because it broke code. I dunno what's so hard to understand about it.

**Comment by FedericoCeratto** [comment]
I support a smoother deprecation process, like the one Araq suggested, because the abrupt change in #12321 creates conditions where `csize` has different meaning in Nim 1.0.0 and the next release, making it difficult to maintain backward compatibility in libraries.
Also, the deprecation process provides a friendly warning to developers instead of introducing a sudden breaking change.

**Comment by krux02** [comment]
@FedericoCeratto 
> I support a smoother deprecation process, like the one Araq suggested, because the abrupt change in #12321 creates conditions where csize has different meaning in Nim 1.0.0 and the next release, making it difficult to maintain backward compatibility in libraries.

Well it is true that this is an abrupt change. But it isn't hard to maintain backwards compatibility with this change. Explicit conversions like `csize(x)` or `cast[csize](x)` will work no matter if `csize` in defined as `int` or `uint`. A new type `csize_t` and deprecating `csize` would force you to either fix the deprecation warning, drop older nim versions, or copy the definition of `csize_t` locally into the project to make it compatible with old versions of Nim.





@FedericoCeratto

**Pull request merged**
