### PR TITLE
Fix backwards array indexing.

### LINKED ISSUE #14497: proc `[]`(s: string; i: BackwardsIndex): char {...} doesn't return var char
### Summary
Like 
proc `[]`[T](s: var openArray[T]; i: BackwardsIndex): var T {...}
proc `[]`[Idx, T](a: var array[Idx, T]; i: BackwardsIndex): var T {...}

can 
proc `[]`(s: string; i: BackwardsIndex): char {...} return var char?

### Description
I was trying to get this to work doing exercisim.io

```
func reverse*(a: string):string =
  result = a
  for i in 0 ..< a.len div 2:
    #swap(result[i], result[^(i+1)]) # result[BackwardsIndex(i+1)] is immutable, not var!
    swap(result[i], result[a.high - i]) # had to do this
```

### PR DESCRIPTION
**Pull request by solo989**
Can now return T or var T depending on context.
Fixes #14497 
Ignore everything before merge branch 'devel'

### CODE REVIEW

**Comment by mratsim** [comment]
Template is not the solution, they would cause issue when used in other templates

**Review by mratsim — CHANGES_REQUESTED** [review]
Template is not the solution, they would cause issue when used in other templates

**Comment by Araq** [comment]
Templates cause the same multi evaluation bugs that the proc based solution avoids.

**Comment by solo989** [comment]
Reverted the changes and added a var overload.

**Comment by solo989** [comment]
Closing for now so I can delete my fork and start fresh.

**Comment by solo989** [comment]
New pull request based on my new fork. #14513

**Pull request closed without merging**
