### PR TITLE
pathnorm fix

### PR DESCRIPTION
**Pull request by krux02**
``normalizePath("")`` is now ``"/"``, it was ``""``.

This will make ``check("/a" /../ "d" == "/d")`` work without touching the implementation. 

## additional information

https://github.com/nim-lang/Nim/blob/d2b3046c7073bc3316127258212a5fb140de8f06/lib/pure/os.nim#L359

### CODE REVIEW

**Comment by Araq** [comment]
But why would it be "/"? Why not "."? I don't agree with this fix, it's better not to guess what the empty path means.

**Comment by krux02** [comment]
@Araq because the path componets of ``"/a"`` would then be [``""``, ``"a"``], where ``""`` indicates the root. Joining them will then lead to ``/a`` again. A very stable transformation.

And no it's not a guess what the empty path means. I referenced the ``isRootDir("")`` assertion that is already there.

**Comment by Araq** [comment]
But the path components could also be ``["/", "a"]`` which would make everything clearer.

**Comment by krux02** [comment]
Well this is a breaking change. It even breaks bootstrapping.

On my system in this line:
https://github.com/nim-lang/Nim/blob/83f5839e2c1fa0c3c2c579c63eb52351a757d9cc/compiler/extccomp.nim#L573

``conf.ccompilerpath`` is ``""``, and ``exe`` is ``"clang++"``, creating the absolute path ``"/clang++"``, which is of course wrong. One could argue that this is wrong logic to begin with, but that doesn't change the fact that this change might break much more code that is based on this old behavior.

**Comment by krux02** [comment]
Well there is ``readlink -m`` on the terminal to normalize paths. It doesn't change ``""``  to ``"/"`` either. So I think this PR should not be merged in it's current state. But don't close, I will think about a different solution.

**Comment by Araq** [comment]
> But don't close, I will think about a different solution.

The PR queue is not your personal Todo list and I don't think it needs a "solution" anyway. Don't guess what an empty string means.

**Pull request closed without merging**
