### PR TITLE
Add documentation into the manual for `unsafeAddr`

### PR DESCRIPTION
**Pull request by define-private-public**
This operator is vital if you need to do data & memory manipulation.  I've had to use it quite a few times when interfacing with C libraries.  It isn't documented right now but it should be.

### CODE REVIEW

**Comment by cheatfate** [comment]
You example you have provided you are using `unsafeAddr`, but you can use in this situation simple `addr`.
So example doesn't show any use-cases of `unsafeAddr`, where `addr` is not working.
Also documentation text is too shallow and needs more improvements, even system.nim documentation is better describing where `unsafeAddr` can be used.
```
  ## Builtin 'addr' operator for taking the address of a memory location.
  ## This works even for ``let`` variables or parameters for better interop
  ## with C and so it is considered even more unsafe than the ordinary ``addr``.
  ## Cannot be overloaded.
```

**Comment by krux02** [comment]
I just wanted to mention that I did something similar here https://github.com/nim-lang/Nim/pull/5362 completely independent of this pull request. So yes the documentation of `unsafeAddr` needs improvement.

**Comment by krux02** [comment]
I think you should add an example, where you need to pass the address of a parameter to a C fuction, but you do not want to use a var parameter, because the parameter will not be modified.

**Comment by Araq** [comment]
Reopen when you fixed it. As it is now the description of ``unsafeAddr`` is more wrong than helpful.

**Pull request closed without merging**
