### PR TITLE
JS codegen, for loops use `let` instead of `var` so `i` is not a global mutable variable

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Change codegen "hardcoded" `for` loops to use `let i` instead of `var i` so `i` is not a global mutable variable in JavaScript targets.
- No name collision on FFI if the wrapped code uses `i`.
- This is also to prepare the jsgen to generate typed vanilla JavaScript.

### CODE REVIEW

**Comment by metagn** [comment]
Is this worth breaking ES5 at syntax level?

**Comment by juancarlospaco** [comment]
https://caniuse.com/let

**Comment by metagn** [comment]
You can polyfill things that aren't part of the syntax. With this you have to subtitute each `let` in the output JS, which you can't reliably do without a full JS analyzer, so you need to use something like Babel every time you compile JS.

5% of users is not a small number, and browsers also aren't the only use of JS.

Can you argue why the benefit could outweigh the damage in this situation?

**Comment by juancarlospaco** [comment]
This is part of a long-term effort to generated typed vanilla javascript,
I want to add this first to see if people complains etc.

Also currently it produces global mutable unmangled symbols.

But if you have better ideas on how to evolve the jsgen, let me know.

**Comment by Araq** [comment]
There is a gross misunderstanding here that JS developers would use Nim if only the produced JS would look like it adheres to all the JS style fads. 

What would help much more is a blog post: 

> JS developers are underpaid because they don't understand software development, so let's help them: What is a compiler, why the word 'transpiler' makes no sense and why optimizing for every single byte of JS output seems rather misguided when 35% of all internet downloads are related to pornography.

**Comment by jmgomez** [comment]
Something that would probably help is a typescript definition parser. Something like this: https://github.com/fable-compiler/ts2fable but at Nim's compile time.

**Comment by juancarlospaco** [comment]
@jmgomez How a typescript static parser helps to improve the jsgen?. 🤔

I think we can use `let` were possible (not `const`), 
and maybe reduce the mangling were possible (because every symbol is no longer global mutable state),
and then generate typed vanilla javascript.

Another idea can be explore wasm wat codegen. Ideas welcome.

**Comment by jmgomez** [comment]
@juancarlospaco it doesnt, I was referring to what Araq said about adoption. 
IMO to have a nicer output js is great, but the only two things that are holding people from adopting Nim are tooling + ecosystem. A lib/macro like the one I mentioned would address the later at least for the js backend (it may even help with C/C++ too but that's another story)

**Comment by juancarlospaco** [comment]
@jmgomez You improved the C++ target a lot and that allows projects like NimForUE etc,
C target is also perfected and allows for a lot of projects and ecosystem to grow on top, 
the JS targets gets in the dust, but is also the most used scripting lang, has a decent standard assembly too.

**Comment by arnetheduck** [comment]
fwiw, `nlvm` has a wasm backend that natively generates wasm bytecode - to turn that into a js backend replacement, one would need to add "glue" support so that existing js code can call into the wasm-compiled functions (similar to exporting nim code to c) and stdlib support (ie wasi - emscripten solves this via emulation which is nice but also not nice) which can be developed as a library.

**Comment by Araq** [comment]
> the JS targets gets in the dust, but is also the most used scripting lang, has a decent standard assembly too.

It is underdeveloped but producing JS code that 5% of users cannot run will not help us. If you want to help, I can guide you. Ask on discord please.

**Pull request closed without merging**
