### PR TITLE
Add unicode procs

### PR DESCRIPTION
**Pull request by jyapayne**
This adds unicode procs that are useful for string manipulation.

### CODE REVIEW

**Comment by Araq** [comment]
Needs a transition period at least. Also the old procs in strutils should be named ``toLowerAscii`` and ``toUpperAscii`` perhaps? Or maybe the new ones in unicode should be ``toLowerUnicode``? Or maybe ``A`` vs ``U`` suffixes? This needs some serious thoughts.

**Comment by Araq** [comment]
Also when adapting the stdlib it's less disruptive to use ``import unicode except toLower``. ;-)

**Comment by jyapayne** [comment]
> Needs a transition period at least. Also the old procs in strutils should be named toLowerAscii and toUpperAscii perhaps? Or maybe the new ones in unicode should be toLowerUnicode? Or maybe A vs U suffixes? This needs some serious thoughts.

I agree that it would be good to have some sort of naming convention for similar procs from both `strutils` and `unicode`. Any of what you suggested would be fine I think. `toLowerUnicode` makes it very clear what is happening, but it's very long to type. The `U` suffix is obviously much shorter, but sacrifices clarity.

Would it be okay to have the procs have the `Unicode` suffix and then have an exported template that has the shorter `U` suffix? That way we could get the best of both worlds and no transition period is needed.

> Also when adapting the stdlib it's less disruptive to use import unicode except toLower. ;-)

Alright, I will do that for this PR and in the future :)

**Comment by Varriount** [comment]
I'm not sure having two names tied to one procedure is a good idea, especially if both strutils and unicode are imported in one module.

I'm in favor of just making the toLower and toUpper procedure Unicode-aware, and giving the old versions 'Ascii' prefixes.

**Comment by Araq** [comment]
> I'm in favor of just making the toLower and toUpper procedure Unicode-aware, and giving the old versions 'Ascii' prefixes.

I think I agree. We claim Nim's strings are UTF-8, so toUpper should deal with UTF-8.

**Comment by jyapayne** [comment]
Alright. I'm fine with either, so having the unicode be the default is good :) I'll update this PR when I have time with the appropriate changes, including deprecation paths for the old string procs, and updating the news.

**Comment by jyapayne** [comment]
@Araq, for deprecation paths, I'm trying to do the following:

```nim
{.deprecated: [capitalize: capitalizeAscii, toUpper: toUpperAscii,
  toLower: toLowerAscii, isUpper: isUpperAscii, isLower: isLowerAscii,
  isAlpha: isAlphaAscii
].}
```

However, I'm getting compile "redefinition" errors due to `toUpper`, `toLower`, etc. having a definition using `char` as an argument. There are two questions I have about this.

1. Should I rename the procs that take in a `char` with the `Ascii` suffix as well? Does it make sense to?
2. Is there a way to select argument types in order to narrow down procs with the `deprecated` pragma?

**Comment by Varriount** [comment]
Wait, hadn't we agreed to make toUpper, toLower, etc. Unicode/utf-8 aware, and simply add ascii equivalents? This way there is no actual deprecation, just "enhancement".

**Comment by jyapayne** [comment]
@Varriount I'm confused now :) I thought that's what I was doing? Since these procs are in `strutils.nim` I have to rename them to `toLowerAscii`, etc. and provide a deprecation path, no? The procs in `unicode.nim` will remain unicode aware and retain the names without any suffix.

**Comment by Varriount** [comment]
Oh. I thought we were making the ones in strutils.nim Unicode-aware by exporting the procedures from the Unicode module.

**Comment by jyapayne** [comment]
Ah :) That is also a possibility. I just assumed @Araq would want the unicode procs to stay inside the `unicode.nim` module without importing them into `strutils.nim`.

**Comment by Araq** [comment]
> Ah :) That is also a possibility. I just assumed @Araq would want the unicode procs to stay inside the unicode.nim module without importing them into strutils.nim.

You assumed correctly. ``strutils`` should be encoding agnostic (yes I know we need to move ``wordWrap`` etc.)

**Comment by Varriount** [comment]
Ascii is an encoding though... Yet these will be left in strutils?

**Comment by Araq** [comment]
> Should I rename the procs that take in a char with the Ascii suffix as well? Does it make sense to?

Yes.

> Is there a way to select argument types in order to narrow down procs with the deprecated pragma?

The deprecated pragma doesn't really work with procs, it was designed for types. We can either improve the compiler since it's a requested feature or use the other manually intensive .deprecated pragma for procs.

**Comment by Araq** [comment]
> Ascii is an encoding though... Yet these will be left in strutils?

Yes.

**Comment by jyapayne** [comment]
@Araq, continuing on with the deprecation process, since `toLower`, etc. have char equivalents, there is another problem.

When using the deprecation pragma above that was designed for types, I guess it doesn't handle overloaded procs that well. I get compilation errors when trying to compile old code that has `toLower` for strings, but not for code that has `toLower` for chars. Which means the pragma is only choosing the `toLower` for chars.

So this leaves me with trying to deprecate using the `{.deprecation.}` format for procs. What format would you suggest for this? Since I renamed the `strutils` procs, should I recreate the old procs that forward to these new `Ascii` suffixed procs and mark them with `{.deprecated.}`? Or is there a smarter method?

**Comment by Araq** [comment]
> Since I renamed the strutils procs, should I recreate the old procs that forward to these new Ascii suffixed procs and mark them with {.deprecated.}? Or is there a smarter method?

Not unless you want to wait on a compiler patch for the .deprecated statement. (Looks rather hard to fix internally, though.)

**Comment by jyapayne** [comment]
Alright. I'll create some forwarding procs with the {.deprecated.} pragma when I get the time :)

**Comment by jyapayne** [comment]
All done. I've created the deprecated forwarding procs :)

**Comment by jyapayne** [comment]
I still need to update the news with the changes. I have some free time tomorrow, so I'll do it then.

**Comment by Araq** [comment]
Leads to: 


lib/pure/strutils.nim(163, 13) Error: attempting to call undeclared routine: 'isSpace'

**Comment by jyapayne** [comment]
Oops! That error came from rebasing and me failing to check if the changes broke anything. I've fixed it now :)

**Comment by Araq** [comment]
``title`` needs to be renamed to ``toTitle`` in some other PR.

**Pull request merged**
