### PR TITLE
Allow full commands and blocks in type sections

### PR DESCRIPTION
**Pull request by metagn**
Previously only the following syntax compiled:

```nim
type A = call(x, y, z...)
type B = call x # single argument
```

Now the following compiles:

```nim
type
  Foo = call x, y, z:
    abc
  do:
    def
```

### CODE REVIEW

**Comment by Araq** [comment]
This needs a corresponding grammar update. You do that by editing the `#|` comments inside parser.nim and then run `nim c -r compiler/parser.nim`.

**Comment by c-blake** [comment]
Looks like `type A = call(x=yadda, y=howza, ..)` also already works, but maybe that's not sufficiently distinct to count.  Seems convenient for macro generated type sections.

If you are in the mood to hack on the parser, this is another case where ["named do"](https://forum.nim-lang.org/t/8110#53255) might help make block-call sites more self-documenting and re-orderable. :-) { idea being `w.do:` or `do(w):` for some hypothetical 4th param `w` in your `def` example }.  Surely another PR, though.

**Comment by metagn** [comment]
@c-blake For most cases `of` is enough for labelling. `do (w):` is also valid syntax, you can handle it if you are using a macro. `do block label:` is an unambiguous option but pretty ugly

**Comment by c-blake** [comment]
Well, personally I like the dotcall syntax best as in `w.do:`.  (EDIT: oh, and having to use a macro every time just to "round out" named parameter style seems a smidge onerous.)

**Comment by juancarlospaco** [comment]
Does it allows pragmas ?.

**Comment by metagn** [comment]
> Does it allows pragmas ?.

Do you mean the syntax in this PR? I don't see why they wouldn't, where are you expecting the pragmas to be?

**Comment by metagn** [comment]
> This needs a corresponding grammar update. You do that by editing the `#|` comments inside parser.nim and then run `nim c -r compiler/parser.nim`.

@Araq Is the grammar update sufficient?

**Comment by metagn** [comment]
Review?

**Comment by Araq** [comment]
You need to add a couple of tests showing that invalid indentation and precedence problems are still detected properly.

**Comment by metagn** [comment]
Added some tests, can't think of more

**Pull request merged**
