### PR TITLE
Add missing braces

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Add missing whitespaces, semicolons and braces. Continuation of https://github.com/nim-lang/Nim/pull/19948
- JavaScript allows to omit some braces, but it is best practice to use all proper explicit braces.

### CODE REVIEW

**Comment by Araq** [comment]
Enough of this, I don't care about best practices for generated JS code. It's just an invitation to the losers out there who don't understand how compilers work and think they can judge generated JS code by the same principles they judge other JS code.

**Comment by juancarlospaco** [comment]
> I don't care about best practices

@Araq
I understand but would not be better to generate correct proper code anyway?. 😐

I think it is a way to keep evolving the JS backend,
maybe you do not work with the JS day to day, but some people do,
also if you ever need to debug it, is better to read stuff thats readable...

**Comment by Araq** [comment]
The code was "proper" before too. And it's readable too or at least these additions do not help the readability.

**Comment by ringabout** [comment]
readable doesn't matter too much. I always use formatter to pretty the generated code.

**Comment by juancarlospaco** [comment]
> readable doesn't matter too much.

@xflywind
Readable does matter for a lot of people,
and theres no benefit on emitting badly formatted code,
even the performance is the same, because the current codegen emits too many unneeded empty lines and unneeded excessive indentations.

**Comment by AmjadHD** [comment]
> readable doesn't matter too much. I always use formatter to pretty the generated code.

A line in dochack.js:
before formatting:
```
            if (!(nxt_469762432 < x_469762421.childNodes.length)) Temporary8 = false; else {              Temporary8 = (x_469762421.childNodes[i_469762431].nodeName == "LI");            }            if (!Temporary8) Temporary7 = false; else {              Temporary7 = (x_469762421.childNodes[i_469762431].childNodes.length == 1);            }            if (!Temporary7) Temporary6 = false; else {              Temporary6 = (x_469762421.childNodes[nxt_469762432].nodeName == "UL");            }          if (Temporary6) {
```
after formatting:
```
				if (!(nxt_469762432 < x_469762421.childNodes.length)) Temporary8 = false; else { Temporary8 = (x_469762421.childNodes[i_469762431].nodeName == "LI"); } if (!Temporary8) Temporary7 = false; else { Temporary7 = (x_469762421.childNodes[i_469762431].childNodes.length == 1); } if (!Temporary7) Temporary6 = false; else { Temporary6 = (x_469762421.childNodes[nxt_469762432].nodeName == "UL"); } if (Temporary6) {
```
Why not accept this simple diff ?
If readable isn't important it would be better than this state ,of indentations without newlines, to not emit whitespace at all.

**Pull request closed without merging**
