### PR TITLE
Markdown code blocks migration part 7

### PR DESCRIPTION
**Pull request by a-mr**

### CODE REVIEW

**Comment by ringabout** [comment]
@a-mr Hello, thanks for your hard work. While we are at it, would you possibly turn https://github.com/nim-lang/Nim/blob/devel/lib/system_overview.rst into Markdown?

Btw, does Markdown code blocks need indentation? Or it is just a taste of style?

**Review by ringabout — APPROVED** [review]
Nice!

**Comment by a-mr** [comment]
yes, I will do it for `system_overview.rst`.

Yes, indentation is more of a style preference.

Markdown code blocks don't need indentation, so indentation can be any in range 0..3. When it's >= 4, it's considered indented code block as whole including ```` ``` ```` which is not what we want.

Initially (when I just started the migration) I preserved 2 additional spaced of indentation to **minimize** the changes in git diff when `code-block::` had 2 spaces of indentation after it.
* Then it seemed like a good-looking style to me
* and I thought that it would be good to have a uniform style. For example, for RST people asked what is "canonical" indentation for "code-block"s. I thought it's good to have it consistent through the whole project. So even when `code-block::` had 3 or 1 spaces of indentation I changed it to 2 spaces
* and if `code-block::` had 4 spaces or more then it was necessary decrease indentation. And again it seemed logical to set it to 2 spaces.

There is no really other deep thought about it.
So if you think that it's a bad idea just tell me here :-)

**Comment by ringabout** [comment]
No, either way is fine with me. I was asking out of curiosity.

**Pull request merged**
