### PR TITLE
fix #6416

### LINKED ISSUE #6416: asynchttpserver crashes on out of bounds http version
```nim
import asynchttpserver, asyncdispatch

var server = newAsyncHttpServer()
proc cb(req: Request) {.async.} =
  await req.respond(Http200, "Hello World")

waitFor server.serve(Port(8080), cb)
```

`echo "GET / HTTP/340282366920938463463374607431768211455.1" | ncat 127.0.0.1 8080`

```
Traceback (most recent call last)
t.nim(7)                 t
asyncdispatch.nim(1010)  waitFor
asyncdispatch.nim(1045)  poll
asyncdispatch.nim(179)   processPendingCallbacks
asyncmacro.nim(34)       cb0
asynchttpserver.nim(189) processClientIter
asynchttpserver.nim(125) parseProtocol
parseutils.nim(246)      parseInt
parseutils.nim(237)      parseBiggestInt
parseutils.nim(222)      rawParseInt
system.nim(2725)         sysFatal
[[reraised from:
t.nim(7)                 t
asyncdispatch.nim(1010)  waitFor
asyncdispatch.nim(1045)  poll
asyncdispatch.nim(179)   processPendingCallbacks
asyncfutures.nim(288)    :anonymous
]]
Error: unhandled exception: over- or underflow
  processClient's lead up to read of failed Future:
    Traceback (most recent call last)
    t.nim(7)                 t
    asyncdispatch.nim(1010)  waitFor
    asyncdispatch.nim(1045)  poll
    asyncdispatch.nim(179)   processPendingCallbacks
    asyncmacro.nim(34)       cb0
    asynchttpserver.nim(189) processClientIter
    asynchttpserver.nim(125) parseProtocol
    parseutils.nim(246)      parseInt
    parseutils.nim(237)      parseBiggestInt
    parseutils.nim(222)      rawParseInt
    system.nim(2725)         sysFatal [OverflowError]
```

### PR DESCRIPTION
**Pull request by enthus1ast**
fix #6416

### CODE REVIEW

**Comment by dom96** [comment]
This looks like a good PR but it makes me curious about what happens when overflow checks are disabled, can you test that?

**Comment by pyloor** [comment]
why not be more restrict and do it like apache: https://github.com/apache/httpd/blob/e837836f91b0c1ee1f39076edc1ef957d5c32726/server/protocol.c#L753

the len of the HTTP Version string may not be bigger as 8 chars.

**Comment by Araq** [comment]
This won't work reliably when overflow checks are turned off (and for release they are turned off).

**Comment by enthus1ast** [comment]
what would be a proper way to check this then?

**Comment by Araq** [comment]
As pyloor said, make it "the len of the HTTP Version string may not be bigger as 8 chars."

**Comment by Araq** [comment]
This has been fixed differently.

**Pull request closed without merging**
