### PR TITLE
Easier build instructions for windows - just run `build_all.bat`.

### PR DESCRIPTION
**Pull request by treeform**
Create `build_all.bat` and make the build instructions same as for `build_all.sh`.

### CODE REVIEW

**Comment by Araq** [comment]
``build_all.sh`` was already a bad idea. If you want to build from source, learn how the system is setup or write your own script.

**Comment by treeform** [comment]
I find it odd that you have a sh to build on posix, but for windows its commands...

**Comment by Araq** [comment]
So make it least consistent with the shell script, it doesn't do this:

```
rmdir csources /S /Q
git clone --depth 1 https://github.com/nim-lang/csources.git
```

for example.

**Comment by treeform** [comment]
That's a great point will fix, with a better PR soon.

**Comment by treeform** [comment]
I have updated the build_all.bat to match the behavior in build_all.sh.

**Pull request merged**
