### PR TITLE
Get OS version

### PR DESCRIPTION
**Pull request by EchoPouet**
Hello,

With Nim we can get the OS/distribution but not the version. I had a function to get it for BSD, Linux (not all), Windows and Mac.

Thanks.

### CODE REVIEW

**Comment by dom96** [comment]
We have an osinfo package which covers this already, I think it would be best to extend it: https://github.com/nim-lang/osinfo

**Comment by EchoPouet** [comment]
I didn't know this package, there is also [sysinfo](https://github.com/treeform/sysinfo).

I agree that we shouldn't add too many functions already propose in a package like yours but for me the OS name only is incomplete. An important information is missing.

If Nim stdlib allows to get the OS, it should allow to get the version.

**Comment by juancarlospaco** [comment]
Some of those proc are not going to work on some popular Linux, eg Alpine, 
maybe wrap it in a `try: ... except: ...` :thinking:

**Comment by dom96** [comment]
> If Nim stdlib allows to get the OS, it should allow to get the version.

I disagree, there is very specific purpose for this module and it's to detect distros to enable better messages for Nimble. Getting version information is not necessary for that use case. The only reason this is in the stdlib seems to be to give Nimble's nimscript eval the ability to use it.

**Comment by timotheecour** [comment]
getting OS version should indeed be in stdlib, eg use case: when a externc proc / program / bugfix / feature was made available after a certain version.

**Comment by dom96** [comment]
Then you check the OS version using the low-level primitives. You don't shell out to `uname`...

**Comment by timotheecour** [comment]
> Then you check the OS version using the low-level primitives. You don't shell out to uname...

that can be an enhancement in subsequent work, and can be done 1 os at a time, transparently for user code.
Having it available here in the meantime (whether via uname or low-level primitives) means users don't need to re-invent the wheel when OS version is needed.

**Comment by Araq** [comment]
It's unclear what the "OS version" is, the kernel version? The distro version? It's unclear why we need it. Sorry, rejected, you can create a Nimble package for this instead. ``distros.nim`` is only for Nimble and it was a mistake to ever add it, it's fragile and untestable.

**Comment by EchoPouet** [comment]
No problem, I'll use a package for this feature.

**Comment by EchoPouet** [comment]
It's my last post for this PR.

If `distros.nim` is a problem and use only for Nimble it'll be good to get it out of the stdlib.
That way no one will want to use it, fix it or make it better. Only Nimble contributor :)

**Comment by Araq** [comment]
Well you can use it but since it needs to be tested manually on a plethora of OSes, getting changes accepted is hard. And feature additions are harder still. I think that's acceptable.

**Pull request closed without merging**
