### PR TITLE
New freebsd platforms

### PR DESCRIPTION
**Pull request by lbartoletti**
This PR proposes to add all platforms supported by FreeBSD. 

image

cc @euantorano

### CODE REVIEW

**Comment by euantorano** [comment]
Unfortunately I only have access to an AMD64 based FreeBSD system at the moment, [as does builds.sr.ht](https://man.sr.ht/builds.sr.ht/compatibility.md#freebsd). This doesn't look like it'd cause any problems though as far as I can tell.

**Comment by euantorano** [comment]
PS: note that the FreeBSD build failure is unrelated to this PR - sr.ht seems to have messed up due to a race condition that they're aware of. Pushing an empty commit should re-trigger it.

**Comment by timotheecour** [comment]
Pushing an empty commit restarts all CI, instead you should only restart the CI that needs to be restarted

**Comment by euantorano** [comment]
The only person who can do that is Araq as far as I know, and I prefer not to annoy him if possible.

**Comment by timotheecour** [comment]
Just create a sourcehut account and you can

**Comment by euantorano** [comment]
Yes, but then it gets re-submitted under my name instead: https://builds.sr.ht/~euantorano/job/241766

Thinking about it, I'm not sure if re-submitting even re-triggers the GitHub webhook to update the status.

**Comment by timotheecour** [comment]
as you can see, it still works (it's now green for builds.sr.ht), but until it finishes, the badge isn't updated; I've reported it here: https://todo.sr.ht/~sircmpwn/builds.sr.ht/271 feel free to upvode

**Comment by euantorano** [comment]
Ah, awesome. I didn’t think that would work since it would be under my name instead but it’s good to know it does.

**Comment by timotheecour** [comment]
We need to add a section under contributing on how to restart CI in a resource effective way, it differs for azure vs github vs buildshrt

**Comment by lbartoletti** [comment]
> Unfortunately I only have access to an AMD64 based FreeBSD system at the moment

No worries, I tested FreeBSD / RiscV with Qemu. PPC works already, Mips should work too. Like my previous PR for arm, with this PR our Nim package will be compiled on supported platforms (if it doesn't work in our package infrastructure, I can fix it ;) )

**Pull request merged**
