### PR TITLE
better $uint64

### PR DESCRIPTION
**Pull request by ringabout**
It doesn't seem to speed up uint64 ...
```nim
const digitsTable* = "0001020304050607080910111213141516171819" &
    "2021222324252627282930313233343536373839" &
    "4041424344454647484950515253545556575859" &
    "6061626364656667686970717273747576777879" &
    "8081828384858687888990919293949596979899"

func digits10*(num: uint64): int {.noinline.} =
  if num < 10:
    result = 1
  elif num < 100:
    result = 2
  elif num < 1_000:
    result = 3
  elif num < 10_000:
    result = 4
  elif num < 100_000:
    result = 5
  elif num < 1_000_000:
    result = 6
  elif num < 10_000_000:
    result = 7
  elif num < 100_000_000:
    result = 8
  elif num < 1_000_000_000:
    result = 9
  elif num < 10_000_000_000'u64:
    result = 10
  elif num < 100_000_000_000'u64:
    result = 11
  elif num < 1_000_000_000_000'u64:
    result = 12
  else:
    result = 12 + digits10(num div 1_000_000_000_000'u64)

template numToString*(result: var string, origin: uint64, length: int) =
  var num = origin
  var next = length - 1
  while num >= 100:
    let originNum = num
    num = num div 100
    let index = (originNum - num * 100) shl 1
    result[next] = digitsTable[index + 1]
    result[next - 1] = digitsTable[index]
    dec(next, 2)

  # process last 1-2 digits
  if num < 10:
    result[next] = chr(ord('0') + num)
  else:
    let index = num * 2
    result[next] = digitsTable[index + 1]
    result[next - 1] = digitsTable[index]

proc toString*(x: uint64): string {.noSideEffect, raises: [].} =
  ## The stringify operator for an unsigned integer argument. Returns `x`
  ## converted to a decimal string.
  if x == 0:
    return "0"
  elif x == 1:
    return "1"

  let length = digits10(x)
  setLen(result, length)

  numToString(result, x, length)


import std/monotimes

template benchmark(name, fn): untyped =
  proc name() =
    block:
      let past1 = getMonoTime()
      for i in 1000 .. 8000:
        discard fn(uint64(i))
      let last1 = getMonoTime() - past1
      echo astToStr(fn) & ": " & $last1


benchmark(hello1, `$`)
benchmark(hello2, tostring)

for i in 0 ..< 10:
  hello2()
  hello1()
```

### CODE REVIEW

**Comment by ringabout** [comment]
Include seems to cause some problems in `nimhcr`. I don't know why.

**Comment by timotheecour** [comment]
instead, can you add `addInt(result: var string, b: uint64)` overload? most of implementation would reuse code from #16160

**Comment by juancarlospaco** [comment]
Have you tried moving the `const` inside the body of the `func`, `{.noinit.}` on the `func`, convert the `if` to `case` of ranges ?.

**Comment by timotheecour** [comment]
> convert the if to case of ranges ?

i don't think that would help (in cgen it'd be `if` anyways) but binary search might be worth trying, see:
* https://stackoverflow.com/a/13080148/1426932

or an improved version:
* https://stackoverflow.com/a/20259224/1426932
> A quick benchmark clearly showed the binary search methods winning. lakshmanaraj's code is quite good, Alexander Korobka's is ~30% faster, Deadcode's is a tiny bit faster still (~10%), but I found the following tricks from the above link give a further 10% improvement.

(would need to be benchmarked)

Note that this can be done in a different PR

**Pull request closed without merging**
