### PR TITLE
added uri to Response/AsyncResponse, which holds the last redirect url.

### PR DESCRIPTION
**Pull request by enthus1ast**
Signed-off-by: David Krause <krause@biochem2.uni-frankfurt.de>

### CODE REVIEW

**Review by dom96 — CHANGES_REQUESTED** [review]
What's the rationale? You're giving the url as an input, just pass it around in your code instead of adding this data into the `Response` object.

**Comment by enthus1ast** [comment]
Currently it's not possible to get the url from where a content was served after redirecting.
This pr adds this url to the response.

After this pr this is possible:

```nim
echo $(client.head("http://google.de/").uri)
```
Edit:
So the uri in the response is the uri where the content came from. And it's more logical to have this value in the response then in the HttpClient object 
So in the Google example this will be eg. "http://www.google.com" since google redirected. Another option to enable this would be to export `currentURI`.

**Comment by ringabout** [comment]
See also https://github.com/nim-lang/Nim/issues/16685

https://github.com/nim-lang/Nim/pull/16691

**Comment by ringabout** [comment]
@enthus1ast feel free to take over #16691 and make that feature opt-in.

**Comment by ringabout** [comment]
It is requested again https://forum.nim-lang.org/t/8778

**Pull request closed without merging**
