### PR TITLE
nils are JNulls in json parsing and serializing

### LINKED ISSUE #11894: Converting Object with a JsonNode to JSON compiles but crashes.
```nim
import json

type
  Foo = ref object
    name: string
    params: JsonNode

var foo = Foo()
echo pretty %foo
```

### nim c
```
Traceback (most recent call last)
/p/andrelytics/tmp/bug2.nim(10) bug2
/Users/andre.vonhouck/.choosenim/toolchains/nim-#devel/lib/pure/json.nim(716) pretty
/Users/andre.vonhouck/.choosenim/toolchains/nim-#devel/lib/pure/json.nim(655) toPretty
/Users/andre.vonhouck/.choosenim/toolchains/nim-#devel/lib/pure/json.nim(639) toPretty
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### nim js
```
/p/andrelytics/tmp/bug2.js:994
                switch (node_237621.kind) {
                                   ^

TypeError: Cannot read property 'kind' of null
    at to_pretty_237617 (/p/andrelytics/tmp/bug2.js:994:22)
    at to_pretty_237617 (/p/andrelytics/tmp/bug2.js:1053:8)
    at pretty_238040 (/p/andrelytics/tmp/bug2.js:1214:3)
    at Object.<anonymous> (/p/andrelytics/tmp/bug2.js:1724:9)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
Error: execution of an external program failed: '/usr/local/Cellar/node/8.0.0_1/bin/node /p/andrelytics/tmp/bug2.js '
```

I expected to either:
* Complain during compilation that converting JsonNode to JSON is not possible.
Or:
* Just convert it to regular JSON.

```
Nim Compiler Version 0.20.99 [MacOSX: amd64]
Compiled at 2019-07-17
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by disruptek**
fixes #11894

### CODE REVIEW

**Comment by krux02** [comment]
I am sorry, I don't like it. This is not a stable transformation. Serialization and deserialization should always return the exact same value. `nil` and an object of JNull is not the exact same value.

**Comment by krux02** [comment]
I just read your comment in the issue. Aparently this is desired behavior. Yea ...

**Comment by disruptek** [comment]
I understand your criticism, but how does that square with this current behavior?

```nim
import json

type
  Foo = ref object
var bar: Foo
let j = %bar
echo j # null
bar = j.to(Foo)
echo bar.repr # nil
```
So we only convert nil ref values to null when... what, exactly?

BTW, if you do decide you want to change any of this, it probably needs a changelog entry.

**Comment by krux02** [comment]
Well, you said `nil` and `JNull` are semantically the same. Since we can't get rid of `nil`, maybe the better solution would be to get rid of `JNull` then. But that isn't criticism of this PR though.

**Comment by disruptek** [comment]
Right, and we could maybe remove more of JNull for consistency, but I think it will take a larger amount of code and create a commensurately larger amount of breakage.  Want me to try that route?

**Comment by krux02** [comment]
After thinking much about it, I think the cleanest solution would be to raise a proper error message when the input on `%` is a nil `JsonNode`. nil-JsonNodes are incorrect input for most JsonNodes, when `%` would complain as well, it would just be more consistent.

**Comment by disruptek** [comment]
Closing as per #11894

**Pull request closed without merging**
