### PR TITLE
Add logical assignment operator

### PR DESCRIPTION
**Pull request by juancarlospaco**
- [&&=](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND_assignment)
- [||=](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment)
- [??=](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment)

### CODE REVIEW

**Comment by timotheecour** [comment]
the list of imported procs could grow potentially quite large, there's no reason it'd stop here. IMO it should be in its own module, because jsffi is commonly used already and existing clients may not want to have all those added operators in scope. Furthermore, jsffi is far from a pure-wrapper module, whereas the procs you're adding are pure wrappers.

we should bikeshed the name and scope (only operators?) of this new module.
candidates:
* `std/jsops`
* `std/jsbuiltinops`
* `std/jsoperators`
* `std/jsbuiltins`

note:
* we have std/jscore but that's (at least now) only symbols that are not operators
* it's still unclear to me whether the API based on `JsObject` is the right one (instead of `auto` or some generic param); in lots of cases this ends up being harder to use (but has benefit of being non-generic, more restrictive in scope); for eg std/jscore uses generic types (eg `SomeNumber`), not JsObject; I'm genuinely curious here.
* maybe: the existing pure wrappers from jsffi could potentially be imported and selectively re-exported from the new `std/jsops` eg:
```nim
proc `/=` *(x, y: JsObject): JsObject {.importcpp: "(# /= #)", discardable.}
```

**Comment by juancarlospaco** [comment]
I added it there because `**` was also recently added there, and has similar operators anyway.

I am in favor of splitting `jsffi`, but I dont know if that can be done without breaking peoples code,
and having half the operators in one module and half the operators in another is worse. :shrug:

**Comment by timotheecour** [comment]
> I am in favor of splitting jsffi, but I dont know if that can be done without breaking peoples code,

as i suggested above, we can import and re-export selectively, eg:
```nim
# jsffi
from std/jsops import nil
export jsops.`/=`, jsops.... # only re-export pre-existing ones (might even deprecate those re-exports in future but that's a separate issue)

# jsops
## pre-existing ones from jsffi
proc `/=` *(x, y: JsObject): JsObject {.importcpp: "(# /= #)", discardable.}

## new ones
func `&&=`*(lhs, rhs: JsObject): JsObject {.importjs: "(# &&= #)", discardable.}
... can grow in future
```

**Comment by Araq** [comment]
Too alien for Nim and these operators would produce `void` in Nim anyway. Nim is not JS.

**Pull request closed without merging**
