### PR TITLE
Atlas: clone with `--recursive`

### PR DESCRIPTION
**Pull request by Gruruya**

### CODE REVIEW

**Comment by Araq** [comment]
What does that do? What are the implications for the download performance?

**Comment by beef331** [comment]
If a package has submodules it'll clone them, which is what one generally would want.

**Comment by Gruruya** [comment]
To add-on, nimble also uses `--config core.autocrlf=false --config core.eol=lf` for hashes to match but I don't think that matters here.
https://github.com/nim-lang/nimble/blob/7484582e52b3201d3c0a510ed2feeb5d7a8c3491/src/nimblepkg/download.nim#L41

Performance should be unimpacted. Cloning submodules is necessary for some projects to work and without `--recursive` you would have to go through each repo and run `git submodule update --init --recursive`.

**Comment by Araq** [comment]
@Gruruya If you're good at github consider working on this please:

### The Atlas `tag [optional_explicit_version]` command

Tags a release. Use in a directory that is a git project. Maybe checks the git history in order to determine if it's a patch or a new feature. Uses the already used version format or if none it uses Nim's format. Pushes the tag.

**Comment by Gruruya** [comment]
sure, I'll take a look.

**Pull request merged**
