### PR TITLE
fix #7292 (better fix: git diff wont flag on staged uncommitted files)

### LINKED ISSUE #7292: ./koch xz doesn't check for dirty work tree
As I've painfully found out, the tool will happily take whatever uncomitted changes I have and put it in the release tar ball. Not good.

### PR DESCRIPTION
**Pull request by timotheecour**
* fixes #7292
/cc @araq @dom96 
git diff won't make the difference bw clean repo and repo with staged but uncommitted files

### CODE REVIEW

**Comment by Araq** [comment]
That's the point, I always have files unknown to git and don't want to teach ``.gitignore`` about every single one of them.

**Comment by dom96** [comment]
If we want to make this better I think we should also check ``git diff --staged`` just in case. But ``git diff`` should be good enough.

AFAIK ``koch`` has an explicit list of files it picks up so unstaged files are unlikely to be packaged. (Right?)

**Comment by Araq** [comment]
> AFAIK koch has an explicit list of files it picks up so unstaged files are unlikely to be packaged. (Right?)

Well ``koch xz`` does have that list, yes.

**Comment by Araq** [comment]
``git status --porcelain`` produces a long list of ``??`` entries for me, it doesn't work.

**Comment by timotheecour** [comment]
ok I'll let you close this PR then. But just to reiterate:
* if tools in Nim repo are producing files that make git status not clean (ie, `git status --porcelain` non-empty), they should be adjusted to put these inside a gitignore'd directory instead (eg `build/`) (or, less preferably, be added to .gitignore themselves)
* as it stands, `ensureCleanGit` doesn't match user's expectation of what this function does

**Comment by Araq** [comment]
Ok.

**Pull request closed without merging**
