### PR TITLE
[Windows] Use GetSystemInfo for obtaining processor count

### PR DESCRIPTION
**Pull request by data-man**
IMO, there is a serious vulnerability for all multithreaded Windows-apps compiled by Nim.
For example, the user can execute `set NUMBER_OF_PROCESSORS = 1000000.`

### CODE REVIEW

**Comment by data-man** [comment]
Note: tested on Win32 only.

**Comment by Araq** [comment]
Very good idea. Need to rerun appveyor and then it's good to go.

**Comment by data-man** [comment]
Why tests do not pass?

**Comment by TiberiumN** [comment]
@dandevelo All plans have maximum build job execution time of 60 minutes.

**Comment by data-man** [comment]
@TiberiumN
Have you answered me or dandevelo? :-)

> All plans have maximum build job execution time of 60 minutes. (on appveyor)

I just look at other PRs and there all the tests pass.

**Comment by TiberiumN** [comment]
@data-man appveyor is Windows, and windows is slower at compiling stuff.
So a lot of time there's a 60 minutes limit.
Examples:
https://github.com/nim-lang/Nim/pull/6015
https://github.com/nim-lang/Nim/pull/6012
https://github.com/nim-lang/Nim/pull/6006
https://github.com/nim-lang/Nim/pull/6003

**Comment by data-man** [comment]
@Araq

Is it ok?

**Comment by Araq** [comment]
i think this is wrong as it **always** cause appveyor to timeout.

**Comment by data-man** [comment]
Hmm, all ok on my PC (Windows 8.1 x32).
Maybe the problem is that the appveyor is using Windows x64?

**Comment by data-man** [comment]
Maybe it's worth upgrading GCC to version [7.1.0](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/7.1.0/threads-win32/seh/x86_64-7.1.0-release-win32-seh-rt_v5-rev0.7z/download) on appveyor.yml?
Perhaps this will speed up compiling & tests passing.

**Comment by data-man** [comment]
@Araq 
What about this PR?

**Pull request merged**
