### PR TITLE
discardable async procs are now an error

### LINKED ISSUE #11912: Add undiscardable pragma and forbid Futures from being discarded
### Summary
The docs say that we shouldn't discard futures, but Nim should really catch that on compile time if possible.

### Description
The easiest way should be by adding an {.undiscardable.} pragma for types, using it for Future and making nim generate a compile time error discarding such types on sem checking: I can open a PR, if this is accepted

### Alternatives
Just forbidding discarding Future, but not sure how this will work without somehow hardcoding that (the user might have different Future type)

### LINKED ISSUE #12912: Pragmas async+discardable should be a Syntax Error
Pragmas `{.async.}` and `{.multisync.}` combined with `{.discardable.}` 
should be a Syntax Error or at least a compile time Warning.

### Example
```nim
import asyncdispatch

proc foo(): Future[void] {.async, discardable.} = discard
proc bar(): Future[void] {.multisync, discardable.} = discard

```

Similar but not the same https://github.com/nim-lang/Nim/issues/11912#issue-478298948
recommends adding an  `{.undiscardable.}` pragma for `discard asyncProc()`, 
this bug is about the combination of `{.async, discardable.}` should be a Syntax Error.
I guess should not be too complicated to get a list of pragmas and if both found together thrown error.

### PR DESCRIPTION
**Pull request by metagn**
fixes #12912 

Also had discard as an error (#11912) but decided against it.

### CODE REVIEW

**Comment by metagn** [comment]
Test failures because of https://github.com/nim-lang/Nim/commit/3d2459bdc0b6d6236a2cd9209ed81c965ee411a5, unrelated

**Comment by metagn** [comment]
Still unrelated? Those GitHub CI errors are weird. Will try rebasing with devel

**Comment by Araq** [comment]
Tough decision, TR macros only exist for optimization purposes.

**Comment by metagn** [comment]
Well `asyncCheck` is some kind of optimization. We just force people to use it instead of automatically using it.

> optimization: an act, process, or methodology of making something (such as a design, system, or decision) as fully perfect, functional, or effective as possible

It's functional or effective if you check exceptions inside futures.

**Comment by disruptek** [comment]
So you had to remove the successful use of `discard` from the tests...  Was that not a hint that this is a reasonable use of `discard` against a `Future`?

**Comment by metagn** [comment]
Warning instead of error then? I don't really know what the test does, I just assumed since it's a test that it's not a real world example. If not you can still `let _ = `.

**Comment by disruptek** [comment]
I think a warning is fair but I think documentation improvements are the correct patch.  I'm sorry if my previous message came across as harsh; it was composed in haste! :pray:

**Comment by Araq** [comment]
I think  #11912 should be closed as "won't fix", ``discard x`` is a dangerous construct, you clearly throw away information, you clearly should know what you're doing. Comparable to Nim's ``cast``.

**Comment by metagn** [comment]
Custom warning here is a bit problematic since you can't suppress specific user errors without suppressing all user errors (the warning category User, you cant make your own warning category). You can opt out of this term rewriting macro altogether by doing `import asyncfutures except discardedFutureWarning` though. Maybe `-d:asyncSuppressDiscardedFutureWarning` too. This is too complicated though, I'll just remove it.

The problem here is people do `discard fut` without realizing it's wrong. ["Use asyncCheck"](https://nim-lang.org/docs/asyncdispatch.html#discarding-futures) could not be more clear in the docs, some people just don't read them or they learn through trial and error.

If `discard` is some kind of unsafe/unsound operation then we should start mentioning that in documentation. "Only use discard when you know what will happen next". Otherwise there is no clue to that at all.

**Comment by disruptek** [comment]
The point is that it isn't unsafe.  It's behavior by design, and to do otherwise is a slippery (not to mention inconsistent) slope; a "race to the bottom" as @Araq says.  :grin:

My personal opinion is that the emphasis on `asyncCheck` is misplaced and the source of confusion for newcomers to Nim's async, but you know what they say about opinions...

**Comment by dom96** [comment]
> So you had to remove the successful use of discard from the tests... Was that not a hint that this is a reasonable use of discard against a Future?

Funnily enough it is not a reasonable use of `discard`. You should never discard a future, it really is that simple. That test needs to be fixed because it leaks exceptions!

**Comment by disruptek** [comment]
If I want to leak exceptions, why should Nim deny me?  We don't forbid leaks like some other languages.  Where does it end?

**Comment by dom96** [comment]
> If I want to leak exceptions, why should Nim deny me? We don't forbid leaks like some other languages. Where does it end?

Then you can still do it, just not using `discard`. This is like saying "If I want to concatenate strings and integers, why should Nim deny me?".

**Comment by D-Nice** [comment]
> > So you had to remove the successful use of discard from the tests... Was that not a hint that this is a reasonable use of discard against a Future?
> 
> Funnily enough it is not a reasonable use of `discard`. You should never discard a future, it really is that simple. That test needs to be fixed because it leaks exceptions!

This really doesn't change that, I can still discard futures (on latest devel branch git hash: baa80ca9d4c5bef4b90aabf4a666b2300c62b5b7), this PR just seems to stop me from potentially identifying an async proc as being acceptable to discard, the behaviour you consider dangerous is still quite possible, so I am confused by this PR as it leaves the root of the apparent problem intact.

A warning would seem more appropriate if discard on futures are used, because there are still instances where I may run a bunch of async things, but don't care to know what happens with them or that they block other things from running. And from my experimentation, there are no memory leaks or the like for not catching these exceptions.

**Comment by metagn** [comment]
@D-Nice The old version of the PR used term rewriting macros to error on `discard fut` where `fut` is of type `Future[T]`. I changed it after someone suggested the current behavior. Term rewriting macros aren't meant for gatekeeping language features or library defined errors.

**Comment by D-Nice** [comment]
@hlaaftana I see, thanks for the context! So is this PR moreso to then require a verbose discard, over before being able to "hide" the discarding?

I am still wondering, what is so bad if you wantonly and knowingly ignore Future exceptions in Nim, especially if you don't want other async events affected by one raising exceptions. I understand it's against best practices in general, but there are cases where one wants this purposefully, for example creating something that stress tests a webserver, you may want it to keep hitting that webserver at the same speed even if requests start being excepted, rather than having to start to handle each exception, and lowering the load.

**Comment by dom96** [comment]
> I am still wondering, what is so bad if you wantonly and knowingly ignore Future exceptions in Nim, especially if you don't want other async events affected by one raising exceptions. I understand it's against best practices in general, but there are cases where one wants this purposefully, for example creating something that stress tests a webserver, you may want it to keep hitting that webserver at the same speed even if requests start being excepted, rather than having to start to handle each exception, and lowering the load.

The answer to your question is the same as the answer to "What's so bad about handling all exceptions and silently dropping them?"

Hopefully you know the answer. Sure, you may not care and still want to do it. But the problem with `discard`ing a future is that people aren't aware that this is what they are doing (discarding potential exceptions).

**Pull request merged**
