### PR TITLE
Avoid referencing undefined SSLv2_method on MacOSX

### PR DESCRIPTION
**Pull request by tmm1**
I'm using OSX 10.11 El Capitan and currently see an error when using `nim`@`devel` with ssl (for example with `nimble`):

```
$ ./nimble
could not import: SSLv2_method
```

OSX 10.11 does not ship with openssl, and I have openssl 1.0.2d installed via homebrew in /usr/local. I guess this version no longer ships with ssl2?

This PR avoids referencing the undefined symbol on OSX, similar to the way it was already being done for linux. I tried to use `defined(SSLv2_method)` but that didn't work.

cc https://github.com/nim-lang/nimble/issues/142

### CODE REVIEW

**Comment by tmm1** [comment]
Interestingly the deprecated sockets module does the same thing for OpenBSD: https://github.com/nim-lang/Nim/blob/devel/lib/pure/sockets.nim#L317

**Comment by tmm1** [comment]
Maybe it's simplest to remove the `of protSSLv2` case branch altogether, since it is not recommended that anyone use sslv2.

**Comment by dom96** [comment]
Yeah, let's just remove ``protSSLv2``.

**Comment by tmm1** [comment]
Updated the PR to always `raiseSslError()` for sslv2

**Pull request merged**
