### PR TITLE
testament: refactor and better parallel execution

### PR DESCRIPTION
**Pull request by arnetheduck**
Several changes:

* Test discovery and running is split into two phases
  * Full suite known before tests start
  * Print test progress report as tests are executing

* Parallel test execution using threads, channels
  * Parallelization within category
  * Capped at number of cpus, not number of categories

* Test matrix expansion
  * Spec is read then expanded into instances that are passed to test
runner
  * opens up for more test matrix features in specs (for example
options)
  * unique test id for each instance that can be used for filtering

* Move one directory up
  * less typing
  * it's not a test

* Simplified test filtering
  * each test has an id
  * `r` does substring filtering to potentially match multiple tests

### CODE REVIEW

**Comment by Araq** [comment]
> Parallel test execution using threads, channels

> Parallelization within category
> Capped at number of cpus, not number of categories

Meh, I don't think it's wise to do that unless there is some checking in place that ensures at least e.g. 3000 tests in total have been processed. And even then I don't want to do it. ``testament`` is crucial for ensuring the overall quality of Nim's implementation, it shouldn't touch multi-threading. Note that in the past even the simple change to use ``execProcesses`` to speed up the testing introduced regressions where failing tests started to not make testament fail.

**Comment by arnetheduck** [comment]
> > Parallel test execution using threads, channels
> 
> > Parallelization within category
> > Capped at number of cpus, not number of categories
> 
> Meh, I don't think it's wise to do that unless there is some checking in place that ensures at least e.g. 3000 tests in total have been processed. And even then I don't want to do it. `testament` is crucial for ensuring the overall quality of Nim's implementation, it shouldn't touch multi-threading. Note that in the past even the simple change to use `execProcesses` to speed up the testing introduced regressions where failing tests started to not make testament fail.

technically, the sane thing to do in that case would be to compile testament itself with the csources bootstrap compiler and a blessed std lib version (for example it could be dumped in csources, or submodule-linked) - that would isolate it from any "issues" in development versions of the compiler itself. if the tool is the centrepiece of ensuring nim quality, making it substandard and annoying seems counterproductive in the long run.

threads are just one small piece of what it stresses, looking at the implementation, it already covers almost all of nim anyway (including use of macros, iterators, gc etc etc, for example to get the json module to compile. that said, looks indeed like the threading story of nim needs love and attention - ie even the absolutely most trivial channel usage introduced looks like it breaks something: https://travis-ci.org/nim-lang/Nim/jobs/429291231 (it smells of threading at least, though I didn't investigate)

threading is not actually strictly needed here, it's just seemed the easiest way to deal with handling process i/o (stdin etc) in parallel - there doesn't seem to be any other convenient tool in nim for that kind of multiplexing.

parallel-by-category is problematic for several reasons:
* not parallel enough: categories are very uneven
* too parallel: too many processes launched causes trouble on resource-limited devices where it would be nice to have a nim compiler going forwards (yeah, could be solved with a category limit)
* hard to add useful features / options because they must all be passed on to next process on the command line (there's a couple I'd like to add, including some white/blacklisting and comparison runs)

all-in-all, the main point of this PR is to split up test discovery and running, so that there's a global view on all the tests that need to be run, and running them is outsourced to a separate part of the code that can do so based on policy (policy means threads-vs-processes, how many of them, etc etc) - this is what enables building many of the useful bells and whistles that would enable better maintenance of the test suite in the future (including more powerful specs).

I guess the `runner.nim` part of this PR could be changed to use processes instead of threads - should be fairly easy - would that be more palatable? would keep everything single-threaded and still enable all the good stuff.

**Comment by Araq** [comment]
> if the tool is the centrepiece of ensuring nim quality, making it substandard and annoying seems counterproductive in the long run.

It is the centrepeice of ensuring Nim's quality. "Substandard and annoying" is just an overly harsh way of saying "so simple that it can be trusted upon".

> too parallel: too many processes launched causes trouble on resource-limited devices where it would be nice to have a nim compiler going forwards (yeah, could be solved with a category limit)

That's not how ``execProcesses()`` works...

> hard to add useful features / options because they must all be passed on to next process on the command line (there's a couple I'd like to add, including some white/blacklisting and comparison runs)

Unclear why these features need to be command line arguments and/or how it's "hard" to pass them on to child processes.

> all-in-all, the main point of this PR is to split up test discovery and running, so that there's a global view on all the tests that need to be run, and running them is outsourced to a separate part 

Ok.

> of the code that can do so based on policy (policy means threads-vs-processes, how many of them, etc etc) - this is what enables building many of the useful bells and whistles that would enable better maintenance of the test suite in the future (including more powerful specs).

That's exactly what ``testament`` needs to not do: Adding "bells and whistles". The simplest code remains to be the code *not written*. Creeping featurism is Nim's plague. There is always "one more feature that one really needs, and it's really simple and Nim lacking it makes it  inconsistent!". 

> I guess the runner.nim part of this PR could be changed to use processes instead of threads - should be fairly easy - would that be more palatable? 

Yes.

**Comment by arnetheduck** [comment]
simple is such a loaded word these days.. how about we settle for `elegant` instead? so easy that simple turns to simplistic as dogmatism takes over.

anyway, I'm happy to remove a few features as well:

* `all` and `c` are both handled by `r` now due to its simplified match criteria, no need to keep them
* the html report looks out of place and could be cut as far as I'm concerned.. there's already json that a general-purpose tool can turn into something fancy
* by refactoring some of the tests, specs could be made more simple, less inconsistent and more powerful at the same time - this I think is the work for a separate branch though, there's enough in this one already - ie right now, it's a merry mix of `categories.nim`, specs and `callXxx` determining the test flow 

> That's not how execProcesses() works...

right, oops, missed the `n` argument

> Unclear why these features need to be command line arguments and/or how it's "hard" to pass them on to child processes.

they don't need to be, just are in the current implementation - hard because they're hand-coded for each option separately (easy to forget to pass on) and need the right amount of quoting which tends to be different cross-platform..

> Adding "bells and whistles". 

This does not necessarily imply writing more code, just better code - in fact it's often the opposite - specially with tools that have not seen a good round of refactoring in a while..

**Comment by Araq** [comment]
> all and c are both handled by r now due to its simplified match criteria, no need to keep them

They are in my finger-muscles now though, please keep them.

> the html report looks out of place and could be cut as far as I'm concerned.. there's already json that a general-purpose tool can turn into something fancy

Agreed, this can be a separate tool / library for those that look at the HTML, I never do.

> by refactoring some of the tests, specs could be made more simple, less inconsistent and more powerful at the same time - this I think is the work for a separate branch though, there's enough in this one already - ie right now, it's a merry mix of categories.nim, specs and callXxx determining the test flow

Yeah, refactoring tests is always an ongoing process and should be a separate PR.

**Comment by arnetheduck** [comment]
>>    I guess the runner.nim part of this PR could be changed to use processes instead of threads - should be fairly easy - would that be more palatable?
>  Yes.

bummer - this was easier said than done - `select` for process output is deprecated, so the trivial way of passing data between processes is dead..

**Comment by arnetheduck** [comment]
there - a thread-free version that uses execprocesses as before, and has no more magic than there already was.

the ci's don't have more than 2 cpus (travis) it but I think most people working on the compiler do

I'll kill the html stuff later indeed, in a separate branch - though arguably it doesn't make testament very much more complex / that's not where the complexity lies anyway..

**Comment by arnetheduck** [comment]
re doing in multiple branches / PR's, I don't quite see the point - the current testament version is a tangled mess of includes and tricky dependencies - there's no way to meaningfully split up this refactoring really - after this branch:
* `types.nim` is new and is used to clean up some dependencies
* everything that was in `tester.nim` related to running tests has moved to `runner.nim`
* `tester.nim` is a simple shell to fill out and shuffle variables around
* the only thing move-testament-in-separate-pr would help with would be a few paths - sure, can do a separate PR for that but...

**Comment by arnetheduck** [comment]
ok, did #9137 with some of the changes to make this branch smaller and less conflicty - don't have as much time as I'd like for this branch right now, and it still needs some improvement

**Comment by Araq** [comment]
We did refactor testament and sped it up with a "megatest" instead. More changes can be done in a fresh PR, closing.

**Pull request closed without merging**
