### PR TITLE
Restrict usages of underscore

### PR DESCRIPTION
**Pull request by nc-x**
Closes https://github.com/nim-lang/Nim/issues/7171

cc @Araq @dom96 @mratsim 

Note: I might have missed some places, so let me know if you know of any ;)

### CODE REVIEW

**Comment by nc-x** [comment]
Note: `nim check filename` currently shows duplicate error messages for 
```
type
  X = ref object           # (and also for ptr object)
    _: int 
```
which is fixed by this PR => https://github.com/nim-lang/Nim/pull/10107

**Comment by nc-x** [comment]
Arraymancer breaks 
(╯°□°）╯︵ ┻━┻

**Comment by Araq** [comment]
Ok, will simply close #7171 instead. It's really a non-issue.

**Comment by nc-x** [comment]
@Araq What about https://github.com/nim-lang/Nim/pull/10125/commits/caa9274d076cac7971ff443ca07c7ea656d4551a
Atleast it should be consistent for vars/lets and const

**Pull request closed without merging**
