### PR TITLE
Improve warning msg when -d:profiler not passed

### PR DESCRIPTION
**Pull request by boydgreenfield**
Partially addresses #3741

### CODE REVIEW

**Comment by Araq** [comment]
Why not make it use '.error' instead?

**Comment by boydgreenfield** [comment]
Updated, sorry for the delay.

**Comment by Araq** [comment]
Er sorry, ``-d:profiler`` is wrong, you need to use ``--profiler:on --stackTrace:on`` or ``--profiler:off --stackTrace:on -d:memProfiler``

**Comment by boydgreenfield** [comment]
Good point. Updated and squashed. Sorry about all that.

**Pull request merged**
