### PR TITLE
use func in uri module

### PR DESCRIPTION
**Pull request by ringabout**

### CODE REVIEW

**Review by dom96 — COMMENTED** [review]
Hmm, do these need to be called for the Nim compiler to test whether they have side effects? If so you will need to test each of them by calling them.

**Comment by ringabout** [comment]
Yea, there are `when isMainModule` tests in this module, I remove all the export symbols and only one function `initUri` is not covered. I call it by hand.

Run the test, we can get the successful msgs: "All good!"

**Comment by Araq** [comment]
Whenever we switch from ``proc`` to ``func`` we should also test with ``--experimental:strictFuncs``

**Comment by ringabout** [comment]
Is `{.experimental:strictFuncs.}` at the top of `uri` for testing module enough?
I will add test option in testsament.

**Comment by Araq** [comment]
Instead patch ``tests/effects/tstrict_funcs``, add ``uri`` to the ``import`` statement.

**Pull request merged**
