### PR TITLE
JS: Fixed passing byvar

### PR DESCRIPTION
**Pull request by yglukhov**
The problem is demonstrated in the test. I'm not sure if it should be fixed in the backend though.

### CODE REVIEW

**Comment by dom96** [comment]
Why create a PR if you don't want it merged?

**Comment by yglukhov** [comment]
Because I hope, there might be a better solution =). @Araq, could you please take a look?

**Comment by Araq** [comment]
``foo(s)`` should produce something like ``foo(nkConv(s))`` so fix the codegen for the implicit type conversion.

**Comment by yglukhov** [comment]
So after some discussions and trials and errors, it turned out that jsgen should look at the argument types. cgen does kinda similar thing. And that is done. Does it look less hacky?

**Pull request merged**
