### PR TITLE
fixes #11118

### LINKED ISSUE #11118: `except Exception as e: raise e` cannot be excepted.
On the C++ backend, excepting an Exception as e, and then raising it, can not be caught by calling functions.

```nim
proc raises() =
    raise newException(ValueError, "Raising a ValueError")

proc raises2() =
    try:
        raises()
    except ValueError as e:
        echo "Triggered raises2 except."
        raise e

try:
    raises2()
except ValueError as e:
    echo "Triggered the main body's except."
    raise e
```

### Current Output
```
Triggered raises2 except.
```

### Expected Output
```
Triggered raises2 except.
Triggered the main body's except.
*crash*
```

This bug occurs on both Nim 0.19.4 and a devel compiled at the time of this bug report, The C backend works as expected.

As a side note, while no except branches are triggered, the code after the try/except isn't called either. A hang occurs.

### PR DESCRIPTION
**Pull request by cooldome**
simple fix with 2 extra lines.
Avoid pushing the same exception into exception stack twice and do not pop too early.

### CODE REVIEW

**Comment by Araq** [comment]
For some reason tests/iter/tyieldintry.nim fails with this patch.

**Comment by cooldome** [comment]
I can replicate the failure. I will investigate though I will be away for couple of days

**Comment by cooldome** [comment]
I had a look on `tests/iter/tyieldintry.nim` failure. Looks like it is closure iterators codegen problem. 
Closure iterators understandably call `closureIterSetupExc((*colonenvP_).coloncurExc1_)` to set `currException`. Crash happens in finally block. Once we are in to finally block, I expect `colonenvP_.coloncurExc1_` to be reset with something like `(*colonenvP_).coloncurExc1_ = nil`, but it is not happening and we end up with dangling `colonenvP_.coloncurExc1_` 

We will need yglukhov help to progress.

@yglukhov: 
Hi Iuri,
Is possible to borrow your for this issue. Looks like  `colonenvP_.coloncurExc1_` is reset after finally and while it should be done right at the start of finally.

**Comment by krux02** [comment]
@cooldome is there still activity going on here?

**Comment by narimiran** [comment]
> We will need yglukhov advice to progress.

Pinging @yglukhov once again.

**Comment by yglukhov** [comment]
I'll take a look shortly

**Comment by yglukhov** [comment]
Superseded by #11147

**Pull request closed without merging**
