### PR TITLE
Allow marshal procs to be passed to a procvar

### PR DESCRIPTION
**Pull request by endragor**

### CODE REVIEW

**Comment by dom96** [comment]
procvar needs to die.

**Comment by endragor** [comment]
I agree, but can we merge this until it dies?

**Comment by Araq** [comment]
These look exactly like they will grow new optional parameters. Downvote from me. It's easy enough to wrap these in anon procs, right?

**Comment by endragor** [comment]
Alright, I overlooked the fact that they may grow new optional parameters and that will break backward compatibility. Closing this.

**Pull request closed without merging**
