### PR TITLE
fix #10073

### LINKED ISSUE #10073: can't build a tuple with `static int` element
can't build a tuple with `static int` element

### Example
```nim
block:
  proc foo[N: static int](dims: array[N, int])=
    const N1 = N
    let temp = N # works
    let temp2 = (a:N) # Error: invalid type: 'static[int](2)' in this context: 'tuple[a: static[int](2)]' for let
    # let temp3 = (N, N) # ditto

  foo([1, 2])
```

### Current Output
```
Error: invalid type: 'static[int](2)' in this context: 'tuple[a: static[int](2)]' for let
```

### Expected Output
compiles because `let temp = N` works

### PR DESCRIPTION
**Pull request by timotheecour**
* fix #10073

## links
* https://github.com/nim-lang/Nim/issues/9043 and PR https://github.com/nim-lang/Nim/pull/9046

### CODE REVIEW

**Comment by timotheecour** [comment]
looks like this PR helps a bit, but still fails in following case:

```nim
proc foo[N: static int](dims: array[N, int]): auto =
  const N1 = N
  let temp = N # works
  let temp2 = (a:N)
  temp2

echo foo([1, 2]) # now is ok
doAssert foo([1, 2]) == (a:2) # Error: type mismatch: got <tuple[a: static[int](2)], tuple[a: int]>
```

couldn't we make `static` convert to something else (`const`??) as soon as it's instantiated, to avoid special casing it everywhere via `skipTypes` in this PR as well as in https://github.com/nim-lang/Nim/pull/9046 ?

**Comment by Araq** [comment]
``static T`` needs to be removed from the language IMHO. Just allow to pass integer values as type parameters turning the value ``N`` into ``range[0..N-1]`` would allow almost the same patterns without this never ending clusterfuck of bugs, edge cases and downright unspecified behaviour.

**Comment by timotheecour** [comment]
> static T needs to be removed from the language IMHO

=> we can discuss that here: https://github.com/nim-lang/Nim/issues/10085

**Comment by timotheecour** [comment]
/cc @Araq 
PTAL, this unblocks https://github.com/nim-lang/Nim/pull/10070 

removing the WIP label to unblock this PR, the workaround for clients is simple enough (add `const N1 = N` for a static param `N`), and the other issue mentioned above in https://github.com/nim-lang/Nim/pull/10080#issuecomment-449630833 is pre-existing.

**Comment by timotheecour** [comment]
ping @zah or @Araq

**Comment by Araq** [comment]
That doesn't help much. 

1. It is not clear that ``static T`` within a tuple should be allowed.
2. It is not clear that the codegens can deal with it.

**Comment by timotheecour** [comment]
> That doesn't help much.

that unblocks https://github.com/nim-lang/Nim/pull/10070 (otherwise I'd need to change the test 

> It is not clear that static T within a tuple should be allowed.

there's a test that relies on it, see https://github.com/nim-lang/Nim/pull/9046 (./tests/vm/tissues.nim) /cc @LemonBoy 
seems also rather arbitrary to disallow `static T within a tuple`

> It is not clear that the codegens can deal with it.

not sure I understand that point; I assumed by the time it reaches codegen, `static[T]` would already be converted to `T` ; CI should already cover this I believe

**Comment by Araq** [comment]
> not sure I understand that point; I assumed by the time it reaches codegen, static[T] would already be converted to T ; CI should already cover this I believe

But ``static T`` object/tuple fields should be optimized away since they don't contain any runtime values...

**Comment by timotheecour** [comment]
> But static T object/tuple fields should be optimized away since they don't contain any runtime values...

I still dont' understand; how is that different from behavior of `const` or `static` in example below, where it doesn't get optimized away since `let a = (...)` tells the compiler to convert them to a runtime value?
```nim
const Foo1 = 10
proc fun(foo4: bool, Foo5: static bool) =
  const Foo2 = 11
  let foo3 = 12
  let a = (Foo1, Foo2, foo3, foo4, Foo5) # works
  echo a

fun(true, true)
```
the way we use the static/const/var should dictate whether it should get converted to a runtime value or not

**Comment by zah** [comment]
A more proper fix has been pushed here: https://github.com/nim-lang/Nim/pull/10218

**Comment by timotheecour** [comment]
thanks a bunch @zah I verified it also passes this: https://github.com/nim-lang/Nim/pull/10080#issuecomment-449630833 ; closing this in favor of your PR

**Pull request closed without merging**
