### PR TITLE
Support json null in %*

### PR DESCRIPTION
**Pull request by def-**
This is the nicest way I found to support `null` directly in `%*`. It's nice being able to directly paste json into Nim code, otherwise we could just use `nil`. This PR fixes that `nil` used to create a string `""`, which is now a `null`.

### CODE REVIEW

**Comment by dom96** [comment]
The `%*` operator is already a macro, perhaps `null` could be special cased inside the macro?

**Comment by def-** [comment]
Right, I thought about that but thought it could cause confusion when someone else has a variable coincidentally named `null`. I think both variants have problems, not sure which is better here.

**Comment by dom96** [comment]
Actually I think that simply fixing it so that `nil` works is good enough. No need for the `null` support, it just becomes confusing.

**Comment by def-** [comment]
I guess you're right, probably the best solution.

**Pull request merged**
