### PR TITLE
Fix async SSL tests

### PR DESCRIPTION
**Pull request by avsej**
Ensure that all messages has been send by client

### CODE REVIEW

**Comment by cheatfate** [comment]
@avsej what is the reason of this change? Original version is also `ensure that all messages has been send by client`.

**Comment by avsej** [comment]
The problem with older version is that it didn't wait for all futures to complete and closed sender too early. Which caused mismatch of number of received messages. `msgCount` equals `swarmSize`.

The issue is 100% reproducible. At least on Fedora 29/30:
https://koji.fedoraproject.org/koji/taskinfo?taskID=29394338

The fix is using `all` function to await for all `send` commands.

**Comment by cheatfate** [comment]
@avsej how it didn't wait for all futures to complete, if it exactly makes
```nim
await send(client, "Message " & $i & "\c\L")
```
so it waits for every single data it sends. So your fix produces exactly equal behavior but in different way.

**Comment by avsej** [comment]
So you are saying that code:
https://github.com/nim-lang/Nim/blob/e63c66b8104225cefe0413471410ef4c072f9954/tests/async/tasyncssl.nim#L27-L28
Will not close socket until it will send all `messagesToSend` messages, until *all* `messagesToSend` futures will be completed? In reality this is not true, and it closes socket after first completed future. This is why I accumulated futures in a group and return as single future to await from `sendMessages`.

Could you clarify, why the code is equivalent?

**Comment by dom96** [comment]
> So you are saying that code: [...] Will not close socket until it will send all messagesToSend messages, until all messagesToSend futures will be completed?

Yes, @cheatfate is correct. Your code shouldn't affect the semantics, if it does then there is a bug somewhere else (did you test after https://github.com/nim-lang/Nim/pull/8843?)

**Comment by avsej** [comment]
@dom96 the patch you have pointed cannot be a fix as this code does not exist in 0.18.0

**Comment by dom96** [comment]
So the problem exists in 0.18.0 too?

**Comment by avsej** [comment]
Right. Maybe it is related to updated OpenSSL in Fedora 29/30 (`OpenSSL 1.1.1-pre9`)? As it does not affect Fedora 28 (`OpenSSL 1.1.0h-fips`). But I don't see why it might affect the behaviour of nim futures. Is there something I can do to trace the cause?

Here are quick steps to get environment to reproduce it.

```
docker run -ti --rm registry.fedoraproject.org/fedora:29 /bin/bash
```

And inside container:

```
dnf install @development-tools

git clone --depth 1  --branch v0.18.0 git://github.com/nim-lang/nim.git
cd nim
git clone --depth 1 https://github.com/nim-lang/csources.git
(cd csources; sh build.sh)
./bin/nim c koch
./koch boot -d:release

./koch tests cat async
```

**Comment by dom96** [comment]
Can you elaborate on what the error your getting is?

**Comment by avsej** [comment]
Sure. This tests spawns SSL server, which counts number of messages sent. Also it spawns number of senders which send those messages. For success server have to receive all messages, but in the fact the sender sockets closed after first message. So instead of `swarmSize * messagesToSend`, the server receives only `swarmSize * 1` messages.

This is how communication of the client-server looks in wireshark.

screenshot-2018-09-06_07-13-26-1536207206

My idea was that in this case somehow `await sendMessages(sock)` only waits for first future and skips everything else.

**Comment by Araq** [comment]
@dom96 This test also fails for @krux02 on his local Linux box.

**Comment by dom96** [comment]
This isn't a valid fix though. The problem lies somewhere else and this PR is just working around it by accident.

Can @krux02 investigate?

**Pull request closed without merging**
