### PR TITLE
fix system.write skipping null bytes on Windows [backport]

### PR DESCRIPTION
**Pull request by exelotl**
On Windows, using Nim 1.0.0 or the latest nightly build, `write()` skips over null bytes. This would break any code that uses `write` or `writeFile` to output raw binary / non-text data.

This commit aims to fix it.

### CODE REVIEW

**Comment by Araq** [comment]
Nice but you also need to patch techo_unicode.nim

**Comment by narimiran** [comment]
@exelotl Since this is marked as `[backport]`, can you please patch `techo_unicode.nim` so we can include this in the upcoming v1.0.2?

**Comment by exelotl** [comment]
@narimiran Sorry for the delay with this, but it seems like putting nulls in the 'expected output' for `techo_unicode` does not cause the test to pass, because somehow the 'actual output' contains newlines instead of nulls. Is this a problem with testament?

Besides this, I'm having second thoughts on whether my solution here is the right way to go. See the discussion on issue https://github.com/nim-lang/Nim/issues/12315, and please let me know if you have any ideas

**Comment by narimiran** [comment]
Superseded by https://github.com/nim-lang/Nim/pull/12385. Closing.

**Pull request closed without merging**
