### PR TITLE
getHomeDir fallback implementation on posix

### PR DESCRIPTION
**Pull request by kubo39**

### CODE REVIEW

**Comment by Araq** [comment]
Meh, getHomeDir for nimscript is dangerous.

**Comment by dom96** [comment]
Under what circumstances is the HOME env var not present?

**Comment by kubo39** [comment]
Inside Perl/CGI, there's no environment vairables.

**Comment by Araq** [comment]
This is Linux specific code and ugly. Closing.

**Comment by ehmry** [comment]
Actually the official POSIX way to get the home directory is `getpwent`, I believe `getenv(HOME)` is more a convention then a standard.

**Pull request closed without merging**
