### PR TITLE
Custom pragmas in proc types

### PR DESCRIPTION
**Pull request by cooldome**
Pragmas in proc types.

I was not sure where put pragma in `PType` so I have used existing effects node, let me know if there are better places.

Luckily, nnkProcTy already had a place for pragma so it should be non breaking change.

### CODE REVIEW

**Comment by Araq** [comment]
Impressively clean patch. :-) Let's hope the tests are green.

**Comment by Araq** [comment]
tests/macros/tgettypeinst.nim fails.

**Comment by cooldome** [comment]
Thanks.
I have fixed the test, fingers crossed hopefully no more issues

**Comment by Araq** [comment]
But travis says: 

[1mlib/packages/docutils/rst.nim(1335, 6) [0m[31mError: [0m'parseSection' is not GC-safe as it calls 'parseParagraph'[0m
FAILURE

Which seems related to your patch.

**Comment by cooldome** [comment]
Sorry, missed `rst.nim` somehow I was looking into `strutils_examples.nim`.
Not sure I am going the right direction with the last two submits.

**Comment by cooldome** [comment]
Should be good for review now, tests failures are from devel branch

**Pull request merged**
