### PR TITLE
random: minor documentation updates

### PR DESCRIPTION
**Pull request by Jjp137**
This pull request mainly adds documentation and examples for the `sample` procs that have a `set` parameter. There are also spelling fixes and other minor changes too.

### CODE REVIEW

**Comment by krux02** [comment]
@narimiran the failing test is in https://github.com/narimiran/itertools, so I request you to review this. It is just documentation changes, but maybe I oversaw something.

**Comment by juancarlospaco** [comment]
Why theres a hard-coded seed on all the `runnableExamples` :grey_question: 
I mean users can get confused that is the best practice and the way it suppose to be done,
if you are editing it, that can be improved like `randomize(987)` :arrow_right: `randomize()`
:thinking:

**Comment by Jjp137** [comment]
@juancarlospaco See the discussion in #10546, although I'm not too fond of it either. That's the best we came up with at the time, though.

**Comment by juancarlospaco** [comment]
Ok, you are right. :+1:

**Pull request merged**
