### PR TITLE
Use testament to check Norm test pass

### PR DESCRIPTION
**Pull request by moigagoo**
This is what I actually use to test Norm, so it's better to use it.

This should not currently pass. This is expected because this is exactly the problem I want to highlight with this PR. My tests do indeed not pass at the moment.

### CODE REVIEW

**Comment by moigagoo** [comment]
Relates to #19017

**Comment by moigagoo** [comment]
It seems like this fix didn't land in 1.6.2. Why is that?

I thought develop is merged into master and a new tag is added during release but apparently this commit from develop wasn't merged.

I was hoping to update Nim version for Norm but I can't since tests won't run on 1.6.0 or 1.6.2.

**Comment by narimiran** [comment]
> It seems like this fix didn't land in 1.6.2. Why is that?

Because it wasn't marked as `[backport]`.



> I thought develop is merged into master

1. There is no `master`.
2. Stuff in `devel` will become next **major** release.
3. Anything that should be *backported* to next **minor** release, should be marked as `[backport]`. E.g. for Nim 1.6.x, commits marked as `[backport]` are cherry-picked into `version-1-6` branch.

**Comment by moigagoo** [comment]
Thanks for the explanation. My bad, didn't know all that, should've learned first


Is it too late to mark it as backport so that it lands in 1.6.4? If there will be 1.6.4.

**Comment by narimiran** [comment]
> Is it too late to mark it as backport so that it lands in 1.6.4?

It is not too late.

> If there will be 1.6.4.

I'm 99% sure there'll be 1.6.4.

**Comment by narimiran** [comment]
It is backported now, it will be part of the next 1.6.x stable release, whenever that comes out.

**Comment by narimiran** [comment]
@moigagoo `norm` is now red on 1.6.x CIs: https://github.com/nim-lang/Nim/runs/4573499025?check_suite_focus=true (`testament: command not found`)

**Comment by ringabout** [comment]
https://github.com/nim-lang/Nim/pull/19092 needs to be backported too which fixed the other part of the issue.

**Pull request merged**
