### PR TITLE
Move four modules to graveyard

### PR DESCRIPTION
**Pull request by narimiran**
Rationale:

These four modules (subexes, scgi, smtp, oids) are poorly documented, not used in the stdlib, there are no tests for them, and aren't much used [in the wild](https://gist.github.com/GULPF/6d49e74af9992f8fc65476a9264488a0).

They will be added to [graveyard](https://github.com/nim-lang/graveyard) so they can be installed via nimble.

----

Please do NOT squash commits when merging, in case one of them needs to be reverted later.

### CODE REVIEW

**Comment by andreaferretti** [comment]
Just a reminder:

Fixes https://github.com/nim-lang/Nim/issues/2796
Fixes https://github.com/nim-lang/Nim/issues/9741
Fixes https://github.com/nim-lang/smtp/issues/2

**Comment by narimiran** [comment]
And with `asyncio` already in `lib/deprecated`, removing `scgi` also fixes nim-lang/Nim#8298.

**Comment by dom96** [comment]
This is pretty breaking. I can think of at least two of my projects that use `oids` and at least one that uses `smtp`, why remove it? 

By the way, merging your own PR is really bad, especially for something like this...

**Comment by timotheecour** [comment]
a few more points:
* generally I like the spirit of this PR and we want this kind of spring cleaning; that being said:
* I also use `oids`, eg for `nimongo`; maybe we shd prioritize moving things that have an existing better alternative as opposed to stuff that don't have such alternative, eg I don't know of any replacement of `oids` ??
* some of the linked issues shouldn't be closed just because the files were removed; a better option is:
  * migrate these issues to graveyard repo, as the underlying issues remain un-fixed, eg https://github.com/nim-lang/Nim/issues/9741
* we should really prioritize https://github.com/nim-lang/graveyard/issues/4 (add travis and appveyor configs) before further moving stuff to graveyard otherwise things will bitrot

> By the way, merging your own PR is really bad, especially for something like this...

indeed. A thumbs up means: I like the spirit of the PR, it doesn't mean "I approve this PR after a proper review".
That being said, merging your own PR if someone approved it should be fine. The definition of "someone" is subject to debate, see https://irclogs.nim-lang.org/09-01-2019.html#08:17:44 for the whole discussion thread around it /cc @Araq

**Comment by narimiran** [comment]
> merging your own PR is really bad

It was discussed internally previously, I wouldn't merge it otherwise.

**Comment by narimiran** [comment]
> It was discussed internally previously and approved

...but, after some more discussion, SMTP and OIDS are back :) (0a2f711b9)

**Comment by andreaferretti** [comment]
> I can think of at least two of my projects that use oids and at least one that uses smtp

@dom96 That's not a good reason to avoid moving modules into graveyard: your projects can simply add a nimble dependency.

I have no opinion on `smtp`, but it is very weird to have `oid` into the stdlib since:

* it is something similar to a UUID (something common to many languages) but not compatible with its spec
* instead, it is derived from MongoDB concept of OID
* and still fails to ba compatible with the MongoDB spec

We should implement UUIDs and remove this module

**Comment by dom96** [comment]
> @dom96 That's not a good reason to avoid moving modules into graveyard: your projects can simply add a nimble dependency.

That's true. And yes, in general I'm happy for this to happen, but I want us to have a good discussion about it. What exactly belongs in a stdlib and what doesn't?

**One thing I would like to stress though:** how are users supposed to know that they can get these modules from graveyard? We need a transition period for these otherwise our users will just get frustrated. @narimiran Instead of removing these modules, can you replace the file's contents with ``{.error: "This module has moved to the graveyard, use it by adding `requires "subexes"` to your .nimble file"}``?

**Comment by narimiran** [comment]
> deserves a separate dedicated discussion in a github issue for easy cross-reference

---> https://github.com/nim-lang/RFCs

**Comment by Araq** [comment]
> instead, it is derived from MongoDB concept of OID and still fails to ba compatible with the MongoDB spec

It was ported from C to Nim and then later MongoDB changed its spec / C implementation, that's why.

**Comment by ITwrx** [comment]
i object to the idea that smtp is not used much in the wild just because _libraries_ on _github.com_ don't need to send email.  Nearly every web app will (contact forms, at the least) and some desktop apps will, and i'm guessing you wouldn't hear about it.

**Comment by Araq** [comment]
True but regardless of these facts Smtp as an external package not tied to Nim's slow release cycle makes sense.

**Comment by ITwrx** [comment]
hmm, i hadn't thought about that aspect. I see that smtp is not even in the Graveyard repo (anymore?) and is in it's own repo. I guess modules in their own nim-lang repo are planned to be supported going forward. If so, great!

**Comment by Araq** [comment]
> I guess modules in their own nim-lang repo are planned to be supported going forward. If so, great!

Yes, that is indeed the case and we try to ensure that the docs still cover these modules.

**Pull request merged**
