### PR TITLE
Continue #13002

### PR DESCRIPTION
**Pull request by Clyybber**
Now uses the dfa for firstWrite analysis.
Eventually I want to implement https://github.com/nim-lang/Nim/issues/13003#issuecomment-570078768 and do init elision along the way.

### CODE REVIEW

**Comment by cooldome** [comment]
Thinking if we need to do anything extra for variable global variables. It may look like a first assignment in proc, but if it is is global variable assignment can happen outside of DFA reach. Possibly it is not a problem just thinking out loud. Not blocker for this PR.

**Comment by Araq** [comment]
@Clyybber Found any new flaws in the meantime?

**Comment by cooldome** [comment]
I can run it on my codebase on Monday

**Comment by cooldome** [comment]
This  is a rocket

**Pull request merged**
