### PR TITLE
Fix astdef typ deref

### PR DESCRIPTION
**Pull request by alehander42**

### CODE REVIEW

**Comment by Araq** [comment]
tests\pragmas\tcustom_pragma.nim(210, 3) Error: enable the 'not nil' annotation with {.experimental: "notnil".}

**Comment by alehander42** [comment]
ugh, the nim.cfg from my other branch fooled me

**Comment by alehander42** [comment]
Ok, added the pragma inline

**Comment by alehander42** [comment]
unrelated error(i think)

**Comment by alehander42** [comment]
this should be ok

**Pull request merged**
