### PR TITLE
Fixed symbol reordering in lambdalifting introduced in #22559

### PR DESCRIPTION
**Pull request by yglukhov**
@bung87, please review

### CODE REVIEW

**Comment by Araq** [comment]
Fine for now, but needs a comment on why this is required because it is subtle.

**Comment by yglukhov** [comment]
> Fine for now, but needs a comment on why this is required because it is subtle.

TBH I don't have a clue why this patch works, as it was @bung87 who suggested it. Would be cool if @bung87 added a comment or something.

**Comment by yglukhov** [comment]
Failure unrelated?

**Comment by Araq** [comment]
Failure unrelated but I noticed a new problem: This seems to lift every local even it might not be used?

**Comment by yglukhov** [comment]
I've found [a way to force the required order](https://github.com/yglukhov/yasync/commit/f92a6a1e8780b4aef863d7fb777f4d5e41b0f0a1) from my code, so this PR is not important for me, unless you think that order preservation is required in lambdalifting.

**Comment by Araq** [comment]
Well the code looks better without this patch...

**Pull request closed without merging**
