### PR TITLE
Fixes `times` module compilation on cpp backend.

### PR DESCRIPTION
**Pull request by dom96**
My attempt at fixing this. No idea if it's valid.

### CODE REVIEW

**Comment by GULPF** [comment]
Shouldn't it be cint? `time_t` is 32 bits on 32 bit platforms.

**Comment by cooldome** [comment]
time_t size is different depending on the platform. AFAIK, on linux it can be both 32bit and 64bit depending on how you have compiled your libc and kernel. On windows size depends on defines like _USE_32BIT_TIME_T

**Comment by dom96** [comment]
``cint`` doesn't work, I still get the errors then:

```
        ...        ...... error: no matching function for call to 'localtime'
        ...         result = (*localtime((&a)));
        ...                    ^~~~~~~~~
        ... /usr/include/time.h:112:12: note: candidate function not viable: no known conversion from 'int *' to 'const time_t *' (aka 'const long *') for 1st argument
        ... struct tm *localtime(const time_t *);
```

**Comment by Araq** [comment]
Merging for now but it's unlikely to be correct for all Posix platforms.

**Pull request merged**
