### PR TITLE
Make createDir return discardable bool

### LINKED ISSUE #4917: RFC: More flexible directory creation
Currently stdlib only provides one portable way (as far as I can see) to create a directory: `createDir`. It, however, lacks flexibility:
1. It creates the all the parent directories, which sometimes may not be what we want. Maybe we should expose some lower-level function (`createSingleDir`?) and implement `createDir` using it?
2. More importantly (in my case), it does not indicate whether the directory has already existed. This is, indeed, a preferred behaviour for most use cases (just as the comment says), but not for all. For example, this [issue](https://github.com/OpenSystemsLab/tempfile.nim/issues/5) in tempfile. We need some kind of escape hatch to access this information without reinventing `createDir` from scratch in each use case, or introducing races into our programs with `existsDir` checks. A simplest solution would be for `createDir` to return a discardable `bool` to indicate success. This should not break much existing code, but it still might break some.

### PR DESCRIPTION
**Pull request by nigredo-tori**
Fixes #4917

### CODE REVIEW

**Comment by yglukhov** [comment]
Well you're still not getting precise control. The bool is returned, but how many intermediate directories we have created on our way? Or how do i make it to not create intermediates and fail in such cases? I would still suggest going my way described in #4917. Implementation detail is not an argument here. Better think from the users perspective whether this interface would be simple and intuitive. E.g. `mkdir` unix command behaves in `strict` mode by default, and `auto` mode with `-p` flag.

**Comment by nigredo-tori** [comment]
I agree we don't get full control with `createDir`, but we shouldn't strive to. There are a lot of aspects the user might care about: exactly how many directories were created, were any of those symlinks, etc. We really can't cover all cases. `createDir` is a convenience function, that covers one (overwhelmingly common) use case. The smart thing to do here would be to expose a primitive for cases where greater degree of control is required.

About your suggestion: it's not just the implementation - again, the whole behaviour changes depending on the value of the flag you suggest. Conditions recognized as an error change. Take `createDir`'s current doc comment for example: every second sentence will have to be amended for the strict version!

This really should be a separate proc - and we already have the implementation. `rawCreateDir` in `os` internals does exactly the thing we need, we just have to export it (with a better name, of course).

Finally, about `mkdir -p`. Command-line tools tend to have a lot of flags to avoid having a separate executable for each task (and to cater to some popular scenarios) - look at `ls` for example. This line of thinking does not hold in programming, though - we don't have to glue functions together in our API just because they do similar things and their type signatures match. As an example - `mkdir(2)` *syscall* is perfectly focused, and does exactly one thing, even though it would be quite easy to give it a lot of flags for different use cases.

**Comment by Araq** [comment]
> createDir is a convenience function, that covers one (overwhelmingly common) use case. The smart thing to do here would be to expose a low-level primitive for cases where greater degree of control is required.

I completely agree but this raises the question whether ``createDir`` needs to be patched at all then. ``discardable`` doesn't play nice with ``auto`` return types. (Try it, it can get confusing.)

**Comment by nigredo-tori** [comment]
Improved following the discussion in #4917

**Pull request merged**
