### PR TITLE
[doc/tut1] removed discard discussion in comments

### LINKED ISSUE #11504: Remove `discard` discussion from Comments section Tutorial 1
At least for a newcomer (like me) to Nim, the sudden introduction of the `discard` statement as early as https://nim-lang.org/docs/tut1.html#lexical-elements-comments was jarring. I did click on the link and it turned out to be a discussion on procedures and silently throwing away return values. 

This, in my opinion, is both unnecessary and confusing. Since at the very start of the tutorials we don't know that triple quotes are procs that return values (at least that's what I gather from the discussion), that diversion increases the overall effort the reader must apply in order to understand something as simple as comments.

If indeed the triple quotes are procs with return values, we should simplify the explanation to say so.

### PR DESCRIPTION
**Pull request by pietroppeter**
Fixes #11504 
My first pull request, testing the machinery while doing something very simple... :)

### CODE REVIEW

**Comment by Araq** [comment]
Why remove this? it's the *only* supported way by testament.

**Comment by pietroppeter** [comment]
I understood that this removal was the implied solution in the discussion about issue #11504. I went for it since the issue was open and it was recently marked hacktoberfest.

If I were to summarize the sense of this removal I would say:

* the standard way of making a multi comment changed to using #[]#
* in a tutorial for beginners it might be distracting to propose an alternative way that links to a more complicate discussion about discard
* a more experienced user would be able to understand a discard multi line string anyway

Now I get that it seems important in testament, although I was not able to understand how and why (beginner in Nim and testament is acknowledged to lack documentation; I tried looking at code but could not understand the relation to this topic).

If this paragraph is indeed deemed important, I guess you could just dismiss this pull request and close the original issue.

**Comment by GULPF** [comment]
> Why remove this? it's the only supported way by testament.

I doubt anyone reading `tut1` cares or even knows about testament.

**Comment by Araq** [comment]
Ok, I take it back, removing it from the tutorial is fine.

**Comment by Araq** [comment]
Irrelevant CI failure, merging.

**Comment by b3liever** [comment]
I have an objection, you removed it from the tutorial but nowhere else it's mentioned, meaning this information is lost. You could have added it in the manual

**Pull request merged**
