### PR TITLE
[feature] Added `getDataDir()` and `getStateDir()` besides `getConfigDir()` and `getCacheDir` and made them all uniform.

### PR DESCRIPTION
**Pull request by auroraanna**

### CODE REVIEW

**Comment by Araq** [comment]
I don't know what a "state dir" is but these things should go into `std / appdirs` and `os.nim` should be patched too.

**Comment by auroraanna** [comment]
The state directory is defined in the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/latest/ar01s02.html).

**Comment by auroraanna** [comment]
Patched with what tho?

**Comment by auroraanna** [comment]
It is kind of difficult to choose directories, to create functions for because the OSs use different directories. Currently the xdg data directory and the xdg state directory have no mapping in this library and several directories in macOS don't have either under `~/Library`.

**Comment by auroraanna** [comment]
I want the xdg data directory and the xdg state directory to get added in this library too so I won't have to put my program's files in the wrong directory.

**Comment by ringabout** [comment]
Now there is a new module called `st/appdirs` https://github.com/nim-lang/Nim/blob/devel/lib/std/appdirs.nim

**Comment by ringabout** [comment]
Now there is a new module called `st/appdirs` https://github.com/nim-lang/Nim/blob/devel/lib/std/appdirs.nim

**Comment by auroraanna** [comment]
I was trying to adapt my pr to the the changes but this is confusing.

**Comment by auroraanna** [comment]
Why are procs like getHomeDir, getConfigDir defined in `lib/std/private/osappdirs.nim` and then defined again in `lib/std/appdirs.nim`, where they just reference the first one?

**Comment by auroraanna** [comment]
Where should I put my new procs?

**Comment by Ecorous** [comment]
#21408 Added `getDataDir`, so that one is irrelevant afaics

**Comment by ringabout** [comment]
Succeeded by https://github.com/nim-lang/Nim/pull/21408 Feel free to make a new PR for another proc if that's needed.

**Pull request closed without merging**
