### PR TITLE
[WIP] Http client reconnection fix

### PR DESCRIPTION
**Pull request by dom96**
This is a really rough PR that I quickly created and so the code is horrible. We can likely do better, but I wanted to get it out here as a reminder.

### CODE REVIEW

**Comment by skilchen** [comment]
what happens if you encounter a malicious server doing something like:
```nim
import asynchttpserver, asyncdispatch, asyncnet

var server = newAsyncHttpServer()

const msg = "HTTP/1.1 200"

proc cb(req: Request) {.async.} =
    await req.client.send(msg)
    req.client.close()

waitFor server.serve(Port(8000), cb)
```
your new client will loop indefinitely...
You really shouldn't use recursion (its just as wrong here as it is in the handling of redirects). And you probably should limit the number of retries. But what problem do you want to solve with this? IMHO the behaviour of the original httpclient (raising the exception ` Connection was closed before full request has been made [ProtocolError]`) is more appropriate.

**Comment by dom96** [comment]
I think that exception is only appropriate when the connection is closed in the middle of a request. If I have a ``AsyncHttpClient`` instance connected to a server, and that server disconnects my client in between two requests then ``AsyncHttpClient`` should be able to reconnect.

**Comment by dom96** [comment]
To give a bit more context I ran into this when testing my HTTP server. It went something like this:

1. Create new HTTP client
2. Start ``helloworld`` server on port 8080
3. Request "/"
4. Kill ``helloworld`` server.
5. Start ``dispatcher`` server on port 8080
6. Request "/"
    * Exception is raised.

I suppose you could say I should have created a new HTTP client when I killed my server. But I spent a lot of time wondering what was going wrong, and seen others run into the same issue, so I thought it was time to fix it.

**Comment by Araq** [comment]
Stalled PR, closing.

**Comment by dom96** [comment]
Hope I remember that I created this when I run into this bug again.

**Pull request closed without merging**
