### PR TITLE
retain postfix node in type section typed AST, with docgen fix

### PR DESCRIPTION
**Pull request by metagn**
Continued from #23096 which was reverted due to breaking a package and failing docgen tests. Docgen should now work, but ~~a PR is still pending for the package: https://github.com/SciNim/Unchained/pull/45~~ has been merged

### CODE REVIEW

**Comment by metagn** [comment]
CI now passes

**Comment by Araq** [comment]
Superb work, but how hard would it be for the doc gen to not render the export markers? Only public symbols are visible in the docs anyway so the export marker is redundant and it's bit uglier with them.

**Comment by metagn** [comment]
Apparently the docgen just [renders the AST](https://github.com/nim-lang/Nim/blob/4b1a84170786653f60313f7bdf56efa3928c2a3a/compiler/docgen.nim#L1033-L1034), we could add a `TRenderFlag` that never renders postfixes. This would also make object fields not render postfixes anymore ([right now they do](https://nim-lang.org/docs/system.html#Exception)). Edit: Added `renderNoPostfix`, but it has an exception for fields

That being said I only now realized `let`/`const`/`proc` also do not retain postfix nodes. I can do these as well but they have a chance of breaking packages again (especially proc), should they go in a separate PR after this one?

**Comment by Araq** [comment]
> should they go in a separate PR after this one?

Yes, please.

**Pull request merged**
