### PR TITLE
Fixed THINSTANCE declaration in dynlib.nim for VS compiler

### PR DESCRIPTION
**Pull request by kosz78**
VS compiler produce the following error during compilation of dynlib.nim:
```
stdlib_dynlib.cpp(390): error C2664: 'BOOL FreeLibrary(HMODULE)': cannot convert argument 1 from 'void *' to 'HMODULE'
stdlib_dynlib.cpp(390): note: Conversion from 'void*' to pointer to non-'void' requires an explicit cast
stdlib_dynlib.cpp(399): error C2664: 'FARPROC GetProcAddress(HMODULE,LPCSTR)': cannot convert argument 1 from 'void *' to 'HMODULE'
stdlib_dynlib.cpp(399): note: Conversion from 'void*' to pointer to non-'void' requires an explicit cast
```
I found correct way that declared in [lib/system/dyncalls.nim](https://github.com/nim-lang/Nim/blob/devel/lib/system/dyncalls.nim#L88)

### CODE REVIEW

**Comment by cheatfate** [comment]
Sorry, but i dont have any problems with VS compiler (Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23506 for x64).

**Comment by kosz78** [comment]
I have tested with the same version of VS Compiler.
Just create nim file with one import
```
import dynlib
```
and compile with
`cc=vcc`

`nim cpp test.nim`

**Comment by cheatfate** [comment]
Ok, "nim cpp test.nim" failes to compile but "nim c test.nim" compiled successfully. But your patch doesnt check any defines...

**Comment by kosz78** [comment]
I have added check for cpp

**Pull request merged**
