### PR TITLE
Add new self-signed 4096 bit certificate to testdata

### PR DESCRIPTION
**Pull request by kraptor**
The test tasyncssl may fail on modern linux versions
as they require at least 2048 bit certificates.

A new certificate and private key with default values
has been added to meet this new requirement, and
pushed it a bit further to 4096 to be future proof.

### CODE REVIEW

**Comment by kraptor** [comment]
As a reference, this is the error output for that test failing in this scenario:

```
[  888s] FAIL: tests/async/tasyncssl.nim c                                  ( 2.19 sec)
[  888s] Test "tests/async/tasyncssl.nim" in category "async"
[  888s] Failure: reExitcodesDiffer
[  888s] Expected:
[  888s] exitcode: 0
[  888s]
[  888s] Gotten:
[  888s] exitcode: 1
[  888s]
[  888s] Output:
[  888s] tasyncssl.nim(59)        tasyncssl
[  888s] asyncmacro.nim(232)      createServer
[  888s] asyncmacro.nim(28)       createServerNimAsyncContinue
[  888s] tasyncssl.nim(45)        createServerIter
[  888s] net.nim(661)             newContext
[  888s] net.nim(575)             loadCertificates
[  888s] net.nim(540)             raiseSSLError
[  888s] [[reraised from:
[  888s] tasyncssl.nim(59)        tasyncssl
[  888s] asyncfutures.nim(438)    asyncCheck
[  888s] asyncf/home/abuild/rpmbuild/BUILD/nim-1.6.4/testament/testament.nim(794) testament
[  888s] /home/abuild/rpmbuild/BUILD/nim-1.6.4/testament/testament.nim(765) main
[  888s] /home/abuild/rpmbuild/BUILD/nim-1.6.4/testament/categories.nim(692) processCategory
[  888s] /home/abuild/rpmbuild/BUILD/nim-1.6.4/testament/categories.nim(185) asyncTests
[  888s] /home/abuild/rpmbuild/BUILD/nim-1.6.4/testament/testament.nim(575) testSpec
[  888s] /home/abuild/rpmbuild/BUILD/nim-1.6.4/testament/testament.nim(556) targetHelper
[  888s] /home/abuild/rpmbuild/BUILD/nim-1.6.4/testament/testament.nim(531) testSpecHelper
[  888s] /home/abuild/rpmbuild/BUILD/nim-1.6.4/testament/testament.nim(311) addResult
[  888s] /home/abuild/rpmbuild/BUILD/nim-1.6.4/lib/std/private/gitutils.nim(78) diffStrings
[  888s] /home/abuild/rpmbuild/BUILD/nim-1.6.4/lib/std/private/gitutils.nim(50) diffFiles
[  888s] /home/abuild/rpmbuild/BUILD/nim-1.6.4/lib/system/assertions.nim(38) failedAssertImpl
[  888s] /home/abuild/rpmbuild/BUILD/nim-1.6.4/lib/system/assertions.nim(28) raiseAssert
[  888s] /home/abuild/rpmbuild/BUILD/nim-1.6.4/lib/system/fatal.nim(53) sysFatal
[  888s] Error: unhandled exception: /home/abuild/rpmbuild/BUILD/nim-1.6.4/lib/std/private/gitutils.nim(50, 12) `(status == 0) or (status == 1)`  [AssertionDefect]
[  888s] utures.nim(272)    callback=
[  888s] asyncfutures.nim(251)    addCallback
[  888s] asyncfutures.nim(104)    callSoon
[  888s] asyncfutures.nim(437)    asyncCheckCallback
[  888s] ]]
[  888s] Error: unhandled exception: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small
[  888s] Async traceback:
[  888s]   tasyncssl.nim(59)   tasyncssl
[  888s]   asyncmacro.nim(232) createServer
[  888s]   asyncmacro.nim(28)  createServerNimAsyncContinue
[  888s]     ## Resumes an async procedure
[  888s]   tasyncssl.nim(45)   createServerIter
[  888s]   net.nim(661)        newContext
[  888s]   net.nim(575)        loadCertificates
[  888s]   net.nim(540)        raiseSSLError
[  888s] Exception message: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small
[  888s]  [SslError]
```

**Comment by kraptor** [comment]
I'm checking the CI errors...

**Comment by kraptor** [comment]
The latest CI issue is because it timeouts and it's cancelled for who knows what reason... Up to Nim developers what to do here.

**Comment by kraptor** [comment]
Do you mind to rerun the cancelled CI task, @dom96?

Thanks!

**Comment by ringabout** [comment]
> Do you mind to rerun the cancelled CI task

done

**Comment by kraptor** [comment]
Thanks @xflywind. It seems everything went well and it's ready to merge. :)

**Comment by metagn** [comment]
@narimiran can you backport this to 1.6? It might fix the current CI failure for linux amd64

**Comment by narimiran** [comment]
> @narimiran can you backport this to 1.6? It might fix the current CI failure for linux amd64

Backported now.

**Pull request merged**
