### PR TITLE
0 is valid fd on unix (if user closed stdin).  Also export handle so fs can be conserved.

### PR DESCRIPTION
**Pull request by c-blake**
The current code is broken if the caller closes stdin and then uses memfiles. The correct invalid fd should be -1.

Further, the handle should either be exported (or an API to close it and set it to -1 should be added).  Handles
aka file descriptors are a scarce resource on Unix, sometimes with default limits as low as 64.  Contrariwise, memory maps are not scarce (default limits usually in the many thousands) and there is no need to keep the handle open to use the mapped file.  The only need to keep the file open on unix that might arise in the future is resizing the file after the initial map.  Then you need an fd to call `ftruncate` to resize the file.  That feature is not currently supported, though - the file can be closed any time after the initial size setting.  So, at least for now we should allow releasing that file descriptor/handle.  I don't know about Windows constraints/default limits about these things, but this PR only impacts the unix side.

### CODE REVIEW

**Comment by c-blake** [comment]
I should perhaps also have mentioned, that the reason I simply exposed the handle and made it ok to manually close was that I don't think Windows has very tricky resource constraints to work around.  So, that branch probably doesn't need anything.  I'm not even sure if it's valid in Windows to have a live memory map on a closed file handle.  A Unix-only API call seemed, eh...Maybe nice, but not very necessary.  I'm happy to do it the API way if you prefer (say, a proc closeOnlyHandle()), but the basic feature/ability to not keep a bunch of fds allocated simply to have the memory maps alive is a pretty important one in Unix-land.

**Comment by napalu** [comment]
Good catch - in Windows it is also good practice to call ´CloseHandle´ as soon as possible. Closing the handle in Windows does not invalidate the mapped address range which remains valid until `UnmapViewOfFile` is closed. So best practice would be to close memory mapped handles right after mapping. Here's a relevant passage from MSDN https://msdn.microsoft.com/en-us/library/windows/desktop/aa366532(v=vs.85).aspx:

Quoting MSDN (bodl emphasis mine):

> When each process finishes using the file mapping object and has unmapped all views, it must close the file mapping object's handle and the file on disk by calling CloseHandle. **These calls to CloseHandle succeed even when there are file views that are still open.** However, leaving file views mapped causes memory leaks.

**Comment by c-blake** [comment]
Ok.  Then it sounds like we should maybe not export the file handle, but rather proactively close it in both branches (still using -1 on Unix for "invalid fd").  If the dynamic resizing after creation feature I mentioned ever gets added then `memfiles.open` can take an argument `allowResize=false` and only conditionally close the handles.  Then best practice/open file conservation is followed unless otherwise requested by the user (by a feature that needs it).  (As to why that feature needs it, at least on Unix, re-opening under the same path name is unreliable - file could be renamed or process could `chdir()`, etc.).

**Comment by Araq** [comment]
I don't mind your change, but you need to rebase against devel, it's all messed up to a point where I cannot even review your code.

**Comment by c-blake** [comment]
Sorry.  I messed up my rebase enough that it was easier to just trash all that, fork a new repo and PR against that.  So, there's a new PR with just one clean commit.  I'll just delete this version of the PR or you can if I don't.

**Pull request closed without merging**
