### PR TITLE
Refactor sizealignoffset, new improvements

### PR DESCRIPTION
**Pull request by krux02**
* ``computePackedObjectOffsetsFoldFunction`` and ``computeObjectOffsetsFoldFunction`` has been merged into one function (code normalization).
* The folding object ``OffsetAccum`` is now used more extensively (Simpler to read, less error prone to write).
* tsizeof is now enabled for c++ testing
* offset values for objects with inheritance now also works when compiling to c++ at compile time.
* fixed a bug that would cause problems with big enum sets on 32 bit platforms

### CODE REVIEW

**Comment by krux02** [comment]
I cannot reproduce the error from CI locally. On my system the failed test just passes with no problem at all. I am a bit worried about the state of local testing as https://github.com/nim-lang/Nim/issues/12053 shows another example where local testing and server testing diverges.

**Comment by krux02** [comment]
This PR is ready to be merged. The test failure is unrelated.

**Comment by krux02** [comment]
failing test is https://github.com/moigagoo/norm, this is an unrelated failure

**Comment by Araq** [comment]
Took over and merged it.

**Pull request closed without merging**
