### PR TITLE
[JS] Ref #15952 make toOpenArray works better

### PR DESCRIPTION
**Pull request by ringabout**
ref #15952 toOpenArray works better

### CODE REVIEW

**Comment by timotheecour** [comment]
@Araq I added a label `backport`, just remove that new label if you disagree; I think that's easier than having to specify it in commit msg since it allows decision to be made/unmade after a PR is merged; 
alternatively we can add 3 labels: backport_10, backport_20, backport_40 instead of backport

**Comment by Araq** [comment]
That's for @narimiran to decide as he is doing the backports.

**Comment by timotheecour** [comment]
I've removed the backport label from this PR in light of https://github.com/nim-lang/Nim/pull/17006 (but the label itself is still useful IMO, to tag whether or not to backport PR's)

**Comment by Araq** [comment]
The label is useful but more useful would be "backport-1.2" etc.

**Comment by timotheecour** [comment]
> The label is useful but more useful would be "backport-1.2" etc.

done, added those; only 1 need to be specified each time a backport is needed:
image

It looks like this PR was backported to 1.4.4, but we may need to revisit this for 1.4.6 because of https://github.com/nim-lang/Nim/pull/17006

> note that toOpenArray with var param doesn't seem to actually work (ie source data isn't mutated), so it's not clear that #17001 actually improved things (it turned an error into a silent non-mutation)

**Comment by narimiran** [comment]
Please continue to use commit messages containing `[backport*]` tag for stuff that needs to be backported.

These labels might be easier for y'all to tag, but harder for me to do backports. I'm removing them so we don't have stuff labeled, but without tag.

**Comment by timotheecour** [comment]
> Please continue to use commit messages containing [backport*] tag for stuff that needs to be backported.

the problem with commit messages is that it requires the decision to be made before the PR is merged; a label gives you more flexibility and hindsight since you can tag/untag after a PR is merged; in this case for example, it was discovered after the PR was merged that it causes an issue and probably shouldn't have been backported.

**Comment by Araq** [comment]
Sure but @narimiran is doing the work so we have to adapt. However, maybe there could be an official backport queue instead that lists commits to backport?

**Comment by metagn** [comment]
What's the followup needed label for?

**Pull request merged**
