### PR TITLE
nimgrep: add `--inContext` and `--notinContext` options

### PR DESCRIPTION
**Pull request by a-mr**
This feature allows to define filters for requiring to match additional patterns in the context of main match (possibly multi-line context).
For example `nimgrep --context:1 --inContext:PAT1 --notinContext:PAT2 "main match"` will match only occurrences like this:
```
...
... main match ...
... PAT1 ...
```
but not just
```
...
... main match ...
...
```
and not
```
... PAT1
... main match ...
... PAT2 ...
```

**UPD**: Changed name of filtering options. Added options `--parentPath` and `--notparentPath` (besides `--dirname` and `--notdirname` for completeness and logical correctness (previous 2 options `--includeDirectory` and `--excludeDirectory` were not mutually exclusive).

### CODE REVIEW

**Comment by Araq** [comment]
This looks very useful but the interface isn't intuitive. I wonder if we can come up with a better syntax/inferface.

**Comment by a-mr** [comment]
one of thing that currently looks a bit messy (it is my fault) is usage of `include`/`exclude` vs `match`/`noMatch`. 

1. May be we need to use only `include`/`exclude` but then we also need to change from `--match` (aka `--matchFile`) to something like `--includeContents`, etc.
2. Another possible development would be to introduce a `--not`=`-n` option that would convert its following option from positive filter to negative one. Then for each pair of options we will need only one option.

current PR | proposal 1 | proposal 2
-: | :-: | -:
`--matchFile`, `--mf` | `--includeContents` | `--fileContains`, `--fc`
`--noMatchFile`, `--nf` | `--excludeContents` | `--not --fileContains`, `-n --fc`
`--matchContext`, `--mc` | `--includeContext` | `--contextContains` `--cc`
`--noMatchContext`, `--nc` | `--excludeContext`| `--not --contextContains`, `-n --cc`
`--includeFile`, `--if` | same `--includeFile`| `--filenameContains`, `--nc`
`--excludeFile`, `--ef` | same `--excludeFile` | `--not ‑-filenameContains`, `-n --nc`
`--includeDir`, `--id` | same `--includeDir` | `--dirContains`, `--dc`
`--excludeDir`, `--ed` | same `--excludeDir` | `--not --dirContains`, `-n --dc`

cc @timotheecour @quantimnot

**Comment by quantimnot** [comment]
@a-mr

Here are some random brainstorms to also consider:

```
# positive
--contents
--contexts
--filename
--dirname
--ext

# negative
--!contents
--!contexts
--!filename
--!dirname
--!ext

# negative
--notContents
--notContexts
--notFilename
--notDirname
--notExt

# positive
--matchContents
--matchContexts
--matchFilename
--matchDirname
--matchExt

# negative
--!matchContents
--!matchContexts
--!matchFilename
--!matchDirname
--!matchExt

# negative
--notMatchContents
--notMatchContexts
--notMatchFilename
--notMatchDirname
--notMatchExt

# positive
--matchesContents
--matchesContexts
--matchesFilename
--matchesDirname
--matchesExt

# negative
--!matchesContents
--!matchesContexts
--!matchesFilename
--!matchesDirname
--!matchesExt

# negative
--notMatchesContents
--notMatchesContexts
--notMatchesFilename
--notMatchesDirname
--notMatchesExt
```

Possibly change the help menu so that all filter options are consolidated under
one group:
```
* Filter file selection:
  --contents:PAT     select files containing a match of PAT
  --!contents:PAT    skip files containing a match of PAT
  --contexts:PAT     select files containing a match of PAT in the surrounding
                     context (multiline with `-c`, `-a`, `-b`) of PATTERN
  --!contexts:PAT    select files containing a match of PAT in the surrounding
                     context (multiline with `-c`, `-a`, `-b`) of PATTERN
  --filename:PAT     select files whose name matches pattern PAT
  --!filename:PAT    skip files whose name matches pattern PAT
  --dirname:PAT      select files whose directory name matches pattern PAT
  --!dirname:PAT     skip files whose directory name matches pattern PAT
  --ext:EX1|EX2|...  select files whose extension matches the given extensions,
                     empty one ("--ext") means files with missing extension
  --!ext:EX1|EX2|... skip files whose extension matches the given extensions,
                     empty one ("--ext") means files with missing extension
  --bin:on|off|only  process binary files? (detected by \0 in first 1K bytes)
                     (default: on - binary and text files treated the same way)
  --text, -t         process only text files, the same as `--bin:off`
```

**Comment by a-mr** [comment]
@quantimnot ,

I used your suggestions for doing these changes (already implemented), PTAL:

before | after this PR
:- | :-
`--matchFile`, `--mf` | `--inFile`, `--inf`
`--noMatchFile`, `--nf` | `--notinFile`, `--ninf`
<br/> | `--inContext`, `--inc`**this PR topic**
<br/> | `--notinContext`, `--ninc` **this PR topic**
`--includeFile`, `--if` | `--filename`, `--fi`
`--excludeFile`, `--ef` | `--notfilename`, `--nfi`
`--includeDir`, `--id` | `--parentPath`, `--pa`\*
<br/> | `--notparentPath`, `--npa`**also added in this PR**
<br/> | `--dirname`, `--dirname`\* **also added in this PR**
`--excludeDir`, `--ed` | `--notdirname`, `--ndi`\*
`--ext` | `--extension`, `--ex`
`--noext` | `--notextension`, `--nex`
`--text` | the same `--text` + `--te`
`--bin:only` | ~~`--!text`, `--!te`~~

**UPD 12.05:** Changed `!` -> `not/n` and `contentsFile` -> `inFile`, removed `-!text`.

\* Here we resolve `--includeDir/--excludeDir` anomaly of not being mutually exclusive. Variant for positive "include 1 element of directory" was previously considered useless: it's obvious that `--excludeDir:'.git'` omits all directories containing `.git`, but it was not obvious what its positive case should mean. So `--includeDir` was the same as `--parentPath` — match for parent directory's path. But we **may** actually want the positive case, e.g. if we really do want to search in files like `path/to/.git/subpath/file` and here `--dirname:'.git'` will work.

And new `--!parentPath` may be useful also.

Also `!` can be substituted to `not` everywhere (it's difficult to type `\!` in conventional shells like bash & zsh)

I also edited the help page like you suggested, but making a separate section for `-inContext` options since they filter only matches, not whole files.

Personally I still have doubts: if always using `include`/`exclude` in the beginning, then at least we can understand that it's filtering options. Here we don't have such a clue.

Please say me your thoughts. 

Backward compatibility will be fully preserved, though only new variants are present in the help page.

**Comment by quantimnot** [comment]
@a-mr

> * Here we resolve --includeDir/--excludeDir anomaly of not being mutually exclusive. Variant for positive "include 1 element of directory" was previously considered useless: it's obvious that --excludeDir:'.git' omits all directories containing .git, but it was not obvious what its positive case should mean. So --includeDir was the same as --parentPath — match for parent directory's path. But we may actually want the positive case, e.g. if we really do want to search in files like path/to/.git/subpath/file and here --dirname:'.git' will work.

Can you clarify your desired behavior in a test for me? I added a test suite below.

> Also ! can be substituted to not everywhere (it's difficult to type \! in conventional shells like bash & zsh)

Hmm, I don't need to escape '!' in bash or zsh on my system.

> I also edited the help page like you suggested, but making a separate section for -inContext options since they filter only matches, not whole files.

I misunderstood the point of this PR. I thought the context filter was to select whether a file was used in the final results.

> Personally I still have doubts: if always using include/exclude in the beginning, then at least we can understand that it's filtering options. Here we don't have such a clue.

Regarding whether or not to use include/exclude, I have no personal preference. I was just giving some alternatives. We should just be as consistent as possible.

> Please say me your thoughts.

I see you have removed the `--bin` option. I think it should remain, because I would like to propose a change in another PR:
- search text by default
- remove `--text` and `--bin:off` options
- `--bin:on` becomes `--bin` to include binary files along with text files
- `--bin:only` remains the same to only search binary files

I want to make sure I understand the options and intended behaviors.
Linked is a start of a test suite for nimgrep. Maybe you can add it to this PR as `tests/tools/tnimgrep.nim`?
These test are not comprehensive. I've run out of time for now. Please change it however is needed.

https://gist.github.com/quantimnot/5d23b32fe0936ffc453220d20a87b9e2

**Comment by a-mr** [comment]
Exclamation ! is for history expansion by default in both bash and zsh. (https://zsh.sourceforge.io/Doc/Release/Expansion.html and https://www.gnu.org/software/bash/manual/html_node/History-Interaction.html). You must have turned it off in you system by using `set +H` in bash or by `setopt nobanghist` in zsh (or setting `histchars` variable in both).

Interestingly neither `nim rst2html` nor `rst2html.py` allow ! (or any punctuation) after `--` in option lists. So it's really atypical :-/

**Comment by a-mr** [comment]
@Araq PTAL.

Hopefully interface is more consistent and intuitive now. Also anomalies existed before have been fixed (without breaking compatibility).

**Comment by a-mr** [comment]
@Araq PTAL.

Hopefully interface is more consistent and intuitive now. Also anomalies existed before have been fixed (without breaking compatibility).

**Comment by Varriount** [comment]
@a-mr If you can resolve the conflicts, I can merge this.

**Comment by a-mr** [comment]
Thank you @Varriount 

I merged devel.

Also in the last commit i changed `--parentPath` to `--dirpath`, it seems more consistent.

**Pull request merged**
