### PR TITLE
better support for PROGMEM like annotations for lets/vars; fixes #12216

### LINKED ISSUE #12216: Produce static/const initializations for variables when possible
A top-level initialization in Nim produces C code which first declares the variable, then later assigns a value in the module's `Init` function.

This is troublesome for embedded programming, because there is no way to make a variable 'const' in the generated C code.

As a result, there is no sensible way to put an object/array in ROM and be able to take a pointer to it using `unsafeAddr`. See my [forum post](https://forum.nim-lang.org/t/5192) for why this is important.

### Example
The following Nim code:
```nim
type Point = object
  x, y: int

let foo* = Point(x:10, y:20)
```
currently leads to the following C code for our variable 'foo':
```c
// ...

tyObject_Point_R2WHeB5ABtUUFMDs9bCVSuA foo_pp3aIVrMTc9cwqFMF9btpcoQ;

// ...

N_LIB_PRIVATE N_NIMCALL(void, unknown_mymoduleInit000)(void) {
{
	nimZeroMem((void*)(&foo_pp3aIVrMTc9cwqFMF9btpcoQ), sizeof(tyObject_Point_R2WHeB5ABtUUFMDs9bCVSuA));
	foo_pp3aIVrMTc9cwqFMF9btpcoQ.x = ((NI) 10);
	foo_pp3aIVrMTc9cwqFMF9btpcoQ.y = ((NI) 20);
}
}
```

### Proposed Solution

After some further dicussion [on IRC](https://irclogs.nim-lang.org/17-09-2019.html#20:43:13), we decided that the best way to handle this would be to make the codegen for `let` smarter, so that it will produce a fully initialized global or static const in cases where that is possible.

In other words, the previous C code would become:
```c
const tyObject_Point_R2WHeB5ABtUUFMDs9bCVSuA foo_pp3aIVrMTc9cwqFMF9btpcoQ = { ((NI) 10), ((NI) 20) };
```

I believe this can be done for any top-level `let` variable as long as the initialization only contains the following:
- literals / constants
- addresses of other top-level variables / procedures
- `cast[]`, `sizeof`, and any other operations that are acceptable in a static initialization context

The same rules can apply to `var` too (though I suppose it's less important). The 'const' modifier should be omitted in that case.

However, the codegen should *not* be applied for any initialization that depends on the result of a procedure or the value of a variable at runtime.

#### Visibility/mutability rules
Nim code:
```nim
let a = 1
let b* = 2
var c = 3
var d* = 4
```
Desired C initializers:
```c
static const NI a_xxx = 1;
const NI b_xxx = 2;
static NI c_xxx = 3;
NI d_xxx = 4;
```

#### Using C-style arrays (pointer + size)
Nim code:
```nim
type AnimData = object
  loop: bool
  frames: ptr UncheckedArray[int]
  len: int

let walkFrames = [2,3,4]

let walkAnimation = AnimData(
  loop: true,
  frames: cast[ptr UncheckedArray[int]](unsafeAddr walkFrames),
  len: walkFrames.len
)
```
Desired C initializers:
```c
static const tyArray_xxx walkFrames_xxx = {((NI)2), ((NI)3), ((NI)4)};
static const tyObject_AnimData_xxx walkAnimation_xxx = {
	NIM_TRUE,
	(&walkFrames_xxx),
	((NI) 3)
};
```

#### Linked list of procedures
Nim code:
```nim
type Action = object
  body: proc () {.nimcall.}
  next: ptr Action

proc fn1() = echo "first"
proc fn2() = echo "second"

let second = Action(body: fn2, next: nil)
let first = Action(body: fn1, next: unsafeAddr second)
```
Desired C initializers:
```c
static const tyObject_Action_xxx second_xxx = { fn2_xxx, NIM_NIL };
static const tyObject_Action_xxx first_xxx = { fn1_xxx, (&second_xxx) };
```

### Other considerations
- This change may mess with some people's assumptions about the behavior of `unsafeAddr`. Currently `let` variables are still mutable under the hood, but with these changes that would not always be the case.
- I suspect this wouldn't play nicely with every imported C variable. (See the `EACCES` example in the [manual](https://nim-lang.org/docs/manual.html#implementation-specific-pragmas-nodecl-pragma)).
- It might be worth introducing some pragma to control which kind of codegen is used, in case you (a) really want to guarantee static const  (b) really want to avoid it

### PR DESCRIPTION
**Pull request by Araq**

### CODE REVIEW

**Comment by krux02** [comment]
How does this solve #12216? It doesn't implement any of the proposed solutions, nor does it mention anything why they were rejected.

**Comment by foldl** [comment]
> How does this solve #12216? It doesn't implement any of the proposed solutions, nor does it mention anything why they were rejected. On the other hand this solution wasn't discussed at all, at least not as far as I can tell.

This is just the best way mentioned in #12216:

> [To] make the codegen for `let` smarter, so that it will produce a fully initialized global or static const in cases where that is possible.

**Comment by krux02** [comment]
@foldl Regarding "[To] make the codegen for let smarter, so that it will produce a fully initialized global or static const in cases where that is possible.", As far as I can tell, this PR doesn't do that. I looked into the generated C code, and it doesn't emit a `const` for the requested let example. The test case also doesn't even use a `let` it explicitly tests for a mutable `var` that needs to not have a const. So I really don't understand how this PR does address the problem in #12216

**Comment by foldl** [comment]
@krux02 You are right. I am looking forward to `let`-ing the `const` be.

**Comment by foldl** [comment]
Armed with this PR, I am thrilled to find that it is so easy to add `const` in the generated code, and 
can't help to create a PR (#12824). :)

**Pull request merged**
