### PR TITLE
Fix symlinks switch

### PR DESCRIPTION
**Pull request by dkgitdev**
Well, I've debugged it to the point it allows to compile and use logging.

As the switch has no symlink support, there is no option to import those from header file. So I've cut them out.

And the Application name is a pain as well, but since switch has almost no use of direct syslog usage, the stub should do the trick.

### CODE REVIEW

**Comment by dkgitdev** [comment]
BTW, tell me if it's wrong branch or something :)

**Comment by planetis-m** [comment]
Thanks for your PR, @dkgitdev! Please use the devel branch instead.

**Comment by dkgitdev** [comment]
@planetis-m 

I've tried to build devel branch but failed.

I'm successfully built Nim comipler:
```
$ ./koch boot -d:release
iteration: 1
bin/nim c  --skipUserCfg --skipParentCfg -d:nimKochBootstrap --nimcache:nimcache/r_linux_amd64 -d:release --noNimblePath --compileOnly compiler/nim.nim
Hint: used config file '/home/dk/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/dk/Nim/config/config.nims' [Conf]
Hint: used config file '/home/dk/Nim/compiler/nim.cfg' [Conf]
...............................................................................................................................................................................................................................................
/home/dk/Nim/compiler/vmops.nim(41, 1) Hint: duplicate import of 'strutils'; previous import here: /home/dk/Nim/compiler/vm.nim(15, 6) [DuplicateModuleImport]
.....................................................................
Hint: mm: orc; opt: speed; options: -d:release
166072 lines; 5.008s; 611MiB peakmem; proj: /home/dk/Nim/compiler/nim.nim; out: /home/dk/Nim/nimcache/r_linux_amd64/nim.json [SuccessX]
bin/nim jsonscript --noNimblePath --nimcache:nimcache/r_linux_amd64 -d:release compiler/nim.nim
Hint: used config file '/home/dk/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/dk/Nim/config/config.nims' [Conf]
Hint: used config file '/home/dk/Nim/compiler/nim.cfg' [Conf]
iteration: 2
compiler/nim1 c  --nimcache:nimcache/r_linux_amd64 -d:release --noNimblePath --compileOnly compiler/nim.nim
Hint: used config file '/home/dk/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/dk/Nim/config/config.nims' [Conf]
Hint: used config file '/home/dk/Nim/compiler/nim.cfg' [Conf]
...............................................................................................................................................................................................................................................
/home/dk/Nim/compiler/vmops.nim(41, 1) Hint: duplicate import of 'strutils'; previous import here: /home/dk/Nim/compiler/vm.nim(15, 6) [DuplicateModuleImport]
.....................................................................
Hint: mm: orc; opt: speed; options: -d:release
166072 lines; 4.934s; 611MiB peakmem; proj: /home/dk/Nim/compiler/nim.nim; out: /home/dk/Nim/nimcache/r_linux_amd64/nim.json [SuccessX]
compiler/nim1 jsonscript --noNimblePath --nimcache:nimcache/r_linux_amd64 -d:release compiler/nim.nim
Hint: used config file '/home/dk/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/dk/Nim/config/config.nims' [Conf]
Hint: used config file '/home/dk/Nim/compiler/nim.cfg' [Conf]
executables are equal: SUCCESS!
``` 

But when I  try to build my switch static lib, I get this:
```
$ nimble build_device_test
  Executing task build_device_test in /home/dk/PycharmProjects/toggleNx/toggleNx.nimble
Building: /home/dk/PycharmProjects/toggleNx/src/toggleNx/deviceTest/c.nim...
Building static lib file...
switch_build.nim(61)     execProc
Error: unhandled exception: Command failed: 1
CMD: nim  --out=build/c/libc.a --nimcache=nimcache/c --passL='  -specs=/opt/devkitpro/libnx/switch.specs -L/opt/devkitpro/libnx/lib -lnx' --passC=' -I/opt/devkitpro/libnx/include' --app:staticlib --noMain  c --os:nintendoswitch /home/dk/PycharmProjects/toggleNx/src/toggleNx/deviceTest/c.nim
RESULT: Hint: used config file '/home/dk/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/dk/Nim/config/config.nims' [Conf]
Hint: used config file '/home/dk/PycharmProjects/toggleNx/nim.cfg' [Conf]
.........................................................
/home/dk/Nim/lib/system/alloc.nim(767, 5) template/generic instantiation of `atomicPrepend` from here
/home/dk/Nim/lib/system/alloc.nim(758, 18) template/generic instantiation of `storea` from here
/home/dk/Nim/lib/system/alloc.nim(140, 36) Error: undeclared identifier: 'atomicStoreN'
candidates (edit distance, scope distance); see '--spellSuggest': 
 (4, 3): 'atomicStatDec'
 (4, 3): 'atomicStatInc'
 [Exception]
stack trace: (most recent call last)
/tmp/nimblecache-334211879/nimscriptapi_3780686481.nim(187, 16)
/home/dk/PycharmProjects/toggleNx/toggleNx.nimble(34, 3) build_device_testTask
/home/dk/Nim/lib/system/nimscript.nim(264, 7) exec
/home/dk/Nim/lib/system/nimscript.nim(264, 7) Error: unhandled exception: FAILED: switch_build -S src/toggleNx/deviceTest/c.nim [OSError]
       Tip: 1 messages have been suppressed, use --verbose to show them.
     Error: Exception raised during nimble script execution
```

Here's the cfg I'm using for my nintendo proj:
```
--mm:orc
--d:nimAllocPagesViaMalloc
--define:nimInheritHandles
--nimcache:cache
--outdir:build
```

What should I do? Is this ok?

**Comment by planetis-m** [comment]
Well as the error message mentions a recent refactoring has broken alloc.nim when switch is active. Try to find the commit from git blame and the line info to know how it may be fixed. Good luck!

**Comment by dkgitdev** [comment]
Okay, reopening it here: https://github.com/nim-lang/Nim/pull/21368.

@planetis-m could you take a look when you have time: everything should be nice this time :)

**Pull request closed without merging**
