### PR TITLE
contentLength default to -1 if not present

### LINKED ISSUE #16770: httpclient contentLength error when missing
# Examples

```nim
import httpclient
let client = newHttpClient()  # OK
let rspons = client.head("http://google.com")  # OK
echo rspons.contentLength  # BUG
```

# Current Output

```nim
$ nim r example.nim
nim-#devel/lib/pure/httpclient.nim(248) contentLength
nim-#devel/lib/pure/strutils.nim(1073) parseInt
Error: unhandled exception: invalid integer:  [ValueError]

$
```

- This is a `parseInt` error.

 
# Expected Output

I see 2 options, if `contentLength` is missing:

- Return `0`.
- Return a better specific error message instead of a `parseInt` error, [`httpclient` has specific errors already](https://nim-lang.github.io/Nim/httpclient.html#HttpRequestError).

# Additional Information

- Repro on any version of Nim, should be kinda easy to fix.
- HTTP Standard says is Ok for `contentLength` to be missing.

# System Information

<details>

```json

{
  "compiled": "2021-01-18T00:58:04",
  "NimVersion": "1.5.1",
  "hostCPU": "amd64",
  "hostOS": "linux",
  "cpuEndian": "littleEndian",
  "getTempDir": "/tmp/",
  "now": "2021-01-20T14:42:58-03:00",
  "getCurrentEncoding": "UTF-8",
  "getFreeMem": 401408,
  "getTotalMem": 528384,
  "getOccupiedMem": 96064,
  "countProcessors": 4,
  "arch": "x86_64",
  "FileSystemCaseSensitive": true,
  "nimcacheDir": "/home/juan/.cache/nim/nimbug_r",
  "ccompilerPath": "",
  "currentCompilerExe": "/home/juan/.choosenim/toolchains/nim-#devel/bin/nim",
  "nimpretty": "0.2",
  "nimble": "nimble v0.12.0 compiled at 2021-01-20 01:09:43\ngit hash: couldn't determine git hash",
  "nimgrep": "1.6.0",
  "nimsuggest": "Nim Compiler Version 1.5.1 [Linux: amd64]\nCompiled at 2021-01-20\nCopyright (c) 2006-2021 by Andreas Rumpf\n\ngit hash: fbdf3f2cebc4d492b458cecfad1f19fdd1375f5a\nactive boot switches: -d:release -d:danger --gc:markAndSweep",
  "choosenim": "choosenim v0.7.4 (2020-10-20 17:30:52) [linux/amd64]",
  "gcc": "gcc (GCC) 10.2.0",
  "clang": "clang version 11.0.1",
  "git": "2.30.0",
  "node": "v15.6.0",
  "python": "3.9.1",
  "ssd": true
}
```

</details>

# Proposed Labels

```csv
httpclient
```

### PR DESCRIPTION
**Pull request by bung87**
fix https://github.com/nim-lang/Nim/issues/16770

### CODE REVIEW

**Comment by Varriount** [comment]
Please add a changelog entry. What was the previous behavior?

**Comment by bung87** [comment]
> Please add a changelog entry. What was the previous behavior?

prevousely cause ValueError when goes into parseInt, I'll write the changelog

**Comment by Varriount** [comment]
Oh, and this behavior also needs to be documented. And.. I'm not sure if this breaks backwards compatibility or not? Perhaps a better value to return here would be `0`, rather than -1. What behavior do other libraries (in other languages) have for this case?

**Comment by bung87** [comment]
> Oh, and this behavior also needs to be documented. And.. I'm not sure if this breaks backwards compatibility or not? Perhaps a better value to return here would be `0`, rather than -1. What behavior do other libraries (in other languages) have for this case?

you can check the issue comments , I've found three std libs in different languages default to -1, so I pick this solution.

**Comment by bung87** [comment]
> Please add a changelog entry. What was the previous behavior?

which changelog file should be written ? I got `changelogs/changelog_1_6_0.md`, changelog.md `# v1.8.x - yyyy-mm-dd` in this old branch.

**Comment by Varriount** [comment]
https://github.com/nim-lang/Nim/blob/devel/changelog.md#v18x---yyyy-mm-dd

Also, which standard libraries return a length of "-1"?

**Review by Varriount — APPROVED** [review]

**Pull request merged**
