### PR TITLE
fix #19335 Disallow void in type section

### LINKED ISSUE #19335: void type allowed in type definitions, use leads to compiler error
For some reason it is possible to use the void type for object fields. It is impossible to initialize, but using it as a type on var works. An attempt to use it will result in a compiler error.

Example:
```nim
type
  MyType = object
    a: void

var o: MyType
o.a
```
Output:
```
Error: internal error: genRecordField 3 MyType
```

### PR DESCRIPTION
**Pull request by SirOlaf**
Fixes #19335

Edit: Other option would be having the field disappear like with generics but that seems confusing

### CODE REVIEW

**Comment by Araq** [comment]
No, what we should do instead is to map `void` to some `Unit`-like type and optimize it away in the backends.

**Comment by SirOlaf** [comment]
Would that actually address the issue with using a field typed as void and is there a good reason to allow typing a field as void in the first place

**Comment by Araq** [comment]
In the example it makes no sense but for 

```
type G[T] = object
  x: T

G[void]
```

**Comment by SirOlaf** [comment]
Yeah that is the case that makes fields disappear, and it continues to work

**Comment by SirOlaf** [comment]
Actually this presents the question why void can't be modeled as an empty object instead of a special case
```nim
type VoidType = object
```

Edit: Rust seems to do it that way and it allows cool stuff like saying `Set<Key> = Map<Key, ()>` (https://doc.rust-lang.org/nomicon/exotic-sizes.html#zero-sized-types-zsts), but getting that to work seems a lot more involved

**Comment by arnetheduck** [comment]
`typeof(G[void]().x)` should still work in the above example - it's useful in generic code to not have to introduce a special case for void, often

**Comment by SirOlaf** [comment]
That never worked because as I said it makes the fields disappear completely https://play.nim-lang.org/#ix=4dGQ

Edit: Specifically here https://github.com/nim-lang/Nim/blob/devel/compiler/semtypinst.nim#L208

**Comment by Araq** [comment]
> Edit: Rust seems to do it that way and it allows cool stuff like saying Set<Key> = Map<Key, ()> 

Nim had that before Rust, see e.g. `CritbitTree[void]`.

**Comment by arnetheduck** [comment]
> That never worked 

too bad - makes for a good feature request :)

**Pull request closed without merging**
