### PR TITLE
decrease iteration count of btree test

### PR DESCRIPTION
**Pull request by bung87**

### CODE REVIEW

**Comment by ringabout** [comment]
How much is the reduced time? It would be better if we could get statistics of sorting the tests by used time.

**Comment by bung87** [comment]
> How much is the reduced time? It would be better if we could get statistics of sorting the tests by used time.

it takes 190s on my windows i7 intel 12th 12700f

**Comment by ringabout** [comment]
Since we switched to ORC recently, you probably need to compare it with `refc` in case of performance regression.

**Comment by bung87** [comment]
> Since we switched to ORC recently, you probably need to compare it with `refc` in case of performance regression.

that's another problem, here it is because this test port from original module main entry , it is not meant to be tested often. the big iteration count doesn't affect corretness.

**Pull request merged**
