### PR TITLE
remove compiler/strutils2.nim

### PR DESCRIPTION
**Pull request by bung87**

### CODE REVIEW

**Comment by ringabout** [comment]
Benchmarks on multiple platforms?

**Comment by bung87** [comment]
it has been done in https://github.com/nim-lang/Nim/pull/16193

**Review by ringabout — DISMISSED** [review]
Please adapt this test case https://github.com/timotheecour/vitanim/blob/master/testcases/t10332d.nim to show whether the results actually change. Statistics are preferred. Thanks.

**Comment by bung87** [comment]
I've done locally, the additional call and assign cause slower, after refactor it is faster, well, it's bit op should faster in general.

**Comment by bung87** [comment]
CI fails unrelated.

**Comment by Araq** [comment]
This **undoes** the "always write" optimization! But even if you're right does the compiler even use `strutils2.toLowerAscii` in critical places?

**Comment by bung87** [comment]
the idea is keep same implementation with std strutils, it doen't used in critical places, also I can change to "always write" version, no matter what the optimization is.

**Comment by Araq** [comment]
Just remove compiler/strutils2.nim instead.

**Comment by bung87** [comment]
fails on nimsuggest on osx

**Comment by bung87** [comment]
@Araq ready for merge

**Pull request merged**
