### PR TITLE
RST: improve line blocks

### PR DESCRIPTION
**Pull request by a-mr**
Nim RST only preserves newlines in line block lines when it's it's not empty.
According to RST spec :
1. empty lines should be respected also
2. indentation in line blocks should be preserved.

Particularly point 1. is important since it's the official way to insert extra space between paragraphs:
```
Paragraph 1

|

Paragraph 2
```

This PR makes an example from RST spec be processed properly:
```
| A one, two, a one two three four
|
| Half a bee, philosophically,
|     must, *ipso facto*, half not be.
| But half the bee has got to be,
|     *vis a vis* its entity.  D'you see?
|
| But can a bee be said to be
|     or not to be an entire bee,
|         when half the bee is not a bee,
|             due to some ancient injury?
|                              
| Singing...
```
image

cc @narimiran

### CODE REVIEW

**Comment by timotheecour** [comment]
can edit your PR description to add the rendering before and after your PR?

**Comment by a-mr** [comment]
> can edit your PR description to add the rendering before and after your PR?

yes, please

**Comment by timotheecour** [comment]
I meant "can you edit"; anyhow here it is:
## before
image

## after
image

**Comment by a-mr** [comment]
> I meant "can you edit"; anyhow here it is:
> 

OK, i will do in future PRs :-)

**Pull request merged**
