### PR TITLE
convenience procs for db_mysql [#3217]

### PR DESCRIPTION
**Pull request by Senketsu**
Since i'm working on a project that use mysql quite alot and i noticed this (#3217) issue, here is a pull request.
Made this convenience procs , dunno if its what you imagined.

[Please don't mind my spelling.]
Cheers

### CODE REVIEW

**Comment by Araq** [comment]
This is getting out of hand, 3 different row types? Perhaps your extensions should be in a separate module and it cannot be, modify db_mysql so that it can be.

**Comment by Senketsu** [comment]
Something like this ?

**Comment by Araq** [comment]
Yes. Now make it a Nimble package and move it out of the stdlib please. :-)

**Comment by Senketsu** [comment]
[Don't merge yet]

**Comment by Senketsu** [comment]
canceling pull request

**Pull request closed without merging**
