### PR TITLE
Refac of lists module

### PR DESCRIPTION
**Pull request by GULPF**
This is subjective of course, but I dislike how many `{.dirty.}` templates are used in the standard library. I made an attempt to refactor the lists module to use type classes instead (where possible). It's less code, less duplicated doc comments, and (imo) more readable.

### CODE REVIEW

**Comment by GULPF** [comment]
I used `Some*` because that's what used for the other OR type classes in yhe stdlib. E.g `SomeNumber`, `SomeOrdinal` etc.

**Comment by Araq** [comment]
Not worth it IMO. This whole module will be deprecated.

**Comment by dom96** [comment]
>This whole module will be deprecated.

Why?

**Comment by yglukhov** [comment]
I'm using this module, whats the alternative? I think it has to be developed further.

**Pull request merged**
