### PR TITLE
bugfix. fix #9453 db_mysql/db_sqlite fails on with '?' in query without arguments.

### LINKED ISSUE #9453: db misses an API to precompile the query and bind data later.
dbFormat is used to substitute the param values. 
the question mark (?) is matched on the entire sql-string instead
of binding by the database. This would harden the API and the
database is able to cache the (already parsed) prepared statements.
At the moment the database does a hard-parse  on every invocation.

#### example for sqlite3 to demonstrate the issue:
```nim
import db_sqlite

const create_table1_sql = sql"""
create table if not exists ttab(
  id integer primary key,
  question text,
  answer text
);"""

const insert_sql = sql"""
insert into ttab (id,question,answer) values (?,'how do you do ?',?)
 """

let db = open(":memory:","","","") 
db.exec(create_table1_sql)
db.exec(insert_sql,1,"fine!") # index out of bounds is raised here
db.close

#[ runtime outcome is:
  db_sqlite.nim(139)       exec
  db_sqlite.nim(129)       tryExec
  db_sqlite.nim(119)       dbFormat
  system.nim(2939)         sysFatal
  Error: unhandled exception: index out of bounds [IndexError]
]#
```

#### Solution:
DbType already present within db_common.nim; for db_postres.nim
there is also a "prepare" proc already present but
unfortunately the parameter dbType is missing.

The API could be extended a little bit (introduce new procs without affecting the 
present API) so that the caller is able to promote the dbTypes. 
Or introduce a preparedStatement object (better solution I think) and bind the values like this:  ps.setString(1,"fine!")
Binding (driver layer) would be not that difficult then.

### Additional Information

this affects the entire db-driver layer.

Discussion can be found here:
https://forum.nim-lang.org/t/4320

related discussion here
https://github.com/nim-lang/Nim/issues/5768

also in the past some issues relating this problem
bubbled up:
https://github.com/nim-lang/Nim/issues/3328
https://github.com/nim-lang/Nim/issues/6571

### PR DESCRIPTION
**Pull request by muxueqz**

### CODE REVIEW

**Comment by Araq** [comment]
Why does the query contain '?' and no parameters? That simply hides bugs.

**Comment by muxueqz** [comment]
@Araq 
I wrote 'import sql' program, this sql have `?`

**Comment by Araq** [comment]
If your query contains a ``?`` that is not replaced by an actual parameter, the query is wrong.

**Comment by muxueqz** [comment]
@Araq 
but , [Postgres](https://github.com/nim-lang/Nim/blob/devel/lib/impure/db_postgres.nim#L100) is support `?`

My "import sql" program like 'mysql < file.sql', 
'file.sql' from `mysqldump > file.sql`

**Comment by krux02** [comment]
I guess Araq would be fine if you would support to escape the `?` so it won't consume an argument.

**Pull request closed without merging**
