### PR TITLE
Fix links in os module document

### PR DESCRIPTION
**Pull request by demotomohiro**

### CODE REVIEW

**Comment by timotheecour** [comment]
@demotomohiro how about using `idx` instead, with the expectation that we'll fix  #9477 to make it more useful

**Comment by demotomohiro** [comment]
I tried ``idx`` but it doesn't make a link.
I don't know when #9477 will be fixed, but if it is not fixed in next release, people read os module documents without links.
If so, how about to merge this PR temporaliry and fix links with ``idx`` after #9477 fixed?

**Comment by rayman22201** [comment]
Well, #9477 doesn't fix this problem directly. It will make idx searchable, but will not turn idx nodes into links.
Rendering the idx nodes as a link *seems* fairly easy, but where do we want the link to point to? the index (easy) or the actual doc for the function (hard)?

**Comment by timotheecour** [comment]
a few options;
clicking on 
```
`setFilePermissions`:idx:
```
could pop up the search with `"mode:exact setFilePermissions"` which would work well if it's overloaded (or just `"setFilePermissions"` until https://github.com/nim-lang/Nim/issues/9431 works)

another option is to directly link to 1st entry in that list (pre-computed href)

**Comment by rayman22201** [comment]
> another option is to directly link to 1st entry in that list (pre-computed href)

This is ideal imo, because doc links should not rely on the search (the docs should still work with javascript disabled).
But this is hard atm, because there is not enough information in the idx node to compute the link location, especially if the idx reference points to a function in a different module.
The rst parser would have to be modified to provide the corresponding source node for the idx reference node. This is hard.

@timotheecour you are giving me feature creep heartburn lol

**Comment by timotheecour** [comment]
at doc generation time (which is run by CI) any `setFilePermissions:idx:` symbol should resolve, otherwise we can make `nim doc` give an error (and the CI is not green) ; this would guarantee idx links are always kept in sync with code

for out of module references, isnt' theindex.json sufficient? (and if ambiguity, require to prefix symbol via module, eg: `os.setFilePermissions:idx:` )

**Comment by Araq** [comment]
Needs a better, more general solution. Sorry.

**Pull request closed without merging**
