### PR TITLE
Fix docs

### PR DESCRIPTION
**Pull request by Clyybber**

### CODE REVIEW

**Comment by timotheecour** [comment]
need to try this on user docs with sub dirs; please hold on

**Comment by timotheecour** [comment]
ok this indeed breaks user docs when there are subdirs eg:

nim doc --project --outdir:/tmp/d35 main.nim
```nim
# main.nim:
import sub/fun.nim

# sub/fun.nim:
proc baz*() = discard
```
=> will break css for /tmp/d35/sub/fun.html since it'd now point do /tmp/d35/sub/nimdoc.out.css

**Comment by kaushalmodi** [comment]
Can the base href somehow help us here? https://html.com/attributes/base-href/

We probably need to pass the base href via some switch to `nim doc`.

**Comment by timotheecour** [comment]
note : in the meantime, until a fix is found, latest release docs can be used:

* https://nim-lang.github.io/Nim/lib.html broken (latest devel)
* https://nim-lang.org/docs/lib.html  works (latest release)

**Comment by Clyybber** [comment]
@timotheecour Afaict, this is still better than the status quo, so I guess we should merge this and then try the approach @kaushalmodi lined out.

**Comment by timotheecour** [comment]
ok go for it, we can do another PR to fix user docs later

**Comment by kaushalmodi** [comment]
I agree, hard-coding `/` in the href is not a good idea.

**Comment by Clyybber** [comment]
@timotheecour @kaushalmodi Are you on gitter?

**Pull request merged**
