### PR TITLE
allow generic typedesc field access

### PR DESCRIPTION
**Pull request by dumjyl**
```nim
type Foo[T] = object
  val: T
echo sizeof Foo[int].val # undeclared field: 'val'
```

### CODE REVIEW

**Comment by dumjyl** [comment]
appveyor passed here: https://ci.appveyor.com/project/Araq/nim/builds/27574946

**Comment by cooldome** [comment]
Looks good to me. Though someone with better generic type knowledge should have a look

**Comment by Araq** [comment]
The compiler refactoring looks nice but ``Foo[int].val`` is not a type! This example should be

```nim

var x: typeof(Foo[int].val)
```

Whether that works with today's compiler or not I don't know... :-)

**Comment by Clyybber** [comment]
OTOH `Foo.val` already is treated as a type in current nim.

**Comment by krux02** [comment]
How about this:

```nim
type Foo[T] = object
  val: T

echo sizeof default(Foo[int]).val # undeclared field: 'val'
```

It already works.

**Comment by dumjyl** [comment]
> Whether that works with today's compiler or not I don't know... :-)

It works today in the sense that `typeof(typedesc)` is a nop.

> How about this:
> 
> ```nim
> type Foo[T] = object
>   val: T
> 
> echo sizeof default(Foo[int]).val # undeclared field: 'val'
> ```
> 
> It already works.

Not actually blocked on this, the `Obj.field` syntax doesn't add anything that some combination of `typeof` and `default` don't provide, its just a shorthand I find convenient. This PR was more from the perspective of one less half implemented feature.

Anyway, I don't agree with enforcing `typeof` (beyond a style guide). I'm using `typedesc` because I want to work with types.

I'm in favor keeping things how they are + this PR. No code breaks, no one has to implement the changes. If this syntax is really that awful and we would break backwards compatibility with a change, then I would rather deprecate it entirely and leave it up to `typeof` + `default`.

**Comment by krux02** [comment]
> I'm in favor keeping things how they are + this PR. No code breaks, no one has to implement the changes. If this syntax is really that awful and we would break backwards compatibility with a change, then I would rather deprecate it entirely and leave it up to typeof + default.

I am not entirely sure what you want to deprecate, but ``typeof`` + ``default`` seems to be already everything what we need. Allowing ``MyType.field`` could have potential bad side effects. Please don't enable it.

**Comment by dumjyl** [comment]
> Please don't enable it.

It's been enabled for years.
```nim
type MyType = object
  field: int

echo MyType.field
echo default(MyType.field)
```

**Comment by Clyybber** [comment]
@krux02 Counterargument: When `MyType.field` is not a type, neither a value, what is it then?
Araq argues its "nothing", but I feel like that just complicates semantics further with `typeof(MyType.field)`.

**Comment by Araq** [comment]
> but I feel like that just complicates semantics further with typeof(MyType.field).

Yes, but ``typeof(default(MyType).field)`` is what should be used. We don't need more quirks, we need fewer.

**Comment by Araq** [comment]
Please rebase. Deprecating this feature altogether might be a good idea but should be an RFC. So for now this counts as "bugfix", so please rebase.

**Pull request merged**
