### PR TITLE
 low/high for float ranges 

### LINKED ISSUE #9897: low/high does not work for range float types
```
var a:range[-1..1]
echo a.low  # => -1
echo a.type.low # => -1

var b:range[-1f..1f]  
echo b.low  # Error "invalid argument for: low"
echo b.type.low # " Error "conversion from float to range -1.0..1.0(float32) is invalid"
```

### PR DESCRIPTION
**Pull request by GULPF**
Fixes #9897

### CODE REVIEW

**Comment by GULPF** [comment]
> There are firstFloat/lastFloat as equivalents for firstOrd/lastOrd

Fixed

> These should work for distinct too

Do you mean e.g `distinct range[-1'f..1.0'f]`? The new code in semfold should handle distinct, but it might be tricky to make it work in system.nim. I don't know how to make a high/low overload that matches distinct float ranges without involving concepts.

**Comment by Araq** [comment]
Why should it work for ``distinct float``? A distinct float is not a float.

**Comment by Clyybber** [comment]
@JasperJenkins It shouldn't work for distinct integers either, so that's a misfeature/bug IMO.

**Comment by krux02** [comment]
I am against this feature, simply because float ranges are not practical. For all my experience in computer graphics where I work a lot with float ranges, they need an exclusive upper bound. An inclusive upper bound for float ranges is a can of worms, something that will cause subtile problems everywhere. If we start with float ranges somewhere in the code and expose those types in the standard library, people will use it, see the problems with it and report the problems with it. Problems that might even be unfixable. So please don't merge this.

**Comment by GULPF** [comment]
@krux02 This PR doesn't introduce float ranges, they where introduced by @cooldome last year and are even included in the 0.19.x versions. Feel free to reject the PR, but then float ranges should be removed from the language imo. Why have a feature if improvements to it are rejected.

**Comment by krux02** [comment]
I too a deeper look in the diff. Aparently this diff doesn't expose any float ranges in the standard library. I guess as long as the float ranges are a secret and not exposed anywhere it is OK, to not raise a compilation error or something like that. But I would be more happy, if float ranges are put under an experimental feature flag.

**Comment by Araq** [comment]
> For all my experience in computer graphics where I work a lot with float ranges, they need an exclusive upper bound. 

Oh not this again. There is no such thing as an "exclusive" range on a machine that operates on concrete bits, an exlusive range is not even constructive mathematics, it cannot possibly affect programming. The only reason why ``0..<x.len`` is everywhere is due to the silly 0-based indexing that also makes no sense whatsoever but we're stuck with it for historical reasons.

**Comment by krux02** [comment]
> silly 0-based indexing:

I let your subjective opinion judge with code looks cleaner.
```nim
const width = 64
const height = 64
const depth = 64

# for 0 based arrays

proc flatIndex(x,y,z: int): int =
  z * width * height + y * width + x

proc toCoords(idx: int): tuple[x,y,z: int] =
  result.x = idx mod width
  result.y = (idx div width) mod height
  result.z = (idx div width) div height # mod depth if repeating is wanted

# for 1 based arrays

proc flatIndex(x,y,z: int): int =
  z * width * heigh + y * width + x - width - width * heigh

proc toCoords(idx: int): tuple[x,y,z: int] =
  result.x = (idx-1) mod width + 1
  result.y = ((idx-1) div width) mod height + 1
  result.z = ((idx-1) div width) div height + 1
```

**Comment by Araq** [comment]
> I let your subjective opinion judge with code looks cleaner.

Firstly, you wrote this in a convoluted fashion in order to have a point. Secondly, whether "it looks clean" is not a mathematical argument at all. You cannot even model probabilities like 0.0 .. 0.1 with your exclusive range bullshit.

**Pull request merged**
