### PR TITLE
Changes for FreeRTOS/LwIP Port for the ESP32 (ESP-IDF)

### PR DESCRIPTION
**Pull request by elcritch**
Adding FreeRTOS/LwIP to compiler:

* adding freertos option
* dyncalls for freertos
* add freertos to posix os list
* adding lwip option

Setting up networking FreeRTOS/LwIP Port:

* setting up lwip network for freertos
* fixing posix / networking for freertos
* disable setInheritable for freerots
* using lwip for net control items

### CODE REVIEW

**Comment by elcritch** [comment]
@Araq I finally got my changes for the FreeRTOS/LwIP port cleaned up and squashed. 

This includes the changes required to build for FreeRTOS. Those changes are fairly minor, mostly adding compiler options for FreeRTOS. Not all Nim standard libraries will work with FreeRTOS, particularly those dealing with files and signals. 

The LwIP changes are more extensive. Mostly they're similar to the regular POSIX but there are enough changes and missing items that I opted to duplicate the POSIX bindings. I figure these are stable enough that it'll easy maintenance for LwIP. 

I'm not sure how or where to add documentation, though I could add some where it's appropriate. It'd be great to have builds & tests or at least a cross-compiles, but I don't have bandwidth for that. Though a few others seemed interested in the port, so if this is upstreamed, others might be able to help with that.

**Comment by Araq** [comment]
I'm merging this. In a follow-up PR please document it a bit here: https://nim-lang.org/docs/nimc.html#nim-for-embedded-systems

**Comment by mfiumara** [comment]
Any examples on how to build a sample application for freeRTOS?

**Comment by elcritch** [comment]
I haven't gotten to a PR for it yet, but essentially you just pass `--os:freertos`. However, I haven't tried building it for "generic" FreeRTOS yet. It's largely dependent upon the micro-controller SDK's build system, some use cmake, makefiles, eclipse, etc. 

Here's a sample of what I do for the ESP32 using the ESP-IDF by Espressif: 

https://github.com/elcritch/nesper/blob/master/esp-idf-examples/simplewifi/config.nims

The basic route is to compile your Nim application to C code upfront using `--compileOnly --nimcache:src/nimcache/`. Then you link that into your micro-controllers build system. 

For the ESP32, this is done by [adding the nimcache folder](https://github.com/elcritch/nesper/blob/e1d9f7ba13eebe45aea43c08fe839dd0544927c2/esp-idf-examples/simplewifi/main/CMakeLists.txt#L2).

**Pull request merged**
