### PR TITLE
fixes #20015; document `shallowCopy` does a deep copy with ARC/ORC

### LINKED ISSUE #20015: shallowcopy string doesn't work with arc/orc
```nim
type RotatedString* = object
  underlying: string
  shift: int

proc rotate*(s: var string, i: int): RotatedString =
  result = RotatedString(shift: i)
  shallowCopy(result.underlying, s)
  # prepareMutation(result.underlying)

proc `[]=`*(r: var RotatedString, i: int, c: char) {.inline.} =
  # when defined(gcArc) or defined(gcOrc):
  #   prepareMutation(r.underlying)
  let L = r.underlying.len
  assert 0 <= i and i < L
  let s = i + r.shift
  if s < L:
    r.underlying[s] = c
  else:
    r.underlying[s - L] = c


var
  x = "Hello, world"
  y = x.rotate(5)

y[0] = 'f'
doAssert x[5] == 'f'
```

ref https://github.com/nim-lang/Nim/pull/19972

### PR DESCRIPTION
**Pull request by ringabout**
fixes #20015

image

### CODE REVIEW

**Comment by arnetheduck** [comment]
@Araq is this the long-term plan, that `shallowCopy` is broken from ARC/ORC? ie this is a significant semantic change - if it is the case, it should really be deprecated / removed-when-arc instead - these  bugs will be incredibly hard to find

**Comment by Araq** [comment]
Yes, you're right. We should simply remove it from system.nim for --mm:orc. 

(You're supposed to use `x = move y` instead if the compiler does not know a move is valid.)

**Comment by arnetheduck** [comment]
> (You're supposed to use x = move y instead if the compiler does not know a move is valid.)

this is semantically different: a shallow copy allows (mutable) aliasing (in an unhealthy way, I'd argue, but this is a different story) - so the two are not .. equivalent - that said, good riddance.

**Comment by Araq** [comment]
I know it's semantically different, else we would implement shallowCopy as move... But often it can be used instead.

**Pull request merged**
