### PR TITLE
Add support for parsing parameterised sql types

### PR DESCRIPTION
**Pull request by cletusigwe**
This PR allows the `sqlParser` to include the parameters of database types in its parsed AST. [Forum discussion here](https://forum.nim-lang.org/t/12605)

### CODE REVIEW

**Comment by Araq** [comment]
Unnecessary code breakage. Instead add a flag to `SqlParser` that can be set in the constructors defaulting to `false` and then check for this flag before parsing complex types in your new way.

**Comment by cletusigwe** [comment]
You are right. I added the boolean field `considerTypeParams` to the `sqlParser` object, so users can set how they want parsing to work. 

I also wanted to change the signature of the parseSql proc that accepts an input string from:
```nim
proc parseSql*(input: string, filename = "", considerTypeParams = false): SqlNode =
  ## parses the SQL from `input` into an AST and returns the AST.
  ## `filename` is only used for error messages.
  ## Syntax errors raise an `SqlParseError` exception.
  parseSql(newStringStream(input), "", considerTypeParams)
```
to
```nim
proc parseSql*(input: string,  considerTypeParams = false): SqlNode =
  ## parses the SQL from `input` into an AST and returns the AST.
  ## `filename` is only used for error messages.
  ## Syntax errors raise an `SqlParseError` exception.
  parseSql(newStringStream(input), "", considerTypeParams)
```
because the `filename` parameter is not really being used, but decided against it because it might also break something.

**Comment by Araq** [comment]
I wanted to reopen it so that I can merge it but something went wrong...

**Comment by Araq** [comment]
Reopening...

**Pull request closed without merging**
