### PR TITLE
strutils: Make the invalidFormatString error a bit more informative

### PR DESCRIPTION
**Pull request by kaushalmodi**
The error in https://github.com/nim-lang/Nim/issues/14485 said just:

> Error: unhandled exception: invalid format string [ValueError]

This PR will add a bit more context to that particular exception.

Ref: https://github.com/nim-lang/Nim/issues/14485

### CODE REVIEW

**Comment by timotheecour** [comment]
see also https://github.com/nim-lang/Nim/pull/14282 (which i forgot to convert from draft)

**Comment by kaushalmodi** [comment]
https://github.com/nim-lang/Nim/pull/14282 is certainly more informative than my quick stab in this PR. I don't see why that draft PR cannot be committed.

**Comment by timotheecour** [comment]
i guess i was just trying to settle on the most useful debug output; since this is at least the 2nd concrete use case i'll convert it soon

**Comment by kaushalmodi** [comment]
Can you also commit https://github.com/nim-lang/Nim/pull/14282? I can then close this.

**Comment by timotheecour** [comment]
> Can you also commit #14282? I can then close this.

I will... soon!

**Pull request closed without merging**
