### PR TITLE
Correct the doc for rand with a float argument.

### PR DESCRIPTION
**Pull request by konqoro**
Also tried to make the javascript code do the same. But I haven't tested it.

### CODE REVIEW

**Comment by Araq** [comment]
Well test it please. It's subtle.

**Comment by konqoro** [comment]
Not ready for review, since I still figuring out the tests.

**Comment by konqoro** [comment]
Nah its not a good test.

**Comment by Araq** [comment]
Tests fail with

```
Error message:
Failure: reOutputsDiffer
Expected:
ok

Gotten:
failed randomInt
failed shuffle
ok
```

**Comment by konqoro** [comment]
Yes and they will continue to fail no matter what. What needs to be done is compute the confidence interval and a proper simulation and turn this from a test to just output the info. So closing.

**Pull request closed without merging**
