### PR TITLE
macros.expectKind with errorMessage

### PR DESCRIPTION
**Pull request by juancarlospaco**
- https://github.com/timotheecour/Nim/issues/775#issue-935836549

### CODE REVIEW

**Comment by timotheecour** [comment]
same comment as https://github.com/nim-lang/RFCs/issues/185; i don't see why we should introduce N different APIs when a single once would suffice (either doAssert or something similar to unittest.check)

**Comment by juancarlospaco** [comment]
@timotheecour
I agree, but then if it has to stay because reasons, 
then at least make it barely useful with a non-hardcoded message... 🤷

**Comment by timotheecour** [comment]
why not add an optional param instead to those APIs, eg:
```nim
proc expectKind*(n: NimNode; k: set[NimNodeKind]) =
  ## Checks that `n` is of kind `k`. If this is not the case,
  ## compilation aborts with an error message. This is useful for writing
  ## macros that check the AST that is passed to them.
  if n.kind notin k: error("Expected one of " & $k & ", got " & $n.kind, n)
=>
proc expectKind*(n: NimNode; k: set[NimNodeKind], msg = "") =
  ## Checks that `n` is of kind `k`. If this is not the case,
  ## compilation aborts with an error message. This is useful for writing
  ## macros that check the AST that is passed to them.
  if n.kind notin k:
    var msg2 = "Expected one of " & $k & ", got " & $n.kind
    if msg.len > 0: msg2.add "; " & msg
    error(msg2, n)
```

**Comment by juancarlospaco** [comment]
Maybe we can `{.deprecated.}` ?. 🤔

This is by definition a precondition, it grows bad APIs like these for the lack of a proper DBC module in stdlib.

**Comment by Araq** [comment]
So which other languages have a "proper DBC" module in their stdlibs? And how does it help them?

**Pull request closed without merging**
