### PR TITLE
rename `std/threads` to `std/typedthreads`

### PR DESCRIPTION
**Pull request by ringabout**
Or should it be `typedthreads` or `thread_v1`? I don't know. Suggestions are appreciated.

### CODE REVIEW

**Comment by PMunch** [comment]
Depends on what the new module is going to be called, and what the relationship between them is going to be. The threads module is a fairly thin wrapper over the system threads, how is this going to change with the new threads? Are people still going to use the old threads module if they want this low-level access?

**Comment by arnetheduck** [comment]
why is it being changed?

**Comment by ringabout** [comment]
The implementation of `std/threads` is not good enough. In 2.x, there will be likely to have a better `std/threads` module. In case of the name conflicts, it needs to be renamed.

**Comment by ringabout** [comment]
> how is this going to change with the new threads? Are people still going to use the old threads module if they want this low-level access?

The new `std/threads` is likely to have bare primitives and no generics. It should be simply a thin wrapper of system threads while it's not true for the current implementation which stores thread local data and the callback pair.

**Comment by arnetheduck** [comment]
Developing a new thread module sounds like something that will be a compromise between rushing a poor thread module and delaying v2 - why not leave a new thread module to 2.2? Creating one is not part of v2 goals really.

**Comment by ringabout** [comment]
> Developing a new thread module sounds like something that will be a compromise between rushing a poor thread module and delaying v2 - why not leave a new thread module to 2.2? Creating one is not part of v2 goals really.

> In 2.x, there will be likely to have a better std/threads module. 

Perhaps I was not clear. As I said, there is no plan for a new `std/threads` module in v2 release. It will be implemented in 2.x.

**Comment by PMunch** [comment]
I don't think it's a great look for Nim v2 to have soft deprecated our threads module with no alternative.. I find this a very strange decision, especially considering how `--threads:on` will become the default and ARC/ORC promises easier multithreading.

**Comment by arnetheduck** [comment]
> I don't think it's a great look

"It will be shipped in 2.2" is an excellent answer to that comment - ie it's perfectly fine, given that nothing was really lost (ie the current threads module is hardly worth bragging about and DIY threading is kind of the norm since none of abstactions work well - the idea with `--threads:on` is to make sure that the core language parts don't fall apart under DIY threading conditions at least.

**Comment by PMunch** [comment]
I was more thinking about the publicity spike that Nim will get a v2 release. It will look like Nim v1 had threading but v2 removed it. I'm just saying that it would look a bit odd, even if the old threading module wasn't anything to write home about. In a perfect world I would of course like Nim v2 to ship with a new and improved story for multithreading, but by the look of things that would delay the launch quite significantly (although maybe it would be more deserving of the v2 name).

**Comment by Varriount** [comment]
I feel that it would be better to deprecate the current "thread" module only when we have a viable replacement. This avoids pressure to release a sub-par alternative because "we need a replacement ASAP".

**Comment by Araq** [comment]
Let me clear up the situation: The threading primitives moved out of system.nim for `nimPreviewSlimSystem`. There was no `std / threads` before so nothing got removed. We're bikeshedding about a name, that's all. And ideally the new name doesn't prevent us from coming with an even better threads module later so `typedthreads` is a good solution.

**Comment by PMunch** [comment]
So this module will still be automatically imported when `--threads:on`? The new `typedthreads` name is definitely much better, when I started commenting it was called `oldthreads` which made it appear like we didn't have a new solution for threads.

**Comment by ringabout** [comment]
> So this module will still be automatically imported when --threads:on?

Yeah. It is imported by default (without `-d:nimPreviewSlimSystem`).

**Comment by arnetheduck** [comment]
so hold on - if this is imported automatically and not meant to be a "user" import, why is it in  the `std` namespace?

**Comment by ringabout** [comment]
Because it is not imported with `-d:nimPreviewSlimSystem`. Users' code should still work with `-d:nimPreviewSlimSystem` by simply importing a module. Perhaps we can give an error when users try to import these modules without `-d:nimPreviewSlimSystem`.

**Pull request merged**
