### PR TITLE
Add --randomize to Testament

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Add `--randomize` to Testament. Tiny diff.

# Why?

On Unittests a "Unit" must not depend on previous unit,
and next unit must not depend on the current unit, and so on,
random order for tests helps against unwanted unit cross-dependency,
when something on a test depends on something on a previous test,
like bad Tear-Downs, state, file or folder existence, leaked data, etc.

### CODE REVIEW

**Comment by Araq** [comment]
The idea is nice but are you certain this does the randomization you're after?

**Comment by juancarlospaco** [comment]
@Araq 
I `echo` before and after several times, and is working, obviously I removed debug `echo` for PR. 

I always used similar construct on Python for years, sometimes it catches bugs too,
also ensures tests are not dependent of each others, correct setups/teardowns.

More stuff can be randomized if wanted on the future, but this is a good base feature,
some testing framework do stuff like randomized delays between tests, etc etc,
is up to creativity, if you see something else that should be randomized feel free to comment,
if I know how to do it can be implemented on a future PR, to keep Diff tiny.

**Comment by alaviss** [comment]
Are you certain this is what you want? As far as this goes, it only randomize the order of `categories` tested.

**Comment by juancarlospaco** [comment]
I know, still better than nothing, what do you want to randomize?, individual files?,
really dont know where the files are on a sequence form on the code to shuffle them up, 
if you can tell me where the list of files is on the code I can add that too. :shrug: 

If you thinking of compiler targets?, I dont think was too important, but maybe can be added too. :shrug:

**Comment by Araq** [comment]
Sorry, rejected. I cannot imagine this to find any real bugs given that nimcache is project specific already.

**Comment by juancarlospaco** [comment]
@Araq 
This is `nimcache` agnostic, can be confirmed by the fact that still works on JS target. :shrug:

**Comment by disruptek** [comment]
I like the idea.  Can you explain what you mean by reference to the nimcache, @Araq?

**Comment by Araq** [comment]
The nimcache is project specific so there is no overlap between projects. This PR's randomization basically tests for this fact and only for this fact. But we know it to be true and it's a tradeoff between "test what is super unlikely to ever get broken" and "add more code to testament to maintain".

**Pull request closed without merging**
