### PR TITLE
Add low, high and len for tuples

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by Araq** [comment]
Why do we need this? And why doesn't it have an RFC?

**Comment by data-man** [comment]
If the tuple fields can be accessed by index, then it would be logical to have these procedures.
Isn't it?

**Comment by Araq** [comment]
No, because you cannot *iterate* over tuple fields. Only constant indexes are allowed. And you can only use the constant indexes when you already know the ``high`` value.

**Comment by data-man** [comment]
> No, because you cannot iterate over tuple fields. 

But I can iterate over fixed-size arrays. What's difference? I hope it can be solved.

> And you can only use the constant indexes when you already know the high value.

But ```high``` for tuple is known at compile time.

**Comment by Araq** [comment]
> But I can iterate over fixed-size arrays. What's difference? I hope it can be solved.

The difference is that every field in a tuple can have a different type.

**Comment by hlaaftana** [comment]
`fields` and `fieldPairs` expand the for loop at CT, that's why they work. You can't do `for i in low(tup)..high(tup): echo tup[i]`

**Comment by dom96** [comment]
What's the use case for these? You can't access the members of a tuple by index at runtime.

**Comment by data-man** [comment]
I remember someone's question in the chat. Something like 'how to get the length of a tuple?'.
Somewhere there is a macro for this. But now this information is not easy to find.

**Comment by Varriount** [comment]
@data-man To get the length of a tuple, you can use the `arity` function in the typetraits module.

With regards to this PR, I think a `len` procedure for tuples makes possible sense (it's more obvious than `arity`, in both documentation and naming) however `low` and `high` procedures have little use.

**Comment by Bulat-Ziganshin** [comment]
I see usecase in templates> Currently, we don't have variadic generics and templates can't do much with varargs parameters. Compile-time iteration and slicing (i.e. all but first field) of tuples may allow to provide features similar to C++/D variadic templates, and may be even more readable.

**Comment by yglukhov** [comment]
This doesn't need compiler help, it can be implemented in a library:
```nim
var tt = (a: 1, b: "str1")

proc tupleLen(T: typedesc): int {.compileTime.} =
  var v: T
  for i in fields(v): inc result

template len(v: tuple): int =
  const l = tupleLen(type(v))
  l

template low(v: tuple): int = 0
template high(v: tuple): int = v.len - 1

echo tt.len
echo tt.low
echo tt.high
```

**Comment by Araq** [comment]
Once every type supports every verb we have a language that does not detect any errors.

**Pull request closed without merging**
