### PR TITLE
re-enable nimgame2

### PR DESCRIPTION
**Pull request by ringabout**

### CODE REVIEW

**Review by timotheecour — APPROVED** [review]

**Comment by timotheecour** [comment]
this was disabled in #15935 ; what changed since then? or maybe it was already working after that PR?

**Comment by ringabout** [comment]
I'm just testing them and I will make a PR to fix nimgame2.

**Comment by Araq** [comment]
nimgame2 worked for me with the deprecated "random" stuff removed.

**Comment by ringabout** [comment]
@araq the issue is https://github.com/nim-lang/Nim/issues/16462
https://github.com/pragmagic/godot-nim/issues/81

**Pull request closed without merging**
