### PR TITLE
fix #12122

### LINKED ISSUE #12122: `ByteAddress` broken for its intended purpose
https://github.com/nim-lang/Nim/blob/cb0450398a5695e1e1193e6c49ff9c7548980438/lib/system.nim#L2205

`ByteAddress` is an `int` - this is problematic for several reasons:

* you can't use it for its documented purpose of printing / readability: address space generally is not considered  to go into the negative
* you can't do arithmetic on it because `int` is a checked type that will raise even on seemingly valid pointer operations: for example linux in 32-bit mode uses a 3gb address space for pointers meaning that at least at the 2gb mark, it crosses into `int` negative space

It seems appropriate to deprecate this type and add a new `uint`-based distinct type that has a few pointer operations attached to its name along with documentation explaining the pitfalls of doing  so.

### PR DESCRIPTION
**Pull request by bung87**

### CODE REVIEW

**Comment by Araq** [comment]
Too much effort. Deprecate `ByteAdress` and use `int` in system.nim and its dependencies, problem solved.

**Comment by arnetheduck** [comment]
> use int in system.nim

`uint` you mean?

**Comment by Araq** [comment]
> uint you mean?

Not immediately, that would be a more invasive change.

**Comment by bung87** [comment]
maybe need introduce new type (haven't get a good name) for easier maintaining both for compiler developer and package developer

**Comment by arnetheduck** [comment]
> more invasive change.

I think there's no way out of that in general - ie using int (and its defects) is simply .. wrong - sure, it can happen in stages, but every `int` arithmetic on pointers is basically a ticking bomb.

**Comment by bung87** [comment]
araq's temporary solution only introduce a warning to users. a PR like that can't even mark as "fix #12122" , package developers may not change to `uint` directly in some cases, so they may have nothing to do when they notice such a warning.

guess the final fix may not included in v2.

**Comment by arnetheduck** [comment]
> araq's temporary solution only introduce a warning to users.

I think anyone using `ByteAddress` should get a warning because they need to move away from it - the route we've gone is to introduce functions to work with `pointer` directly instead of going the `uint` way: https://github.com/status-im/nim-stew/blob/master/stew/ptrops.nim - this might not be for everyone though, but the named functions make it clear that this is not "ordinary" arithmetic.

The PR, as I imagine it, puts `{.deprecated.}` on `ByteAddress` and changes all stdlib usage to use `uint` then casts the result to `int` where necessary, after arithmetic, for backwards compat - this is the "minimally" invasive thing to do that is also correct - we need `ByteAddress` to remain deprecated for a few releases so that users can upgrade at their own pace and not have to upgrade everything at once.

**Comment by ringabout** [comment]
Succeeded by https://github.com/nim-lang/Nim/pull/21096

**Pull request closed without merging**
