### PR TITLE
Represent more types as JS `TypedArray`s

### PR DESCRIPTION
**Pull request by AmjadHD**

### CODE REVIEW

**Comment by AmjadHD** [comment]
What about `WideChar = distict uint16` and `Positive32 = range[1i32..int32.high]`, shouldn't these get more compact representations too ?

**Comment by metagn** [comment]
They already should, since `tyDistinct` and `tyRange` should be skipped.

**Comment by AmjadHD** [comment]
They're not:
```nim
type
  WideChar = distinct uint16
  Positive32 = range[1i32..int32.high]

var wca: array[5, WideChar]
var p32a: array[5, Positive32]
```
```js
var wca_469762060 = [[0, 0, 0, 0, 0]];
var p32a_469762061 = [[0, 0, 0, 0, 0]];
```

**Comment by metagn** [comment]
Ok then, they should be skipped. The minimal change would be to add `let typ = typ.skipTypes(abstractRange)` as the first line of `arrayTypeForElemType`.

**Comment by AmjadHD** [comment]
You mean `abstractInst` or `abstractVarRange` ?
and how will this affect this code: https://github.com/nim-lang/Nim/blob/be4bd8a0edd527b24679372b8cb9d2afa548056d/compiler/jsgen.nim#L2274-L2277

**Comment by metagn** [comment]
The array type is already skipped, but the element type isn't. We want to skip the element type. The element type isn't used in that code except for calling `arrayTypeForElemType`. or by recursing on `createVar` which already skips the type.

Yes `abstractVarRange` is fine. `abstractInst` doesn't have range AFAIK, but one of your examples was a range type.

**Comment by AmjadHD** [comment]
And what about `tyEnum` and `tyBool` ?

**Comment by AmjadHD** [comment]
For `tyBool` Ig it's fine to represent it as `new UInt8Array([true, false, true])`, nim works with bools via their numerical values, so in that sense nothing changes here except that (`console.log` will output `UInt8Array([1, 0, 1]` instead of `[true, false, true]` but that is a minor point since `echo` doesn't change).
For `tyEnum` how to get it's size ?

**Pull request merged**
