### PR TITLE
WIP: GitHub templates

### PR DESCRIPTION
**Pull request by data-man**
Just an idea.
Feel free to test it in my [repository](https://github.com/data-man/GitHubTesting).

### CODE REVIEW

**Comment by Araq** [comment]
What's the point?

**Comment by Yardanico** [comment]
@Araq it would be easier to read issues if they all will have roughly the same structure

**Comment by data-man** [comment]
It remains only to compose a text most suitable for Nim's specificity.

**Comment by Araq** [comment]
> it would be easier to read issues if they all will have roughly the same structure

How so? Things are easier to read when they are not full of pointless boilerplate. For most bugs I don't need CPU/OS/CC information. Also we would need a way of enforcing this super new scheme. This is not something I want to spend time on. Nor do I want you to spend time on it. Closing.

**Pull request closed without merging**
