### PR TITLE
`import` now works at local scope

### LINKED ISSUE #410: import at local scope
## proposal
make `import` work at local scope, which removes a long standing restriction.

local imports is a basic feature found in lots of other languages with a module system and improves modularity and symbol scoping and can trim down dependencies to "import what you use" in generic code.

## examples of languages that support import at local scope
* python
* D
* rust
* scala
* ruby
* typescript
* js (eg via dynamic import)
* java (you can use fully qualified name inside a function without needing top-level import)
* C# (supports `using` inside a namespace for scoping)
* matlab, etc

## benefits
This allows client/library code to avoid top-level scope pollution when a symbol is only needed in a certain local scope (block or proc). Or, if an operator should only be used in some scope, you can use a local import (refs https://github.com/kaushalmodi/ptr_math/pull/2 for pointer arithmetic operators)

For imports inside generics, this furthermore allows the import depedency to only occur when the generic is instantiated, leading to smaller and more localized dependencies ("import what you use").

Finally, this can also help with circular dependencies, e.g. when an import is inside a generic.

## PR
this has been implemented, see https://github.com/nim-lang/Nim/pull/18734

### PR DESCRIPTION
**Pull request by timotheecour**
## links
* see tests
* see RFC: fixes https://github.com/nim-lang/RFCs/issues/410
* https://www.pythoninsight.com/2018/09/why-doesnt-import-work-at-function-scope/ 
>  there’s an exception for “from ... import *“, which can’t be used inside a function

### CODE REVIEW

**Comment by konsumlamm** [comment]
Why not just allow general imports at local scope?

**Comment by timotheecour** [comment]
> Why not just allow general imports at local scope?

done

**Comment by konsumlamm** [comment]
This would be very useful! Does this require an RFC? I don't think it is controversial, but still.

**Comment by timotheecour** [comment]
> This would be very useful! Does this require an RFC? I don't think it is controversial, but still.

see https://github.com/nim-lang/RFCs/issues/410

and yes, this is very useful.

**Comment by juancarlospaco** [comment]
Add a line explaining that `import` is scoped in the Manual near 
https://nim-lang.github.io/Nim/manual.html#modules-import-statement

**Comment by timotheecour** [comment]
> Add a line explaining that import is scoped in the Manual near

done, i added a section

**Pull request closed without merging**
