### PR TITLE
fix #12471

### LINKED ISSUE #12471: nim doc cannot grok IOSelectorsException
The following produces errors when passed to `nim doc`, though it compiles and runs just fine.

```nim
import selectors

try:
  discard
except IOSelectorsException:
  discard
```

```
Error: undeclared identifier: 'IOSelectorsException'
Error: only a 'ref object' can be raised
Warning: imported and not used: 'selectors' [UnusedImport]
```

```
Nim Compiler Version 1.0.99 [Linux: amd64]
Compiled at 2019-10-20
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 734da9e1dfdd5cb441a5c1461539f10ab331596a
active boot switches: -d:danger
```

### PR DESCRIPTION
**Pull request by ringabout**
Since `IOSelectorsException` is exported, it should be exported in docs too.

### CODE REVIEW

**Comment by ringabout** [comment]
I don't know how to test this.

Now I find I must add `runnableExamples`.

It works. And It does test them because it failed in Nim v 1.4.0 as expected.

image

**Comment by Araq** [comment]
If you don't mind too much, please remove the test again, it's unlikely to regress and "bloat" can become a problem for a testsuite too.

**Comment by ringabout** [comment]
done

**Comment by ringabout** [comment]
I delete the test. Let me put a picture to show it is a right fix:
image

**Comment by ringabout** [comment]
Record:
```
  FAIL: norm C
  Test "norm" in category "nimble-packages-2"
  Failure: reBuildFailed
  package test failed
  $ nim c -r tests/tsqliterows.nim
  Hint: used config file '/Users/runner/work/Nim/Nim/config/nim.cfg' [Conf]
  Hint: used config file '/Users/runner/work/Nim/Nim/config/config.nims' [Conf]
  Hint: used config file '/Users/runner/work/Nim/Nim/pkgstemp/norm/tests/config.nims' [Conf]
  ....
  Error: cannot open 'tests/tsqliterows.nim'
```

**Pull request merged**
