### PR TITLE
fix #20997 calling system.card[T](x: set[T]) with T of int8 or uint8 …

### LINKED ISSUE #20997: calling `system.card[T](x: set[T])` with `T` of `int8` or `uint8` uses mismatched C array sizes
### Description

When calling `system.card[T](x: set[T])` on either `set[int8]` or `set[uint8]`, Nim generates a function
```c
static N_INLINE(NI, cardSet)(tyArray__S8ib5N31oJbAkqOZTlNg5Q s, NI len);
...
static N_INLINE(NI, cardSet)(tyArray__S8ib5N31oJbAkqOZTlNg5Q s, NI len) {
    ...
}
```

which is called from
```c
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	tySet_tyInt8__chXunH2dwinSkhpA6JnsXw T1_;
	nimfr_("cmdfile", "cmdfile.nim");
	nimln_(1, "cmdfile.nim");
	nimZeroMem((void*)T1_, sizeof(tySet_tyInt8__chXunH2dwinSkhpA6JnsXw));
	(void)(cardSet(T1_, 32));
	nimTestErrorFlag();
	popFrame();
}
}
```

where `tyArray__S8ib5N31oJbAkqOZTlNg5Q` and `tySet_tyInt8__chXunH2dwinSkhpA6JnsXw` are defined as
```c
typedef NU8 tySet_tyInt8__chXunH2dwinSkhpA6JnsXw[32];
typedef NU8 tyArray__S8ib5N31oJbAkqOZTlNg5Q[8192];
```

It's calling (through/via a `void *`, which in itself is fine) a function expecting an `NU8[8192]` with an `NU8[32]`. It doesn't ever access these extra (8192-32) elements of the array, because it sets `cardSet`'s `len` parameter to 32, but given that the sizes are both known ahead of time, it's feasible to match them.

### Nim Version

```
Nim Compiler Version 1.6.10 [Linux: amd64]
Compiled at 2022-11-23
Copyright (c) 2006-2021 by Andreas Rumpf
```

```
Nim Compiler Version 1.7.3 [Linux: amd64]
Compiled at 2022-12-02
Copyright (c) 2006-2022 by Andreas Rumpf
```

```
$ gcc --version
gcc (Debian 12.2.0-9) 12.2.0
```

### Current Output

```text
$ nim c --passC=-flto --passL=-flto --eval:"discard card(default(set[uint8]))"
Hint: used config file 'Nim/config/nim.cfg' [Conf]
Hint: used config file 'Nim/config/config.nims' [Conf]
...................................................................
CC: cmdfile.nim
Hint:  [Link]
.cache/nim/cmdfile_d/@mcmdfile.nim.c: In function ‘NimMainModule’:
.cache/nim/cmdfile_d/@mcmdfile.nim.c:240:16: warning: ‘cardSet’ accessing 8192 bytes in a region of size 32 [-Wstringop-overflow=]
  240 |         (void)(cardSet(T1_, 32));
      |                ^
.cache/nim/cmdfile_d/@mcmdfile.nim.c:240:16: note: referencing argument 1 of type ‘NU8[8192]’
.cache/nim/cmdfile_d/@mcmdfile.nim.c:153:8: note: in a call to function ‘cardSet’
  153 | static N_INLINE(NI, cardSet)(tyArray__S8ib5N31oJbAkqOZTlNg5Q s, NI len) {
      |        ^
Hint: mm: orc; threads: on; opt: none (DEBUG BUILD, `-d:release` generates faster code)
27506 lines; 0.577s; 30.328MiB peakmem; proj: cmdfile; out: .cache/nim/cmdfile_d/cmdfile [SuccessX]
```

### Expected Output

```text
No usage of mismatched array sizes on caller/callee side.
```

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by bung87**
…uses mismatched C array sizes

fix #20997

### CODE REVIEW

**Comment by tersec** [comment]
Aside from it not bootstrapping for me via `build_all.sh`, it's also incomplete. https://github.com/nim-lang/Nim/issues/20997 is one example, but subrange types allow arbitrary constructions of these, as would sufficiently large enums.

```nim
template f(n: int) = discard card(default(set[range[0 .. (1 shl n) - 1]]))
f( 7)
f( 8)
f( 9)
f(10)
f(11)
f(12)
f(13)
f(14)
f(15)
f(16)
```

generates
```c
  typedef NU8 tySet_tyInt__dbI9aeqZ7Ml0VFzfa12ZB6w[16];
typedef NU8 tyArray__S8ib5N31oJbAkqOZTlNg5Q[8192];
typedef NU8 tySet_tyInt__Oicxd75j1oQ6Xr53IdlvoA[32];
typedef NU8 tySet_tyInt__FKMmRtto61Q69cw1undK9a4g[64];
typedef NU8 tySet_tyInt__qwRxnwWF4Tgl9baqDkQ57Uw[128];
typedef NU8 tySet_tyInt__2UDDwdvL6JYkarNT0QbuIw[256];
typedef NU8 tySet_tyInt__YF9cxdY6bvJpsAiXDP6swQQ[512];
typedef NU8 tySet_tyInt__tqGDrEI4iDvYtB8wWvw0GA[1024];
typedef NU8 tySet_tyInt__pKQB8Onopm3Drm9bbBD19bGA[2048];
typedef NU8 tySet_tyInt__S2fJwyGvRnuaf2yJCYmldw[4096];
typedef NU8 tySet_tyInt__0Qsu6ykZBzpuXoFSXQGViA[8192];

...

static N_INLINE(NI, cardSet)(tyArray__S8ib5N31oJbAkqOZTlNg5Q s, NI len);

...

static N_INLINE(NI, cardSet)(tyArray__S8ib5N31oJbAkqOZTlNg5Q s, NI len) {

...

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	tySet_tyInt__dbI9aeqZ7Ml0VFzfa12ZB6w T1_;
	tySet_tyInt__Oicxd75j1oQ6Xr53IdlvoA T2_;
	tySet_tyInt__FKMmRtto61Q69cw1undK9a4g T3_;
	tySet_tyInt__qwRxnwWF4Tgl9baqDkQ57Uw T4_;
	tySet_tyInt__2UDDwdvL6JYkarNT0QbuIw T5_;
	tySet_tyInt__YF9cxdY6bvJpsAiXDP6swQQ T6_;
	tySet_tyInt__tqGDrEI4iDvYtB8wWvw0GA T7_;
	tySet_tyInt__pKQB8Onopm3Drm9bbBD19bGA T8_;
	tySet_tyInt__S2fJwyGvRnuaf2yJCYmldw T9_;
	tySet_tyInt__0Qsu6ykZBzpuXoFSXQGViA T10_;
	nimZeroMem((void*)T1_, sizeof(tySet_tyInt__dbI9aeqZ7Ml0VFzfa12ZB6w));
	(void)(cardSet(T1_, 16));
	nimZeroMem((void*)T2_, sizeof(tySet_tyInt__Oicxd75j1oQ6Xr53IdlvoA));
	(void)(cardSet(T2_, 32));
	nimZeroMem((void*)T3_, sizeof(tySet_tyInt__FKMmRtto61Q69cw1undK9a4g));
	(void)(cardSet(T3_, 64));
	nimZeroMem((void*)T4_, sizeof(tySet_tyInt__qwRxnwWF4Tgl9baqDkQ57Uw));
	(void)(cardSet(T4_, 128));
	nimZeroMem((void*)T5_, sizeof(tySet_tyInt__2UDDwdvL6JYkarNT0QbuIw));
	(void)(cardSet(T5_, 256));
	nimZeroMem((void*)T6_, sizeof(tySet_tyInt__YF9cxdY6bvJpsAiXDP6swQQ));
	(void)(cardSet(T6_, 512));
	nimZeroMem((void*)T7_, sizeof(tySet_tyInt__tqGDrEI4iDvYtB8wWvw0GA));
	(void)(cardSet(T7_, 1024));
	nimZeroMem((void*)T8_, sizeof(tySet_tyInt__pKQB8Onopm3Drm9bbBD19bGA));
	(void)(cardSet(T8_, 2048));
	nimZeroMem((void*)T9_, sizeof(tySet_tyInt__S2fJwyGvRnuaf2yJCYmldw));
	(void)(cardSet(T9_, 4096));
	nimZeroMem((void*)T10_, sizeof(tySet_tyInt__0Qsu6ykZBzpuXoFSXQGViA));
	(void)(cardSet(T10_, 8192));
	popFrame();
}
}
```

which has exactly the same issue. There are at least 10 distinct cases here (types larger than `int16`/`uint16` being rejected for `set`s, and smaller types not triggering usage of `cardSet` but directly calling `countBits32`/`countBits64`).

**Comment by bung87** [comment]
use proc overload works but break IC test, compilerproc generic is not supported,  seperate to multiple procs cause `Error: system module needs: cardSet`, no idea how to fix this.

**Comment by tersec** [comment]
Hadn't checked this before, but Nim's set codegen's not restricted to powers of two:
```nim
import std/macros

template f(n: int) = discard card(default(set[range[0 .. n]]))
macro g(): untyped =
  result = newStmtList()
  for setsize in countup(64, 65535, 8):
    result.add newCall(bindSym"f", newLit(setsize))
g()
```
creates, by using byte-size-strides effectively,
```
  typedef NU8 tySet_tyInt__g3YNp45iiYwa623pyVq1UA[9];
typedef NU8 tyArray__S8ib5N31oJbAkqOZTlNg5Q[8192];
typedef NU8 tySet_tyInt__R5WvQzcCA9c17vCAXfonIBQ[10];
typedef NU8 tySet_tyInt__OXp7sX03jzDKsHu8LcYKsA[11];
typedef NU8 tySet_tyInt__prtDISSCPSTv9c1fZwFJDtA[12];
typedef NU8 tySet_tyInt__9bRWsUpa0azIZIRpORylWIQ[13];
typedef NU8 tySet_tyInt__yuxREVOTigp3Kb8C8b5lDw[14];
typedef NU8 tySet_tyInt__ar0qt9aaXRKlsc9cpyAE0EZw[15];
typedef NU8 tySet_tyInt__QWsYllnqxPzf3hJulnqBcg[16];
typedef NU8 tySet_tyInt__eQ19av3k0epopaUa9cx9b2O3Q[17];
typedef NU8 tySet_tyInt__QKmKn9aOmB0uJ9a0eTme5bVw[18];
typedef NU8 tySet_tyInt__pDkZh2d9caHHe59bVYyg84Ew[19];
typedef NU8 tySet_tyInt__XTNLcPyqBAw7Rk3uagLWwg[20];
typedef NU8 tySet_tyInt__Gyb9a8b9cW9ajcJdvOmKvjVHg[21];
typedef NU8 tySet_tyInt__k2exkv0Q69aCbdnoE2cGokw[22];
typedef NU8 tySet_tyInt__2u8Uq5HtaeogMgqfa4aXjA[23];
typedef NU8 tySet_tyInt__FVymwlTXJJuIEdfEEWohqQ[24];
typedef NU8 tySet_tyInt__CMpw2LIG7xyd7BWQSMUkrA[25];
typedef NU8 tySet_tyInt__9bnu9bWJHSuOHBI8SeKCKq8Q[26];
typedef NU8 tySet_tyInt__L7d3SsMWppBX7mTg289boaw[27];
typedef NU8 tySet_tyInt__1CBoeOL7R7QVzZn8Rhw6aA[28];
typedef NU8 tySet_tyInt__2waXokKg0mAFnq388tVmuw[29];
typedef NU8 tySet_tyInt__1r7mjJVjdW6J01MR5VCU9aQ[30];
typedef NU8 tySet_tyInt__utfQpUqac9cRn6zQwnoiqmw[31];
typedef NU8 tySet_tyInt__VYLCaYbbHgiUTlfcPTXZVA[32];
typedef NU8 tySet_tyInt__YoKf8dOzAH8uSpravjT9aBg[33];
typedef NU8 tySet_tyInt__529b5OJo8knxQ8JYJiclXMA[34];
typedef NU8 tySet_tyInt__prVQh7Oip1EQ0VCv1DJyMg[35];
typedef NU8 tySet_tyInt__Sv5KvbycI9coZ7LW5CHGW5A[36];
typedef NU8 tySet_tyInt__PC9cfL0yybMrtsJFUaLQAiQ[37];
typedef NU8 tySet_tyInt__09aZ1lHqJgFlODixFQxvdTA[38];
typedef NU8 tySet_tyInt__pByM9bESOIO7jW1UkQK9b1og[39];
typedef NU8 tySet_tyInt__OajRmquHuLX9aqVruIBpxXg[40];
typedef NU8 tySet_tyInt__QguME9adygS01S5p3kFP3YQ[41];
typedef NU8 tySet_tyInt__Vngu6Bqwwcopuo3vz3EZhg[42];
...

typedef NU8 tySet_tyInt__ydc4pMQJPGpYaVg3tTs8og[8174];
typedef NU8 tySet_tyInt__BFxOQUpJsX519ab09aSkFL9ag[8175];
typedef NU8 tySet_tyInt__J9bFN5bnxIxUrg3o18fwWQQ[8176];
typedef NU8 tySet_tyInt__6rr6EtlNkpC9aEanwDoljlw[8177];
typedef NU8 tySet_tyInt__SFsjxAFIxFLdhIBy6L2CFg[8178];
typedef NU8 tySet_tyInt__YwY9cqKMe4DvX8KD9bti44FQ[8179];
typedef NU8 tySet_tyInt__wGgDkMFY2BRmcR4v72nLmw[8180];
typedef NU8 tySet_tyInt__pX6DoSba282Xcg2ulPc6kA[8181];
typedef NU8 tySet_tyInt__jJu3XeiIxnVOa7Awyl9bXMw[8182];
typedef NU8 tySet_tyInt__4aYQ163IzUSPpWz1uqg8og[8183];
typedef NU8 tySet_tyInt__SXdOHTv3HD9ahQxNuY46ibA[8184];
typedef NU8 tySet_tyInt__LzU43aEsSWJ51Vx44UNkeQ[8185];
typedef NU8 tySet_tyInt__Uh0cI9cLrC2a8MqJggdeTjw[8186];
typedef NU8 tySet_tyInt__9cFHpa8Ml4Cj9aLatkefNhIg[8187];
typedef NU8 tySet_tyInt__9cgfRGWSw2iy9b2S6yIp4IWw[8188];
typedef NU8 tySet_tyInt__k62S5LDtd9bskZ9cN3MuYDcg[8189];
typedef NU8 tySet_tyInt__kIKxJRxS1FcIOlJDolVHKA[8190];
typedef NU8 tySet_tyInt__mNBquj1kxw3otKBjj9bEfoA[8191];
typedef NU8 tySet_tyInt__MRWrGe9bzN07F0D9aMsUhB1Q[8192];
```
hitting every integral array size in between.

It then creates each of them
```
	tySet_tyInt__g3YNp45iiYwa623pyVq1UA T1_;
	tySet_tyInt__R5WvQzcCA9c17vCAXfonIBQ T2_;
	tySet_tyInt__OXp7sX03jzDKsHu8LcYKsA T3_;
	tySet_tyInt__prtDISSCPSTv9c1fZwFJDtA T4_;
	tySet_tyInt__9bRWsUpa0azIZIRpORylWIQ T5_;
	tySet_tyInt__yuxREVOTigp3Kb8C8b5lDw T6_;
	tySet_tyInt__ar0qt9aaXRKlsc9cpyAE0EZw T7_;
	tySet_tyInt__QWsYllnqxPzf3hJulnqBcg T8_;
	tySet_tyInt__eQ19av3k0epopaUa9cx9b2O3Q T9_;
	tySet_tyInt__QKmKn9aOmB0uJ9a0eTme5bVw T10_;
	tySet_tyInt__pDkZh2d9caHHe59bVYyg84Ew T11_;
	tySet_tyInt__XTNLcPyqBAw7Rk3uagLWwg T12_;
	tySet_tyInt__Gyb9a8b9cW9ajcJdvOmKvjVHg T13_;
	tySet_tyInt__k2exkv0Q69aCbdnoE2cGokw T14_;
	tySet_tyInt__2u8Uq5HtaeogMgqfa4aXjA T15_;
	tySet_tyInt__FVymwlTXJJuIEdfEEWohqQ T16_;
	tySet_tyInt__CMpw2LIG7xyd7BWQSMUkrA T17_;
	tySet_tyInt__9bnu9bWJHSuOHBI8SeKCKq8Q T18_;
	tySet_tyInt__L7d3SsMWppBX7mTg289boaw T19_;
	tySet_tyInt__1CBoeOL7R7QVzZn8Rhw6aA T20_;
	tySet_tyInt__2waXokKg0mAFnq388tVmuw T21_;
...
	tySet_tyInt__SXdOHTv3HD9ahQxNuY46ibA T8176_;
	tySet_tyInt__LzU43aEsSWJ51Vx44UNkeQ T8177_;
	tySet_tyInt__Uh0cI9cLrC2a8MqJggdeTjw T8178_;
	tySet_tyInt__9cFHpa8Ml4Cj9aLatkefNhIg T8179_;
	tySet_tyInt__9cgfRGWSw2iy9b2S6yIp4IWw T8180_;
	tySet_tyInt__k62S5LDtd9bskZ9cN3MuYDcg T8181_;
	tySet_tyInt__kIKxJRxS1FcIOlJDolVHKA T8182_;
	tySet_tyInt__mNBquj1kxw3otKBjj9bEfoA T8183_;
	tySet_tyInt__MRWrGe9bzN07F0D9aMsUhB1Q T8184_;
```
and then calls the mismatched cardinalities:
```nim
	nimZeroMem((void*)T1_, sizeof(tySet_tyInt__g3YNp45iiYwa623pyVq1UA));
	(void)(cardSet(T1_, 9));
	nimZeroMem((void*)T2_, sizeof(tySet_tyInt__R5WvQzcCA9c17vCAXfonIBQ));
	(void)(cardSet(T2_, 10));
	nimZeroMem((void*)T3_, sizeof(tySet_tyInt__OXp7sX03jzDKsHu8LcYKsA));
	(void)(cardSet(T3_, 11));
	nimZeroMem((void*)T4_, sizeof(tySet_tyInt__prtDISSCPSTv9c1fZwFJDtA));
	(void)(cardSet(T4_, 12));
	nimZeroMem((void*)T5_, sizeof(tySet_tyInt__9bRWsUpa0azIZIRpORylWIQ));
	(void)(cardSet(T5_, 13));
	nimZeroMem((void*)T6_, sizeof(tySet_tyInt__yuxREVOTigp3Kb8C8b5lDw));
	(void)(cardSet(T6_, 14));
	nimZeroMem((void*)T7_, sizeof(tySet_tyInt__ar0qt9aaXRKlsc9cpyAE0EZw));
	(void)(cardSet(T7_, 15));
	nimZeroMem((void*)T8_, sizeof(tySet_tyInt__QWsYllnqxPzf3hJulnqBcg));
	(void)(cardSet(T8_, 16));
	nimZeroMem((void*)T9_, sizeof(tySet_tyInt__eQ19av3k0epopaUa9cx9b2O3Q));
	(void)(cardSet(T9_, 17));
	nimZeroMem((void*)T10_, sizeof(tySet_tyInt__QKmKn9aOmB0uJ9a0eTme5bVw));
	(void)(cardSet(T10_, 18));
...
	nimZeroMem((void*)T8181_, sizeof(tySet_tyInt__k62S5LDtd9bskZ9cN3MuYDcg));
	(void)(cardSet(T8181_, 8189));
	nimZeroMem((void*)T8182_, sizeof(tySet_tyInt__kIKxJRxS1FcIOlJDolVHKA));
	(void)(cardSet(T8182_, 8190));
	nimZeroMem((void*)T8183_, sizeof(tySet_tyInt__mNBquj1kxw3otKBjj9bEfoA));
	(void)(cardSet(T8183_, 8191));
	nimZeroMem((void*)T8184_, sizeof(tySet_tyInt__MRWrGe9bzN07F0D9aMsUhB1Q));
	(void)(cardSet(T8184_, 8192));
```

This is just with `nim c -c`, and this might be excessive both in compile time for a test case (several seconds locally) and pushing things on the C side a bit much, but any random subset of this would be a reasonable expectation to have work in non-gimmick Nim code.

There's nothing wrong, on the C level, with just saying it's a `NU8*` with some length specified in the other parameter. I'm not sure what advantage is gained by claiming to the C compiler that the first parameter of `cardSet` is an array, specifically, rather than pointer. Or, if Nim's generics can be made to be part of the codegen, that'd be fine too. But hand-specifying 8000+ cases seems excessive.

**Comment by bung87** [comment]
that's a mess, I only see nim repo use `set[range['a' .. 'z']]` , maybe we just add check the size should be power of two.

**Comment by bung87** [comment]
CI fails un related

**Pull request merged**
