### PR TITLE
Deprecate not for integers and introduce ~

### LINKED ISSUE #1498: Gotcha with `not`.
``` nimrod
echo(not 0 >= 5)
```

Will output `false` because `not 0` is evaluated first as a bitwise not. @Araq mentioned on IRC the possibility of using `~` instead.

### PR DESCRIPTION
**Pull request by shmup**
Fixes #1498

### CODE REVIEW

**Comment by shmup** [comment]
Curious what I'm supposed to do in regards to these failures:

- https://travis-ci.org/nim-lang/Nim/jobs/249754090#L2560
- https://ci.appveyor.com/project/Araq/nim/build/1237#L2122

It's regarding this test: https://github.com/nim-lang/Nim/blob/devel/tests/concepts/t3330.nim#L40

**Comment by Araq** [comment]
Well you need to adapt the test, the line numbers changed because they refer to ``system.nim`` which you changed.

Also and more importantly: "bitwise not" is not common enough to be an operator IMO, it should be ``proc bnot`` instead and then perhaps ``band`` and ``bor`` and ``bxor`` for consistency. @dom96 what do you think? Ask on the forum?

**Comment by andreaferretti** [comment]
I agree it is not worth to reserve the `~` operator for this use. I like `bnot`, `band` and so on more.

That said, it may be worth to move all of them to `bitops` (with deprecations and so on)

**Comment by dom96** [comment]
So I actually dislike both ``~`` and ``bnot``. The former because Nim prefers words for these operations, the latter because the ``b`` could mean either ``bool`` or ``bitwise``.

So... Not sure what we should do.

**Comment by krux02** [comment]
well, I like to use `not` and  `and` and `or` on integers. Unlike C, Nim has a boolean type and static overloading, therefore the bitwise logic operations don't need to have a new name than the boolean logic operators (semantically one bit). Keeping `not` `and` and `or` is just consistent and introducing new names would only introduce problems. I vote to reject this pull request.

**Comment by dom96** [comment]
Yeah, I vote for rejecting this PR as well. Could we provide a warning for at least the common case where this is a gotcha? @Araq?

**Comment by Araq** [comment]
Warning about this is unresonably hard to implement. I think we can live with a wart that comes up once in a decade.

**Pull request closed without merging**
