### PR TITLE
cgen can now generate pretty-printed C/C++ files

### PR DESCRIPTION
**Pull request by timotheecour**
after this PR, simply add:
```
--cgenPostprocessCmd:"clang-format -i $#"
```
to your config files and the generated C/C++ files will look more readable; makes it easier when you need to look at generated C/C++ files

before: https://gist.github.com/timotheecour/ff834261e8f8e5e03aeec12871aab18d
after: https://gist.github.com/timotheecour/5d615ea453e177fb2d6f85ab395f44ae

note: users can customize the cmd to their liking, avoids any flame war on what's more readable.
It defaults to empty (= no re-formatting)

### CODE REVIEW

**Comment by Araq** [comment]
I thought you would create a PR for precise dependency tracking of ``.compile``'d files?

**Comment by timotheecour** [comment]
> I thought you would create a PR for precise dependency tracking of `.compile`'d files?

yes, it's on my (long) TODO list, but I don't see how that relates to this PR
for reference: https://github.com/nim-lang/RFCs/issues/510

**Comment by Araq** [comment]
Here is why it's related: I don't enjoy reviewing new compiler features nobody else asked for and so you need to argue first why it's worth adding. For me the difference between clang-format'ed generated C code and the old generated C code is underwhelming. Furthermore it never stops amazing me how all the Unix pipeline wizardry is incapable of doing a simple prostprocessing step on its own, without patching the Nim compiler.

**Comment by timotheecour** [comment]
refs https://github.com/nim-lang/Nim/pull/17103#discussion_r579569754

**Pull request closed without merging**
