### PR TITLE
better doc for hard to find --define:SYMBOL:VAL

### PR DESCRIPTION
**Pull request by timotheecour**
was hard to find
I'd even refer to https://nim-lang.org/docs/manual.html#implementation-specific-pragmas-compile-time-define-pragmas if that's not too long (personally I don't care about archaic 80 col width limit, but maybe some do)

### CODE REVIEW

**Comment by Varriount** [comment]
What is the `cf:` for?

**Comment by andreaferretti** [comment]
@Varriount It means "see". It is a standard abbreviation, much like i.e. or e.g.

**Comment by dom96** [comment]
From [Wikipedia](https://en.wikipedia.org/wiki/Cf.):

> It is recommended that "cf." be used only to suggest a comparison, and the word "see" be used to point to a source of information.

Cf. doesn't mean "see", it means "compare". You should use "see" instead, it's almost as short, and it's English so everyone should know what it means. Plus "Cf" isn't even correct.

**Comment by timotheecour** [comment]
done, PTAL

**Pull request merged**
