### PR TITLE
attempt to support short commit hashes

### PR DESCRIPTION
**Pull request by planetis-m**
Not sure if that's the correct way and what happens when the short hash matches "head"

### CODE REVIEW

**Comment by Araq** [comment]
Well it's ok to me. You tested it, right?

**Comment by planetis-m** [comment]
> Well it's ok to me. You tested it, right?

Yes, now its ready.

**Review by planetis-m — COMMENTED** [review]
Can I enable this error? (Line 213, GitHub doesn't allow me to comment on it)

**Comment by Araq** [comment]
> Can I enable this error? (Line 213, GitHub doesn't allow me to comment on it)

I think the next step would be to add tests via "mocking" the `exec` calls first. And then we can enable the check.

**Pull request merged**
