### PR TITLE
Do not use clone(2) if a process can setuid(2).

### PR DESCRIPTION
**Pull request by kubo39**
please see: https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87152373
I hope nobody uses this flag..

cc: @alaviss, because I guess you're familiar with *nix.

### CODE REVIEW

**Comment by alaviss** [comment]
`useClone` is the default if you're on Linux.

Now, I don't think we're affected by this at all, because we don't `setuid`, ever. See `startProcessAfterFork` for how the process spawning after `clone` is done.

**Comment by alaviss** [comment]
Now, there are a lot of problems with `vfork` that's unrelated to this `setuid` issue that we are certain to hit. From reading this [bug report](https://sourceware.org/bugzilla/show_bug.cgi?id=10354) it appears that musl libc has cracked the formula to be safe while using `vfork` and I believe we should learn from them.

**Comment by kubo39** [comment]
> Now, I don't think we're affected by this at all, because we don't setuid, ever. See startProcessAfterFork for how the process spawning after clone is done.

Ahh, first I thought startProcess uses `chidr` between fork and exec, but I'm still afraid that because the child's stack is allocated by the parent process.

> Now, there are a lot of problems with vfork that's unrelated to this setuid issue that we are certain to hit. From reading this bug report it appears that musl libc has cracked the formula to be safe while using vfork and I believe we should learn from them.

Exactly so, especially for signal handlers I described in comments.
glibc hit the problem: https://sourceware.org/bugzilla/show_bug.cgi?id=14750

**Comment by kubo39** [comment]
Hmm, startProcessAfterFork has race condition when the parent process in multi-threaded situation?

**Comment by alaviss** [comment]
> Hmm, startProcessAfterFork has race condition when the parent process in multi-threaded situation?

How so?

**Comment by kubo39** [comment]
Sorry, it's in startProcessAuxSpawn, not startProcessAfterFork.

**Comment by alaviss** [comment]
Aside from the `chdir` call, I don't think there's any problem?

Too bad `posix_spawn` API can't do `chdir` :P

**Comment by kubo39** [comment]
> Too bad posix_spawn API can't do chdir :P

AFAIK Solaris and glibc >= 2.29 only has API for it, but in case there's no portable way.

> Aside from the chdir call, I don't think there's any problem?

Hmm... I think this is bad and may cause an unexpected behavior when another threads see chdir()'ed directory silently, but I couldn't come up with a certain problem now.

**Comment by alaviss** [comment]
> Hmm... I think this is bad and may cause an unexpected behavior when another threads see chdir()'ed directory silently, but I couldn't come up with a certain problem now.

The bigger problem might be that we don't even `chdir` back to the old one :p 

Also, I think this bug in [python](https://bugs.python.org/issue35823) describes pretty well the shortcomings of `posix_spawn`.

**Comment by Araq** [comment]
I see nothing to "fix" with our code.

**Pull request closed without merging**
