### PR TITLE
Logger must respects global filter level

### PR DESCRIPTION
**Pull request by rgv151**

### CODE REVIEW

**Comment by reactormonk** [comment]
I think it's fine as it is, usually you want information from specific handlers, so you can filter for the logs which are useful to the current problem.

**Comment by rgv151** [comment]
I use a module, it writes a lot of DEBUG messages to console, there is no way to hide those messages cuz `setLogFilter` didn't work for Loggers

**Comment by reactormonk** [comment]
Could you post your code?

**Comment by rgv151** [comment]
try my `rethinkdb` module if you interesting

**Comment by dom96** [comment]
@Araq thoughts about this?

**Pull request merged**
