### PR TITLE
[Dont merge] Trying to fix appveyor

### PR DESCRIPTION
**Pull request by yglukhov**

### CODE REVIEW

**Comment by dom96** [comment]
Just FYI I disabled appveyor for now, seeing failures everywhere is annoying.

**Comment by yglukhov** [comment]
Ok this is getting ridiculous. Failed because of timeout :(

**Comment by dom96** [comment]
And I suppose increasing the timeout requires some payment? :)

**Comment by yglukhov** [comment]
Yep. What do you guys think of running the tests in parallel? Will it improve the time?

**Pull request closed without merging**
