### PR TITLE
attr feature

### PR DESCRIPTION
**Pull request by yglukhov**
This PR introduces a feature to Nim called "attr pragma". The intention is to let users annotate their definitions with types like it may be done with `tags` pragma, but unlike `tags`, `attr` doesn't have any meaning to the compiler. Also I have introduced a couple of macros to inspect such annotations. Usage example is in the test file, please read it first, especially the "advanced" part of it =). For now annotations may be placed on routines and object field declarations, but this is just an "experimental phase" restriction, we could allow `attrs` pretty much anywhere. I will add docs and news when this is reviewed. Thoughts?

### CODE REVIEW

**Comment by Araq** [comment]
Need to review it more carefully, but I love the feature.

**Comment by dom96** [comment]
Cool feature. What are you going to be using it for?

**Comment by yglukhov** [comment]
@dom96, here's a couple of use cases that comes to mind:
- Better auto serialization/deserialization control:
```nim
type MyObj = object
  a {.attrs: dontSerialize.}: int
  b {.attrs: defaultDeserialize[5].}: int
  c {.attrs: serializationKey["_c"].}: string
```
- Adopting type for gui inspector in a game engine:
```nim
type MyComponent = object
  position {.attrs: [editable, animatable].}: Vector3
  alpha {.attrs: [editable, animatable, editRange[0.0, 1.0]].}: float32
```
- ORM
```nim
type UserProfile {.attrs: dbCollection["profiles"].} = object
  name {.attrs: dbKey["n"].}: string
  state {.attrs: dbForeignKey["s"].}: SomeState
```
* Other domains, like REST/RPC API generation, etc...

**Comment by dom96** [comment]
@yglukhov Can't all of these use cases be handled by custom pragmas?

```
type MyObj = object
  a {.dontSerialize.}: int
  b {.defaultDeserialize: 5.}: int
  c {.serializationKey: "_c".}: string

```

etc.

**Comment by yglukhov** [comment]
@dom96, sure, but there's no such thing in Nim like custom pragmas. There are only pragma aliases which expand immediately, and don't follow namespace rules.

**Comment by yglukhov** [comment]
But i really like your syntax better. So here's another idea. What if we allow any object type name as pragma everywhere. With pragma arguments being used as generic arguments.
```
type
  MyAttr[S: static[string]] = object

type AnnotatedObj = object
  a {.MyAttr: "hi".}: int

var o: AnnotatedObj
assert(o.a.attrAt(o.a.findAttrIt(it is MyAttr)) is MyAttr["hi"])
```

I think it should not be that hard, and the syntax is more natural.

**Comment by yglukhov** [comment]
On the other hand, allowing objects as pragmas would be less consistent with proc pragmas where custom pragmas are macros/templates, so i don't really know what would be better. After all since pragmas are not really designed to be beautiful code, maybe consistency should be favored here, and as such, this PR should be ok =)

**Comment by Araq** [comment]
As an alternative to this feature, how about we change the pragma rules like so:

"Unrecognized pragmas do not cause compilation errors and remain in the AST."

That would allow for the same thing -- right, wrong?

**Comment by zah** [comment]
@Araq, the last proposal would turn any typos in the pragma's name into silent errors. Renaming a pragma may also produce a lot of dangling no-op usages.

How about extending the "pragma pragma" syntax to allow parameters:

``` nim
{.pragma: serializationKey(key: string, compressed: bool).}
```

Then an example usages is:

``` nim
type Foo = object
   myX {.serializationKey("x", compressed = true).}: string
```

And we can have a strongly-typed compile-time API for accessing these values:

``` nim
Foo.myX.getPragma("serializationKey").key # returns "x"
```

**Comment by yglukhov** [comment]
@zah, that's nice, but I don't like the `getPragma("serializationKey")` part for your own reasons. Instead it should be `getPragma(serializationKey)`, and as such `serializationKey` should be a symbol that follows namespace rules.

**Comment by Araq** [comment]
Pragmas should be mapped to templates/macos, not types as they already are for proc annotations. This solves the namespacing and is consistent with the rest of the language and does introduce typo resistance.

**Comment by zah** [comment]
@Araq, what is the specific proposal then? 

How are attributes attached to fields and what is the API for detecting and reading these attributes in some code that iterates over all fields for example?

**Comment by cooldome** [comment]
Thumb up on this feature, really useful. What do we need to bring this forward?

**Comment by Araq** [comment]
IMHO this feature should work like this:

```nim

import macros

template myAttr(): untyped {.pragma.}

block:
  proc myProc() {.myAttr.} = discard
  const myAttrExists = myProc.hasPragma(myAttr)
  assert(myAttrExists)

block:
  type MyObj = object
    myField {.myAttr.}: int
  var o: MyObj
  assert o.myField.hasPragma(myAttr)

block: # A bit more advanced case
  template serializationKey(s: static[string]) {.pragma.}
  template defaultValue(V: static[typed]) {.pragma.}

  type MySerializable = object
    a {.serializationKey: "asdf", defaultValue: 5.} : int
    b {.defaultValue: "hello".} : int

  var s: MySerializable

  const aDefVal = s.a.getPragmaVal(defaultValue)
  doAssert(aDefVal == 5)
```

**Comment by cooldome** [comment]
Looks good. Just to understand nim's internals better, quick question. Why did you choose templates for pragmas implementation?

**Comment by yglukhov** [comment]
@Araq 👍, but looks harder to implement. I'll see what I can do.

**Comment by zah** [comment]
@Araq, I think we should also support pragmas with multiple parameters.

The parameter names can be used to access the individual values as in my previous proposal:

``` nim
const aDefVal = s.a.getPragma(defaultValue).V
```

Is the lack of body the only thing that will discriminate these attribute-attaching no-op macros. Someone may try to forward-declare a pragma macro, which under this scheme should probably be an error at the body definition site.

**Comment by zah** [comment]
I guess another discriminator could be the lack of return type.

**Comment by Araq** [comment]
> Is the lack of body the only thing that will discriminate these attribute-attaching no-op macros? 

No, it's caused by the {.pragma.} annotation.

**Comment by Araq** [comment]
>  Just to understand nim's internals better, quick question. Why did you choose templates for pragmas implementation?

Has nothing to do with the implementation and as @yglukhov said "it's harder to implement". It's however a design that fits Nim better. We can already invoke macros/templates via  ``proc p() {.customThing.}``

**Comment by dom96** [comment]
Why do we need the ``{.pragma.}`` annotation? Aren't all macros/templates available as pragmas implicitly already?

**Comment by Araq** [comment]
> Why do we need the {.pragma.} annotation? Aren't all macros/templates available as pragmas implicitly already?

We need to know these templates are not to be expanded and kept in the AST for later introspection.

**Comment by yglukhov** [comment]
Closing in favor of #6987

**Pull request closed without merging**
