### PR TITLE
followup #18379: nim secret issues a warning on symbol redefinition

### PR DESCRIPTION
**Pull request by timotheecour**
follows https://github.com/nim-lang/Nim/pull/18379 which changed semantics on redefinition, refs https://github.com/nim-lang/Nim/pull/18379#issuecomment-869863606

this PR adds a warning; in this simple example it's obvious something was redefined, but in more complex examples this could be un-intentional. In any case, warnings are easy to shut off if needed

## before PR
```nim
nim secret
>>> var a = 1
>>> var a = "foo"
>>> echo a
foo
```

## after PR
```nim
nim secret
>>> var a = 1
>>> var a = "foo"
stdin(2, 5) Warning: redefinition of 'a'; previous declaration here: stdin(1, 5) [User]
/Users/timothee/git_clone/nim/Nim_prs/compiler/lookups.nim(293, 13) compiler msg initiated here [MsgOrigin]
>>> echo a
foo
```

I'd be ok with using a different warning though; errors/warnings/hints scale well, it's just an enum and growing it doesn't impact performance in a meaningful way.

### CODE REVIEW

**Comment by Araq** [comment]
`warnUser` is the wrong warning category though and I deliberately programmed it this way to produce no error as it's very common in the REPL.

**Comment by timotheecour** [comment]
PTAL, now using warnRedefinitionRepl

>  I deliberately programmed it this way to produce no error 

well the behavior until recently was to produce no error and also not update the symbol, which (in conjuciton) didn't make sense (silently do nothing)

**Comment by Araq** [comment]
> well the behavior until recently was to produce no error and also not update the symbol, which (in conjuciton) didn't make sense (silently do nothing)

That wasn't originally the case, when I wrote it 10 years ago, the symbol would get updated. But the REPL has no test coverage... Which is also why REPLs and hot code reloading are a bad idea for Nim's current manpower.

**Comment by timotheecour** [comment]
>  But the REPL has no test coverage... 

I added some in trunner. Coverage should increase, but it's better than nothing.

> Which is also why REPLs and hot code reloading are a bad idea for Nim's current manpower.

REPL's are incredibly useful, when they work (ipython, matlab, maple, mathematica, and now cling for C++, are all very useful tools for interactive programming). `nim secret` is currently the only repl we have (inim isn't a true repl since it re-evaluates everything on each cmd) and needs compiler support (compilerapi isn't enough) so we should improve what we have (and I've sent out a few PRs in support of it). If it could be split off, that'd be great, but it'd still need compiler support in various places.

As for HCR, well, it's a bit of a sad story, good potential but half baked and some tests have since been disabled.

**Pull request closed without merging**
