### PR TITLE
scoped memory management

### PR DESCRIPTION
**Pull request by Araq**
PR to make destructor injections scope-based. This produces faster, smaller code for destructors and hence ARC/ORC.

### CODE REVIEW

**Comment by timotheecour** [comment]
@Araq since there is no PR description or comments that I could find, I'm asking here:

is this PR implementing the following change:
function based dtor => scope based dtor?

is the "after PR" snippet below what this PR will do?
```nim
when defined case2:
  type Foo = object
    x: int
  proc `=destroy`(a: var Foo) =
    echo ("in dtor", a.x)
  proc initFoo(x: int): Foo =
    echo ("in initFoo", x)
    result = Foo(x: x)
  proc main() =
    var a1 = initFoo(1)
    block:
      var a2 = initFoo(2)
    var a3 = initFoo(3)
  main()
```

before PR:
```
("in initFoo", 1)
("in initFoo", 2)
("in initFoo", 3)
("in dtor", 3)
("in dtor", 2)
("in dtor", 1)
```

after PR:
```
("in initFoo", 1)
("in initFoo", 2)
("in dtor", 2)
("in initFoo", 3)
("in dtor", 3)
("in dtor", 1)
```

(the function based dtor always seemed bizarre to me, so this would bring behavior closer to C++/D  and other languages with RAII)

**Comment by Araq** [comment]
Yes, exactly. Unfortunately it's quite away from being mergable as you can see in the many failing test cases. I think we need more codegen patches to handle it well. I think it's time to turn a Rope into a "C++ IR AST".

**Comment by Araq** [comment]
But hey, at least the code is much cleaner now.

**Comment by timotheecour** [comment]
* I remember (but can't find where) that you once said the rationale for function based destructor was for efficiency reasons; but I never understood why; in any case I'm curious whether this argument is completely gone.

* this is perhaps relevant for this PR: https://github.com/nim-lang/Nim/issues/14604, in particular the following proposal:
> don't call destructor for a variable that was not initialized or default-initialized
> This requires tracking which variables are default-initialized or un-initialized, which would also be useful for #14602

**Comment by Araq** [comment]
The performance argument was mostly about "hmmm at least it produces only 1 setjmp for the 1 implicit try-finally". With goto based exceptions that's gone and scopes win.

**Comment by ghost** [comment]
Are we supposed to test this PR yet or not? :)
For a small example of broken code:
```nim
# a.nim
proc eval*() =
  if 1 != 0: return
  let args = @[1] # Error: internal error: expr: var not init args_3330013

# b.nim
import a
eval()
```

```nim
if true:
  return
let args = [1]
destructor is 3330027 proc `=destroy`(dest): =
  var :tmp_3330032 = 0
  while `<`(:tmp_3330032, len(dest)):
    inc(:tmp_3330032, 1)
  destroy(dest)

>---------transformed-to--------->

var :tmpD_3330726
try:
  if true:
    return
  let args_3330013 =
    wasMoved_3330727(:tmpD_3330726)
    `=_3330036`(:tmpD_3330726, [1])
    :tmpD_3330726
finally:
  `=destroy_3330027`(args_3330013)

```
shouldn't finally destroy :tmpD_3330726 instead?

**Comment by Araq** [comment]
You're supposed to help me with this. :P

**Comment by ghost** [comment]
Another one:
```nim
type
  Chunk = ref object

  VM = ref object
    chunk: Chunk

  Compiler = ref object
    compilingChunk: Chunk

proc compile(chunk: Chunk): bool = 
  var c = Compiler(compilingChunk: chunk)
  result = true

proc interpret(vm: VM) = 
  var chunk = Chunk()

  if not compile(chunk): # Error: internal error: expr: temp not init :tmpD_3327170
    return

  vm.chunk = chunk

var vm = VM()

vm.interpret()
```

<details>
  <summary>toDebug output for interpret</summary>

   ```nim
  ### interpret:
  CFG:
    0 def	chunk	#15
    1 use	chunk	#17
    2 fork	L5	#18
    3 goto	L8	#18
    4 goto	L5	#18
  L5:
    5 use	chunk	#20
    6 use	vm.chunk	#20
    7 goto	L9	#0
  L8:
    8 goto	L9	#0
  L9: End


  var chunk = Chunk()
  if not compile(chunk):
    return
  vm.chunk = chunk
  destructor is 3327034 proc `=destroy`(dest): =
    if nimDecRefIsLast(dest):
      nimRawDispose(dest)
    dest = nil

  starting point for chunk is 1 nkSym
  ugh false false
  starting point for chunk is 5 nkSym
  ugh true true
  starting point for chunk is 5 nkSym
  ugh true true
  >---------transformed-to--------->

  try:
    var chunk_3327086 = Chunk_3327002()
    if not_1188105 compile_3327016:
      wasMoved_3327171(:tmpD_3327170)
      `=_3327039`(:tmpD_3327170, chunk_3327086)
      :tmpD_3327170:
      var :tmpD_3327170
      try:
        return
      finally:
    `=sink_3327044`(vm_3327085.chunk_3327011, chunk_3327086)
    wasMoved_3327175(chunk_3327086)
  finally:
    wasMoved_3327173(chunk_3327086)
    `=destroy_3327034`(chunk_3327086)
```

  
</details>

**Comment by Araq** [comment]
Excellent!

**Comment by ghost** [comment]
Another short one (from unittest):
```nim
type
  OutputLevel* = enum All, None

var outputLevel = OutputLevel.All
if $outputLevel == "badabum": # Error: internal error: expr: temp not init :tmpD_3327042
  outputLevel = None
```

<details>
  <summary>toDebug output for interpret</summary>

   ```nim
  ### a:
  CFG:
    0 def	outputLevel	#4
    1 use	outputLevel	#5
    2 fork	L5	#6
    3 def	outputLevel	#6
    4 goto	L5	#6
  L5:
    5 goto	L6	#0
  L6: End


  type
    OutputLevel = enum
      All, None
  var outputLevel = All
  if $outputLevel == "asd":
    outputLevel = None
  destructor is 1590038 proc `=destroy`(dest): =
    destroy(dest)

  >---------transformed-to--------->

  type
    OutputLevel_3327002 = enum
      All_3327004, None_3327005
  var outputLevel_3327007 = All
  if
    :tmpD_3327042 = $_3327008outputLevel_3327007
    :tmpD_3327042 ==_1191780
      "asd":
    var :tmpD_3327042
    outputLevel_3327007 = None
    `=destroy_1590038`(:tmpD_3327042)

```

  
</details>

**Comment by ghost** [comment]
Actually just
```nim
var outputLevel = 5
if $outputLevel == "badabum": # Error: internal error: expr: temp not init :tmpD_3327019
  outputLevel = 3
```

**Comment by ghost** [comment]
```nim
type
  VM = ref object
    val: string
  
proc push(vm: VM, data: string) = 
  vm.val = data

proc test(vm: VM) =
  if not true:
    # works without return here
    return
  let res = "hi"
  vm.push(res) # Error: internal error: expr: var not init res_3327028

let vm = VM()
vm.test()
```

<details>
  <summary>toDebug</summary>

```nim
### test:
CFG:
	0 fork	L3	#11
	1 goto	L7	#11
	2 goto	L3	#11
L3:
	3 def	res	#12
	4 use	vm	#13
	5 use	res	#13
	6 goto	L8	#0
L7:
	7 goto	L8	#0
L8: End


if false:
  return
let res = "hi"
push(vm, res)
destructor is 1590038 proc `=destroy`(dest): =
  destroy(dest)

starting point for res is 5 nkSym
ugh true true
>---------transformed-to--------->

try:
  if false:
    return
  let res_3327028 = "hi"
  push_3327007(vm_3327027, res_3327028)
finally:
  wasMoved_3327098(res_3327028)
  `=destroy_1590038`(res_3327028)

```

</details>

**Comment by ghost** [comment]
```nim
type
  MathExpression = object
    # For some reason need this specific field layout
    e: int
    input: string
    len: int
    ch: char
  
  Evaluator = ref object

proc newEvaluator: Evaluator =
  Evaluator()

proc eval(e: Evaluator, input: string) =
  if input.len == 0:
    raise newException(ValueError, "The line is empty!")

  # this is required
  var expr = MathExpression()

proc main = 
  # so is this
  let e = newEvaluator()
  e.eval("")

main()
```

<details>
  <summary>toDebug</summary>

```nim
### eval:
CFG:
	0 use	input	#15
	1 fork	L4	#16
	2 goto	L9223372036854775807	#16
	3 goto	L4	#16
L4:
	4 def	expr	#19
	5 goto	L6	#0
L6: End


if len(input) == 0:
  raise
    (ref ValueError)(msg: "The line is empty!", parent: nil)
var expr = MathExpression()
destructor is 3330063 proc `=destroy`(dest): =
  `=destroy`(dest.input)

>---------transformed-to--------->

try:
  if len_1194807(input_3327064) ==_1191920 0:
    raise
      (ref ValueError_1194042)(msg_1194126: "The line is empty!", parent_1194124: nil)
  var expr_3330002 = MathExpression_3327002()
finally:
  `=destroy_3330063`(expr_3330002)
````


</details>


<details>
  <summary>For some weird reason doesn't trigger under ``--debugger:native``. Compiled with ``-d:useMalloc`` for some more info</summary>

With useMalloc:
```nim
double free or corruption (out)
Traceback (most recent call last)
/home/dian/Projects/nim-mathexpr/a2.nim(26) a2
/home/dian/Projects/nim-mathexpr/a2.nim(24) main
/home/dian/Projects/nim-mathexpr/a2.nim(17) eval
SIGABRT: Abnormal termination.
```

Without:
```nim
Traceback (most recent call last)
/home/dian/Projects/nim-mathexpr/a2.nim(26) a2
/home/dian/Projects/nim-mathexpr/a2.nim(24) main
/home/dian/Projects/nim-mathexpr/a2.nim(17) eval
/home/dian/Things/Nim/lib/system/alloc.nim(972) dealloc
/home/dian/Things/Nim/lib/system/alloc.nim(871) rawDealloc
/home/dian/Things/Nim/lib/system/avltree.nim(74) del
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

</details>
Maybe Linux-specific, I don't know :)

EDIT: Compiled with `-d:useSysAssert`, got:
```nim
[SYSASSERT] rawAlloc: requested size too small
```

**Comment by ghost** [comment]
After adding
```nim
  cprintf("size to alloc: %d, sizeof(FreeCell): %d\n", requestedSize, sizeof(FreeCell))
```
to line 752 in alloc.nim I get:
```
size to alloc: 9, sizeof(FreeCell): 16
[SYSASSERT] rawAlloc: requested size too small
```

**Comment by ghost** [comment]
Without sysassert but with clang sanitizers (they work with debugger: native)
```nim
size to alloc: 9, sizeof(FreeCell): 16
size to alloc: 72, sizeof(FreeCell): 16
size to alloc: 32, sizeof(FreeCell): 16
==18336==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55a43cc72e0f in eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ /home/dian/Things/Nim/lib/system/fatal.nim:49:16
    #1 0x55a43cc7bd36 in eqdestroy___x9ctd6v5t4DqIi9bHbFwQvkA /home/dian/Projects/nim-mathexpr/a2.nim:19:2
    #2 0x55a43cc7bd36 in eval__bWoOHwtZcF9cD9b5Iarrsz0g /home/dian/Projects/nim-mathexpr/a2.nim:19:3
    #3 0x55a43cc7c290 in main__ayPqW1uT2XM0WP9ccKSkYqA /home/dian/Projects/nim-mathexpr/a2.nim:24:2
    #4 0x55a43cc7c435 in NimMainModule /home/dian/Projects/nim-mathexpr/a2.nim:26:2
    #5 0x55a43cc7c435 in NimMainInner /home/dian/Things/Nim/lib/system.nim:2130:2
    #6 0x55a43cc7c5dd in NimMain /home/dian/Things/Nim/lib/system.nim:2138:2
    #7 0x55a43cc7c5dd in main /home/dian/Things/Nim/lib/system.nim:2145:2
    #8 0x7f369375e001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
    #9 0x55a43cbe40ad in _start (/home/dian/Projects/nim-mathexpr/a2+0x2e0ad)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/dian/Things/Nim/lib/system/fatal.nim:49:16 in eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ
Exiting
```

**Comment by ghost** [comment]
Not sure if same as previous:
```nim
proc newClosIter(s: string): iterator(): char =
  result = iterator(): char =
    for i in s:
      yield i

proc parse(code: string) =
  let iter = newClosIter(code)
  for x in iter():
    echo x

proc main = 
  let code = "test"
  code.parse()

main()
```

```nim
Traceback (most recent call last)
/home/dian/Projects/benchmarks/brainfuck/bf.nim(15) bf
/home/dian/Projects/benchmarks/brainfuck/bf.nim(13) main
/home/dian/Projects/benchmarks/brainfuck/bf.nim(8) parse
/home/dian/Things/Nim/lib/system/iterators.nim(218) :anonymous
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

and clang with useMalloc and sanitizers:
```
==15956==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x562c3d5cad53 in colonanonymous___tZNMocVIewqJ9awVdDINXbw /home/dian/Projects/benchmarks/brainfuck/bf.nim:4:45
    #1 0x562c3d5d01bb in parse__5Y9cHu2I4orFdaIe6KDSuwg /home/dian/Projects/benchmarks/brainfuck/bf.nim:8:8
    #2 0x562c3d5d1440 in main__s2go3HPotlpm2exihiAy4g /home/dian/Projects/benchmarks/brainfuck/bf.nim:13:2
    #3 0x562c3d5d1ef9 in NimMainModule /home/dian/Projects/benchmarks/brainfuck/bf.nim:15:2
    #4 0x562c3d5d1bf8 in NimMainInner /home/dian/Things/Nim/lib/system.nim:2131:2
    #5 0x562c3d5d2090 in NimMain /home/dian/Things/Nim/lib/system.nim:2139:2
    #6 0x562c3d5d2208 in main /home/dian/Things/Nim/lib/system.nim:2146:2
    #7 0x7f25cd75e001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
    #8 0x562c3d5180bd in _start (/home/dian/Projects/benchmarks/brainfuck/bf+0x310bd)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/dian/Projects/benchmarks/brainfuck/bf.nim:4:45 in colonanonymous___tZNMocVIewqJ9awVdDINXbw
Exitin
```

**Comment by ghost** [comment]
```nim
proc unpack: seq[string] = 
  @["hello", "world", "three"]

proc extractAllLocations() =
  if false: return
  let tokens = unpack()
  let (ccStr, coordStr, tzName) = (tokens[0], tokens[1], tokens[2]) # Error: internal error: expr: var not init tokens_3267032

extractAllLocations()
```

<details>
  <summary>toDebug</summary>

```nim
### extractAllLocations:
CFG:
        0 fork  L3      #5
        1 goto  L11     #5
        2 goto  L3      #5
L3:
        3 def   tokens  #6
        4 use   tokens[0]       #7
        5 use   tokens[1]       #7
        6 use   tokens[2]       #7
        7 def   ccStr   #7
        8 def   coordStr        #7
        9 def   tzName  #7
        10 goto L12     #0
L11:
        11 goto L12     #0
L12: End


if false:
  return
let tokens = unpack()
let (ccStr, coordStr, tzName) = (tokens[0], tokens[1], tokens[2])
destructor is 1690835 proc `=destroy`(dest): =
  var :tmp_1690840 = 0
  while `<`(:tmp_1690840, len(dest)):
    `=destroy`(dest[:tmp_1690840])
    inc(:tmp_1690840, 1)
  destroy(dest)

destructor is 3267050 proc `=destroy`(dest): =
  `=destroy`(dest[0])
  `=destroy`(dest[1])
  `=destroy`(dest[2])

starting point for tokens[0] is 4 nkBracketExpr
ugh true true
starting point for tokens[1] is 5 nkBracketExpr
ugh true true
starting point for tokens[2] is 6 nkBracketExpr
ugh true true
destructor is 1590038 proc `=destroy`(dest): =
  destroy(dest)

starting point for :tmp_3267091[0] is -1 nkBracketExpr
destructor is 1590038 proc `=destroy`(dest): =
  destroy(dest)

starting point for :tmp_3267091[1] is -1 nkBracketExpr
destructor is 1590038 proc `=destroy`(dest): =
  destroy(dest)

starting point for :tmp_3267091[2] is -1 nkBracketExpr
>---------transformed-to--------->

var
  :tmpD_3267097
  :tmpD_3267101
  :tmpD_3267105
try:
  if false:
    return
  let tokens_3267032 = unpack_3267002()
  var :tmp_3267091 = (tokens_3267032[0], tokens_3267032[1], tokens_3267032[2])
  var ccStr_3267034 =
    wasMoved_3267098(:tmpD_3267097)
    `=_1590044`(:tmpD_3267097, :tmp_3267091[0])
    :tmpD_3267097
  var coordStr_3267035 =
    wasMoved_3267102(:tmpD_3267101)
    `=_1590044`(:tmpD_3267101, :tmp_3267091[1])
    :tmpD_3267101
  var tzName_3267036 =
    wasMoved_3267106(:tmpD_3267105)
    `=_1590044`(:tmpD_3267105, :tmp_3267091[2])
    :tmpD_3267105
finally:
  wasMoved_3267093(tokens_3267032[0])
  wasMoved_3267094(tokens_3267032[1])
  wasMoved_3267095(tokens_3267032[2])
  `=destroy_1690835`(tokens_3267032)
  `=destroy_3267050`(:tmp_3267091)
  `=destroy_1590038`(ccStr_3267034)
  `=destroy_1590038`(coordStr_3267035)
  `=destroy_1590038`(tzName_3267036)
```

</details>

**Comment by ghost** [comment]
Found from `osproc.startProcess`:
```nim
proc main = 
  var a = allocCStringArray(@["a", "b", "c"])
  a.deallocCStringArray()

main()
```

Error:
```
/home/dian/.cache/nim/ba_r/stdlib_system.nim.c: In function ‘allocCStringArray__LjSatDbwrF5hMmOARlJhEw’:
/home/dian/.cache/nim/ba_r/stdlib_system.nim.c:2075:43: error: ‘colontmpD_Len_0’ undeclared (first use in this function); did you mean ‘colontmpD_’?
 2075 |  eq___il9azw7IMqGldOhrQBMRqpg(colontmpD_, colontmpD_Len_0, a, aLen_0);
      |                                           ^~~~~~~~~~~~~~~
      |                                           colontmpD_
```

<details>
  <summary>Relevant C code</summary>

```c
N_LIB_PRIVATE N_NIMCALL(NCSTRING*, allocCStringArray__LjSatDbwrF5hMmOARlJhEw)(NimStringV2* a, NI aLen_0) {
	NCSTRING* result;
	NimStringV2* colontmpD_;
	void* T1_;
	NimStringV2* x;
	result = (NCSTRING*)0;
	colontmpD_ = (NimStringV2*)0;
	T1_ = (void*)0;
	T1_ = alloc0Impl__KzdpcuLT9aef9bsiSHlIu9aFg_3(((NI) ((NI)((NI)(aLen_0 + ((NI) 1)) * ((NI) 8)))));
	result = ((NCSTRING*) (T1_));
	colontmpD_ = 0;
	eq___il9azw7IMqGldOhrQBMRqpg(colontmpD_, colontmpD_Len_0, a, aLen_0);
	x = ((NimStringV2*) (colontmpD_));
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (aLen_0-1);
		res = ((NI) 0);
		{
			while (1) {
				void* T5_;
				if (!(res <= colontmp_)) goto LA4;
				i = res;
				T5_ = (void*)0;
				T5_ = alloc0Impl__KzdpcuLT9aef9bsiSHlIu9aFg_3(((NI) ((NI)(x[i].len + ((NI) 1)))));
				result[i] = ((NCSTRING) (T5_));
				copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) (result[i])), ((void*) ((&x[i].p->data[((NI) 0)]))), ((NI) (x[i].len)));
				res += ((NI) 1);
			} LA4: ;
		}
	}
	return result;
}
```

</details>


<details>
  <summary>toDebug, not sure if needed</summary>

```nim
### allocCStringArray:
CFG:
	0 use	a	#2181
	1 def	result	#2181
	2 use	a	#2183
	3 def	x	#2183
	4 use	a	#2184
	5 def	:tmp_3327065	#66
	6 def	res	#77
	7 use	res	#78
	8 use	:tmp_3327065	#78
	9 fork	L58	#78
	10 use	res	#79
	11 def	i	#2184
	12 use	i	#2185
	13 use	x[i]	#2185
	14 use	i	#2185
	15 use	i	#2185
	16 use	result[i]	#2185
	17 use	i	#2186
	18 use	result[i]	#2186
	19 use	i	#2186
	20 use	addr(x[i][0])	#2186
	21 use	i	#2186
	22 use	x[i]	#2186
	23 use	res	#80
	24 use	res	#78
	25 use	:tmp_3327065	#78
	26 fork	L58	#78
	27 use	res	#79
	28 def	i	#2184
	29 use	i	#2185
	30 use	x[i]	#2185
	31 use	i	#2185
	32 use	i	#2185
	33 use	result[i]	#2185
	34 use	i	#2186
	35 use	result[i]	#2186
	36 use	i	#2186
	37 use	addr(x[i][0])	#2186
	38 use	i	#2186
	39 use	x[i]	#2186
	40 use	res	#80
	41 use	res	#78
	42 use	:tmp_3327065	#78
	43 fork	L58	#78
	44 use	res	#79
	45 def	i	#2184
	46 use	i	#2185
	47 use	x[i]	#2185
	48 use	i	#2185
	49 use	i	#2185
	50 use	result[i]	#2185
	51 use	i	#2186
	52 use	result[i]	#2186
	53 use	i	#2186
	54 use	addr(x[i][0])	#2186
	55 use	i	#2186
	56 use	x[i]	#2186
	57 use	res	#80
L58:
	58 goto	L59	#0
L59:
	59 goto	L60	#0
L60:
	60 goto	L61	#0
L61:
	61 use	result	#2178
	62 goto	L63	#0
L63: End


## Creates a NULL terminated cstringArray from `a`. The result has to
## be freed with `deallocCStringArray` after it's not needed anymore.
result = cast[cstringArray](
  discard
  alloc0Impl(chckRange((len(a) + 1) * 8, 0, 9223372036854775807)))
let x = cast[ptr UncheckedArray[string]](a)
block :tmp3327063:
  var
    i
    :tmp_3327065
  :tmp_3327065 = high(a)
  ## An alias for `countup(a, b, 1)`.
  ## 
  ## See also:
  ## * [..<](#..<.i,T,T)
  ## 
  ## .. code-block:: Nim
  ##   for i in 3 .. 7:
  ##     echo i # => 3; 4; 5; 6; 7
  var res = 0
  block :tmp3327072:
    while res <= int(:tmp_3327065):
      i = T(res)
      result[i] = cast[cstring](
        discard
        alloc0Impl(chckRange(len(x[i]) + 1, 0, 9223372036854775807)))
      copyMem(result[i], addr(x[i][0]),
              chckRange(len(x[i]), 0, 9223372036854775807))
      inc(res, 1)
>---------transformed-to--------->

var :tmpD_3327075
## Creates a NULL terminated cstringArray from `a`. The result has to
## be freed with `deallocCStringArray` after it's not needed anymore.
result_1695205 = cast[cstringArray_1216429](
  discard
  alloc0Impl_1225404(chckRange((len_1695206(a_1695204) +_1190646 1) *_1190686 8, 0,
                               9223372036854775807)))
let x_1705003 = cast[ptr UncheckedArray_1189047[string_1188014]](
  wasMoved_3327076(:tmpD_3327075)
  `=_3327038`(:tmpD_3327075, a_1695204)
  :tmpD_3327075)
block :tmp3327063_3327063:
  var i_1705017
  var :tmp_3327065
  :tmp_3327065 = high_1705004(a_1695204)
  ## An alias for `countup(a, b, 1)`.
  ## 
  ## See also:
  ## * [..<](#..<.i,T,T)
  ## 
  ## .. code-block:: Nim
  ##   for i in 3 .. 7:
  ##     echo i # => 3; 4; 5; 6; 7
  var res_3327070 = 0
  block :tmp3327072_3327072:
    while res_3327070 <=_1191940 int_1188045(:tmp_3327065):
      i_1705017 = T_1690618(res_3327070)
      result_1695205[i_1705017] = cast[cstring_1188016](
        discard
        alloc0Impl_1225404(chckRange(len_1194807(x_1705003[i_1705017]) +_1190646 1,
                                     0, 9223372036854775807)))
      copyMem_1225208(result_1695205[i_1705017], addr(x_1705003[i_1705017][0]),
                      chckRange(len_1194807(x_1705003[i_1705017]), 0,
                                9223372036854775807))
      inc_1345064(res_3327070, 1)
```
</details>

**Comment by ghost** [comment]
From unittest:
```nim
type
  TestResult = object
    suiteName: string

let testSuiteName = "hello"

let testResult = TestResult(
  suiteName: testSuiteName
)

```

Error:
```c
/home/dian/.cache/nim/a_r/@ma.nim.c: In function ‘NimMainModule’:
/home/dian/.cache/nim/a_r/@ma.nim.c:134:46: error: assignment of member ‘len’ in read-only object
  134 |  testSuiteName__9b1anH9cQLXBu6vmShjtZrLA.len = 0; testSuiteName__9b1anH9cQLXBu6vmShjtZrLA.p = NIM_NIL;
      |                                              ^
/home/dian/.cache/nim/a_r/@ma.nim.c:134:93: error: assignment of member ‘p’ in read-only object
  134 |  testSuiteName__9b1anH9cQLXBu6vmShjtZrLA.len = 0; testSuiteName__9b1anH9cQLXBu6vmShjtZrLA.p = NIM_NIL;
      |   
```

<details>
<summary>C code</summary>

```c
/* Generated by Nim Compiler v1.3.5 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing -fno-ident  -I/home/dian/Things/Nim/lib -I/home/dian/Stuff/arctests -o /home/dian/.cache/nim/a_r/@ma.nim.c.o /home/dian/.cache/nim/a_r/@ma.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
#define nimfr_(x, y)
#define nimln_(x, y)

/* section: NIM_merge_FORWARD_TYPES */
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_TestResult__S6gHcZ9cOTOWEpjueh9cE27Q tyObject_TestResult__S6gHcZ9cOTOWEpjueh9cE27Q;

/* section: NIM_merge_TYPES */
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct tyObject_TestResult__S6gHcZ9cOTOWEpjueh9cE27Q {
NimStringV2 suiteName;
};

/* section: NIM_merge_PROC_HEADERS */
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___tCofevtpaYkqdmg3nSSuyQ)(tyObject_TestResult__S6gHcZ9cOTOWEpjueh9cE27Q* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);

/* section: NIM_merge_DATA */
static  struct {
  NI cap; NIM_CHAR data[5+1];
} TM__R8RUzYq41iOx0I9bZH5Nyrw_2 = { 5 | NIM_STRLIT_FLAG, "hello" };

/* section: NIM_merge_VARS */
N_LIB_PRIVATE NIM_CONST NimStringV2 testSuiteName__9b1anH9cQLXBu6vmShjtZrLA = {5, (NimStrPayload*)&TM__R8RUzYq41iOx0I9bZH5Nyrw_2};
N_LIB_PRIVATE tyObject_TestResult__S6gHcZ9cOTOWEpjueh9cE27Q testResult__wchfqGJgWTqqo66tN0h4eg;
extern NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;

/* section: NIM_merge_PROCS */
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___tCofevtpaYkqdmg3nSSuyQ)(tyObject_TestResult__S6gHcZ9cOTOWEpjueh9cE27Q* dest) {
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).suiteName));
}
static N_INLINE(void, initStackBottomWith)(void* locals) {
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
	void (*volatile inner)(void);
	inner = PreMainInner;
	systemInit000();
	(*inner)();
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
NIM_BOOL* nimErr_;
nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&testResult__wchfqGJgWTqqo66tN0h4eg), sizeof(tyObject_TestResult__S6gHcZ9cOTOWEpjueh9cE27Q));
	testResult__wchfqGJgWTqqo66tN0h4eg.suiteName = testSuiteName__9b1anH9cQLXBu6vmShjtZrLA;
	testSuiteName__9b1anH9cQLXBu6vmShjtZrLA.len = 0; testSuiteName__9b1anH9cQLXBu6vmShjtZrLA.p = NIM_NIL;
	eqdestroy___tCofevtpaYkqdmg3nSSuyQ((&testResult__wchfqGJgWTqqo66tN0h4eg));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&testSuiteName__9b1anH9cQLXBu6vmShjtZrLA));
	BeforeRet_: ;
	nimTestErrorFlag();
}
}



```
</details>

**Pull request merged**
