### PR TITLE
fixes #14665; fixes #19150; NimNode.add now returns void

### LINKED ISSUE #14665: wrong error: `is of type 'NimNode' and has to be used (or discarded)` in else branch
This code is mostly self-explanatory, I really don't understand why that error happens :)

### Example
```nim
import macros

macro test*(): untyped =   
  let b = @[1, 2, 3, 4]

  result = nnkStmtList.newTree()
  var i = 0
  while i < b.len:
    if false:
      # this quote do is mandatory, removing it fixes the problem
      result.add quote do:
        let testtest = 5
    else:
      result.add quote do:
        let test = 6
      inc i
      # removing this continue fixes the problem too
      continue
    inc i

test()
```

### Current Output
```
/home/dian/Projects/nim-snippets/tt.nim(14, 7) Error: expression '
add(result, getAst(`:anonymous`(newIdentNode("result"))))
inc i, 1
continue' is of type 'NimNode' and has to be used (or discarded); start of expression here: /home/dian/Projects/nim-snippets/tt.nim(9, 5)
```

### Expected Output
No error

## Additional information
Confirmed that it worked in 1.0.6 via the playground.

```
$ nim -v
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-06-14
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: d749c8cd87508871dc28b528f57d26b1004007b3
active boot switches: -d:release -d:danger
```

### LINKED ISSUE #19150: `result.add x` is not void when result is a NimNode, returns itself
getting the type of a templated block inside a macro is complicated by the fact that `typeof(result.add x)` is `NimNode` and not `void`

### Example
```nim
import macros
macro foo():untyped =
  result = nnkStmtList.newNimNode
  var x = nnkDiscardStmt.newTree(newEmptyNode())
  let str = result.add x # compiles ???
  doAssert str == result # ???
  doAssert typeof(result.add x) is NimNode #<= how i found out and what i really care about
foo()
```

### Current Output
```
asserts all succeed
```

### Expected Output
```
shouldn't compile; both assertions should fail
```

### PR DESCRIPTION
**Pull request by ringabout**
fixes #14665
fixes #19150

### CODE REVIEW

**Comment by ringabout** [comment]
Probably we should add a new switch `nimPreviewV2` to hide this feature. Or we can turn `nimPreviewSlimSystem` into `nimPreviewV2`.

**Comment by metagn** [comment]
This doesn't fix the root issue of #14665. It just works around it for NimNode.

```nim
proc add2(a: var seq[int], b: int): int =
  a.add(b)
  b

proc fn(): seq[int] =
  for i in 0..2:
    if false:
      add2(result, i)
    else:
      discard
      break
```

This gives the same wrong error.

**Comment by nc-x** [comment]
Somewhat related issues:
- https://github.com/nim-lang/Nim/issues/19672
- https://github.com/nim-lang/Nim/issues/13871

I had attempted a fix some time back but it didn't go anywhere - https://github.com/nim-lang/Nim/pull/19733

**Comment by ringabout** [comment]
not worth, breaks too many packages.

**Comment by Araq** [comment]
Bummer, but ok.

**Pull request closed without merging**
