### PR TITLE
[FEATURE] Support for indentation in 'of/else/else if' etc.

### PR DESCRIPTION
**Pull request by haxscramper**
Implements https://github.com/nim-lang/RFCs/issues/420

### CODE REVIEW

**Comment by Araq** [comment]
Needs a gramar update too. For this, patch some ``#|`` comment in parser.nim and then run `nim c-r compiler/parser.nim`.

**Comment by Araq** [comment]
There seems to be some nimble important_packages hiccups.

**Comment by haxscramper** [comment]
CI passed earlier with the same implementation, and it is very unlikely that grammar comment modification affected semcheck for a package (code fails with type mismatch error).

Does this mean I need to figure out what is wrong, or PR will still be accepted?

**Comment by Araq** [comment]
It means we'll close and reopen the PR this weekend until it's green.

**Comment by ringabout** [comment]
> CI passed earlier with the same implementation

CI is broken which doesn't run at all but is green until this PR: https://github.com/nim-lang/Nim/pull/18811 (make sure you already fetch the latest commit)

**Comment by ringabout** [comment]
I don't think closing and reopening this PR helps. As I said before, the PR may break some packages (CI may be green wrongly before). So make sure the PR already bases on the latest commit. If it were, maybe you need to figure out why the `cligen` library is broken.

**Comment by haxscramper** [comment]
Separately executing testament for package batch 1_3, running `inim` tests (cligen is shown in CI, but `inim` test fails) with new compiler showed no issues.

**Comment by ringabout** [comment]
> it is very unlikely that grammar comment modification affected semcheck for a package 

IMO your PR can affect code like this

```nim
readStmt = if typeMapping.hasKey(node.protoType): quote do: `stream`.`protoRead`()
  else: quote do: `stream`.`protoRead`(`stream`.protoReadInt64()) #TODO: This is not implemented on the writer level
```

see protobuf failure
```
home/runner/work/Nim/Nim/pkgstemp/protobuf/src/protobuf.nim(786, 79) Error: attempting to call routine: 'protoRead'
    found 'protoRead' [let declared in /home/runner/work/Nim/Nim/pkgstemp/protobuf/src/protobuf.nim(785, 11)]
```

**Comment by haxscramper** [comment]
Closing because it seems like it is impossible to implement cleanly, considering all of these ridiculous edge cases that I didn't even know were valid. Basically allowing *any* kind of flexibility with block arguments would create 'danging else' kind of situation, turning implementation in a completely broken piece of garbage, and it is not worth it.

```nim
  readStmt = if 1: quote do: 3 # ok now
    else: quote do: 2

  readStmt = if 1: quote: 3 # ok now
    else: quote: 2

  match: # Supported now
    myOf: 12
  of:
    discard

  match 1: # supported now, would be ambigous to implement
    match 2:
    of 1: discard # For inner one, indented against 'match 2'
    of 1: discard # Meant to be added to outer, or inner?
  of 1: discard # Added to outer one
```

The same goes for `match arg\nof` - very ambiguous, current grammar is overly flexible, someone probably already depends on all edge cases that exist, and breaking their code for minor consistency improvements does not make any sense.

**Comment by haxscramper** [comment]
And this is off-topic, but what is the point of having CI that randomly allows passing invalid code in the first run? If I initially updated grammar, it could potentially be merged, because the implementation looks so "harmless" and "simple" and no sane person could make up code like this for unit tests.

**Comment by ringabout** [comment]
It was a mistake in testament logics and has been fixed.

see https://github.com/nim-lang/Nim/issues/18805

Because it didn't raise when a package name was wrong. The error was swallowed silently.

https://github.com/nim-lang/Nim/pull/18806/files

image

**Pull request closed without merging**
