### PR TITLE
Add envvars.getEnv

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Added `envvars.getEnv` overload that stores the value in argument.

### CODE REVIEW

**Comment by konsumlamm** [comment]
What exactly is the point of this? What's wrong with `value = getEnv(...)`?

**Comment by juancarlospaco** [comment]
Stores the value in argument, not creating a new string,
code is tiny, I do not know how to make the explanation more explicit.

**Comment by Varriount** [comment]
Hm, I'm not sure about this. Isn't the compiler supposed to optimize this (through use of move analysis, etc.)?

**Comment by juancarlospaco** [comment]
> the compiler supposed to optimize this

Prove me wrong plz, but it looks like a new string is created on my machine, AFAIK.

**Comment by dom96** [comment]
Do you actually have a program which calls `getenv` in a hot code path and so sees significant improvements in performance thanks to this new proc? If so, what are the improvements?

**Pull request closed without merging**
