### PR TITLE
Fix #9405 - cfg and nims run in sync

### LINKED ISSUE #9405: global user config can override project specific config
currently, config files are processed in that order:
all nim.cfg files first
then all config.nims files

eg:
```
Hint: used config file '/Users/timothee/git_clone/nim/Nim/config/nim.cfg' [Conf]
Hint: used config file '/Users/timothee/.config/nim/nim.cfg' [Conf]
Hint: used config file '/Users/timothee/git_clone/nim/proj/nim.cfg' [Conf]
and THEN:
Hint: used config file '/Users/timothee/.config/nim/config.nims' [Conf]
/Users/timothee/git_clone/nim/proj/config.nims
```

this is odd, as it makes global/user configs (/Users/timothee/.config/nim/config.nims) override project-specific ones (eg /Users/timothee/git_clone/nim/proj/nim.cfg) (given that flags / options can be set in both)

## proposal
process in lockstep instead, example:

global nim.cfg
global config.nims
user nim.cfg
user config.nims
proj nim.cfg
proj config.nims

etc

## alternative: depreacte nim.cfg
we could think about whether we plan on deprecating nim.cfg, now that config.nims covers all use cases of nim.cfg (but with more features)

### PR DESCRIPTION
**Pull request by genotrance**

### CODE REVIEW

**Comment by genotrance** [comment]
Test is failing in devel itself.

> testament run tests/osproc/texitcode.nim

**Comment by genotrance** [comment]
https://github.com/nim-lang/Nim/issues/13449

**Comment by Araq** [comment]
I fixed it too here, https://github.com/nim-lang/Nim/pull/13461

Not sure which version I like better though. Yours seem to avoid some code duplication.

**Comment by genotrance** [comment]
I just moved most of the code into `loadConfigs()` since I felt it gets used in many more places and simplified `loadConfigsAndRunMainCommand()`. But until CI passes, I have no idea if I did this right.

**Comment by timotheecour** [comment]
>  But until CI passes, I have no idea if I did this right.

for now just close/reopen (https://github.com/nim-lang/Nim/issues/13449 is flaky, not failing always) EDIT: I've sent a PR to fix it https://github.com/nim-lang/Nim/pull/13487

> Not sure which version I like better though. Yours seem to avoid some code duplication.

* indeed; I prefer this version, eg now `optSkipUserConfigFile` appears only once , whereas in https://github.com/nim-lang/Nim/pull/13461 it appears twice (ditto with other such flags)

* however, as explained here #13488 this PR has correctness issues that are addressed in #13488, which builds upon this PR

**Comment by timotheecour** [comment]
> Not sure which version I like better though. Yours seem to avoid some code duplication.

indeed; I prefer this version, eg now `optSkipUserConfigFile` appears only once , whereas in https://github.com/nim-lang/Nim/pull/13461 it appears twice (ditto with other such flags)
however you can borrow/steal the tests from https://github.com/nim-lang/Nim/pull/13461

**Comment by disruptek** [comment]
Is there a way for `nimph` to _not_ run the NimScript while parsing with `loadConfigs`?  This seems like a breaking change for me...

**Comment by timotheecour** [comment]
> Is there a way for nimph to not run the NimScript while parsing with loadConfigs? This seems like a breaking change for me...

nim --fullhelp:
 --skipCfg:on|off          do not read the nim installation's configuration file
  --skipUserCfg:on|off      do not read the user's configuration file
  --skipParentCfg:on|off    do not read the parent dirs' configuration files
  --skipProjCfg:on|off      do not read the project's configuration file

**Comment by disruptek** [comment]
Sure, but `nimph` is running `loadConfigs` directly from the `compiler/`...  After talking to @genotrance it sounds like this is obsolescence by design, so we'll make it work no matter how slow/broken it is.  :+1:

**Comment by genotrance** [comment]
Superseded by #13488

**Pull request closed without merging**
