### PR TITLE
Many fixes for osproc.nim

### PR DESCRIPTION
**Pull request by cheatfate**
- All: Added `exitFlag` to `ProcessObj` which exactly shows if process is still running.
- Posix: Remove `-3` as marker of finished process.
- Windows: Added `fThreadHandle` to Windows `ProcessObj`.
- Windows: Fix for `execProcesses()` on machines with number of cpu cores more than `MAXIMUM_WAIT_OBJECTS`.
- Windows: Fix for `execProcesses()` to avoid unnecessary calls to `WaitForSingleObject`.
- Windows: Cache process exit, to omit unnecessary syscalls.
- Windows: Fix closing main thread of new process during `startProcess()`.
- Windows: Fix for `pause()`/`resume()` to suspend `main thread`, but not `process` handle.
- Windows: Fix process handle leak on `close()`.
- Windows: Change behavior for `waitForExit()` with timeout. Now if process exceeds specified timeout, it will be terminated.
- Windows: Remove timeout `50ms` from all waiting functions.
- Cosmetic: Change of `var status : cint = 1` to `var status: cint = 1`.

### CODE REVIEW

**Comment by dom96** [comment]
> Windows: Change behavior for waitForExit() with timeout. Now if process exceeds specified timeout, it will be terminated.

Does this align with the behaviour on posix?

**Comment by cheatfate** [comment]
@dom96 yes.

**Comment by dom96** [comment]
That should definitely be explained in the docs.

**Comment by cheatfate** [comment]
Of course, but my english is not so good to write documentation properly (and without mistakes).

**Pull request merged**
