### PR TITLE
Don't crash if generic body is tyForward

### LINKED ISSUE #1500: internal error: no generic body
### Example

```nim
type
  TFtpBase*[SockType] = object
    job: TFTPJob[SockType]

  PFtpBase*[SockType] = ref TFtpBase[SockType]
  TFtpClient* = TFtpBase[string]
  TFTPJob[T] = object
```

### Current Output

```
Error: internal error: no generic body
```

### Expected Output

This should compile

### Workaround

change the order of declarations

```nim
type
  TFTPJob[T] = object
  TFtpBase*[SockType] = object
    job: TFTPJob[SockType]

  PFtpBase*[SockType] = ref TFtpBase[SockType]
  TFtpClient = TFtpBase[string]
```

### Additional Information

```
$ nim -v
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-04-26
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: e48f420ab0161d6fc46c72a5a4f0142e77ed9796
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by LemonBoy**
Fixes #1500

### CODE REVIEW

**Comment by Araq** [comment]
Insufficient test. You also need to test some procs using these types can be compiled to correct C code.

**Comment by Araq** [comment]
Er ... why did you close it?

**Comment by LemonBoy** [comment]
Needs more thought/effort, gotta reopen it if I come up with a proper fix.

**Comment by LemonBoy** [comment]
The problem is the `TFtpClient* = TFtpBase[string]` instantiation of `TFtpBase` occurs before `TFtpJob` is resolved, the only two solutions I see are either throwing a more informative error or performing a topological sort of the types based on their inter-dependencies and process the RHS of the typesection in that order.

**Pull request closed without merging**
