### PR TITLE
Fix fixAbstractType for user defined typeclasses

### LINKED ISSUE #18409: Possibly spurious `no tuple type for constructor` error
The following code snippet gives a `no tuple type for constructor` error for the last `assert` statement (with a tuple instance parameter). I'm not sure yet whether this is a spurious error or a misunderstanding of the language, but Araq has suggested an issue to record it.

```nim
# A vector space over a field F concept.
type VectorSpace*[F] = concept x, y, type V
  vector_add(x, y) is V
  scalar_mul(x, F) is V
  dimension(V) is Natural

# Real numbers (here floats) form a vector space.
func vector_add*(v: float, w: float): float =  v + w
func scalar_mul*(v: float, s: float): float =   v * s
func dimension*(x: typedesc[float]): Natural = 1

# 2-tuples of real numbers form a vector space.
func vector_add*(v, w: (float, float)): (float, float) =
  (vector_add(v[0], w[0]), vector_add(v[1], w[1]))

func scalar_mul*(v: (float, float), s: float): (float, float) =
  (scalar_mul(v[0], s), scalar_mul(v[1], s))

func dimension*(x: typedesc[(float, float)]): Natural = 2

# Check concept requirements.
assert float is VectorSpace
assert (float, float) is VectorSpace

# Commutivity axiom for vector spaces over the same field.
func axiom_commutivity*[F](u, v: VectorSpace[F]): bool =
  vector_add(u, v) == vector_add(v, u)

# This is okay.
assert axiom_commutivity(2.2, 3.3)

# This is not.
assert axiom_commutivity((2.2, 3.3), (4.4, 5.5))
```

@sixte on the Nim Forum has kindly distilled the issue down to this code:

```nim
type XConcept* = concept x
  check(x) is int

proc check[T](x : T) : int = 1

proc reif*(u : XConcept): bool =
  true

# This is okay.
assert reif(2.2)

# This is not.
assert reif((2.2, 3.3))
```

```
$ nim -v
Nim Compiler Version 1.5.1 [MacOSX: arm64]
Compiled at 2021-06-27
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 908b2cc2e44bededdcb943778f44b908a4f3c1df
active boot switches: -d:release -d:nimUseLinenoise
```

### LINKED ISSUE #19730: Error with anonymous tuples passed to concept function arguments.
Anonymous tuples passed to function arguments expecting concepts give the error: `Error: no tuple type for constructor`

```nim
type
  Color = concept c
    c.r is SomeFloat
    c.g is SomeFloat
    c.b is SomeFloat
    c.a is SomeFloat

proc useColor(color: Color) =
  discard

useColor((r: 1.0, g: 1.0, b: 1.0, a: 1.0))
```

### Current Output
```
Error: no tuple type for constructor
```

### Expected Output
No compilation error.

### Additional Information
If you set the tuple to a variable first it works fine.
```nim
type
  Color = concept c
    c.r is SomeFloat
    c.g is SomeFloat
    c.b is SomeFloat
    c.a is SomeFloat

proc useColor(color: Color) =
  discard

let color = (r: 1.0, g: 1.0, b: 1.0, a: 1.0)
useColor(color)
```

`Nim Compiler Version 1.6.4 [Windows: amd64]`

### PR DESCRIPTION
**Pull request by nc-x**
Fixes #19730
Fixes #18409

tyUserTypeClass is needed for 19730
tyUserTypeClassInst is needed for 18409

Relevant code -
https://github.com/nim-lang/Nim/blob/dc4cc2dca53e3772efb3654a4ddbbe8350d1db43/compiler/semexprs.nim#L640-L651

### CODE REVIEW

**Comment by Araq** [comment]
Nice patch but maybe it's better to fix `fixAbstractType` via `abstractVar + {tyUserTypeClass}`

**Comment by nc-x** [comment]
Yes, that is also a possibility, although i did it the current way thinking that similar kinds of issues could be present elsewhere (although i don't know where all that could be the case :) )

Just give me a confirmation as to how you would like this to be solved and I will update the PR accordingly.

**Comment by Araq** [comment]
(nim)grep for `abstractVar` and use your best judgement please, it's how I would do it. (I'm not saying this because I'm lazy, I'm trying to teach.)

**Comment by nc-x** [comment]
I have updated the CR to also include `tyUserTypeClassInst` as that is also needed for resolving the other test case that i have added.

While i manually check the code and try to figure out if this would be the correct approach or not, I have commited the alternative version as well, so that we can check the CIs atleast - https://github.com/nc-x/nim/commit/0ec26f0cc03627d6654c98c12d20285f3ae68db8

**Comment by nc-x** [comment]
I looked at the all the code that uses abstractVar and nothing jumps out where it could cause any issues (or it could help either).
But there is lots of such code, so the chances of causing issues if higher than solving anything, so i have updated the PR to localize the changes in `fixAbstractType` itself.

**Comment by Araq** [comment]
@narimiran please backport.

**Pull request merged**
