### PR TITLE
exportc now mangles same as importc, fixes #10578

### LINKED ISSUE #10578: `exportc` mangles as C++ and doesn't work with `importc`(C) with `nim cpp`
Nim should allow controlling symbol mangling; it currently seems impossible with `nim cpp`.

Using test example below:
```
# this works
nim c -r main.nim

# this errors: Undefined symbols for architecture x86_64: _my_foobar1
nim cpp -r main.nim
```

## test example
main.nim:
```nim
proc foobar1(a: int) {.importc: "my_foobar1".}
proc main() = foobar1(10)
main()

# intentially putting this at the end;
# other use cases: this could be linked from a shared library (nim plugin)
# other use cases: forward declaration to avoid module import cycles
import ./t0202b
```
t0202b.nim:
```
proc foobar1(a: int) {.exportc: "my_foobar1".} = echo (a:a)
```

## very partial workaround
Here's my current workaround that works with `nim c` and `nim cpp`
It still doesn't let me mangle a c++ symbol the way I want, so it doesn't help if I need to export a symbol for a non-nim program that expects a given mangling over which I have no control. 
```
# main.nim:
proc getMangle(cName, cppName: string): string =
  when defined(cpp): cppName else: cName

proc foobar1(a: int) {.importc: getMangle("my_foobar1", "_Z10my_foobar1x").}
...

# t0202b.nim:
proc foobar1(a: int) {.exportc: "my_foobar1".} = echo (a:a)
```

no success, please explain

* I tried:
```
var foobar2 = proc(a: int) {.codegenDecl: "$1 foobar2_b $3".} = discard

# gives compilation error for t0202b.cpp:
error: use of undeclared identifier 'colonanonymous__t4FhpLqaEhvD69cnCq6B8Sg'
        foobar2_tPSgPPlTA53EAR1UTPkutw = colonanonymous__t4FhpLqaEhvD69cnCq6B8Sg;
```

* I also tried:
```
proc foobar2(a: int) {.codegenDecl: "$1 my_foobar1 $3".} = echo (a:a)
# this elides `foobar2` from `t0202b.cpp` as the symbol is unused, so gives a link error for main

# but if i add this to avoid eliding the symbol:
if false: foobar2(0)
# then I get:
error: use of undeclared identifier 'foobar2_t4FhpLqaEhvD69cnCq6B8Sg'
```

## workaround via emit: couldn't make it work
```nim
{.emit:"""extern "C"""".}
proc foobar2(a: int) {.exportc: "nim_foobar2".} = echo (a:a)
```
when you compile, it seems to work (no error!) but doesn't actually work:
the generated cpp code is:
```
extern "C"
N_NIMCALL(void, nim_foobar2)(NI a);
....

// NOTE: no `extern "C"` here so it doesn't relate to above declaration and won't be visible by outside
N_NIMCALL(void, nim_foobar2)(NI a) {
       ...
	echoBinSafe(T1_, 1);
	popFrame();
}
```

## [EDIT] (credits: @araq)
this seems to work:
```
proc foobar1(a: int) {.exportc: "my_foobar1", codegenDecl: """extern "C" $1 $2 $3""".} = echo "ok1"
```
however, it breaks `nim c` compatibity; so, see proposal below.

### rule 1
when `exportc` is specified, it should imply `extern "C"` so that it works seamlessly in tandem with `importc` ; that's the most common use case and the one that'll lead to least bugs when we need to support both  `nim c` and `nim cpp`  (either in isolation, or even when a `nim c` main links against a `nim cpp` shared library)
Eg:
```nim
# this should mangle to same symbol `my_foobar1` regardless we use `nim c`  or `nim cpp`
proc foobar1(a: int) {.exportc: "my_foobar1".} = echo (a:a)
# ditto, mangles to "foobar1"
proc foobar1(a: int) {.exportc.} = echo (a:a)
# ditto, mangles to "foofoobar1bar"
proc foobar1(a: int) {.exportc: "foo$1bar".} = echo (a:a)
```

### rule 2
We also allow (but as an opt-in option) for `exportc` to mangle as c++ as follows:
```nim
# this should mangle to same symbol `__Z10my_foobar1x` (`c++filt __Z10my_foobar1x  = my_foobar1(long long)`)
proc foobar1(a: int) {.exportc: "my_foobar1", mangling: cpp.} = echo (a:a)

# ditto with "$1" which only affects the function name before mangling via function arguments
```

## note:

* `{.push: mangling: cpp.}` can be used for convenience to wrap lots of procs at once
* in D, there is `pragma(mangle)` for this purpose;
it allows flexibilty, for example by conrolling how a particular type `Foo` gets mangled (say, to `FooAlias`), so that when a type `Bar` that depends on it (eg `std::vector<Foo>`) gets mangled (using c++ mangling rules), it'll use the name `FooAlias` inside the mangling of `Bar` , as if `Foo` was named `FooAlias` in the 1st place.
* [EDIT] `mangling` can support different options, eg:
  * `mangling:native` : use C or C++ mangling depending on whether `nim c` or `nim cpp` is used
  * `mangling: cpp`: use C++ mangling with `nim cpp`, and currently errors `with `nim c` but could add support in future (eg [link](https://stackoverflow.com/questions/40740604/how-do-i-get-the-mangled-name-of-a-nameddecl-in-clang) or by calling c++ codegen for the declaration along with its minimal needed dependencies )
  * `mangling: objc`, `mangling: d` (reserved for future use)

### PR DESCRIPTION
**Pull request by timotheecour**
* fix https://github.com/nim-lang/Nim/issues/10578
* see added tests

### CODE REVIEW

**Comment by Araq** [comment]
This is a breaking change.

**Comment by timotheecour** [comment]
> This is a breaking change. It needs a changelog entry and it requires us to introduce externCpp to compensate for the loss of functionality.

done.
* I'm assuming you meant `exportcpp`, not `externCpp` (since we have `wExportNims`, `wExportc` already)
* exportcpp produces an error with `nim c`
* I refactored a bit the pragma sets in pragmas.nim to reuse a common `declPragmas` which makes it easier to spot the common part vs different parts; To avoid changing semantics (except for the added `wExportcpp`), I had to exclude some elements from `lambdaPragmas` and `fieldPragmas`, not clear to me whether these missing pragmas were omissions or intended, please double check

* Instead of adding `sfExportCpp` and patching in many places, it was much simpler to add a  `sfMangleCpp` that can combine with `sfExportC`; `sfMangleCpp` is then used in a single place

* `importcpp` never worked for `nim cpp` (at least for free functions) and this PR doesn't try to fix it; making it work is left for future PR's; so I used instead this in the test:
`proc funx1() {.importc: "_Z5funx1v".}`

**Comment by Araq** [comment]
Thank you!

**Comment by kaushalmodi** [comment]
This is awesome! Does it mean that I do not need to scatter my Nim wrappers with this?

```nim
const
  externCDecl* = when defined(cpp):
                   """extern "C" $1 $2 $3"""
                 else:
                   """$1 $2 $3"""

# ..

proc foo() {.exportc, codegenDecl: externCDecl.} =
  # ..
```

**Comment by timotheecour** [comment]
indeed (let me know if that's not the case somehow), except if you need to support nim versions prior to this PR

**Pull request merged**
