### PR TITLE
make nim_temp compile with --gc:arc --sinkInference:off

### PR DESCRIPTION
**Pull request by cooldome**
This is the changes I had to make to compile nim_temp with `--gc:arc --sinkInference:off`.
Compiled nim_temp doesn't work yet there are runtime issues.

### CODE REVIEW

**Comment by Clyybber** [comment]
Ha, I just recently did the same here (the vm fix only): https://github.com/nim-lang/Nim/pull/13741, I switched it to use `ptr UncheckedArray` as to save one pointer indirection.

**Comment by cooldome** [comment]
@Clyybber , your approach is more efficient so I merged it. This is now a codegen only fix

**Comment by Clyybber** [comment]
Nice, I think @Araq wanted to delay merging my PR until 1.2 is released tho :D

**Comment by narimiran** [comment]
@cooldome no need to restart the build. The fail on `freebsd` is unrelated, and is happening on some other PRs/commits too.

**Pull request merged**
