### PR TITLE
Load Google Fonts last, with update tests

### PR DESCRIPTION
**Pull request by iacore**
A new pull request since https://github.com/nim-lang/Nim/pull/19683 was reverted

### CODE REVIEW

**Comment by xflywind** [comment]
For reviewer: see also https://github.com/nim-lang/Nim/pull/19701

**Review by dom96 — APPROVED** [review]
LGTM but needs rebase

**Comment by ringabout** [comment]
Iirc, plus fixing nimdoc/rst2html/expected/rst_examples.html to make CI green

**Comment by iacore** [comment]
Is there a way to only run tests for doc?

**Comment by dom96** [comment]
It looks like these failures aren't flaky (it seems there are some differences between the generated and expected html files): https://dev.azure.com/nim-lang/Nim/_build/results?buildId=20916&view=logs&j=c6054849-8341-5e23-b888-79fd7ec95d3a&t=8f082e70-3e0a-5206-473a-da5bdc1e1c68&l=278

> Is there a way to only run tests for doc?

Not sure, but you should be able to run what the CI does above locally

**Comment by ringabout** [comment]
Succeeded by https://github.com/nim-lang/Nim/pull/20541

**Pull request closed without merging**
