### PR TITLE
deprecated list comprehension

### PR DESCRIPTION
**Pull request by krux02**

### CODE REVIEW

**Comment by mratsim** [comment]
While the current list comprehensions are quite clunky and probably only used for programming tutorials there should be a replacement.

I don't think for-expressions are ready to take over.

**Comment by alehander42** [comment]
what about https://github.com/alehander42/comprehension (it's WIP: it's based on Araq's idea and there is a PR with probably better implementation idea by [b3liever](/b3liever)  https://github.com/alehander42/comprehension/pull/1

**Comment by krux02** [comment]
The replacement is a for loop and ``add`` on a seq.

**Comment by alehander42** [comment]
IMO functional stuff like <t>It should be the replacement

**Comment by mratsim** [comment]
Mostly 
- https://github.com/nim-lang/Nim/wiki/Nim-for-Python-Programmers#list-comprehensions
- https://scripter.co/notes/nim/#list-comprehension cc @kaushalmodi  

Didn't see in Nim basics (cc @narimiran) nor Nim Days (cc @xmonader)

This came back a couple of time in SO and some blogs:
  - https://freethemalloc.wordpress.com/2016/05/19/understand-list-comprehensions-in-nim/
  - https://stackoverflow.com/questions/54157460/nim-lang-list-comprehension-with-two-variables
  - https://stackoverflow.com/questions/29895918/nim-equivalent-of-pythons-list-comprehension
  - https://qiita.com/6in/items/809f4eb788d00503a825

**Comment by Araq** [comment]
> I don't think for-expressions are ready to take over.

Why not?

**Comment by mratsim** [comment]
> > I don't think for-expressions are ready to take over.
> 
> Why not?

They are not documented: not in the manual and no example equivalent to the one for list comprehensions.

**Comment by Araq** [comment]
We can bless for loop expressions later, but for now I'm accepting this.

**Comment by zqqw** [comment]
"They are not documented: not in the manual and no example equivalent to the one for list comprehensions."
If it helps anyone to note, I found this was equivalent to the examples:
```
import sugar

echo lc[x | (x <- 1..10, x mod 2 == 0), int]
const n = 20
echo lc[(x,y,z) | (x <- 1..n, y <- x..n, z <- y..n, x*x + y*y == z*z),
       tuple[a,b,c: int]]

var
  b = newSeq[int]()
  c = newSeq[tuple[a:int; b:int; c:int;]]()

for val1 in 1..10:
  if val1 mod 2 == 0:
    b.add val1
echo b

for fx in 1..n:
  for fy in fx..n:
    for fz in fy..n:
      if ((fx*fx) + (fy*fy)) == (fz*fz):
        c.add (fx, fy, fz)
echo c
```

**Pull request merged**
