### PR TITLE
tasks that support return values

### PR DESCRIPTION
**Pull request by Araq**

### CODE REVIEW

**Comment by Araq** [comment]
Unrelated CI failure.

**Comment by arnetheduck** [comment]
there is no need for the task object to have an extra pointer to implement return values - ie see https://github.com/status-im/nim-taskpools/blob/stable/taskpools/taskpools.nim#L455

**Comment by Araq** [comment]
Sure but it was easier for me to write it this way.

**Comment by arnetheduck** [comment]
sure, though this has downstream effects on taskpools which was carefully optimised for the 1.6 version and changes like this require re-tuning it - I think the right thing to do here is to simply to deprecate std/tasks since it has a significant tradeoff / design space and its use in experiments like malebolgia prevents it from being a stable base for something like taskpools (ie we'll simply fork it)

**Comment by Araq** [comment]
I'm happy to take patches that remedy the situation. But if your programs use the standard library in a way so that they depend on `sizeof` for objects which never clearly announced their size, that has nothing to do with the quality of the standard library.

**Comment by arnetheduck** [comment]
This is not a quality issue but rather a procedural one: performance is a core feature of nim-taskpools so any changes to it (such as the doubling of the size of the object) require verification that it doesn't cause a regression - this change to std lib was (presumably) done without doing such regression testing, but moreover, the "fix" from taskpools' side is to revert the change (it already pays the "return value price" with a different mechanism than the extra pointer) which presumably will break `malebolgia` which has different tradeoffs (ie convenience for @Araq to experiment).

All in all, it seems to me it's easier for each project to maintain its own task representation tuned to the specific needs of the project rather than having a worst-of-all-worlds component in the std lib.

**Pull request merged**
