### PR TITLE
experiment showing how iterators can (almost) be implemented with a library solution

### PR DESCRIPTION
**Pull request by timotheecour**
support material for https://github.com/nim-lang/RFCs/issues/272

would fix these long standing issues with closure iterators:
* closure iterators can't be used in VM
https://github.com/nim-lang/Nim/pull/15818
* closure iterators can't be used in js
https://github.com/nim-lang/Nim/issues/4695
* closure iterators can't be recursive
https://forum.nim-lang.org/t/7020#44149
* defer/exceptions don't work in closure iterators:
https://github.com/nim-lang/Nim/issues/15501
https://github.com/nim-lang/Nim/issues/11815
* [Closure iterators can leak resources and there is no easy way to prevent it · Issue #13289 · nim-lang/Nim](https://github.com/nim-lang/Nim/issues/13289) https://github.com/nim-lang/Nim/issues/13289

## links
* https://github.com/nim-lang/Nim/issues/15501#issuecomment-730231149
* https://github.com/nim-lang/RFCs/issues/272

### CODE REVIEW

**Comment by Araq** [comment]
Why is this a pull request? This is not a pull request. And the RFC is refers to is not an RFC, it's a question. A valid, interesting question with known answers: Yes it can.

**Comment by Araq** [comment]
Reopening for the sake of it, but it's still not clear to me why:

- This cannot at least start as a fusion module, if it cannot be a Nimble package.
- These ideas cannot ported into the compiler so that closure iterators work better than before.

**Comment by dom96** [comment]
> This cannot at least start as a fusion module, if it cannot be a Nimble package.

This. You're just creating noise by creating this as a PR.

**Comment by ringabout** [comment]
On the other hand javascipt or VM can support closures => https://github.com/nim-lang/Nim/pull/23493

**Pull request closed without merging**
