### PR TITLE
fix #20624 break in closure iterator causes finally to be executed twice

### LINKED ISSUE #20624: break in closure iterator causes `finally` to be executed twice
```nim
import asyncdispatch

proc tryFinally(){.async.} =
  block route:
    try:
      echo "trying"
      raise
    except:
      echo "exception caught"
      break route
    finally:
      echo "finally block"
```

Output:

```
trying
exception caught
finally block
finally block
```

Originally reported in https://github.com/dom96/jester/issues/301. CC @sdmcallister

### PR DESCRIPTION
**Pull request by bung87**
fix #20624

### CODE REVIEW

**Comment by Menduist** [comment]
I already have a fix for this, I'll push it later

**Comment by bung87** [comment]
> I already have a fix for this, I'll push it later

oh , I just have done right now.

**Comment by Menduist** [comment]
Interesting, yours is different to mine: https://github.com/nim-lang/Nim/pull/20630
I think mine makes more sense, but haven't look at yours too deeply

Yours doesn't fix 18824 apparently

**Comment by bung87** [comment]
> Interesting, yours is different to mine: #20630 I think mine makes more sense, but haven't look at yours too deeply
> 
> Yours doesn't fix 18824 apparently

yeah, yours is better, mine is special case handle. didn't know there's `hasYields`,  am new to cgen code.

**Pull request closed without merging**
