### PR TITLE
Make async stacktraces less verbose

### LINKED ISSUE #19931: Async stack traces are very verbose.
Here is an example of one of my async stack traces:

```
C:\p\bencher\src\server.nim(990) server
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(1961) waitFor
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(1653) poll
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(419) runOnce
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(234) processPendingCallbacks
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncmacro.nim(31) processRequestNimAsyncContinue
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asynchttpserver.nim(330) processRequestIter
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncmacro.nim(232) cb
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncmacro.nim(28) cbNimAsyncContinue
C:\p\bencher\src\server.nim(971) cbIter
C:\p\bencher\src\server.nim(496) runs
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\system\fatal.nim(53) sysFatal
[[reraised from:
C:\p\bencher\src\server.nim(990) server
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(1961) waitFor
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(1653) poll
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(419) runOnce
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(234) processPendingCallbacks
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncmacro.nim(31) processRequestNimAsyncContinue
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncmacro.nim(131) processRequestIter
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncfutures.nim(389) read
]]
[[reraised from:
C:\p\bencher\src\server.nim(990) server
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(1961) waitFor
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(1653) poll
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(419) runOnce
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(234) processPendingCallbacks
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncmacro.nim(28) processClientNimAsyncContinue
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncmacro.nim(131) processClientIter
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncfutures.nim(389) read
]]
[[reraised from:
C:\p\bencher\src\server.nim(990) server
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(1961) waitFor
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(1653) poll
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(419) runOnce
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(234) processPendingCallbacks
C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncfutures.nim(437) asyncCheckCallback
]]
Error: unhandled exception: index 1000 not in 0 .. 13
Async traceback:
  C:\p\bencher\src\server.nim(990)                                              server
  C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(1961)  waitFor
  C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(1653)  poll
  C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(419)   runOnce
  C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(234)   processPendingCallbacks
  C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncmacro.nim(31)       processRequestNimAsyncContinue      
  C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asynchttpserver.nim(330) processRequestIter
  C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncmacro.nim(232)      cb
  C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncmacro.nim(28)       cbNimAsyncContinue
  C:\p\bencher\src\server.nim(971)                                              cbIter
  C:\p\bencher\src\server.nim(496)                                              runs
  C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\system\fatal.nim(53)          sysFatal
  #[
    C:\p\bencher\src\server.nim(990)                                              server
    C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(1961)  waitFor
    C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(1653)  poll
    C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(419)   runOnce
    C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(234)   processPendingCallbacks
    C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncmacro.nim(31)       processRequestNimAsyncContinue
    C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncmacro.nim(131)      processRequestIter
    C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncfutures.nim(389)    read
  ]#
  #[
    C:\p\bencher\src\server.nim(990)                                              server
    C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(1961)  waitFor
    C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(1653)  poll
    C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(419)   runOnce
    C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncdispatch.nim(234)   processPendingCallbacks
    C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncmacro.nim(28)       processClientNimAsyncContinue
    C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncmacro.nim(131)      processClientIter
    C:\Users\me\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncfutures.nim(389)    read
  ]#
Exception message: index 1000 not in 0 .. 13
 [IndexDefect]
```

I expect a stack traces that looks some thing like this:

```
C:\p\bencher\src\server.nim(990) server
C:\p\bencher\src\server.nim(971) cbIter
C:\p\bencher\src\server.nim(496) runs
Error: unhandled exception: index 1000 not in 0 .. 13
 [IndexDefect]
```

That's right the function is only 3 async layers deep.

Maybe it would be helpful to mark async functions, so its easier to follow:

```
C:\p\bencher\src\server.nim(990) {.async.} server
C:\p\bencher\src\server.nim(971) {.async.} cbIter
C:\p\bencher\src\server.nim(496) {.async.} runs
Error: unhandled exception: index 1000 not in 0 .. 13
 [IndexDefect]
```

Currently even debugging simple async stack traces is very hard.

### PR DESCRIPTION
**Pull request by ire4ever1190**
Closes #19931

Example program (Change the when statement to compare stack traces)
```nim
when true: # Show async
  import std/asyncdispatch
else: # Show no async
  template async {.pragma.}
  template await(x) = x
  template waitFor(x) = x

proc test() {.async.} =
  raise newException(ValueError, "Async error")
proc a() {.async.} = await test()
proc b() {.async.} = await a()
proc c() {.async.} = 
  await b()

waitFor c()
```

After PR the async stacktrace looks like this
```
/home/jake/Documents/projects/Nim/test.nim(15) test
/home/jake/Documents/projects/Nim/test.nim(13) c (Async)
/home/jake/Documents/projects/Nim/test.nim(11) b (Async)
/home/jake/Documents/projects/Nim/test.nim(10) a (Async)
/home/jake/Documents/projects/Nim/test.nim(9) test (Async)
[[reraised from:
/home/jake/Documents/projects/Nim/test.nim(15) test
/home/jake/Documents/projects/Nim/test.nim(13) c (Async)
/home/jake/Documents/projects/Nim/test.nim(11) b (Async)
/home/jake/Documents/projects/Nim/lib/pure/asyncmacro.nim(135) a (Async)
/home/jake/Documents/projects/Nim/lib/pure/asyncfutures.nim(385) read
]]
[[reraised from:
/home/jake/Documents/projects/Nim/test.nim(15) test
/home/jake/Documents/projects/Nim/test.nim(13) c (Async)
/home/jake/Documents/projects/Nim/lib/pure/asyncmacro.nim(135) b (Async)
/home/jake/Documents/projects/Nim/lib/pure/asyncfutures.nim(385) read
]]
[[reraised from:
/home/jake/Documents/projects/Nim/test.nim(15) test
/home/jake/Documents/projects/Nim/lib/pure/asyncmacro.nim(135) c (Async)
/home/jake/Documents/projects/Nim/lib/pure/asyncfutures.nim(385) read
]]
[[reraised from:
/home/jake/Documents/projects/Nim/test.nim(15) test
/home/jake/Documents/projects/Nim/lib/pure/asyncdispatch.nim(2013) waitFor
/home/jake/Documents/projects/Nim/lib/pure/asyncfutures.nim(385) read
]]
Error: unhandled exception: Async error
Async traceback:
  /home/jake/Documents/projects/Nim/test.nim(15) test
  /home/jake/Documents/projects/Nim/test.nim(13) c (Async)
  /home/jake/Documents/projects/Nim/test.nim(11) b (Async)
  /home/jake/Documents/projects/Nim/test.nim(10) a (Async)
  /home/jake/Documents/projects/Nim/test.nim(9) test (Async)
Exception message: Async error
 [ValueError]
```
Changes made to get here
- The second async traceback now has all the reraises removed
- Internal async procs like `procContinue` are now hidden from the stacktrace
- The async iterator has name changed from `procIter` to `proc (Async)` so its clearly shown whats async and whats not

### CODE REVIEW

**Comment by bung87** [comment]
I remenber https://github.com/nim-lang/Nim/commit/bd12fb3f6439f27274a533e5156a6033c9f69ec0 merged and less verbose than the log you provide (path starts with `lib/pure/async` are omited) , so that one reverted ?

**Comment by ire4ever1190** [comment]
That was in #20116 and it was never merged it seems

**Comment by ire4ever1190** [comment]
Unsure if CI failure is related or not
```
  [Suite] Token Bucket
    [OK] Sync test
    [OK] Async test
    [OK] Over budget async
    [OK] Sync manual replenish
    [OK] Async manual replenish
    [OK] Async cancellation
      /Users/runner/work/Nim/Nim/pkgstemp/chronos/tests/testratelimit.nim(110, 31): Check failed: bucket.tryConsume(1) == false
      bucket.tryConsume(1) was true
      false was false
      /Users/runner/work/Nim/Nim/pkgstemp/chronos/tests/testratelimit.nim(112, 31): Check failed: bucket.tryConsume(1) == true
      bucket.tryConsume(1) was false
      true was true
    [FAILED] Very long replenish
    [OK] Short replenish
  ```

Looking at the [test file](https://github.com/status-im/nim-chronos/blob/master/tests/testratelimit.nim) it doesn't seem to depend on asyncdispatch and its passed in windows/linux CI's

**Comment by Araq** [comment]
Let's see if a restart makes a difference.

**Pull request merged**
