### PR TITLE
remove default argument for readLines

### LINKED ISSUE #12788: Default value for `readLines` shouldn't be 1
I was just doing Advent of Code and used `readLines` in a loop, I was confused to see it return a single line... https://nim-lang.org/docs/io.html#readLines%2Cstring

### Example
```nim
for line in readLines("blah.txt"):
  echo line
```

### Current Output
 One line

### Expected Output
All lines

### Possible Solution

* Deprecate this function and introduce one that does not have the `n` as a default argument

### PR DESCRIPTION
**Pull request by cooldome**
fixes #12788

### CODE REVIEW

**Comment by Araq** [comment]
Needs a [backport] tag. But I'm wondering if can rename this to something like ``staticReadLines`` ?

**Comment by cooldome** [comment]
@Araq: np, will rename

**Comment by narimiran** [comment]
> Needs a [backport] tag. 

Wouldn't this break people's code if backported?

**Comment by Araq** [comment]
> Wouldn't this break people's code if backported?

It only made it into version 1.0 because of an oversight by me. It was a bug that this was added with this particular design.

**Comment by cooldome** [comment]
tests are green now, ready for review

**Pull request merged**
