### PR TITLE
Revert "Add OpenSSL 3 support"

### PR DESCRIPTION
**Pull request by Araq**
Reverts nim-lang/Nim#19814

### CODE REVIEW

**Comment by Varriount** [comment]
Can't we fix whatever is causing the CI/CD errors instead?

**Comment by Araq** [comment]
Yes, I'm investigating.

**Comment by arnetheduck** [comment]
It's not terrible to have to fix CI for this - the problem is rather that users will face the same issue, so openssl will have to be installed alongside Nim for those users: this needs communication or a solution (for example having the brew package depending on the right ssl version to automate the process)

**Comment by Araq** [comment]
OSX uses libreSSL afaict so removing the support for libre is just nuts.

**Comment by metagn** [comment]
The original patch seems tiny enough to use a define for openssl 3 despite the comment saying it would be a combinatorial explosion. From what I can tell it's just the init procs, the TLS_method call for the protocol, and the changes to the test. The rest of the PR seem to be independent refactors (the test might be just a refactor too).

**Comment by Araq** [comment]
Alternative: https://github.com/nim-lang/Nim/pull/20324 which seems to work for my OSX.

**Pull request closed without merging**
