### PR TITLE
Atlas: virtual environments

### PR DESCRIPTION
**Pull request by Araq**

### CODE REVIEW

**Comment by arnetheduck** [comment]
Instead of specifying a "virtual env", just install `nim` in `_deps` and use it - this removes a step from the process of getting the right nim version and does the "right thing" for most users (which is to use a nim that the package claims to support according to minimal version) - newer versions can then be used by turning nim into a package which is supposed to have preference)

**Comment by Araq** [comment]
Why should my dependencies dictate the Nim compiler that I want to use? Certainly not for `atlas use`, maybe for `atlas clone`, I don't know.

**Comment by Araq** [comment]
Keep in mind that every nimble package specifies something like `requires "nim >= 1.2"` without ever checking whether that actually works.

**Comment by arnetheduck** [comment]
because nim and above all, its std lib, is just a dependency: if I want my program to work, nim as to play ball. It's a library that I need to build my program - there's nothing special about it _really_ except its place at the bottom of the dependency tree. if I clone a project, I don't much care which nim version is used to compile it as long as it does its job, just like I don't care about any other dependency.

Imagine you have no nim at all installed (the state of most computers out there). You download `atlas` and nothing else, then clone a project and "it just works" out of the box with no further guesswork: it picks the right dependencies _and_ it picks the right nim (which is just one more dependency to get it to work).

> Keep in mind that every nimble package

As soon as atlas starts doing the above (ie applying the same strategy to nim as it does to any other dependency), people will have to fix their nimble files to be correct and useful, if they want their packages to work.

Think about the CI story (which is now exactly the same as a developer cloning your package): you download `atlas`, clone your package and run `atlas` to set up dependencies: nim gets installed like any other dependency and your CI is _exactly_ in the state you want it for running tests. It has an (insecurely, because versions are names and can change) reproducible state that matches the one used for developing the package without further intervention.

**Comment by arnetheduck** [comment]
Another way to put this: if atlas is _not_ using the information in the nimble file to reason about the version of nim (a dependency) needed to use the package, it offers no advantage over choosenim - only by using the information in the nimble file does it provide a useful benefit ("help me download the dependencies of the project in reasonable versions")

**Comment by Araq** [comment]
You will get this feature via `--autoenv` (can also be put into the config) but I don't want it as a default. Maybe later.

> it offers no advantage over choosenim

Ha, good one. ;-)

**Pull request merged**
