### PR TITLE
fixes #9970, #10990, #10962

### LINKED ISSUE #9970: Echoing Compile Time Var Causes 'gcc' error.
Echoing compile time `var`'s results in a `gcc` error, same thing happens if you use `let`. I'm not even sure you should be able to do this but if not an error from `nim` would be better.

I have not tested the JS backend. 

### Example
```nim
var i {.compileTime.} : int = 0
echo i
```

### Current Output
```
Hint: compiletimevar [Processing]
CC: compiletimevar
CC: stdlib_system
CC: stdlib_helpers2
Error: execution of an external compiler program 'gcc -c -w  -I/home/deech/Nim/Nim/lib -o /home/deech/.cache/nim/compiletimevar_d/compiletimevar.c.o /home/deech/.cache/nim/compiletimevar_d/compiletimevar.c' failed with exit code: 1

/home/deech/.cache/nim/compiletimevar_d/compiletimevar.c: In function ‘NimMainModule’:
/home/deech/.cache/nim/compiletimevar_d/compiletimevar.c:144:23: error: ‘i_y9cnQC7lDNumSxFlzcVlOhQ’ undeclared (first use in this function)
  T1_[0] = nimIntToStr(i_y9cnQC7lDNumSxFlzcVlOhQ);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/deech/.cache/nim/compiletimevar_d/compiletimevar.c:144:23: note: each undeclared identifier is reported only once for each function it appears in
Traceback (most recent call last)
nim.nim(109)             nim
nim.nim(73)              handleCmdLine
cmdlinehelper.nim(103)   loadConfigsAndRunMainCommand
main.nim(168)            mainCommand
main.nim(82)             commandCompileToC
extccomp.nim(808)        callCCompiler
extccomp.nim(756)        execCmdsInParallel
osproc.nim(309)          execProcesses
extccomp.nim(740)        :anonymous
msgs.nim(414)            rawMessage
msgs.nim(411)            rawMessage
msgs.nim(332)            handleError
msgs.nim(317)            quit
FAILURE
```

### Expected Output
Compile time output should include `0`.

### PR DESCRIPTION
**Pull request by deech**

### CODE REVIEW

**Comment by narimiran** [comment]
@deech I've solved merged conflicts and now, from what I can tell, the test you've written (`tcompiletimeletvar.nim`) is failing. Can you double-check?

**Comment by deech** [comment]
@narimiran Fixed.

**Comment by deech** [comment]
bump

**Comment by Araq** [comment]
As I said, I don't like this change. In ``sigmatch.nim`` you effectively change how overloading resolution is performed and in the spec no such special cases are mentioned. I think we would disagree on the spec if it were more fleshed out so I ask you to tell me what the spec should say. :-)

**Comment by deech** [comment]
@Araq That's fair. If I update the manual would it help convince you?

**Comment by Araq** [comment]
Yes, can be done in this very pull request or maybe as an RFC, depending on your taste and the perceived complexity on this issue.

**Comment by ringabout** [comment]
Issues mentioned are already fixed.

**Pull request closed without merging**
