### PR TITLE
Add a note to windows users to avoid blanks

### PR DESCRIPTION
**Pull request by m33m33**
Blank in path to mingw/nim sources will break compilation with build_all.bat

### CODE REVIEW

**Comment by m33m33** [comment]
Capture d’écran 2021-04-26 à 19 25 25

**Comment by timotheecour** [comment]
can you fix the problem instead?
not that i support spaces in filenames but at least these could be supported on a best effort basis

**Comment by m33m33** [comment]
> can you fix the problem instead?

I will give it a try, no guarantee I have to use windows to build binaries for coworkers, I don't like it that much anyway

It seems that the issue is not in the bat scripts, but rather when nim.exe calls gcc.exe to build other ressources. On that I can't help :(

**Comment by Araq** [comment]
> It seems that the issue is not in the bat scripts, but rather when nim.exe calls gcc.exe to build other ressources. On that I can't help :(

How to reproduce the problem? We support spaces and "Program Files" for a decade now...

**Comment by m33m33** [comment]
> > It seems that the issue is not in the bat scripts, but rather when nim.exe calls gcc.exe to build other ressources. On that I can't help :(
> 
> How to reproduce the problem? We support spaces and "Program Files" for a decade now...

Honestly I was about to close this PR and blame my W10 PC. But I just reproduced it on another W10 laptop.

Steps to reproduce:
1. Open a cmd.exe shell
2. Create "C:\Nim Lang"
3. Unzip https://nim-lang.org/download/mingw64.7z in "C:\Nim Lang\mingw64"
4. Ensure you don't have previous or conflicting gcc.exe compiler lurking around (like cygwin) : gcc -v should gives you file not found
5. Source mingw env: go in "C:\Nim Lang\mingw64" and run mingwvars.bat
6. gcc -v now should give you the mingw version
7. In "C:\Nim Lang" : git clone https://github.com/nim-lang/Nim.git  so you have the source tree in "C:\Nim Lang\nim"
8. Go in  "C:\Nim Lang\nim" and run build_all.bat

The result it this log on screen: https://pastebin.com/cnGfPz1X

Repeat this with a base directory without spaces like "C:\NimLang" and everything works well.

**Comment by timotheecour** [comment]
see https://github.com/nim-lang/Nim/pull/17875 instead

**Pull request closed without merging**
