### PR TITLE
8684 add shortcut sort procs

### PR DESCRIPTION
**Pull request by moigagoo**
Add versions of `sort`, `sorted`, and `isSorted` procs that use `system.cmp[T]` as cmp function (https://github.com/nim-lang/Nim/issues/8684).

### CODE REVIEW

**Comment by moigagoo** [comment]
I'd be happy to, but I couldn't find the right existing test. Like, there's no talgorithm.nim. I did spot a tsortcall.nim, which is quite rudimentary. Could you please help me find the right test file to merge my new tests into?

**Comment by dom96** [comment]
indeed, it looks like tsortcall would be best.

**Comment by moigagoo** [comment]
Done!

**Comment by tim-st** [comment]
There is also [this PR](https://github.com/nim-lang/Nim/pull/8778), which is finished afaict

**Comment by moigagoo** [comment]
> There is also this PR, which is finished afaict

Oh, should I close this one?

**Comment by moigagoo** [comment]
> Ugh, I just realized I like your PR moreso. Can you please rebase?

First, thanks a lot, I feel humbled, a lot.

Second, I did try rebasing, although I'm not sure I've done the right thing. Got no conflicts, but I've added a whole bunch of commits from devel to this PR. Is that OK?

**Pull request merged**
