### PR TITLE
Replace factorial function with a compile time one

### PR DESCRIPTION
**Pull request by notTito**

### CODE REVIEW

**Comment by Yardanico** [comment]
I think it may be better to generate this table directly in "fac" proc, so if user doesn't use "fac" compiler doesn't create these?

**Comment by konqoro** [comment]
@Yardanico Nice suggestion. So the alternative might be:
```
# Factorials

proc createFactTable[n: static[int]]: array[0 .. n, int] =
   result[0] = 1
   for i in 1 .. n:
      result[i] = result[i - 1] * i

proc fact*(n: int): int =
   when sizeof(int) == 4:
      var factTable {.global.} = createFactTable[12]()
   else:
      var factTable {.global.} = createFactTable[20]()
   assert(n > 0, $n & " must not be negative.")
   assert(n < factTable.len, $n & " is too large to look up in the table")
   factTable[n]

echo fact(2)
```
Which for some reason can't be const. Let's wait for the maintainer comment.

**Comment by konqoro** [comment]
Or just:
```
# Factorials

proc createFactTable[n: static[int]]: array[0 .. n, int] =
   result[0] = 1
   for i in 1 .. n:
      result[i] = result[i - 1] * i

when sizeof(int) == 4:
   const factTable = createFactTable[12]()
else:
   const factTable = createFactTable[20]()

proc fact*(n: range[0 .. high(factTable)]): int =
   factTable[n]

var t = 20
echo fact(t)

```

**Comment by notTito** [comment]
@Araq, @dom96, someone, please review.

**Comment by survivorm** [comment]
Looks like a sound idea, no improvements coming into mind

**Comment by dom96** [comment]
This depends on a couple of factors:

* Does this affect compile-time when I am importing ``math`` but not using ``fac``?

* When ``fac`` is used how much slower is the compilation?

* How much does this affect the binary size?

**Comment by notTito** [comment]
@dom96 1) I think not but I don't know if this or my previous commit is the right way.
2) none at all. It only creates a table of 21 integers. 3) +168 bytes I guess?

**Comment by Yardanico** [comment]
@notTito sorry, I didn't notice it earlier - why did you remove ability to call fac with 0?

**Comment by notTito** [comment]
@Yardanico can someone with access fix it, sry I dont have time.

**Pull request merged**
