### PR TITLE
Added countup/countdown iterators for floats.

### PR DESCRIPTION
**Pull request by dom96**

### CODE REVIEW

**Comment by Yardanico** [comment]
What's the status of this? Seems to be useful in some cases

**Comment by dom96** [comment]
Good question. Let's see if rebasing fixes test failures.

**Comment by Yardanico** [comment]
It seems that Travis failure is unrelated, isn't it?

**Comment by dom96** [comment]
It is related. That code uses ``countdown``.

**Comment by GULPF** [comment]
Looks dangerous for large values. This will loop forever:
```nim
for x in countup(9007199254740992.0, 9007199254740992.0):
  echo x
```
But this wont:
```nim
for x in countup(9007199254740992, 9007199254740992):
  echo x
```

**Comment by dom96** [comment]
My god, floating point is just a big minefield. Can anyone explain why this is? and why we don't have a runtime check for this?

```nim
let x = 9007199254740992.0

doAssert(x + 1.0 == x)
```

**Comment by Vindaar** [comment]
That is expected, due to the accuracy of a `float64`. 
In a `float64` you have 52 bits for the mantissa:
https://en.wikipedia.org/wiki/Floating-point_arithmetic#Internal_representation), 
which is ~4.5e15. The number you write there has 16 significant digits. If you remove one digit, the assert still fails, but from the 16th digit on adding 1.0 leaves the float unchanged, since the last won't be sensitive to 1.0 anymore (adding 2.0 is enough to still make the assert fail).

**Comment by dom96** [comment]
So from what I can tell there are three things we can do:

* Add a runtime check into ``countup`` for this case.
* Create a dedicated ``countup`` for floats in ``lenientops``
* Both of the above

**Comment by Araq** [comment]
Python's ``range`` doesn't support floating point either and there is not much "counting" involved here when you use floating point. Can't we just close this please?

**Pull request closed without merging**
