### PR TITLE
[obsolete] Revert "fix #13182: `proc fun(a: varargs[Foo, conv])` now can be overloaded (#13345)

### LINKED ISSUE #13182: write requires conversion to string
write requires conversion to string

<FromDiscord> <Clyybber> hmm, I think this is a bug

### Example
```nim
type
  Kind = enum INT, STR, ELT
  Tree = ref object
    case k: Kind
    of INT: i: int
    of STR: s: string
    of ELT:
      e: string
      a: seq[(string, string)]
      b: seq[Tree]

proc tree(x: int): Tree = Tree(k: INT, i: x)
proc tree(x: string): Tree = Tree(k: STR, s: x)

proc write(f: File, x: Tree) =
  case x.k
  of INT: f.write x.i
  of STR: f.write x.s
  of ELT:
    f.write '('
    f.write x.e
    f.write ' '
    for (k, v) in x.a:
      f.write k
      f.write '='
      f.write v
    f.write ' '
    for i in x.b:
      f.write i
    f.write ')'

stdout.write tree 42
```

### Current Output
```
rec.nim(29, 15) Error: type mismatch: got <Tree>
but expected one of:
proc `$`(x: bool): string
proc `$`(x: int64): string
proc `$`(w: WideCString; estimate: int; replacement: int = 0x0000FFFD): string
proc `$`(x: char): string
proc `$`(x: float): string
proc `$`(x: cstring): string
proc `$`[T](x: openArray[T]): string
proc `$`[T, IDX](x: array[IDX, T]): string
proc `$`(s: WideCString): string
proc `$`(x: string): string
proc `$`[T: tuple |
    object](x: T): string
proc `$`[Enum: enum](x: Enum): string
proc `$`(x: uint64): string
proc `$`(t: typedesc): string
proc `$`[T](x: set[T]): string
proc `$`[T](x: seq[T]): string
proc `$`(x: int): string
proc `$`[T, U](x: HSlice[T, U]): string
```

### Expected Output
```
42
```

### Possible Solution

s/write/mywrite fixes the example

but i would expect that my write method would be used

### Additional Information

```
$ nim -v
Nim Compiler Version 0.20.2 [Linux: amd64]
Compiled at 2019-07-17
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches: -d:release -d:nativeStackTrace
```

### LINKED ISSUE #13378: Internal error in getTypeDescAux
This doesn't compile anymore
Removing one seq field from resource fixes it.

### Example
```nim
type
  Resource = ref object of RootObj
    name: string
    readers, writers: seq[RenderTask]

  RenderTask = ref object
    name: string

var res = Resource(name: "Resource 1")

(proc (r: typeof(res)) =
   echo r[])(res)
```

### Current Output
```
Error: internal error: getTypeDescAux(tyGenericParam)
Traceback (most recent call last)
...
```

### Expected Output
```
Compilation successfull :)
```

### Additional Information

* It was working just a few days ago, I'm still figuring out what broke it..
* This issue is blocking my project

```
$ nim -v
Nim Compiler Version #devel
```

### PR DESCRIPTION
**Pull request by timotheecour**
* fix #13378 by reverting #13345
* means we have to reopen https://github.com/nim-lang/Nim/issues/13182

very sad, I know ...

maybe someone has a better idea? /cc @Clyybber

## note (for whoever wants to revisit #13345)
when compiling nim with --stacktrace:on --debugger:native, the crash in #13378 is inside some cgen code; that means the error should've been detected earlier but wasn't; it's possible that some piece of code didn't check for `result == nil` somewhere down the line after `c.semTryExpr`

### CODE REVIEW

**Comment by Clyybber** [comment]
@timotheecour I don't, but didn't your original PR first have a different solution to #13182 ?
Or am I misremembering

**Comment by timotheecour** [comment]
it did, but 1st solution didn't work; and now looks like 2nd solution doesn't work either... somehow `varargs[string,conv]` really is complex to handle properly

**Comment by krux02** [comment]
To my experience ``varargs`` is cursed. See for example #10975. It can't be fixed without breaking it. My personal advice is to not use if you can avoid it. My recommendation is to use ``openArray`` instead which doesn't suffer from any of the problems that ``varargs`` does.

**Comment by Araq** [comment]
Let's not merge this, I have a proper fix.

**Comment by timotheecour** [comment]
can you also see if your proper fix improves https://github.com/nim-lang/Nim/issues/10975 ? this seems at least somewhat related

**Pull request closed without merging**
