### PR TITLE
add sugar.ntimes

### PR DESCRIPTION
**Pull request by timotheecour**
small sugar but often requested

### CODE REVIEW

**Comment by c-blake** [comment]
Not a big deal, but maybe call it `repeat`?  (That's what Zsh does...)

**Comment by timotheecour** [comment]
was what i started with but repeat is ambiguous with sequtils.repeat

**Comment by metagn** [comment]
Clojure calls it `dotimes` which would be weird here, `timesDo` would look bad (especially with `do:`), I think `times` might be the best option despite being a risky name, with the module named times and being a common name. `10.times do: ` could be good. Could be a good stress test for symbol resolution. Maybe even do `body: untyped{nkStmtList}` to enforce `do:`, that would be another good stress test. If these break anything though, any other name is fine.

**Comment by Varriount** [comment]
I don't believe this is needed. It literally saves less than a line of typing. Keep in mind that these things do have cognitive overhead, in that they increase what must be learnt.
Additionally, the implementation is simple enough that users, if they decide it's *really needed*, can implement it themselves.

**Comment by c-blake** [comment]
Unless `sugar` is already imported, it actually costs (or is super close to a net wash)...
```Nim
for _ in 1..():
ntimes():, sugar
```
Even if `sugar` is already imported it doesn't save much...Things do go in `sugar` and then if they never become popular, they get retired.  I feel like this has happened several times already.  So, I'm not against the experiment, but I also tend to agree that there is little value.  (I'm not sure anyone is really claiming "tremendous value", though..Seems a little thing one way or the other.)

**Comment by juancarlospaco** [comment]
```nim
template retry*(tries = 1.Positive, delay = 0.Natural, backoff = 1.Positive, code: untyped) =
```

instead IMHO. Bonus if it can be used as pragma `{.retry.}` or `{.retry: 3.}`.

**Comment by Araq** [comment]
Sorry, but the downsides as @Varriount mentioned are more severe than the advantages.

**Pull request closed without merging**
