### PR TITLE
Update parsecfg.nim

### PR DESCRIPTION
**Pull request by lihf8515**
Added a number of features, including the creation of the configuration file, read, modify, delete operations.

### CODE REVIEW

**Comment by Varriount** [comment]
Hm. What about tests?

**Comment by lihf8515** [comment]
I'm testing the normal. What do you mean?

**Comment by reactormonk** [comment]
@lihf8515 he's referring to automated tests in `tests/`

**Comment by lihf8515** [comment]
Is there a problem with my code?

**Comment by Varriount** [comment]
Three things:
 - Why use a file stream in writeCfg? A regular file will work just as well, and be slightly more efficient.
 - Tests for the new procedures would be nice.
 - Have you given thought to what happens when multiple keys/sections of the same name are present?

**Pull request closed without merging**
