### PR TITLE
capture macro now accepts variables of different types

### PR DESCRIPTION
**Pull request by Clyybber**
cc @foldl

### CODE REVIEW

**Comment by Clyybber** [comment]
I made it backwards compatible with the syntax `capture [...]: ...`, but since for capturing differently typed variables you will need to use `capture ...: ...` maybe I should adapt the examples to use that?

**Comment by Clyybber** [comment]
The new syntax is a bit simpler and required for capturing differently typed vars, so I made the examples use it, so that new users will use that syntax instead.

**Comment by Araq** [comment]
Bah, but I liked the old version better. The ``[a, b]`` notation is cute. I think we should patch the compiler/spec to make ``openArray[typed]`` work as ``varargs[typed]``.

**Comment by Clyybber** [comment]
Wouldn't that require changes to array constructor logic?
I also found it cute, but with varargs it feels more like a builtin keyword.

**Pull request merged**
