### PR TITLE
Allow likely(x) and unlikely(x) in all targets, fix #3882

### LINKED ISSUE #3882: `unlikely`/`likely` should be no-ops for the Javascript backend
Currently, the `system.unlikely` and `system.likely` functions are directly mapped to a C compiler builtin for the C/CPP/etc backends.  However, they aren't defined at all in the Javascript backend.  This makes a certain amount of sense - Javascript has no way of suggesting which branches are most likely to occur, and not much reason for them.

However, this means that libraries that use `unlikely` cannot be used at all for Javascript, even if they are otherwise entirely backend-agnostic.  Given that these functions are just compiler hints, it makes sense for them to be replaced by a no-op inlineable function when building for the Javascript backend.

Alternative solutions:

- change them to be pragmas - most other compiler hints are implemented as pragmas, so that makes sense.  But that would mean fairly major breaking changes, so may not be a great idea.
- change them to be macros/templates - the macro could be converted into a call to a internal_unlikely() function, or just do nothing, depending on the chosen backend.  This would probably be easier to maintain, but there might be a slight breaking change depending on the semantics of function vs macro.

This would hopefully make it a lot easier to maintain libraries that work for both C-like and Javascript targets.

### PR DESCRIPTION
**Pull request by MrJohz**
Provides an alternative (no-op) implementation for `likely` and `unlikely` for targets that don't use compiler hints (i.e. the VM and JS targets).

### CODE REVIEW

**Comment by MrJohz** [comment]
So GH's cross-issue links work, this fixes #3882.

**Comment by Araq** [comment]
Sorry, please rebase.

**Comment by yglukhov** [comment]
@MrJohz, maybe it would be better to not duplicate the test case twice, but instead run the `tests/system/testlikely.nim` test from `categories.nim/js` as it already has some references to other tests which are not in js folder.

Also you don't have a test for vm:
```nim
proc foo(): int =
  if likely true:
    result = 1
  if unlikely false:
    result = 2
const v = foo()
doAssert(v == 1)
```

**Comment by Araq** [comment]
Fixed it differently.

**Pull request closed without merging**
