### PR TITLE
fixes #21989; lift `=dup` from a custom `=copy` for objects to keep backward compatibilities 

### LINKED ISSUE #21989: Lifting the =dup hook broke existing code
### Description

The `=dup`hook is now lifted by #21903, causing the compiler to insert `=dup` in some places where it originally inserted `=copy`. This breaks existing code that implements only the `=copy` hook, such as  [nim-lang/threading/smartptrs.nim](https://github.com/nim-lang/threading/blob/03a5b433313b1db283d4294dc2ee7e15c2899c1b/threading/smartptrs.nim).

Here is an example
```nim
type Rc = object
  counter: ptr int

proc `=destroy`(self: var Rc) =
  if self.counter != nil:
    dec self.counter[]
    if self.counter[] == 0:
      echo "destroy!"
      # deallocShared self.counter

proc `=copy`(dest: var Rc, src: Rc) =
  `=destroy`(dest)
  wasMoved(dest)
  if src.counter != nil:
    echo "copy!"
    inc src.counter[]
    dest.counter = src.counter

proc use(self: sink Rc) =
  discard

proc newRc(): Rc =
  result.counter = createShared(int)
  result.counter[] = 1

proc main =
  var x: Rc
  block:
    var a = newRc()
    use(a)
    x = a
  echo x.counter[]

main()

# --expandArc: main
# var
#   x
#   :tmpD
# try:
#   block :tmp:
#     var
#       a
#       :tmpD_1
#     a = newRc()
#     use:
#       :tmpD_1 = `=dup`(a)
#       :tmpD_1
#     x = a
#   echo [
#     :tmpD = `$`(x.counter[])
#     :tmpD]
# finally:
#   `=destroy`(:tmpD)
#   `=destroy_1`(x)
# -- end of expandArc ------------------------
```

### Nim Version

Nim Compiler Version 1.9.3 [Linux: amd64]
Compiled at 2023-06-03
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 1133f20fe2c834d14454c32d7d9fc2cd1fe8ffa2
active boot switches: -d:release

### Current Output

```text
destroy!
0
```

### Expected Output

```text
copy!
1
destroy!
```

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #21989

### CODE REVIEW

**Comment by ringabout** [comment]
Well, I tried to only generate `=dup` for refs and `=wasMoved; =copy` for non-refs. But it seems to be less neat and efficient than lift `=dup` from an existing custom `=copy`, in which most of types cannot benefit from lifted `=dup` hooks. As to backwards compatibilities, it should suffice since `=wasMoved` is rarely used, which is quite new.

**Comment by Araq** [comment]
> Well, I tried to only generate =dup for refs and =wasMoved; =copy for non-refs. But it seems to be less neat and efficient than lift =dup from an existing custom =copy, in which most of types cannot befefit from lifted =duphooks. As to backwards compatibilities, it should suffice since=wasMoved` is rarely used, which is quite new.

What does that mean?

**Comment by ringabout** [comment]
Succeeded by https://github.com/nim-lang/Nim/pull/22015

**Comment by ringabout** [comment]
Discussed on the Discord

**Comment by Araq** [comment]
So should I review this one then?

**Comment by ringabout** [comment]
Yep

**Pull request merged**
