### PR TITLE
Windows: fix a eraseLine bug

### PR DESCRIPTION
**Pull request by data-man**
```nim
import terminal
echo "123"
echo "456"
cursorUp(2)
eraseLine()
```

### CODE REVIEW

**Comment by Araq** [comment]
Huh, is this perhaps caused by the newer Windows version? Usually code is not written in this way if it wasn't required back then.

**Comment by dom96** [comment]
This was already presumably fixed by https://github.com/nim-lang/Nim/commit/822da4b21352ca733c85b0f0303d0cf8f90e5aa6

The person making the fix surely tested their solution?

This patch makes sense though I guess. But how did this code ever work previously?

**Comment by data-man** [comment]
> The person making the fix surely tested their solution?

Of course.

**Comment by Yardanico** [comment]
@data-man - dom96 asked about previous attempt to fix this issue

**Comment by data-man** [comment]
Oops, sorry. :-)

**Comment by data-man** [comment]
@Araq 
> is this perhaps caused by the newer Windows version?

I do not think so. Apparently this function was never used before. :-)

**Comment by nc-x** [comment]
https://docs.microsoft.com/en-us/windows/console/clearing-the-screen
(Example 2)

On mobile, so didn't check properly, but isn't the code in the link effectively doing `ht*wt` which this PR changes to `wt` only.

**Comment by data-man** [comment]
The proposed fix does not completely solve the problem.
If a string was longer than screen's width, it is wrapped.
Which a line then to erase?
What to do, scan the screen's buffer and search the line break?

**Comment by Araq** [comment]
> What to do, scan the screen's buffer and search the line break?

I think it's fine to assume no line wrapping.

**Comment by dom96** [comment]
It was definitely used by choosenim at least, and it did work (except for in rare circumstances) so I'm a bit worried whether this fixes it or breaks it even more.

**Comment by data-man** [comment]
Then the docs should be corrected.
> Erases the entire current line.

Now the behavior of the function is the same as in *nix.

**Pull request merged**
