### PR TITLE
install older version of nimcuda for arraymancer

### PR DESCRIPTION
**Pull request by metagn**
Attempt to fix CI failure, refs https://github.com/nim-lang/Nim/pull/24495#issuecomment-2511299112, alternative is to use a commit version like https://github.com/SciNim/nimcuda/commit/bc65375ff52980ca2faec058bea40c2306ab6081

### CODE REVIEW

**Comment by Clonkk** [comment]
@Vindaar are you aware of the issue with latest nimcuda ?

**Comment by Vindaar** [comment]
Kind of? Recently I've seen weird installation issues across a few repositories (weave, arraymancer and maybe something else, don't remember). I assumed it was a nimble issue (the error messages were not very helpful in each case). I can investigate, +but here I also don't understand how the fix is a nimcuda issue.+ 

edit: misread the last part of the fix and that 0.2.1 is not the latest anymore, heh. I'll investigate

**Comment by Clonkk** [comment]
Could it be related to how Nimble resolves the commit hash used to compile dependencies?

I have had issue on atlas (if they use the same algo?) when not using MaxVer

**Comment by Vindaar** [comment]
> Could it be related to how Nimble resolves the commit hash used to compile dependencies?
> 
> I have had issue on atlas (if they use the same algo?) when not using MaxVer

Had a short look. The issue here is indeed just an issue with a) how nimcuda now handles the wrapper (need to supply paths to the CUDA installation at CT due to https://github.com/SciNim/nimcuda/issues/27) and b) the fact that arraymancer (still) always builds with CUDA support. The latter was never a problem when `nimcuda` only loaded the cuda libraries at runtime in case they were actually needed.

I'll likely make a `-d:cuda` switch mandatory for arraymancer to build with CUDA support in the future.

**Comment by metagn** [comment]
Merging for now

**Pull request merged**
