### PR TITLE
Error out if vararg match isn't an exact one

### LINKED ISSUE #8172: Varargs with array ignores leading arguments.
```
proc f(v: varargs[string]) =
    echo(v)

f("a", ["b", "c"])
```
Outputs `["b", "c"]`.

### PR DESCRIPTION
**Pull request by LemonBoy**
Fixes #8172 

Let's see if the CI likes it, I don't really like how the error message is worded though.

### CODE REVIEW

**Comment by Quelklef** [comment]
Is it possible this be defined behavior rather than an error? I found the bug trying to use varargs this way and expecting the call to echo `["a", "b", "c"]`. I think that'd be rather useful behavior. If it's disallowed, some calls like `f(val, rest)` where `val` is `T` and `rest` is `array[N, T]` have to become `f(@[val] & @rest)` instead.

**Comment by LemonBoy** [comment]
> Can I suggest this usage of varargs be allowed rather than an error?

Sure, but you have to discuss this with the higher ups as I don't know if such a change needs an RFC/NEP/whatever from the bureaucratic point of view.

From a technical point of view it should be easy to implement since it's just a matter of concatenating the contents of the `nkBracket` that's passed as argument.

**Comment by Araq** [comment]
> Can I suggest this usage of varargs be allowed rather than an error?

Would require an RFC. But you already have my downvote. We don't need more builtin language features to save a couple of keystrokes, we need cleaner rules and less bugs.

**Comment by dom96** [comment]
I'm in agreement with @Araq on this one. We can always get back to this later, for now the uglier code is good enough.

**Comment by Quelklef** [comment]
Sure. A macro can probably do this, anyway.

**Comment by Araq** [comment]
Brilliant.

**Pull request merged**
