### PR TITLE
Add docs for nnkHiddenStdConv

### PR DESCRIPTION
**Pull request by treeform**

### CODE REVIEW

**Review by timotheecour — APPROVED** [review]

**Comment by timotheecour** [comment]
LGTM but this needs to be targetting devel, not 1-4; don't merge before this is fixed
(click on Edit in PR next to title, no need to open a new PR)

**Review by ringabout — CHANGES_REQUESTED** [review]
Please change the base branch

**Comment by treeform** [comment]
I changed the base branch, but now it has all of these extra commits?
I don't understand what is going on.

**Comment by treeform** [comment]
I created a different pull rq to get around this. https://github.com/nim-lang/Nim/pull/16408

**Comment by timotheecour** [comment]
@treeform 
> I don't understand what is going on.

the problem is that devel in your fork isn't up to date, all you needed to to instead of opening a new PR was:
* 1. push devel in your fork to latest devel
* 2. change target branch in this PR to devel

if you did 2 before 1 you can change target branch to anything else, do 1, then 2 again

**Pull request closed without merging**
