### PR TITLE
Table.withValue(): .. else: support

### PR DESCRIPTION
**Pull request by Menduist**
This PR adds support for
```nim
    t.withValue(522, value):
      doAssert false
    else:
      # block is executed when `key` not in `t`
      discard
```
(previously a `do` was required)

### CODE REVIEW

**Comment by metagn** [comment]
Could also do:

```nim
import macros

macro unwrapElse(ex: untyped): untyped = # maybe goes somewhere in standard library
  if ex.kind == nnkElse:
    result = ex[0]
  else:
    result = ex
    
template foo(a, b, c) =
  if a:
    b
  else:
    unwrapElse(c)
    
foo false:
  echo "a"
else:
  echo "b"
```

**Comment by Menduist** [comment]
Done, though I don't understand the CI failure, seems to be caused by IC trying to use the macro at runtime?

**Comment by metagn** [comment]
Probably not worth it to investigate IC, the original way is good enough. Though a way to refactor it might be:

```nim
template withValueImpl(..., elseBlock) =
  # original withValue

macro withValue*(..., originalElseBlock) =
  let elseBlock = if originalElseBlock.kind == nnkElse: originalElseBlock[0] else: originalElseBlock
  result = getAst(withValueImpl(..., elseBlock))
```

so the actual implementation of `withValue` is a bit more visible.

**Comment by Menduist** [comment]
The original way also caused the same CI failure, unfortunately

**Pull request closed without merging**
