### PR TITLE
[WIP] fix https://github.com/nitely/nim-regex/issues/60

### LINKED ISSUE #60: nim CI important_packages failure
probably caused by the recent changes:
https://github.com/nim-lang/Nim/pull/13865

https://dev.azure.com/nim-lang/255dfe86-e590-40bb-a8a2-3c0295ebdeb1/_apis/build/builds/4019/logs/80
```
2020-04-04T09:41:33.8575534Z PASS: https://github.com/andreaferretti/react.nim C                ( 4.24 sec)
2020-04-04T09:41:33.8575912Z FAIL: https://github.com/nitely/nim-regex C
2020-04-04T09:41:33.8577041Z Test "https://github.com/nitely/nim-regex" in category "nimble-packages"
2020-04-04T09:41:33.8577375Z Failure: reBuildFailed
2020-04-04T09:41:33.8577583Z package test failed
2020-04-04T09:41:33.8577798Z $ nim c src/regex
2020-04-04T09:41:33.8578074Z Hint: used config file 'd:\a\1\s\config\nim.cfg' [Conf]
2020-04-04T09:41:33.8578458Z Hint: used config file 'd:\a\1\s\config\config.nims' [Conf]
2020-04-04T09:41:33.8578753Z Hint: system [Processing]
2020-04-04T09:41:33.8579001Z Hint: widestrs [Processing]
2020-04-04T09:41:33.8579219Z Hint: io [Processing]
2020-04-04T09:41:33.8579453Z Hint: regex [Processing]
2020-04-04T09:41:33.8579743Z Hint: tables [Processing]
2020-04-04T09:41:33.8580222Z Hint: hashes [Processing]
2020-04-04T09:41:33.8580504Z Hint: math [Processing]
2020-04-04T09:41:33.8580740Z Hint: bitops [Processing]
2020-04-04T09:41:33.8580953Z Hint: macros [Processing]
2020-04-04T09:41:33.8581192Z Hint: algorithm [Processing]
2020-04-04T09:41:33.8581426Z Hint: sequtils [Processing]
2020-04-04T09:41:33.8581648Z Hint: unicode [Processing]
2020-04-04T09:41:33.8581892Z Hint: strutils [Processing]
2020-04-04T09:41:33.8582115Z Hint: parseutils [Processing]
2020-04-04T09:41:33.8582514Z d:\a\1\s\pkgstemp\regex\src\regex.nim(156, 17) Error: cannot open file: pkg/regex/nodetype
2020-04-04T09:41:33.8582818Z 
2020-04-04T09:45:45.5746035Z PASS: https://github.com/arnetheduck/nim-result C                  ( 4.78 sec)
```

### PR DESCRIPTION
**Pull request by timotheecour**
[DO NOT REVIEW YET]

fix https://github.com/nitely/nim-regex/issues/60

nim-regex (after an awesome performance update) is now using `import pkg/foo` instead of `import foo` which broke nim CI because it was using `nim c src/regex` and for some reason `src` isn't in the path (maybe because the logic for important_packages doesn't install foo ?)

EDIT: doesn't work yet... but i've now found the root cause and it's a bug in important_packages logic, not in regex package:
`nimble install regex` installs the latest release tag (13.1), as it should (we should only test latest releases, HEAD would be too unstable)
but then `git clone regex` clones HEAD (which is different from latest release tag), and it fails with `import pkg/foo` since that refers to the installed regex, not the cloned one.

## the fix
either use nimble develop after the clone (but that has the drawback of testing HEAD instead of latest release), or (preferred), after git clone we must `git reset --hard rev` where rev is the revision used in nimble install

there are other (preexisting) issues though:
if `nimble install bar` installs foo at a specific version, (say regex at 10.0) that is different from the one implied by `nimble install foo`, it can cause issues

the obvious short term workaround is to disable regex, but the underlying issue is still there and will keep popping up unless it is fixed

## EDIT
upstream regex was updated to remove `import pkg/foo` so the bug disappeared but underlying issue is still there.
if we're disallowing `import pkg/foo` (btw we should have a linter to issue warnings when this is detected), that means we're forced to use `import foo` which can cause ambiguities; maybe what we need is:

`import thispkg/foo` to refer to current nimble package (implementation is easy, built on top of `getNimbleFile` from https://github.com/nim-lang/Nim/pull/13223). I will explain this in more details later.

### CODE REVIEW

**Comment by Araq** [comment]
Once again the root cause is Nimble with it's stupid $nimbleDir.

**Comment by genotrance** [comment]
Every package should be testable without installation. Especially important packages should have a cfg with `--path:src` or equivalent if not already.

**Comment by timotheecour** [comment]
@araq 
> Once again the root cause is Nimble with it's stupid $nimbleDir.

That's not the root cause, and `NIMBLE_DIR` is essential for sandboxing in particular on user's machine eg `export NIMBLE_DIR=$HOME/.nimble_alt && nimble install foo && nimble test`

The root cause is what I described above or here https://github.com/timotheecour/Nim/issues/167, and keeps breaking important_packages, as just happened again today with inim (https://github.com/inim-repl/INim/issues/74), see my explanation here: https://github.com/inim-repl/INim/issues/74#issuecomment-618869294

* important_packages.nim does this:
* `nimble install inim` => this installs inim at latest release tag
* `git clone inim https://github.com/inim-repl/INim && cd INim && nimble test` => we've installed inim at latest release tag but test inim at HEAD, which is obviously a bug: latest commit added `requires "https://github.com/PMunch/ansiparse"` so depends on `ansiparse`, but that package won't be installed by nimble install since that dependency wasn't added after latest release tag. Or maybe that dependency is there, for totally unrelated ephemeral reasons, because some other important_package installed it.

the short term fix is simple: 
after `git clone foo`, we need to also do `git checkout rev` where rev is whatever revision got installed by `nimble install foo`

@genotrance 
> Every package should be testable without installation.

that can't work if package `foo` depends on `bar`.
What should work is `nimble test foo` where installation still happens, but under-the-scene.

## note: testing head vs testing latest release tag
IMO important_packages should only be concerned with testing packages at their latest release tag (eg 1.2.3), not at HEAD. That's what my proposed solution would enable.
Testing at HEAD would just break a lot more often especially wrt depenencies.

> Especially important packages should have a cfg with --path:src or equivalent if not already.

I'm on the fence on this. should be discussed further.

**Comment by Araq** [comment]
> IMO important_packages should only be concerned with testing packages at their latest release tag (eg 1.2.3), not at HEAD. That's what my proposed solution would enable.
Testing at HEAD would just break a lot more often especially wrt depenencies.

Ok, that is an acceptable design. However, this PR does nothing like that and stalled.

**Comment by timotheecour** [comment]
and yet another instance of this: https://github.com/c-blake/cligen/issues/142

**Pull request closed without merging**
