### PR TITLE
Fix readLine handling of long lines.

### PR DESCRIPTION
**Pull request by rbehrends**
Fix readLine handling of long lines.

### CODE REVIEW

**Comment by Araq** [comment]
@def- ping, please review.

**Comment by rbehrends** [comment]
Yes, I'd like to have someone independently check this. There are several corner cases due to the poor design of `fgets()`; I think I got them all, but independent verification would be a good thing.

**Comment by Varriount** [comment]
Just wondering, how much of a performance impact does this have?

**Comment by rbehrends** [comment]
Performance impact should be fairly small, given that `memset()` and `memchr()` are likely to dominate cost. More importantly, the current implementation is simply incorrect and needs to be fixed.

It would be worthwhile to have a high-performance implementation for `readLine()` and `lines()` that uses buffered reads, but that would require a separate data structure to store the buffer and cannot be tacked on to a `FILE *`.

**Comment by def-** [comment]
Looks good to me.

**Pull request merged**
