### PR TITLE
make case-object transitions explicit, make unknownLineInfo a const, …

### PR DESCRIPTION
**Pull request by ghost**
…replace a few magic numbers with consts

### CODE REVIEW

**Comment by Araq** [comment]
Oh wow this is amazing! I had no idea we can do this... :-)

**Comment by Varriount** [comment]
Out of curiosity, what exactly do the transition procedures do? All I can tell is that they take a roundabout way to change the node's `kind` field.

**Comment by ghost** [comment]
That is what they are.
As of 0.20(?) Nim warns on assignment to discriminator and terminates at runtime on a branch transition. Only `transitionNoneToSym` is an actual branch transition, the rest are to suppress warnings.
Currently the compiler builds with `warning[CaseTransition]:off` and `define:nimOldCaseObjects` to suppress these behaviors.
The motivation being my code which uses the compiler as a library is not forced into a less safe mode of operation.

**Comment by timotheecour** [comment]
@dumjyl  cool but `transitionSymKindCommon` + friends are not DRY; 

the following `caseTransition` allows safe case transition, copying all the fields automatically; 

maybe that could be added to stdlib ?

```nim
  import std/macros
  macro getFieldByName*(s, name: untyped): untyped =
    result = newTree(nnkDotExpr, s, name.`$`.ident)

  template caseTransition*(obj: var object, caseIdent, caseVal: untyped): untyped =
    let old = obj
    type T = type(obj)
    obj = T(caseIdent: caseVal)
    const s = astToStr(caseIdent)
    for name, v in fieldPairs(obj):
      when name != s:
        v = getFieldByName(old, name)

  ## usage
  type Kind = enum
    k1, k2, k3

  type Foo1 = object
    x1: int
    case kind: Kind
    of k1, k2:
      x12: string
    of k3:
      x3: string

  proc main()=
    var a1 = Foo1(kind: k1, x12: "abc", x1: 12)
    echo a1
    caseTransition(a1, kind, k2)
    echo a1

  main()
```

prints:
```
(x1: 12, kind: k1, x12: "abc")
(x1: 12, kind: k2, x12: "abc")
```

(and with a bit more work on the macro, the intermediate copy `let old = obj` can probably be avoided)

**Pull request merged**
