### PR TITLE
Create chomp proc and tests

### PR DESCRIPTION
**Pull request by zachaysan**
Note: I haven't figured out the rsu____ pragma pattern yet. I tried blindly adding it and compiling, but that did not work. If there is a link to where I can learn more about the pragmas I'd be happy to learn.

Feel free to reject this request if you want stylistic changes to the code. I'm still new to the Nim language :)

### CODE REVIEW

**Comment by ReneSac** [comment]
Many problems:
* You should not have moved `{.pop.}` to after your additions. Those checks are probably desired.
* You should prefer using result instead of return.
* You can use `^1` and `^2` instead of your `last` and `last -1`.
* No documentation. Make clear what the differences are compared to strip, for example. And put a use case with code example, that split would not do.

**Comment by zachaysan** [comment]
Hey ReneSac! Thanks for taking the time with your response :)

Re: `{.pop.}` Good catch, I will update the PR with changes.

Re: Result - ah force of habit, will update PR with that change.

Re: `^1` and `^2` Thanks for that, I'll definitely keep those in mind for the future, but for this specific proc I think it is clearer the way it is since suffix strings can have variable length and the complications with `\n` vs `\r\n` make it easier to handle, but I'm open to suggestions.

Re: Documentation - I wasn't even sure if Araq would clear the idea of Chomp until reviewing the logs after getting home. I'll update the PR with full documentation. As for differences between `chomp` and `strip` I'll make sure I cover them, although there are differences in what you can do, the primary use case of `chomp` is for programmer delight / legibility.

Re: the returning a new string vs in-place modification, in Ruby we have `chomp` and `chomp!` which handle each case. Since most things in strutils returned a new string, I decided to just return a new string. Is there a standard method that people in the Nim community do for this? I'd prefer to have the option for in place vs return new string if possible, but I didn't see that done in the code base very frequently.

**Comment by reactormonk** [comment]
For in-place modification, we have the `var` types. If something is modifiable, modify it.

**Comment by Araq** [comment]
> I decided to just return a new string. Is there a standard method that people in the Nim community do for this? I'd prefer to have the option for in place vs return new string if possible, but I didn't see that done in the code base very frequently.

You're right that it's not done frequently. There is a ``reverse`` vs ``reversed`` or ``sort``  vs ``sorted`` distinction though so it would be ``chomped``  and ``chomp``

**Comment by ReneSac** [comment]
Let's see:
`s.chomp()` is kinda like `.strip(leading=false, chars=NewLines)`, but will only remove one new line marker. This isn't as useful in nim as in ruby or pearl, as readlines does the new line stripping for you.

`s.chomp("string")` is more unique, and like the above only remove one instance of the thing. Maybe we should have an strip accepting a string too.

`s.chomp("")` is an anomaly. It is in between `s.chomp()` and `.strip(leading=false, chars=NewLines)`. Using the empty string to mean something else is quite unorthodox. I don't think it is necessary.

**Comment by zachaysan** [comment]
> That doesn't return a new string makes more sense so that chomp even more fills a void.

I agree and it would cover the normal use case more frequently. Should we call it `chomped` instead and default to in-place modification?

> `s.chomp("")` is an anomaly.

I agree, I can / am happy to remove it, but I initially leaned towards mirroring Ruby's ability since I thought they may have come across a semi-common edge case that warranted different behaviour and solved it with empty string I also thought mirroring chomp's behaviour would reduce mental overhead to Ruby devs that were used to it. 

> `s.chomp()` is kinda like s.strip(leading=false, chars=NewLines)
> Maybe we should have an `strip` accepting a string too.

I think string manipulation is fairly common so I don't think the inclusion of chomp would be needlessly bloated, and I shy away from overloading strip since it 1. Removes repeats by default which fits it's name, but isn't what I want . 2. Because users may forget the `leading=false` flag which will result in bugs like `snakes.strip("s")`.

**Comment by Varriount** [comment]
I'm not entirely happy with the name... "chomp", while clever, lacks that self-explanatory characteristic that procedures like "strip" and "replace" possess.

**Comment by kirbyfan64** [comment]
@Varriount Doesn't Perl use `chomp`?

**Comment by Varriount** [comment]
@kirbyfan64 I don't know, I haven't written in Perl before\*. Even if out is used, the argument still stands that the name is a non-obvious verb (What exactly does chomping a string of characters mean?).

\* Although from what I've read, using the "Well language X does it this way" argument with Perl may not be the best idea.

**Comment by kirbyfan64** [comment]
@Varriount Yeah, Perl isn't necessarily the best example of a readable programming language...

**Comment by strcmp** [comment]
it's not just Perl that uses the name "chomp", Ruby does too, so while the name might be bad I think its behaviour could be easily identified by programmers with the name "chomp" where as another name I'm not sure, unless it's a really good name :)

**Comment by Xe** [comment]
Can you add documentation?

**Comment by zachaysan** [comment]
@Xe, I'm kinda waiting on where the community land on whether they actually want Chomp in and what they want it to look like if it comes in before changing the PR to include documentation. If you want to see the original intended behaviour check out Ruby's `chomp` method. Although the final implementation is probably going to change. I'm kinda waiting on direction before modifying the PR.

**Comment by ReneSac** [comment]
@zachaysan: I'm not against the inclusion of chomp. But I don't like the `""` argument for chomp making it behave in a completely different and non-ituitive way. We can make a new proc or a new boolean parameter latter if people want this specific behaviour. It may be familiar for Ruby programmers, but will trip everybody else.

And about the name: chomp would be for in-place modification, chomped would return a new chomped string. @Varriount: The other name suggested was `chop`.  Any other ideas?

**Comment by Varriount** [comment]
@renesac Yes, I'd favour "chop" more than chomp (it's not perfect, but better)

**Comment by zachaysan** [comment]
@ReneSac: Agreed, I'll remove the "" arg.

As for `chop` I'm against it. In Perl, [Ruby](
http://ruby-doc.org/core-2.2.2/String.html#method-i-chop), and D `chop` means:

> Remove the last character of a string. If the removed character is a newline, remove a paired return feed as well if there is one.

And all three languages (Perl, Ruby, D) have support for `chomp` and `chop` so I wouldn't want to pollute the meaning.

Perhaps `removeSuffix` as a less cute name?

**Comment by Varriount** [comment]
Yes!

**Comment by strcmp** [comment]
if we go with removeSuffix how are you going to name the proc that does in-place modification? removeSuffixed? :)

**Comment by strcmp** [comment]
other way around but yeah ;)

**Comment by Varriount** [comment]
Wouldn't it be removedSuffix? (Then again, the former is more visually obvious)

**Comment by zachaysan** [comment]
Well, if we are going to go with *just* the in-place modified version, it seems kinda silly to just have `removedSuffix` since it hints that there would be a `removeSuffix` without there actually being one there.

**Comment by Varriount** [comment]
Oh. I was assuming there would be both in-place and copying versions.

**Comment by zachaysan** [comment]
Ok, I added some of the changes we talked about here. I'd like Araq to comment if he has time, since he never actually ack'd the change to `removeSuffix` and if he'd like a non-in-place version I can add that as well.

Which brings me to a question I've been thinking about: Why do we decide these on a proc by proc level? Wouldn't it be better to just make a in-place version of every string function? It wouldn't even be that much extra work, since each non-in-place proc could just clone the input and return the changed clone.

**Comment by Araq** [comment]
@dom96 is reponsible for the stdlib, not me.

**Comment by dom96** [comment]
I like ``removeSuffix`` but I don't think it should be in-place.

**Comment by dom96** [comment]
Are in-place versions of all of these things really that important? There are some inconsistencies in the ``strutils`` module. The ``delete`` proc for example is in-place, but almost every other proc in that module is not. Many procedures would need to be renamed to follow the ``reverse`` vs. ``reversed`` convention.

**Comment by reactormonk** [comment]
Is overloading on var too unpredictable?

**Comment by kirbyfan64** [comment]
@reactormonk That's *way* too C++-ic. A lot.

**Comment by zachaysan** [comment]
> Are in-place versions of all of these things really that important?

@dom96 I haven't tested the performance or in place vs copy, since I assume it's similar to C. That being said, in my opinion, while this language is still prior to mass adoption I think we should nail the performance on the areas of the code base that are going to be widely used. Especially string manipulation. For example, some people will build APIs that will take in base64 encoded images. I don't think we should assume that in-place is irrelevant. Especially with chained string manipulations, the memory footprint would start to add up.

Also, It will be much more difficult to transition libraries if we have to update `strip` to be `strip` and `stripped`. This is one of the reasons I like how Ruby uses an exclamation point for in place modification, it allows that option to be added later and it is more predictable, but since convention is to add `ed` to the end of the proc name, we should figure out what truly *doesn't* need in-place before it becomes more difficult.

Since Nim is hitting 1.0 sometime late this year I think it will start to gain serious traction. Until then though I don't think shying away from completeness is the right move, even if it comes at the cost of some bloat. The last thing we want is fragmentation in the string manipulation libraries.

**Comment by Varriount** [comment]
Defaulting to in-place operations is the safer choice of the two. String copying isn't hard (just an assignment) and new procedures can be made in the future to do copying automatically.

**Comment by kirbyfan64** [comment]
Ugh, I hate in-place operations. They screw over lambdas and make writing functional pipelines (e.g. `map` and `filter`) a pain in the behind.

**Comment by reactormonk** [comment]
@kirbyfan64 Not necessarily. If you map in a destructive sense from the same to the same type, it's pretty simple to chain.

**Comment by zachaysan** [comment]
@Araq I'm back from vacation, so I have time to put in more effort if more is required. Can I get some direction on this?

**Comment by dom96** [comment]
@zachaysan Please make these return a new copy of the string. I think a good reason for this is that you can then call this function on a string literal or immutable string.

**Comment by zachaysan** [comment]
@dom96 Ok, will handle that tomorrow. So "no" to the inplace modify version?

**Comment by Varriount** [comment]
@don96 We have mutable strings for a reason. Why not support both in-place and copying versions? Otherwise we get "omg Nim strings are so slow".

Even if the decision isn't made here, it will have to be made at some point - I consider it a major flaw that many of the manipulation procedures in the  strutils module don't support in-place modification.

**Comment by zachaysan** [comment]
I agree with @Varriount, but I also understand letting the issue to rest right now.

**Comment by dom96** [comment]
I don't disagree, we need a convention for naming when we want both an in-place and a copying version though. A thought just came to me: could we just overload the same proc name? (@Araq, is this a bad idea?)

**Comment by zachaysan** [comment]
I missed araq's comment about how you (Dominik) was in charge of the standard lib. I strongly favor using the ruby styled ! to denote inplace modification because it is more predictable than to where to put the "ed" and whether a method is inplace or not. For example, sort is inplace but strip is not. That can be a cause for confusion and can make it harder to create an inplace version later.

Regardless, I'm happy to write in place versions of every strutil function if we decide to do so and to update this PR once we've decided what to do. 

-Zach

**Comment by reactormonk** [comment]
You can't use `!`, `sort!` is parsed as two identifiers.

**Comment by Araq** [comment]
Well the reason why ! and ? are not available as suffix is that I think it doesn't work well with user definable operators:  foo! bar  is  (foo) ! (bar)  in Nim. The inplace vs not inplace distinction is done with the type system instead: If it returns ``void``, you know it's inplace, otherwise it's not.

> That can be a cause for confusion and can make it harder to create an inplace version later.

It's not more confusing than Ruby where the '!' is only a convention and frequently ignored too. In fact, it's a very strange thing to do in an OO world where mutable state abounds anyway.

**Comment by Araq** [comment]
> could we just overload the same proc name?

Meh, we have no void vs non-void overloading resolution but it's not hard to do I guess. Except that it is yet more complexity in the language. And for what? cause you cannot accept 'sort' vs 'sorted'? Come on.

**Comment by dom96** [comment]
@Araq 
```nim
proc foo(x: string) = echo("non-var")
proc foo(x: var string) = echo("var")
foo("asdf") # -> non-var
```

Works.

**Comment by dom96** [comment]
There is no need for any additional support in the compiler.

**Comment by Varriount** [comment]
I would prefer not to overload based on var type (or even return type), in favor of explicit naming differences. Whether a different tense should be used ('chomped' vs 'chomping') or a suffix ('chompMod'. 'chompM') is difficult to decide.

**Comment by dom96** [comment]
@Varriount Why?

**Comment by zachaysan** [comment]
For others that don't understand what @dom96 is arguing:

Basically since we control whether or not a string is immutable with the `let` vs `var` distinction, we can ditch the whole idea of differing names and just lean on the type system to sort it out. See this example:

```nim
proc excite(x: string): string =
  x & "!"

proc excite(x: var string): string =
  x.add("!")

let a = "Nimrod"
var b = "Nim"

discard excite(a)
echo a # prints "Nimrod"                                                                                                                  
discard excite(b)
echo b # prints "Nim!"                                                                                                                    
```

Which I like.

Aside: Why does `excite(excite(b))` cause a `Illegal storage access.` error? I'd expect to be able to chain mutating methods.

**Comment by strcmp** [comment]
It's an interesting idea, I like it too, does that mean in-place modification will become the default for mutable strings as time goes by? I think it would only be a matter of providing in-place alternatives to do that, and then you wouldn't have to think about mutable vs not, just you have a string defined with 'var' or 'let'.

**Comment by kirbyfan64** [comment]
-1 to that proposal. To me, it's too subtle a distinction and would end up being a major bug magnet.

**Comment by Araq** [comment]
@dom96 This has been discussed to death already and it is a **bad** idea.

That procs return their first argument just to support chaining is bad and not required in wonderful Nim land where you can just use a macro instead of patching each and every proc to support your questionable coding style. Inplace op + non-void return value is just evil and won't happen.

**Comment by dom96** [comment]
@Araq Alright. So you're suggesting to:

* Remove all the current procedures which "return their first argument", for example ``proc toUpper(s: string): string``
* Replace them all with ones which modify the first argument instead of returning a new copy, for example: ``proc toUpper(s: var string)``
* Create a macro which makes chaining easier. Any ideas how the invocation of such a macro will look like? I can't imagine how you will get convenient chaining syntax using macros.

I think my suggestion may have been misinterpreted so let me be clear, I want:

* To have both a ``proc toUpper(s: string): string`` and a ``proc toUpper(s: var string)``, for all string operations (ideally).

Funnily enough, now that I think about it, this could actually be generated easily with a macro. Is this a bad idea? Why?

**Comment by Varriount** [comment]
Judging by the number of comments here, as well as the complexity of the problem, perhaps this discussion should be tabled for now. I would prefer for an enhancement proposal to be submitted arguing for a particular solution, rather than for us to clutter up poor @zachaysan's PR with (offtopic) discussion.

**Comment by Araq** [comment]
@dom96 No, no and no.

> I think my suggestion may have been misinterpreted so let me be clear, I want.

No, I understood you correctly and it's a horrible idea unless we get a limited form of overloading by return type.

**Comment by dom96** [comment]
@Araq But why is it a bad idea? You're still not being clear.

**Comment by kirbyfan64** [comment]
Because it's confusing??

**Comment by Araq** [comment]
Because ``var x = ...; toUpper(x)`` shouldn't be different from ``let x = ...; toUpper(x)`` or from ``toUpper("abc")``. Code is edited, what used to be a ``let`` can become a ``var`` for different reasons and you don't want that ``toUpper`` suddenly to act differently or suddenly to not compile anymore ("expression has type 'void'").

**Comment by dom96** [comment]
@Araq Thank you.

**Comment by andreaferretti** [comment]
My 2 cents:

* I agree with Araq that mutating procs should have `void` return value
* I am fine with using explicitly different names instead of dispatching based on `var` vs `let`, but
* I would still expect that procs that mutate string **do** take a `var string` as parameter (this should not be controversial, but following the discussion I am not sure)

**Pull request merged**
