### PR TITLE
Added examples in documenation for len dec inc incl excl

### PR DESCRIPTION
**Pull request by TheAnonymous**

### CODE REVIEW

**Comment by TheAnonymous** [comment]
Added example
```
for i in 0..<arr.len: 
  echo arr[i]
```

**Comment by Araq** [comment]
I think these are so common that it's better we improve their docs in the tutorials.

**Comment by TheAnonymous** [comment]
I oriented on the Ruby documentation (e.g. [Array](http://docs.ruby-lang.org/en/2.0.0/Array.html)) as it's IMHO one of the best documentations.
And there are examples for **every** method, which I found very helpful when Ruby was new to me.
These was a first attempt to improve the documentation.
If you think there is a better way to do this please point me to it.

**Comment by dom96** [comment]
I think the more examples we show the better.

**Pull request merged**
