### PR TITLE
fix #16264  low(Time) OverflowDefect

### LINKED ISSUE #16264: regression(0.18.0 => devel): `import times; echo low(Time)` gives OverflowDefect
regression: `import times; echo low(Time)` gives OverflowDefect

### Example
```nim
import times
echo low(Time)
```

### Current Output
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11448.nim(6) t11448
/Users/timothee/git_clone/nim/Nim_devel/lib/pure/times.nim(2152) $
/Users/timothee/git_clone/nim/Nim_devel/lib/pure/times.nim(1318) local
/Users/timothee/git_clone/nim/Nim_devel/lib/pure/times.nim(1175) inZone
/Users/timothee/git_clone/nim/Nim_devel/lib/pure/times.nim(1081) initDateTime
/Users/timothee/git_clone/nim/Nim_devel/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: over- or underflow [OverflowDefect]

### Expected Output
works

### Additional Information
* fails in 1.5.1 devel edce5897a52aac308fbe9b14f155139f15da02cd
* works in 0.18.0

found this while debugging HCR issues, which uses `low(Time)` as initial value

EDIT: I found this code in nimhcr:
```nim
  proc sanitize(arg: Time): string =
    when defined(testNimHcr): return "<time>"
    else: return $arg

```
that may be related, in which case it should probably be fixed in PR that fixes this

### PR DESCRIPTION
**Pull request by bung87**
…gives OverflowDefect  

fix #16264

### CODE REVIEW

**Comment by Araq** [comment]
So instead you introduced a new regression. Nobody cares about version 0.18 anymore.

**Comment by bung87** [comment]
`initTime(low(int64), 0)` means nothing to me, and it doesn't really work. it's not about `0.18`

https://play.nim-lang.org/#ix=4cUC

**Comment by bung87** [comment]
this existed since v1.4.0 when the times module refactoring.

**Comment by bung87** [comment]
@Araq pls merge this!

**Pull request merged**
