### PR TITLE
deprecate `high(value)` and `low(value)`

### PR DESCRIPTION
**Pull request by narimiran**
As discussed on the forum: https://forum.nim-lang.org/t/6780

### CODE REVIEW

**Comment by juancarlospaco** [comment]
But for `enum` and `range` kinda makes sense?,
how do you get the `high` and `low` of an unknown `range` when this is removed?.

**Comment by alehander92** [comment]
@juancarlospaco yes, but this is only for value, the typedesc version stays :)

**Comment by kaushalmodi** [comment]
@narimiran Hello. This deprecation is causing a lot of warnings in the compiler/ code

```
/home/kmodi/downloads/git/Nim/compiler/ast.nim(1359, 13) Warning: Deprecated since v1.4; there should not be `low(value)`. Use `low(type)`.; low is deprecated [Deprecated]
/home/kmodi/downloads/git/Nim/compiler/ast.nim(1360, 19) Warning: Deprecated since v1.4; there should not be `low(value)`. Use `low(type)`.; low is deprecated [Deprecated]
...........................................
/home/kmodi/downloads/git/Nim/compiler/saturate.nim(18, 14) Warning: Deprecated since v1.4; there should not be `low(value)`. Use `low(type)`.; low is deprecated [Deprecated]
/home/kmodi/downloads/git/Nim/compiler/saturate.nim(20, 14) Warning: Deprecated since v1.4; there should not be `high(value)`. Use `high(type)`.; high is deprecated [Deprecated]
/home/kmodi/downloads/git/Nim/compiler/saturate.nim(27, 14) Warning: Deprecated since v1.4; there should not be `low(value)`. Use `low(type)`.; low is deprecated [Deprecated]
/home/kmodi/downloads/git/Nim/compiler/saturate.nim(29, 14) Warning: Deprecated since v1.4; there should not be `high(value)`. Use `high(type)`.; high is deprecated [Deprecated]
/home/kmodi/downloads/git/Nim/compiler/saturate.nim(32, 11) Warning: Deprecated since v1.4; there should not be `low(value)`. Use `low(type)`.; low is deprecated [Deprecated]
/home/kmodi/downloads/git/Nim/compiler/saturate.nim(36, 14) Warning: Deprecated since v1.4; there should not be `low(value)`. Use `low(type)`.; low is deprecated [Deprecated]
/home/kmodi/downloads/git/Nim/compiler/saturate.nim(43, 13) Warning: Deprecated since v1.4; there should not be `low(value)`. Use `low(type)`.; low is deprecated [Deprecated]
/home/kmodi/downloads/git/Nim/compiler/saturate.nim(44, 14) Warning: Deprecated since v1.4; there should not be `high(value)`. Use `high(type)`.; high is deprecated [Deprecated]
/home/kmodi/downloads/git/Nim/compiler/saturate.nim(77, 14) Warning: Deprecated since v1.4; there should not be `high(value)`. Use `high(type)`.; high is deprecated [Deprecated]
/home/kmodi/downloads/git/Nim/compiler/saturate.nim(79, 14) Warning: Deprecated since v1.4; there should not be `low(value)`. Use `low(type)`.; low is deprecated [Deprecated]
..........
/home/kmodi/downloads/git/Nim/compiler/vmgen.nim(614, 19) Warning: Deprecated since v1.4; there should not be `high(value)`. Use `high(type)`.; high is deprecated [Deprecated]
```

**Comment by narimiran** [comment]
@kaushalmodi  Ok, I've created a PR fixing the stuff you mention in your comment: https://github.com/nim-lang/Nim/pull/15291

If there's something else that produces the warning, you can comment either here or under that PR.

**Pull request merged**
