### PR TITLE
`lineInfoObj` (and `check`, `expect`) now return absolute paths

### PR DESCRIPTION
**Pull request by timotheecour**
/cc @Varriount 

before PR:
check 1==2 would return project path regardless of --listFullPaths
(inconsistent with other logging)

after PR:
check 1==2 would return absolute path when --listFullPaths is provided
(consistent with other logging)

likewise with require.

Note: this fixes https://github.com/nim-lang/Nim/issues/7429 (item A_lineInfoObj)

**EDIT**
/cc @Araq 
new behavior after feedback from @araq is to always return absolute path instead of previous behavior which was to always return project path. New behavior is better because project path can be ambiguous for users when printed out as it depends on cmd line args (it found the first path, via `-p` cmd line, where file is found and prints the path relative to that)

- [ ] future PR could be to allow customizing what's returned by `lineInfoObj`, but that's controversial and left out of this PR

### CODE REVIEW

**Comment by Araq** [comment]
But this compiler option should not affect the paths the macro system exposes. The proper fix is to use ``toFullPath`` here. I think.

**Comment by timotheecour** [comment]
> The proper fix is to use toFullPath here. I think.

user may want to configure whether to return relative or absolute paths though (there are use cases for both, eg when sharing error messages with others, it's best to use relative paths; for personal projects absolute paths may be better (eg in case of multiple clones etc).

currently `--listFullPaths` is documented as: `list full paths in messages`
so I expected it to work with both compile time messages (eg compile warnings) and runtime ones (eg expect) ; if you wanna distinguish these 2 things, how about I add a flag:
`--listFullPathsRuntime list full paths in runtime messages`
and change doc of `--listFullPaths` to:
`--listFullPaths list full paths in compile time messages`
and implement `opcNGetFile` using a new `toMsgFilenameRuntime` that acts like `toMsgFilename` except it's controlled by `--listFullPathsRuntime` instead of `--listFullPaths`

**Comment by Araq** [comment]
No no no. Only compile time messages are affected by these switches, otherwise nobody could use ``instantiationInfo`` in a library and get reliable results; these should not be affected by an obscure compiler switch.

**Comment by Araq** [comment]
Oh sorry, please also add an entry to the changelog that documents this changed behaviour.

**Comment by timotheecour** [comment]
PTAL

**Pull request merged**
