### PR TITLE
Fix getting custom pragma from generic object

### PR DESCRIPTION
**Pull request by ire4ever1190**
`getCustomPragmaVal` and `hasCustomPragma` fail when the object is generic

Running this snippet causes `macros.nim(1573, 22) Error: node is not a symbol`
```nim
import macros
template examplePragma() {.pragma.}
type
  Foo[T] {.examplePragma.} = object
    x {.examplePragma.}: T
var f: Foo[string]
doAssert f.hasCustomPragma(examplePragma)
doAssert f.x.hasCustomPragma(examplePragma)
```
Adds fix and test case

### CODE REVIEW

**Comment by ire4ever1190** [comment]
Seems I didn't fix it properly, found some other cases where it fails

**Comment by ire4ever1190** [comment]
```nim
type Foo[T] {.examplePragma.} = object
  when T is float:
    t2 {.examplePragma.}: float
```
the `examplePragma` in `t2` seems to be removed from the AST
```
TypeDef
  PragmaExpr
    Sym "Foo"
    Pragma
      Sym "examplePragma"
  GenericParams
    Sym "T"
  ObjectTy
    Empty
    Empty
    RecList
      RecWhen
        ElifBranch
          Infix
            Sym "is"
            Sym "T"
            Type
          Sym "t2"
```

**Comment by Varriount** [comment]
@ire4ever1190 Is this PR ready to be reviewed? It's not clear from your comments whether the original issue still exists.

**Comment by ire4ever1190** [comment]
Sorry about that, removed the comments to remove confusion.

The PR is ready for review. The original snippet shown doesn't work on latest devel but is fixed in this PR

**Pull request merged**
