### PR TITLE
delete list comprehension

### PR DESCRIPTION
**Pull request by krux02**
removal is overdue

### CODE REVIEW

**Comment by Araq** [comment]
No changelog entry?

**Comment by krux02** [comment]
done

**Comment by krux02** [comment]
The changelog entry cause the test failure? The failing test is surprisingly ``tsqlite.nim`` how? Is it a new flaky test? Should I disable it?

**Comment by krux02** [comment]
```
Failure: reBuildFailed
package test failed
$ nim c -r tests/tsqlite.nim
Hint: used config file 'C:\projects\nim\config\nim.cfg' [Conf]
Hint: used config file 'C:\projects\nim\config\config.nims' [Conf]
Hint: used config file 'C:\projects\nim\pkgstemp\norm\tests\config.nims' [Conf]

[Suite] Creating and dropping tables, CRUD
    C:\projects\nim\pkgstemp\norm\tests\tsqlite.nim(82, 51): Check failed: dbConn.getAllRows(sql query % "users") ==
    @[@[?0, ?"id", ?"INTEGER", ?1, ?nil, ?1],
      @[?1, ?"email", ?"TEXT", ?1, ?nil, ?0],
      @[?2, ?"ssn", ?"INTEGER", ?0, ?nil, ?0],
      @[?3, ?"birthDate", ?"INTEGER", ?1, ?nil, ?0],
      @[?4, ?"lastLogin", ?"INTEGER", ?1, ?nil, ?0]]
    dbConn.getAllRows(sql query % "users") was @[@[0, 'id', 'INTEGER', 1, '0', 1], @[1, 'email', 'TEXT', 1, '''''', 0], @[2, 'ssn', 'INTEGER', 0, NULL, 0], @[3, 'birthDate', 'INTEGER', 1, NULL, 0], @[4, 'lastLogin', 'INTEGER', 1, '0', 0]]
    @[@[?0, ?"id", ?"INTEGER", ?1, ?nil, ?1],
  @[?1, ?"email", ?"TEXT", ?1, ?nil, ?0],
  @[?2, ?"ssn", ?"INTEGER", ?0, ?nil, ?0],
  @[?3, ?"birthDate", ?"INTEGER", ?1, ?nil, ?0],
  @[?4, ?"lastLogin", ?"INTEGER", ?1, ?nil, ?0]] was @[@[0, 'id', 'INTEGER', 1, NULL, 1], @[1, 'email', 'TEXT', 1, NULL, 0], @[2, 'ssn', 'INTEGER', 0, NULL, 0], @[3, 'birthDate', 'INTEGER', 1, NULL, 0], @[4, 'lastLogin', 'INTEGER', 1, NULL, 0]]
    C:\projects\nim\pkgstemp\norm\tests\tsqlite.nim(89, 51): Check failed: dbConn.getAllRows(sql query % "books") ==
    @[@[?0, ?"id", ?"INTEGER", ?1, ?nil, ?1],
      @[?1, ?"title", ?"TEXT", ?1, ?nil, ?0],
      @[?2, ?"authorEmail", ?"TEXT", ?1, ?nil, ?0],
      @[?3, ?"publisherTitle", ?"TEXT", ?1, ?nil, ?0]]
    dbConn.getAllRows(sql query % "books") was @[@[0, 'id', 'INTEGER', 1, '0', 1], @[1, 'title', 'TEXT', 1, '''''', 0], @[2, 'authorEmail', 'TEXT', 1, '''''', 0], @[3, 'publisherTitle', 'TEXT', 1, '''''', 0]]
    @[@[?0, ?"id", ?"INTEGER", ?1, ?nil, ?1],
  @[?1, ?"title", ?"TEXT", ?1, ?nil, ?0],
  @[?2, ?"authorEmail", ?"TEXT", ?1, ?nil, ?0],
  @[?3, ?"publisherTitle", ?"TEXT", ?1, ?nil, ?0]] was @[@[0, 'id', 'INTEGER', 1, NULL, 1], @[1, 'title', 'TEXT', 1, NULL, 0], @[2, 'authorEmail', 'TEXT', 1, NULL, 0], @[3, 'publisherTitle', 'TEXT', 1, NULL, 0]]
    C:\projects\nim\pkgstemp\norm\tests\tsqlite.nim(95, 54): Check failed: dbConn.getAllRows(sql query % "editions") ==
    @[@[?0, ?"id", ?"INTEGER", ?1, ?nil, ?1],
      @[?1, ?"title", ?"TEXT", ?1, ?nil, ?0],
      @[?2, ?"bookId", ?"INTEGER", ?1, ?nil, ?0]]
    dbConn.getAllRows(sql query % "editions") was @[@[0, 'id', 'INTEGER', 1, '0', 1], @[1, 'title', 'TEXT', 1, '''''', 0], @[2, 'bookId', 'INTEGER', 1, NULL, 0]]
    @[@[?0, ?"id", ?"INTEGER", ?1, ?nil, ?1],
  @[?1, ?"title", ?"TEXT", ?1, ?nil, ?0],
  @[?2, ?"bookId", ?"INTEGER", ?1, ?nil, ?0]] was @[@[0, 'id', 'INTEGER', 1, NULL, 1], @[1, 'title', 'TEXT', 1, NULL, 0], @[2, 'bookId', 'INTEGER', 1, NULL, 0]]
  [FAILED] Create tables
    C:\projects\nim\pkgstemp\norm\tests\tsqlite.nim(246, 51): Check failed: dbConn.getAllRows(sql query % "users") ==
    @[@[?0, ?"id", ?"INTEGER", ?1, ?nil, ?1],
      @[?1, ?"email", ?"TEXT", ?1, ?nil, ?0],
      @[?2, ?"ssn", ?"INTEGER", ?0, ?nil, ?0],
      @[?3, ?"birthDate", ?"INTEGER", ?1, ?nil, ?0],
      @[?4, ?"lastLogin", ?"INTEGER", ?1, ?nil, ?0]]
    dbConn.getAllRows(sql query % "users") was @[@[0, 'id', 'INTEGER', 1, '0', 1], @[1, 'email', 'TEXT', 1, '''''', 0], @[2, 'ssn', 'INTEGER', 0, NULL, 0], @[3, 'birthDate', 'INTEGER', 1, NULL, 0], @[4, 'lastLogin', 'INTEGER', 1, '0', 0]]
    @[@[?0, ?"id", ?"INTEGER", ?1, ?nil, ?1],
  @[?1, ?"email", ?"TEXT", ?1, ?nil, ?0],
  @[?2, ?"ssn", ?"INTEGER", ?0, ?nil, ?0],
  @[?3, ?"birthDate", ?"INTEGER", ?1, ?nil, ?0],
  @[?4, ?"lastLogin", ?"INTEGER", ?1, ?nil, ?0]] was @[@[0, 'id', 'INTEGER', 1, NULL, 1], @[1, 'email', 'TEXT', 1, NULL, 0], @[2, 'ssn', 'INTEGER', 0, NULL, 0], @[3, 'birthDate', 'INTEGER', 1, NULL, 0], @[4, 'lastLogin', 'INTEGER', 1, NULL, 0]]
    C:\projects\nim\pkgstemp\norm\tests\tsqlite.nim(253, 51): Check failed: dbConn.getAllRows(sql query % "books") ==
    @[@[?0, ?"id", ?"INTEGER
```

**Comment by narimiran** [comment]
> The changelog entry cause the test failure? The failing test is surprisingly tsqlite.nim how? Is it a new flaky test? Should I disable it?

Can you resolve merge conflicts so we can then see if the failing test was some one time glitch, or if there is something else going on?

**Pull request merged**
