### PR TITLE
disable presto

### PR DESCRIPTION
**Pull request by ringabout**

### CODE REVIEW

**Comment by narimiran** [comment]
I've seen it failing also on the `version-2-0` branch (so, I'll backport this once merged), but I'm interested to know what's the reason for sudden fails. Looking at https://github.com/status-im/nim-presto, there were no new commits recently.
Any idea? Something external?

**Comment by ringabout** [comment]
I belive it is caused by some network issues(or something) on [nim-presto](https://github.com/status-im/nim-presto) tests

**Comment by narimiran** [comment]
> I belive it is caused by some network issues(or something) on [nim-presto](https://github.com/status-im/nim-presto) tests

Ok, I've created https://github.com/status-im/nim-presto/pull/81 to see if the fails are reproducible there.

**Comment by narimiran** [comment]
`2.0.x` and `devel` failing there too. (But `1.6.x` is not failing!!)

Looking at stuff in both those branches, merged/backported recently, https://github.com/nim-lang/Nim/pull/23892 looks suspicious, but that had green CIs before merging!?

**Comment by tersec** [comment]
> I've seen it failing also on the `version-2-0` branch (so, I'll backport this once merged), but I'm interested to know what's the reason for sudden fails. Looking at https://github.com/status-im/nim-presto, there were no new commits recently. Any idea? Something external?

https://github.com/nim-lang/Nim/issues/23973 combined with https://github.com/arnetheduck/nim-results/pull/46

**Pull request merged**
