### PR TITLE
float parsing: Add test for a fixed issue

### LINKED ISSUE #14407: backticks : Float-like part of a variable identifier is changed in [XDeclaredButNotUsed] Hint
A variable name like `` `v0.99.99` `` changes when it's reported in the XDeclaredButNotUsed hint. The last part .99, seems like, is treated like a float.

### Example

Run `nim c t.nim`.

```nim
let
  `v0.99` = "0.99"       # ok  Hint: 'v0.99' is declared but not used
  `v0.99.99` = "0.99.99" # ??  Hint: 'v0.99.98999999999999' is declared but not used
```

### Current Output

```
/home/kmodi/sandbox/nim/bug_reports/declared_but_not_used/t.nim(2, 3) Hint: 'v0.99' is declared but not used [XDeclaredButNotUsed]
/home/kmodi/sandbox/nim/bug_reports/declared_but_not_used/t.nim(3, 3) Hint: 'v0.99.98999999999999' is declared but not used [XDeclaredButNotUsed]
```

### Expected Output
```
/home/kmodi/sandbox/nim/bug_reports/declared_but_not_used/t.nim(2, 3) Hint: 'v0.99' is declared but not used [XDeclaredButNotUsed]
/home/kmodi/sandbox/nim/bug_reports/declared_but_not_used/t.nim(3, 3) Hint: 'v0.99.99' is declared but not used [XDeclaredButNotUsed]
```

### Additional Information

* I was working on my [`version` module][1] when I noticed the strange-looking hints.

```
$ nim -v
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-05-19
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: e909486e5cde5a4a77cd6f21b42fc9ab38ec2ae6
active boot switches: -d:release
```

[1]: https://github.com/kaushalmodi/version/blob/f9c0937b65a15eccfc33197e84a93e10662fb912/src/get_version.nim#L176-L190

### PR DESCRIPTION
**Pull request by kaushalmodi**
Fixes https://github.com/nim-lang/Nim/issues/14407 .

This issue was fixed by https://github.com/nim-lang/Nim/pull/18139.

This command passes on my machine:

```
# cd to cloned Nim repo
testament r tests/errmsgs/treportunused.nim   
```

### CODE REVIEW

**Comment by kaushalmodi** [comment]
@Araq I see that the order of the Hints got shuffled up when I added that let block at the end. Is that shuffling expected? For that reason, the diff of the discard block is bigger than I expected. I expected only line number changes in there. But instead, I also had to paste the exact order of Hints that I saw when compiling that test locally.

**Comment by kaushalmodi** [comment]
The order of the Hints messages is still an issue. The changes in this test passed on most machines, but failed on:

1. an Azure Linux run: https://dev.azure.com/nim-lang/Nim/_build/results?buildId=16979&view=logs&j=ba7bbfa4-f55c-5c34-6d52-1b6b4edd3f37&t=01b6eca1-ed82-5532-a6ed-8d9a0cd0188a&l=389

    ```
    -------- Expected -------
    treportunused.nim(28, 5) Hint: 's8' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(35, 3) Hint: 'v0.99' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(36, 3) Hint: 'v0.99.99' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(26, 7) Hint: 's6' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(25, 6) Hint: 's5' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(22, 10) Hint: 's2' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(23, 10) Hint: 's3' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(30, 6) Hint: 's10' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(21, 10) Hint: 's1' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(24, 6) Hint: 's4' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(27, 7) Hint: 's7' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(31, 6) Hint: 's11' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(29, 5) Hint: 's9' is declared but not used [XDeclaredButNotUsed]

    --------- Given  --------
    Hint: used config file '/home/vsts/work/1/s/config/nim.cfg' [Conf]
    Hint: used config file '/home/vsts/work/1/s/config/config.nims' [Conf]
    Hint: used config file '/home/vsts/work/1/s/tests/config.nims' [Conf]
    treportunused.nim(28, 5) Hint: 's8' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(36, 3) Hint: 'v0.99.99' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(26, 7) Hint: 's6' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(25, 6) Hint: 's5' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(22, 10) Hint: 's2' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(23, 10) Hint: 's3' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(30, 6) Hint: 's10' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(21, 10) Hint: 's1' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(24, 6) Hint: 's4' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(27, 7) Hint: 's7' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(31, 6) Hint: 's11' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(35, 3) Hint: 'v0.99' is declared but not used [XDeclaredButNotUsed]
    treportunused.nim(29, 5) Hint: 's9' is declared but not used [XDeclaredButNotUsed]
    ```

2. most likely an unrelated error on Azure MacOS: https://dev.azure.com/nim-lang/Nim/_build/results?buildId=16979&view=logs&j=30931762-47c4-53b3-6a83-316eb5a6b9d7&t=90890b9c-f12c-53eb-b238-5d782d0298c3&l=2982 .

**Comment by timotheecour** [comment]
> The order of the Hints messages is still an issue

please open a separate issue to track that (and cross-link there); it's fixable using perhaps similar approach as I did in https://github.com/nim-lang/Nim/pull/13701 for sorting sigmatch errors

in the meantime you can use a different file for the test case as a workaround

**Comment by kaushalmodi** [comment]
> in the meantime you can use a different file for the test case as a workaround

Ok, I'll do that later today. Thanks.

**Comment by timotheecour** [comment]
> Ok, I'll do that later today. Thanks.

or wait for https://github.com/nim-lang/Nim/pull/18336 to get merged, that way we don't have to add another file here

**Comment by kaushalmodi** [comment]
@timotheecour Looks like waiting for your PR merge is the only option 😃 

```
 tests/errmsgs/t14407.nim c

Failure: reMsgsDiffer
Expected:
t14407.nim(11, 3) Hint: 'v0.99' is declared but not used [XDeclaredButNotUsed]
t14407.nim(12, 3) Hint: 'v0.99.99' is declared but not used [XDeclaredButNotUsed]


Gotten:
Hint: used config file '/home/vsts/work/1/s/config/nim.cfg' [Conf]
Hint: used config file '/home/vsts/work/1/s/config/config.nims' [Conf]
Hint: used config file '/home/vsts/work/1/s/tests/config.nims' [Conf]
t14407.nim(12, 3) Hint: 'v0.99.99' is declared but not used [XDeclaredButNotUsed]
t14407.nim(11, 3) Hint: 'v0.99' is declared but not used [XDeclaredButNotUsed]
CC: stdlib_assertions.nim
CC: stdlib_digitsutils.nim
CC: stdlib_system.nim
CC: t14407.nim
Hint:  [Link]
Hint: gc: refc; opt: none (DEBUG BUILD, `-d:release` generates faster code)
32505 lines; 0.770s; 25.949MiB peakmem; proj: t14407; out: t14407 [SuccessX]
```

**Comment by timotheecour** [comment]
ping now that https://github.com/nim-lang/Nim/pull/18336 was merged

**Comment by kaushalmodi** [comment]
@timotheecour PTAL This PR now passes the CI.

**Pull request merged**
