### PR TITLE
Add a code of conduct to promote goodwill and respect

### PR DESCRIPTION
**Pull request by BigBoneDaddy**
A code of conduct helps promote goodwill and respect throughout the community

### CODE REVIEW

**Comment by dom96** [comment]
I think this might be more appropriate in the Wiki.

**Comment by BigBoneDaddy** [comment]
I think it is important to keep it with the code because it mean that everyone who get Nim source code get code of conduct too. The wiki is fleeting. Nobody look at it and nobody care about it. Some evil doer could even change code of conduct to say it is ok to be racism which is clearly not ok! Wiki is good for unimportant docs but I don't think wiki is good for critical docs.

**Comment by fowlmouth** [comment]
I am opposed to this. https://github.com/orange-lang/orange/pull/2. You are clearly doing this for attention. Any code of conduct should come from inside the community, not someone trying to buff their ego.

**Comment by fowlmouth** [comment]
Oh hey welcome to github I see that you joined yesterday. The trolling is super obvious now

**Comment by dom96** [comment]
I disagree. It should be in the wiki.

**Comment by ozra** [comment]
Style guide for coding is good with source, code of conduct is good in the wiki.

**Comment by BigBoneDaddy** [comment]
@fowlmouth Yes I joined yesterday I'm new to github. Theres nothing wrong with that. I think your comments are a good example of why we need a code of conduct. I come here to contribute and you attack me and call me names. Please show respect and kindness.

**Comment by BigBoneDaddy** [comment]
@dom69 @ozra It should be in the source code because it is as important as the source code but I have put it in wiki now like you said to.

**Comment by fowlmouth** [comment]
@BigBoneDaddy obvious trolling is obvious.
https://github.com/ark-lang/ark/issues/438
https://github.com/ark-lang/ark-docs/issues/3
https://github.com/ark-lang/ark/issues/442
https://github.com/ark-lang/ark/issues/440
https://github.com/ark-lang/ark/issues/439
https://github.com/ark-lang/ark/issues/437

**Comment by BigBoneDaddy** [comment]
@fowlmouth Ark is very broken language. It has no string functions! I opened issue because it is missing important functions.

**Comment by felixangell** [comment]
@fowlmouth Yep, ignore this jackass. Just report him.

**Comment by BigBoneDaddy** [comment]
@felixangell Can you please stop harassing me and following me around? Yes I pointed out a bug with your programming language. I don't know why that offended you. Please stop harassing me!

**Comment by dom96** [comment]
@fowlmouth Those links do not prove anything.

@felixangell Do not call people jackasses here.

@BigBoneDaddy I do not know whether you are a troll or not. You do seem to be posting on a lot of issues in this project. The comments you have made on other projects have been deleted, but I do not know what they were so I cannot use that as proof of anything. You are welcome to continue being a member of the Nim community, but I will keep a close eye on you.

I am going to lock this discussion now.

**Pull request closed without merging**
