### PR TITLE
Use truncation division in mod for floats

### PR DESCRIPTION
**Pull request by GULPF**
This might just be a pointless breaking change, but it annoys me that modulus for floats uses floor division, when `div` and `mod` for integers uses truncating division.

### CODE REVIEW

**Comment by krux02** [comment]
Yes this changes an unnecessary inconsistency. Here is an example how it is now.

```Nim
import math

echo -3 mod 2
echo -3.0 mod 2.0
```

output:
```
-1
1.0
```


But I am still agains this changes, I would prefer a lot if integers would behave like the float in this case and the result would be:

```
1
1.0
```

I only need floor divison modulo. Never needed the truncating divison. Most of the time I use modulo is for indices of arrays  ``arr[i mod arr.len]``. But this patters breaks for negative numbers. So I end up writing this ugly code  ``arr[(i mod arr.len + arr.len) mod arr.len]`` or I wrtie this: ``assert(arr.len-1 and arr.len == 0) #[ arr.len is power of two #] ; arr[i and (arr.len - 1)]``. I really wish I could reliably write ``arr[i mod arr.len]`` and it would work reliably for negative numbers.

**Comment by GULPF** [comment]
[Here's a good read on the different ways to implement `div` and `mod`](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/divmodnote-letter.pdf)

I don't really have an opinion on floor div vs trunc div, but I doubt changing the behavior of div and mod for integers would be accepted since it will break a lot of code.

**Comment by data-man** [comment]
C++ [std::fmod](http://en.cppreference.com/w/cpp/numeric/math/fmod)

> fmod(+5.1, +3.0) = 2.1
> fmod(-5.1, +3.0) = -2.1
> fmod(+5.1, -3.0) = 2.1
> fmod(-5.1, -3.0) = -2.1
> fmod(+0.0, 1.0) = 0
> fmod(-0.0, 1.0) = -0
> fmod(5.1, Inf) = 5.1
> fmod(+5.1, 0) = -nan

Nim's output:
```nim
import math

echo +5.1 mod +3.0
echo -5.1 mod +3.0
echo +5.1 mod -3.0
echo -5.1 mod -3.0
echo +0.0 mod 1.0
echo -0.0 mod  1.0
echo 5.1 mod Inf
echo +5.1 mod  0
```

> 2.1
> 0.9000000000000004
> -0.9000000000000004
> -2.1
> 0.0
> 0.0
> nan
> 5.1

**Comment by GULPF** [comment]
I changed the PR to simply use use `fmod` directly for C and `%` for JS, this is probably the most sane alternative.

**Comment by krux02** [comment]
and hese is what mod does in maxima, a computer algebra system:

```maxima
(%i8) mod(+5.1, +3.0);
(%o8)                          2.099999999999999
(%i9) mod(-5.1, +3.0);
(%o9)                         0.9000000000000004
(%i10) mod(+5.1, -3.0);
(%o10)                       - 0.9000000000000004
(%i11) mod(-5.1, -3.0);
(%o11)                        - 2.099999999999999
(%i12) mod(+0.0,+1.0);
(%o12)                                0.0
(%i13) mod(-0.0,+1.0);
(%o13)                               -0.0
(%i14) mod(5.1, inf);
                                             5.1
(%o14)                       5.1 - inf floor(---)
                                             inf
(%i15) mod(5.1, 0);
(%o15)                                5.1

```

**Comment by krux02** [comment]
I have changed my mind. I agree that this PR should be taken.

**Comment by Araq** [comment]
This needs a changelog entry.

**Comment by krux02** [comment]
I like how it is now. When the tests are fixed. I would approve it.

**Comment by GULPF** [comment]
Ready to merge

**Comment by data-man** [comment]
Changelog's entries for floorDiv/floorMod?

**Pull request merged**
