### PR TITLE
Revert "Revert adding generic `V: Ordinal` parameter to `succ`, `pred`, `inc`, `dec`"

### PR DESCRIPTION
**Pull request by ringabout**
Reverts nim-lang/Nim#22328

alternative to https://github.com/nim-lang/checksums/pull/6

### CODE REVIEW

**Comment by konsumlamm** [comment]
Is this really necessary? What's the problem with https://github.com/nim-lang/checksums/pull/6?

This "feature" was introduced without any RFC, documentation, changelog entry, tests or review. I still think it's a bad idea to allow adding any two `Ordinal`s. Wouldn't it be enough to add an overload for `uint64` specifically (or `SomeInteger`)? Then at least we wouldn't be able to add *arbitrary `Ordinal`s. It also breaks the JS backend, which currently relies on the second argument always being an `int`.

**Comment by ringabout** [comment]
> Wouldn't it be enough to add an overload for uint64 specifically (or SomeInteger)? 

Perhaps, I will test that.

**Comment by ringabout** [comment]
Doesn't `+=` also support some integers as increments? Is that proc broken for JS as well?

**Comment by ringabout** [comment]
Succeeded by **https://github.com/nim-lang/Nim/pull/22470**

**Comment by konsumlamm** [comment]
> Doesn't `+=` also support some integers as increments? Is that proc broken for JS as well?

No, `+=` only accepts arguments with the same type.

**Pull request closed without merging**
