### PR TITLE
Add another JSON example

### PR DESCRIPTION
**Pull request by FedericoCeratto**
JSON generation can be a bit tricky, another example might help

### CODE REVIEW

**Comment by Xe** [comment]
What does this example show exactly?

**Comment by oderwat** [comment]
I guess it shows that you can add properties to already existing json objects, which may indeed not be obvious and is a very nice feature.

**Comment by FedericoCeratto** [comment]
I had to fiddle around a bit to find a way to create that output. Adding a property is a little workaround to create nested JSON. Users might instead try to marshal nested Tables with no success.

**Comment by dom96** [comment]
Thank you. But could you separate these examples and put them under their own headings? (similar to the way its done in the ``db_*`` [modules](https://github.com/nim-lang/Nim/blob/devel/lib/impure/db_mysql.nim#L27))

**Pull request merged**
