### PR TITLE
Revert "Fix parseUri to sanitize urls containing ASCII newline or tab"

### PR DESCRIPTION
**Pull request by Araq**
Reverts nim-lang/Nim#17967

### CODE REVIEW

**Comment by Araq** [comment]
Reason: `parseUri` previously raised no exception.

**Comment by dom96** [comment]
I don't think we should revert this. It's unlikely newlines in URLs would have been useful to any program, so this is unlikely to break existing code. The only concern I see is with `{.raises.}` breakage, but that's then a feature :)

**Comment by Araq** [comment]
It's a breaking change, esp because the new default is `strict = true`. This can easily break somebody's server software. Previously for newlines in URLs: garbage in, garbage out. New behaviour: Server rejects the request and maybe even crashes.

**Comment by planetis-m** [comment]
This might also have an effect on httpclient, see https://github.com/nim-lang/Nim/pull/15919/files#r532210659

**Comment by beshrkayali** [comment]
@Araq @dom96 

Although it's unlikely that there's code out there that parses urls with newlines or tabs and doesn't break, I suppose it's a possibility. What do you think about defaulting `strict = false` for now and plan for a switch later? An alternative is to add a `safeParseUri` that would raise instead of silent sanitation?

**Comment by Araq** [comment]
> An alternative is to add a safeParseUri that would raise instead of silent sanitation?

That's what I prefer. I would name it `parseStrictUri` or similar, "safe" can also mean "cannot raise".

**Comment by Araq** [comment]
But more importantly, what is the threat model here? What if the string contains binary zero? Some databases cannot handle that, what's so special about new lines and tabs, what about the ASCII unit separator?

**Comment by timotheecour** [comment]
> That's what I prefer. I would name it parseStrictUri or similar, "safe" can also mean "cannot raise".

having both parseStrictUri and parseUri isn't good, see https://github.com/nim-lang/RFCs/issues/376

note that reverting this PR goes against the spec: https://url.spec.whatwg.org/#concept-basic-url-parser

I'd be in favor of this:
```nim
const parseUriDefault = when defined(nimLegacyParseUriDefault): false else: true
func parseUri*(uri: string, result: var Uri, strict = parseUriDefault)
```

or, as 2nd best option, adding `proc validateUri(uri: string): bool`

> This can easily break somebody's server software.
> Server rejects the request and maybe even crashes.

reliable server code should be written with assumption that server loop can raise.

**Comment by beshrkayali** [comment]
I think possible attacks associated with keeping newlines/tabs in a url include [HTTP response splitting](https://owasp.org/www-community/attacks/HTTP_Response_Splitting) and [log injection](https://owasp.org/www-community/attacks/Log_Injection), probably some more, it'd take some crafting for sure, but now that more people are aware that some standard libs are susceptible to it, I'm guessing there will be some attempts. It's also to be compliant with the URL spec. There could be some other non-compliances that need to be addressed but I haven't run additional tests yet, I'm planning on writing a little nim program to go through [this list](https://github.com/web-platform-tests/wpt/blob/master/url/resources/urltestdata.json) to see what breaks.

Regarding breaking/non-breaking discussion, if there are programs out there that do indeed parse urls that include newlines/tabs and don't complain about it, I'd _assume_ they'd want their program to break, or at least sanitize input. If adding a new function `parseStrictUri` goes against the language spec (the idea of having one func with optional args instead of many is reasonable imo, but then how do you deal with potential need to change default argument values if needed?), would it work for now to just default strict to `false` to avoid including a breaking change. Could be flipped in a future release if raising is deemed more appropriate as a default.

**Comment by beshrkayali** [comment]
(I'm not sure if this should go here or on https://github.com/nim-lang/RFCs/issues/376, but I'll add here to avoid littering.)

If the goal is to be compliant with URL Spec, I think it's ok to never raise basically and just sanitize. I agree that changing defaults or removing functions in a patch or a minor release is not perfectly reasonable, but probably on limited circumstance it will be required. 

On the url parsing issue, I can see that even going with a silent sanitize option could potentially break some programs out there if they rely on the fact that Nim doesn't do it somehow. The same happened in Python 3.9.5, which didn't raise and only silently sanitized, and still broke some libraries (django and boto) because of assumptions made on the part of these libraries. 

- https://github.com/boto/botocore/issues/2377
- https://code.djangoproject.com/ticket/32713

**Comment by Araq** [comment]
> It's also to be compliant with the URL spec. There could be some other non-compliances that need to be addressed but I haven't run additional tests yet, I'm planning on writing a little nim program to go through this list to see what breaks.

Can't argue with the spec, but then it should always ignore these characters during parsing and not raise an exception. And then it's a real bugfix, the code then follows the spec more closely.

**Comment by beshrkayali** [comment]
> but then it should always ignore these characters during parsing and not raise an exception

Do you think it makes sense to keep the strict argument and default it to `false` for now then? This way it won't raise unless user explicitly wants to handle it themselves, which could be useful if a user wants to block clients providing rouge urls multiple times for example.

**Comment by Araq** [comment]
Switches which change the `.raises` behavior at runtime are not trackable by Nim's effect system so that's a bad solution. If the code previously didn't raise, don't make it suddenly raise, there are people out there who actually use the effect tracking. Ideally the stdlib should enforce this to become explicitly visible via `.push raises: []` in every stdlib module, but that's a different topic.

**Comment by timotheecour** [comment]
> Switches which change the .raises behavior at runtime are not trackable by Nim's effect system so that's a bad solution

as i mentioned in https://github.com/nim-lang/RFCs/issues/376, using a static param solves this:
```nim
func parseUri*(uri: string, result: var Uri, strict: static bool = parseUriDefault)
```

> there are people out there who actually use the effect tracking.
> Ideally the stdlib should enforce this to become explicitly visible via .push raises: [] in every stdlib module, but that's a different topic.

that's very controversial, it prevents evolving stdlib and bugfixes in many cases, say when original API didn't properly handle a special case that should've been handled by raising an exception; silencing errors just because some code relies on the fact the error was silenced in the original version is a worse option, code shouldn't rely on bugs. Migration strategies are the way to go in such cases.

**Pull request merged**
