### PR TITLE
Add icon for Nim

### PR DESCRIPTION
**Pull request by serjan-nasredin**

### CODE REVIEW

**Comment by juancarlospaco** [comment]
That setup icon is really cool, I hope it gets merged soon.

**Comment by Araq** [comment]
These are awesome, thanks!

**Comment by dom96** [comment]
I know these reuse the Nim logo so they are already likely subject to the Nim team's ownership. But just in case...

@snxx-lppxx please confirm that you are giving the Nim team (specifically @Araq) the copyright for these icons.

**Comment by serjan-nasredin** [comment]
@dom96,

I transfer all rights to use the icons to the Nim team.
I hand over the change, delete, add rights to @Araq and his Nim community.
<br/>
And also I agree to transfer the rights to use this repository to obtain the necessary permissions for icons: <https://github.com/nim-libs/nsis/tree/master/assets/img>.

I recommend using this bot for user authorization, and for the transfer of rights into the hands of the author: <https://github.com/marketplace/cla-bot-cla-automation>.

**Pull request merged**
