### PR TITLE
All modules should be importable without the std/ prefix.

### PR DESCRIPTION
**Pull request by dom96**
Refs #7938

### CODE REVIEW

**Comment by dom96** [comment]
So @Araq tells me that these modules are in an enforced ``std/`` directory because they may clash with existing Nimble packages. I can appreciate that but nonetheless I wish we could get rid of this inconsistency. As far as I can see we can do a couple of things:

* Break code and enforce the ``std/`` namespace on all modules.
* Live with the consequences of possibly breaking code when a new module is added.

I'm really curious how Python handles this issue and will look into it. Hopefully what I've written makes sense.

**Comment by dom96** [comment]
Oh here is the relevant issue as well #7939

**Comment by dom96** [comment]
https://docs.python.org/3/whatsnew/2.5.html#pep-328-absolute-and-relative-imports

> Python users soon learned not to duplicate the names of standard library modules in the names of their packages’ submodules, but you can’t protect against having your submodule’s name being used for a new module added in a future version of Python.

So it seems Python didn't handle this possibility and has been working fine for years.

I think we should go back to putting all modules into `lib/pure`. In the (unlikely) event that a new stdlib module clashes with an existing package, users can fix their code by prefixing their imports with ``pkg/``.

**Comment by nc-x** [comment]
> So it seems Python didn't handle this possibility and has been working fine for years.
  
Yeah, but nearly all other languages do.
  
Instead of hoping that people don't do name clashes, it is better IMO to have a clear `std/` vs `pkg/` distinction. What harm does typing 4 extra characters do?

**Comment by CodeDoes** [comment]
As long as its optional its good. I'd much rather prefer just being able to
refer to a specific package with no ambiguity if I like.

**Comment by dom96** [comment]
> What harm does typing 4 extra characters do?

It breaks all code. That's the harm.

**Comment by nc-x** [comment]
> It breaks all code. That's the harm.

And the fix takes only 1 minute and is facilitated by the compiler. You don't even have to worry about whether the behaviour of your code will change or not.
  
Consider this to the other breaking changes that are happening or going to happen.

**Comment by andreaferretti** [comment]
> You don't even have to worry about whether the behaviour of your code will change or not.

Of course you have to worry, because not everything you import comes from the standard lib.

But the **major** problem is that there are libraries out there perfectly functional and working as intended that will not be updated because they are not maintained. Granted, this is a problem with every breaking change, but this particular change is especially egregious in this regard, in that it breaks essentially **everything** that has been written so far

**Comment by andreaferretti** [comment]
(actually, I think that the right solution would be to have namespaces for modules, so that for instance

```nim
import random
import somelib.random
```

would work without clashes)

**Comment by nc-x** [comment]
> there are libraries out there perfectly functional and working as intended that will not be updated because they are not maintained.
  
Nothing is perfect. If they are not being maintained, then I would say that that is a bigger issue as you won't even get bug fixes, forget being compatibility with latest Nim. 
  
Also, you should not expect a moving language to not change. 
  
Looking at the changelog, this seems a pretty minor change. I don't see any reason why so many people oppose this change. Many other languages (for eg. Rust) were pretty much in flux during pre-1.0 and every release used to break everything. Nim has so far taken a very conservative approach to breakages. But it should not shy away for breaking things where experience dictates that that breakage would prove to be useful in the feature. Considering that nearly every language has such a feature, and that this change is very minor and won't make using Nim any more difficult than it is now, also considering that `std/` vs `pkg/` distinction is much easier to grasp than Rust's modules or Java's `org.crap.*`, I personally see no reason to discuss this any more.

The decision making power do not lie with me, but if anyone asks me - my vote goes for having a **compulsory** 'std/` vs 'pkg/` distinction.

**Comment by andreaferretti** [comment]
@nc-x Luckily, that is just your vote :-)

**Comment by Araq** [comment]
There is no reason whatsoever we can't have a long deprecation period for ``import strutils`` and the like, we can even decide the old stdlib modules should be seen as "keyword-like" and do not have to deprecate it at all (!) but all the new stuff ends up in ``std``. 

And if you want to go into zealot-mode wrt "consistency" you can already do ``import std / strutils`` and will continue to be able to do so. There simply is no issue here to resolve once you get over your fanatisms.

**Comment by CodeDoes** [comment]
std module should be protected from being overwritten

**Comment by Araq** [comment]
The ``std`` dir is here to stay. Closing.

**Pull request closed without merging**
