### PR TITLE
remove jstin from important packages

### PR DESCRIPTION
**Pull request by ringabout**
Ref https://github.com/nim-lang/Nim/pull/17759
Ref https://github.com/nim-lang/Nim/pull/17711

https://github.com/LemonBoy/jstin/blob/master/src/jstin.nim is already archived and cannot pass CI anymore.

### CODE REVIEW

**Comment by ringabout** [comment]
How about putting the source code and tests to Nim repo? I remember the code caught a regression ever.

**Comment by Araq** [comment]
> How about putting the source code and tests to Nim repo? I remember the code caught a regression ever.

If you feel like it.

**Comment by timotheecour** [comment]
* @LemonBoy I don't see any note or issue report mentioning the reason for archival, please comment if you can

> How about putting the source code and tests to Nim repo? I remember the code caught a regression ever.

let's fork it instead, eg under nim-lang/nim, and change nimble url to point to the new fork

**Comment by ringabout** [comment]
please do it, i don't have the right.

**Comment by timotheecour** [comment]
done => https://github.com/nim-lang/jstin

> i don't have the right.

@Araq how about giving @xflywind those rights? there were a few other instances like that

TODO:
- [x] make a PR against nimble to update the ref
- [x] change ref in important_packages
- [x] add commit to fix the jstin CI error re `default` (https://github.com/nim-lang/jstin/pull/1)

**Pull request merged**
