### PR TITLE
Fix usage of parameters types in templates #6756

### PR DESCRIPTION
**Pull request by vegansk**

### CODE REVIEW

**Comment by dom96** [comment]
Can you add a test case for this?

**Comment by Araq** [comment]
Shouldn't T be have been gensym'ed here instead of weaking the doAssert condition?

**Comment by vegansk** [comment]
@Araq , the compiler fails on type `A`, not `T`, see the debug output from issue #6756:
```
A_105025: ["sfUsed"], [], ["issue.nim", 5, 15], skType
```

**Comment by Araq** [comment]
My remark remains, why is ``A`` not gensym'ed in the first place?

**Comment by vegansk** [comment]
Sorry, have no time to investigate it for now :-(

**Pull request merged**
