### PR TITLE
fix https://github.com/nim-lang/RFCs/issues/311 remove unary slice

### LINKED ISSUE #311: deprecate unary slice `b[..2]` (error prone and not useful)
## proposal
deprecate unary slice
https://nim-lang.github.io/Nim/system.html#..%2CsinkT

### example 1
it seems error prone eg:
```nim
when true:
  var b: array[-3..3, float]
  echo b[.. 2] == b[0 .. 2]
  echo b[b.low .. 2] == b[0 .. 2]
```
prints:
true
false

it'd be useful if `b[.. 2]` would be syntax sugar for `b[b.low .. 2]` (analog to `b[3..^1`) but it seems that all it does is being equal to `default(int)`, ie `0`.

I don't see the point of avoiding to type `0`.

### example 2
it also doesn't compose well with rest of nim, eg:
```nim
when true:
  var b: array[..3, float] # Error: illformed AST: ..3
```
(analog to https://github.com/nim-lang/Nim/issues/6215)

### PR DESCRIPTION
**Pull request by timotheecour**
fix https://github.com/nim-lang/RFCs/issues/311

let's see what breaks before deprecating...

## note
only 2 packages failed, and corresponding PR's have been merged
- [x] glob => https://github.com/citycide/glob/pull/56
- [x] norm => https://github.com/moigagoo/norm/pull/112 (merged)

### CODE REVIEW

**Comment by juancarlospaco** [comment]
This also covers things like ?
```nim
for i in  ..9: echo i
```

**Comment by timotheecour** [comment]
> This also covers things like ?

yes

**Review by Clyybber — APPROVED** [review]

**Review by ringabout — APPROVED** [review]

**Comment by Araq** [comment]
Er... Removal without a deprecation period?!

**Comment by timotheecour** [comment]
=> https://github.com/nim-lang/Nim/pull/17794

**Pull request merged**
