### PR TITLE
[WIP] Raise/catch cpp imported exceptions

### PR DESCRIPTION
**Pull request by cooldome**
I decided to try implementing https://github.com/nim-lang/Nim/issues/3571. Basically it is throwing and catching native cpp exceptions.

Making `raise` to use throw directly for imported types was not difficult, but for `except` I have a problem. 
I need exception variable to be present in the `except` branch to be able to do something with it and it should be of the right type. Language design decision is required,  I see the following possibilities:

- Extend `except` branch syntax to have optional exception variable name (old version with just a type will still be supported):
Something like
```
except ValueError(ex):
except ValueError ex:
except ValueError, ex:
except (ex: ValueError):
```
- Magical `getCurrentException()`, but what would be its return type given that in cpp you can throw anything.
 
- Simply have a variable with fixed name appearing magically in except branch
- Other??
--

### CODE REVIEW

**Comment by cooldome** [comment]
Hi Araq, I am asking for you input to decide how the feature should work

**Comment by GULPF** [comment]
This already works:
```nim
try:
    raise newException(Exception, "Hello World")
except Exception as exc:
    echo(exc.msg)
```
Doesn't look like it's documented anywhere though

**Comment by cooldome** [comment]
`except Exception as exc:` looks good thanks GULPF , will proceed using this syntax

**Comment by Yardanico** [comment]
Strange that it's not documented

**Comment by cooldome** [comment]
Tried `except Exception as exc`  and found couple of ways to crash it. I guess I need to fix it first.

**Comment by cooldome** [comment]
I will soon submit a new version of this PR with support pf cpp imported exceptions

**Pull request closed without merging**
