### PR TITLE
Add getCompileOptionString() to get Nim config at compile time

### PR DESCRIPTION
**Pull request by genotrance**
Would like to get more info such as nimcache, nimblePaths and other data at compile time.

Unclear how to return a new seq[string] for mCompileOptionSeq in semfold.nim.

### CODE REVIEW

**Comment by timotheecour** [comment]
* instead of `getCompileOptionSeq`, `getCompileOptionString` (+ other, eg `getCompileOptionInt`), why not simply have:
`proc getCompileOption(conf: ConfigRef; info: TLineInfo): JsonNode` and reuse the code in `of "dump"` in compiler/main.nim ; would make it more DRY, and easier for tooling

**Comment by genotrance** [comment]
Good idea but how do you return a JSON object in semfold.nim?

https://github.com/nim-lang/Nim/blob/devel/compiler/semfold.nim#L363

Looks like only basic types are supported.

**Comment by timotheecour** [comment]
How about returning it as serialized jsonnode, ie, a string? Performance will not be a bottleneck here

**Comment by genotrance** [comment]
I have renamed to `compileSetting()` and `compileMultiSetting()`.

The former works but the latter gives me `SIGSEGV: Illegal storage access. (Attempt to read from nil?)`. Appreciate any guidance - not sure if I am returning the seq[string] [correctly](https://github.com/nim-lang/Nim/pull/12950/files#diff-404830e1d7d752545f3e98392dc56c0cR370).

> Araq: and be prepared for a little fight because I don't want Nim code to depend on the --path or --nimcache

Reason for this feature is to simply allow calling a child nim process with the correct command line flags at compile time. If user is not using a nim.cfg, there's no way to know if a different setting is in effect. See [issue](https://github.com/nimterop/nimterop/issues/153).

**Comment by Araq** [comment]
Can this go into a new stdlib module instead? I know it's rather arbitrary but system.nim is still growing like cancer.

**Comment by genotrance** [comment]
I'm good with that - open to suggestions. Do we want this in `lib\system\xyz.nim` or in a separate stdlib module?

Further, are there any other procs that can be moved from system.nim into this new module? We can deprecate it from system.nim and remove eventually.

**Comment by Araq** [comment]
Create ``std / compilersettings``.

**Comment by timotheecour** [comment]
@genotrance the diff (39 files) shows unrelated changes; can you simply rebase against latest devel?

**Pull request closed without merging**
