### PR TITLE
Updated 'nim for embedded systems' section to use --os:any and --gc:arc

### PR DESCRIPTION
**Pull request by zevv**

### CODE REVIEW

**Comment by timotheecour** [comment]
@zevv good changes but why were certain parts of the docs removed? They still seem useful / relevant even in light of --gc:arc/--gc:any; eg:
* the paragraph describing -d:StandaloneHeapSize=<size> still seems relevant ; perhaps also the mention of panicoverride.nim
* ditto for the example describing 16bit micro controllers

**Comment by zevv** [comment]
Araq suggested for me to "rewrite the docs", maybe I overdid that a bit.

- `--os:standalone` is still supported, but no longer the preferred method for embedded systems.
- `panicoverride` and standalone heap not relevant when using `--os:any`  /  `-d:useMalloc`

As far as I know there is nothing special about running on 16 bit systems, is there anything specific happening with `-os:standalone` that I missed to help with this?

**Comment by dom96** [comment]
For something like an ESP8266 or Arduino it doesn't seem like ``--gc:any`` is the way to go, can we get back that section about `--os:standalone`?

Some relevant discussion: https://irclogs.nim-lang.org/18-10-2020.html#17:13:34

Edit: the compilation errors I'm seeing for an ESP8266: https://gist.github.com/dom96/7a3b3fa98f7d5c3009bbeb6d4988ce1b

**Comment by zevv** [comment]
`-d:nimEmulateOverflowChecks` ?

**Comment by dom96** [comment]
yeah, Yardanico gave me that hint. It helped. But we should probably document it in this doc.

**Comment by dom96** [comment]
Also would be nice to fix https://github.com/nim-lang/Nim/issues/15627

**Pull request merged**
