### PR TITLE
Prevent false variable injections in `quote`

### PR DESCRIPTION
**Pull request by LemonBoy**
I was investigating the ICE reported by @copygirl [here](https://gist.github.com/copygirl/811c025807053db7fa2a78c68f895db7) and found that the root problem is that `sevColor` leaks into the quote'd AST (along with `sevStr` and `groupStr`).

The solution is IMO the best one here: the quoted piece of code is evaluated in a detached scope in order to avoid any kind of cross-contamination.

Let's see if the CI likes it, travis spin that disk!

### CODE REVIEW

**Comment by LemonBoy** [comment]
The tests are red because the code in `json` is wrong.
The presence of the unquoted `verifyJsonKind` means the symbol will be kept as-is till the macro callsite but on the other hand `verifyJsonKind` is not an exported symbol, that's why the tests fail.

We may work around this problem by adding a switch for "dirty" quotes or adjust the json library and call it a day.

**Comment by zah** [comment]
This seems a little bit hackish, but if it works ... oh, well. The good news is that it will probably also fix some old issues such as https://github.com/nim-lang/Nim/issues/7323

**Comment by LemonBoy** [comment]
> hackish

You mean the implementation (I can sprinkle some syntactic sugar over the scope replacement) or the idea (I believe `quote` should preserve the unquoted parts a-la scheme's quasiquote)

> The good news is that it will probably also fix some old issues such as #7323

It does! :) I'll add a test

**Comment by zah** [comment]
The idea. In the end of the day, `quote` should probably have a spec regarding how it handles calls to private symbols in the local module (does it perform `bind` by default like a template, or does it return raw AST). This implementation will always return raw AST, but you can work around this by using `bindSym` outside of the quote block and then interpolating the symbol inside. Other policies are possible too, but the code will have to be different.

**Comment by LemonBoy** [comment]
Returning the raw AST makes it more practical for writing complex macros (or when you don't need the full power of the AST-based building). The escape hatch is there, if the user needs (as we do in `json`, the `bindSym` trick is cleaner than my half-assed attempt at fixing it) a local symbol they may always use `bindSym` where the backticks aren't enough.

**Comment by dom96** [comment]
I also think a spec would really help here. Wouldn't it be handy to allow symbol binding using some other operators?

For example:

```
quote do:
  @verifyJsonKind(`jsonNode`, true)
```

We should consult such mechanisms in other languages with macros and come up with a good spec. We need to think about the big picture here, not just continue fixing/working around specific issues...

**Pull request closed without merging**
