### PR TITLE
build nimble with ORC

### LINKED ISSUE #20099: `nimble test` is broken with ORC
```
git clone https://github.com/treeform/netty
cd netty
nim c -r --mm:orc ../nimble.nim test
```

### PR DESCRIPTION
**Pull request by ringabout**
fixes https://github.com/nim-lang/Nim/issues/20099

### CODE REVIEW

**Comment by Araq** [comment]
CI failures seem related.

**Comment by ringabout** [comment]
Yeah, commented at https://github.com/nim-lang/Nim/issues/20099

**Comment by bung87** [comment]
since the global related line is changed to `var pkgList {.global.}: seq[PackageInfo]` https://github.com/nim-lang/nimble/blame/412af022a44157dd17118432fba825da9f204125/src/nimble.nim#L96, this become another problem.

**Comment by ringabout** [comment]
ref https://github.com/nim-lang/nimble/pull/1074; nimble tests have passed in ORC.

**Comment by ringabout** [comment]
Will open a new one with the latest nimble

**Pull request closed without merging**
