### PR TITLE
equality check on NimSym has now support in the VM

### PR DESCRIPTION
**Pull request by krux02**
fixes https://github.com/nim-lang/Nim/issues/5551

### CODE REVIEW

**Comment by krux02** [comment]
interesting to see that appveyor things this pull request in non-mergeable.

**Comment by Araq** [comment]
This can more easily implemented by mapping it to the VM's node comparison capabilities.

**Comment by krux02** [comment]
Well that's a good idea, but since this implementation is already done, tested and pretty straight forward, I disagree that "mapping it the the VM's node comparison capabilities" is easier implemented.

**Comment by Araq** [comment]
Ok, well but the VM is really bloated already with all these super specialized opcodes. Less code is better code.

**Comment by krux02** [comment]
Well the problem is, I don't know about the node comparison capabilites. So I guess you should implement it, because I don't know what you want.

**Comment by dom96** [comment]
Fair request. Thank you for your PR @krux02 :)

Maybe Araq could give some more pointers, somebody else might pick this up.

**Comment by Araq** [comment]
Reworked this PR and merged it.

**Pull request closed without merging**
