### PR TITLE
Renamed inplace versions of map and mapIt to apply and applyIt, inlin…

### PR DESCRIPTION
**Pull request by petermora**
…ed map, preallocate in mapIt

See http://forum.nim-lang.org/t/1665 for details.

### CODE REVIEW

**Comment by petermora** [comment]
This is a first of several pull requests. I'm very careful because the sequtils are well-known, and push only those changes which were widely accepted on the forum. Please indicate if some of these changes are not wanted. I would be happy to have this PR in the next release, so the inplace ``mapIt`` could show a deprecated warning. This is the first step to remove the type parameter from ``mapIt``.

**Comment by Araq** [comment]
1. I do not like new things in system.nim and even ``map`` should be moved to sequtils for consistency.
2. I'm fine with breaking sequtils now that the new version will be 0.12.0 and not 0.11.4.

**Comment by petermora** [comment]
I'll modify the PR based on your comments. Thanks for reading it. Peter

**Comment by petermora** [comment]
@Araq Some people here http://forum.nim-lang.org/t/1333 suggested that many functions should be part of system.nim (see point A11). I'm preparing a new PR with ``map`` moved to *sequtils.nim*. Just a heads-up: prepare for the fight :)

**Comment by petermora** [comment]
Closing pull request. The new pull request based on Araq's comments is at: https://github.com/nim-lang/Nim/pull/3423

**Pull request closed without merging**
