### PR TITLE
improve C/C++ debug output readability (1/N)

### PR DESCRIPTION
**Pull request by heterodoxic**
The purpose of this PR is to make some shallow adjustments to the way the C/C++ code is generated in order to ease inspection - especially with the `--debugger:native` switch present.
This PR aims to achieve the following:

- remove redundant #line directives
- simplify some #line directives (when not changing the file)
- fix some formatting issues (new lines, indentations etc.)

I spread this effort out to several baby steps, as it is a WIP (still need to figure out some improvements), and I would like to see first if no unwelcome side effects occur.

As one side benefit, this might also reduce debug build times a tiny bit, at least for larger Nim projects, since there is both a bit less runtime string formatting applied and less code to be output.

### CODE REVIEW

**Comment by heterodoxic** [comment]
This seems to improve the output a bit for now regarding output formatting and less `#line`/`nimln_` noise.
I have also taken the liberty of replacing several `$n`s with mere `\n`s where I assumed it would simplify the process of formatting ropes. In the end, $n will get transformed to \n in most cases anyway, I thought. Is this approach acceptable or am I missing anything crucial here?

**Comment by Araq** [comment]
There is a difference between `$n` and `$N` which `\n` cannot capture but I never cared about this distinction.

**Comment by planetis-m** [comment]
Hey, I think this PR broke the source code displayed with objdump on Linux. To test just run `objdump --no-show-raw-insn -drwlS -M intel myexe`

**Comment by heterodoxic** [comment]
Sorry about that! :frowning_face: I will have a look at this later today, re-evaluate my changes rigorously, also with objdump.
Thanks for reporting this!

**Comment by heterodoxic** [comment]
Trying to fix this here: https://github.com/nim-lang/Nim/pull/21764

**Pull request merged**
