### PR TITLE
add `std/rtti` and `getDynamicTypeInfo`

### LINKED ISSUE #573: rtti: getDynamicTypeInfo
refs:
> Hi! Noob question: having a ref to a "base" type, (how) can I print the name of the "runtime" type it points to?

(question was asked in gitter)

### PR DESCRIPTION
**Pull request by timotheecour**
* pretty much all languages that support type hierarchies have this feature, eg:
  * C++ `typeid` returning a `type_info` refs https://en.cppreference.com/w/cpp/language/typeid
  * D: `typeid` returning a `TypeInfo` refs https://dlang.org/spec/expression.html#typeid_expressions
  * C#: `GetType` refs https://docs.microsoft.com/en-us/dotnet/api/system.object.gettype?view=net-5.0
  * swift: `type(of:)` refs https://developer.apple.com/documentation/swift/2885064-type
  * java: `getClass` https://www.tutorialspoint.com/java/lang/object_getclass.htm
* works with regular gc (gc:refc) or `nimV2` (eg gc:arc|orc)
* fixes https://github.com/timotheecour/Nim/issues/573

## use cases
* user defined better error messages
* debugging
* writing gdb/lldb plugins in nim and exploring runtime type
* also asked in nim chat: [in the irc log of the conversation](https://irclogs.nim-lang.org/06-02-2021.html#22:10:39) (see also [further down](https://irclogs.nim-lang.org/06-02-2021.html#22:13:30)).

## notes
* `std/rtti` is a new module and hidden behind `-d:nimExperimentalTypeInfoCore` so this module can more freely evolve until it stabilizes, while at same time allowing people to try it as opt-in, refs https://github.com/timotheecour/Nim/issues/575
* I intentionally didn't add that API inside `typeinfo` which is about the `Any` type, whereas `getDynamicTypeInfo` is about runtime type information (in particular for polymorphic types, but also useful for non polymorphic ones), but both can be combined
* the diff in sytem.nim is to avoid `Error: system module needs: programResult` for `tests/dll/nimhcr_integration.nim`
* turned `hti` include module into a private import module `std/private/hti` to avoid it being included more than once (and because imports are cleaner in general)

## future work
- [ ] move definition of `TNimTypeV2` to hti.nim now that hti is a proper import module, so that it can be deduplicated from system.nim and std/rtti (alternatively, I could do this in this PR)
- [ ] see whether `lib/system/cyclebreaker.nim` can reuse this proc instead of it defining its own `proc getDynamicTypeInfo[T](x: T): PNimTypeV2 {.magic: "GetTypeInfoV2", noSideEffect, locks: 0.}`
- [ ] maybe also expose a common API in std/rtti that would work with both gc:refc and gc:arc, eg via getters `getSize`, `gteAlign`, `getName` etc

### CODE REVIEW

**Comment by Araq** [comment]
This should be opt-in, the type names might not always be available (I can think of v2 implementations that use integers and modulo operations for the ``of`` operator). Also, the type names are generally of little use -- you cannot construct objects via the type name and the runtime reflection capabilities of Nim are weak.

**Comment by Varriount** [comment]
Is there any plan for the design of this module? I'm assuming users are going to want more functionality than just the single function retrieving and comparing type information objects for equality.

**Comment by Araq** [comment]
This needs an RFC.

**Comment by Araq** [comment]
As I said, this needs an RFC first.

**Pull request closed without merging**
