### PR TITLE
Fix links to manual

### PR DESCRIPTION
**Pull request by konqoro**
Not tested

### CODE REVIEW

**Comment by Araq** [comment]
Meh, IMO the hierarchy is not important enough.

**Comment by dom96** [comment]
I think it's a useful link. Surely won't hurt us to merge this.

**Comment by konqoro** [comment]
Fyi I didnt't add the links, they were there and broken...

**Comment by Araq** [comment]
It does hurt. It needs maintainance should the website's documenation structure change.

**Comment by Araq** [comment]
> Fyi I didnt't add the links, they were there and broken...

Oh alright then.

**Pull request merged**
