### PR TITLE
#12141 Define SDL lib name for OpenBSD and FreeBSD

### LINKED ISSUE #12141: Nim In Action test failures on OpenBSD
Some of the `Nim In Action` tests fail on OpenBSD.

- The `SDL` tests only specify `libName` for Linux, Mac and Windows: https://github.com/nim-lang/Nim/blob/devel/tests/niminaction/Chapter8/sdl/sdl.nim#L1
- The `SFML` tests fail with the following error:

```
Category: niminaction
Name: tests/niminaction/Chapter8/sfml/sfml_test.nim C++ --nilseqs:on
Action: compile
Result: reNimcCrash
-------- Expected -------

--------- Given  --------
$ /home/administrator/build/Nim/bin/nim cpp --hints:on -d:testing --nimblePath:tests/deps --nilseqs:on --nimCache:nimcache/tests/niminaction/Chapter8/sfml/sfml_test.nim_d8de44f831a39fe22ef81cd6a2f25664 --stdout '--hint[Path]:off' '--hint[Processing]:off' tests/niminaction/Chapter8/sfml/sfml_test.nim
Hint: used config file '/home/administrator/build/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/administrator/build/Nim/config/config.nims' [Conf]
Hint: used config file '/home/administrator/build/Nim/tests/config.nims' [Conf]
CC: stdlib_system.nim
CC: stdlib_posix.nim
CC: stdlib_times.nim
CC: stdlib_os.nim
CC: sfml_test.nim
Error: execution of an external compiler program 'clang++ -c  -w  -I/home/administrator/build/Nim/lib -I/home/administrator/build/Nim/tests/niminaction/Chapter8/sfml -o /home/administrator/build/Nim/nimcache/tests/niminaction/Chapter8/sfml/sfml_test.nim_d8de44f831a39fe22ef81cd6a2f25664/sfml__test.nim.cpp.o /home/administrator/build/Nim/nimcache/tests/niminaction/Chapter8/sfml/sfml_test.nim_d8de44f831a39fe22ef81cd6a2f25664/sfml__test.nim.cpp' failed with exit code: 1

/home/administrator/build/Nim/nimcache/tests/niminaction/Chapter8/sfml/sfml_test.nim_d8de44f831a39fe22ef81cd6a2f25664/sfml__test.nim.cpp:10:10: fatal error: 'SFML/Graphics.hpp' file not found
#include <SFML/Graphics.hpp>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

### PR DESCRIPTION
**Pull request by euantorano**
Partly fixes #12141 - define SDL lib name for OpenBSD and FreeBSD. Other architectures now get a compile error.

### CODE REVIEW

**Comment by krux02** [comment]
I think your PR should be made in this repo: https://github.com/nim-lang/sdl2

**Comment by euantorano** [comment]
It should be made in both really to allow the tests to pass for the compiler. I’ll make one to the library later.

**Comment by dom96** [comment]
@euantorano the point of these tests is to make sure that Nim doesn't break the Nim in Action book examples, this change shouldn't cause an issue but still... if you modify these then this no longer reflects the book. I would prefer if openbsd was instead disabled for these tests.

@Araq can you please not merge these kinds of changes?

**Comment by euantorano** [comment]
I think I’ll need to make some changes to the tester to disable OpenBSD, but I’m going to have to do that anyway for some of the other failing tests (such as coroutines). I’ll open another PR to do that and revert this.

**Comment by Araq** [comment]
@dom96 But the real source code examples are protected by their hashes...

**Pull request merged**
