### PR TITLE
Make build_all.sh more portable and a bit simpler

### PR DESCRIPTION
**Pull request by Clyybber**
Performance stayed exactly the same as https://github.com/nim-lang/Nim/pull/13300

### CODE REVIEW

**Comment by Clyybber** [comment]
Nope, you can verify its effect by doing `./start_all.sh` and watching with htop or some other process viewer.

**Comment by kubo39** [comment]
~~It's nice to use `-l` option, but I think it would be better to add [the link](https://unix.stackexchange.com/questions/316644/is-make-j-with-no-argument-dangerous/393247#393247) the comment.~~

Also, I prefer `command -v` over `which`. https://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then/85250#85250

**Comment by Clyybber** [comment]
@kubo39 That link is wrong, make uses http://git.savannah.gnu.org/cgit/gnulib.git/tree/lib/getloadavg.c . It does not refer to the job count.

**Comment by kubo39** [comment]
Ah, sorry, I found that the algorithm in the GNU make' code (job.c).
Please ignore this.

**Comment by Clyybber** [comment]
@Araq Can we merge this?

**Pull request merged**
