### PR TITLE
Use GCC/Clang built-in assembler instead FASM

### PR DESCRIPTION
**Pull request by nanoant**
This removes extra dependency from Nim, also making coroutines compile on OSX. It should run on Intel systems as long we use some other GCC compatible compilers with integrated assembler.

**Note:** @r-ku @Araq This PR is not removing `.asm` and `assembler` handling, but altogether I think it is really unnecessary and should be removed. I don't think we need really any external assembler since GCC/Clang is just fine also for other architectures such as ARM.

### CODE REVIEW

**Comment by r-ku** [comment]
Reason for picking FASM was retarded AT&T asm syntax gcc uses by default. And i was not aware of ``.intel_syntax noprefix``. This change totally makes sense, @Araq i think you shold merge it once change is complete.

@nanoant this change seems to have missing one part - a compiler mod which adds gcc assembler as built-in "compiler" for .s extension. Or does it work without it?

**Comment by nanoant** [comment]
> @nanoant this change seems to have missing one part - a compiler mod which adds gcc assembler as built-in "compiler" for .s extension. Or does it work without it?

It works without it. GCC/Clang knows that `.s` is an assembly.

> EDIT: on the second thought - this change breaks feature for msvc compiler while it would have worked with fasm. I still like built in assembler idea better but support for lots of compilers is source of problems. @Araq how we should go about that?

We may either:

1. Enable this only for GCC/Clang.
2. Provide `ms_i386.asm` and `ms_amd64.asm` with MASM compatible syntax and enable it only for MSVC (again no extra dependency since MASM `ml` in included in MSVC)
3. Require GNU `as` as a dependency when using MSVC.
4. Install object files `.o` when booting & installing Nim, since anyway you cannot boot nim with MSVC. Then when using MSVC with binary distro, you will just have to link apropriate `.o` files.

**Comment by yglukhov** [comment]
5. Implement asm within nim ;)

**Comment by r-ku** [comment]
1. Honestly i dont care much for msvc but its just me. Does not mean msvc is not important. Some people may want to use this feature linking nim code to whatever msvc produces. This probably would be viable when clang MS ABI matures.
2. Maybe this could be pulled off with some include magic and no code duplication? However making it work with other compilers could become increasingly difficult? Not sure about this..
3. This one is probably worst. Some KB fasm executable as external dependency is much lighter than gcc. Having gcc as dependency would be big finger to msvc users.
4. This is probably best idea IMHO. Im no expert on object formats used across compilers but maybe it would make coverage of other compilers easier too?
5. PRs are welcome! :p

**Comment by Varriount** [comment]
Wait, Nim isn't bootable with MSVC?

**Comment by nanoant** [comment]
> Wait, Nim isn't bootable with MSVC?

No it's not. That's why we may get `.o` (`.obj` object files) out of `.s` during boot that has to be done with GCC/Clang. Then simply link these object file during normal use with whatever compiler you want.

**Comment by kirbyfan64** [comment]
Be careful with sending over `.o` files. I have literally blown up linkers by trying to mix GCC and MSVC objs before.

Then again, this doesn't seem to hold anything that would cause linker issues...

**Comment by nanoant** [comment]
@kirbyfan64 You've probably tried mixing MS C++ABI with GCC C++ABI. In this case this is plain old C calling convention made out of assembly. There is no reason it wouldn't work. As for `.obj`/`.o` files themselves, these are platform dependent not compiler dependent.

**Comment by kirbyfan64** [comment]
@nanoant No; they were C. I don't know if I had a broken GCC install or *what*. I just know it didn't end well. GCC was ignoring every single MSVC object file...or at least it wasn't picking up the symbols correctly.

**Comment by nanoant** [comment]
@kirbyfan64 Just tested with mingw64 and MSVC 2015 on my Windows VM, there no problem of linking two objects out of C source compiled with `cl` and `gcc`. So sounds like some false alarm.

**Comment by dom96** [comment]
Just tried this on Windows and I get:
```
CC: ms_i386
c:\users\dominik\git\nimrod\lib\arch\ms_i386.s: Assembler messages:
c:\users\dominik\git\nimrod\lib\arch\ms_i386.s:10: Error: can't open i386.s for
reading: No such file or directory
Error:  execution of an external program failed; rerun with --parallelBuild:1 to
 see the error message
```

After changing the ``.include`` to point to ``arch/i386.s`` I get:

```
CC: ms_i386
c:\Users\Dominik\git\nimrod\lib/arch/i386.s: Assembler messages:
c:\Users\Dominik\git\nimrod\lib/arch/i386.s:17: Error: bad expression
c:\Users\Dominik\git\nimrod\lib/arch/i386.s:17: Error: junk `ecx+0Ch]' after exp
ression
c:\Users\Dominik\git\nimrod\lib/arch/i386.s:18: Error: bad expression
c:\Users\Dominik\git\nimrod\lib/arch/i386.s:18: Error: junk `ecx+10h]' after exp
ression
c:\Users\Dominik\git\nimrod\lib/arch/i386.s:19: Error: bad expression
c:\Users\Dominik\git\nimrod\lib/arch/i386.s:19: Error: junk `ecx+14h]' after exp
ression
c:\Users\Dominik\git\nimrod\lib/arch/i386.s:20: Error: bad expression
c:\Users\Dominik\git\nimrod\lib/arch/i386.s:20: Error: junk `ecx+18h]' after exp
ression
c:\Users\Dominik\git\nimrod\lib/arch/i386.s:29: Error: bad expression
c:\Users\Dominik\git\nimrod\lib/arch/i386.s:29: Error: junk `ecx+0Ch]' after exp
ression
c:\Users\Dominik\git\nimrod\lib/arch/i386.s:31: Error: bad expression
c:\Users\Dominik\git\nimrod\lib/arch/i386.s:31: Error: junk `ecx+10h]' after exp
ression
c:\Users\Dominik\git\nimrod\lib/arch/i386.s:33: Error: bad expression
c:\Users\Dominik\git\nimrod\lib/arch/i386.s:33: Error: junk `ecx+14h]' after exp
ression
c:\Users\Dominik\git\nimrod\lib/arch/i386.s:48: Error: bad expression
c:\Users\Dominik\git\nimrod\lib/arch/i386.s:48: Error: junk `ecx+0Ch]' after exp
ression
c:\Users\Dominik\git\nimrod\lib/arch/i386.s:49: Error: bad expression
c:\Users\Dominik\git\nimrod\lib/arch/i386.s:49: Error: junk `ecx+10h]' after exp
ression
c:\Users\Dominik\git\nimrod\lib/arch/i386.s:50: Error: bad expression
c:\Users\Dominik\git\nimrod\lib/arch/i386.s:50: Error: junk `ecx+14h]' after exp
ression
Error:  execution of an external program failed; rerun with --parallelBuild:1 to
 see the error message
```

Not sure what's going on, could it be that MINGW doesn't like intel syntax?

**Comment by nanoant** [comment]
@dom96 I've updated the PR with the fix. The problem was `XXh` hexadecimal notation, while older GCC expects `0xXX`.

@r-ku For some reason trying to compile Nim with `./koch boot --parallelBuild:1 -d:nimCoroutines` causes Nim stage 2 to crash on:

~~~
* thread #1: tid = 0xa519b, 0x0000000100409811 nim1`growobj_66006 + 257, queue = 'com.apple.main-thread, stop reason = EXC_BAD_ACCESS (code=1, address=0x8)
    frame #0: 0x0000000100409811 nim1`growobj_66006 + 257
nim1`growobj_66006:
->  0x100409811 <+257>: movzbl 0x8(%rax), %r9d
    0x100409816 <+262>: cmpl   $0x1c, %r9d
    0x10040981d <+269>: jne    0x100409828               ; <+280>
    0x100409823 <+275>: jmp    0x10040983b               ; <+299>
~~~

I don't know what is the reason. Any ideas?

**Comment by r-ku** [comment]
Is it compiler crash or what? And post code you are compiling, otherwise for me it stumbling in the dark ;)

**Comment by kirbyfan64** [comment]
@r-ku He said:

> For some reason trying to **compile Nim** with `./koch boot --parallelBuild:1 -d:nimCoroutines` causes **Nim stage 2** to crash on:

The compiler is crashing while building the compiler.

**Comment by r-ku** [comment]
ohh /facepalm. thanks for clarification. ill take a look.

**Comment by nanoant** [comment]
@r-ku FYI it crashes both when using this patch and using old `fasm` based solution. I tested only on 64-bit arch, Windows and OS X.

**Comment by Araq** [comment]
Well. The DSL would be the best ultimate solution but it's up in the sky. For now this PR makes matters worse:

* Doesn't work with Visual C++ anymore then.
* '.intel_syntax noprefix' seems fragile.
* Opportunity to use a real assembler will be helpful for pure Nim code generators etc.

**Comment by nanoant** [comment]
@Araq I am sorry to see you closing this, because your reservations are not entirely true:

> Doesn't work with Visual C++ anymore then.
But VC cannot be used for booting Nim. My solution works on any GCC/Clang which is used to boot Nim. So as I pointed out above, object files can be generated at boot stage, then `.o` files get linked with any compiler, including VC. This is not covered by this PR, but this can be easily implemented.

> '.intel_syntax noprefix' seems fragile.
I am sorry, but `.intel_syntax` exists in GCC since 2003 or so, Clang supports that too. Do we want support booting Nim using some compiler versions from 90-ties!?

> Opportunity to use a real assembler will be helpful for pure Nim code generators etc.
By real you mean `fasm`? What makes it more real than `gcc`? Do we really want to add extra dependency if we can solve things without doing so?

**Pull request closed without merging**
