### PR TITLE
Run ttimes parseTest across multiple timezones

### PR DESCRIPTION
**Pull request by FedericoCeratto**
Related to #5704 #6045 and #6465
Work in progress.
EDIT: this PR is being integrated in #6552

### CODE REVIEW

**Comment by GULPF** [comment]
Shouldn't it be possible to use the IANA timezone identifiers instead of looking for the files? E.g `Europe/London`, `Asia/Seoul` etc.

**Comment by FedericoCeratto** [comment]
@GULPF timezone files might differ across users, buildbots and change over time (e.g. a timezone stops existing or is renamed).

**Comment by GULPF** [comment]
OK, that makes sense. Perhaps it would be possible to include a few problematic timezone definitions directly in the tests folder? I dislike having nondeterministic tests (still an improvement over the current situation though, which is even more nondeterministic).

**Comment by dom96** [comment]
oh, this is nice. Exactly what I was talking about in @GULPF's PRs. We need this to ensure our tests cover as many cases as possible.

I would also prefer to have more determinism. We can surely grab a list of reliable timezones that are offered by all systems (we can expand on this list in the future). What do you guys think?

**Comment by FedericoCeratto** [comment]
I also dislike non-deterministic tests, however this is an integration test rather than unit test where we are testing how the times library works against the libraries and files present on various systems. Users should be able to run the tests against their system if needed.

(On a side node, can timezone files be hardcoded successfully? Perhaps they are platform/architecture dependent)

We can hardcode a list of timezones that must be present instead of using a threshold.

**Comment by FedericoCeratto** [comment]
@GULPF this PR is currently only adding tests and not fixing things. Do you want to rebase your fixes on top of it?

**Comment by GULPF** [comment]
I've incorporated the timezone tests into #6552 now (don't know how to do a git rebase across PR's) and made them pass. Actually found a few bugs right away because of the new tests :)

**Pull request closed without merging**
