### PR TITLE
correct grammar (ref #20199) and add check for grammar.txt

### PR DESCRIPTION
**Pull request by ringabout**

### CODE REVIEW

**Comment by Araq** [comment]
How come `parser.nim` does not reflect this?

**Comment by ringabout** [comment]
Is there a test for grammar? 

```nim
when isMainModule:
  # Leave a note in grammar.txt that it is generated:
  #| # This file is generated by compiler/parser.nim.
  import pegs
  when defined(nimPreviewSlimSystem):
    import std/syncio
  var outp = open("doc/grammar.txt", fmWrite)
  for line in lines("compiler/parser.nim"):
    if line =~ peg" \s* '#| ' {.*}":
      outp.write matches[0], "\L"
  outp.close

  import ".." / tools / grammar_nanny
  checkGrammarFile()
```
I only saw this in the parser.nim, which generates a new grammar.txt if executed directly. If there isn't a test, I can write one to compare newly generated text with the existing one.

**Comment by metagn** [comment]
This is in `parser.nim`, it's just not in grammar.txt.

https://github.com/nim-lang/Nim/blob/9d858a29fc9776963cf1e7a2c706dceda45e662e/compiler/parser.nim#L2111-L2114

**Comment by ringabout** [comment]
> This is in parser.nim, it's just not in grammar.txt.

Yeah, so we need to add a test case for grammar.txt to keep it in accordance with `parser.nim`.

**Comment by Araq** [comment]
> Yeah, so we need to add a test case for grammar.txt to keep it in accordance with parser.nim.

Not really. "Nobody is allowed to touch grammar.txt directly" is good enough as a rule.

**Comment by ringabout** [comment]
Yeah, they can also forget to run `compiler/parser.nim` after modifying the documentation comments. And grammar.txt is part of the Nim manual.

**Comment by Araq** [comment]
So did somebody forget to run `compiler/parser.nim`?

**Comment by ringabout** [comment]
> So did somebody forget to run compiler/parser.nim?

Yes, I think so according to the diff of #20199.

Here is the change in the parser.nim

image

But it is not reflected in the grammar.txt 

image

And if you execute the `compiler/parser.nim`, you can get the corresponding changes for grammar.txt.

**Comment by Araq** [comment]
Ok, but don't duplicate the program from `parser.nim` for your test. Instead import parser.nim and inside parser.nim use `when isMainModule or defined(nimGenerateGrammar)` or similar.

**Comment by ringabout** [comment]
Sure.

**Pull request merged**
