### PR TITLE
change chronos test flags

### PR DESCRIPTION
**Pull request by bung87**
will figure out the causes before this get merged

### CODE REVIEW

**Review by arnetheduck — APPROVED** [review]

**Comment by Araq** [comment]
Does this affect CI times measurably? These assertions can be quite expensive iirc.

**Comment by bung87** [comment]
I just test on my mini PC, not sure how this feels.

platform: win10
nim version: Nim Compiler Version 1.9.5 [Windows: amd64]
cpu: Intel® Pentium® Silver N6005 Processor 2.00 GHz (with burst disabled by settings power supply 99%)

test on release mode.

flags: `-d:useSysAssert -d:useGcAssert`

without flags:

run:
0.00user 0.10system 1:50.84elapsed 0%CPU (0avgtext+0avgdata 5500maxresident)k
0inputs+0outputs (1436major+0minor)pagefaults 0swaps

with flags:

run:

0.00user 0.09system 1:53.56elapsed 0%CPU (0avgtext+0avgdata 5500maxresident)k
0inputs+0outputs (1436major+0minor)pagefaults 0swaps

**Comment by ringabout** [comment]
> will figure out the causes before this get merged

It breaks CI anyway. It needs to be figured out before merging. You can test bugs on your own fork with CI enabled.

**Comment by ringabout** [comment]
Succeeded by https://github.com/nim-lang/Nim/pull/22374

**Pull request closed without merging**
