### PR TITLE
feat: copy to clipboard

### LINKED ISSUE #18944: DocGen Copy button for code snippets
Would be great to add a "Copy" button to the code blocks rendered by the Docgen,
just like GitHub itself has nowadays on the code blocks, the Docgen needs to add 1 line:

```html
<button onclick="document.querySelector('#SELECTOR').select();document.execCommand('copy');">Copy</button>
```

I copied from https://github.com/timotheecour/Nim/issues/802
@juancarlospaco

### PR DESCRIPTION
**Pull request by vj-abishek**
Shows a `copy to clipboard` button like this  on hover
image

fixes #18944

### CODE REVIEW

**Comment by a-mr** [comment]
you also need to copy `nimdoc.css` to nimdoc/testproject/**expected**/nimdoc.out.css manually. (we have a docgen test that just compares files in directories, in this case with generated nimdoc/testproject/**htmldocs**/nimdoc.out.css)

**Comment by vj-abishek** [comment]
@a-mr, fixed the issue

**Comment by vj-abishek** [comment]
Hello @a-mr actually I'm doing it as a part of hacktoberfest, So please check it when you have free time 🙃

**Comment by ringabout** [comment]
>> I'm doing it as a part of hacktoberfest, So please check it when you have free time

> Your pull requests will count toward your participation if they are in a repository with the 'hacktoberfest 'topic and once they have been merged, approved by a maintainer or labeled as **hacktoberfest-accepted**.

**Comment by a-mr** [comment]
@vj-abishek ,
How to use it?
When I process any `rst` or `nim` file with `nim rst2html` or `nim doc` command and open the resulting `html`, I see that a new button appears on hovering over any code. But when I press it nothing happens — button does not change its color and text is not being copied to clipboard.

**Comment by vj-abishek** [comment]
I think you need to compile dochack.nim. I used  `./koch docs` Or `nim js -d:danger tools/dochack/dochack.nim` commands

Could you check if `dochack.js` has a function known as `copyToClipboard`?

**Comment by a-mr** [comment]
Yes, you are right, thank you. One also needs to copy manually the resulting `dochack.js` to the same directory as `.html`. Just `nim doc` does not do it, but e.g. `nim doc --project` does. It seems that this issue was mentioned before: https://github.com/nim-lang/Nim/issues/4868, https://github.com/nim-lang/Nim/issues/8952.

**Comment by juancarlospaco** [comment]
How this is going?, I really like the change. 🙂

**Comment by vj-abishek** [comment]
I'm also waiting.....

**Comment by a-mr** [comment]
Something is not quite right on Linux, I see something like a race.

After I defined
```nim
proc f*() =
  ## doc
  discard
```
I'm trying to select a fragment from the snippet:
image

Note that I don't really "click" on text, instead I press left button, move the pointer and release it, as usual in selecting.

After a few retries I see that 2 results happen randomly:
* roc f() {.r
* proc f() {.raises: [], tags: [].}

Actually I don't understand in the first place why the whole text area works as a button. And it seems that selecting also triggers this "button" and then either of 2 happens:
* normal browser mechanism on copying the selected text to clipboard is triggered last
* this PR `copyToClipboard` is triggered last

Note that I have [clipboard.autocopy=true](http://kb.mozillazine.org/Clipboard.autocopy) in my Firefox about:config, which allegedly works only on Unix. And my OS is a Debian 10 clone.

**Comment by a-mr** [comment]
Also a minor thing, when pragma is still folded
image
then text is copied literally with 3 additional dots:
```
proc f() {.....}
```
Though it may be too hard to fix.

**Comment by vj-abishek** [comment]
Will fix it soon.

**Comment by vj-abishek** [comment]
Done ✅

**Comment by a-mr** [comment]
Great, it's much better. Now only button acts as button.

Regarding pragmas: would it be possible instead of just getting value by `const clipBoardContent = e.target.value` to descend into the block and recursively traverse it, omitting all objects with class `pragmadots` while accumulating `value` content into string?

It's just an arbitrary suggestion, note that I know next to nothing about Web technologies.

**Comment by vj-abishek** [comment]
Hope everything is fixed

**Comment by Araq** [comment]
Additional improvements can be done in follow-up PRs.

**Comment by a-mr** [comment]
Yes, it works very well now, thanks.

There are minor usecases with pragmadots that are not perfect (e.g. when 2 pragmadots occur for procs `echo`, `equalMem` in `system.html`, then 2nd `...` is additionally copied into clipboard), but I doubt it's even worth investing time to fix it.

**Pull request merged**
