### PR TITLE
CI openbsd: 3x batching via NIM_TESTAMENT_BATCH ; overall CI finishes in 21m instead of 34m

### PR DESCRIPTION
**Pull request by timotheecour**
followup after https://github.com/nim-lang/Nim/pull/14823: openbsd is now the bottleneck by far, taking ~34mn whereas the next most expensive (Linux_i386) takes 23mn

## timing results
* 1x batching (before this PR): max = 32m to 34m
* 2x batching: 25+26 (max = 26m)
* 3x batching: 20+19+20 (max=20m)

## after PR
* investigate why is openbsd (and windows) is so slow, in particular compared to freebsd which should intuitively should give similar timing results (both are BSD OS's and both run in same CI hosted on https://builds.sr.ht/): without batching: 32m(openbsd) vs 19m (freebsd)

/cc @euantorano since you've done the most work related to freebsd/openbsd

* same remarks, caveats, and suggested improvements as noted in https://github.com/nim-lang/Nim/pull/14823, in particular for tests outside of `execFold("Run tester", "nim c -r -d:nimCoroutines testament/testament --pedantic --batch:$1 all -d:nimCoroutines" % ["NIM_TESTAMENT_BATCH".getEnv("_")])`

### CODE REVIEW

**Comment by ghost** [comment]
@timotheecour not really related to the CI, but OpenBSD is generally known to have worse performance than other OSes (even FreeBSD) due to having a lot of security features/mitigations enabled by default.

**Comment by timotheecour** [comment]
that indeed seems to be the case; some random links:
* https://www.phoronix.com/scan.php?page=article&item=8-linux-bsd&num=5
* https://github.com/golang/go/issues/29223
* http://bulk.fefe.de/scalability/

2x slower than OSX is pretty disappointing though

**Comment by euantorano** [comment]
Sorry, I missed the CC as I didn't get a mention.

It is true that OpenBSD is generally slower than FreeBSD or Linux and isn't particularly well known for its speed. Not only do the security measures slow it down, but there is still to this day a giant lock in the kernel (same goes for NetBSD AFAIK). There is ongoing work to unlock various parts of the kernel though in each release which should help in the future.

**Comment by timotheecour** [comment]
> Sorry, I missed the CC as I didn't get a mention.

i forgot the `@`, fixed it ;-)

> Not only do the security measures slow it dow

any way to turn off some of those?
any other recommendations to improve speed of openbsd besides this PR? (which is a bit wasteful in terms of overall resource usage but still much better that what was before)

**Comment by euantorano** [comment]
We could experiment with the clock type, I’m not sure what clock type sr.ht is using right now. I’ll have a look and experiment this weekend.

**Pull request merged**
