### PR TITLE
fix #13517

### LINKED ISSUE #13517: Wrong compile-time integer result
Wrong compile-time integer result:

### Example
```nim
type MyUint64 = distinct uint64

proc `==`(a: MyUint64, b: uint64): bool = uint64(a) == b

block:
  doAssert MyUint64.high is MyUint64
  doAssert MyUint64.high == 18446744073709551615'u64     # works

static:
  doAssert MyUint64.high is MyUint64
  doAssert MyUint64.high == 18446744073709551615'u64     # FAILS !!
```

### Current Output
```
Compilation fails:

.../nim-git/lib/system/fatal.nim(55, 5) Error: unhandled exception: /tmp/test.nim(11, 12) `MyUint64.high == 18446744073709551615'u64`  [AssertionError]
```

### Expected Output
```
Program should compile.
```

### Additional Information

* Issue #6733 might be somewhat related.

```
$ nim -v
Nim Compiler Version 1.1.1 [Linux: amd64]
Compiled at 2020-02-27
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 42dad3a836f7eed860f300e68b33d4c0b39bd1f4
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by ringabout**
fix #13517

### CODE REVIEW

**Review by timotheecour — APPROVED** [review]

**Comment by timotheecour** [comment]
LGTM
pre-existing, but what's the rationale for `high(a: Dollar)` being automatically defined for `type Dollar = distinct int` ?

**Comment by mratsim** [comment]
Agree with @timotheecour with distinct we need to reimplement `+`, `-`, `$`, `==`, ...

I don't see why `high` should be special.

**Comment by ringabout** [comment]
> LGTM
> pre-existing, but what's the rationale for `high(a: Dollar)` being automatically defined for `type Dollar = distinct int` ?

`high` accepts `Ordinal` types which may be the reason.
I'm not sure whether it is easy to disable it.

The root cause is that `distinct Ordinal` is `Ordinal`.

**Comment by Araq** [comment]
> The root cause is that distinct Ordinal is Ordinal.

Tried to fix that once but broke too much code. But we should really do it and have some switch re-enable it for the people who depend on it.

**Comment by timotheecour** [comment]
> Tried to fix that once but broke too much code. But we should really do it and have some switch re-enable it for the people who depend on it.

=> https://github.com/nim-lang/RFCs/issues/313

**Pull request merged**
