### PR TITLE
Add NIMTEST_NO_ELAPSED_TIME to a CI files

### PR DESCRIPTION
**Pull request by data-man**
Need for PR #6601.

### CODE REVIEW

**Comment by dom96** [comment]
If this needs to be added for tests then you should either:

* Make this feature disabled by default
* Fix the tests to work with the new feature

Otherwise all the tests will fail locally and people won't know about this env var.

**Comment by data-man** [comment]
> people won't know about this env var.
This env var described in the docs. :)

**Comment by dom96** [comment]
People don't reads docs.

**Comment by data-man** [comment]
So it is better to do:: close this PR and disable a estimated time by default in unittests?

**Comment by dom96** [comment]
I think so. But you might want to wait to see what others think.

**Comment by data-man** [comment]
Env var renamed to NIMTEST_WITH_ELAPSED_TIME and disabled by default.

**Pull request closed without merging**
