### PR TITLE
`succ`, `pred`, `inc` and `dec` accept some integers instead of int

### PR DESCRIPTION
**Pull request by ringabout**
supersedes https://github.com/nim-lang/Nim/pull/22457

### CODE REVIEW

**Comment by konsumlamm** [comment]
This is better than https://github.com/nim-lang/Nim/pull/22457, but I'd still prefer https://github.com/nim-lang/checksums/pull/6. `+`/`+=` don't allow different argument types for good reason imo. This also breaks the JS backend, which relies on the second argument always being an `int`. This could be solved by only using the magic if the second argument is an `int` (i.e. adding an overload for `SomeInteger`, that doesn't use the magic).

**Comment by ringabout** [comment]
Unrelated CI failure.

**Comment by ringabout** [comment]
> This could be solved by only using the magic if the second argument is an int (i.e. adding an overload for SomeInteger, that doesn't use the magic).

Feel free to improve that in the following PRs. I need this to unblock https://github.com/nim-lang/Nim/pull/22453

**Comment by konsumlamm** [comment]
Again, what's the problem with https://github.com/nim-lang/checksums/pull/6?

**Comment by ringabout** [comment]
Well, not like I object to my own PR. Either one is fine to merge.

**Comment by Araq** [comment]
The signature is `inc(Ordinal, int)` etc, I don't know why this is debatable.

**Comment by konsumlamm** [comment]
> The signature is `inc(Ordinal, int)` etc, I don't know why this is debatable.

That's how it originally was and currently is (without this PR or #22457), but `checksums` apparently relied on it also accepting `uint64` as second argument, while the signature was `inc[T: Ordinal, V: Ordinal](T, V)`.

**Comment by ringabout** [comment]
https://github.com/nim-lang/checksums/pull/6 was merged

**Pull request closed without merging**
