### PR TITLE
Fixed and slightly changed exception handling in JS.

### PR DESCRIPTION
**Pull request by yglukhov**
All JS tests are green now. Exception propagation fixed. Exception handling is slightly simplified. The price:
1. I'm not sure if I've done anything wrong to lua codegen. Do I have to worry?
2. *Unhandled exception* case is not handled by Nim anymore. Such exceptions are just propagated upwards to whatever called us. Actually this may be beneficial when using Nim-written code from within pure JS code.

### CODE REVIEW

**Comment by Araq** [comment]
> 2. Unhandled exception case is not handled by Nim anymore. Such exceptions are just propagated upwards to whatever called us

This is what I have to do for the C++ backend too and I don't like it. Can you re-enable this feature via some switch?

**Comment by yglukhov** [comment]
Well, I have disabled it not because I like it that way, but because I didn't know how to do it otherwise. But ok, I will think on it some more.

**Comment by yglukhov** [comment]
Ok, maybe this PR requires an RFC tag to kick discussion off. My opinion is that nim doesn't have to handle *unhandled exceptions* since it requires complexity in terms of both logic and performance, while the outcome is really phantom. The only benefit is a readable stack-trace of such exceptions. But if user really wants to he may just wrap his top-level in a try-catch and enjoy those stack traces. Also the problem gets much more obscure when nim code is intended to be called from foreign C/C++/JS code. Nim can never know whether that code is prepared for handling exceptions, and in my opinion this is not nim's problem. If we're to handle *unhandled exceptions* while the calling foreign code really tends to handle those it may lead to some confusion, albeit arguable. Thoughts? =)

**Comment by Araq** [comment]
Well all it takes is some counter to see if we're in a Nim generated 'try' statement and if so our 'raise' really raises, otherwise 'raise' produces the lovely Nim stack traces and exits. So ... it's not much effort to generate but is very similar to ``-d:noSignalHandler`` which can be disabled too.

**Comment by yglukhov** [comment]
It's not only that. You have to check for exception types that are caught. If there's no generic catch in the stack there still might me an appropriate catch.

**Comment by yglukhov** [comment]
However... Maybe this can be done later in a catch...

**Comment by yglukhov** [comment]
@Araq, it turned out you were totally right. This type checking reduced to just a counter in the end. I've also made that non-Nim exceptions are just propagated upwards without calling to unhandledException().

**Comment by yglukhov** [comment]
Thank you!

**Pull request merged**
