### PR TITLE
clean zip support < 1.0.0

### PR DESCRIPTION
**Pull request by ringabout**
(EDIT(timotheecour): refs https://github.com/timotheecour/Nim/issues/389)

### CODE REVIEW

**Comment by timotheecour** [comment]
IMO this is fine because 0.20.0 is only needed for bootstrap, which doesn't rely on zip, and nim only supports 1.0+ via `--useVersion`. The only downside would be if koch.nim (or its dependents) is later modified to depend on zip, but the `when bootstrap` logic could be handled in koch.nim instead of stdlib.

but then the code should be removed instead of commented out (you can always use git history)

**Comment by ringabout** [comment]
Sorry, I misread the code.

**Comment by timotheecour** [comment]
also had misread code in this PR; the issue was that it would break 1.0.x branch instead of branches prior to 1.0

**Comment by Araq** [comment]
Gah, I too misread the code.

**Pull request closed without merging**
