### PR TITLE
Implement some custom formatting for input fields in the documentation

### PR DESCRIPTION
**Pull request by Calinou**
Aside of resulting in more consistent appearance across browsers, this also fixes input form rendering when using Firefox with a dark system theme on Linux.

## Preview

nimdoc_input_styling

### CODE REVIEW

**Comment by trustable-code** [comment]
Fixes #10777

**Comment by Varriount** [comment]
Looks like you need to update the docgen tests, so the ci/cd pipeline will pass.

**Comment by narimiran** [comment]
> Looks like you need to update the docgen tests

Those can be fixed by running `nim c -d:fixup -r nimdoc/tester`

**Comment by Calinou** [comment]
@narimiran Thanks for the tip :smiley:

I just did so and it left just the original changes in `nimdoc.cfg`, like I had before amending this commit today.

**Comment by narimiran** [comment]
> Won't it fail again?

From what I can see, nimdoc tests are still not changed, so yes, it will fail again. Let me try to work this out.

**Comment by narimiran** [comment]
> I just did so and it left just the original changes in nimdoc.cfg, like I had before

I just pushed the changes. It seems that the command I gave you should be run twice: the first time it just reports the failing test, and the second time it fixes them.

**Pull request merged**
