### PR TITLE
Change stdlib imports to use std prefix in most examples

### PR DESCRIPTION
**Pull request by ghost**
Please leave feedback, this is just a draft.

vscode regexes used:
`runnableExamples:\n\s*(import|from)` (search for imports in the start of runnableExamples)

`##\s*(import|from)` - search for import (or from) in comments

`import ` - search for import and a space

### CODE REVIEW

**Comment by ghost** [comment]
I might've missed some, but I think that I covered most examples.

**Comment by ghost** [comment]
Last commit changes some imports in manual - please say if that shouldn't be done.

**Review by timotheecour — APPROVED** [review]
LGTM. I checked everything.

merging, refs https://github.com/nim-lang/Nim/pull/17105

**Comment by timotheecour** [comment]
@Yardanico further cleanup PR's welcome, eg
* turning code-blocks into runnableExamples
* finishing what was started with https://github.com/nim-lang/Nim/pull/17100

**Pull request merged**
