### PR TITLE
Add module jscanvas

### PR DESCRIPTION
**Pull request by b3liever**
Notes:
- All coordinates are integers. Is this ok?
- CanvasElement could move to `dom`

### CODE REVIEW

**Comment by dom96** [comment]
There is plenty of Nimble packages that implement this already, why do you think it belongs in the stdlib?

**Comment by b3liever** [comment]
Ready for review

**Comment by narimiran** [comment]
`[ci skip]` tag should be used sparingly, e.g. for correcting a single spelling error in the documentation. Adding a new module is not such a case.

And since I did a lot of work improving the docs of the existing modules, I expect nothing less from (potentially) new modules, i.e. detailed documentation with explanations, examples and links.

**Comment by dom96** [comment]
I see that you've asked about this in IRC: https://irclogs.nim-lang.org/12-04-2019.html#13:05:07. It would be helpful to mention that in your PR (and not ignore me :'/).

I'll reiterate though, we've got https://gitlab.com/define-private-public/HTML5-Canvas-Nim and my gamelight package and both wrap canvas. We need to have good reasons to put this into the stdlib. So why do you think it should be there?

**Comment by b3liever** [comment]
Close, bc there is a better alternative.

**Comment by b3liever** [comment]
The better alternative was this [issue](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API), a nimble package is also published here: https://github.com/b3liever/jscanvas

**Pull request closed without merging**
