### PR TITLE
Feature/xmltree additions

### PR DESCRIPTION
**Pull request by survivorm**
Several functions useful working with Xml tree

### CODE REVIEW

**Comment by survivorm** [comment]
Any idea why enumerate in CI works this way? On my local PC it works perfectly fine. Enumerate itself hadn't change for 2 years, so, why?  
https://github.com/nim-lang/Nim/actions/runs/3594403218/jobs/6052617903

**Comment by survivorm** [comment]
Also can somebody in core team elaborate, why insert method takes only `xnElement`'s for child's kind? It doesn't make much sense, as add has no such limitation. Perhaps it's something to do with performance?

**Comment by survivorm** [comment]
rewritten w/o enumerate, while still not sure why previous code didn't pass CI

**Comment by Araq** [comment]
"useful working with XmlTree" is not a valid criterion for inclusion in a standard library. `insert` and `delete` are justifyalbe but `replace` might already be overkill and `restrictTags` is strangely specific.

**Comment by survivorm** [comment]
It's somewhat similar to CRUD philosophy. I'm not sure it's a justification, but every module should be useful, isn't it? It's not a question of is it in standard lib or not it's more of a question of is it easy and comfortable to use. And yeah, I can see that you mean about the specifics of restrictTags. But also it's a question of is it incapsulation breach, or not. I mean - method is heavily relying on the current internal object structure of XmlNode. Is it good to have such method in a stand-alone lib? 
As for applications - i've stumbled upon the need for such method in writing a module for FictionBoook2 format writer/reader. But seeing as it may (or may not, perhaps, I admit) have more general applications in other instances, then we have not allowed/not recognized tags i decided to place it in here. So, I'm asking as for there it belongs, in your opinion?

**Comment by Araq** [comment]
C++'s stdlib: Specified big-O behavior, encourages independent implementations, superb documentation, well thought out in what it offers and the interface it provides.

Nim's stdlib: Added `restrictTags` to its XML handling because it's handy when implementing a FictionBoook2 reader/writer.

Can you guess which design principles will stand the test of time?

**Comment by survivorm** [comment]
Ok, I get it. But any advice on there it should be? Cause it's in-between specific and general purpose and breaches incapsulation (thou, that _may_ be rewritten to be on a lesser scale, perhaps). XmltreeExt? As a standalone lib for methods not in stdlib, but may be handy?
And what about the other parts of the pr?

**Comment by survivorm** [comment]
Also, on a different note - we have child methods here, but none of the parent/ancestor. It's not my place to decide if they're needed (as I have yet to need any), but that sounds not very consistent. I can understand it's connected with that we don't want cyclic structures here, but what about adding methods (like `proc parent(root, child: XmlNode): XmlNode`)
Not very efficient, but better than nothing, no?

**Comment by Araq** [comment]
`insert` and `delete` and `replace` are ok but please ensure they are tested well.

Offering a "parent" feature if you cannot do so efficiently would only encourage very poorly written code. It also prevents the sharing of nodes between trees, it's an anti-feature.

**Comment by survivorm** [comment]
Oh, one more question. Why `insert` method takes only `xnElement`'s for `child`'s kind? What's the purpose of such a limitation?

**Comment by survivorm** [comment]
@Araq May you please answer (you're this code's author (see above))

**Comment by Araq** [comment]
Can't remember, looks like a bug to me.

**Comment by survivorm** [comment]
So you're okay to me lifting that restriction on all insert/replace methods?

**Comment by Araq** [comment]
Yes.

**Comment by Araq** [comment]
@survivorm May you please update this PR (you're the PR's author).

**Comment by survivorm** [comment]
I'm working on it "low priority" I'll update it, but it won't be final for now (i plan to add more tests)

**Comment by survivorm** [comment]
Updated, tests in progress

**Comment by survivorm** [comment]
Tests added. Do I need to update changelog?

**Comment by survivorm** [comment]
Re-running pipeline. As I don't think failure has anything to do with my code...

**Comment by survivorm** [comment]
Looks like test fails are sporadic and not connected to my code. So, i think i'll rerun pipeline again

**Comment by survivorm** [comment]
@Araq Any other thoughts on what should be done?

**Comment by survivorm** [comment]
@Araq ping

**Pull request merged**
