### PR TITLE
fix #8129 by calling `semExpr` in `semIs` if node is `strLit`

### LINKED ISSUE #8129: Regression: SIGSEGV caused by using `is` with string
I had code similar to
```nim
let d = "aaa"
if d is "":
  echo "help"
```
in a library from when I was learning Nim. Trying to compile on the most recent devel causes a SIGSEGV during compilation.
`koch` outputs:
```
Traceback (most recent call last)
nim.nim(133)             nim
nim.nim(97)              handleCmdLine
main.nim(162)            mainCommand
main.nim(73)             commandCompileToC
modules.nim(124)         compileProject
modules.nim(71)          compileModule
passes.nim(194)          processModule
passes.nim(103)          processTopLevelStmt
sem.nim(587)             myProcess
sem.nim(555)             semStmtAndGenerateGenerics
semstmts.nim(1894)       semStmt
semexprs.nim(908)        semExprNoType
semexprs.nim(2510)       semExpr
semstmts.nim(160)        semIf
semexprs.nim(59)         semExprWithType
semexprs.nim(2440)       semExpr
semexprs.nim(1988)       semMagic
semexprs.nim(410)        semIs
semexprs.nim(345)        isOpImpl
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
FAILURE
```

While `is` and `isnot` should be used on types as I know nowadays, this should still not crash the compiler. The regression is also introduced by the recent typedesc merge of: https://github.com/nim-lang/Nim/pull/7681

### PR DESCRIPTION
**Pull request by Vindaar**
With the help of @LemonBoy an attempt to fix #8129.

### CODE REVIEW

**Comment by zah** [comment]
I suggest finding the root origin of this. How come the string literal doesn't have a proper type set?

**Comment by LemonBoy** [comment]
> How come the string literal doesn't have a proper type set?

Because it's not semanticized at all, that's why I suggested to introduce a `semExpr` (no flags are needed tho)

**Comment by zah** [comment]
`isOpImpl` is a low-level helper proc in the compiler being called from `semIs`, which is supposed to call `semExpr` and friends on the inputs.

**Comment by Vindaar** [comment]
@LemonBoy: Oh, I just realized that the `internalAssert` in `isOpImpl` checks for the `kind` of `n.sons[2]` instead of `n.sons[2].typ.kind`.
That's why the check for `and t2.kind != tyTypeDesc:` is indeed useful. Without it, the following test case from `tisopr.nim` fails (returns "no" instead of "yes"):
```nim
proc test[T](x: T) =
  when T is typedesc:
    echo "yes"
  else:
    echo "no"

test(7)
```

I changed that and rebased it. Also removed the unnecessary flag in the `semExpr` call.

@zah: But that's exactly what the PR does, no?

**Comment by zah** [comment]
Ah, you are right. I got confused by the diff viewer somehow. LGTM.

**Comment by Varriount** [comment]
Attempting to re-start travis build.

**Comment by LemonBoy** [comment]
> Oh, I just realized that the internalAssert in isOpImpl checks for the kind of n.sons[2] instead of n.sons[2].typ.kind.

Good catch, sometimes I can't read :)

**Comment by Araq** [comment]
Unrelated test case failure. Merging anyway.

**Pull request merged**
