### PR TITLE
help our poor CI; don't run CI on other branches for push

### PR DESCRIPTION
**Pull request by ringabout**
only trigger CI when pushing to the devel branch

### CODE REVIEW

**Comment by Varriount** [comment]
Will this disable CI testing for pull requests?

**Comment by ringabout** [comment]
> Will this disable CI testing for pull requests?

I don't think so. It only disables pushing to other branches.

**Review by Varriount — APPROVED** [review]

**Comment by metagn** [comment]
Should `version-1-0`, `version-1-2`, `version-1-4`, `version-1-6` etc be added to this as well?

**Comment by ringabout** [comment]
Yeah, seems so.

**Pull request merged**
