### PR TITLE
Add bufSize to newFileStream

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by bluenote10** [comment]
While you are at it, it would be nice to document in system.nim what the `bufSize = -1` actually means and add a link here :).

**Comment by data-man** [comment]
Yes, I also wonder what the bufSize = -1 actually means in the open proc. Since it is not documented, I left it as is. :)
But after some study sysio.nim, I think bufSize = -1 means unbuffered reading.

**Comment by bluenote10** [comment]
I also had a quick at [how](https://github.com/nim-lang/Nim/blob/8bdcade1a08306ccf17c719838a97427a43a112c/lib/system/sysio.nim#L349-L352) it is implemented. Note: Not sure why it has an `elif` and doesn't just use `bufSize >= 0` in the if => change?

I'm not a C expert, but not calling `setvbuf` probably means that the default buffer size applies ([Q/A on SO](https://stackoverflow.com/questions/28311201/buffer-size-in-file-i-o)). So the docs could say something like: _A `bufSize >= 0` will set the buffer size explicitly (e.g. `setvbuf` for the C backend), negative numbers result in the system's default buffer size_.

**Comment by Araq** [comment]
-1 means "use default buffer size"
0 means "unbuffered"

**Comment by data-man** [comment]
@Araq 
Thanks for the explanation!

But my English is not so good to fix the documentation.
It would be nice if someone else can do PRs with the explanations to the documentation.

**Pull request merged**
