### PR TITLE
fixes #11474

### LINKED ISSUE #11474: Case does not check all cases.
```nim
proc case_test(): string = 
  case "1":
  of "": return "empty"
  of "a": return "aye"
  of "b": return "bee"

echo (case_test())
```

Given this program, I'm expecting the exhaustiveness checker to complain and *not* compile. But it compiles, returns an empty string, and a 0 exit code.

### Additional Information
```
$ nim -v
Nim Compiler Version 0.20.0
```

### PR DESCRIPTION
**Pull request by Araq**

### CODE REVIEW

**Comment by Araq** [comment]
Note: wrong commit message.

**Comment by timotheecour** [comment]
=> https://github.com/nim-lang/Nim/issues/11773

**Comment by krux02** [comment]
I have to support the criticism of @zah here. 

- no documentation
- no specification
- no tests for error messages
- no review process (did we ever even consider if using the [] operator here could introduce ambiguities in the Nim grammar?)

Introducing new features into Nim like this can really Hurt the language. Please revert this commit and make a proper RFC for it with a specification of the behavior. And then the PR must contain tests for that ensure the misuses of unref will trigger proper error messages, instead of doing undefined behavior.

**Comment by dom96** [comment]
No need to revert it, but discussion should be had, I agree with @krux02 and @zah on that.

**Comment by Araq** [comment]
> did we ever even consider if using the [] operator here could introduce ambiguities in the Nim grammar?

How could it? The parser was left untouched. But I completely agree with all your other points.

**Comment by krux02** [comment]
@Araq since this PR got removed again, I think it is not that relevant anymore but

> How could it? The parser was left untouched. But I completely agree with all your other points.

An `nkBracketExpr` on a type is usually a generic invocation. That is the ambiguity I am talking about. And my point is not if it is ambiguous, but that we should at least have a review process to see if there could be an ambiguity.

**Pull request merged**
