### PR TITLE
added isAbsolute to uri.nim

### PR DESCRIPTION
**Pull request by enthus1ast**

### CODE REVIEW

**Comment by Araq** [comment]
@dom96 looks good to me

**Comment by trustable-code** [comment]
I think the name is ambiguous. In HTML/URLs "relative" usually means, that a linked URL is relative to the URL of the current page. Your function checks, if the URL contains a protocol.
Relative example:  
Absolute example:

**Comment by enthus1ast** [comment]
@trustable-code `` is relative, cause it lacks information to retrieve a 
resource. An absolute url contains every information to retreive resource.
It is an absolut **path**, though.

**Comment by dom96** [comment]
Nice! Please also add a test for "protocol-relative absolutely URLs" e.g. ``//domain.com/img/logo.png`` (it should be considered an absolute URL).

**Comment by dom96** [comment]
or maybe I'm wrong and it is actually a relative URL. There seems to be some contradiction about this: http://stackoverflow.com/a/19709846/492186 and http://stackoverflow.com/a/27034171/492186.

**Comment by enthus1ast** [comment]
´//´ at (least in http context?) means first try https then try http. 
so this means we have in fact 2 urls:
```
https://domain.com/img/logo.png
http://domain.com/img/logo.png
```
both would be absolute.
but
https://www.paulirish.com/2010/the-protocol-relative-url/ stated that this is an 'anti pattern'

I think about it this way: 
it is **relative** cause it involves another step (first try https, then try http)
to get the actual (the absolute) location of an resource.

**Comment by dom96** [comment]
Perfect thanks!

**Pull request merged**
