### PR TITLE
 fix #16025 repr now consistent: does not insert trailing newline

### LINKED ISSUE #16025: `repr` inserts a spurious newline at RT (unlike in VM)
repr inserts a spurious newline at RT (unlike in VM)

### Example
```nim
when true:
  const a = cast[pointer](nil)
  echo a.repr
  static: echo a.repr
```

### Current Output
CT:nil
RT:nil\n

### Expected Output
CT:nil
RT:nil

### Additional Information
devel 1.5.1 632af8afad92594da050a5f7fd784ea111c3cc54

### PR DESCRIPTION
**Pull request by timotheecour**
fix #16025

## before PR:
repr was very inconsistent (and not documented) wrt whether a trailing newline was inserted:
* no trailing newline for
var openarray
sets
array or seq in vm backend but not c,js backend (except for `--gc:arc`)

* trailing newline for:
array or seq in c, js backend (but not vm), but not on --gc:arc...

and other random rules

## after PR:
no trailing newline
EDITI: I've added `-d:nimLegacyReprWithNewline` to allow users to revert to previous behavior

### CODE REVIEW

**Comment by Araq** [comment]
This will probably break somebody's test suite, it's a bad idea. Instead use ``strip repr x`` if you need it so badly. But why would you, it's for debugging only. You can argue that ``--gc:arc`` should also produce the newline though.

**Comment by timotheecour** [comment]
PTAL

> This will probably break somebody's test suite

[EDIT]
I've added the usual `when defined(nimTransition16034)` and mentioned it in changelog + docs of `repr`. The behavior before PR is simply madness and impossible to justify (try explaining this as a set of rules ...):
* inconsistent: depends on vm vs rt
* inconsistent: depends on sets vs arrays
* inconsistent: depends on arrays vs openarrays
* inconsistent: depends on --gc:arc vs regular gc
* inconsistent with macros.repr (no newline for macros.repr) [1]
* inconsistent with `$` (no newline)
* inconsistent with repr's own docs (`echo repr(i) # => 0x1055ed050[1, 2, 3, 4, 5]`)

> You can argue that --gc:arc should also produce the newline though.

that would equally break debugging code in your argument, but most importantly would still be inconsistent (with $, macros.repr, vm, and other cases mentioned above) and go in the wrong direction.

my PR makes everything consistent and simple (repr self consistent and consistent with $ and macros.repr); `echo foo.repr` would also not insert an arbitrary empty newline in some cases.

`-d:nimTransition16034` should remove any remaining concerns.

[1] macros.repr doesn't add newline
```nim
import macros
macro deb(a): untyped = newLit(a.repr)
doAssert deb("abc") == "\"abc\""
```

**Comment by Araq** [comment]
> macros.repr doesn't add newline

macros.repr has nothing to do with ``repr``, it's just some name that got re-used by me for unknown reasons.

``nimTransition16034`` is a meaningless name, how about ``nimReprWithNewline`` instead. Also, let's see what others think.

**Comment by PMunch** [comment]
It's these kinds of inconsistencies that makes Nim feel a bit unpolished/unfinished. The overhead for people to fix their testsuites should be very minimal with this so I think we should go ahead with it.

**Comment by narimiran** [comment]
> `nimTransition16034` is a meaningless name

+1, together with that `nimHasWorkaround12345` (can't be bothered to find the correct number)

**Comment by timotheecour** [comment]
PTAL, renamed to `-d:nimLegacyReprWithNewline` instead of `-d:nimReprWithNewline` to make it obvious (and greppable using `nimLegacy` prefix for all future such cases) this is a legacy flag, consistently with existing `--legacy` flag:
```
--legacy:allowSemcheckedAstModification|checkUnsignedConversions
                            enable obsolete/legacy language feature
```

(and legacy is shorter to type than transition)

**Pull request merged**
