### PR TITLE
Remove finish.exe UI

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Remove Aporia Downloader GUI, stdlib no longer has the GUI module anyways.
- I can not find anything anywhere depending on that code, can be revived as nimble package if needed.

### CODE REVIEW

**Comment by Araq** [comment]
That's not an Aporia downloader! That's a UI for finish.exe, beginning of a decent installer for Nim. But we can remove it anyway.

**Comment by juancarlospaco** [comment]
@Araq Feel free to close if you think is better, my `finish.exe` used terminal when I tried on Windows. Theres niminst too.

**Comment by dom96** [comment]
Fixed that for you :)

**Comment by juancarlospaco** [comment]
Sorry about the title, I forgot to change it. :(

**Comment by Araq** [comment]
I'm happier with this code being around.

**Comment by juancarlospaco** [comment]
@Araq 
About reviving it, we removed all GUI modules from stdlib sadly,
if 1 GUI module can be added to stdlib, then it can be revived, maybe bring back IUP ?.

**Comment by Araq** [comment]
It used my "ui" lib, not IUP and there is no need to bring it back, koch could install dependencies for it. The biggest problem is that it's still not a "real" installer, we need some .exe packing tech for that.

**Comment by juancarlospaco** [comment]
@Araq 
We need ZIP back on stdlib then, or you want to just use `staticRead` ?, or you want to add more dependencies for that?.

**Comment by juancarlospaco** [comment]
Comparing libui vs iup, giving libui advantage, still iup wins for several reasons,
not to mention the readme explicitly saying is kinda broken, even if libui was perfectly working iup has lots of features not present on libui.

**Comment by timotheecour** [comment]
@juancarlospaco by `koch could install dependencies for it` i think he means this:
extending `./koch installdeps` to install further dependencies, which doesn't require them to be in stdlib or nim repo.

**Comment by Araq** [comment]
> We need ZIP back on stdlib then, or you want to just use staticRead ?, or you want to add more dependencies for that?.

There are tools I started to develop that we need but we should all spend our time elsewhere.

**Pull request closed without merging**
