### PR TITLE
deprecate programResult, avoid exposing in standalone mode

### PR DESCRIPTION
**Pull request by arnetheduck**

### CODE REVIEW

**Comment by arnetheduck** [comment]
Ideally, `unittest` would be updated not to do this, but there's no simple way to hook into "all tests run" given how `unittest` runs tests imperatively..
ping @zah

**Comment by zah** [comment]
What's the point of deprecating `programResult`?

**Comment by arnetheduck** [comment]
it leaves a writable, non-optional global lying around in the binary (cruft) with unclear and difficult semantics that's largely dependent on the C library startup procedure.. it will be hard to support in a stand-alone future that has less interaction with C, and is already hard to support for standalone targets like wasm, limiting its usefulness

**Comment by zah** [comment]
So, what's the plan for the `unittest` module? It still uses it.

**Comment by krux02** [comment]
@zah, I guess, refactor unittest to not use it anymore.

**Comment by zah** [comment]
I see two possible ways to refactor `unittest`:

1) Introduce a new API that explicitly runs the tests:

``` nim
import
  unittest, tests_a, tests_b

suite "foo":
  test "bar":
    check ...

quit runTests()
```

2) Introduce another API (probably a bit less familiar to users) that gives access to an equivalent variable managed by the `unittest` module:

```nim
import
  unittest, tests_a, tests_b

suite "foo":
  test "bar":
    check ...

quit unittest.osResult
```

I'm not sure `programResult` is problematic enough to justify breaking the existing tests and asking the users to switch to such a less convenient API.

**Comment by Araq** [comment]
Why not simply insert an ``if errorCount > 0: quit(1)`` at the end of a ``suite``? This way other suites would not run but also at least the ``suite`` has a purpose then.

**Comment by zah** [comment]
It's quite common to have tests outside of any suite. Well, you can treat them as suites and stop at the first failure, but such a policy is not very typical for a testing framework (usually, it's an option).

**Comment by arnetheduck** [comment]
I guess that's a general issue with the unittest lib, that it runs the tests eagerly / without a global view of all tests, and `programResult` is a bit of a hack to work around this limitation by keeping this feature in the compiler for return code (only) - if instead collected them and was able to run them after the full set of suites/tests are known, it would make a lot of features like this easier (progress bars, smart parallellization, "global" reporting etc

**Comment by krux02** [comment]
@zah You can use ``addQuitProc``.

```nim
var unittestResult = 0

proc unittestFinalizer(): void {.noconv.} =
  quit(unittestResult)

addQuitProc(unittestFinalizer)
```

I tested it for js and it seems like it doesn't work yet. But that seems to be a simple fix, as the following example works: 

```js
function unittestFinalize() {
  console.log("myunittestfinalizer");
  process.exit(0);
}

[`exit`, `SIGINT`, `SIGUSR1`, `SIGUSR2`, `uncaughtException`, `SIGTERM`].forEach((eventType) => {
  process.on(eventType, unittestFinalize);
})

process.exit(1);
```

**Comment by bluenote10** [comment]
I think it applies to all proposed solutions, but just to point it out: It would be nice to go for a solution that allows to use the unittest module for compile-time procs / macros as well. So far this was blocked by `programResult` not being available in a `static` block. I sometimes lost time (and made mistakes) re-writing minimalistic test suites for compile time stuff.

**Comment by krux02** [comment]
Well a solution that works without any magic is a unittest module that just quits on error directly. That works at compile time, on runtime, on javascript template. And for 90% of the time it is exactly what you need. Then when you actually want to continue the program when a unittest failed, then an Unittest alias that just returns the testing status as a value would be pretty easy to provide.

**Comment by Araq** [comment]
``addQuitProc`` is a very nice solution that I didn't consider. It would be nice to port it to JS.

**Comment by arnetheduck** [comment]
you can't use `addQuitProc` as currently implemented - using `exit` from within `atexit` is undefined in C: http://man7.org/linux/man-pages/man3/atexit.3.html#NOTES

**Comment by Araq** [comment]
Bah that's nasty, wasn't aware.

**Pull request merged**
