### PR TITLE
integers and floats constants use BitTable in VM; 10% performance boost on average nimscript programs

### PR DESCRIPTION
**Pull request by ringabout**
Both VM and nimscript benefits from this change.

fixes https://forum.nim-lang.org/t/8003

```nim
import std/[vmutils, sequtils]

when true:
  import macros
  proc identity[T](a: T): T = a
  macro genData(n: static int): untyped =
    result = newNimNode(nnkBracket)
    for i in 0..<n: result.add newLit(i + high(int32))
  const n = 800000 # every time this doubles, compilation time quadruples (ie quadratic complexity)
#   const arr = genData(n)


  proc fn() =
    #  vmtrace(true)
    #  let arr = arr # would be fast with this
    #  vmtrace(false)
    let arr = genData(n)
    for i in 0..<3:
      echo i
      for ai in arr: discard # slow! ditto with `items(arr)`
      # for ai in identity(arr): discard # would be fast!
  static: fn()
```

It takes the old implementation forever to execute the program. But for the BiTable implement, it works like a breeze.

```
echo "hello, World
```

For a simple program like above, it is embarrassing for the Nim compiler to generate inefficient code like `genLiteral`, `sameConstant`, which consumes 10% of the execution time.

image

After this PR

image

The more constants the program uses, the more speedups we shall see.

### CODE REVIEW

**Comment by ringabout** [comment]
Btw, for simple programs, parsing might consume to to 20% of the execution time. In the future, nimscript should generate byte code caches to solve this problem.

image

**Comment by ringabout** [comment]
It will be better to have a dedicated `ldConstFast` opcode, which uses `genType` to preserve type infos. But `genType` seems to be quite heavy because of `PType`. Ideally, there should be a lightweight `VMType`, which uses ids to index the real type.

**Comment by ringabout** [comment]
I have learned a lot this weekend. So I changed my mind. It would be better to use a plain table to cache values (int/float/string) loop up. Then there is no need for extra opcodes.

**Comment by Araq** [comment]
So what is the status of this?

**Pull request closed without merging**
