### PR TITLE
fix #17201 sqrt does not work with integers literals

### LINKED ISSUE #17201: The sqrt(2) does not work with integers literals.
Function `sqrt` does not work with integers literals.

### Example

https://play.nim-lang.org/#ix=2RdE
```nim
import math
echo sqrt(2)
```

### Current Output

```
/usercode/in.nim(2, 10) Error: ambiguous call; 
both math.sqrt(x: float32) [declared in /playground/nim/lib/pure/math.nim(256, 8)] 
and math.sqrt(x: float64) [declared in /playground/nim/lib/pure/math.nim(257, 8)] 
match for: (int literal(2))
```

### Expected Output

It just works like `sqrt(2.0)`.

### Possible Solution

Two `math.sqrt` are defined. One for `float32` and one for `float64`. For some reason it can't pick which one it should do when you give it an integer. One could create a 3rd that deals with some integer and converts it to float64. Or maybe do some thing with converters?

### PR DESCRIPTION
**Pull request by bung87**
fix #17201

### CODE REVIEW

**Comment by ringabout** [comment]
Notes: it doesn't fix the root cause of https://github.com/nim-lang/Nim/issues/17201

```nim
proc fn(a: float32) = discard
proc fn(a: float) = discard
fn(2)
```
It is still broken.

**Comment by bung87** [comment]
> Notes: it doesn't fix the root cause of #17201
> 
> ```nim
> proc fn(a: float32) = discard
> proc fn(a: float) = discard
> fn(2)
> ```
> 
> It is still broken.

that's another problem, see https://play.nim-lang.org/#ix=4fXG

**Comment by Varriount** [comment]
How feasible is it to fix the root cause instead?

**Comment by bung87** [comment]
well , https://github.com/nim-lang/Nim/pull/20852 is fix by change the int - float family conversation, here is match the param directly with explictly conversation. the idea is take less steps as possible like other procs in stdlib.  
also https://github.com/nim-lang/Nim/pull/20852 is a good idea, from my experience of making patch of targeting int width https://github.com/nim-lang/Nim/pull/20829

**Comment by metagn** [comment]
> Notes: it doesn't fix the root cause of https://github.com/nim-lang/Nim/issues/17201

The way I see it, this needs an RFC for int literals to match `float` better than `float32` (and maybe same for `uint`). #20852 is an example implementation but I am neutral about it so I closed it for now

**Comment by Araq** [comment]
There is nothing to fix.

**Comment by bung87** [comment]
but this is support sqrt with integer argument that doesn't rely on implict conversation.

**Pull request closed without merging**
