### PR TITLE
Try to let memTracker compile

### PR DESCRIPTION
**Pull request by cdunn2001**
`-d:memTracker` does not compile right now.

### CODE REVIEW

**Comment by Araq** [comment]
Er why doesn't appveyor test this PR?!

**Comment by cdunn2001** [comment]
No idea. But I had to submit this about 3 times this morning. GitHub was having trouble. I'll rebase and push. Maybe AppVeyor will start then...

**Comment by cdunn2001** [comment]
```
tests\testament\tester.exe "--nim:compiler\nim " cat fragmentation
FAIL: tfragment_alloc.nim C
Test "tests\fragmentation\tfragment_alloc.nim" in category "fragmentation"
Failure: reExitcodesDiffer
Expected:
exitcode: 0
Gotten:
exitcode: 1
Output:
out of memory
SKIP: tfragment_gc.nim C
FAILURE! total: 2 passed: 0 skipped: 1
```
I don't understand the failure, so I'm testing *without* my change.

**Comment by cdunn2001** [comment]
Yeah, same failure without my change. AppVeyor is already broken.

**Comment by Araq** [comment]
Yeah, we know this test is flaky.

**Comment by slyshykO** [comment]
Connected issue #6363

**Pull request merged**
