### PR TITLE
Backport nimble support

### PR DESCRIPTION
**Pull request by yyoncho**

### CODE REVIEW

**Comment by ringabout** [comment]
Pre-existing,

The CI of version-1-6 has been broken for a few days https://github.com/nim-lang/Nim/actions/runs/4057361036/jobs/6983016699

- disable bump in the important packages
- fix chronicles somehow

**Comment by yyoncho** [comment]
@ringabout thank you! Then I guess this backport is safe to go? (I don't think that there is anything in the CI that will be affected by this change because there are no projects using nim as a nimble dependency).

**Comment by ringabout** [comment]
Sure

**Review by ringabout — APPROVED** [review]

**Comment by yyoncho** [comment]
Closing, backported by @narimiran

**Comment by ringabout** [comment]
Hello @yyoncho do you happen to know whether it is related to the nimble file changes? The nightlies has been failing for four days on the version-1-6 branch.

https://github.com/nim-lang/nightlies/actions/runs/4148826770/jobs/7177211232

> Warning:  Source file doesn't exist: compiler.nimble

**Comment by ringabout** [comment]
> Hello @yyoncho do you happen to know whether it is related to the nimble file changes? The nightlies has been failing for four days on the version-1-6 branch.
> 
> https://github.com/nim-lang/nightlies/actions/runs/4148826770/jobs/7177211232
> 
> > Warning:  Source file doesn't exist: compiler.nimble

**Comment by yyoncho** [comment]
@ringabout I will take a look.

**Comment by yyoncho** [comment]
@ringabout here it is a potential fix: https://github.com/yyoncho/Nim/commit/06632f8169d4b64e5c9ca20e266073f6d0ad3dd8 

(I alternatively, I can do the fix more defensively here https://github.com/yyoncho/Nim/blob/version-1-6/tools/niminst/install.nimf#L120 )

I am not quite sure how to proceed with the testing.

**Comment by ringabout** [comment]
A pull request will be appreciated. We can merge it and see its effect.

**Comment by yyoncho** [comment]
> A pull request will be appreciated. We can merge it and see its effect.

@ringabout PR at https://github.com/nim-lang/Nim/pull/21369 . If it doesn't work, I can do the change only regarding compiler.nimble/nim.nimble.

**Comment by ringabout** [comment]
Thank you! Let's give it a try.

**Pull request closed without merging**
