### PR TITLE
Fix nightlies timeout / recursive winrelease

### PR DESCRIPTION
**Pull request by genotrance**
Fixed issue - https://github.com/nim-lang/nightlies/issues/17

### CODE REVIEW

**Comment by genotrance** [comment]
Was waiting for your input since you might have already gone through this.

How about:

```nim
let kochExe = getAppDir() / "koch"
```

This way it will work for both koch and winrelease.

**Comment by Araq** [comment]
@timotheecour pushed your suggestion.

**Comment by genotrance** [comment]
Araq: this is still broken - needs to be:

```nim
let kochExe =
  when isMainModule:
    os.getAppFilename()
  else:
    getAppDir() / "koch"

proc kochExec*(cmd: string) =
  exec kochExe.quoteShell & " " & cmd
```

**Comment by timotheecour** [comment]
@genotrance u need to rebase against latest devel, there are conflicts shown

**Pull request closed without merging**
