### PR TITLE
fixes #7842 if no uri.scheme specified raise ValueError with hint

### LINKED ISSUE #7842: HttpClient: requesting URL with no scheme fails
```nim
import httpclient

var client = newHttpClient()
client.getContent("google.com").echo
```

```
a10.nim(4)               a10
httpclient.nim(1237)     getContent
httpclient.nim(1226)     get
httpclient.nim(1218)     request
httpclient.nim(1195)     request
httpclient.nim(1164)     requestAux
httpclient.nim(1106)     newConnection
net.nim(1606)            dial
oserr.nim(66)            raiseOSError
Error: unhandled exception: Connection refused [OSError]
```

### PR DESCRIPTION
**Pull request by enthus1ast**
This fixes only the `newHttpClient` based version. 
Should i also fix the deprecated?

Signed-off-by: enthus1ast <david@code0.xyz>

### CODE REVIEW

**Comment by dom96** [comment]
Wouldn't it be better to assume http?

**Comment by enthus1ast** [comment]
i would not assume something. When we really want to then we should assume https.
https://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by dom96** [comment]
Every site that supports https will also support http, the same is not true the other way around. Because of that it's better to assume http.

**Comment by Clyybber** [comment]
I would rather not assume http by default because it is not ssl-secured. I think raising an exception is perfectly adequate here.

**Comment by Varriount** [comment]
Considering the ubiquity of https, either attempt https then http, or raise an error

**Comment by dom96** [comment]
I disagree. If I type ``localhost:5000`` into my browser it doesn't assume https. If I run `curl localhost:5000` it also doesn't assume https.

> Considering the ubiquity of https, either attempt https then http, or raise an error

http is far more ubiquitous than https: https://www.ssllabs.com/ssl-pulse/. ~60% of sites support https. 100% support http.

**Comment by enthus1ast** [comment]
I also can understand dom96.
Since we speak of an "http"client it _may_ be ok to assume http if its missing.

But image this case then:
  If you know what you are doing you specify the scheme anyway. 
  You want to be warned about your mistake.
  
  when you don't know what you do (or you just forget or have a bug in code or the list of urls is not homogen) 
  and try to log into an api and forget the https then your credentials will be send in cleartext.

So i clearly vote for raising an exception.

**Comment by genotrance** [comment]
This is an api which will mostly receive urls at runtime, not hard coded strings. Totally killing the app with an assert isn't appropriate. 

Raising an exception seems most sensible since it is documented and can be handled in code. Assuming http in this day and age isn't ideal.

**Pull request merged**
