### PR TITLE
fixes regression #20746; remove string copies for ORC booted compiler

### LINKED ISSUE #20746: multiReplace / replace taking a long time to execute in VM since commit: ae050b05e9ce6f4e356c46de8722724a2f706e18
### What happened?

In NimForUE, we're running macros that do string replacements.  Since ae050b05e9ce6f4e356c46de8722724a2f706e18 the sample code below takes many minutes to finish executing. In prior commits or example v1.6.8 the following code would take a couple seconds to execute, and if fully compiled the resulting executable finishes instantly:
```nim
#nim.cfg:
--mm:orc # is orc the default on this commit? this doesn't seem necessary, but it's what we use to be clear.
```
```nim
#main.nim
import std/strutils
const source = staticRead("importedengine.txt")

static:
  echo "multiReplace - takes a long time in VM since: ae050b05e9ce6f4e356c46de8722724a2f706e18"
  let res = source.multiReplace(
              ("{.inject.}", ""),
              ("{.inject, ", "{."),
              ("<", "["),
              (">", "]"), #Changes Gen. Some types has two levels of inherantce in cpp, that we dont really need to support
              ("::Type", ""), #Enum namespaces EEnumName::Type
              ("::Mode", ""), #Enum namespaces EEnumName::TypeB
              ("::", "."), #Enum namespace
              ("__DelegateSignature", ""))
  writeFile("replaced_importedengine.nim", res)
  echo "finished"
```
Attached is the sample file we produce for the replacement. [importedengine.txt](https://github.com/nim-lang/Nim/files/9933180/importedengine.txt) I renamed the extension to `.txt` because of github.

### Nim Version

PS C:\Nim> nim --version
Nim Compiler Version 1.7.3 [Windows: amd64]
Compiled at 2022-11-03
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: ae050b05e9ce6f4e356c46de8722724a2f706e18
active boot switches: -d:release

### Current Standard Output Logs

```shell
Compiling with `nim c main`, the output prints:

multiReplace - takes a long time in VM since: ae050b05e9ce6f4e356c46de8722724a2f706e18

and can take many minutes to finish on my Ryzen 9 5950x. I Ctrl+C to kill it.
```

### Expected Standard Output Logs

```shell
The output should say `finished` after a couple seconds.
```

### Possible Solution

_No response_

### Additional Information

The problem doesn't happen when not in the VM. If you remove the `static` block, compile and run the executable, it finishes instantly

### PR DESCRIPTION
**Pull request by ringabout**
fixes #20746

In this case, ORC does nothing wrong. It is the right thing it does that incurs this penalty. `refc` booted compiler works by accident, taking advantage of this [undefined behavior](https://github.com/nim-lang/Nim/issues/16312). It “worked” before because `let s = regs[rb].node.strVal` doesn't copy the string in `refc`. Instead, it points to the original string. There seems to be an issue with string copying in ORC, but it isn't related to this fix.

### CODE REVIEW

**Comment by ringabout** [comment]
It is a bug fix which shouldn't introduce unrelated changes. The following-up PR will tackle similar cases.

**Comment by bung87** [comment]
pls change the file extension to txt, or maybe dont need test, since it's more like a benchmark on CI.

**Comment by ringabout** [comment]
It has the correct prefix. I fail to see there is any problem.

**Comment by bung87** [comment]
Atleast I dont wanna see 20k lines nim source file in code base just for testing, I guess somebody as well.

**Comment by ringabout** [comment]
> maybe dont need test, since it's more like a benchmark on CI.

It is a serious performance regression for edge cases.

> Atleast I dont wanna see 20k lines nim source file in code base just for testing, I guess somebody as well.

It is not a good reason. You don't need to read the file starting with `m` prefix in the `/tests` directory. But I will change the file extension because sometimes we use search to keep tests update with changes. Using `.nim` extension can add a wee noise.

**Comment by metagn** [comment]
To be fair it's not valid Nim, there are things like:

```nim
EMeshFeatureImportance::Type textureImportance*:
```

**Comment by Araq** [comment]
Please don't add a 20K test file. If it means that the bugfix remains untested, so be it.

**Comment by bung87** [comment]
I tried to simulate the issue case,<s> but fails to see much perfomance difference</s> , I see, I forget that --mm should put after koch temp, now 2s vs 20s on my pc.
```nim
# flag:  --benchmarkVM
import std/[strutils,times]

const l = 300_000

const s = static:
  var a = newStringOfCap(l)
  var i  = 0
  var d = newStringOfCap(HexDigits.len)
  for c in HexDigits:
    d.add c
  while i < l:
    a.add d
    i.inc HexDigits.len
  a

static:
  
  var t0 = cpuTime()
  discard s.multiReplace(
    ("ab", "cd"),
    ("ef","gh"),
    ("0123","vbnm"),
    ("4567", "uiop"),
    ("89", "xy"),
    ("_","#")
    )
  echo "-----CPU time [s] ", cpuTime() - t0 , "-------"
```

**Comment by ringabout** [comment]
You can try my test case with the devel branch which compiles for more than 100 secs. With my fix, it compiles within 5 secs.

**Pull request merged**
