### PR TITLE
[WIP] allow parsing of JSON at compile time

### PR DESCRIPTION
**Pull request by Vindaar**
This PR prototypes support for parsing JSON at compile time as a `.compileTime.` variable. 
**Note:** it explicitly does *not* support storing a parsed `JsonNode` in a `const` and using it at runtime, since `JsonNode` is a ref type.

It introduces `staticParseJson` and `staticParseFile` (please provide better names :P) for this, so that
```nim
var jData {.compileTime.} = staticParseJson("{"name" : "Araq"}")
static:
  doAssert jData["name"].getStr == "Araq"
```
is possible. 

Regarding the implementation, I just cleaned up my hacky code somewhat I mentioned on IRC. If we consider merging this, I'm happy improve it. 
I wrote it some time ago to try to check some JSON at compile time. 

Related discussion on IRC yesterday: https://irclogs.nim-lang.org/10-02-2019.html#14:30:29

### CODE REVIEW

**Comment by yglukhov** [comment]
Why introduce a new proc instead of making `parseJson` work in compile time?

**Comment by mratsim** [comment]
Nim supports static overloading:

```Nim


proc myProc(n: int): int =
  10 * n

proc myProc(n: static int): int =
  100 * n


const x = myProc(5)
let y = myProc(5)

echo x # 500
echo y # 500

echo myProc(x) # 50000
echo myProc(y) # 5000
```

**Comment by yglukhov** [comment]
And nim supports `when nimvm`:
```nim
proc myProc() =
  when nimvm:
    echo "I'm running in CT"
  else:
    echo "I'm running in RT"

**Comment by Vindaar** [comment]
> And nim supports `when nimvm`:

Originally the code was even more hacky and I just replaced stuff. But while cleaning it up earlier today I thought there *had* to be something like this. I just didn't know what it was called. So, thanks a lot! Will incorporate it!

**Comment by Vindaar** [comment]
Sorry, I was busy the last week. Just got back to this and while trying to make use of `nimvm` I quickly became aware of its limitations. As also stated in the manual: 
https://nim-lang.github.io/Nim/manual.html#statements-and-expressions-when-nimvm-statement
- the expression *must* be `when nimvm`, so I can't do 
  ```nim
  when defined(js) or nimvm:
  ```
  in the code.
- no `elif` allowed, so the `js` part cannot be its own branch either.
- cannot define symbols in the block, which are used outside, which means I can't define `BaseLexer` and `JsonParser` once for the VM and once for runtime, both with the same name, nor do something like
  ```nim
  type 
    BaseLexer = object
      when nimvm:
        input: string 
      else:
        input: Stream
  ```
  either. 

Overloading the `parseJson` proc is fine at least (there `when nimvm` can be used) and also both `lexbase.close` and `parsejson.open` can be merged.

I thought about adding a complete `StringStream` for the VM, but that already fails because of the necessary up conversion from e.g.
```nim
proc ssCtRead(s: Stream, buffer: pointer, bufLen: int): int =
  var s = StringStream(s) #  <---- fails in vmgen
```
but that would be necessary, since the `Stream` type needs such a signature for the `impl` procs.

#### Possible solutions
- drop this
- live with `RT` and `CT` distinction of the types
- add additional fields to the `RT` types to accommodate the CT requirements
  
Anything I'm missing and preferences?

**Comment by GULPF** [comment]
I don't think it's a good idea to have `static T` overloads with completely different semantics than the base proc. If I write `parseFile("/some/absolute/path")` I definitely don't expect it to read and parse the file at compile time (this would be a breaking change as well).

**Comment by Vindaar** [comment]
> I don't think it's a good idea to have `static T` overloads with completely different semantics than the base proc. If I write `parseFile("/some/absolute/path")` I definitely don't expect it to read and parse the file at compile time (this would be a breaking change as well).

Oops, that was simply a mistake on my part. `parseFile` was only supposed to read the file at CT if called in a static context.

**Comment by krux02** [comment]
Generally I like it when you manage to get the json parser to work at compile time. What I don't like is that you introduce a lot of code duplication and many changes to the signature of procedures, just to make the fild ``input`` a ``string`` instead of a ``Stream``.

Wouldn't it be better to just support the ``Stream`` type at compile time? I don't know what Araq thinks about that though since I can remember there was some resistence to support ``File``, ``stdout``, etc at compile time (dependencey if Stream).

**Comment by Vindaar** [comment]
Ok, apparently I don't understand what `when nimvm` really does, because the current code for `parseFile` with a `static string` always evaluates the VM branch. Maybe only in addition though? Not sure.

> Generally I like it when you manage to get the json parser to work at compile time. What I don't like is that you introduce a lot of code duplication and many changes to the signature of procedures, just to make the fild `input` a `string` instead of a `Stream`.

Yes, totally agree.

> Wouldn't it be better to just support the `Stream` type at compile time? I don't know what Araq thinks about that though since I can remember there was some resistence to support `File`, `stdout`, etc at compile time (dependencey if Stream).

That would certainly be more elegant. But since it's not that simple, it's beyond me at the moment.

**Comment by ryukoposting** [comment]
> Wouldn't it be better to just support the `Stream` type at compile time? I don't know what Araq thinks about that though since I can remember there was some resistence to support `File`, `stdout`, etc at compile time (dependencey if Stream).

Sure, `stdout` and `Files` are streams, but there are plenty of other kinds of streams that intuitively should be perfectly valid at compile time (for example, a stream of JSON data generated from a static string). Nim's metaprogramming capabilities are incredibly powerful, but they kind of become a second-class member of the language unless they have support for as much of the standard library as possible.

The other problem I see is how it exposes inner mechanisms of the standard library in a way that's very confusing for a user to debug (see #10733)- the average user doesn't know what parts of the standard library depend on each other, nor should they have to. Obviously, there are some things that simply can't be done in a compile-time execution environment, but JSON parsing? Come on.

My vote doesn't mean much, but count me in the crowd who thinks that code duplication is far less of a sin than gimping a core strength and exposing an inconsistent interface.

**Comment by krux02** [comment]
@ryukoposting I alread posted in the other issue, but I would like to say it again. JSON parsing isn't as important as your might think it is. I actually really discourage you from doing so. JSON is usually used to set some confuguration at runtime. Parsing JSON at compiletime will make it impossible to use a different config at runtime. Kind of defeating the purpose to use a config file in the first place. The alternative is constants:

For example the following json that need to be used at compile time:

```json
{
  "valueA": 123.456
  "valueB": "hello something"
  "someArray": [1,2,3,4,5,6]
}
```

can also be written as:

```nim
const
  valueA = 123.456
  valueB  = "hello something"
  someArray = [1,2,3,4,5,6]
```

Using constants has two advantages, parsing is done by the optimized parsor of the nim language and not by a parser that runs on top of the nim bytecode interpreter, and you are in the programming language nim, meaning you can use nim to compute the configuration.

**Comment by ryukoposting** [comment]
@krux02 JSON is used for a heck of a lot more than "setting some configuration at runtime," firstly. Even if my use case was an outlier, Amazon isn't exactly an outlier worth ignoring. Either way, I think discussion of the specifics of my use case would be more appropriate for the other thread.

**Comment by krux02** [comment]
@ryukoposting you are right. I was just looking into making stream work at compile time, at least the StringStream, but no luck so far. I think your use case might be absolutely valid.

**Comment by ptdel** [comment]
just wanted to chime in and say this would be very cool to see as somebody looking for a chance to adopt Nim at my workplace.  In addition to JSON (or YAML) being used for configuration, it's also employed in IDLs, such as Swagger and RAML.  I believe Go uses code generation to form their SDK methods https://github.com/aws/aws-sdk-go/blob/master/awsmigrate/awsmigrate-renamer/gen/gen.go . Being able to tell my colleagues that Nim macros and templates are ideal for generating API interfaces from IDLs would be a big selling point for adoption.

**Comment by krux02** [comment]
I would like to inform you, that I am working on a different approach for the same goal here: 
https://github.com/nim-lang/Nim/pull/10746

**Comment by Vindaar** [comment]
> I would like to inform you, that I am working on a different approach for the same goal here:
> #10746

Sweet, that looks nice. I didn't think dealing with the object up conversion would be that simple. Will gladly close this PR if yours works out! :)

**Comment by krux02** [comment]
> Sweet, that looks nice. I didn't think dealing with the object up conversion would be that simple. Will gladly close this PR if yours works out! :)

Actually it is called [downcasting](https://en.wikipedia.org/wiki/Downcasting), I have no idea why in the compiler the node kind for that is called ``nkObjUpConv``. And I also didn't expect it to be that simple. I hope I didn't open Pandora's box here.

**Comment by ryukoposting** [comment]
> Actually it is called [downcasting](https://en.wikipedia.org/wiki/Downcasting), I have no idea why in the compiler the node kind for that is called `nkObjUpConv`. And I also didn't expect it to be that simple. I hope I didn't open Pandora's box here. But honestly I don't think so.

It look to me like you're just *adding support for downcasting* to nimvm, not *actually downcasting things* in nimvm, right? Just want to make sure my read-through of the code is correct.

**Comment by krux02** [comment]
@ryukoposting The code that does the downcasting is already implemented it is in streams.nim, I did not write it. Enabling downcasting in the vm is necessary.

**Comment by ryukoposting** [comment]
> @ryukoposting The code that does the downcasting is already implemented it is in streams.nim, I did not write it. Enabling downcasting in the vm is necessary.

Okay, figured as much. It's good to know that this change isn't going to completely blow up the current stream implementation or anything like that.

**Comment by juancarlospaco** [comment]
Feed it this, is designed to break JSON parsings: https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/blns.json
:slightly_smiling_face:

**Comment by krux02** [comment]
Since my branch to address the same problem has been merged, this branch is now redundant. I closing it now.

**Pull request closed without merging**
