### PR TITLE
`std/sysrand` for Windows XP

### PR DESCRIPTION
**Pull request by rockcavera**
`BCryptGenRandom` is not present in Windows XP, but has `CryptGenRandom`.

I believe this can be discussed.

### CODE REVIEW

**Comment by rockcavera** [comment]
The error you reported in "nim-lang.Nim (Windows_amd64_batch1_3 packages)" has to do with this problem here: #19537

As for the problem in "nim-lang.Nim (OSX_amd64_cpp packages)" I have no idea, but I guarantee it has nothing to do with this PR.

**Comment by xflywind** [comment]
Newer Python versions have dropped Win 7 or earlier supports

Ref https://www.python.org/downloads/windows

**Comment by Araq** [comment]
That's quite a lot of code in order to support Windows XP. I don't mind supporting XP if it doesn't take much effort but this seems excessive for an OS that Microsoft ended all support for on April 8th, 2014.

**Comment by wqweto** [comment]
IMO easiest way to support XP is to use [`RtlGenRandom`](https://docs.microsoft.com/en-us/windows/win32/api/ntsecapi/nf-ntsecapi-rtlgenrandom) in first place (that is `SystemFunction036` export of `advapi32.dll`).

It does not need a handle being opened/closed like both current `BCryptGenRandom` and `CryptGenRandom` so an XP supporting implementation using `RtlGenRandom` might actually reduce boilerplate code.

**Comment by rockcavera** [comment]
> IMO easiest way to support XP is to use [`RtlGenRandom`](https://docs.microsoft.com/en-us/windows/win32/api/ntsecapi/nf-ntsecapi-rtlgenrandom) in first place (that is `SystemFunction036` export of `advapi32.dll`).
> 
> It does not need a handle being opened/closed like both current `BCryptGenRandom` and `CryptGenRandom` so an XP supporting implementation using `RtlGenRandom` might actually reduce boilerplate code.

It appears to be the best solution. I researched and it seems to be used quite a lot by other languages and libraries.

https://github.com/golang/go/issues/33542

**Comment by rockcavera** [comment]
@xflywind I wanted to hear from you who added sysrand if there was any discussion about the Windows API and any objections to RtlGenRandom...

**Comment by Varriount** [comment]
Looking at a [related PR elsewhere](https://github.com/rust-random/rand/issues/111), I agree with @wqweto. RtlGenRandom is the way to go here.

**Pull request closed without merging**
