### PR TITLE
Support whileOption, whileNotNil

### PR DESCRIPTION
**Pull request by alehander42**
Yesterday several people in the chat expressed need for something that lets them loop until something is `none` (similar to rust's while let) or until something is `nil`  (@mratsim, crem)

This PR implements a possible solution. I am not sure if it seems nimish and if the functions are placed in the right modules, but if people want something like this, they can discuss it

### CODE REVIEW

**Comment by bluenote10** [comment]
Some thoughts:

- `whileSome` would make more sense to me than `whileOption`, because all elements are options, but the condition is that it is a `Some`.
- Would be good to check that the macro input nodes are a valid `in` expression.

**Comment by stisa** [comment]
I'd rather it be a single general loop construct, something like:
```nim
import macros, options

type C = ref object
  c: int

macro until(cond,node,body:untyped):untyped =
  # Example implementation, just to prove it's possible
  let 
    el = node[1]
    list = node[2]
  result = quote do:
    for `el` in `list`:
      if `cond`(`el`): break
      `body`

var b = @[C(c: 0), nil, C(c: 2)] 

until isnil, a in b:
  echo a.c
# 0

var c = @[some(2), none(int), some(8), some(10)] 

until isNone, a in c:
  echo a
# Some(2)
```
And I agree, the macro should do some checks on what it gets passed

( not sure about the name, maybe `unless` would be more clear? )

As for in which module to put this, I really like the idea of putting these kind of QoL things in a `sugar.nim` module ( I think it was Araq's ?)

**Comment by alehander42** [comment]
@stisa I really like that, but then for `isNone` you get `Some` which is undesirable as all the values are `Some` anyway, that's why I wanted automatic unwrapping too 

otherwise such a `until` construct seems very nice

@bluenote10 I agree with both points

**Comment by mratsim** [comment]
I like the `whileSome`, but the `whileNotNil` seems to be better served by a more generic`takeWhile` proc.

Furthermore it seems strange to have special treatment of nilable types in sequtils.

Lastly crem mentionned that `while (let x = nextObj(); not x.isnil):` is good enough for him. If anything we should add that construct to a cookBook / HowTo.

**Comment by mratsim** [comment]
To be more precise, this is useful in 3 cases:
- nilable types
- Option type
- closure iterators

I am also guilty of keeping a [gist](https://gist.github.com/mratsim/e0c7f2eefb8fa91fb27f0cd9a97cff00) for `while let` ;)
```Nim
proc filter[T](it: (iterator : T), f: proc(x: T): bool): (iterator: T) =
  return iterator(): T =
    while (let x = it(); not finished(it)):
      if f(x):
        yield x
```

My take:
- I like `whileSome` in `options`.
- I don't like the special nil treatment in `sequtils`
   Also the `takeWhile` I proposed above would not cover every use case of whileNotNil --> doSomething

Ideally:
Once `opt` is in core, Rust [`while let` syntactic sugar](https://doc.rust-lang.org/1.14.0/book/if-let.html#while-let) would also be useful. What do you think @dom96, @Araq ?
```Rust
let mut v = vec![1, 3, 5, 7, 11];
while let Some(x) = v.pop() {
    println!("{}", x);
}
```

**Comment by Araq** [comment]
These are all ugly, :-) I thought about ``while let Some(x) = v.pop`` but it doesn't fit Nim's design all that much:

- Conditions are of type ``bool``, not of type "successful match".
- ``opt[T]`` owns the ``T`` so it can introduce yet more copies.
- Nim's flow based typing is more expressive and doesn't have these problems. (It has other problems but it's easier to fix them than introducing more and more foreign concepts into Nim.)

**Comment by dom96** [comment]
Thank you for these suggestions!

> Lastly crem mentionned that `while (let x = nextObj(); not x.isnil):` is good enough for him. If anything we should add that construct to a cookBook / HowTo.

IMO if anything, we should introduce a macro that makes that construct shorter. But that's easier said than done.

Personally, I'm happy with that code.

**Comment by Araq** [comment]
Closing. Reopen once you have a design that is not as ugly. :-)

**Pull request closed without merging**
