### PR TITLE
Fix int literals and range interaction

### PR DESCRIPTION
**Pull request by GULPF**
Both `isConvertibleToRange` in sigmatch and the manual treated `int` as equal to `int literal` which is wrong. This meant that `int` could be implicitly converted to ranges of a smaller integer type.

This PR also allows int literals to be implicitly converted to ranges of unsigned types. This makes sense since int literals can already be converted to the unsigned base types.

Previously ranges of type `int`/`int64`/`uint`/`uint64` where special and any integer type could be implicitly converted to them. I've removed this special casing except for `int` as it caused breakage.

### CODE REVIEW

**Comment by mratsim** [comment]
We have a couple of [range issues](https://github.com/nim-lang/Nim/issues?q=is%3Aopen+is%3Aissue+label%3ARange). Does it fix some of them?

**Comment by narimiran** [comment]
Fails for nimgame2 with `input.nim(931, 11) Error: type mismatch: got <int> but expected 'JoyAxis = range -32768..32767(int16)'`

That's here:
```nim
proc movement*(gi: GeneralInput): int =
  return case gi.kind:
    of giMouse:
      case gi.mouse.kind:
      of mMove:
        case gi.mouse.direction:
        of dirX: mouse.rel.x.int
        of dirY: mouse.rel.y.int
      else: 0
    of giJoystick:
      let id = gi.joystick.guid.getId()
      if id < 0: 0  # no such joystick opened
      else:
        case gi.joystick.kind:
        of jAxis: joyAxis(id, gi.joystick.axis)  # <--- this returns JoyAxis
        of jBall:
          case gi.joystick.ballDirection:         # <--- line 931, these are int
          of dirX: joyBall(id, gi.joystick.ball).x
          of dirY: joyBall(id, gi.joystick.ball).y
        else: 0
    else: 0

```

and `JoyAxis` is defined as:
```nim
type
  JoyAxis* = range[low(int16)..high(int16)]
```

cc @Vladar4

**Comment by mratsim** [comment]
If JoyAxis is meant to be backed by an `int` I think the type definition should be:

```Nim
type JoyAxis* = range[int(low(int16))..int(high(int16))]
```

**Comment by GULPF** [comment]
@mratsim I couldn't find any reported issue that would be fixed by this PR.

**Pull request merged**
