### PR TITLE
Added future module to system

### PR DESCRIPTION
**Pull request by moigagoo**
Based on this proposal http://forum.nim-lang.org/t/2440

### CODE REVIEW

**Comment by Araq** [comment]
Fails with an interesting error:

$ nim e install_nimble.nims
Hint: used config file '/home/travis/build/nim-lang/Nim/config/nim.cfg' [Conf]
lib/core/macros.nim(511, 1) Error: cannot generate VM code for macro dumpTree(s: untyped): untyped

**Comment by moigagoo** [comment]
@Araq That's *so* weird. The error is weird itself, but the other weird thing is that tests do pass on my machine. I mean, I ran them before submitting the PR to make sure nothing breaks.

I'm running the tests with `nim c koch; Koch tests`. Is that correct?

**Comment by Araq** [comment]
> I'm running the tests with nim c koch; Koch tests. Is that correct?

Yes.

**Comment by moigagoo** [comment]
Hm, I just re-ran them, and all seem to pass. Ran the new ones in isolation, still  no issues. Any ideas?

**Comment by moigagoo** [comment]
Definitely need more work, closing for now.

**Comment by dom96** [comment]
I don't think you should do it this way anyway. Just copy and paste the macros into system. The ``future`` module can then be deprecated.

**Comment by moigagoo** [comment]
I agree, and I tried doing it this way as well, but I get the same error. I'll investigate the issue closer when I can and send another, cleaner PR.

**Pull request closed without merging**
