### PR TITLE
Compiler: show compile timestamps

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by data-man** [comment]
WTF, what benefits from reproducible builds? It's stupidly!
It's senseless, because the sources can be compiled by various compilers.

**Comment by dom96** [comment]
Isn't this what this PR was about? https://github.com/nim-lang/Nim/pull/7661

For reproducible builds that env var will be defined and there will be no problems. Reopening because I miss the dates in ``--version`` too.

**Comment by zah** [comment]
Ah, my first impression was that this a comment inserted in every single file. If it affects only the version message of Nim itself, it's more reasonable.

**Comment by data-man** [comment]
I'd even prefer to have more information about all the compilation switches, as it does ```gcc -v```.

**Comment by dom96** [comment]
Right. I'm merging this. I'm 99% sure the PR I linked will fix any issues this might bring. If not, we can revert.

**Comment by yglukhov** [comment]
@data-man, @dom96, tbh I don't understand the user story behind this. Nim binary already embeds git hash from which the timestamp can be derived easily. To simplify it even more, we could embed git timestamp `staticExec("git log -1 --format=%cd")`, which yields the current HEAD time. Apart from that if you need to know build timestamp of nim while you're currently tinkering with it you can rely on the exe file modification date, or ... your own memory ;)

**Comment by data-man** [comment]
@yglukhov 
I use several copies of the compiler, compiled with different options and a simple script to create the link /usr/local/bin/nim
But it's my problems and use case, of course.

**Comment by dom96** [comment]
Sure, I can check the modification time of the file but that really isn't
convenient. A date in version output allows me to figure out how outdated
my devel build is easily.

Git timestamp would actually be better but the git hash isn't always
available, compile date always is.

**Comment by yglukhov** [comment]
@dom96, your use case is only within a git working copy, right?

@data-man, so you're building the same git version with different options and use them? How does timestamp help you distinguish the options?

Don't get me wrong, I'm not against including additional metadata into the build, it's just "the current local system timestamp" info that I find useless and even potentially harmful because it explicitly takes away the possibility of building equal binaries.

**Pull request merged**
