### PR TITLE
xmltree: Make indentation consistent with any num of children nodes

### PR DESCRIPTION
**Pull request by kaushalmodi**
Ref: https://forum.nim-lang.org/t/5972

### CODE REVIEW

**Comment by kaushalmodi** [comment]
I'll wait and see if it breaks any of the existing xmltree tests ..

**Comment by kaushalmodi** [comment]
@Araq Actually please remove that "merge_when_passes_CI".. I found a case that this PR does not cover.

It does not handle this example properly: `x = <>l0(<>l1(<>l2_1(), <>l2_2(<>l3_1(), <>l3_2(), <>l3_3(<>l4_1(), <>l4_2(), <>l4_3())), <>l2_3(), <>l2_4()))`

Let me ping you once this PR is ready to be merged.

**Comment by kaushalmodi** [comment]
@Araq I believe this is in much better shape now. Though, the `noWhitespace` logic is still not as robust as I would have liked. Can you please review the new and modified tests in this PR?

**Comment by Araq** [comment]
Good enough for me.

**Pull request merged**
