### PR TITLE
strscans: skip input until next token is found

### PR DESCRIPTION
**Pull request by konqoro**
Uses parseutils.skipUntil

### CODE REVIEW

**Comment by konqoro** [comment]
Issue #5097

**Comment by konqoro** [comment]
Anyway I think this is the wrong approach of what I am trying to achieve (extract the links from a html). I should be using scanp instead.

**Comment by Araq** [comment]
This is getting out of hand. ``$/`` and ``$-`` are arbitrary choices, let's instead document ``scanp``?

**Comment by konqoro** [comment]
sure I agree.

**Pull request closed without merging**
