### PR TITLE
[RFC] IO interfaces

### PR DESCRIPTION
**Pull request by zielmicha**
This PR adds new IO interfaces (related to RFC #5728) and their implementation for all (?) IO objects in Nim stdlib.

`io` module:

```nim
type
  SyncOutput* = concept x
    ## Writes data from view into the output. Returns the number of bytes written.
    ##
    ## Return value of 0 indicates end of file.
    x.writeSync(ByteView) is int

    ## Closes the output.
    x.close

  SyncInput* = concept x
    ## Reads data into the buffer. Returns the number of bytes read.
    ##
    ## Return value of 0 indicates end of file.
    x.readSync(ByteView) is int

    ## Closes the input.
    x.close

  SyncIO* = concept x
    x is SyncOutput
    x is SyncInput
```

`asyncio` (replaces long deprecated asyncio module):

```nim
type
  Output* = concept x
    ## Writes data from view into the output. Returns the number of bytes written.
    x.write(ByteView) is Future[int]

    ## Closes the output.
    x.close

  Input* = concept x
    ## Reads data into the buffer. Returns the number of bytes read.
    x.read(ByteView) is Future[int]

    ## Closes the input.
    x.close

  IO* = concept x
    x is Output
    x is Input
```

Compare with currently implemented Streams:
```nim
type
  Stream* = ref StreamObj
  StreamObj* = object of RootObj ## Stream interface that supports
                                 ## writing or reading. Note that these fields
                                 ## here shouldn't be used directly. They are
                                 ## accessible so that a stream implementation
                                 ## can override them.
    closeImpl*: proc (s: Stream) {.nimcall, tags: [], gcsafe.}
    atEndImpl*: proc (s: Stream): bool {.nimcall, tags: [], gcsafe.}
    setPositionImpl*: proc (s: Stream, pos: int) {.nimcall, tags: [], gcsafe.}
    getPositionImpl*: proc (s: Stream): int {.nimcall, tags: [], gcsafe.}
    readDataImpl*: proc (s: Stream, buffer: pointer,
                         bufLen: int): int {.nimcall, tags: [ReadIOEffect], gcsafe.}
    peekDataImpl*: proc (s: Stream, buffer: pointer,
                         bufLen: int): int {.nimcall, tags: [ReadIOEffect], gcsafe.}
    writeDataImpl*: proc (s: Stream, buffer: pointer, bufLen: int) {.nimcall,
      tags: [WriteIOEffect], gcsafe.}
    flushImpl*: proc (s: Stream) {.nimcall, tags: [WriteIOEffect], gcsafe.}
```

* `Input` and `Output` objects are logically unbuffered -- there will be separate type BufferedInput/BufferedOutput in a similar manner to Java (of course less verbose!). This eliminates `peek` and `flush` from the interface. (This has benefit of making `net.nim` and `asyncnet.nim` code clearer).
* There is no `setPosition`, `getPosition` procs. They apply only to regular files, so there is no place for them in abstract `Input/Output`.
* Currently, there only concept definitions (compile-time polymorphism). I hope that `vtref` will be implemented soon. 

    Side note: @Araq argued before that the runtime polymorphism in style of StreamObj is faster -- vtref pointers are 16 bytes, while Stream is only 8 bytes. On the other hand the vtable for Stream is duplicated for every instance (blowing L1 cache). This won't matter anyway in practice, because I/O operations are almost always dominated by either waiting for the I/O to complete or L2 cache misses. That means that we should use the mechanism which is clearest (if it is reasonably performant).
* The sync versions are named prefixed/suffixed `Sync`. Alternatively we could prefix/suffix async version with `Async`. Depends on which I/O method we prefer (I like async more :) ).
* There is also very first version of `AsyncLoop` concept defined, which will be implemented by `PDispatcher` (this will follow pluggable loop design from Python asyncio)

### CODE REVIEW

**Comment by Araq** [comment]
> Input and Output objects are logically unbuffered -- there will be separate type BufferedInput/BufferedOutput in a similar manner to Java (of course less verbose!). This eliminates peek and flush from the interface. (This has benefit of making net.nim and asyncnet.nim code clearer).

I'm completely unconvinced this is a good design. I never need "unbuffered" IO.

> There is no setPosition, getPosition procs. They apply only to regular files, so there is no place for them in abstract Input/Output.

Memory streams naturally support them too. Maybe you can argue they are hard to provide for async IO or streaming APIs.

> This won't matter anyway in practice, because I/O operations are almost always dominated by either waiting for the I/O to complete or L2 cache misses. That means that we should use the mechanism which is clearest (if it is reasonably performant).

I can't say I agree. In-memory string streams are common and not bound by IO at all.

> The sync versions are named prefixed/suffixed Sync. Alternatively we could prefix/suffix async version with Async. Depends on which I/O method we prefer (I like async more :) ).

Can't we use 2 different types and overloading, I still enjoy "blocking IO" operations. (In fact, I could write a blog post about how async IO breaks all kinds of useful abstractions.)

**Comment by zielmicha** [comment]
> I can't say I agree. In-memory string streams are common and not bound by IO at all.

In this design operations that write only a few bytes would use `BufferedIO`, which would be a concrete type (so no virtual call overhead). 
That's actually one of the most important advantages of having separate BufferedIO and standard IO - that compiler can optimize small buffered IO to the point where it is as fast as (checked) array access (even in case of asynchrounous buffered I/O)

> I'm completely unconvinced this is a good design. I never need "unbuffered" IO.

Having unbuffered IO is very important in case of program which move large amounts of data without looking at them (e.g. proxies, storage servers).

> Can't we use 2 different types and overloading, I still enjoy "blocking IO" operations. (In fact, I could write a blog post about how async IO breaks all kinds of useful abstractions.)

This has a problem that `AsyncIO` can no longer be also automatically `SyncIO` (due to conflicting return types).

**Comment by zielmicha** [comment]
The alternative io module:
```
type
  SyncOutput* = concept x
    ## Writes data from view into the output. Returns the number of bytes written.
    ##
    ## Return value of 0 indicates end of file.
    x.write(ByteView) is int

    ## Closes the output.
    x.close

  SyncInput* = concept x
    ## Reads data into the buffer. Returns the number of bytes read.
    ##
    ## Return value of 0 indicates end of file.
    x.read(ByteView) is int

    ## Closes the input.
    x.close

  SyncIO* = concept x
    x is SyncOutput
    x is SyncInput
```

After some thought, `AsyncIO` being automatically `SyncIO` is anyway not the best idea, when there are multiple dispatchers in one thread. Instead, there will be function `toSyncIo(dispatcher: AsyncLoop, io: IO): SyncIO` (and `toSyncInput`, `toSyncOutput`).

**Comment by dom96** [comment]
My thoughts (written as I read through the discussion):

* Synchronous operations shouldn't have a ``sync`` suffix.

* The ``vtref`` will (hopefully) have the following syntax (i.e. s/concept/interface/), and indeed, these should be defined as interfaces not concepts:

```nim
type
  Output* = interface x
    ## Writes data from view into the output. Returns the number of bytes written.
    x.write(ByteView) is Future[int]

    ## Closes the output.
    x.close

  ...
```

* I like my IO procedures to take a ``string`` not a ``ByteView``.

* > There is no setPosition, getPosition procs. They apply only to regular files, so there is no place for them in abstract Input/Output.

    Agreed, there should be a more specific ``FileStream`` interface. 

* Hrm, does it really make sense to have two separate Input/Output interfaces? Why not just have a single ``Stream`` interface?

* > The sync versions are named prefixed/suffixed Sync. Alternatively we could prefix/suffix async version with Async. Depends on which I/O method we prefer (I like async more :) ).

    I dislike suffixes. I like the way it is done now: disambiguating based on the first parameter type (Socket vs. AsyncSocket). Can we accomplish the same using interfaces? (after reading further I see that @Araq asked for the same thing, glad we agree :) )

* Again, seeing that you have to reuse the module ``asyncio``, I don't think you should call it ``io``.

**Comment by Varriount** [comment]
Not that I have much hope for such a thing, but new modules should really come with a NEP (Nim Enhancement Proposal). Looking through the code is one thing, but it's rather hard to deduce high-level decisions and considerations without either extended discussion or a proposal document.

**Comment by zah** [comment]
@dom96, I think the idea is that `ByteView` will be implicitly convertible from `string` and you need `ByteView` to make it possible to write zero-copy networking code.

I'm not planning to introduce `interface` as a separate keyword. This only reduces the combinatorial expressivity of the type system. As an alternative to `vtref` and `vtprt`, I've also considered `ref SomeConcept.value` and `ptr SomeConcept.value` (we may discuss this in a separate issue).

Separating the input and output streams makes sense to me (there are many types of devices that can act only as an input or an output stream). Concepts can be combined with the `and` operator to create a combined type.

Relying more on overloading instead of Sync/Async suffixes looks nice to me. A weaker version of `await` may be defined that automatically becomes a no-op in synchronous code and allows you to write generic algorithms that work both in synchronous and asynchronous settings. Return-type overloading is a planned feature, which we may decide to introduce sooner if it would benefit the proposed designs here.

**Comment by dom96** [comment]
> I think the idea is that ByteView will be implicitly convertible from string and you need ByteView to make it possible to write zero-copy networking code.

> As @zah said, ByteViews are essential for networking code that copies data around without parsing it.

@zah @zielmicha How about the interface accepts a ``string | ByteView``? That way it's a bit easier on the programmer as they don't have to remember this new relationship between ByteView and String.

> I'm not planning to introduce interface as a separate keyword.

@zah ``interface`` is already a keyword. I'm pretty sure we discussed this on Skype and you agreed that this was a possibility. Having to write ``vtref concept`` would be weird.

> A weaker version of await may be defined that automatically becomes a no-op in synchronous code and allows you to write generic algorithms that work both in synchronous and asynchronous settings.

@zah This is already supported by my ``multisync`` macro. Unless you have something else in mind?

> I see two possibilities for naming the interfaces:

@zielmicha @zah this is a bit off topic but it really seems to me that we need some easy way to convert a ``concept`` into a ``vtref concept`` and a ``vtref concept`` into a ``concept``. Won't having to define both be a PITA? Shouldn't it be up to the programmer that is using it not the programmer that is defining it? This is sort of analogous to the ``ref`` vs. non-ref problem, and to be fair, letting this conversion happen would be inconsistent with this.

> Separating the input and output streams makes sense to me (there are many types of devices that can act only as an input or an output stream). Concepts can be combined with the and operator to create a combined type.

Alright. Makes sense.

> @dom96 Any ideas for better module name than io/asyncio?

One idea might be to just put these interfaces/concepts into the ``streams`` (and ``asyncstreams``) module.

**Comment by zah** [comment]
@dom96, the VTable type that you can derive from a concept is limited to the procs accepting concrete param types. `string | ByteView` is not a concrete type. The use of `or` types may be treated as a request for multiple overloads in the future, but in this particular situation, having a single run-time proc taking a `ByteView` is more efficient.

We've indeed discussed `interface` before, but I'm pretty sure I've always maintained the same position regarding it. 

I think I need to clarify few things regarding the `vtref` types. A "VTable value" is a run-time type (a fat pointer). It has a compatible interface with the concept behind it, so it can be passed to generic procs, accepting the concept type (this will just lead to one more instantiation). You can construct at any time a VTable value from any type that's compatible with the concept. Sometimes, this will happen automatically at the call-site of a proc accepting a VTable value, sometimes the programmer will be more explicit about it. The benefit of using a VTable value in the signature of a particular proc is that this allows you to reduce the amount of generated run-time code (code bloat) and to create polymorphic collections of values at the expense of run-time execution speed (due to the introduced dynamic dispatch).

**Comment by andreaferretti** [comment]
@zielmicha Any news on this? I am just writing something to prevent stalebot from closing this

**Comment by Araq** [comment]
This now needs to be redesigned and take into consideration our new first class "openArray for views" support.

**Pull request closed without merging**
