### PR TITLE
test fast ci

### PR DESCRIPTION
**Pull request by juancarlospaco**
test ignore, no review

### CODE REVIEW

**Comment by ringabout** [comment]
nimscript is an option as well.

**Comment by juancarlospaco** [comment]
> nimscript is an option as well.

Yes, I am just trying things, I considered Python, Node, Bash, etc.

But you need to compile Nim to run Nimscript?. 🤔

(Sorry to test here but is hard to test in a fork)

**Comment by juancarlospaco** [comment]
Any ideas to speed up CI are welcome...

**Comment by Araq** [comment]
In what universe would I accept a PR that replaces Nim code with Python shit...

**Comment by juancarlospaco** [comment]
The idea was to speed up CI, whatever it takes, but it did not improved anything relevant, ok to close.

**Pull request closed without merging**
