### PR TITLE
fix `strutils.replace` when `sub` is an empty string (fixes #7507)

### LINKED ISSUE #7507: string.replace() should throw an error when used with an empty string
This currently leads to out-of-memory problems:

```
import strutils
echo "hello".replace("", "ohh nooo")
```

### PR DESCRIPTION
**Pull request by narimiran**
fixes #7507 

Also added a couple of tests for `replace`.

### CODE REVIEW

**Comment by notTito** [comment]
Maybe an assert instead?

**Comment by GULPF** [comment]
Some comparisons with other languages, result after running `"foo".replace("", "bar")` or equivalent:
**js**, **ruby**: "barfoo"
**python, java**: "barfbarobarobar"
**C#**: error
I think raising an error makes the most sense.

**Comment by dom96** [comment]
Yep, raising an error is consistent with ``split``'s behaviour: an empty separator fails an assert. Since people love their performance an assert is appropriate here too. You can use ``doAssertRaises`` for your tests.

**Comment by narimiran** [comment]
> Yep, raising an error is consistent with `split`'s behaviour: an empty separator fails an assert.

Will change it to assert to be consistent with `split` (I'll also add tests for that).

Since I f*ed up with commits here, I'll open another PR.

**Pull request closed without merging**
