### PR TITLE
WIP: CI updates

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by Araq** [comment]
What's the effect of this on the travis running times? I fear it makes travis builds much slower...

**Comment by data-man** [comment]
@Araq 
I will try to implement the @dom96 suggestion. See his comment: https://github.com/nim-lang/Nim/pull/6595#issuecomment-339501734
But apparently, editing the CI-files is not enough.
Probably, need to modify the Nim build files from csources.
Close this?

**Comment by Araq** [comment]
Checking that multiple GCC versions can build the generated C code that is initially used is a good solution already.

**Comment by data-man** [comment]
Temporary closed.

**Pull request closed without merging**
