### PR TITLE
close #10735 add testcase

### LINKED ISSUE #10735: cstring with nested case crashes compiler
### Example (run with `nim check`)
```nim
let buf: cstring
case buf[pos]
else:
  case buf[pos]
```

### Current Output
```
t.nim(1, 5) Error: 'let' symbol requires an initialization
t.nim(2, 10) Error: undeclared identifier: 'pos'
t.nim(2, 9) Error: type mismatch: got <cstring, >
but expected one of:
proc `[]`[Idx, T](a: var array[Idx, T]; i: BackwardsIndex): var T
proc `[]`[T, U, V](s: openArray[T]; x: HSlice[U, V]): seq[T]
proc `[]`[T](s: openArray[T]; i: BackwardsIndex): T
template `[]`(s: string; i: int): char
proc `[]`[Idx, T, U, V](a: array[Idx, T]; x: HSlice[U, V]): seq[T]
proc `[]`[T, U](s: string; x: HSlice[T, U]): string
proc `[]`[T](s: var openArray[T]; i: BackwardsIndex): var T
proc `[]`[Idx, T](a: array[Idx, T]; i: BackwardsIndex): T
proc `[]`(s: string; i: BackwardsIndex): char
proc `[]`[I: Ordinal; T](a: T; i: I): T

expression: [](buf, pos)
t.nim(2, 1) Error: selector must be of an ordinal type, float or string
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected
Not crashing

### Additional Information
```
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-02-24
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 28a83a838821cbe3efc8ddd412db966ca164ef5c
active boot switches: -d:release -d:useLinenoise
```

### PR DESCRIPTION
**Pull request by ringabout**
close #10735 add testcase

### CODE REVIEW

**Review by timotheecour — DISMISSED** [review]
LGTM.

- [ ] one downside of this kind of test is it adds friction when stdlib or compiler changes because the output here will likely need to change; maybe (in future work) we could add a flag `-d:nimEchoQuitting` that would print `quitting` before calling `quit` (regardless of error code being 0 or non-0) so that we can easily distinguish whether we gracefully quit (even with non-0 status) or whether it got SIGSEGV.

that way, all you'd need is to test that you got whatever you want to get from nim check output, plus 1 line that would say "quitting" in nimout.

It also gives stronger confidence that the test indeed quit gracefully instead of via a SIGSEGV, which really isn't obvious otherwise.


wdyt ?

EDIT: see https://github.com/nim-lang/Nim/pull/16694

**Comment by ringabout** [comment]
If there exists something which only tests segfault, I would be happy to choose that.

**Review by timotheecour — APPROVED** [review]
LGTM.
we can simplify this once https://github.com/nim-lang/Nim/pull/16694 is merged (i still need to address https://github.com/nim-lang/Nim/pull/16694#issuecomment-759031541 )

**Comment by timotheecour** [comment]
non-controversial (adds a test case), merging

**Pull request merged**
