### PR TITLE
follow up of #20332, `fromChar` -> `parseDigit`

### PR DESCRIPTION
**Pull request by hamidb80**

### CODE REVIEW

**Comment by ghost** [comment]
You also should change it so that it throws a ValueError instead of using an assert

**Comment by ghost** [comment]
And also I'm not sure if it should be named `fromChar` or `parseChar` - right now the strutils has from* procs for non-base 10 parsing, and `parse` is for normal parsing (e.g. `parseInt`)

**Comment by hamidb80** [comment]
> right now the strutils has from* procs for non-base 10 parsing, and `parse` is for normal parsing (e.g. `parseInt`)

how about `parseInt(ch: char): int` ?

**Comment by hamidb80** [comment]
`parseDigit` looks good to me, what do you think?

**Comment by hamidb80** [comment]
to be honest I'm not sure why `ord` returns `int` by default, 
but I guess it's not needed for this functions to be generic.

**Pull request closed without merging**
