### PR TITLE
various enum improvements.

### PR DESCRIPTION
**Pull request by Parashurama**
This PR only affect VM, C & CPP target
This PR improve **reprEnum** from O(N) to O(logN) for enums with holes.
This PR improve **parseEnum** from O(N) to O(logN) for enums with holes.
parseEnumImpl uses a custom linear search with a lookup table for enums with with large number of values. Several implementations were tested but discarded for several reasons. 
* hashmap (default nim hashtable, fastest, x10 more memory, huge additional import)
* hashmap (custom robinhood hashtable, almost as fast, x5 more memory, 600 LOC)
* cached linear search (all normalized strings allocated contiguouly, very fast, but O(N))
* logtables, and several others 

**MyEnum.items** now only return valid enum values for enums with holes.

This PR also add these two procs in ```system.nim```
```nim
proc len*[Enum: enum](x: typedesc[Enum]): int
  ## returns the number of fields in enum
proc isOrdinal*[Enum: enum](x: typedesc[Enum]): bool
  ## returns true if enum is an ordinal (ie: has no holes.)
```
@Araq How can I make the compiler on Travis and AppVeyor accept new **Magic** .
On my local computer I just disable the new code paths using the new **Magic** for recompiling nim and then reenable the code for a second recompiling.

### CODE REVIEW

**Comment by cooldome** [comment]
Amazing, very cool stuff

**Comment by Parashurama** [comment]
Apparently CI builds are failing because of timeout. 
Tests are passing just fine.

**Comment by Araq** [comment]
I appreciate your effort, but this is still pretty convoluted. Why not make ``parseEnum`` generate a ``case`` statement? If cstring vs string is the problem, we can make ``case`` work with cstrings too.

**Comment by Parashurama** [comment]
There are several reasons:
 * The main reason is to avoid using macros module.
 * string switch generate a large amount of code for Enum with large number of values.
 * Also according to my benchmarks, they can also be quite a bit slower than hashmap, or my solution

**Comment by Parashurama** [comment]
UPDATE: I revisited this PR. this now include all improvements to enums except the custom lookup table in strutils.parseEnum.

`parseEnum` now uses linear search on cstring included with Enum typeinfo.
This change only affect platforms C, Cpp, VM.

Further changes to parseEnum could be made in another PR (change from linear sreach to binary search or macro-generated switch)

**Comment by cooldome** [comment]
I am so glad to found out that you revisiting this PR. It has many useful stuff in it. Let's do some work to get it over the line. IMO, you did absolutely right to separate enums with holes improvements and parseEnum improvements.

Couple of comments: ``enumGetString`` it is useful on its own, I think it deserves a place system.nim.
Could be that the following interface would be more usable:
```
proc enumStr (x: enum): cstring  {.magic: "EnumGetString", noSideEffect.}
```

And then parseEnum would look like:
```
from cstrutils import cmpIgnoreStyle
proc parseEnum*[T: enum](s: string): T =
  for e in items(T):
    if cmpIgnoreStyle(s.cstring, e.enumStr()) == 0:
      return e
raise newException(ValueError, "invalid enum value: " & s)
```

But let's see what Araq is going to say.

**Comment by data-man** [comment]
I think that nimImprovedEnum is not needed.

**Comment by cooldome** [comment]
``nimImprovedEnum`` is required to bootstrap the compiler only. Every new magic function when it is introduced needs to be wrapped into some kind of ``when`` or compiler is going to complain about unknown magic

**Comment by data-man** [comment]
@cooldome 
Thanks for the explanation!
So, need to add to the changelog that Nim must be compiled with the nimImprovedEnum option:

> koch boot -d:nimImprovedEnum

**Comment by Yardanico** [comment]
@data-man no, it's not required

**Comment by data-man** [comment]
@Yardanico 
But the entry in the changelog is needed.
So that after next release there were no phrases "changelog not full" or "we didn't mention that ...".

**Comment by Araq** [comment]
Sorry, but the effort and increased internal complexity is not worth it, usually enums only have a couple of different values that can be checked for in a linear fashion. If it becomes a bottleneck, via ``getType`` you can specialize the ``parseEnum`` proc in all the ways you want.

**Pull request closed without merging**
