### PR TITLE
Revert "disable pkg manu"

### PR DESCRIPTION
**Pull request by planetis-m**
Reverts nim-lang/Nim#18292

### CODE REVIEW

**Comment by timotheecour** [comment]
/Users/runner/work/Nim/Nim/lib/system/nimscript.nim(273, 7) Error: unhandled exception: FAILED: nake test [OSError]

**Comment by planetis-m** [comment]
@timotheecour thank you for reporting, I have fixed the issue while the CI was running (basically disabled nake), this is why it failed.

**Comment by timotheecour** [comment]
i've restarted the failing CI jobs then

EDIT: still fails

**Comment by planetis-m** [comment]
Seems like `git --tags push` doesn't update the master branch. Fixed

**Pull request closed without merging**
