### PR TITLE
Fixed compilation of times.nim with mingw 4.9.2 C++ 32bit

### PR DESCRIPTION
**Pull request by yglukhov**

### CODE REVIEW

**Comment by zah** [comment]
I think the problem is that `CTime` is defined to be 64-bit integer on Windows, while in MINGW64 it's a regular `long` (which is a 32-bit int, [see here](https://stackoverflow.com/questions/7607502/sizeoflong-in-64-bit-c)).

The correct fix will be to add more cases around the definition of `CTime`.

**Comment by Araq** [comment]
So make it ``defined(gcc) and defined(windows)`` specific?

**Comment by yglukhov** [comment]
Now I'm not sure if this is only `gcc+windows+32bit` problem, or `windows+32bit`? @zah, @Araq?

**Comment by zah** [comment]
To clarify, my understanding is that in 64-bit mode `MSVC` defines `CTime` as `int64`, but MINGW64 still uses `int32` (even in 64-bit mode). But all of this is based on the fact that I've seen what the error message from MINGW was and the comments regarding Windows (MSVC) in `times.nim`

**Comment by cheatfate** [comment]
My mingw64 4.8.2 using 64bit `time_t`
```
#include <time.h>
#include <stdio.h>
int main(void) {
  printf("%ld\n", sizeof(time_t));
}
```
This code is exactly prints 8.

**Comment by yglukhov** [comment]
Summarizing experiment results:
mingw32 - 4
mingw64 - 8
vcc64 - 8
vcc32 - ???

Anyone around to test vcc32?

**Comment by cheatfate** [comment]
vcc32 = 8 too

**Comment by yglukhov** [comment]
How interesting. Now the question is, do `mingw32` and `vcc32` use different runtime variants of `localtime`?

**Comment by yglukhov** [comment]
I've updated the commit so that `int32` is only on `windows+gcc+32bit`. That's what you would get compiling raw C code with `time_t`.

**Comment by cooldome** [comment]
I recall you can define ``_USE_64BIT_TIME_T`` before including time.h to make time_t 64bit even on 32bit windows

**Comment by cheatfate** [comment]
Agree, it can be easily done via
```nim
when defined(windows) and defined(gcc):
  {.passC: "-D_USE_64BIT_TIME_T".}
```
at the beginning of `times.nim`

**Comment by yglukhov** [comment]
@cooldome, just tested, this trick did not work for me (

**Comment by yglukhov** [comment]
Given that this pr fixes a compilation problem, and doesn't affect public interface, I consider it ready to go.

**Comment by dom96** [comment]
Looks good to me. Merging.

**Pull request merged**
