### PR TITLE
Fix implicit iterators not working in templates

### PR DESCRIPTION
**Pull request by nc-x**
Fixes https://github.com/nim-lang/Nim/issues/11167

### CODE REVIEW

**Comment by nc-x** [comment]
The test case in the PR works with this patch, but unfortunately bootstrapping fails. So the patch needs more work.

**Comment by Araq** [comment]
Yes. The best solution seems to be to introduce hidden ``nkBind`` statements.

**Comment by nc-x** [comment]
@Araq 
Do you mean to introduce nodes for `bind items`, `bind pairs` in the templates? Because if i tested it right (simply by adding these statement manually to the test case in the linked issue), it doesn't work.

**Comment by Araq** [comment]
> Do you mean to introduce nodes for bind items, bind pairs in the templates? Because if i tested it right (simply by adding these statement manually to the test case in the linked issue), it doesn't work.

That's what I meant. And if it doesn't work, it should be made to work, it's the best solution that I can see.

**Comment by narimiran** [comment]
> The best solution seems to be to introduce hidden nkBind statements.
>
>  if it doesn't work, it should be made to work

@nc-x do you plan to continue to work on this or should we close this PR?

**Comment by nc-x** [comment]
Closing for now.

**Pull request closed without merging**
