### PR TITLE
align type mismatch errors to make it visually obvious

### PR DESCRIPTION
**Pull request by timotheecour**
```nim
when true:
  proc fn1(a: int) = discard
  var fn: proc(a: float)
  fn = fn1
```

## before PR
```
Error: type mismatch:
 got 'proc (a: int){.noSideEffect, gcsafe, locks: 0.}' for 'fn1' [proc]
 but expected 'proc (a: float){.closure.}' [proc]
```

## after PR
```
Error: type mismatch:
 obtained 'proc (a: int){.noSideEffect, gcsafe, locks: 0.}' for 'fn1' [proc]
 expected 'proc (a: float){.closure.}' [proc]
```

### CODE REVIEW

**Comment by Varriount** [comment]
Why not just use spaces for alignment? While `obtained` *technically* works here, the definition has connotations that just don't make sense in this context.

**Comment by timotheecour** [comment]
I don't mind changing to something else but I'd rather do it just once after consensus reached; I'd still like to minimize indents if possible; another option:
```
got  X
want Y

got  X
need Y

got    X
expect Y
```

**Comment by kaushalmodi** [comment]
```
expected X
but got  Y
```

**Comment by timotheecour** [comment]
actually, compiler uses this internally:
```
actual X
formal Y
```

seems like a good choice

**Comment by kaushalmodi** [comment]
TBH "formal" doesn't quite ring a bell there at least for me. "actual" and "expected" makes more sense to me.

**Comment by Araq** [comment]
Let's use

```
expected X
but got  Y
```

**Comment by Clyybber** [comment]
```
wanted X
gotten Y
```
could also work, but I don't know how it sounds to native english speakers :D

**Comment by timotheecour** [comment]
```
expected X
but got  Y
```
other compiler messages use the opposite order so that's not ideal (1 got, 2 expected)

how about this then?
```
gotten X
wanted Y
```

**Comment by Araq** [comment]
Fine with me if the native speakers don't complain. Ping @ee7

**Comment by Varriount** [comment]
> how about this then?
> 
> ```
> gotten X
> wanted Y
> ```

This is... grammatically odd. While `gotten` is [technically interchangeable](https://www.grammarly.com/blog/got-gotten/) with `got` ([at least to a certain degree](https://www.lexico.com/definition/gotten)), it really doesn't fit here.

I feel that @Araq's was much better.

```
expected X
but got  Y
```

In compiler messages, the program is the speaker. The error message is read implicitly as "[I] (expected|wanted) X [, but] (got|received) Y".

**Comment by ee7** [comment]
I like the idea to align the types.

But if we compile the top post's snippet
> ```Nim
> when true:
>   proc fn1(a: int) = discard
>   var fn: proc(a: float)
>   fn = fn1
> ```

with a plain `nim c` (using Nim 1.4.8 or the latest `devel`), the output is all on one line:

```
/tmp/mismatch.nim(4, 8) Error: type mismatch: got 'proc (a: int){.noSideEffect, gcsafe, locks: 0.}' for 'fn1' but expected 'proc (a: float){.closure.}'
```

I can reproduce the top post's "before PR" state of

> ```
> Error: type mismatch:
>  got 'proc (a: int){.noSideEffect, gcsafe, locks: 0.}' for 'fn1' [proc]
>  but expected 'proc (a: float){.closure.}' [proc]
> ```

only if I compile with `--declaredLocs`, because the logic for adding extra newlines is this:

https://github.com/nim-lang/Nim/blob/f4ff276a90091f2b88c191aac5a201dcb3ec9795/compiler/types.nim#L1573-L1584

Is this PR's discussion intended to be limited to the case when the above `verbose` evaluates to `true`? Or is there an intention for the compiler's default output to have more newlines in the future?  

This isn't clear to me, since the top post doesn't mention `--declaredLocs`.

**Comment by ee7** [comment]
> ```
> gotten X
> wanted Y
> ```

I don't like it. It's best to avoid "gotten", since it's less common outside of North America.

But it's also more linguistically complex. I'd prefer that a compiler uses simple constructions like:
> "I got a string, but I expected an int"

than more complex things like:
> "I've got(ten) a string, but I expected an int"

> "I've got(ten) a string, but I was expecting an int"

> "I've got(ten) a string, but I had been expecting an int"

So, ignoring the alignment for a moment, the below is much better:
> ```
> got X
> wanted Y
> ```

> In compiler messages, the program is the speaker. The error message is read implicitly as "[I] (expected|wanted) X [, but] (got|received) Y".

I agree.

---

From https://stroppyeditor.wordpress.com/2017/03/27/the-us-has-gotten-this-word-back-and-the-uk-probably-will-too/

> ### How gotten works
> One noteworthy word is *gotten*: standard in the US but not in the UK.
> 
> In both countries, the past tense of *get* is *got*. In British English, the past participle is also *got*. But in American English, it’s more complex. Roughly: when talking about a static situation (possessing or needing) the past participle is *got*; when talking about a dynamic situation (acquiring or becoming) the past participle is *gotten*. So:
> 
> - Yesterday I got a new guitar
> - I’ve got a great guitar
> - I’ve gotten a new guitar
> - You’ve got to see my new guitar
> - I got into playing the guitar last year
> - I’d gotten into playing the guitar the previous year

More:
- https://grammarist.com/usage/got-gotten/
- https://english.stackexchange.com/questions/5531/difference-between-i-have-got-and-i-have-gotten
- https://www.grammar-monster.com/easily_confused/got_gotten.htm (see flowchart)

**Comment by timotheecour** [comment]
> So, ignoring the alignment for a moment, the below is much better:

and how exactly, does this help? the whole point of this PR is alignment; the constraints:
* it must align
* it must preserve ordering (got goes first, to be consistent with other messages)
* ideally no padding space which complicate matters, eg when `--declaredLocs` is not provided, the padding space looks weird, and removing the padding space would create further complications if user tries to use exact substring/prefix match when searching on github and no match is found because of the padding space removed between search and query where `--declaredLocs` was used in 1 but not the other)


can we either settle for this:
```
gotten X
wanted Y
```
or else please suggest an alternative that fits the bill?

We're not writing poetry here, it's just a compiler message and some aspects (ease of spotting mismatch) are more important than others.

**Comment by Varriount** [comment]
Why no padding space?

**Comment by ee7** [comment]
Apologies for the slow reply.

> or else please suggest an alternative that fits the bill?

I can only see a present tense option
```
have X
want Y
```
but I think it's better to stick with past tense.

So my suggestion is just that something with padding space is better than anything with "gotten" - sorry that I can't be more helpful. To unblock this PR, should we just go with something like the below for now

```
got    X
wanted Y
```

```
got  X
want Y
```

and then make a follow-up PR if we can find an option that allows removing the padding space? I think this is better than hoping for a follow-up PR to remove "gotten".

But as far as I understand, this only affects the output with `--declaredLocs`, so it affects few users anyway.

> when `--declaredLocs` is not provided, the padding space looks weird

Can't we only add padding when `--declaredLocs` is used? I do see your argument that padding space can reduce searchability, though.

> We're not writing poetry here, it's just a compiler message and some aspects (ease of spotting mismatch) are more important than others.

Sure.

**Comment by timotheecour** [comment]
please vote:
option 1: vote with 👍 
```
got  X
want Y
```

option 2: vote with  👀 
```
got    X
wanted Y
```

option 3: vote with  😕 
```
got      X
expected Y
```

option 4: vote with  🚀 
```
something else, please explain
```

(and keep the spaces in each case regardless of `--declaredLocs` to avoid impacting search)

so we can finally move on with this

**Comment by konsumlamm** [comment]
I think both parts should be in past tense, for example `got ... expected ...` (this is my preferred option) or `got ... wanted ...`.

**Comment by dom96** [comment]
For me it's option 3 or a custom suggestion:

```
actual   X
expected Y
```

**Comment by ee7** [comment]
> (and keep the spaces in each case regardless of `--declaredLocs` to avoid impacting search)

Are you saying that the default compiler output, without `--declaredLocs`, would look something like these?

```
/tmp/mismatch.nim(4, 8) Error: type mismatch: got   'proc (a: int){.noSideEffect, gcsafe, locks: 0.}' for 'fn1' but wanted 'proc (a: float){.closure.}'
```

```
/tmp/mismatch.nim(4, 8) Error: type mismatch: got      'proc (a: int){.noSideEffect, gcsafe, locks: 0.}' for 'fn1' but expected 'proc (a: float){.closure.}'
```

I think we should have the extra spaces only for the multiline display only.

Anyway, doesn't adding spaces to the default output have a bigger searchability problem? A user would need to remove the new spaces to find old issues/posts with the same error message.

I'd prefer option 3, but the default output stays as
```
/tmp/mismatch.nim(4, 8) Error: type mismatch: got 'proc (a: int){.noSideEffect, gcsafe, locks: 0.}' for 'fn1' but expected 'proc (a: float){.closure.}'
```
That is, without extra spaces, and without removing "but" as this PR does currently.

---

I might be missing something here, because my question [here](https://github.com/nim-lang/Nim/pull/18391#issuecomment-886038300) wasn't answered:

> Is this PR's discussion intended to be limited to the case when the above `verbose` evaluates to `true`? Or is there an intention for the compiler's default output to have more newlines in the future?  
>
> This isn't clear to me, since the top post doesn't mention `--declaredLocs`.

**Comment by timotheecour** [comment]
PTAL, I went for the winning proposal in https://github.com/nim-lang/Nim/pull/18391#issuecomment-905682518 (not something worth getting thousands of votes for, the point is to move forward with a reasonable improvement); it now uses:
```
declaredlocs:off:
got A ..., but expected B ...

declaredlocs:on:
got      A ...
expected B ...
```

**Pull request closed without merging**
