### PR TITLE
Make dot-like operators have dot-like precedence

### PR DESCRIPTION
**Pull request by Clyybber**

### CODE REVIEW

**Comment by timotheecour** [comment]
@Clyybber I agree with the idea of this PR but it doesn't seem to work:
```nim
import macros
macro mydebug(a: untyped): untyped =
  echo a.treeRepr
mydebug:
  a .> b . c .> d
mydebug:
  a . b . c . d
```

prints this (before or after PR):
```nim
StmtList
  Infix
    Ident ".>"
    Infix
      Ident ".>"
      Ident "a"
      DotExpr
        Ident "b"
        Ident "c"
    Ident "d"
StmtList
  DotExpr
    DotExpr
      DotExpr
        Ident "a"
        Ident "b"
      Ident "c"
    Ident "d"
````

I'd expect to give the grouping for the 1st case to be:
```
((a .> b) . c) .> d
```
instead of 
```
(a .> (b . c)) .> d
```
unless i'm misunderstanding something?

## note:
if your PR worked as I expect it to, it'd simplify this:  https://gitter.im/nim-lang/Nim?at=5e3a654bdc52c34ace47f433 for "efficient outplace operator chaining"

## EDIT:
but i found a way without ur PR to get proper tree transform via macros; still though , ur PR makes sense

**Comment by Araq** [comment]
Sorry, this needs to go through the RFC process. Unlikely we will get it right otherwise.

**Comment by timotheecour** [comment]
on the other hand sometimes a (draft) PR can serve as an RFC, if not too much work to write; it often happens you see issues only after implementing the feature (as was the case in https://github.com/nim-lang/Nim/pull/13332#issuecomment-582278809)

**Comment by krux02** [comment]
This is certainly a breaking change.

**Comment by Araq** [comment]
Rejected for now, please write an RFC if you care enough about it.

**Pull request closed without merging**
