### PR TITLE
Initial support for reproducible builds (#7644) via SOURCE_DATE_EPOCH

### PR DESCRIPTION
**Pull request by tersec**
A patch for [#7644](https://github.com/nim-lang/Nim/issues/7644).

### CODE REVIEW

**Comment by zah** [comment]
Why do we need the `--timestamps:on/off` option? It would be simpler to just respect `SOURCE_DATE_EPOCH` if it is defined.

**Comment by zah** [comment]
Ah, I found the relevant discussion here:
https://github.com/nim-lang/Nim/pull/3115

**Comment by Araq** [comment]
I won't fight it anymore but what I said 3 years ago is still true. An idea that requires you to patch every tool ever used for producing software is a bad idea. Consensus doesn't make a bad idea good.

**Comment by tersec** [comment]
I'd also have preferred not adding another compiler switch in addition to the environment variable check -- the latter alone seems preferable. I'd be fine with signalling errors, as well. I'm not particularly tied to the specific semantics here. And, yes, it seems suboptimal to require patching every software-producing tool ever, but I've not seen an overall better approach.

**Comment by Araq** [comment]
> I'd also have preferred not adding another compiler switch in addition to the environment variable check -- the latter alone seems preferable.

Ok, please do that. Less code is better code. (Sorry I changed my mind a bit.)

**Comment by tersec** [comment]
Done. Pull request #7661 should address issues raised here.

**Pull request closed without merging**
