### PR TITLE
Peg captures get stack-like behavior

### PR DESCRIPTION
**Pull request by gemath**
Motivation
--------------
- Indentation-based formats (like Nim code) are hard to describe with PEGs, this should be changed.
- The limitation to atm 20 captured values would hurt less if there was a mechanism to discard obsolete captures.
- Back-references with reverse indexing would make PEG expressions more context-insensitive in general.

Description
--------------- 
With this, captures and back-references in PEGs learn two presently unsupported special cases, in a backwards compatible way:

- Back-references can have negative indices now for reverse indexing: ``$-1`` refers to the last captured value, ``$-2`` to the second-last etc.
- The empty capture expression ``{}`` is legal syntax now, it deletes the last captured value without consuming a character.

With these two changes, the captures array can be used as a stack: a regular capture is a push operation (like before), ``$-1`` gets the top of the stack and ``{}`` acts as a pop operation.

### CODE REVIEW

**Comment by gemath** [comment]
Sry for the annoying merge commits, shouldn't be a problem though.

**Comment by ringabout** [comment]
> Sry for the annoying merge commits, shouldn't be a problem though.

There is nothing to worry about. Pull requests are always squashed automatically :)
image

**Comment by Araq** [comment]
Nim uses ^1, not -1 for reverse indexing.

**Comment by gemath** [comment]
Yes, but then: in PEG syntax, this collides with ``^`` meaning "start of the matching text". Some users of a PEG parsing software written in Nim might not know about Nim at all and would probably be irritated by it when they write a grammar.

**Comment by Araq** [comment]
But it would ``$^``, wouldn't it?

**Comment by gemath** [comment]
So you think ``^`` and ``$^1`` are different enough to not be confusing? If yes, I'll implement ``$^`` for reverse indexing.

**Comment by Araq** [comment]
Yeah, I think so.

**Comment by gemath** [comment]
Dammit, special chars `$` and `^` didn't make it into the commit message. Could try to force push a fixed message togemath:pegs_captures_stack, but I'm not sure what this does to the pull request..

**Pull request merged**
