### PR TITLE
Emscripten support

### PR DESCRIPTION
**Pull request by haiodo**
Hi,
I've added a support for Emscripten environment.

Changes I've made:
1. mmap in Emscripten could return non PageSize aligned pointers so i've added a bit more ram and aligned pointer properly.
2. Emscripten stack is growing so I've updated support for *stackIncreases = true* cases.

I've added a define 'emscripten' so it is possible to compile for Emscripten with -d:emscripten command line.

Thanks,
Andrey.

### CODE REVIEW

**Comment by Araq** [comment]
Love it! But Can you please add a test case?

**Comment by haiodo** [comment]
Not sure it will be easy :-)

Right now I've met one more issue with allow.nim and emscripten.
After some execution rawAlloc() return a pointer with 0x10 value.
Happen after
var c = a.freeSmallChunks[s]
    if c != nil: ...
case.
So digging right now :-)

**Comment by haiodo** [comment]
I think node.js could be used for a tests. Will check.

**Comment by haiodo** [comment]
After few days found why still have problems with alloc and GC.
Emscripten passess values and recieve result of function call not by using stack but with javascript function argumetns and results.

Because of this we could force GC to dealloc objects we are just created :-(

For example generating xmltree.nim module method newelement causes following .c code to be generated
```
N_NIMCALL(Xmlnodeobj124011*, newelement_124052)(NimStringDesc* tag) {
  Xmlnodeobj124011* result;
  NimStringDesc* LOC1;
  nimfr("newElement", "xmltree.nim")
  result = 0;
//  result = newXmlNode(xnElement)
  nimln(46, "xmltree.nim");
  result = newxmlnode_124034(((NU8) 1));
//  result.fTag = tag
  nimln(47, "xmltree.nim");
  if (!(((2 &(1<<(((*result).k)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP743));
  LOC1 = 0;
  LOC1 = (*result).kU.S2.ftag; (*result).kU.S2.ftag = copyStringRC1(tag);
  if (LOC1) nimGCunrefNoCycle(LOC1);
//  result.s = @[]
  nimln(48, "xmltree.nim");
  if (!(((2 &(1<<(((*result).k)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP748));
  if ((*result).kU.S2.s) nimGCunrefNoCycle((*result).kU.S2.s);
  (*result).kU.S2.s = (TY124020*) newSeqRC1((&NTI124020), 0);
  popFrame();
  return result;
}
```

And GC is called in my scenario from
```LOC1 = (*result).kU.S2.ftag; (*result).kU.S2.ftag = copyStringRC1(tag);```

And causes a trouble in Emscripten since result is not on stack because Emscripten generated code are following:

```
function _newelement_124052($tag) {
        $tag = $tag | 0; //@line 1895
        var $0 = 0, $1 = 0, $10 = 0, $11 = 0, $12 = 0, $13 = 0, $14 = 0, $15 = 0, $16 = 0, $17 = 0, $18 = 0, $19 = 0, $2 = 0, $20 = 0, $21 = 0, $22 = 0, $23 = 0, $24 = 0, $25 = 0, $26 = 0; //@line 1896
        var $27 = 0, $28 = 0, $29 = 0, $3 = 0, $30 = 0, $31 = 0, $32 = 0, $33 = 0, $34 = 0, $35 = 0, $36 = 0, $37 = 0, $38 = 0, $39 = 0, $4 = 0, $40 = 0, $41 = 0, $42 = 0, $43 = 0, $44 = 0; //@line 1897
        var $45 = 0, $46 = 0, $47 = 0, $48 = 0, $49 = 0, $5 = 0, $6 = 0, $7 = 0, $8 = 0, $9 = 0, $FR = 0, $LOC1 = 0, $result = 0, label = 0, sp = 0; //@line 1898
        sp = STACKTOP; //@line 1899
        STACKTOP = STACKTOP + 32 | 0; //@line 1900
        if ((STACKTOP | 0) >= (STACK_MAX | 0)) 
            abort(); //@line 1900
        $FR = sp; //@line 1901
        $0 = $tag; //@line 1902
        $1 = $FR + 4 | 0; //@line 1903
        SAFE_HEAP_STORE($1 | 0, 27286 | 0, 4, 0);
        $2 = $FR + 12 | 0; //@line 1905
        SAFE_HEAP_STORE($2 | 0, 27552 | 0, 4, 0);
        $3 = $FR + 8 | 0; //@line 1907
        SAFE_HEAP_STORE($3 | 0, 0 | 0, 4, 0);
        $4 = $FR + 16 | 0; //@line 1909
        SAFE_HEAP_STORE($4 | 0, 0 | 0, 2, 0);
        _nimFrame766($FR); //@line 1911
        $result = 0; //@line 1912
        $5 = $FR + 8 | 0; //@line 1913
        SAFE_HEAP_STORE($5 | 0, 46 | 0, 4, 0);
        $6 = $FR + 12 | 0; //@line 1915
        SAFE_HEAP_STORE($6 | 0, 27552 | 0, 4, 0);
        $7 = _newxmlnode_124034(1) | 0; //@line 1917
        $result = $7; //@line 1918
        $8 = $FR + 8 | 0; //@line 1919
        SAFE_HEAP_STORE($8 | 0, 47 | 0, 4, 0);
        $9 = $FR + 12 | 0; //@line 1921
        SAFE_HEAP_STORE($9 | 0, 27552 | 0, 4, 0);
        $10 = $result; //@line 1923
        $11 = SAFE_HEAP_LOAD($10 >> 0 | 0, 1, 0, 0) | 0 | 0; //@line 1924
        $12 = $11 & 255; //@line 1925
        $13 = $12 & 7; //@line 1926
        $14 = 1 << $13; //@line 1927
        $15 = 2 & $14; //@line 1928
        $16 = ($15 | 0) != 0; //@line 1929
        if (!$16) {
            _raiseFieldError(17508); //@line 1931
        }
        $LOC1 = 0; //@line 1933
        $17 = $result; //@line 1934
        $18 = $17 + 4 | 0; //@line 1935
        $19 = SAFE_HEAP_LOAD($18 | 0, 4, 0, 0) | 0 | 0; //@line 1936
        $LOC1 = $19; //@line 1937
        $20 = $0; //@line 1938
        $21 = _copyStringRC1($20) | 0; //@line 1939
        $22 = $result; //@line 1940
        $23 = $22 + 4 | 0; //@line 1941
        SAFE_HEAP_STORE($23 | 0, $21 | 0, 4, 0);
        $24 = $LOC1; //@line 1943
        $25 = ($24 | 0) != (0 | 0); //@line 1944
        if ($25) {
            $26 = $LOC1; //@line 1946
            _nimGCunrefNoCycle769($26); //@line 1947
        }
        $27 = $FR + 8 | 0; //@line 1949
        SAFE_HEAP_STORE($27 | 0, 48 | 0, 4, 0);
        $28 = $FR + 12 | 0; //@line 1951
        SAFE_HEAP_STORE($28 | 0, 27552 | 0, 4, 0);
        $29 = $result; //@line 1953
        $30 = SAFE_HEAP_LOAD($29 >> 0 | 0, 1, 0, 0) | 0 | 0; //@line 1954
        $31 = $30 & 255; //@line 1955
        $32 = $31 & 7; //@line 1956
        $33 = 1 << $32; //@line 1957
        $34 = 2 & $33; //@line 1958
        $35 = ($34 | 0) != 0; //@line 1959
        if (!$35) {
            _raiseFieldError(17524); //@line 1961
        }
        $36 = $result; //@line 1963
        $37 = $36 + 4 | 0; //@line 1964
        $38 = $37 + 4 | 0; //@line 1965
        $39 = SAFE_HEAP_LOAD($38 | 0, 4, 0, 0) | 0 | 0; //@line 1966
        $40 = ($39 | 0) != (0 | 0); //@line 1967
        if (!$40) {
            $45 = _newSeqRC1(17424, 0) | 0; //@line 1969
            $46 = $result; //@line 1970
            $47 = $46 + 4 | 0; //@line 1971
            $48 = $47 + 4 | 0; //@line 1972
            SAFE_HEAP_STORE($48 | 0, $45 | 0, 4, 0);
            _popFrame767(); //@line 1974
            $49 = $result; //@line 1975
            STACKTOP = sp; //@line 1976
            return $49 | 0; //@line 1976
        }
        $41 = $result; //@line 1978
        $42 = $41 + 4 | 0; //@line 1979
        $43 = $42 + 4 | 0; //@line 1980
        $44 = SAFE_HEAP_LOAD($43 | 0, 4, 0, 0) | 0 | 0; //@line 1981
        _nimGCunrefNoCycle769($44); //@line 1982
        $45 = _newSeqRC1(17424, 0) | 0; //@line 1983
        $46 = $result; //@line 1984
        $47 = $46 + 4 | 0; //@line 1985
        $48 = $47 + 4 | 0; //@line 1986
        SAFE_HEAP_STORE($48 | 0, $45 | 0, 4, 0);
        _popFrame767(); //@line 1988
        $49 = $result; //@line 1989
        STACKTOP = sp; //@line 1990
        return $49 | 0; //@line 1990
    }
```

Looking at emscripten and a way to inform GC about how to teach GC about this kind of calls.

**Comment by dom96** [comment]
This is really awesome. Thank you for your work! :)

**Comment by haiodo** [comment]
Hi guys,

I've added a small test to check Emscripten with GC, it passes on normal environment and fail in Emscripten :-(

It seems fixing GC in Emscripten in easy way is not possible :-(

How it could be solved
1. Add Emscripten support for stack argument passing. Not a easy way I see.
2. Enhance GC and compiler to include collecting of passed arguments and return values in case they are could be GC collected. It seems this approach could be a bit easier and not force to make changes to both project.

How to with with Emscripten right now:

Since problem is easy detectable in my experiments I've used system.GC_disable(), GC_enable() and GC_fullCollect() in some known places.

@Araq if possible could you please include fixes to master branch. At least right now it possible to use it with GC enabled :-)

Thanks,
Andrey.

**Comment by haiodo** [comment]
Thanks :-)

**Pull request merged**
