### PR TITLE
Implicitly set noNimblePath when nimble.lock is present

### LINKED ISSUE #1004: `--noNimblePath` should unconditionally be set for projects with lock files
If a project has a lock file, plain `nim` and tooling should be prevented from ever looking into the nimble folder, so as to avoid that random code from the global nimble cache infects the project.

The current strategy with a conditional `when fileExists("nimble.paths"):` breaks before `nimble setup` has been run, because `nimble.paths` does not exist on a freshly cloned repository.

### PR DESCRIPTION
**Pull request by yyoncho**
Fixes https://github.com/nim-lang/nimble/issues/1004

### CODE REVIEW

**Comment by Varriount** [comment]
@Araq @dom96 What do you think?

**Comment by yyoncho** [comment]
@narimiran - can you backport?

**Comment by SolitudeSF** [comment]
can someone explain what is the point of this?

**Comment by ringabout** [comment]
@yyoncho Hello, it seems to break `stew`.

>   /home/runner/work/Nim/Nim/pkgstemp/stew/tests/ranges/tstackarrays.nim(10, 3) Error: cannot open file: unittest2

**Comment by narimiran** [comment]
> @narimiran - can you backport?

Done.

**Pull request merged**
