### PR TITLE
Correction - os.nim does not retrieve env vars

### PR DESCRIPTION
**Pull request by markprocess**

### CODE REVIEW

**Comment by Araq** [comment]
Sure it does, ``os.getEnv`` is a thing.

**Comment by andreaferretti** [comment]
It is not in the documentation, though! https://nim-lang.org/docs/os.html#getEnv

**Comment by Yardanico** [comment]
@andreaferretti that's because `os` module imports and exports `ospaths` module.

**Comment by markproc** [comment]
https://github.com/nim-lang/Nim/blob/0c683d28bbd559667fa5cd865cf53ca3aef3a8f1/lib/pure/os.nim#L33-L34

So since module os delegates (amongst other things) getEnv to module osprocs then I think that
https://nim-lang.org/docs/os.html#getEnv
needs to link to a "delegates" section in os.html.

**Comment by kaushalmodi** [comment]
May be the docs should explicitly say something along the lines of "os module exports ospaths. So all the exported identifiers (procs, etc) from ospaths is available in the os namespace too.". 

This I believe would need to be rephrased into a more technically correct statement.

**Comment by Araq** [comment]
> So since module os delegates (amongst other things) getEnv to module ospaths then I think that
https://nim-lang.org/docs/os.html#getEnv
needs to be implemented in a "delegates" section in os.html.

Yeah we need something along these lines.

**Comment by markproc** [comment]
Does anyone know how to close this PR but retain the issue for further discussion?

https://github-issue-mover.appspot.com won't work with a pull request issue.

**Comment by Yardanico** [comment]
@markproc close this PR and make an issue?

**Comment by dom96** [comment]
Just create an issue and link to this PR from it.

**Pull request closed without merging**
