### PR TITLE
Documentation add DrNim to 'Tools available with Nim'

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Add DrNim to `Tools available with Nim`, Documentation only.

### CODE REVIEW

**Comment by Araq** [comment]
DrNim isn't documented nor announced for a reason. ;-) This has to wait.

**Comment by juancarlospaco** [comment]
Reopen considering is now part of stable official documentation for a while now (?)
https://nim-lang.org/docs/theindex.html & https://nim-lang.org/docs/drnim.html

**Comment by Araq** [comment]
It should be removed from the documentation instead.

**Comment by juancarlospaco** [comment]
@Araq 
But been out for a while now, theres even blog post related, if you "hide" it from public looks weird or even suspicious...,
I really dont understand the idea of intentionally hiding Documentation from potential users and companies wanting to use Nim,
you can just add a big warning "This is not production ready" or similar  ...and most people will understand it.
:thinking:

**Comment by Araq** [comment]
It's not that it isn't production ready, it's really unfinished. :-(

**Pull request closed without merging**
