### PR TITLE
Implemented JS support for lexbase

### PR DESCRIPTION
**Pull request by flyx**
* Do not use Stream in JS because neither StringStream nor FileStream
   are available. Instead, support taking a string as input.
 * Make open() proc taking a string also available for non-JS.
 * Added test.

### CODE REVIEW

**Comment by yglukhov** [comment]
This is not lexbase's problem that streams work poorly in js. Lexbase works perfectly well with a custom Stream subclass that works in js. Also this is a breaking change. Nogo.

**Comment by flyx** [comment]
But can a custom Stream subclass even be implemented in JS when `copyMem` is not available? I do not see how the low-level `pointer` parameters can be handled properly without it.

**Comment by yglukhov** [comment]
Please, have a look at possible impl. It is really hacky, but works for the most part.
https://github.com/yglukhov/nimx/blob/master/nimx/private/js_data_view_stream.nim

**Comment by flyx** [comment]
Do you think it is feasible to adapt that code so that it works like a StringStream? That would solve my problem.

**Comment by yglukhov** [comment]
Absolutely. Reading chars from such a stream should work pretty flawlessly, unless performance is your concern ;). You can just copy my DataView impl, and replace the dataview parts with nim string accordingly.

**Comment by yglukhov** [comment]
Feel free to ask questions should there be any.

**Comment by yglukhov** [comment]
@flyx, now that i think of it, you can use my impl as is. Just convert nim string to dataview.
```nim
proc stringToDataView(s: string): RootRef =
  {.emit: """
  `result` = new DataView(new Uint8Array(`s`).buffer, 0);
  """.}
let myStream = newStreamWithDataView(stringToDataView("Hello world!"))
```
Haven't tested this code, but you get the point.

**Comment by flyx** [comment]
@yglukhov after sleeping over it, I think this is the wrong way. I should simply not use lexbase if I have an input string because it uselessly slows down the parsing process. Instead, there should be an implementation the works directly on a string.

I'll close this PR for the reasons discussed here. Thanks for inspiration though!

**Pull request closed without merging**
