### PR TITLE
fix getTypeImpl for nkIdentDefs

### PR DESCRIPTION
**Pull request by foldl**
son[0] should be Ident, not nkSym.

### CODE REVIEW

**Comment by Araq** [comment]
But this is a breaking change. Can't we adapt the docs instead?

**Comment by foldl** [comment]
> But this is a breaking change. Can't we adapt the docs instead?

Yes? I get to know sons[0] is nkIdent from `macros.nim`:

```nim
proc newIdentDefs*(name, kind: NimNode;
                   default = newEmptyNode()): NimNode {.compileTime.} =
  ## Creates a new ``nnkIdentDefs`` node of a specific kind and value.
  ##
  ## ``nnkIdentDefs`` need to have at least three children, but they can have
  ## more: first comes a list of identifiers followed by a type and value
  ## nodes. This helper proc creates a three node subtree, the first subnode
  ## being a single identifier name. Both the ``kind`` node and ``default``
  ## (value) nodes may be empty depending on where the ``nnkIdentDefs``
  ## appears: tuple or object definitions will have an empty ``default`` node,
  ## ``let`` or ``var`` blocks may have an empty ``kind`` node if the
  ## identifier is being assigned a value. Example:
  ##
  ## .. code-block:: nim
  ##
  ##   var varSection = newNimNode(nnkVarSection).add(
  ##     newIdentDefs(ident("a"), ident("string")),
  ##     newIdentDefs(ident("b"), newEmptyNode(), newLit(3)))
  ##   # --> var
  ##   #       a: string
  ##   #       b = 3
  ##
  ## If you need to create multiple identifiers you need to use the lower level
  ## ``newNimNode``:
  ##
  ## .. code-block:: nim
  ##
  ##   result = newNimNode(nnkIdentDefs).add(
  ##     ident("a"), ident("b"), ident("c"), ident("string"),
  ##       newStrLitNode("Hello"))
  newNimNode(nnkIdentDefs).add(name, kind, default)
```

**Comment by cooldome** [comment]
Sym is definately better than Ident. Ident gives you just name, while Sym gives you name plus much much more

**Comment by foldl** [comment]
OK, codes of compiler agree with nkSym, while `macros.nim` thinks it should be nkIdent.

Majority wins. It is `newIdentDefs` that needs to be fixed.

**Comment by krux02** [comment]
I think it is a bad idea to change the node type under the hood.

**Comment by foldl** [comment]
> I think it is a bad idea to change the node type under the hood.
> Can you pleare reference the issue that you try to fix? Or at least explain the issue that you try to fix?

#12712

**Comment by krux02** [comment]
It is not obvious why this change would affect your PR. So please elaborate.

**Comment by foldl** [comment]
> It is not obvious why this change would affect your PR. So please elaborate.

Test code:

```nim
macro dbg(body: typed): untyped =
  echo body.treeRepr
  result = body

macro show(x: typed): untyped =
  echo treeRepr getTypeImpl(x)

proc test() =
  dbg:
    var myClosure: proc (x: int): int
    show(myClosure)
```

`type` of `myClosure` printed by `dbg` is:

```
ProcTy
  FormalParams
    Sym "int"
    IdentDefs
      Ident "x"   ## <- Here
      Sym "int"
      Empty
  Empty
```

But, `type` of `myClosure` printed by `show` is:

```
ProcTy
  FormalParams
    Sym "int"
    IdentDefs
      Sym "x"   ## <- Here
      Sym "int"
      Empty
  Empty
```

**Comment by foldl** [comment]
Use `freshIdentNodes` from `sugar` to fix this for us.

**Comment by krux02** [comment]
This is certainly a related issue: https://github.com/nim-lang/Nim/issues/6771
I want it the other way around though.

**Pull request closed without merging**
