### PR TITLE
more refined effect tracking; added .effectsDelayed pragma; WIP

### LINKED ISSUE #13905: `raises` not preseved in `proc` types, invalid "can raise any" error on compile
```nim
proc atoi(v: cstring): cint {.importc: "atoi", cdecl, raises: [].}

type Conv = proc(v: cstring): cint {.cdecl, raises: [].}

var x: Conv = atoi
```

```bash
[arnetheduck@tempus tmp]$ ~/src/Nim-up/bin/nim c test
/home/arnetheduck/tmp/test.nim(5, 15) Error: type mismatch: got <proc (v: cstring): cint{.cdecl.}> but expected 'Conv = proc (v: cstring): cint{.cdecl.}'
.raise effect is 'can raise any'
```

```bash
[arnetheduck@tempus tmp]$ ~/src/Nim-up/bin/nim --version
Nim Compiler Version 1.2.0 [Linux: amd64]
Compiled at 2020-04-07
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 7e83adff84be5d0c401a213eccb61e321a3fb1ff
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by Araq**
Todo: 

- [ ] Tests.
- [ ] Stdlib update.
- [ ] Documentation.
- [ ] RFC process.

Refs https://github.com/nim-lang/Nim/issues/18376, will fix #13905

### CODE REVIEW

**Comment by Araq** [comment]
Relax: The name and syntax of `.effectsDelayed` is up for discussions.

**Comment by arnetheduck** [comment]
potentially related: https://github.com/nim-lang/Nim/issues/17369

**Comment by dom96** [comment]
If you're adding so many `gcsafe` then I think you're heading in the wrong direction :)

Can we get rid of `gcsafe` first?

**Comment by Araq** [comment]
> If you're adding so many gcsafe then I think you're heading in the wrong direction :)

Most of them are due to a compiler bug afaict and can be reverted once that bug is fixed. However, it's an indication of the real complexity of Nim's effect system.

**Comment by Araq** [comment]
Succeeded by https://github.com/nim-lang/Nim/pull/18777

**Pull request closed without merging**
