### PR TITLE
Uses XDG_CACHE_HOME if available

### PR DESCRIPTION
**Pull request by alaviss**

### CODE REVIEW

**Comment by kaushalmodi** [comment]
The XDG_CACHE_HOME is shared by many applications.. Would it be better to have nim use `$XDG_CACHE_HOME/nim/`?

**Comment by Araq** [comment]
Nah. Too much nesting, we have ``_r`` vs ``_d`` suffixes which no other application does. And if you argue that it *might* produce clashes, well ``nim/`` might produce clashes too.

**Comment by kaushalmodi** [comment]
More than clash, I was thinking about ease of removing nim cache files. The .cache has my browser cache too. So if I want to remove just nim cache dirs, `rm -rf $XDG_CACHE_HOME/nim` would work nicely.

**Comment by kaushalmodi** [comment]
Also for precendence, other tools create there subdirs in the XDG_CACHE_HOME. Google Chrome, for example, creates `$XDG_CACHE_HOME/google-chrome`.

**Comment by arnetheduck** [comment]
+1 for `.cache/Nim/..`

**Pull request merged**
