### PR TITLE
implemented alignas pragma

### LINKED ISSUE #1930: Request: Pragma to specify the alignment of object fields
I was looking for something like {.align: 8.} to override how fields in an object are packed in memory, but couldn't find anything. I'm currently creating some bindings for C library that make heavy use of align().

Example:

```
type Foo {.align: 8.} = object
  x: int
  y: int
```

Or maybe we can reuse the {.packed.} pragma for that.

### LINKED ISSUE #5315: Align pragma broken
```nim
type Foo {.align: 16.} = object
```

Results in:

    test.nim(2, 17) Error: invalid pragma: align: 16

Would be great if following worked as well:

```nim
type Foo = ref object
  bar {.align: 16.}: SomeType
```

Where `SomeType` is possibly `importc` type (if it is of any meaning).

Most ideally we would want following to work so that `Foo` type can be aligned as required always.
```nim
type Foo {.align: 16.} = object
```

### PR DESCRIPTION
**Pull request by krux02**
Well this implements https://en.cppreference.com/w/c/language/_Alignas for Nim. A special word in `TSpecialWord` was already reserved for this, it was just waiting for the implementation.

The difference compared to the C version is, this implementation requires an integer argument, in C a type argument is allowed as well. The reason for this limitation is simple: A solution that would cover imported types (unknown alignment to Nim) would be too much effort, at least for now. For non-imported types it is possible it is possible to align to another type with `alignof` inside of `alignas`: ``{.alignas(alignof(float64)).}``.

This feature is actually needed in Nim itself. During my work on [newSeq on Aligned Type](https://github.com/nim-lang/Nim/pull/12430) I stumbled upon this code:

https://github.com/nim-lang/Nim/blob/7e689873e203620c3a14f1697129cd0e3fd548e4/lib/system/alloc.nim#L63-L70

With this feature the code could be rewritten as following:

```nim
  SmallChunk = object of BaseChunk
      next, prev: PSmallChunk  # chunks of the same size
      freeList: ptr FreeCell
      free: int            # how many bytes remain
      acc: int             # accumulator for small object allocation
      data {.alignas(MemAlign).}: UncheckedArray[byte]  # start of usable memory
```

The when statement isn't needed anymore to make it work for 32 bit systems. The constant [MemAlign](https://github.com/nim-lang/Nim/blob/7e689873e203620c3a14f1697129cd0e3fd548e4/lib/system/mmdisp.nim#L49)  could be changed into a constant that can be changed with the "compile time define pragmas", as they are listed in `nim --fullhelp`, and it will work with any alignment value.

closes #1930
closes #5315

### CODE REVIEW

**Comment by krux02** [comment]
@mratsim since you are working with many types that do have alignment constraints. Would this feature be beneficial for you in any way? Note though allocations and `seq` members still ignore these alignment constraints.

**Comment by mratsim** [comment]
Yes, I have 2 very-specific use-cases that need alignment:
1. Thread-safe data structures. I need fine-grained control on where they reside on the cache line.
  This is enabled by this PR. :heavy_check_mark: 
2. SIMD. In that case it's the heap allocation that should be aligned. This is ideal but not required, unaligned loads/stores or a custom allocator work.
The first is actually the most critical for me because I had no workaround besides spraying padding

That was actually one of my complaints in https://github.com/nim-lang/RFCs/issues/160#issuecomment-549199561 (at the very bottom):

https://github.com/mratsim/weave/blob/796b9cc3/picasso/channels/channels_mpsc_bounded_lock.nim#L13-L56
```Nim
type
  ChannelMpscBounded*[T] = object
    pad0: array[PI_CacheLineSize - 3*sizeof(int32), byte]
    backLock: Lock # Padding? - pthread_lock is 40 bytes on Linux, unknown on windows.
    capacity: int32
    buffer: ptr UncheckedArray[T]
    pad1: array[PI_CacheLineSize - sizeof(int32), byte]
    front: Atomic[int32]
    pad2: array[PI_CacheLineSize - sizeof(int32), byte]
    back: Atomic[int32]
```

https://github.com/mratsim/weave/blob/796b9cc3/picasso/memory/persistacks.nim#L13-L53
```Nim
type
  Persistack*[N: static int8, T: object] = object
    pad: array[PI_CacheLineSize - N*sizeof(ptr T) - sizeof(pointer) - sizeof(int8), byte]
    stack: array[N, ptr T]
    rawMem: ptr array[N, T]
    len*: int8
```

And even the Nim system needs it:
https://github.com/nim-lang/Nim/blob/7e689873e203620c3a14f1697129cd0e3fd548e4/lib/pure/concurrency/threadpool.nim#L56-L64

**Comment by mratsim** [comment]
Related issues: https://github.com/nim-lang/Nim/issues/1930 https://github.com/nim-lang/Nim/issues/5315.

does the {.align: 16.} pragma still exist? I don't see it in the manual. Anyway I think even though those issues want type-level alignment, if we have field-level alignment we can just align the first field. So this would close both issues.

**Comment by cooldome** [comment]
I have reviewed looks great. One minor question is why new word `alignas` was taken instead of extending existing one: `align`?
Otherwise ready for submit.

**Comment by krux02** [comment]
@mratsim thanks a lot for the feedback. I also marked the two issues to be closed when this PR gets merged. Regarding the ``{.align: 16.}`` pragma. No that one does not exist (anymore?). I found some dead and outdated code regarding the `align` pragma and I removed it in this PR. The reason I picked field alignment annotations instead of type annotations is, The field annotations are supported in both C and C++. C does not allow to annotate the type with alignment, see the notes section [here](https://en.cppreference.com/w/c/language/_Alignas). So I decided to implement the feature that can be implemented for both C and C++ backend.

@cooldome There are reasons for `alignas`. First of all as just mentioned `align` doesn't really exist anymore. It is currently just one of many reserved words for pragmas. `alignas` is also one of them, so I thought I can just use that one. `alignas` is also the name that is used in C++.

https://github.com/nim-lang/Nim/blob/7e689873e203620c3a14f1697129cd0e3fd548e4/compiler/wordrecg.nim#L79

**Pull request merged**
