### PR TITLE
Fix a couple of small keyword issues.

### PR DESCRIPTION
**Pull request by benji-york**
In this section of the manual, "if" should be enclosed in backticks and "elif" should be lower case.

### CODE REVIEW

**Comment by Araq** [comment]
English grammar requires to start a sentence with an upper cased letter though.

**Comment by benji-york** [comment]
> English grammar requires to start a sentence with an upper cased letter though.

That is true generally, and what I thought was going on, but the document has several other instances of sentences starting with symbols that are not capitalized.  E.g.,

> quotes introduce a triple quoted string literal. `r"""` is the same
> as `"""` since triple quoted string literals do not interpret escape

> If a reference points to *nothing*, it has the value `nil`. `nil` is the
> default value for all `ref` and `ptr` types. The `nil` value can also be

As a house style decision, it makes sense to adopt one of these options:

1. The first word of an English sentence is capitalized, so that's what we'll do, regardless of whether or not that word is a case-sensitive symbol.
2. Capitalization is essential to the meaning of case-sensitive symbols, so when a sentence starts with one we will not capitalize it so as to not to confuse the reader.
3. Will will avoid the problem altogether by disallowing case-sensitive symbols as the first word of a prose sentence.

The current documentation does not consistently do any of these, but chooses 2 more often than not.  How does this project make such decisions?  (I'm a Nim newbie.)

**Comment by beef331** [comment]
It is vastly more important that the verbatim usage of the language is documented rather than ensuring sentences would get a English teacher's approval, is my view.

**Comment by Araq** [comment]
I suppose (2) is much less work than (3), so ok.

**Pull request merged**
