### PR TITLE
fix #12130 ; improve naming scheme in fakePackageName

### LINKED ISSUE #12130: Filenames ending with xxx8.nim
Compiling a file ending with xxx8.nim
will show filename wrongly in the last line of the cc output lines.

Example

```
nim c -r test218.nim
Hint: used config file '/home/hantu2/.choosenim/toolchains/nim-#head/config/nim.cfg' [Conf]
Hint: used config file '/home/hantu2/user/.choosenim/toolchains/nim-#head/config/config.nims' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: test218 [Processing]
CC: test21:.nim                   <-------------------
Hint:  [Link]
Hint: operation successful (21679 lines compiled; 0.331 sec total; 24.035MiB peakmem; Debug Build) [SuccessX]
Hint: /data5/NimStuff/test218  [Exec]
```
Expected output during compile:

```
.
.
CC: test218.nim
Hint:  [Link]
.
.
```

Tested on latest devel version on linux.
Filenames ending with other numbers are fine.

### PR DESCRIPTION
**Pull request by timotheecour**
* `7` `8` are more common (especially in tests) than `@` so `@` seems more appropriate mangling character
* should work on windows as had been mentioned in https://github.com/nim-lang/Nim/pull/8614#issuecomment-413031385 
* should fix https://github.com/nim-lang/Nim/issues/12130 although I wasn't able to reproduce that issue on OSX (might affect linux only)
* /cc @qqtop @juancarlospaco does that fix the problem for you?

```
../bam@bax/cab.nim
=>
..@bam@@bax@cab.nim.c

../bam/bax/cab.nim
=>
..@bam@bax@cab.nim.c
```
the leading `..` could be avoided but IMO is more readable and should be legal anyway

## note
this PR does not try to make the `fakePackageName` a valid nim identifier (shouldn't be needed IIUC); note that this also wasn't the case before this PR, eg:
`nimcache/_7bar.baz7gaz77.nim.c` doesn't give a valid identifier (for `../bar.baz/gaz7.nim`); ditto with starting with `_7` or containing `__`)

### CODE REVIEW

**Comment by Araq** [comment]
You need to adapt some tests I think and then it's ready to go. In retrospect, I would have produces subdirs inside nimcache, but this improves the situation, so thank you!

**Comment by timotheecour** [comment]
> You need to adapt some tests I think and then it's ready to go.

done

> In retrospect, I would have produced subdirs inside nimcache, but this improves the situation, so thank you!

relative paths (`..`) is awkward to deal with subdirs though; and flat generated files seems easier to deal with (no need for `rm -rf` etc)

**Comment by dom96** [comment]
Thank you for this!

**Comment by juancarlospaco** [comment]
its not supposed to do this :grey_question: 
https://nim-lang.github.io/Nim/os.html#quoteShell%2Cstring
Because if not would be a great addition to that proc, like an optional `escapeSlash = true` or something.
:thinking:

**Comment by timotheecour** [comment]
@juancarlospaco not sure I understand how this relates to quoteShell; the goal of fakePackageName/demanglePackageName is to translate a relative path (possibly starting with `..`) to a filename, and back. quoteShell has a different goal.

**Pull request merged**
