### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by timotheecour**
/cc @Araq @dom96 @narimiran 

## links
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

### CODE REVIEW

**Comment by data-man** [comment]
Just for record :) #6630

**Comment by timotheecour** [comment]
I removed all checklist items, it's more intended as being informational than as bureaucratic boilerplate (quite different from https://github.com/nim-lang/Nim/pull/6630), eg:
* the bleeding edge contributing docs is just a click away
* helpful reminder of easy to forget syntax such as [ci-skip]', 'refs #bugid' and 'fix #bugid'  (which are often mis-used/mis-spellt even though they carry semantic)
* made it clear it's intended to be removed; but IMO it's a good occasion to remind a small number of points

**Comment by timotheecour** [comment]
> we don't need them.

take a look at the text I'm adding: it's concise and meant to be informative, not in-your-face boilerplate; 
for example, it'll help remind people to add `[ci-skip]` to their commit messages whenever appropriate.

**Comment by dom96** [comment]
I polished this a little. I'm still mostly against merging this though, the fact that we need to ask the user to remove the message is a big enough signal to make this disruptive.

**Comment by krux02** [comment]
I also don't like it. These are some hints to create a PR, but not a template at all. It is just text that needs to be removed in every pull request. I don't think that pull requests need a template.

**Comment by Araq** [comment]
The issue template is annoying enough, I agree with the others. Sorry.

**Pull request closed without merging**
