### PR TITLE
Better shell scripts

### PR DESCRIPTION
**Pull request by Immortalin**

### CODE REVIEW

**Comment by Varriount** [comment]
@Immortalin Might want to brace yourself for incoming complaints from Araq regarding *nix systems.

Also, I'll just leave this here:

**Comment by Araq** [comment]
``bootstrap.sh`` is not a Bash script, it's a Posix shell script.

**Comment by Varriount** [comment]
What about ``env sh`` then?

**Comment by Araq** [comment]
That wouldn't work on Solaris 4.

**Comment by Varriount** [comment]
We support a ceversion of Solaris over 10 years old?

**Pull request closed without merging**
