### PR TITLE
temporary compiler mechanism for slim system warnings

### LINKED ISSUE #20967: nimPreviewSlimSystem deprecation messages are weird
### Description

Knew about this already (and I bet others did as well) and couldn't think of a solution so didn't report for a while.

Currently deprecation messages for `nimPreviewSlimSystem` are either:

1. directly in system whenever `nimPreviewSlimSystem` is not defined:
   https://github.com/nim-lang/Nim/blob/5658e8e5c5e3852f877eb0501b12e664114de567/lib/system/formatfloat.nim#L4
   These do not get emitted as messages because system has `warnings:off` by default or something, but doing `import system` or `from system import ...` gives `Warning: system is deprecated`.
2. (bad one) directly inside the new modules themselves whenever `nimPreviewSlimSystem` is not defined:
   https://github.com/nim-lang/Nim/blob/5658e8e5c5e3852f877eb0501b12e664114de567/lib/std/formatfloat.nim#L13
   This means whenever we do the right thing and import these modules, we get a complaint (although we should probably only import `when (NimMajor, NimMinor) >= (1, 7)`).

### Nim Version

09b8f98

### Current Output

_No response_

### Expected Output

_No response_

### Possible Solution

This might require adding temporary behavior for this situation to the compiler. For example:

```nim
when not defined(nimPreviewSlimSystem):
  import std/formatfloat
  export formatfloat {.slimSystemDeprecated.}
  # or
  export formatfloat {.deprecated: "import std/formatfloat explicitly".}
```

Don't know if this is feasible.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by metagn**
closes #20967

Not sure if this is the best solution but don't want to bikeshed either. As mentioned in #20967, I can't think of existing compiler mechanisms that are good enough for this situation.

### CODE REVIEW

**Comment by metagn** [comment]
Most tests are failing due to the warnings interfering with `nimoutFull`. I'll silence the warning for each test individually but the `when defined(nimPreviewSlimSystem): import ...` idiom spammed everywhere doesn't really make sense with this warning, it should be something like `when (NimMajor, NimMinor) >= (2, 0): import ...` instead. Or maybe I'm wrong about this whole thing, idk.

**Comment by metagn** [comment]
Now opt-in with `-d:nimSlimSystemWarnings` (there is an issue with generics/iterators where the import in the definition module isn't enough). Not the compiler mechanism though, as I think it would be slower to check for this define every time than just check for the temporary new flag.

**Comment by Araq** [comment]
> as I think it would be slower to check for this define every time than just check for the temporary new flag.

Does this mean there would be a way to accomplish the same without a compiler patch? Because if so, that would be preferrable.

**Comment by metagn** [comment]
No, I don't think there's a way to do it without a compiler patch, because I tried to think of one and couldn't (by "temporary new flag" I meant temporary symbol flag added to the compiler for this). There might be a way that I haven't thought of, and even if there isn't, there might be a better compiler patch to do this; but it's better to actually have these warnings, even if a bit inaccurate, than not have them at all. Performance impact should be negligible.

**Comment by metagn** [comment]
Subpar implementation

**Pull request closed without merging**
