### PR TITLE
Added some C99 funcs

### PR DESCRIPTION
**Pull request by apense**
Error function (and complementary) and gamma function (and truncated). Also cubic root

### CODE REVIEW

**Comment by Araq** [comment]
meh, does visual studio support these? I still consider C99 a non-standard that is fucked up.

**Comment by dom96** [comment]
This might cost us the ability to compile without C99 support. Would dead code elimination help here?

**Comment by apense** [comment]
Well, for instance, `hypot` is already in there, but it was only included since C99, apparently [see here](http://en.cppreference.com/w/c/numeric/math/hypot). I'm not sure any of these necessitates C99 syntax support by the compiler, but I'm not sure.

There are other functions that are more exotic, so I didn't include them here. They're things like the `j0` Bessel functions. `erf` and `erfc` are special functions, too, but they're a lot more common.

**Comment by apense** [comment]
@Araq just checked VS 2013 (no fun) and it supports them. It supports the Bessel functions, too (they're all prefixed with underscore. other is deprecated).

**Comment by Araq** [comment]
@dom96 Yes, .deadCodeElim of couse helps, but it doesn't help with the upcoming bug reports "foobar does not compile on XYZ"

**Pull request merged**
