### PR TITLE
`parsecfg.nim` module supports annotation statements, does not delete comment statements and redundant blank characters, leaving the original style and you can specify annotation delimiters.

### PR DESCRIPTION
**Pull request by lihf8515**
`parsecfg.nim` module supports annotation statements, does not delete comment statements and redundant blank characters, leaving the original style and you can specify annotation delimiters.

### CODE REVIEW

**Comment by dom96** [comment]
You can't just break this module like that. Also I don't understand what this PR achieves, what is the problem with how parsecfg currently works? What configs is it unable to parse?

**Comment by lihf8515** [comment]
This module does not resolve successfully for some INI files, for example, the INI file with the comment symbol `&` does not resolve successfully. Spaces and empty lines in the original file cannot be left intact.

**Comment by dom96** [comment]
Can you show an example of this?

**Comment by lihf8515** [comment]
For example: the following configuration file,Its annotation symbol is `&`.If you use the current version of `parsecfg.nim` to read the value of one of the keys, (ServerIP),The result is read together with the content of the annotation.If you replace it with my modified `parsecfg.nim`, The value of the original INI file content can be read correctly, and the format of the content of the original INI file does not change after the value has been modified (including blank lines, spaces, notes, etc.).When I modified `parsecfg.nim`. I was already compatible, and the previous functions and variables were still available,
The price to pay for this is the need to modify the `nimble` related module file processing of empty keys.
Note: when using the module I modified, call this `loadConfig("Config.ini", "&")`

`Config.ini`
[Server]
ServerOS             = Windows                                        & 'POSSERVER' Server operating system(Windows/Linux)
ServerIP             = 172.16.10.153                                  & 'POSSERVER' Server IP address
ServerPath           = /PosServerPos/PosServer                        & 'POSSERVER' Server path
Serverport           = 8080                                           & 'POSSERVER' Server port

Call code before modification：
import parsecfg
var cfg = loadConfig("Config.ini")
echo cfg.getSectionValue("Server","ServerIP")

Modified call Code：
import parsecfg
var cfg = loadConfig("Config.ini","&")  # When the default annotation symbol is "#;", you can not specify.
echo cfg.getSectionValue("Server","ServerIP")

**Comment by lihf8515** [comment]
If you have no intention of merging and fixing the problem. I will shut it down.thank you!

**Comment by dom96** [comment]
I think you might be better off creating your own ini parser.

**Pull request closed without merging**
