### PR TITLE
fix db_mysql getRow() when column is null error raised

### PR DESCRIPTION
**Pull request by itsumura-h**
If we have following users table in mysql and "email" column have null data

|id|name|email|
|---|---|---|
|1|John|null|

```
echo db.getRow(sql"SELECT * FROM users")
```
expects
```
@["1", "John", ""]
```

However we get an error

```
/nim/lib/impure/db_mysql.nim(310) getRow
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### CODE REVIEW

**Comment by Araq** [comment]
This is not good for performance, better fix ``add(s: string; x: cstring)`` to deal with ``x == nil``.

**Comment by itsumura-h** [comment]
@Araq 
It may works as expected!

**Comment by Araq** [comment]
This commit needs the ``[backport]`` tag.

**Comment by itsumura-h** [comment]
@Araq 
Does it rignt?

https://github.com/nim-lang/Nim/pull/12806/commits/d31305502ac95f86f3ef589ac8fa6e36a9fdec3e

**Pull request merged**
