### PR TITLE
Fixes #5979

### LINKED ISSUE #5979: Cannot cast pointer to char in cpp
```nim
var a: pointer
let b = cast[char](a)
```
```
nim cpp test.nim
```
```
Error: execution of an external compiler program 'clang++ -c  -w  -I/Users/yglukhov/Projects/nim/lib -o /Users/yglukhov/nimcache/test.o /Users/yglukhov/nimcache/test.cpp' failed with exit code: 1

/Users/yglukhov/nimcache/test.cpp:95:30: error: cast from pointer to smaller type 'NIM_CHAR' (aka 'char') loses information
        b_jMbWDpGpOqhqU7TWn5m0uA = ((NIM_CHAR) (a_MKOwYvPH6MkTSfJQoSvUmg));
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

### PR DESCRIPTION
**Pull request by yglukhov**

### CODE REVIEW

**Comment by yglukhov** [comment]
Slightly extended the test to better demonstrate the use case.

**Comment by yglukhov** [comment]
Test failure looks unrelated. Can anyone restart please?

**Comment by markus-oberhumer** [comment]
Please emit this extra `ptrdiff_t` cast for C as well.

**Comment by yglukhov** [comment]
@markus-oberhumer, why? C can cast directly just fine. Also I'm not sure if `ptrdiff_t` is defined by every C compiler.

**Comment by markus-oberhumer** [comment]
Most C compilers emit warnings (but not errors) on this type of cast, it is safer, and it also avoids semantical differences between the C vs C++ backends.

FYI `ptrdiff_t` is defined in `<stddef.h>` which is available on any (even freestanding) C/C++ compiler.

(BTW, the correct type would be `uintptr_t`, but that is not portable to older compilers and it does not matter in practice).

**Comment by yglukhov** [comment]
Ok, done.

**Comment by krux02** [comment]
Well wasn't the consent in the original issue that the compiler message of Nim should be improved to what some backend compilers report, an error instead of silencing everything?

**Pull request merged**
