### PR TITLE
Documentation update nims.rst

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Update `nims.rst` to add modules that work on NimScript as mentioned in the `changelog.md`.
- Documentation only.

### CODE REVIEW

**Comment by timotheecour** [comment]
not opposed to this PR, but that's not DRY and not enforced (so is guaranteed to become out of sync); if possible I'd rather have something that's enforced, why not either link to tests/test_nimscript.nims or add some logic to auto-generate those links from that file?

**Comment by juancarlospaco** [comment]
@timotheecour 
This PR is meant to be *documentation only*. But I added the link to the test.
But it says "At least these modules should work", so is explicit that may not be the exact list whatsoever.

If you know how to do "some logic to auto-generate those links" feel free to send PR, sounds like a cool idea.

**Comment by timotheecour** [comment]
> If you know how to do "some logic to auto-generate those links" feel free to send PR, sounds like a cool idea.

yes there is: see https://github.com/nim-lang/Nim/pull/14687 WIP; it generates a html file with all imports as clickable links via doc gen

**Comment by juancarlospaco** [comment]
Thats a nice idea!.
:)

**Pull request merged**
