### PR TITLE
fixes #12652

### LINKED ISSUE #12652: Race condition in asyncdispatch.closeSocket on Unix
closeSocket's unix implementation first closes the socket handle, making it available for OS to allocate to the process for other purposes, then invokes callbacks, which call `recv` and `send` on the same handle. This makes it possible for recv and send to read/write data from/to another socket or file or whatever is re-bound to the same handle, if there are other threads opening files/sockets. This opens up a way for unexpected behavior and security vulnerabilities.

The code is: https://github.com/nim-lang/Nim/blob/f22d3c75aa68833ae1b01d747d0c71074ccef310/lib/pure/asyncdispatch.nim#L1269 and https://github.com/nim-lang/Nim/blob/devel/lib/pure/asyncdispatch.nim#L1273

As a side note, if read cb throws an exception, which is possible, since it calls user code, then the subsequent callbacks in the list will be leaked, i.e. if something awaits a send on the same socket, it will await forever. I don't think that is the desired behavior here.

### PR DESCRIPTION
**Pull request by Araq**
backport? Note: This is unlikely to be correct.

### CODE REVIEW

**Comment by dom96** [comment]
I think the best short-term fix is to introduce a lock around this code. If it turns out to be slow we can work on a better long-term solution, but until then let's prevent the race condition.

**Comment by Araq** [comment]
Cool, but we don't have async locks. ;-)

**Comment by narimiran** [comment]
> my test (tasyncclosestall) works

That test is really flaky (I'm not talking about this PR, but generally) and causes a lots of false positives with CIs, which are then solved by restarting the failed backend(s). Is there a way to make it more reliable?

**Comment by Araq** [comment]
Also, the Windows version of ``closeSocket`` does not handle any callbacks at all. Why is it required for Posix?

**Comment by dom96** [comment]
> Cool, but we don't have async locks. ;-)

huh? We don't need those in this case, unless I'm missing something.

**Comment by dom96** [comment]
> Also, the Windows version of closeSocket does not handle any callbacks at all. Why is it required for Posix?

POSIX/BSD have a different Async IO API (polling) vs. Windows' IOCP.

**Comment by dom96** [comment]
> That test is really flaky (I'm not talking about this PR, but generally) and causes a lots of false positives with CIs, which are then solved by restarting the failed backend(s). Is there a way to make it more reliable?

Oh, I wasn't aware of that, sorry to hear that. I'm guessing that in some cases the CI machines are under load and so [the 5s timeout](https://github.com/nim-lang/Nim/blob/devel/tests/async/tasyncclosestall.nim#L17) that's in the test isn't enough, can we try increasing it?


As a side note, it's disappointing that no CI company has yet cracked this and implemented infra that shames people who implement flaky tests.

**Pull request closed without merging**
