### PR TITLE
Update docgen style

### PR DESCRIPTION
**Pull request by FedericoCeratto**
Switch to Lato font for better readability
Make text darker
Make spacing between paragraph and pre block consistent

Example: https://cdn.rawgit.com/FedericoCeratto/db002f193d0f8ba311aab883adf7e9d3/raw/184a941377338094e82942c8f84631775bf1e4c3/httpclient.html

### CODE REVIEW

**Comment by Yardanico** [comment]
IMO new doc comments look somewhat worse:
image

**Comment by Araq** [comment]
I really like this improvement. Who else wants to vote?

**Comment by andreaferretti** [comment]
I slightly prefer the old version. The font seems to have a little more spacing and too dark text stand out too much

**Comment by narimiran** [comment]
More contrast is always nice readability-wise and should be applauded, but the new version of text font looks a bit "too heavy" - can font-weight maybe be slightly smaller value?

**Comment by dom96** [comment]
I think that's a side effect of making the text darker. I do like this change though. Not sure about the new font.

**Comment by FedericoCeratto** [comment]
Tweaked colors and kerning, fixed search input box to prevent overlapping with text:
https://screenshots.firefoxusercontent.com/images/0f63674f-e6c1-40ad-a294-27e0e8a14dbd.png

**Comment by Araq** [comment]
Can you please rebase @FedericoCeratto ? We should merge it, it's a good improvement.

**Pull request merged**
