### PR TITLE
fixes #20219; ignore comment/empty node in stmtListExpr

### LINKED ISSUE #20219: `x < 1 (and|or) b` generates temp variables in js output
### What happened?

```nim
proc f(x: int): int {.exportc.} =
  if result > 5 and result < 10:
    discard
```
`nim js -d:danger`
```js
function f(x_0) {
  var temporary_1;
  var result_0 = 0;

  if (!(5 < result_0)) {
    temporary_1 = false;
  } else {
    temporary_1 = (result_0 < 10);
  }
  if (temporary_1) {}

  return result_0;
}
```
it should generate:
```js
function f(x_0) {
  var result_0 = 0;

  if (((result_0 > 5) && (result_0 < 10))) {}

  return result_0;
}
```
https://github.com/nim-lang/Nim/blob/d2318d9ccfe69e21d0517f0448a6469a18b69513/compiler/jsgen.nim#L335
```nim
p.isSimpleExpr(a) == false  # result > 5 also with >= and != infix or call syntax
p.isSimpleExpr(b) == true  # result < 10
```

### Nim Version

1.7.1

### Current Standard Output Logs

_No response_

### Expected Standard Output Logs

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #20219

### CODE REVIEW

**Comment by Varriount** [comment]
What happens in the following scenario?
```nim
var a = 1

proc incrementSideEffect: bool =
  inc(a)
  return true

proc main =
  if incrementSideEffect():
    discard

  echo a
```

**Comment by ringabout** [comment]
> What happens in the following scenario?

It works as expected and prints 2

```js
function main_452984840() {
  if (incrementSideEffect_452984834()) {
  }
  rawEcho(HEX24_318767107(a_452984833[0]));
}
```

`incrementSideEffect` is not a simple expression because it contains two statements.

**Comment by ringabout** [comment]
> What happens in the following scenario?

It works as expected and prints 2

```js
function main_452984840() {
  if (incrementSideEffect_452984834()) {
  }
  rawEcho(HEX24_318767107(a_452984833[0]));
}
```

`incrementSideEffect` is not a simple expression because it contains two statements.

**Comment by AmjadHD** [comment]
A case statement seems more suitable:
```nim
proc isSimpleExpr(p: PProc; n: PNode): bool =
  # calls all the way down --> can stay expression based
  case n.kind
  of nkCallKinds, nkBracketExpr, nkDotExpr, nkPar, nkTupleConstr, nkObjConstr, nkBracket, nkCurly:
    for c in n:
      if not p.isSimpleExpr(c): return false
    result = true
  of nkStmtListExpr:
    for i in 0..<n.len-1:
      if n[i].kind notin {nkCommentStmt, nkEmpty}: return false
    result = isSimpleExpr(p, n.lastSon)
  elif n.isAtom:
    result = true
  else: discard
```

**Comment by ringabout** [comment]
> A case statement seems more suitable:

A following up PR is welcome! First we make it correct, then we can make it even faster.

**Pull request merged**
