### PR TITLE
remove duplication in asynchttpserver examples

### PR DESCRIPTION
**Pull request by timotheecour**
fixes bug 2 in https://github.com/nim-lang/Nim/issues/16506#issuecomment-752238571

followup after https://github.com/nim-lang/Nim/pull/16580
can test server with:
`nim doc -r --doccmd:-d:nimAsynchttpserverEnableTest lib/pure/asynchttpserver.nim`

### CODE REVIEW

**Comment by narimiran** [comment]
So, instead of some code duplication, we now have a runnable example which most likely will never be run.

People found the previous bug just by copy-pasting and running the example. If they do the same now, nothing will happen because of `if` (!) `defined`,  with no mention in the example when this condition is true, i.e. how to enable it.

**Comment by timotheecour** [comment]
`--docCmd` is documented already; in any case I've added a comment to show how to run this; no copy paste needed. And anyone with more than a few hours of experience with nim should know how to pass `-d:foo` on cmdline. Much better than duplication anyways.

**Comment by Araq** [comment]
Why is this an ``if defined``? What's wrong wtih ``when defined``?

**Review by ringabout — APPROVED** [review]

**Comment by timotheecour** [comment]
@Araq 
> Why is this an if defined? What's wrong wtih when defined?

it's intentional, otherwise the code is never semchecked and makes the runnableExamples much less useful for CI; it's a good pattern IMO, to use whenever we want the example to keep compiling but not run by default unless a flag is specified

case in point: see https://github.com/nim-lang/fusion/pull/67 (just today), where a bug was found thanks to `  if defined(fusionJsFormdataTests):` being used instead of `  when defined(fusionJsFormdataTests):` in runnableExamples

**Comment by ghost** [comment]
IMO that example will be very confusing for people who read asynchttpserver's docs. I understand that it reduces code duplication, but generally, the examples in stdlib that we have don't need to be run from the module itself.

**Pull request merged**
