### PR TITLE
add os.hardlinkCount

### PR DESCRIPTION
**Pull request by timotheecour**
refs [How to detect a hard link in Nim? - Nim forum](https://forum.nim-lang.org/t/7573)

also added an informative `runnableExamples`

### CODE REVIEW

**Comment by c-blake** [comment]
Personally, I think just promotion/advertisement of `getFileInfo` & friends is probably enough.

**Comment by timotheecour** [comment]
> Personally, I think just promotion/advertisement of getFileInfo & friends is probably enough.

Let's see what other people think; I think it's a reasonable API to have, but I'm open to modifying this PR to instead add documentation for `getFileInfo` showing it can be used to find number of hard links, along with the runnableExample's from this PR, it illustrates the concepts well IMO.

**Comment by juancarlospaco** [comment]
If people need it, I like it. :+1: 
Ok to add more documentation elsewhere too.

**Comment by timotheecour** [comment]
vote as reply to this comment: 
+1 to introduce os.hardlinkCount
-1 to not introduce os.hardlinkCount (and instead resort to document/runnableExamples)

**Comment by c-blake** [comment]
FWIW, the forum question was answered by an existing API call.  It is quite rare that just knowing something has hard links is interesting.  The way the question was phrased threw a couple of us off track.

It's more common to test sameness (to say avoid copying a file onto itself or insist on distinctness for other reasons) or to want to find all the names/references to any given hard link or all given (as I just roughly sketched in the same forum post) to maybe delete dups or at least know of them.

As already mentioned in the forum, at least on Unix, every directory is a hard link by a simple link count inequality test.  So, any real use of this would *also* be testing `FileInfo.kind` as well.  The user would be better off doing their own `getFileInfo` just once.  *Or* the impl here could add 1 for the test for dirs only (> 2) making it that much more complex, and still being "about something else" (at least on Unix) like how many subdirs, not whether an admin has hardlinked two dirs together.  So, the potential for confusion/complexity seems unbalanced by the payoff of answering an almost never interesting question (already answerable with `getFileInfo` and almost no logic, but a reasonable assumption of user knowledge of FSes already warned about in the doc comment for `getFileInfo`).

Also, given that the forum problem was basically "API call not found (probably from all the noise)", adding more noise via a wider API of very uncommonly needed calls seems unlikely to help and might even hurt.  Just my $0.02.

**Comment by timotheecour** [comment]
OK, convinced, I'll update this PR to instead document that getFileInfo can be used to count the number of hard links (making it more searchable) inside a runnableExamples for `createHardlink` instead

**Comment by Araq** [comment]
Just create a new PR for that then, the queue is filling up, sorry.

**Pull request closed without merging**
