### PR TITLE
Refine raises list in osproc

### PR DESCRIPTION
**Pull request by planetis-m**
With these changes procs in `osproc` no longer list the parent class `Exception`.

PR submitted through the Edit link...

### CODE REVIEW

**Comment by planetis-m** [comment]
nim c koch builds in my machine with both panics:on/off

**Comment by Araq** [comment]
Correct but our CIs boot from an old Nim which complains:

Nim\Nim\lib\pure\streams.nim(126, 27) Error: can raise an unlisted exception: Defect

**Comment by Araq** [comment]
Now that we use a more recent Nim for bootstrapping this should be done. Ping @ringabout @planetis-m

**Comment by ringabout** [comment]
Sure, I will rebase this PR.

**Pull request closed without merging**
