### PR TITLE
ODBC db Error 24000, But the cmd was executed successfully

### PR DESCRIPTION
**Pull request by Angluca**
Maybe it is warning, Otherwise, The database will be disconnected in dbError proc.

### CODE REVIEW

**Comment by Araq** [comment]
Can you elaborate on what this fixes?

**Comment by Angluca** [comment]
Even if the db error 24000, Also to run change db correctly.

**Comment by dom96** [comment]
Is there any documentation you could link us to that describes these errors?

**Comment by Varriount** [comment]
Since there's been no input on the particular PR, and [this](http://www.easysoft.com/developer/interfaces/odbc/sqlstate_status_return_codes.html#24000) page says the 24000 *is* an error (invalid cursor state), I'm closing this PR.

**Comment by enthus1ast** [comment]
I had this error with ODBC and a sybase database, a few days ago, with freshest nim installation, so its still in there! (the invalid cursor state).

**Comment by Varriount** [comment]
@enthus1ast You agree with my reasoning? Or do you mean that this is an actual bug?

**Comment by enthus1ast** [comment]
I don't know if i agree.
i can only test this code on production systems, dupdidu.... but this example:
```
import db_odbc
var db = open("datasource", "user", "pw", "")
db.exec(sql"""UPDATE "rubbish".sometable SET date_of_birth = 'Jan 1, 1980 12:00:00 AM';""")
db.close()
```
failes with:
```
C:\Users\rubbish\Desktop>fixMissing.exe

Error: 24000 [Sybase][ODBC Driver]Invalid cursor state
Traceback (most recent call last)
fixMissing.nim(15) fixMissing
db_odbc.nim(264)         exec
db_odbc.nim(240)         prepareFetchDirect
db_odbc.nim(172)         sqlCheck
db_odbc.nim(168)         dbError
Error: unhandled exception: ODBC Error [DbError]
```
the db entries where updated.
But think it should not fail like this?

**Comment by Varriount** [comment]
Well, whether any rows are updated is up to the database backend. I'm assuming this is a case of undefined/implementation-specific behavior. Should such a statement execute successfully?

**Pull request closed without merging**
