### PR TITLE
Add links to documentation

### PR DESCRIPTION
**Pull request by FedericoCeratto**
Related to #4219

This is a basic example. In future docgen could understand links between pages and allow users to easily add new ones.

### CODE REVIEW

**Comment by bluenote10** [comment]
:+1: Very good idea. A few things we could change:

- Add a link to "Standard Library" as well?
- Style: The list entries have an indentation and look like TOC sections. Looks a bit strange strange, especially since the search bar below is not indented. As a simple work-around you could just remove the `simple-toc` class.
- Probably we should not re-use the `id="toc-list"`, because that's already the ID of the `ul` below.

**Comment by FedericoCeratto** [comment]
@bluenote10 if there's interest in the PR I'll fix the style.

Poll: should URLs and URL descriptions be specified in an ordered table instead of having users fiddle with the HTML?

**Comment by Araq** [comment]
I like this, but we also need an "up" button somehow.

**Comment by FedericoCeratto** [comment]
@Araq a button to scroll back to the top of the page or to go up in a hierarchy? Right now there does not seem to be a hierarchy.

**Comment by FedericoCeratto** [comment]
Updated.

**Comment by bluenote10** [comment]
Yes, looks good to me. FYI for easier reviewing:

image

As a next step we could add the same links to the manual, standard library, and theindex page as well, so that navigating between these three gets easier.

**Comment by Araq** [comment]
>  go up in a hierarchy? Right now there does not seem to be a hierarchy.

Go up in a hierarchy. Well, go to "library overview" etc.

**Comment by Araq** [comment]
Ok, this is pretty good, but should be within an ``@if boot``  switch so that other users of the docgen do not have to patch their config. ``koch`` or ``nimweb`` then need to define ``-d:boot`` when building the documentation.

**Comment by FedericoCeratto** [comment]
@Araq - done.

**Comment by Araq** [comment]
Why was this merged? Where is the addition of ``-d:boot`` in Nim's build system?

**Pull request merged**
