### PR TITLE
support skip ci  in azure pipelines, and support it properly in github actions pipelines

### PR DESCRIPTION
**Pull request by timotheecour**
* `skip ci` now works in azure pipelines; it was tricky to implement (see https://github.com/microsoft/azure-pipelines-agent/issues/2944 long standing upstream feature request) but the way I implemented it seems to work
* `skip ci` now works properly in github actions

in both cases, whether CI is triggered or not after pushing a commit now depends only on the last commit pushed; before this PR azure completely ignored `[skip ci]`, and github actions would honor `[skip ci]` as a default behavior, but would also incorrectly skip CI if head commit of a PR would contain `[skip ci]`, even if latest commit didn't contain it, which didn't make sense, in particular for WIP work that sometimes starts with `[skip ci]` and then has subsequent commits where CI is intended to run. Note that github actions still also considers the PR title for presence of `[skip ci]`; I haven't changed that behavior but future work can harmonize this with azure pipelines

## example
after `[skip ci] example of a commit that skips CI` commit:
* github actions pipeline are skipped (as was case before this PR)
* azure pipeline starts, and the step `Check whether to skip CI` step are skipped:` completes with with an (intended) failure:
```
commitMsg: [skip ci] example of a commit that skips CI
##[error]Bash exited with code '1'.
Finishing: Check whether to skip CI
```
and then subsequent steps are skipped, ending in 
CI for azure completes in only 47 seconds with an error (as intended), and all steps after the `Check whether to skip CI` step are skipped, and pipeline ends with an error
* CI comples in 47 seconds:
image

### CODE REVIEW

**Comment by timotheecour** [comment]
ping @xflywind

**Comment by timotheecour** [comment]
ping @Araq , even your PR's have `[skip ci]` (eg https://github.com/nim-lang/Nim/pull/17784); after this PR, `[skip ci]` will actually work

**Comment by Araq** [comment]
Can't review it as I have no idea what these things do. "Insert rant here about how this form of 'declarative' programming is a mental illness".

**Comment by timotheecour** [comment]
> Can't review it as I have no idea what these things do. "Insert rant here about how this form of 'declarative' programming is a mental illness".

and yet this is what we're stuck with, see my own rant here: https://github.com/microsoft/azure-pipelines-agent/issues/2944, but after reaching the 1 year mark and no sign of upstream action, I decided it's more productive to fix things on our end. The PR should work as advertised, as shown in intermediate commmits; if for some reason it doesn't we can always revert.

the key part is `git log --no-merges -1 --pretty=format:"%s"` which retrieves the latest commit message, while skipping the merge commit for PRs, so that we can detect presence of a keword like `[skip ci]`. The rest is just boilerplate that's hard to avoid in a declarative programming setting.

**Pull request merged**
