### PR TITLE
fix #14421 items uses lent T

### LINKED ISSUE #14421: `items` is 20%~30% slower than iteration via an index
The items iterator for sequence is very slow compared to iterating via index.

This is particularly visible on objects that are around 1 cache-line (64 byte) (probably because they flush the items that were prefetched during the iteration.

```Nim
import math, strformat
import random, times

proc warmup*() =
  # Warmup - make sure cpu is on max perf
  echo "Running warmup to ensure CPU is on max perf if using dynamic frequency"
  let start = cpuTime()
  var foo = 123
  for i in 0 ..< 300_000_000:
    foo += i*i mod 456
    foo = foo mod 789

  # Compiler shouldn't optimize away the results as cpuTime rely on sideeffects
  let stop = cpuTime()
  echo &"Warmup: {stop - start:>4.4f} s, result {foo} (displayed to avoid compiler optimizing warmup away)\n"

warmup()

# --------------------------------------------------------

type
  BigTypeSizeCacheLine = object
    # A big ype that almost fill a cache line
    x, y, z: float64
    r: float64
    u, v, w: float64

  VariantKind = enum
    kBig

  VariantCacheLine = object
    # A variant that takes the full cache line (due to padding)
    case kind: VariantKind
    of kBig:
      b: BigTypeSizeCacheLine

let n = 1_000_000_0000

proc initBigTypes(): seq[VariantCacheLine] =
  for i in 0 ..< 10000:
    result.add VariantCacheLine(
      kind: kBig,
      b: BigTypeSizeCacheLine(
        x: rand(1.0), y: rand(1.0), z: rand(1.0),
        r: rand(1.0),
        u: rand(1.0), v: rand(1.0), w: rand(1.0)
      )
    )

proc checkValue(big: BigTypeSizeCacheLine) =
  # Fake work that cannot be optimized away (without a prover)
  doAssert sqrt(
    big.x * big.y * big.z *
    big.r *
    big.u * big.v * big.w
  ) <= 1.0

proc checkValue(variant: VariantCacheLine) =
  case variant.kind
  of kBig:
    checkValue(variant.b)

proc with_iterator(): float64 =
  let s = initBigTypes()

  let t = cpuTime()
  for big in s: # <-------------------
    checkValue(big)

  result = cpuTime() - t

proc with_index(): float64 =
  let s = initBigTypes()

  let t = cpuTime()
  for i in 0 ..< s.len:
    checkValue(s[i])

  result = cpuTime() - t

proc main_cacheline() =
  let it = with_iterator()
  let idx = with_index()

  echo "---------- 56 bytes (+1-byte tag + padding) ----------------"
  echo "Iterator: ", round(it*1e3, 3), " ms"
  echo "Index: ", round(idx*1e3, 3), " ms"
  echo "Speedup: ", round((it - idx)/it * 100, 2), "%"

main_cacheline()

# -------------------------------------------------------------

type
  CryptoPrimitive = object
    # A 512-bit cryptographic primitive (for example a message signature)
    hash: array[64, byte]


  VariantCrypto = object
    # A variant that distinguish between raw unvalidated data
    # and crypto verified data
    case validated: bool
    of true:
      sig: CryptoPrimitive
    of false:
      raw: array[64, byte]

proc initCrypto(): seq[VariantCrypto] =
  for i in 0 ..< 1024:
    result.add VariantCrypto(
      validated: bool(i mod 2)
    )
    if result[^1].validated:
      for j in 0..<64:
        result[^1].sig.hash[j] = byte rand(255)
    else:
      for j in 0..<64:
        result[^1].raw[j] = byte rand(255)

proc checkValue(big: VariantCrypto) =
  # Fake work that cannot be optimized away (without a prover)
  var sum = 0
  if big.validated:
    for i in 0 ..< 64:
      sum += int(big.sig.hash[i])
  else:
    for i in 0 ..< 64:
      sum += int(big.raw[i])

  doAssert sum <= 255 * 64

proc with_iterator_crypto(): float64 =
  let s = initCrypto()

  let t = cpuTime()
  for big in s: # <-------------------
    checkValue(big)

  result = cpuTime() - t

proc with_index_crypto(): float64 =
  let s = initCrypto()

  let t = cpuTime()
  for i in 0 ..< s.len:
    checkValue(s[i])

  result = cpuTime() - t

proc main_crypto() =
  let it = with_iterator_crypto()
  let idx = with_index_crypto()

  echo "---------- 64 bytes (+1-byte tag) ----------------"
  echo "Iterator: ", round(it*1e3, 3), " ms"
  echo "Index: ", round(idx*1e3, 3), " ms"
  echo "Speedup: ", round((it - idx)/it * 100, 2), "%"

main_crypto()
```

Benchmark on my machine, repeated 5 times via a bash for loop
image

Looking into the generated C code (with -d:danger) this is due to an extra assignment:

```Nim
N_LIB_PRIVATE N_NIMCALL(NF, with_iterator_crypto__7ulxTAN69bbjasPZaf5U4Dw_3)(void) {
	NF result;
	tySequence__iksy5MLCk8g4iIFr3fb9bPw* s;
	NF t;
	NF T5_;
	result = (NF)0;
	s = initCrypto__dx4Aan6xsXcnZXf3lg5Z5w();
	t = cpuTime__9aodCrWXscOGeNVh2cpuZkw();
	{
		tyObject_VariantCrypto__K8mK9cICDx26SlWO8siUc9cw big;
		NI i;
		NI L;
		NI T2_;
		nimZeroMem((void*)(&big), sizeof(tyObject_VariantCrypto__K8mK9cICDx26SlWO8siUc9cw));
		i = ((NI) 0);
		T2_ = (s ? s->Sup.len : 0);
		L = T2_;
		{
			while (1) {
				if (!(i < L)) goto LA4;
				big = s->data[i];  // <------------------
				checkValue__Y9b2ugRAezbQJvLN60hHNmw((&big));  // <------------------
				i += ((NI) 1);
			} LA4: ;
		}
	}
	T5_ = (NF)0;
	T5_ = cpuTime__9aodCrWXscOGeNVh2cpuZkw();
	result = ((NF)(T5_) - (NF)(t));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, with_index_crypto__7ulxTAN69bbjasPZaf5U4Dw_4)(void) {
	NF result;
	tySequence__iksy5MLCk8g4iIFr3fb9bPw* s;
	NF t;
	NF T5_;
	result = (NF)0;
	s = initCrypto__dx4Aan6xsXcnZXf3lg5Z5w();
	t = cpuTime__9aodCrWXscOGeNVh2cpuZkw();
	{
		NI i;
		NI colontmp_;
		NI T2_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		T2_ = (s ? s->Sup.len : 0);
		colontmp_ = T2_;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < colontmp_)) goto LA4;
				i = i_2;
				checkValue__Y9b2ugRAezbQJvLN60hHNmw((&s->data[i])); // <------------------
				i_2 += ((NI) 1);
			} LA4: ;
		}
	}
	T5_ = (NF)0;
	T5_ = cpuTime__9aodCrWXscOGeNVh2cpuZkw();
	result = ((NF)(T5_) - (NF)(t));
	return result;
}
```

## Recommendation
The iterator should return ``lent`` which is dependent on #14420

### PR DESCRIPTION
**Pull request by timotheecour**
* fixes https://github.com/nim-lang/Nim/issues/14421
`items` now has no overhead over mitems or over access via index `myseq[i]`

looks like only 1 test fails:
```
/Users/runner/runners/2.262.1/work/Nim/Nim/pkgstemp/zero_functional/zero_functional.nim(1624, 16)
  Error: '__it__0' is of type <lent seq[uint8]> which cannot be captured as it would violate memory safety, declared here: 
/Users/runner/runners/2.262.1/work/Nim/Nim/pkgstemp/zero_functional/zero_functional.nim(1624, 16)
```

## note
* this causes alloc/dealloc in stat reports to decrease, as expected

## future PR's
- [ ] extend `lent T` to more iterators and procs
- [ ] refine logic to only use `lent` when `T.sizeof` is small (eg, fits in a register) since pass by value won't incur cost in this case;
eg: ptr|ref|pointer|cstring
- [ ] auto-box for var/lent refs https://github.com/nim-lang/Nim/pull/14447#issuecomment-635817921

### CODE REVIEW

**Comment by mratsim** [comment]
I think NimVersion should be its own PR and lent iterators should be serated to depend on it.

**Comment by timotheecour** [comment]
ya I'll do that; i can use "yet another" condsym until nimVersion+nimVersionCT

**Comment by timotheecour** [comment]
@michael72 this PR enables faster `items` but the only test failing with this PR is `nim c -r zero-functional/test`

Error: '__it__0' is of type <lent seq[uint8]> which cannot be captured as it would violate memory safety
```
/Users/timothee/git_clone/nim/zero-functional/test.nim(19, 5) template/generic instantiation from here
/Users/timothee/git_clone/nim/zero-functional/zero_functional.nim(1625, 16) Error: '__it__0' is of type <lent seq[uint8]> which cannot be captured as it would violate memory safety, declared here: /Users/timothee/git_clone/nim/zero-functional/zero_functional.nim(1625, 16)
      ext.node = quote do:
```

I'd appreciate your help here.

I've narrowed it down to this:
```nim
import zero_functional

proc main =
  let bu = @[@[1u8, 2u8], @[3u8]]
  let b = bu --> map(it --> to(seq[int], true))
  # let b = bu --> map(it --> it)
main()
```

zero-functional code is rather hairy (macros calling macros calling macros) so it's hard to debug; After inserting some `repr` in your macros I'm suspecting it's happening for this:
```nim
(proc (): auto =
  var res`gensym36580008: seq[int]
  result = zfInit(res`gensym36580008)
  for __it__0 in __it__0:
    discard
    let __it__1 = __it__0
    zfAddItemChk(result, -1, __it__1, "seq[uint8]", "seq[int]", true))()
```

any help would be appreciated, including a minimal example that doesn't involve zero-functional code;

**Comment by mratsim** [comment]
`__it__0` should become an argument to the proc (to avoid closure check) and zero-functional can call  `anonymousProc(__it__0)` instead of `anonymousProc()`

**Comment by Araq** [comment]
Does this imply we want the borrowing rules in-place as soon as possible?

**Comment by timotheecour** [comment]
well I'm not sure how fast is "as soon as possible" so how about I introduce a temporary opt-out (as opposed to opt-in), eg: `nim c -r -d:nimWorkaround14447 zero-functional/test` ?
so most code will benefit from speedup, and code that breaks as above can use `-d:nimWorkaround14447` ; and once the compiler allows that, `-d:nimWorkaround14447` becomes a noop.

`-d:nimWorkaround14447` would simply prevent `lent` in iterators.nim

and I can mention `-d:nimWorkaround14447` in error message `which cannot be captured as it would violate memory safety` as a possible action (even though it won't apply to all cases)

**Comment by michael72** [comment]
@timotheecour 

> ```nim
> import zero_functional
> 
> proc main =
>   let bu = @[@[1u8, 2u8], @[3u8]]
>   let b = bu --> map(it --> to(seq[int], true))
>   # let b = bu --> map(it --> it)
> main()
> ```

In order to help I need some more information - could you be more specific?
I downloaded your branch, compiled it, installed it as my main nim, recompiled test.nim in zero_functional - no error, just a warning. I'll look into that.

But could you point me to the specific build error - I don't get it. There seem to be several libraries involved.
Your test program also compiles.

Btw - there is a simple macro `->>` that prints better debug output.
https://github.com/zero-functional/zero-functional#debugging-using---

**Comment by timotheecour** [comment]
> In order to help I need some more information - could you be more specific?

* are you sure you're using zero-functional HEAD and not some installed version? 
* what's `nim -v` ?

here are detailed instructions to reproduce:
```
git clone https://github.com/alehander42/zero-functional && cd zero-functional
nimble develop # makes sure it uses head and not some installed version

cd pathto/nim 
git fetch origin pull/14447/head && git checkout FETCH_HEAD # fetch my branch
# rebuild nim either with `./koch boot -d:release` if you're patient or `bin/nim_csources c -o:bin/nim_temp -d:release --lib:lib --hints:off compiler/nim.nim` if you're not
```

```
bin/nim_temp r t10841.nim # test case I mentioned above in https://github.com/nim-lang/Nim/pull/14447#issuecomment-634627267
=> `Error: '__it__0' is of type <lent seq[uint8]> which cannot be captured as it would violate memory safety, declared here: /Users/timothee/git_clone/nim/zero-functional/zero_functional.nim(1624, 16); using '-d:nimWorkaround14447' helps in some cases`

bin/nim_temp r -d:nimWorkaround14447 t10841.nim # works (but disabled lent optimization globally)
```

> no error, just a warning

i get no warning, just an error ;-) (and so did CI until I added -d:nimWorkaround14447); I'm on OSX but shouldn't matter

> Btw - there is a simple macro ->> that prints better debug output.

thanks that helps, it shows:
```nim
# t10841.nim:17
# bu.zfun:
#   map(it -->> to(seq[int], true))
(proc (): auto =
  {.push, hint[XDeclaredButNotUsed]: off.}
  proc helperProc(): auto =
    for it0 in bu:
      let it1 = it0 -->> to(seq[int], true)
      result = it1

  {.pop.}
  var res_47365200: seq[type(helperProc())]
  result = zfInit(res_47365200)
  for it0 in bu:
    let it1 = it0 -->> to(seq[int], true)
    zfAddItemChk(result, -1, it1, "seq[seq[uint8]]", "", false))()

# t10841.nim:17
# __it__0.zfun:
#   to(seq[int], true)
(proc (): auto =
  var res_47390009: seq[int]
  result = zfInit(res_47390009)
  for it0 in it0:
    let it1 = it0
    zfAddItemChk(result, -1, it1, "seq[uint8]", "seq[int]", true))()

# t10841.nim:17
# __it__0.zfun:
#   to(seq[int], true)
(proc (): auto =
  var res_47570008: seq[int]
  result = zfInit(res_47570008)
  for it0 in it0:
    let it1 = it0
    zfAddItemChk(result, -1, it1, "seq[uint8]", "seq[int]", true))()
```

**Comment by Araq** [comment]
> well I'm not sure how fast is "as soon as possible" so how about I introduce a temporary opt-out (as opposed to opt-in), eg: nim c -r -d:nimWorkaround14447 zero-functional/test ?

We can also patch zero-functional instead. I didn't know that the compiler produces an error message, I thought it produced a corruption. So the borrow rules can wait.

**Comment by timotheecour** [comment]
* turns out there was also ggplotnim, I just sent a PR there https://github.com/Vindaar/ggplotnim/pull/74
* @michael72 is there any way to do a similar fix in your code ? sorry it's still quite a bit hairy to dig in because of multiple levels of macros (even if 
`-->>` helps a lot); basically the simplest (but not necessarily most efficient) fix is to try this:
```nim
for it0 in bu:
  let it0 = it0 # <= add this
  ... rest of code
```
(but that code is generated code, not sure where)

**Comment by michael72** [comment]
@timotheecour I'm not really into quick quickfixes, but here we go.
Seems to be working on your branch - I bumped zero_functional to v1.1.1
hope depending libraries are fixed as well

Cheers

**Comment by michael72** [comment]
@timotheecour @Araq 
I tried to create an example that fails with plain nim code - although atmittedly it is somewhat construed - but hey - that's what zero_functional creates ;-)

I've tried to make it as simple as possible - also using the example code that lead to the crash in the first place:

```nim
proc main =
  let orig = @[@[1u8, 2u8], @[3u8]]
  let converted = (proc (): seq[seq[int]] =
    result = @[]
    for it0 in orig:
        let it00 = it0
        let sublist = (proc (): seq[int] =
            result = @[]
            for i in it0: # it00: # would work!
                result.add(int(i)))()
        result.add(sublist))() 
  echo(converted)
main()
``` 

So this is: take a seq[seq[uint8]] and convert it to seq[seq[int]] - yes, this is more like a "Hey - we can do that to!"

we get:
```log
 Error: 'it0' is of type <lent seq[uint8]> which cannot be captured as it would violate memory safety, declared here: /home/michael/projects/zero-functional/testwas.nim(5, 9); using '-d:nimWorkaround14447' helps in some cases
```

The problematic part I think - and this is regarding this PR - is the inner iterator that accesses the outer iterator `it0` directly from an inner function - needing a direct capture - which with this PR does not work any more. If we assign `it0` explicitly to `it00` and use `it00` inside the inner function then it works.

I kind of "fixed" the problem on zero_functional side by adding this additional indirection - but it is somewhat a workaround, right? On the other hand it is an esoteric use case and iterators, anonymous functions and keeping all the use cases efficiently together probably very tough.

So - think about it. If it leads to speed-ups it's maybe worth it, but in edge cases it is a bit weird behaviour.

**Comment by Araq** [comment]
> I kind of "fixed" the problem on zero_functional side by adding this additional indirection - but it is somewhat a workaround, right? On the other hand it is an esoteric use case and iterators, anonymous functions and keeping all the use cases efficiently together probably very tough.

One solution is to make the compiler auto-box for ``var``/``lent`` types.

**Comment by timotheecour** [comment]
> One solution is to make the compiler auto-box for var/lent types.

* so including `result` magic variable, so that this would work and be safe?
```nim
proc main(): int =
  proc bar() =
    result = 1 # Error: 'result' is of type <int> which cannot be captured as it would violate memory safety
  bar()
echo main()
```
IMO this is safe so long `bar` delegate doesn't escape `main`, and that should use the exact same escape analysis as for `var result`


* oh and here's a minimal example:
@michael72
> I've tried to make it as simple as possible - also using the example code that lead to the crash in the first place:

minimized further:

```nim
proc main() =
  for a in @[1,2]:
    # let a = a # uncomment removes error
    proc bar() =
      discard a # Error: 'a' is of type <lent int> which cannot be captured as it would violate memory safety,
    bar()
main()
```

> but it is somewhat a workaround, right? 

yes but there should be exactly 0 performance penalty from before PR since it results in a copy here `let it00 = it0` instead of here `for it0 in orig:`.

The ideal fix is what detecting when it's safe (no escape) and allowing it.

In the meantime we could have a `template ensureCopy(a): untyped` that I think is generally useful and would only return a copy if `a` is `lent|var`, else would return it as is (no double copy).

**Comment by Araq** [comment]
> so including result magic variable, so that this would work and be safe?

Yeah, so that the error message is no more. Let's shift the complexity to the optimizer where it belongs.

**Comment by ghost** [comment]
Is it intended that this now works (unless you pass ``-d:nimWorkaround14447`` of course)?
```nim
var a = @['a', 'b', 'c', 'd', 'e', 'f']


for x in a:
  x = 'c'

echo a
```
I think it should still somehow be caught at CT and not work

**Comment by timotheecour** [comment]
no it should give CT error; looking into it more, it looks like `lent` is pretty buggy and violates the contract:
=> https://github.com/nim-lang/Nim/issues/14498

**Pull request merged**
