### PR TITLE
outline of how I imagine nkError to work

### PR DESCRIPTION
**Pull request by Araq**

### CODE REVIEW

**Comment by timotheecour** [comment]
Will `nkError` act as a poison node to avoid redundant (cascading) errors piling up as in D (refs https://github.com/nim-lang/Nim/issues/16001#issuecomment-730204018, https://github.com/timotheecour/Nim/issues/381) ?

this should be testable with `--errormax:10` and ensuring only non-redundant errors are generated, eg this could mean:
* no tree overlap
* don't generate an error in a parent node if it contains child of kind `nkError`


## example
here's a good test case:

```nim
import dom, bitops
template fn() =
  let x = bitor(0'u32, 0)
fn()
echo fn()
```

currently generates redundant errors:
```
/Users/timothee/git_clone/nim/Nim_devel/lib/js/dom.nim(14, 10) Error: This module only works on the JavaScript platform
..
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11800.nim(8, 3) template/generic instantiation of `fn` from here
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11800.nim(7, 16) Error: expression '' has no type (or is ambiguous)
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11800.nim(8, 3) template/generic instantiation of `fn` from here
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11800.nim(7, 7) Error: 'let' symbol requires an initialization
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11800.nim(9, 8) template/generic instantiation of `fn` from here
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11800.nim(7, 16) Error: expression '' has no type (or is ambiguous)
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11800.nim(9, 8) template/generic instantiation of `fn` from here
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11800.nim(7, 7) Error: 'let' symbol requires an initialization
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11800.nim(9, 6) Error: type mismatch: got <void>
but expected one of:
proc echo(x: varargs[typed, `$`])
  first type mismatch at position: 1
  required type for x: varargs[typed]
  but expression 'let x`gensym1' is of type: void

```

## related issues
* https://github.com/nim-lang/Nim/issues/16178

**Comment by Araq** [comment]
> Will nkError act as a poison node to avoid redundant (cascading) errors piling up as in D (refs #16001 (comment), timotheecour#381) ?

Yes. But there is also a separate PR that improves ``nim check`` / nimsuggest quite a bit.

**Comment by timotheecour** [comment]
see also:
```nim
proc errorSym*(c: PContext, n: PNode): PSym =
  ## creates an error symbol to avoid cascading errors (for IDE support)
  var m = n
  # ensure that 'considerQuotedIdent' can't fail:
  if m.kind == nkDotExpr: m = m[1]
  let ident = if m.kind in {nkIdent, nkSym, nkAccQuoted}:
      considerQuotedIdent(c, m)
    else:
      getIdent(c.cache, "err:" & renderTree(m))
  result = newSym(skError, ident, nextSymId(c.idgen), getCurrOwner(c), n.info, {})
  result.typ = errorType(c)
  incl(result.flags, sfDiscardable)
  # pretend it's from the top level scope to prevent cascading errors:
  if c.config.cmd != cmdInteractive and c.compilesContextId == 0:
    c.moduleScope.addSym(result)
```

seems like some refactoring with this would be needed

**Comment by Araq** [comment]
Succeeded by https://github.com/nim-lang/Nim/pull/17567

**Comment by timotheecour** [comment]
also:
* things like this:
`newSymNode(errorSym(c, n))`

should be transformed into:

`newErrorNode(...)`

## should also merge with:
```
compiler/semdata: proc errorNode*(c: PContext, n: PNode): PNode
compiler/vm: proc errorNode(idgen: IdGenerator; owner: PSym, n: PNode): PNode =
```

## and update these:
```nim
template rejectEmptyNode(n: PNode) =
  # No matter what a nkEmpty node is not what we want here
  if n.kind == nkEmpty: illFormedAst(n, c.config)
```

**Pull request closed without merging**
