### PR TITLE
Fix crash in terminate handler

### PR DESCRIPTION
**Pull request by valashko**
Calling `throw` inside terminate handler causes undefined behavior. It is mitigated by trying to deduce exception type without rethrowing.

### CODE REVIEW

**Comment by nc-x** [comment]
cc @cooldome, @cdunn2001 & @treeform because of https://github.com/nim-lang/Nim/pull/12275.

**Comment by juancarlospaco** [comment]
Changelog entry.

**Comment by cooldome** [comment]
calling throw in terminate handler is deterministic and  c++ standard complaint .
https://eel.is/c++draft/except.handle#7

It is VS is not standard compliant until 2019 update 3.

**Comment by valashko** [comment]
@cooldome thanks for pointing this out. I still think that a workaround for users of older MSVC versions will be useful, so I reworked this PR to do just that.

**Comment by cdunn2001** [comment]
@nc-x, I don't use VC, and my problem with terminate-handler was solved already, so I've got no comment here.

**Pull request merged**
