### PR TITLE
Remove Nimfix

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Remove Nimrod-to-Nim translator.

### CODE REVIEW

**Comment by timotheecour** [comment]
What if someone wants to revive nimfix? (Not hypothetical, see nimlint work)

**Comment by juancarlospaco** [comment]
This reads **Nimrod** code, and translates it into Nim, I can not find anything anywhere using Nimrod code.
Link 1 *active* project that uses Nimrod on production on 2021. :shrug:

**Comment by juancarlospaco** [comment]
@Araq Ping, because you decided on https://github.com/nim-lang/Nim/pull/16596#issuecomment-754859216 too.
:)

**Comment by timotheecour** [comment]
> Link 1 active project that uses Nimrod on production on 2021. 🤷

my point wasn't about nimrod code (which indeed we don't care about), my point was whether nimfix can be revived for a new repurposed tool that would fix/lint code (ie same goal as nimlint project, but builtin). Maybe there's nothing useful left in nimfix, we'd need to double check.

**Comment by juancarlospaco** [comment]
@timotheecour Ok, then close it if you think it makes things worse.

**Comment by Araq** [comment]
I like it but since @timotheecour wants to keep it, closing for now.

**Pull request closed without merging**
