### PR TITLE
Maps `out` keyword to an nnkIdent. Fixes #6011.

### LINKED ISSUE #6011: The "--" template from module nimscript mis-translates "out" key
In this task from a *.nimble* file
```Nim
task testBuild, "build the tests":
  --path: ".."
  --verbosity: 2
  --out: "tests/apitest"
  setCommand "cpp", "tests/apitest"
```
the `--out` template call is translated to a `--var` option in the executed command string. When `switch "out", "tests/apitest"` is used instead, everything works fine.

### PR DESCRIPTION
**Pull request by dom96**
Quick and hackish, but it's #hacktoberfest season and this works :)

### CODE REVIEW

**Comment by krux02** [comment]
I wasn't aware about the keyword ``out``. As I am aware of it now, it could really turn out to be very useful for my Nim to glsl compiler, since glsl has support for out parameters. I am not sure if this hack would make it impossible.

**Comment by dom96** [comment]
This hack is a good solution for now. Certainly in the future we can enable the ``out`` as a proper keyword with its own node kind. As things stand right now, mapping ``out`` to ``var`` is worse than what this PR does.

**Comment by krux02** [comment]
``out`` and ``var`` parameters are actually very similar. I don't know exactly how the glsl compiler treats them differently, but semantically ``out`` in the parameter list says the function doesn't read from the parameter it just writes into it. I am already compiling ``var`` parameters to ``inout`` parametres and in the current solution ``out`` is indistinuishable from ``var`` and therefore also translated into ``inout``. This magically makes the ``out`` parameters work, even if they are not really supported.

I am just worried that as soon as your hack is in the codebase, it will be impossible to have out parameters for GLSL targets. And a "good" can't be created because it would break nimscript.

Can't you create an alias for ``--out`` that is called ``--outDir`` that doesn't conflict with a keyword in Nim? Or can't you put a hack in that macro that translates ``var`` back to ``out``?

**Comment by Araq** [comment]
Function call syntax with spaces means that new stuff like "sink" does not have to become a keyword and neither does "out", proc foo(x: out int)  is parsed as  proc foo(x: out(int))  which is good enough. So the best option seems to be to remove the "out" keyword altogether, it's not documented to be an alias for "var T" anyway.

**Comment by krux02** [comment]
@Araq My nim to glsl compiler works on the typed syntax tree. So there would be a way to store the "out" tag in the typed ast. But that is unrelated to this PR. I am ok with this PR now.

**Pull request merged**
