### PR TITLE
Add Linux constant SO_BINDTODEVICE

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Araq** [comment]
Why only for lib/posix/posix_linux_amd64_consts.nim?

**Comment by ghost** [comment]
I pulled it out of a Linux header and I don't see a mention of it in the FreeBSD or OpenBSD manpages.

**Comment by Araq** [comment]
So? Linux runs on more than just x86_64...

**Comment by ghost** [comment]
Ah, I did not see how `detect.nim` was generating this file. Fixed.

**Pull request merged**
