### PR TITLE
Add `{.alias.}` pragma

### LINKED ISSUE #466: Pragma to mark symbol-imitating templates/macros
### Title

Symbol-imitating template pragma

### Abstract

Add a pragma (no decided name yet) that marks nullary templates/macros as meant to be called in symbol format.

### Motivation

Nullary templates are often used as an "aliases" to complex paths and addresses:

```nim
type
  B = object
    c: int
  A = object
    b: B
  Foo = object
    a: A

var foo: Foo
template c: untyped = foo.a.b.c
c = 3
echo foo # (a: (b: (c: 3)))
```

However they are still treated as "routines" and are subject to overloading. For example, you can't call them directly as aliases to other procs and other things like [templates not giving redefinition errors in the same scope](https://github.com/nim-lang/Nim/issues/8275) can also cause problems. The point being that distinguishing this use of templates and macros from regular function calls may be desirable, even as a cosmetic annotation with no functional differences.

### Description

There is some old discussion on this but I don't have the links at hand. It's not really big enough of a feature for an RFC but I decided to make one just to flesh it out.

It's likely best for this pragma to not prevent normal nullary templates from being called in symbol form, nor should it require templates that use it to be called in symbol form. It would just mark the *intended* use. Currently it could be used for disallowing redefinitions:

```nim
template foo: int {.symbol.} = 3
template foo: int {.symbol.} = 4 # redefinition error
```

or allowing proc aliases:

```nim
template echo2: untyped = echo
echo2 "hello"
# (echo2)("hello") actually currently works
```

or maybe some different overloading behavior.

But it's fine if none of these get implemented (even the redefinition bug is circumventable by using macros), it can just serve as a guide for users on how to use certain templates/macros, similarly to `{.pure.}`.

### Code Examples

Provided some above, honestly since the pragma being a no-op would also implement this RFC the only guaranteed examples are just the normal uses of [the symbol call feature I've used 10 different names for already](https://nim-lang.github.io/Nim/manual_experimental.html#symbols-as-templateslashmacro-calls).

```nim
type Foo = object
  bar: int

var foo = Foo(bar: 10)
template bar: untyped {.symbol.} = foo.bar
assert bar == 10
bar = 15
assert bar == 15
```

### Backwards Compatibility

If the pragma is a no-op, completely backwards compatible, except old versions would need a shim.

Since it's an opt-in pragma, behavior specific to it is backwards compatible, as long as the behavior of regular templates is kept the same.

However, if desired, the behavior of unmarked templates could be changed to disallow some things, example being like this (modified from https://github.com/nim-lang/Nim/issues/7803):

```nim
type
  Foo = object

proc body(foo: Foo): string = "asd"

block:
  template body: var string = x

  var x = "hello"
  body.add("foobar") # overload error without pragma, works with pragma
```

### PR DESCRIPTION
**Pull request by metagn**
Closes https://github.com/nim-lang/RFCs/issues/466

As described in the RFC, this pragma is optional (therefore backwards compatible), and currently only has the extra behavior of disallowing template redefinitions. This solves the trailing issue from #19406 and the `byaddr` redefinition test is re-enabled.

Changelog and experimental manual also updated.

### CODE REVIEW

**Comment by Araq** [comment]
In the context of v2 wouldn't it be better to require templates/macros to be explicitly overwritten via `.override`? The existing rule has been added without any discussions back then. Backwards compatibility would still be easy to achieve. (People can define an annotation `.override` for old versions that does nothing.)

**Comment by metagn** [comment]
It's just templates that allow redefinitions. I was thinking about that option (it was discussed in #8275) but was not sure about adding 2 new pragmas. Would that only work for templates/macros or can it work for procs/variables as well? In that case maybe `shadow` could be another name.

**Comment by metagn** [comment]
With regard to template redefinitions:

https://github.com/nim-lang/Nim/issues/8275#issuecomment-1213806548

> It turns out a fair amount of packages rely on template redefinitions (tested in https://github.com/nim-lang/Nim/pull/20211). Likely because the implicit behavior of templates being injected and not gensyming inside other templates makes people forget about scoping. Sometimes it's desirable to not open a new scope (as in await).
>
> The biggest issue is that this is really hard to detect. It's not easily searchable, and a lot of testing would be required to fix packages. Maybe redefinitions could be restricted to templates with any typed arguments or overloaded templates.
>
> So I think the most we can do now is make template redefinition a warning, and add the override/redefinition pragma on top of it. (I vote the name redefine despite it not necessarily redefining)

The `alias` pragma erroring on redefinition by default would still be a unique behavior if template redefinition only gives a warning by default. Plus it could still allow redefinitions with the pragma. This doesn't matter too much, the `alias` pragma is mostly a placeholder for potential future behaviors

**Comment by Araq** [comment]
Is this still needed now that we have `.redefine`?

**Comment by metagn** [comment]
It's still useful, just a bit less so. I marked as draft because I thought I could come up with more behaviors for it but I can't think of any right now. Having the annotation exist and adopted in advance would make future ideas for the pragma nicer to implement though, as there would be no need to deal with regular templates.

For now it's mostly useful as a marker, i.e. when you see a routine with this pragma, you will know not to call it with `()`. It can help when debugging macros as well.

I've changed the docs to remove overlap with `redefine` to not cause confusion. This feature should be harmless to add, but it might not be useful enough yet to justify adding.

**Review by Varriount — DISMISSED** [review]

**Comment by metagn** [comment]
There are some possible additions to this PR.

**1. Overloaded aliases**: Currently, overloaded alias templates work if and only if they are the last overload defined (https://forum.nim-lang.org/t/9075). We can easily make them work in situations where the alias template is only overloaded by other templates or macros, which I think makes sense as well. However this is new behavior, so we can tie it to the annotation here to make sure old code works the same, but we technically don't have to tie it to the annotation.

**2. Callable aliases**: `.alias` templates/macros in a call will not be considered in routine overloading, and will be resolved instead.

```nim
template foo: untyped {.alias.} = min

echo foo(-5, 5) # -5
```

A problem arises when `foo` is overloaded, however since overloaded aliases are already somewhat limited, we can compromise a bit. We have a couple options:

1. if the alias template is the last overload of `foo`, resolve it immediately (very easy to implement)
2. if the alias template is the last overload of `foo`, check if it has other overloads, if it doesn't, resolve, otherwise, commence normal overloading (a bit more complex but still fine)
3. give it the lowest priority in normal overloading, only resolve it if no other overloads match

3 is harder to implement and will probably also lead to a worse callOperator situation where it is hard to give good errors. But, we can do 3 after 2 and 2 after 1, so I can do 2 for now, and if I can't I can do 1.

If we don't want to do these additions, then there is basically no need for this PR (I think). But if we want to do them and can't do them now for any reason, the PR can be merged with just the annotation added and no behavior attached, in anticipation of them being implemented later.

**Pull request closed without merging**
