### PR TITLE
Include port in host header as expected

### PR DESCRIPTION
**Pull request by Snowie**
Created this with reference to https://github.com/nim-lang/Nim/issues/3267
Wasn't entirely sure how to test this, let me know if something is wrong

### CODE REVIEW

**Comment by nanoant** [comment]
@Snowie Please squash these 2 commits, there's no use to make commit then make another just to fix the previous one.

**Comment by Snowie** [comment]
Got it! Sorry

**Comment by JCavallo** [comment]
Maybe you should initialize `uri` before line 391 and use it there ?

**Comment by Snowie** [comment]
Ah, I didn't see that Proxy parsed the uri no matter what. I'll change that, then

**Comment by nanoant** [comment]
@JCavallo yeah, that makes sense, we will spare one `parseUri` call when using proxy.

**Comment by JCavallo** [comment]
@Snowie I started a patch for this issue, but you beat me to it :) That's how I knew

**Comment by Snowie** [comment]
Okay, I think that should be it. Changed it to just use r because it was a parsed uri no matter what

**Comment by Araq** [comment]
Ping @dom96

**Comment by dom96** [comment]
Looks good, could you do the same here https://github.com/Snowie/Nim/blob/devel/lib/pure/httpclient.nim#L587?

**Comment by Snowie** [comment]
Ah, woops, I guess I missed generate_headers on my first look through of the code. Changed it and updated the pr.

**Comment by dom96** [comment]
Thanks!

**Pull request merged**
