### PR TITLE
Modified handling of zero precision in formatFloat

### PR DESCRIPTION
**Pull request by bluenote10**
A breaking change, but probably worth to get around the impossibility to round to zero digits.

Also added the suggestion from @dom96 on the previous PR.

- [x] update changelog

### CODE REVIEW

**Comment by konqoro** [comment]
Wat? why? is you need zero precision do `int(f)`.

**Comment by bluenote10** [comment]
That is not the same, because it doesn't do rounding. Also `formatFloat` should behave correctly in the general case. E.g. for the string interpolation stuff I'm working on the formatter would have to generate an unnecessarily complicated AST just to handle 0 vs 1.. correctly (different AST for `fmt"$x%10.0f"` vs `fmt"$x%10.1f"`). Zero precision should be zero digits.

**Comment by konqoro** [comment]
ok cool

**Comment by andreaferretti** [comment]
I agree with @bluenote10. Of course one could always special case rounding to 0 digits, but `formatFloat` should be consistent (consider the case of rounding to `i` digits, when `i` is chosen at runtime)

**Comment by Araq** [comment]
This needs to be mentioned in the changelog. Apart from that, excellent improvement!

**Pull request merged**
