### PR TITLE
Add translation support. Implements #8607

### PR DESCRIPTION
**Pull request by FedericoCeratto**
An initial step to support translation.
This adds the "gentranslation" command to create .pot files and the --language option to "nim doc" to translate documentation.

### CODE REVIEW

**Comment by Araq** [comment]
We don't have translations, it's unclear how to keep translations up-to-date, it's unclear who benefits from worse "google-ability".

**Comment by FedericoCeratto** [comment]
@Araq this was also meant for people to use "nim doc" in their own projects want to provide multi-language documentation.

**Comment by dom96** [comment]
This is a pretty nice implementation. It might not be a priority right now, but we shouldn't close this PR and implying that we will never accept it.

**Comment by dom96** [comment]
Idea to have translations is bad? How so?

**Comment by dom96** [comment]
AFAIK this isn't about translating error messages, but about translating documentation.

Not everybody in this world can speak perfect English and they would greatly benefit from resources to help them learn Nim in their native language. This is by no means an anti-feature.

**Comment by FedericoCeratto** [comment]
For clarification, https://github.com/nim-lang/RFCs/issues/96 is meant to implement translation support both for the compiler itself and any projects written in Nim.

**Comment by krux02** [comment]
I am well aware that not everybody speaks perfect English. But for error messages only a very small subset of English is required.

**Pull request closed without merging**
