### PR TITLE
NIR: Nim intermediate representation

### PR DESCRIPTION
**Pull request by Araq**
Theoretical Benefits / Plans: 

- Typed assembler-like language.
- Allows for a CPS transformation.
- Can replace the existing C backend by a new C backend.
- Can replace the VM.
- Can do more effective "not nil" checking and static array bounds checking.
- Can be used instead of the DFA.
- Easily translatable to LLVM.
- Reasonably easy to produce native code from.
- Tiny memory consumption. No pointers, no cry.

**In very early stages of development.**

Todo:
- [x] Map Nim types to IR types.
- [ ] Map Nim AST to IR instructions:
  - [x] Map bitsets to bitops.
  - [ ] Implement string cases.
  - [ ] Implement range and index checks.
  - [x] Implement `default(T)` builtin.
  - [x] Implement multi string concat.
- [ ] Write some analysis passes.
- [ ] Write a backend.
- [x] Integrate into the compilation pipeline.

### CODE REVIEW

**Comment by Araq** [comment]
Lol, I cannot type "intermediate representation", better only use IR.

**Comment by termermc** [comment]
If it opens the gateway for CPS support, then I'm on board

**Comment by runvnc** [comment]
Does web assembly factor into this at all? I'm sorry if this doesn't seem relevant, but it feels like web assembly runtimes will continue to ramp up in popular use until they rival the deployment level of Java. (And I know that web assembly is not really like assembly).

**Comment by Araq** [comment]
> Does web assembly factor into this at all?

The IR can be translated to web assembly, yes. I have no plans to do that but in general writing a backend against the IR should be easier than previously.

**Comment by xigoi** [comment]
Is it going to help with incremental compilation?

**Comment by Araq** [comment]
It was designed with IC in mind but IC also needs more frontend patches or a new frontend altogether.

First I replace the backend passes, then later (which is really much later) the frontend. In the end not much of the old compiler remains and we have IC.

**Comment by juancarlospaco** [comment]
This can allow for a better Nimsuggest ? 🤔

**Comment by Araq** [comment]
No, nimsuggest is frontend business, this here is for the backend.

**Comment by SirOlaf** [comment]
How is this going to behave with multiple files, will it combine everything into one large list of instructions or is there intended to be some sort of import construct?
I assume it's the latter because you mention IC so as an extension to this, how do you expect it to affect projects like [nimscripter](https://github.com/beef331/nimscripter) and the now very dusty HCR feature of Nim?

**Comment by inv2004** [comment]
Just my opinion, but if it moves Nim from c-backend - it is a bad from my POV, because intermediate C helps a lot pretty often when you dig into perf (and want to match c-lang perf). Debug Ffi bindings and etc.  c-backend is a huge plus of Nim

**Comment by Araq** [comment]
> how do you expect it to affect projects like [nimscripter](https://github.com/beef331/nimscripter) and the now very dusty HCR feature of Nim?

The IR is easy to interpret and if you do that the data types between compiled and interpreted code are mostly compatible so things should become easier for nimscripter.

Yes, the IR has the notion of an "import" from different modules. If you seek to interpret the code, you need to have the imported modules in memory. Loading an IR file into memory is cheap as it is already in a linear format, there is little to do.

**Comment by Araq** [comment]
> Just my opinion, but if it moves Nim from c-backend - it is a bad from my POV, because intermediate C helps a lot pretty often when you dig into perf (and want to match c-lang perf). Debug Ffi bindings and etc. c-backend is a huge plus of Nim

There are no plans to abandon C as compilation target, but instead of the AST the NIR is translated to C.

**Comment by inv2004** [comment]
Translation to llvm means that Nim goes away from c-backend. LLVM is also not positive trend in my opinion.

**Comment by jmgomez** [comment]
@inv2004 and what this means:
> Can replace the existing C backend by a new C backend.

It seems to me like the idea here is to allow for more supported backends rather than less.

**Comment by Vindaar** [comment]
> Translation to llvm means that Nim goes away from c-backend. LLVM is also not positive trend in my opinion.

Pretty sure the "Easily translatable to LLVM" is not meant to _replace_ the standard C / C++ backends. It's just mentioning that this should make work like `nlvm` much simpler.

**Comment by inv2004** [comment]
@Vindaar all I wanted to say - that all the things like asm, wasm, llvm and etc are interesting to play with, but it is 3rd priority to have it, but I was afraid that c-backend have a chance to loose its 1st priority. (Everything with llvm does not have the advantage Nim has)

Also, I do not know, but are there any perf-advantages nlvm gives at the moment? The same is about wasm - are there any visible benefits to have it directly or from llvm compared to have it from generated c-code?

If the IR makes the primary c-backend easier from logical endpoint - perfect

**Comment by bpr** [comment]
Since CPS is mentioned, I'm a bit curious: is the existing Nim CPS project somehow lacking?

Also, because I'm `that guy`, is "No pointers, no cry" a reference to the Bob Marley tune? If so, it would be using the somewhat common misinterpretation of that line as an if-then. Just sayin' ...

**Comment by Araq** [comment]
> Since CPS is mentioned, I'm a bit curious: is the existing Nim CPS project somehow lacking?

I don't know, but CPS is a commonly used IR for functional languages with plenty of benefits for a compiler backend. A macro does not do it full justice.

> Also, because I'm that guy, is "No pointers, no cry" a reference to the Bob Marley tune? If so, it would be using the somewhat common misinterpretation of that line as an if-then. Just sayin' ...

I interpret Bob Marley's line correctly and it's Bob Marley who is wrong. ;-)

**Comment by arnetheduck** [comment]
> Easily translatable to LLVM.

on the surface, it looks like the "instruction set" loses a lot of high-level information that `nlvm` currently uses to generate better code, ie type information (aliasing, alignment and a myriad of other uses), exception handling control flow (for zero-cost eh) etc etc.. unless there's a way to tie it back, it will be very hard to generate _good_ llvm code from this. In llvm, this is solved via metadata annotations that allow the transport of "custom" information across layers as well as magics, annotiations and instructions that allow encoding things like multiple return control flows (like happens with exceptions and setjmp in general).

what's the general plan here? has the approach been documented anywhere?

**Comment by Araq** [comment]
- There is the `Typed` opcode that instructions are annotated with which refers to a C-like type system but without C's array decay quirk. Object sizes and offsets are stored in the type graph which is separated.
- Exception handling control flow is done with the `CheckedGoto` instruction but probably needs a couple of patches before it's good enough for nlvm.

**Comment by Araq** [comment]
No documentation yet, sorry, it's too early and requires much more code being written and tinkering.

**Comment by Araq** [comment]
Further commits in follow-up PRs.

**Comment by SirOlaf** [comment]
Seems to break koch tools with `Nim/compiler/nir/ast2ir.nim(2083, 5) Error: undeclared identifier: 'setFrameMsg'` for `nim_dbg` build step.

**Pull request merged**
