### PR TITLE
fix #8255 numerous issues with splitFile

### LINKED ISSUE #8255: [ospaths] BUG: splitFile("/a.txt").dir = "" ; + other bugs with splitFile
- [ ] bug 1:
nim:
echo splitFile("/a.txt")
(dir: "", name: "a", ext: ".txt") #definitely wrong

python:
os.path.split("/a.txt")
('/', 'a.txt')

- [ ] bug 2:
nim:
echo splitFile("a/")
(dir: "a/", name: "", ext: "") # violates good sense, and also documention: "dir does not end in DirSep. extension includes the leading dot."

python:
os.path.split("a/")
('a', '')

- [ ] bug 6
echo splitFile("a/..")
(dir: "a", name: ".", ext: ".")
should be:
(dir: "a", name: "..")

### PR DESCRIPTION
**Pull request by timotheecour**
/cc @Araq 

* fix https://github.com/nim-lang/Nim/issues/8255
(only the parts referring to splitFile; I'll re-open another issue for the parts related to parentDir)

### CODE REVIEW

**Comment by Araq** [comment]
makes the tester die with Error: unhandled exception: value out of range: -1 [RangeError]

**Comment by timotheecour** [comment]
@dom96 @krux02
> Looks good to me. Happy to merge when tests pass.

please use the label `merge_when_passes_CI`  (eg  https://github.com/nim-lang/Nim/issues?utf8=%E2%9C%93&q=label%3Amerge_when_passes_CI+) which is for that purpose: it allows anyone with merge access rights to merge a PR that has such a label, once PR is green.

**Comment by dom96** [comment]
> please use the label merge_when_passes_CI (eg https://github.com/nim-lang/Nim/issues?utf8=%E2%9C%93&q=label%3Amerge_when_passes_CI+) which is for that purpose: it allows anyone with merge access rights to merge a PR that has such a label, once PR is green.

Huh? You mean it makes these PRs more visible? Users with merge access can currently merge any PR, even if it has failing tests.

**Comment by timotheecour** [comment]
yes, that's what I meant; it's a codified stamp of approval; currently it still requires a manual merge but with https://github.com/nim-lang/Nim/issues/9847 it'll be automated (as done in dlang via their dlang-bot)

**Pull request merged**
