### PR TITLE
subsequent of PR #22359

### PR DESCRIPTION
**Pull request by bung87**
if my understanding right, this fix chronos fails by my previous PR.

### CODE REVIEW

**Comment by bung87** [comment]
fails by `timezones/fetchjsontimezones`  `/home/runner/work/Nim/Nim/lib/pure/httpclient.nim(1288) downloadFile
  Error: unhandled exception: 503 Service Unavailable [HttpRequestError]`

created issue here: https://github.com/GULPF/timezones/issues/11

**Review by ringabout — CHANGES_REQUESTED** [review]
You need to include https://github.com/nim-lang/Nim/pull/22367 as a part of this PR so that we will know whether it fixes the real problem.

**Comment by bung87** [comment]
I tested it locally, that PR is questionable to be accepted, see araq's comment

**Comment by ringabout** [comment]
That is not what I meant. You need to verify whether https://github.com/nim-lang/Nim/pull/22359 is the cause of chronos failures. As a part of verification, you need to show the result of testing chronos with the option `-d:release -d:useSysAssert -d:useGcAssert --mm:refc`. Whatever, are you sure that the chronos failure is caused by your PR?

**Comment by bung87** [comment]
I verified locally by change code to previous and run same command agains to chronos, and I tested my PR locally, otherwise I wouldn't create this PR, if as you said I even don't know the cause. and I also checked chronos CI there's only one reversion between success and fails, that's my previous PR.

**Comment by ringabout** [comment]
So merge https://github.com/nim-lang/Nim/pull/22374 into your PR, the old PR breaks chronis when using refc, which is not related with sysassert or whatsoever.

**Pull request closed without merging**
