### PR TITLE
ungeneric unsigned ops

### LINKED ISSUE #12177: system.nim unsigned operators use different rules than signed operators
When using basic operators (+,-,*,div) on integers of different lengths (eg uint16 and uint32), implicit conversion only works when the longest type is first.  It is expected that the order of operands on these operators should not affect the operation.  

### Example
```nim
var a:uint16 = 1
var b:uint32 = 2

echo(b+a) # works
echo(b-a) # works
echo(b*a) # works
echo(b div a) #works

echo (a+b) # Error: type mismatch: got <uint16, uint32>
echo (a-b) # Error: type mismatch: got <uint16, uint32>
echo (a*b) # Error: type mismatch: got <uint16, uint32>
echo (a div b) # Error: type mismatch: got <uint16, uint32>
```

### Current Output
```
/home/user/nim/main.nim(9, 8) Error: type mismatch: got <uint16, uint32>
but expected one of: 
proc `+`[T: SomeUnsignedInt](x, y: T): T
  first type mismatch at position: 2
  required type: T: SomeUnsignedInt
  but expression 'b' is of type: uint32
15 other mismatching symbols have been suppressed; compile with --showAllMismatches:on to see them

expression: a + b
```

### Expected Output
```
3
1
2
2
3
4294967295
2
0
```

### Possible Solution
None yet found.  Workaround is to explicitly convert operands eg:
```
echo (uint32(a) + b)
```

### Additional Information
* Nim version (output of `nim -v`):
```
Nim Compiler Version 0.20.2 [Linux: amd64]
Compiled at 2019-07-17
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 88a0edba4b1a3d535b54336fd589746add54e937
active boot switches: -d:release
```
* Was it working in the previous Nim releases? No (0.19.6 had same behavior)
* A link to a related issue or discussion:
[https://forum.nim-lang.org/t/5185#32509](https://forum.nim-lang.org/t/5185#32509)

### PR DESCRIPTION
**Pull request by dumjyl**
also removes `defined(nimNewShiftOps)` which are not really new anymore (3 years old)
fixes #12177

### CODE REVIEW

**Comment by Araq** [comment]
We need this for 1.1.

**Comment by dumjyl** [comment]
2/3 of the failures are different candidate overload.

The only 'real' failure is:
```nim
# minimized case from tgeneric_issues
import macros, sequtils, sets, sugar
proc foo[T] = lc[x] # fails with undeclared identifier x in semgnrc
```
Before this would use system's ``template `[]`*(s: string; i: int): char`` allowing it out of semgnrc to be processed by the ``sugar.`[]` `` macro. Now it selects system's `proc `[]`*[I: Ordinal;T](a: T; i: I): T` losing the delayed symbol lookup. So I'm unsure if this was a flaky test to begin with or a real regression.

**Comment by Araq** [comment]
> So I'm unsure if this was a flaky test to begin with or a real regression.

Flaky compiler, not a flaky test. :D

**Comment by Araq** [comment]
> 3/4 of the failures are different candidate overload.

So how was this resolved?

**Comment by dumjyl** [comment]
To clarify: different failed candidate overload presentation.
I just reordered two of them and disable one on 32bit.
With overload presentation not being fully deterministic and 50-something new proc everywhere it seems not surprising.

**Pull request merged**
