### PR TITLE
Move timers module to lib/pure (WIP)

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by GULPF** [comment]
What's the purpose of the `timers` module? It looks like it's meant for measuring intervals using monotonic time, but on posix it uses non-monotonic time (neither `CLOCK_REALTIME` or `posix_gettimeofday` are monotonic). I think it's a better idea to add a monotonic time type to the `times` module after #6978 has been merged (so that the `Duration` type can be used), similiar to D's [MonoTime](https://dlang.org/library/core/time/mono_time_impl.html).

**Comment by data-man** [comment]
@GULPF 
Therefore WIP

**Comment by timotheecour** [comment]
ping: https://github.com/nim-lang/Nim/pull/6978 was finally merged

**Comment by dom96** [comment]
We should name this module something else IMO. The name is too similar to ``times``.

**Comment by dom96** [comment]
But actually, I agree with @GULPF

**Comment by Araq** [comment]
Ok, let's not do this then, sorry @data-man

**Pull request closed without merging**
