### PR TITLE
Fixed compilation on Haiku

### LINKED ISSUE #13017: [Haiku] Nimcache glitches on Koch boot
Attempt to bootstrap with `boot` results in weird error, where symbol ':' is somehow replaced by '/'. I tried to trace the error with my own hands.

### koch.nim, begins at line 321
```nim
exec "$# $# $# $# --nimcache:$# --compileOnly compiler" / "nim.nim" %
  [nimi, bootOptions, extraOption, args, smartNimcache]
exec "$# jsonscript $# --nimcache:$# compiler" / "nim.nim" %
  [nimi, args, smartNimcache]
```

### Current Output
```
iteration: 1
bin/nim c --skipUserCfg --skipParentCfg -d:release -d:useLinenoise --nimcache/nimcache/r_haiku_amd64 --compileOnly compiler/nim.nim
command line(1, 2): Error: invalid command line option: '--nimcache/nimcache/r_haiku_amd64'
FAILURE
```

### Expected Output
The above "invalid command line option" should be `--nimcache:nimcache/r_haiku_amd64`, not that example above.

This issue is completely absent on Windows and Linux, so I decided to look at generated code on all three systems and compare it source written on Nim.

On all three systems the generated code is similar to each other (aside the string numbers on Windows):

**Windows:**
image
**Linux:**
image
**Haiku:**
image

The problem strings...
```c
STRING_LITERAL(TM_xRS4M9adyeRIWGepJlj9bcoA_72, "$# $# $# $# --nimcache:$# --compileOnly compiler", 48);
STRING_LITERAL(TM_xRS4M9adyeRIWGepJlj9bcoA_74, "$# jsonscript $# --nimcache:$# compiler", 39);
```
...are similar too. So i didn't localize the problem, but found a temporary solution:

### Possible TEMPORARY Solution

* In file koch.nim make problem symbol ':' be a raw string, concatenated to others.

**Was:**
```nim
exec "$# $# $# $# --nimcache:$# --compileOnly compiler" / "nim.nim" %
  [nimi, bootOptions, extraOption, args, smartNimcache]
exec "$# jsonscript $# --nimcache:$# compiler" / "nim.nim" %
  [nimi, args, smartNimcache]
```

**Will be:**
```nim
exec "$# $# $# $# --nimcache" %
  [nimi, bootOptions, extraOption, args] &
r":" & "$# --compileOnly compiler" / "nim.nim" %
  [smartNimcache]
exec "$# jsonscript $# --nimcache" %
  [nimi, args] &
r":" & "$# compiler" / "nim.nim" %
  [smartNimcache]
```

### Additional Information

* Not needed.

```
$ nim -v
Nim Compiler Version 1.1.1 [Windows: amd64]
Compiled at 2020-01-03
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 0ecb709cbeec2e77d6ce8dae251270a7d1e3826e
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by Teashrock**
Fixed #13017.
It's a temporary solution, I suppose.

### CODE REVIEW

**Comment by Araq** [comment]
Such a weird bug, maybe instead compile ``koch.nim`` with ``--gc:none`` (it doesn't allocate all that much memory anyway),

**Comment by Teashrock** [comment]
@Araq 
I'll try this. Meanwile, I decided to open Python console and apply ord() to both of characters. ':' is 58, and '/' is 47. This is a difference by 11. Maybe there's some bitwise operation accidently doing this?

**Comment by Araq** [comment]
Who knows but it doesn't seem likely.

**Comment by Teashrock** [comment]
@Araq 
Now it tries to lauch `./koch boot -d:release` automatically right after it's compilation and then throws said error.

And no, `--gc:none` didn't help. Still the same error.

**Comment by Araq** [comment]
Well sorry, this workaround is unacceptable. We need to find and fix the root cause.

**Comment by Teashrock** [comment]
@Araq
Actually, it may even be a bug in Haiku's GCC 8, not in compiler sources.

**Comment by Teashrock** [comment]
But no, then it would be GCC complaining...  So, it's not the case.

**Comment by Araq** [comment]
Huh? Of course GCC *could* produce wrong code and then we would see this behavior.

**Comment by Teashrock** [comment]
@Araq 
My bad. I just was too sleepy at that moment. I'll check.

**Comment by Teashrock** [comment]
@Araq 
I sorta localized the bug. With 90% probability it's at os.'/' It a simple "joinPath" function. This function for some unknown reason converts any group of ':' to '/' or nothing. In fact, just perceives it like path divider.

Examples:
1:
```nim
echo "one:two:three"
```
Result: `one:two:three`

2:
```nim
import os

echo "one:two" / ":three"
echo "test::::::::" / "test"
echo "test" / "::::::::test"
echo "test::::" / "::::test"
```
Result:
`
test/test
test/test
test/test
`

**Comment by Araq** [comment]
osseps.nim contains this section

```nim

  AltSep* =
    when doslikeFileSystem: '/'
    elif defined(haiku): ':'
    else: DirSep

```

which seems to be responsible. :-)

**Comment by genotrance** [comment]
>     elif defined(haiku): ':'

This was inherited from [platform.nim](https://github.com/nim-lang/Nim/blob/devel/compiler/platform.nim#L146) and wasn't in the original osseps.nim prior to [this](https://github.com/nim-lang/Nim/pull/11814/files) PR.

**Comment by Teashrock** [comment]
@Araq 
What the heck? O_O What sort of "genius" did this? I thought this was a bug, and this happened to be intended!

Give me time, I'll make another pull request.

**Pull request closed without merging**
