### PR TITLE
Replace 'cstderr.rawWrite' with 'writeToStdErr'

### PR DESCRIPTION
**Pull request by ghost**
Use a procedure that is easy to replace on platforms without UNIX file descriptors.

### CODE REVIEW

**Comment by ghost** [comment]
I give up.

**Comment by Araq** [comment]
Why? We cannot review PRs in realtime, have a little patience please. Please reopen, I like the code... :-/

**Comment by ghost** [comment]
Sorry, I just didn't account for all the permutations of the conditionals. I will reopen later.

**Comment by timotheecour** [comment]
another advantage is:
* we can make `writeToStdErr` work in VM via a magic/vmops (without resorting to `--experimental:compiletimeFFI`)
* ditto for js backend, where we can map it to console.log

**Comment by timotheecour** [comment]
superseded by https://github.com/nim-lang/Nim/pull/17288

**Pull request closed without merging**
