### PR TITLE
CI: Don't to run the tests if only the docs were updated (WIP)

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by data-man** [comment]
Currently for the Travis only.

**Comment by dom96** [comment]
Nice :o

**Comment by data-man** [comment]
The grep not pre-installed on the AppVeyor :-(

**Comment by Yardanico** [comment]
@data-man maybe you can do using PowerShell on AppVeyor?

**Comment by data-man** [comment]
@Yardanico 
It turned out that grep is installed, just not mentioned in [AppVeyor's tools](https://www.appveyor.com/docs/build-environment/#tools).
I created [repo](https://github.com/data-man/ci_testing) for CI-experiments so the victory will be soon. :-)

**Comment by Araq** [comment]
The idea is bad. We check that the documentation builds too via ``koch web`` and typos in the RST files can break the build.

**Comment by data-man** [comment]
@Araq 
But ./koch web executes!
And this PR in WIP.

**Comment by Yardanico** [comment]
@data-man why close?

**Comment by data-man** [comment]
@Yardanico 
I don't have time to do this.

**Comment by timotheecour** [comment]
attempted to revive it here https://github.com/nim-lang/Nim/pull/8552

**Pull request closed without merging**
