### PR TITLE
Fixes #1994

### LINKED ISSUE #1994: Can't tell return value of programs with staticExec
Using `staticExec` the return value of the executed program can't be checked. Even the manual's example of `git rev-parse HEAD` can fail if you're not inside a git repo, which you can't catch nicely. I think `staticExec` should either return an empty string if the return value isn't 0, or have a way to get back the return value as well as stdout.

### PR DESCRIPTION
**Pull request by flyx**
This PR adds `gorgeEx` and `staticReadEx` which both return a tuple of output and result code. Furthermore, it add an optional parameter `onErrorBreak` to `gorge` and `staticRead`, because that was cheap to add when implementing `gorgeEx` functionality.

`staticReadEx` and `gorgeEx` will still break if executing the command raises an `OSError`.

This PR includes #4872.

### CODE REVIEW

**Comment by yglukhov** [comment]
So in what way #4871 is fixed? Any chance to note that in `news.txt`?

**Comment by flyx** [comment]
@yglukhov sorry, just saw that comment. The fix for #4871 has already been merged by #4872, so this seems to be the wrong place to discuss it. @Araq already documented it in the [news](https://github.com/nim-lang/Nim/blob/devel/web/news/e029_version_0_16_0.rst#changes-affecting-backwards-compatibility).

**Comment by Araq** [comment]
I think this implementation is convoluted. Internally opcGorge can be changed to opcGorgeEx and a wrapper gorge can call gorgeEx. I'm also not too happy with this ``Ex`` naming convention.

**Comment by flyx** [comment]
@Araq: I had problems determining which proc was called without splitting `opcGorge` and `opcGorgeEx`. Not sure what and how you want it to be changed.

What would you prefer as name for the extended procs?

**Comment by Araq** [comment]
Implemented it differently. Read and learn.

**Pull request closed without merging**
