### PR TITLE
fix #20997

### LINKED ISSUE #20997: calling `system.card[T](x: set[T])` with `T` of `int8` or `uint8` uses mismatched C array sizes
### Description

When calling `system.card[T](x: set[T])` on either `set[int8]` or `set[uint8]`, Nim generates a function
```c
static N_INLINE(NI, cardSet)(tyArray__S8ib5N31oJbAkqOZTlNg5Q s, NI len);
...
static N_INLINE(NI, cardSet)(tyArray__S8ib5N31oJbAkqOZTlNg5Q s, NI len) {
    ...
}
```

which is called from
```c
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	tySet_tyInt8__chXunH2dwinSkhpA6JnsXw T1_;
	nimfr_("cmdfile", "cmdfile.nim");
	nimln_(1, "cmdfile.nim");
	nimZeroMem((void*)T1_, sizeof(tySet_tyInt8__chXunH2dwinSkhpA6JnsXw));
	(void)(cardSet(T1_, 32));
	nimTestErrorFlag();
	popFrame();
}
}
```

where `tyArray__S8ib5N31oJbAkqOZTlNg5Q` and `tySet_tyInt8__chXunH2dwinSkhpA6JnsXw` are defined as
```c
typedef NU8 tySet_tyInt8__chXunH2dwinSkhpA6JnsXw[32];
typedef NU8 tyArray__S8ib5N31oJbAkqOZTlNg5Q[8192];
```

It's calling (through/via a `void *`, which in itself is fine) a function expecting an `NU8[8192]` with an `NU8[32]`. It doesn't ever access these extra (8192-32) elements of the array, because it sets `cardSet`'s `len` parameter to 32, but given that the sizes are both known ahead of time, it's feasible to match them.

### Nim Version

```
Nim Compiler Version 1.6.10 [Linux: amd64]
Compiled at 2022-11-23
Copyright (c) 2006-2021 by Andreas Rumpf
```

```
Nim Compiler Version 1.7.3 [Linux: amd64]
Compiled at 2022-12-02
Copyright (c) 2006-2022 by Andreas Rumpf
```

```
$ gcc --version
gcc (Debian 12.2.0-9) 12.2.0
```

### Current Output

```text
$ nim c --passC=-flto --passL=-flto --eval:"discard card(default(set[uint8]))"
Hint: used config file 'Nim/config/nim.cfg' [Conf]
Hint: used config file 'Nim/config/config.nims' [Conf]
...................................................................
CC: cmdfile.nim
Hint:  [Link]
.cache/nim/cmdfile_d/@mcmdfile.nim.c: In function ‘NimMainModule’:
.cache/nim/cmdfile_d/@mcmdfile.nim.c:240:16: warning: ‘cardSet’ accessing 8192 bytes in a region of size 32 [-Wstringop-overflow=]
  240 |         (void)(cardSet(T1_, 32));
      |                ^
.cache/nim/cmdfile_d/@mcmdfile.nim.c:240:16: note: referencing argument 1 of type ‘NU8[8192]’
.cache/nim/cmdfile_d/@mcmdfile.nim.c:153:8: note: in a call to function ‘cardSet’
  153 | static N_INLINE(NI, cardSet)(tyArray__S8ib5N31oJbAkqOZTlNg5Q s, NI len) {
      |        ^
Hint: mm: orc; threads: on; opt: none (DEBUG BUILD, `-d:release` generates faster code)
27506 lines; 0.577s; 30.328MiB peakmem; proj: cmdfile; out: .cache/nim/cmdfile_d/cmdfile [SuccessX]
```

### Expected Output

```text
No usage of mismatched array sizes on caller/callee side.
```

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by bung87**
fix #20997, this is subsequent PR of https://github.com/nim-lang/Nim/pull/21010

<s>it's bit tricky here, have to use `NimSet = distinct openArray[uint8]`, otherwise `cardSet` compiler proc will match directly call to system.card , in my case `lib\pure\parseopt.nim` `card(p.shortNoVal)` , which will cause `error: too few arguments to function ‘cardSet’`

then I have to use `toOpenArray`, so I copy paste the magic proc there, can't casting to `openArray[uint8]` for now.</s>

### CODE REVIEW

**Comment by bung87** [comment]
@tersec I runs locally with gcc 11 on ubuntu. warning now gone.

**Comment by tersec** [comment]
Looks fine:
```c
typedef NU8 tySet_tyUInt8__k3HXouOuhqAKq0dx450lXQ[32];

...

static N_INLINE(NI, cardSet)(NU8* s__XE4p9bjQ8DKyijq9cR24jpCg, NI len__zJyMM6Tx9auibNKfKWapu2w);
static N_INLINE(NI, cardSetImpl__system_5035)(NU8* s__uMA4nF9cjdyp87qBSTSnx9aQ, NI s__uMA4nF9cjdyp87qBSTSnx9aQLen_0, NI len__c8tzHysRxFE9culaHHfRFkQ);

...

static N_INLINE(NI, cardSetImpl__system_5035)(NU8* s__uMA4nF9cjdyp87qBSTSnx9aQ, NI s__uMA4nF9cjdyp87qBSTSnx9aQLen_0, NI len__c8tzHysRxFE9culaHHfRFkQ) {
        NI result;
        NI i;
...
                } LA5: ;
        }
        popFrame();
        return result;
}
static N_INLINE(NI, cardSet)(NU8* s__XE4p9bjQ8DKyijq9cR24jpCg, NI len__zJyMM6Tx9auibNKfKWapu2w) {
        NI result;

...

_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
        tySet_tyUInt8__k3HXouOuhqAKq0dx450lXQ T1_;
        nimfr_("cmdfile", "cmdfile.nim");
        nimln_(1, "cmdfile.nim");
        nimZeroMem((void*)T1_, sizeof(tySet_tyUInt8__k3HXouOuhqAKq0dx450lXQ));
        (void)(cardSet(T1_, 32));
        nimTestErrorFlag();
        popFrame();
}
}
```

Also no compile warnings on gcc 12.2.

**Comment by bung87** [comment]
CI fails unrelated.

**Comment by bung87** [comment]
@Araq please merge this! hope not too far away from previous PR

**Comment by Araq** [comment]
I don't understand this patch nor the bug it fixes.

**Comment by bung87** [comment]
it still give cgen warning as still generated `typedef NU8 tyArray__S8ib5N31oJbAkqOZTlNg5Q[8192];` and `cardSet` take that as argument. with this PR it takes pointer now.

**Comment by tersec** [comment]
Checked with both
```nim
template f(n: int) = discard card(default(set[range[0 .. (1 shl n) - 1]]))
f( 7)
f( 8)
f( 9)
f(10)
f(11)
f(12)
f(13)
f(14)
f(15)
f(16)
```
and
```nim
import std/macros

template f(n: int) = discard card(default(set[range[0 .. n]]))
macro g(): untyped =
  result = newStmtList()
  for setsize in countup(64, 65535, 8):
    result.add newCall(bindSym"f", newLit(setsize))
g()
```
and this still seem to fix the issue through gcc 12.2.

**Comment by bung87** [comment]
Thanks for confirm that!

**Comment by tersec** [comment]
Is there some blocking issue in merging this? cc @Araq 

At least for 2.0, and 1.6 would be good too -- this is a effectively fixing invalid C code generation.

**Pull request merged**
