### PR TITLE
Generate code for compile time variables

### LINKED ISSUE #6036: incomplete code generation when using a compile time variable at run time (undeclared identifier)
Here's a test case:
```nim
var x {.compileTime.} = 1
var y = x
```
This codegen bug might be the same as the one for #5958

### PR DESCRIPTION
**Pull request by ephja**
fixes #6036

### CODE REVIEW

**Comment by jangko** [comment]
there are use case where compile-time var need to exists at run-time, but many times I don't want compile-time var also show up in the C code. Perhaps we can add another pragma to enable this feature without make it default?

**Comment by Araq** [comment]
Well if you don't use it at runtime, it should be eliminated still. Maybe this patch fails to do that, but that's how it should be. Not yet another pragma please, make the compiler smarter instead.

**Comment by Araq** [comment]
I think the JS codegen is affected by this too.

**Comment by Araq** [comment]
This comes up more and more often --> next release.

**Comment by Araq** [comment]
This causes test failures and so needs to be dealt with differently. Sad.

**Pull request closed without merging**
