### PR TITLE
showStats: shows statistics on number of alloc's for each unique type

### PR DESCRIPTION
**Pull request by timotheecour**
this PR allows a debug mode (`-d:nimWithStatsTypes`) which prints out stats per unique type at program exit.
it can be run on any program, but of particular interest is running it on nim compiler itself. This can help diagnose bottlenecks in the compiler, and better inform design decisions, identify performance regressions

For example:

* as expected, TNode represents the most number of bytes allocated (hence need for something like https://github.com/nim-lang/Nim/pull/10054 to reduce from 40 to 32 bytes per node)
* the total bytes allocates for `TSym` and `TType` are both < 10% of the total bytes allocated so these don't matter much

## example 1
```
nim c -o:bin/nim_temp1 -d:release -d:nimWithStatsTypes compiler/nim.nim
bin/nim_temp1 c -o:bin/nim_temp1 -d:release -d:nimWithStatsTypes compiler/nim.nim
bin/nim_temp1 c -o:bin/nim_temp1 -d:release -d:nimWithStatsTypes compiler/nim.nim #(yes, we need to call it a 2nd time)
```

the last cmd will print:
```
stats pid: 15407: num: 22 tot: 722256104
  0 TNode              c: 11353329 s: 40   b: 454133160
  1 RopeObj            c: 3463861  s: 40   b: 138554440
  2 TSym               c: 367913   s: 168  b: 61809384
  3 TType              c: 277913   s: 176  b: 48912688
  4 Trunk              c: 126863   s: 80   b: 10149040
  5 TProcCon           c: 38177    s: 88   b: 3359576
  6 TTransfContext     c: 15721    s: 72   b: 1131912
  7 TIdent             c: 24921    s: 40   b: 996840
  8 TTransCon          c: 17182    s: 56   b: 962192
  9 TCProc             c: 7239     s: 128  b: 926592
  10 TInstantiation    c: 30742    s: 24   b: 737808
  11 TContext          c: 200      s: 1392 b: 278400
  12 TCGen             c: 156      s: 1128 b: 175968
  13 TOptionEntry      c: 1480     s: 40   b: 59200
  14 TLLStream         c: 671      s: 72   b: 48312
  15 ProcessObj        c: 140      s: 56   b: 7840
  16 ERecoverableError c: 124      s: 56   b: 6944
  17 TLib              c: 110      s: 24   b: 2640
  18 OSError           c: 40       s: 64   b: 2560
  19 StringTableObj    c: 9        s: 32   b: 288
  20 ValueError        c: 4        s: 56   b: 224
  21 FileStreamObj     c: 1        s: 96   b: 96
```

## caveats (Help welcome!)
this only counts calls to `new`; to be correct it'd have to also count calls to ref object constructors eg `Foo(name: "bar")` where Foo is a ref type.
For example, when compiling and then running this test.nim we only show Foo1, not Foo2 because of that caveat:

```nim
  type Foo1 = ref object
    b1: int
    b2: string

  type Foo2 = ref object
    b1: int
    b2: string

  for i in 0..<1234:
    var xi: Foo1
    xi.new # ok: this is counted
    discard Foo2() # bug: this isn't counted
```
```
bin/nim_temp1 c -d:nimWithStatsTypes --skipParentCfg --skipUserCfg test.nim
./test
```
last cmd will show:
```
stats pid: 52473: num: 1 tot: 19744
  0 Foo1:ObjectType c: 1234 s: 16 b: 19744
```

## note
this gives different (complementary) information from `--hint:GCStats:on` which gives
```
[GC] total memory: 61120512
[GC] occupied memory: 48441984
[GC] stack scans: 4081
[GC] stack cells: 1977
[GC] cycle collections: 0
[GC] max threshold: 0
[GC] zct capacity: 2304
[GC] max cycle table size: 0
[GC] max pause time [ms]: 0
[GC] max stack size: 58496
```

### CODE REVIEW

**Comment by Araq** [comment]
But we could already do that, compile with ``-d:nimTypeNames`` and call ``system.dumpNumberOfInstances()``

**Comment by timotheecour** [comment]
indeeed...

for reference: adding this to compiler/nim.nim
```
  proc fun(){.noconv.} =
    dumpNumberOfInstances()
  addQuitProc(fun)
```

compiler, and then compiler again gives:

```
[Heap] Rope: #2754794; bytes: 154268464
[Heap] PNode: #2527547; bytes: 141542632
[Heap] seq[PNode]: #1143301; bytes: 60135112
[Heap] string: #458983; bytes: 40008538
[Heap] PSym: #136314; bytes: 25081776
[Heap] PType: #103216; bytes: 19817472
[Heap] seq[PType]: #99435; bytes: 4604608
[Heap] KeyValuePairSeq[modulegraphs.SigHash, ropes.Rope]: #459; bytes: 2005344
[Heap] seq[string]: #334; bytes: 1530728
[Heap] PIdent: #24384; bytes: 1365504
[Heap] PTrunk: #6881; bytes: 660576
[Heap] seq[TNodePair]: #153; bytes: 365088
[Heap] seq[tuple[key: string, val: int]]: #306; bytes: 323136
[Heap] seq[tuple[key: SigHash, val: int]]: #153; bytes: 321312
[Heap] seq[TLineInfo]: #2; bytes: 264256
[Heap] seq[TInstr]: #2; bytes: 264256
[Heap] PProc: #2; bytes: 262224
[Heap] BModule: #153; bytes: 175032
[Heap] seq[PSym]: #177; bytes: 171840
[Heap] seq[PTrunk]: #139; bytes: 119648
[Heap] PInstantiation: #2402; bytes: 96080
[Heap] KeyValuePairSeq[modulegraphs.SigHash, ast.PType]: #2; bytes: 67648
[Heap] IdentCache: #1; bytes: 65584
[Heap] BProc: #306; bytes: 44064
[Heap] KeyValuePairSeq[modulegraphs.SigHash, tuple[str: Rope, owner: PSym]]: #1; bytes: 40992
[Heap] seq[PInstantiation]: #283; bytes: 36424
[Heap] KeyValuePairSeq[system.string]: #1; bytes: 32800
[Heap] seq[TBlock]: #306; bytes: 24480
[Heap] seq[TFileInfo]: #1; bytes: 18464
[Heap] seq[KeyValuePair]: #7; bytes: 17120
[Heap] KeyValuePairSeq[system.string, lineinfos.FileIndex]: #1; bytes: 12320
[Heap] seq[Cfile]: #1; bytes: 8224
[Heap] seq[tuple[key: string, value: VmCallback]]: #2; bytes: 4672
[Heap] seq[BModule]: #2; bytes: 4416
[Heap] KeyValuePairSeq[system.int, modulegraphs.SigHash]: #2; bytes: 4160
[Heap] KeyValuePairSeq[system.string, BTree[system.string, ast.PNode]]: #2; bytes: 4160
[Heap] PLib: #96; bytes: 3840
[Heap] ModuleGraph: #2; bytes: 3520
[Heap] KeyValuePairSeq[lineinfos.FileIndex, lineinfos.FileIndex]: #2; bytes: 3136
[Heap] KeyValuePairSeq[system.string, system.BiggestInt]: #2; bytes: 3136
[Heap] KeyValuePairSeq[lineinfos.FileIndex, seq[FileIndex]]: #2; bytes: 3136
[Heap] KeyValuePairSeq[system.string, ast.PNode]: #2; bytes: 3136
[Heap] ConfigRef: #1; bytes: 712
[Heap] BModuleList: #1; bytes: 472
[Heap] PEvalContext: #2; bytes: 368
[Heap] StringTableRef: #7; bytes: 336
[Heap] seq[tuple[info: TLineInfo, detail: string]]: #1; bytes: 288
[Heap] seq[TPass]: #2; bytes: 256
[Heap] seq[FileIndex]: #2; bytes: 136
[Heap] anon ref object from /Users/timothee/git_clone/nim/Nim_prs/compiler/vmops.nim(148, 19): #2; bytes: 80
[Heap] anon ref object from /Users/timothee/git_clone/nim/Nim_prs/compiler/scriptconfig.nim(48, 7): #1; bytes: 72
[Heap] NimProg: #1; bytes: 56
[Heap] JsonNode: #1; bytes: 56
[Heap] Timezone: #1; bytes: 56
[Heap] total number of bytes: 453791946
[Heap] allocs/deallocs: 28609177/21348989
```

let me think whether this can be a tad more easy to use (maybe not)

**Comment by Araq** [comment]
There is also ``iterator dumpHeapInstances*(): tuple[name: cstring; count: int; sizes: int]`` so you can format it any way you like.

**Comment by timotheecour** [comment]
dumpHeapInstances is pretty great indeed ... not super easy to search but ok; closing this for now

**Pull request closed without merging**
