### PR TITLE
Use platform specific newline in excpt.nim

### PR DESCRIPTION
**Pull request by trustable-code**
Use "\p" instead of "\n".
Fix regression from 0.17.2 -> 0.18.0.
Background: My program displays the result of getStackTrace() in a Windows text area. Linebreaks only work with \p, not with \n.

### CODE REVIEW

**Comment by Araq** [comment]
Again, it's not a bug. Nim produces Unix newlines.

**Comment by trustable-code** [comment]
For both PRs: If you think it's better, that it uses Unix newlines on every platform, it will be ok for me. Then I just need to splitLines and join(\p) for the needed result.
So the question is, what is the desired behavior of Nim and Nim programs.
For the Windows terminal \n works.

**Comment by Araq** [comment]
> So the question is, what is the desired behavior of Nim and Nim programs.

With 0.18 Nim defaults to Unix newlines for everything everywhere. Sorry it means workarounds for you.

**Comment by dom96** [comment]
> With 0.18 Nim defaults to Unix newlines for everything everywhere. Sorry it means workarounds for you.

Why? Doesn't this mean all messages output by Nim on windows will be broken?

**Comment by trustable-code** [comment]
@dom96 It is no problem in the terminal, only in a Windows GUI application. I'm fine to use splitLines.join("\p").

**Pull request closed without merging**
