### PR TITLE
added default param to strtabs.getOrDefault

### PR DESCRIPTION
**Pull request by enthus1ast**

### CODE REVIEW

**Comment by trustable-code** [comment]
looks useful for me

**Comment by Araq** [comment]
It would not be consistent with the tables API.

**Comment by dom96** [comment]
I would say that this procedure should be called ``get`` and support a default value. ``getOrDefault`` is too long, is there a reason for why this name was picked?

**Comment by enthus1ast** [comment]
to me it sounds like it would fail gracefully

**Comment by Araq** [comment]
For consistency every getOrDefault should actually support a default value, but as a first step this is fine. Merging.

**Comment by yglukhov** [comment]
Some concerns.
1. This is a breaking change. Previously default was nil. Should be documented at least.
2. When default parameter is later added to Table it would not be consistent with StrTabs, because string default value is nil, and not "". Tables due to their generic nature will likely return nil as a default string value.

**Comment by yglukhov** [comment]
I would suggest making default arg `nil` to maintain consistency and to avoid breaking changes.

**Comment by dom96** [comment]
I agree with @yglukhov

**Comment by Araq** [comment]
no, the default was "" before, see the diff. No breaking change I think.

**Comment by yglukhov** [comment]
My bad, sorry. So only concern 2 left, but its not introduced with this pr. As a future direction, maybe the new `get` function could behave a bit differently for strtabs, returning nil as a default... In any case this pr doesnt introduce _new_ problems which I erroneously thought it did.

**Comment by enthus1ast** [comment]
After you've pointed to the inconsistency, i've looked into tables and tried to change it accorgingly.
If you let me i would try to make a new pr with the change to tables.

**Comment by yglukhov** [comment]
How about deprecating `getOrDefault` and doing a brand new and consistent `get` everywhere?

**Comment by yglukhov** [comment]
Maybe even dubbing it with `{}` operator to be consistent with `json`?

**Pull request merged**
