### PR TITLE
fixes syncio document

### PR DESCRIPTION
**Pull request by NanXiao**

### CODE REVIEW

**Comment by ringabout** [comment]
@NanXiao Your efforts on documentation improvements are appreicated. If you happen to have some free time, you might check issues labelled with [Documentation Content](https://github.com/nim-lang/Nim/issues?q=is%3Aopen+label%3A%22Documentation+Content%22).

**Comment by NanXiao** [comment]
> @NanXiao Your efforts on documentation improvements are appreicated. If you happen to have some free time, you might check issues labelled with [Documentation Content](https://github.com/nim-lang/Nim/issues?q=is%3Aopen+label%3A%22Documentation+Content%22).

@ringabout I will check it when I have time, thanks very much!

**Comment by litlighilit** [comment]
I'm coming from [doc of nim website](https://nim-lang.org/docs/syncio.html#setInheritable%2CFileHandle%2Cbool)

Strangely, finding that the corresponding html rendered is left unfixed

image

May due to a lack of re-build of this part of doc.

> Emm... unknown where to make a commit, I have to make a comment here to mention
Sorry to bother NanXiao

**Comment by ringabout** [comment]
It hasn't been backported, check the devel documentation instead => https://nim-lang.github.io/Nim/syncio.html#setInheritable%2CFileHandle%2Cbool

**Pull request merged**
