### PR TITLE
Create entity nodes with xmlparser, add a test to xmlparser

### PR DESCRIPTION
**Pull request by Matt14916**
I threw up a test at the last minute so it may not be up to snuff. I hijacked the apparently unused doc1.xml file for the test.

### CODE REVIEW

**Comment by Araq** [comment]
Meh, this is a breaking change so it shouldn't end in 0.12.2. -.-

**Comment by dom96** [comment]
:(

**Comment by dom96** [comment]
Want me to revert it?

**Comment by Araq** [comment]
Well I think nobody relied on this edge case, so it's fine.

**Pull request merged**
