### PR TITLE
ISO-26300 Documentation generator rstgen

### PR DESCRIPTION
**Pull request by juancarlospaco**
- ISO-26300 Documentation generator `rstgen.nim`, A.K.A "ODT".
- `runnableExamples` for HTML, Latex, ODT.
- `when isMainModule:` runs for HTML, Latex, ODT.
- Documentation for HTML, Latex, ODT with examples and links.
- Unittests for HTML, Latex, ODT with the same input strings (Tests incremented x3).
- Unittests for Latex (was HTML only).
- Output ODT is pretty-printed.
- Everything has comments.
- styleCheck clean (NEP1).

ISO Standard:
- https://www.iso.org/standard/66363.html

Official Specs:
- https://www.oasis-open.org/committees/download.php/19274/OpenDocument-v1.0ed2-cs1.pdf

Wikipedia:
- http://wikipedia.org/wiki/OpenDocument

nim-odt

:slightly_smiling_face:

### CODE REVIEW

**Comment by Araq** [comment]
Ok, well, this is ``[feature]`` and needs some documentation. But thanks, nice work!

**Comment by arnetheduck** [comment]
well, this is nice, but is it really in scope for a compiler to provide an rst to _openoffice_ template engine? could this be moved to a separate package? what's the maintenance implication/burden?

**Comment by juancarlospaco** [comment]
Being an ISO standard is not like going to do crazy changes nor vanish overnight,
validating is easy since is XML strict, test increased, everything is commented and documented,
is not OpenOffice only format is for any office software, now and for decades to come,
maintenance is not hurt compared to the new feature, is keep as lightweight as possible,
just tiny static strings added on a new `case` branch, and one `include` with the headers,
the module also looks more clean due to the changes to add one more format to the existing ones.

But is open for discussion, no problem. Let me know any comments. :slightly_smiling_face:

**Comment by arnetheduck** [comment]
the issue would rather be that anyone that wants to improve the compiler must become an expert at said ISO standard so as not to break things - every new feature starts out small until the corner cases start being taken into consideration - and that improvements to the documentation generation must be bottlenecked by compiler devs instead of having someone that's focused on ODT take care and nurture them lovingly without these ping-pongs - seems like a win-win to keep this separate (similar to how sphinx is used with python, but lives as a separate project). 

Over at status we have documentation folks looking to work on improving doc generation, but it's generally a daunting task to modify the compiler - the more independent (and thus focused) this could be, the easier it would be to contribute eventually.

**Comment by juancarlospaco** [comment]
I totally understand what you say.

For comparison, few people know how to manually code Latex, also is not a Standard, 
has an official spec tho, needs compiling, is hard to validate since is not XML or JSON, etc.

HTML is cool, but is not a format you can edit right away.

ODT Basically is XML strict, a DOM where only `<p>` exists, style is made by unique ID, thats all.

You wonder how editors do more, can use raw SVG, and Base64 embed things in, but it doesnt implement that because KISS.

**Comment by Araq** [comment]
arnetheduck is convincing, we shouldn't have this as part of the compiler. Please make this a Nimble package, you can import the compiler API as a Nimble dependency and create a new tool. (Yes, I know that it's currently a fragile API, so nail down its version or even commit hash.)

**Pull request closed without merging**
