### PR TITLE
Update example code for UDP sockets

### PR DESCRIPTION
**Pull request by euantorano**
Reference: https://forum.nim-lang.org/t/4082

### CODE REVIEW

**Comment by dom96** [comment]
Make PRs to ``devel`` not ``master``.

**Comment by euantorano** [comment]
@dom96 In the future, note that the target ref can be changed for a PR after the fact, so I could have simply switch this to `devel` instead of `master`. Since it was closed, I've opened a new PR instead: #8476

**Comment by dom96** [comment]
You could've reopened this PR, no?

**Comment by euantorano** [comment]
I don't believe I could, there isn't an option to open it now at the least.

**Comment by dom96** [comment]
Hrm, perhaps GitHub doesn't allow that for the PR creators.

**Pull request closed without merging**
