### PR TITLE
fix outdated example to invoke Nim from C

### LINKED ISSUE #8139: Outdated example to invoke Nim from C
The documentation of [Nim invocation example from C](https://nim-lang.org/docs/backends.html#interfacing-backend-code-calling-nim) is completely outdated.

### original issue

Nim compiler generates a statically linked library which does not link.

```gcc -o m -I./nimcache -Ipath/to/nim/lib libfib.a maths.c```
```
/tmp/cce625tz.o: In function `main':
maths.c:(.text+0x9): undefined reference to `NimMain'
maths.c:(.text+0x1c): undefined reference to `fib'
```

### PR DESCRIPTION
**Pull request by yyyc514**
- resolves #8139

### CODE REVIEW

**Comment by yyyc514** [comment]
Or should we use `~` in the example for HOME?

**Comment by krux02** [comment]
`$HOME` is just fine. This example won't work on windows, maybe you can add a comment on how to change the paths for windows scripts. If you can't provide that, it is also OK.

**Comment by yyyc514** [comment]
>  maybe you can add a comment on how to change the paths for windows scripts

If you tell me what it should say. No idea, I don't use Windows.

**Comment by dom96** [comment]
The above text says "Unix-like". I think this is a good change. We can rewrite this to be more windows-friendly in a separate PR.

**Comment by Araq** [comment]
This could have get a ``[backport]`` tag.

**Comment by narimiran** [comment]
> This could have get a `[backport]` tag.

Backported.

**Pull request merged**
