### PR TITLE
Fix edge-case from #15064 

### LINKED ISSUE #15064: [strscans] scanf doesn't match a single character with $+ if it's the end of the string
Self explanatory really.

### Example
```nim
import strscans

var nick, msg: string
if scanf("<abcd> a", "<$+> $+", nick, msg):
  echo nick
  echo msg
else:
  echo "failed"
```

### Current Output
```
failed
```

### Expected Output
```
abcd
o
```

```
$ nim -v
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-07-23
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 18a70a75638ded6ff23b2a9a57edfc7dd09bb5b1
active boot switches: -d:release -d:danger
```

### PR DESCRIPTION
**Pull request by ghost**
I'm not sure if this is 100% correct, but strscans tests seem to pass.
Fixes #15064

### CODE REVIEW

**Comment by ghost** [comment]
timezones failure seems unrelated - fails on devel too - https://github.com/nim-lang/Nim/runs/909341967

**Comment by ghost** [comment]
Aww, seems to be incorrect:
```nim
import strscans

var nick, msg: string
if scanf("<abcd> ", "<$+> $+", nick, msg):
  echo nick
```
will work after this PR which is not correct behaviour

**Comment by narimiran** [comment]
> will work after this PR which is not correct behaviour

This was incorrect even before this PR.

But I think I have a simpler/elegant solution for both problems, see my PR: https://github.com/nim-lang/Nim/pull/15223

**Comment by narimiran** [comment]
#15223 was merged. Closing this.

**Pull request closed without merging**
