### PR TITLE
Check for nil when converting from string to cstring

### PR DESCRIPTION
**Pull request by yglukhov**

### CODE REVIEW

**Comment by nanoant** [comment]
@yglukhov This is pretty serious change, that may make tracking bugs harder. Now if developer is unaware that string variable is `nil` converting to `cstring` will crash.

Your change will cause conversion to succeed, returning `NULL` which can be later passed to many function or APIs that have undefined or bad behavior on passing `NULL`.

Personally I prefer my program crash early than late in a place where I can hardly know that there was `nil` somewhere in my code, or at least have a choice to have cast with implicit `NULL` or not, eg.: `str.cstring` vs `str.safeCString`.

**Comment by yglukhov** [comment]
@nanoant, but so you would later crash with NULL cstring, right? And consider the following code.
```nim
var s: string = nil
var cs: cstring
# Let's say I want cs to be NULL, when s is nil.
cs = s # Crash

# Second try
cs = if s.isNil: nil else: s # Crash! Wait wat? Ahh, type of the if expr is still string...

# Finally we succeed.
if not s.isNil: cs = s

# how about calling the following function with s?
proc myFunc(csThatMayBeNULL: cstring) = discard

# if expr will not do it. Create a temp var of type cstring!
var tempVar : cstring
if not s.isNil: tempVar = s
myFunc(tempVar) # Ahhh, finally. How convenient ;)

And here's some consistency example.

var myNilString: string
myFunc(nil) # OK
myFunc(myNilString) # BAM! =)
```

**Comment by yglukhov** [comment]
Ideal decision, imho, would be to use not nil annotation. Such that nil string converts to NULL cstring silently, and (string not nil) converts to (cstring not nil). I don't know how far nim is away from this, but the change in my pr is consistent with such behavior, should it be implemented in future.

**Comment by yglukhov** [comment]
Oh and here's one last nail. C/C++ standards state that dereferencing NULL is not a crash, but undefined behavior. Basically that means, that now converting nil strings in Nim is undefined behavior. ;)

**Comment by nanoant** [comment]
What I am saying that the proposed change gives you absolutely no benefit on functions such as `strdup`, `getenv` that have undefined behavior (likely crash) on invalid pointer, regardless it is `(nil)->data` (current cgen) or your proposition. Only thing you get is probably some performance penalty doing extra check on each cast that won't save you from anything.

Btw. If you want to do one liner you should make:
~~~nim
myFunc(if str != nil: str.cstring else: nil) # the type of expr in (...) is cstring, so else: nil is real NULL, and you get what you want
~~~

What I propose is to just have simple extra functions:
~~~nil
proc toCString(str: string): cstring =
  # this one silently converts to nil
  if str != nil: str.cstring else: nil

proc safeToCString(str: string): cstring =
  # this one throws on nil
  if str == nil: throw ...
  str.cstring
~~~
This will give you some flexibility, depending what API you are alling, instead sacrificing performance for some implicit nil check that may not save you anyway. So leaving `str.cstring` (or implicit conv) as it is now.

`not nil` annotations (or `optionals` like in Swift) is neat behavior that can save you from some problems. Still I don't agree we should do any implicit check on conversion. And if we do, they should be there only in debug mode and should throw on nil (same as boundary checks).

**Comment by yglukhov** [comment]
But there are lots of functions that handle NULL cstring properly. And for such functions, a statement that Nim converts strings transparently does not hold. It's not intuitive, and you always have to remember to explicitly convert for such functions. Intuitively, NULL by itself is a perfectly valid value for both string and cstring, and semantically they mean the same to me.

**Comment by nanoant** [comment]
If this change was zero cost I wouldn't bother, but it isn't. It is extra `testq`, `je`, which may be unnecessary if you are dealing with methods that expect non-null pointer.

I don't want Nim to have some extra hidden stuff that cannot be turned off. Currently all boundary checks run on debug for example, but not on release. They can be selectively turned on/off upon needs. Your functionality cannot.

But I fully agree that this could / should be easier, but not until we have something like `optional` type annotation.

Then doing `optional string` -> `optional cstring` could convert `nil` to `NULL` implicitly. But `string` -> `cstring` shouldn't.

Alternatively you can just introduce some `orNil` template, so

~~nim
# instead writing
myFunc(if str != nil: str.cstring else: nil)
# I write
myFunc(str.orNil) # expressing I know str may be nil and it can be safely turned into NULL
~~

**Comment by nanoant** [comment]
Okay I forgot Nim has `not nil` already, unfortunately it isn't used a lot across the std library. IMHO, this should be other way around `not nil` should be default while `optional` should be qualifier, but whatever :>

So the correct solution is to distinguish `string` -> `cstring` from `string` -> `cstring not nil`. Currently there is none:
~~~nim
proc strdup(env: cstring not nil): cstring {.header: "<string.h>", importc: "strdup".}
var str: string
echo "env=", strdup(str)
~~~
This compiles well and then crashes :)

**Comment by nanoant** [comment]
I think it should check for that both source `string` and target `cstring` have `tfNotNil` unset and do the implicit check and conversion from `nil` string to `NULL` cstring.

I was talking with @Araq earlier today about `not nil`, and we share opinion that it makes sense to reverse that making `ref`s and `ptr`s to be `not nil` by default and make them optionally markable as `or nil` (capable of holding nil - todays default).

In most cases, such as `libc`, functions' cstring arguments cannot be nil, but devs probably will forget to put `cstring not nil` on every such `importc` declaration, so your implicit conversion will be triggered even it is completely unnecessary. But anyway this is not the PR problem, as long it respects `tfNotNil`.

**Comment by yglukhov** [comment]
I'll better close this for now until not nil is default.

**Pull request closed without merging**
