### PR TITLE
Fix newLit for objects having string fields

### PR DESCRIPTION
**Pull request by zah**
This is another fix in the vein of https://github.com/nim-lang/Nim/pull/10760 with the exact same explanation.

### CODE REVIEW

**Comment by Clyybber** [comment]
I think this really needs a test to make sure it doesn't regress.

**Comment by zah** [comment]
I think there is another underlying issue here. In theory, `newLit` is overloaded, so it should act as a mixed-in symbol and the ordering shouldn't matter. If you try a simple test case, you'll find that things work as expected, but in more complicated multi-module chain-of-instantiations scenarios, I'm triggering the errors and the fix here is able to resolve them.

**Comment by Clyybber** [comment]
So it's a compilerbug :(

**Comment by krux02** [comment]
This bug that we fixed recently might be related: 
https://github.com/nim-lang/Nim/issues/12416

**Pull request merged**
