### PR TITLE
[WIP] first pass at fixing #7430: universal to conversion template

### PR DESCRIPTION
**Pull request by timotheecour**
here's a 1st pass at https://github.com/nim-lang/Nim/issues/7430 ; I (or others) can add more conversions once we agree on design principles below

design principles:

* each `to` overload should be in the module where the types / conversions are defined, eg `s.to(JsonNode)` goes in `lib/pure/json.nim` , `s.to(bool)` goes in `lib/pure/strutils.nim` etc

this is preferable to having a dedicated hodge-podge `conv.nim` module that would import everything needed and wrap for eg `parseFoo` to `to(Foo)` ; that would not scale (eg wouldn't work with nimble packages, which can't be imported by `conv.nim`) ;

* the existing `parseFoo(a:string)` `toFoo(...)` etc should become thin wrappers around the corresponding `to` proc/template (the `to` would contain the actual implementation) and eventually deprecated
eg: see this PR for parseBool becoming thin wrapper around `s.to(bool)`

* prefer `proc` to `template` whenever possible

* we should standardize ASAP on ideal signature, eg the name of arguments matters in case generic code uses named parameter syntax (eg: `to(s:foo, Bar)`; so I suggest:
```
proc to*(s: string; dest: typedesc[T]): T = ...
```
which is short and generic (`s` standing for `source`)

* new conversion functions (eg what would be currently called parseFoo or toFoo) should just use `to` and not even define `parseFoo` or `toFoo`

### CODE REVIEW

**Comment by PMunch** [comment]
I think the idea was to not only support parsing, but general conversion though

**Comment by Araq** [comment]
Meh, general conversion is too general. Think about error handling/reporting.

**Comment by timotheecour** [comment]
@Araq how about:
each appropriate module defines overloaded `parse` procs/template: eg:
```
proc parse(s: string; dest: typedesc[bool]): bool = s.parseBool
echo "true".parse(bool)
```
somewhere (eg in `conv.nim` or `strutils.nim`) we also add:
```nim
template to*[T](s: string; dest: typedesc[T]): auto = s.parse(dest)
```

that way user can choose the most generic `to` or the string specific `parse` depending on his use case; 
all the `parse` overloads conform to a given signature (feel free to suggest improvements)

**Comment by dom96** [comment]
I agree with @Araq.

Think about the following:

```nim
"tru".to(bool) # Error? False?
"{{{".to(JsonNode) # Definitely an error.
```

``parse`` is a better name here. The ``to`` name implies a strict conversion that has some compile-time checks to me.

**Comment by timotheecour** [comment]
I think the semantics should be obvious here:
```nim
"tru".to(bool) # throws Exception
"{{{".to(JsonNode) # throws Exception
```

**Comment by Araq** [comment]
I don't see the need for ``to``, ``to`` is an overly generic preposition, Ruby uses it for counting iirc, ``parse`` is a verb, procs should be verbs.

**Comment by dom96** [comment]
I think until we can ascertain how useful this is in the wild, this should go into a Nimble package. Further down the line we can decide whether it belongs in the stdlib once we see how useful it is.

The stdlib is a gentle thing, we want to be conservative, it's much easier to add things to it than it is to remove.

**Comment by PMunch** [comment]
I agree. But I still think we could implement the `parse` proc in strutils for a more generic interface for parsing. To in Nim can often be done just by the simple `42.uint8; 1.bool`, so I don't entirely see the need for that.

**Comment by Araq** [comment]
Adding ``parse`` support in the stdlib is fine once the "typedesc vs generic parameter" fight is settled though.

**Pull request closed without merging**
