### PR TITLE
splitPath() behavior synchronized with splitFile()

### PR DESCRIPTION
**Pull request by luav**
Behavior of the paths processing routines is made uniform as expected in all languages (and matches the one in Python), splitPath() docstrings are updated, tests are added for both splitPath() and splitFile().

### CODE REVIEW

**Comment by Araq** [comment]
This is a breaking change, so at least it needs a changelog entry and maybe some ``--define`` to get back the old behaviour.

**Comment by luav** [comment]
@Araq you are right that the change is breaking but also it uniforms the API behaviour making it more intuitive and unambiguous. Let me know please if something specific is further required from my side to accomplish this fix.

**Comment by Araq** [comment]
But that's what I did, please write a changelog entry and do your patch conditionally like so:

```
when (NimMajor, NimMinor) <= (1, 0):
  # old version
else:
  # your version
```

**Comment by luav** [comment]
@Araq the respective changelog entry is made and the code is taken into the required condition and optimized.

**Pull request merged**
