### PR TITLE
nep1: prefer one-liners for single element type/var/import sections

### PR DESCRIPTION
**Pull request by timotheecour**

### CODE REVIEW

**Review by dom96 — CHANGES_REQUESTED** [review]
I have really grown to love the type section over the years. I don't think this should be in nep-1 for the following reasons:

* A standalone `type` on its own line has been a part of Nim's code style for a long time, there is  a lot of code written like this.
* Having multiple type sections can lead to problems, if for example there are types that depend on each other you need to put them in the same type section.

Same goes for `const`, I think it's common to define multiple constants and so grouping them together is nice. Maybe at least make it clear that this only applies to single const declarations?

For `import` I don't have a strong preference, but I can see it being elegant to write something like:

```nim
import
  std/[strutils, sugar],
  fusion/[htmlparse, patterns]
```

Don't see why we should discourage it.

**Comment by timotheecour** [comment]
the scope of this proposal is for single element type/var/import sections, multi-element type/var/import sections are not affected by this proposal:

this proposal concerns this:
```nim
# good
import std/[a,b]
const a = 1
type A = object
  x: int

vs

# bad
import
  std/[a,b]
const
  a = 1
type
  A = object
    x: int
```

but doesn't concern this:
```nim
import
  std/[a,b]
  fusion/[b, c]
const
  a = 1
  b = 2
type
  TA = object
    x: int
  A = ref TA
```

I thought it was clear but I guess it wasn't so I'll try to clarify this in the doc

**Comment by timotheecour** [comment]
PTAL

**Comment by dom96** [comment]
Personally I would still prefer not to discourage this for `type` sections specifically. A `type` on its own line has been the preferred style for all of Nim's history :/

**Comment by Araq** [comment]
Sorry, rejected as it doesn't reflect reality.

**Pull request closed without merging**
