### PR TITLE
followup #17336, improve tests/arc/tmovebug.nim coverage

### PR DESCRIPTION
**Pull request by timotheecour**
followup #17336

refs https://github.com/nim-lang/Nim/pull/17336#issuecomment-797073587

### CODE REVIEW

**Comment by Clyybber** [comment]
`{.requiresInit.}` is not related (because it isn't considered by the transformation at all, and once it will we will add an appropriate testcase).
Neither is the transformation affected by wether it is `gc:arc` or `gc:refc`.
Adding `gc:refc` to the tests matrix just makes arc development more annoying because now `testament c arc` takes longer.

**Comment by timotheecour** [comment]
the original reported bug affects gc:refc only, not gc:arc (at least until 1.4.0; then since 1.4.2 a regression made it also affect gc:arc)

so testing it only in gc:arc doesn't make sense (implementation details shouldn't dictate what's being tested to prevent regressions when implementation changes).
the 1 extra second out of 60 seconds for `testament pcat arc` is IMO entirely justified, furthermore, we'll eventually have https://github.com/timotheecour/Nim/issues/445 or similar allow you to filter tests by tags eg: `testament --tags:arc all` or `testament --tags:arc someCategory`, so that extra second will disappear.

I'd rather increase coverage and less test duplication than save a few tiny fractions of CI time, especially when we can add flag-specific megatest down the road which can considerably further reduce CI running times.

**Comment by Clyybber** [comment]
I'll reapply https://github.com/nim-lang/Nim/pull/17317 then (https://github.com/nim-lang/Nim/pull/17347, also has the `{.requiresInit.}`), because `tmovebug` should stay an arc only test IMO.

**Comment by timotheecour** [comment]
ok, good enough for me, thanks

**Pull request closed without merging**
