### PR TITLE
Fix for vm var param

### LINKED ISSUE #12489: var ref param doesn't work when it comes from an object member
### Example
```nim

type
  MyObjectRef = ref object
    a,b: int

  MyContainerObject = ref object
    member: MyObjectRef

proc foobar(dst: var MyObjectRef) =
  dst = new(MyObjectRef)
  dst.a = 123
  dst.b = 321

proc test() =
  # when it comes from a var, it works
  var y: MyObjectRef
  foobar(y)
  echo y != nil
  # when it comes from a member, it fails on VM
  var x = new(MyContainerObject)
  foobar(x.member)
  echo x.member != nil

test()
static:
  test()
```

### Current Output
```
Hint: scratch [Processing]
true
false
CC: stdlib_system.nim
CC: scratch.nim
Hint:  [Link]
Hint: operation successful (21928 lines compiled; 1.042 sec total; 25.594MiB peakmem; Dangerous Release Build) [SuccessX]
Hint: /tmp/scratch  [Exec]
true
true
```

### Expected Output

```
Hint: scratch [Processing]
true
true
CC: stdlib_system.nim
CC: scratch.nim
Hint:  [Link]
Hint: operation successful (21928 lines compiled; 1.042 sec total; 25.594MiB peakmem; Dangerous Release Build) [SuccessX]
Hint: /tmp/scratch  [Exec]
true
true
```

### Additional Information

 * Non ref parameters work fine.
 * This causes problems in my json macro
    https://github.com/nim-lang/Nim/blob/2ccd1c34284f08ba8e4c7b5b4986de8899f60354/lib/pure/json.nim#L1051

### PR DESCRIPTION
**Pull request by krux02**
fixes #12489

Status: 

I am currently blocked in this PR. 

I have a I broke some logic. At the linked code, the value of `regs[ra].node` is `nil` and the compiler crasehs. I have no idea how that happened or how to debug the VM in a way to find this out. I need some help for this.

https://github.com/nim-lang/Nim/blob/fix-for-vm-var-param/compiler/vm.nim#L668

Here are the two stack traces

nimvm:
```
tjsonmacro.nim(640, 11)  tjsonmacro
tjsonmacro.nim(63, 14)   testJson
json.nim(371, 14)        %
json.nim(364, 41)        %
json.nim(331, 36)        %
json.nim(364, 39)        %
json.nim(359, 13)        []=
tableimpl.nim(52, 12)    []=
tableimpl.nim(22, 10)    rawInsert
```
compiler:
```
compiler/nim.nim(106) nim
compiler/nim.nim(83) handleCmdLine
compiler/cmdlinehelper.nim(98) loadConfigsAndRunMainCommand
compiler/main.nim(188) mainCommand
compiler/main.nim(92) commandCompileToC
compiler/modules.nim(144) compileProject
compiler/modules.nim(85) compileModule
compiler/passes.nim(210) processModule
compiler/passes.nim(86) processTopLevelStmt
compiler/sem.nim(601) myProcess
compiler/sem.nim(569) semStmtAndGenerateGenerics
compiler/semstmts.nim(2216) semStmt
compiler/semexprs.nim(987) semExprNoType
compiler/semexprs.nim(2742) semExpr
compiler/semstmts.nim(2156) semStmtList
compiler/semexprs.nim(2794) semExpr
compiler/semstmts.nim(2108) semStaticStmt
compiler/vm.nim(2075) evalStaticStmt
compiler/vm.nim(2065) evalConstExprAux
compiler/vm.nim(668) rawExecute
```

### CODE REVIEW

**Comment by Clyybber** [comment]
Does this also fix https://github.com/nim-lang/Nim/issues/12282 ?

**Comment by krux02** [comment]
@Clyybber unfortunately it doesn't. It even introduces new bugs and I am blocked to continue on this PR, see my last edit.

**Comment by Araq** [comment]
Succeeded by https://github.com/nim-lang/Nim/pull/12667

**Comment by timotheecour** [comment]
@krux02  underlying bug (#12282) is still there (#12667 fixed some other bug)

> I have no idea how that happened or how to debug the VM in a way to find this out. I need some help for this.

-d:nimVMDebug is your friend

**Pull request closed without merging**
