### PR TITLE
Fix destructor injections for global variables

### LINKED ISSUE #9799: Destructors are called too early for the global variables
The global varibles get destroyed immediately after use. You need 2 modules to demonstrate the issue. 

first file `ObjFile.nim`
```nim
type
  TestObject* = object
    anInteger: int
    aString: string

proc `=destroy`*(this: var TestObject) =
  echo "=destroy @", cast[uint](this.unsafeaddr)
  this.anInteger = -1
  this.aString = ""

proc `=`*(this: var TestObject, other: TestObject) =
  echo "= this@", cast[uint](this.unsafeaddr)," other@", cast[uint](other.unsafeaddr)
  this.anInteger = other.anInteger
  this.aString = other.aString

proc `=sink`*(this: var TestObject, other: TestObject) =
  echo "=sink this@", cast[uint](this.unsafeaddr)," other@", cast[uint](other.unsafeaddr)
  this.anInteger = other.anInteger
  this.aString = other.aString


proc `$`*(this: TestObject):string =
  "Addr =" & $(cast[uint](this.unsafeaddr)) & " with int=" & $this.anInteger & " and string = \"" & this.aString & "\""


proc initTestObject():TestObject =
  echo "initTestObject @", cast[uint](result.unsafeaddr)
  result.anInteger = 21
  result.aString = "a valid string different from nothing"

echo "--------------gblTestObject---------------"
var gblTestObject* {.global.} = initTestObject()

proc isValid*(this: TestObject): bool =
  echo "isValid @", cast[uint](this.unsafeaddr)
  return this.anInteger > 0 and this.aString != ""
```

Second module
```nim
import objFile

proc Something()=
  echo "-----------TestObject Testing file--------------"
  echo "is global object ready to use? ", gblTestObject.isValid(), " ==>", $gblTestObject

Something()
```

The output is
```
--------------gblTestObject---------------
initTestObject @6552560
=sink this@4374336 other@6552336
=destroy @4374336
-----------TestObject Testing file--------------
isValid @6552592
is global object ready to use? false ==>Addr =6552592 with int=-1 and string = ""
```
As you can see gblTestObject global variable was destroyed right after construction before second module had any oppotunnity to use it.

### PR DESCRIPTION
**Pull request by Clyybber**
Fixes #9799
Refs #11217
I consider this a WIP as
- I don't know if this should really belong in ModuleGraph or in myClose
- ~generated temporaries for globals leak into topLevelVars such as in https://github.com/nim-lang/Nim/blob/devel/tests/ccgbugs/tsequence_outoforder.nim and thus only get destroyed at the end of the mainModule or cause generating invalid C. EDIT: This also the reason the tests currently fail...~
  EDIT: Fixed!
- It is not yet implemented for the other backends

### CODE REVIEW

**Comment by Clyybber** [comment]
Now megatest fails, as expected, as globals are now only destroyed at the end of the program.
This is IMO the better behaviour as it's more predictable (and in line with what C/C++ does).

**Comment by cooldome** [comment]
+1 for the fix. I already like the fix the way it is, but please consider if the following alternative is possible.
Currently, inject destructors generates the following:
```nim
try:
  body
finally:
  destroy(x1)
  destroy(x2)
```
Codegen doesn't support top level finally properly. The idea  is to detect in codegen that finally clause is at thentop level and accumulate all finally blocks and emits them in myClose just like you do in this PR.

The benefit is that not only destructors for global variables will work. User will be able to put any cleanup logic in finally blocks at the top level, top level `defer` statement will start working as well. 

This is just a proposal of untested idea.

**Comment by Clyybber** [comment]
@cooldome Oh, ok I didn't know that codegen doesn't properly support top-level try-finally.
As you can see, I only implented generating top level try-finally in https://github.com/nim-lang/Nim/pull/11230/commits/bec683dc6809f44b31d0993ae6b39e35a01cc196 to fix the issue that top-level temporaries would not get destroyed until the end of the program.
So top level try-finally are only generated for temporaries, because I'd like for them to get destroyed as early as possible.

**Comment by Clyybber** [comment]
@cooldome Regarding you proposal, how should top-level try-finally/defer behave in imported modules?
To make your idea work, the finally/defer part would have to always be executed at the end of the main module, not the individual modules, but I think this is expected? WDYT?

**Comment by cooldome** [comment]
Yes, it is expected finally to be executed at the end of the main module, just like you did in this PR already. Manual will be updated to reflect it.

**Comment by Clyybber** [comment]
@cooldome After thinking a bit more about it, I'm not so sure anymore, that changing the behaviour of top-level try-finally statements is a good idea, as this special casing of top-level try-finally statements would cause inconsistencies such as this one:
```nim
try:
  echo "one"
finally:
  echo "two"

echo "three"
```
would then print "one three two" which IMO isn't necessarily desired/expected behaviour.

**Pull request merged**
