### PR TITLE
Change severity of template instantiation message [backport]

### PR DESCRIPTION
**Pull request by ghost**
With this PR tools such as nimlsp (or some other editors) won't report phantom errors anymore.

For code:
```nim
type 
  X {.requiresInit.} = object
    a: string

let xs = newSeq[X]()
```

Before:
```
> chk test.nim
.chk    skUnknown               Hint    ???     0       -1      "test [Processing]"     0
chk     skUnknown               Error   /home/dian/.nim/test.nim        5       15      "template/generic instantiation from here"      0
chk     skUnknown               Warning /home/dian/.nim/lib/system.nim  649     9       "Cannot prove that \'result\' is initialized. This will become a compile time error in the future. [ProveInit]" 0
chk     skUnknown               Hint    /home/dian/.nim/test.nim        5       4       "\'xs\' is declared but not used [XDeclaredButNotUsed]" 0
```

After:
```
> chk test.nim
.chk    skUnknown               Hint    ???     0       -1      "test [Processing]"     0
chk     skUnknown               Hint    /home/dian/.nim/test.nim        5       15      "template/generic instantiation from here"      0
chk     skUnknown               Warning /home/dian/.nim/lib/system.nim  649     9       "Cannot prove that \'result\' is initialized. This will become a compile time error in the future. [ProveInit]" 0
chk     skUnknown               Hint    /home/dian/.nim/test.nim        5       4       "\'xs\' is declared but not used [XDeclaredButNotUsed]" 0
```

I'm not sure if this is the best way and I don't know if it breaks something out there:P

### CODE REVIEW

**Comment by alaviss** [comment]
This should fix nim-lang/nimsuggest#115 (please add a clause in your PR description so that the issue is closed automatically on merge)

**Comment by ghost** [comment]
Also found another case where there are phantom errors being reported, will try to fix that one too maybe:
```nim
import tables

type Obj = object

proc create: TableRef[string, Obj] =
  result = newTable[string, Obj]()

let a = create()
```

Output after this PR:
```
> chk a.nim
.chk    skUnknown               Hint    ???     0       -1      "a [Processing]"        0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/a.nim  6       19      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tables.nim 815     26      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tables.nim 338     26      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tables.nim 307     10      "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/.nim/lib/pure/collections/tableimpl.nim      130     24      "undeclared field: \'first\' "  0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/a.nim  6       19      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tables.nim 815     26      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tables.nim 338     26      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tables.nim 307     10      "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/.nim/lib/pure/collections/tableimpl.nim      130     24      "undeclared field: \'.\' "      0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/a.nim  6       19      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tables.nim 815     26      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tables.nim 338     26      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tables.nim 307     10      "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/.nim/lib/pure/collections/tableimpl.nim      130     24      "type mismatch" 0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/a.nim  6       19      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tables.nim 815     26      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tables.nim 339     44      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tableimpl.nim      36      14      "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/.nim/lib/pure/collections/tableimpl.nim      130     24      "undeclared field: \'first\' "  0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/a.nim  6       19      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tables.nim 815     26      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tables.nim 339     44      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tableimpl.nim      36      14      "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/.nim/lib/pure/collections/tableimpl.nim      130     24      "undeclared field: \'.\' "      0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/a.nim  6       19      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tables.nim 815     26      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tables.nim 339     44      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tableimpl.nim      36      14      "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/.nim/lib/pure/collections/tableimpl.nim      130     24      "type mismatch" 0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/a.nim  6       19      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tables.nim 815     26      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tables.nim 339     44      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tableimpl.nim      36      14      "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/.nim/lib/pure/collections/tableimpl.nim      130     24      "undeclared field: \'first\' "  0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/a.nim  6       19      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tables.nim 815     26      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tables.nim 339     44      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tableimpl.nim      36      14      "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/.nim/lib/pure/collections/tableimpl.nim      130     24      "undeclared field: \'.\' "      0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/a.nim  6       19      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tables.nim 815     26      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tables.nim 339     44      "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/collections/tableimpl.nim      36      14      "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/.nim/lib/pure/collections/tableimpl.nim      130     24      "type mismatch" 0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/a.nim  8       4       "\'a\' is declared but not used [XDeclaredButNotUsed]"  0
```

**Comment by ghost** [comment]
Sadly this does not fix https://github.com/nim-lang/nimsuggest/issues/115, after my PR the output is:
```
> chk test_lazytree.nim
.chk    skUnknown               Hint    ???     0       -1      "test_lazytree [Processing]"    0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      9       6       "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      11      7       "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/Projects/nim-mathexpr/test_lazytree.nim      14      30      "attempting to call undeclared routine: \'treeIter\'"   0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      9       6       "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      11      7       "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/Projects/nim-mathexpr/test_lazytree.nim      14      30      "attempting to call undeclared routine: \'treeIter\'"   0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      9       6       "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      11      7       "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/Projects/nim-mathexpr/test_lazytree.nim      14      30      "type mismatch" 0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      9       6       "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      11      7       "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/Projects/nim-mathexpr/test_lazytree.nim      14      30      "attempting to call undeclared routine: \'treeIter\'"   0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      9       6       "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      11      7       "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/Projects/nim-mathexpr/test_lazytree.nim      14      30      "attempting to call undeclared routine: \'treeIter\'"   0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      9       6       "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      11      7       "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/Projects/nim-mathexpr/test_lazytree.nim      14      30      "type mismatch" 0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      9       6       "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      11      7       "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/Projects/nim-mathexpr/test_lazytree.nim      14      30      "attempting to call undeclared routine: \'treeIter\'"   0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      9       6       "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      11      7       "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/Projects/nim-mathexpr/test_lazytree.nim      14      30      "attempting to call undeclared routine: \'treeIter\'"   0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      9       6       "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      11      7       "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/Projects/nim-mathexpr/test_lazytree.nim      14      30      "type mismatch" 0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/unittest.nim   625     24      "conversion from string to itself is pointless [ConvFromXtoItselfNotNeeded]"    0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/unittest.nim   671     13      "condition is always true: \'nodeSeq[0] of XmlNode\' [CondTrue]"        0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      9       6       "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      18      7       "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/Projects/nim-mathexpr/test_lazytree.nim      21      30      "attempting to call undeclared routine: \'treeIter\'"   0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      9       6       "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      18      7       "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/Projects/nim-mathexpr/test_lazytree.nim      21      30      "attempting to call undeclared routine: \'treeIter\'"   0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      9       6       "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      18      7       "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/Projects/nim-mathexpr/test_lazytree.nim      21      30      "type mismatch" 0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      9       6       "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      18      7       "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/Projects/nim-mathexpr/test_lazytree.nim      21      30      "attempting to call undeclared routine: \'treeIter\'"   0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      9       6       "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      18      7       "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/Projects/nim-mathexpr/test_lazytree.nim      21      30      "attempting to call undeclared routine: \'treeIter\'"   0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      9       6       "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      18      7       "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/Projects/nim-mathexpr/test_lazytree.nim      21      30      "type mismatch" 0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      9       6       "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      18      7       "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/Projects/nim-mathexpr/test_lazytree.nim      21      30      "attempting to call undeclared routine: \'treeIter\'"   0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      9       6       "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      18      7       "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/Projects/nim-mathexpr/test_lazytree.nim      21      30      "attempting to call undeclared routine: \'treeIter\'"   0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      9       6       "template/generic instantiation from here"      0
chk     skUnknown               Hint    /home/dian/Projects/nim-mathexpr/test_lazytree.nim      18      7       "template/generic instantiation from here"      0
chk     skUnknown               Error   /home/dian/Projects/nim-mathexpr/test_lazytree.nim      21      30      "type mismatch" 0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/unittest.nim   625     24      "conversion from string to itself is pointless [ConvFromXtoItselfNotNeeded]"    0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/unittest.nim   625     24      "conversion from string to itself is pointless [ConvFromXtoItselfNotNeeded]"    0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/unittest.nim   625     24      "conversion from string to itself is pointless [ConvFromXtoItselfNotNeeded]"    0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/unittest.nim   625     24      "conversion from string to itself is pointless [ConvFromXtoItselfNotNeeded]"    0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/unittest.nim   625     24      "conversion from string to itself is pointless [ConvFromXtoItselfNotNeeded]"    0
chk     skUnknown               Hint    /home/dian/.nim/lib/pure/unittest.nim   625     24      "conversion from string to itself is pointless [ConvFromXtoItselfNotNeeded]"    0
```

**Comment by ghost** [comment]
as @alaviss found out the bug with the type mismatch can be reproduced with this:
```
echo compiles(2 + "hello")
```

**Comment by alaviss** [comment]
`[backport]` please

**Review by alaviss — APPROVED** [review]

**Pull request merged**
