### PR TITLE
Do not include date in binaries

### PR DESCRIPTION
**Pull request by bmwiedemann**
and do not claim copyright for 2018
in order to make nim package builds reproducible.

See https://reproducible-builds.org/ for why this is good.

An alternative approach would be to implement using
[`SOURCE_DATE_EPOCH`](https://wiki.debian.org/ReproducibleBuilds/TimestampsProposal#Perl)
for CompileDate and CompileTime

### CODE REVIEW

**Comment by Araq** [comment]
Having to update the year every year manually is worse than the current solution.

**Comment by bmwiedemann** [comment]
Is there a way to have the `const copyrightYear = "2017"` in one place and change all users to use it from there?
Then the script that builds a release tarball could also update that file.

**Comment by Araq** [comment]
What's the point anyway, diff the binary files with a tool **slightly** smarter than ``memcmp``.

**Comment by bmwiedemann** [comment]
In openSUSE we already have a smart tool called `build-compare` that comes with a dozen filters for various formats but detecting date/time strings in the middle of binaries is not that trivial... and then you can never be sure that you dont ignore important changes by mistake.
That is why the goal of the reproducible-builds project is to be able to build bit-identical binary packages (and ISO images) where you can publish one sha256sum and other people build the package/ISO from sources and get the same sha256sum.
Maybe nim could do similar to gcc that accepted a patch to use $SOURCE_DATE_EPOCH for its __DATE__ and __TIME__ macros... it is just that I'm not that good at this language (yet) or I would have written it myself.

However, claiming copyright for future years is something I find questionable independent of that.

**Comment by Araq** [comment]
> An alternative approach would be to implement using SOURCE_DATE_EPOCH for CompileDate and CompileTime

Ok, that is beginning to sound good. But if that env var is not set, it should continue to use the current time.

**Comment by bmwiedemann** [comment]
>>  However, claiming copyright for future years is something I find questionable independent of that.

> I don't understand this, it uses the current year.

Yes, so when I build today's nim in 2018 it will say "Copyright 2018" even though no author can have worked on this version in 2018.

**Comment by bmwiedemann** [comment]
See also http://rb.zq1.de/compare.factory-20170807/nim-compare.out for how package diff looks.

**Comment by Araq** [comment]
> Yes, so when I build today's nim in 2018 it will say "Copyright 2018" even though no author can have worked on this version in 2018.

Since I work every day on Nim, this is a theoretical issue. Once development slows down I can reconsider this.

**Comment by bmwiedemann** [comment]
No, you are working every day on the master version, but when I talk about today's version, I mean
https://github.com/nim-lang/Nim/tree/b2a2522d2dcef2f85b7e1615fc0720d3475427de (or any release tarball) - things that do not change anymore - and they will still get a Copyright 2018 when built in 10 weeks.

**Comment by Calinou** [comment]
Is dating copyrights even useful today? Version information (version number or Git hash) can easily be looked up online, after all.

**Comment by dom96** [comment]
In fact, the date shouldn't be updated according to this: https://stackoverflow.com/a/2391555/492186.

We should be using "Copyright 2004" everywhere!

**Comment by FedericoCeratto** [comment]
It is not beneficial to move the year forward if only one date is present. The initial date should stay the same and ideally match the true year of authorship. It's possible to use a range e.g. "2004 - 2017", although it is not a requirement.

**Pull request merged**
