### PR TITLE
rename conflicting file names

### PR DESCRIPTION
**Pull request by krux02**
In nim, printed file-line-information is usually printed with just the file name. This is all nice and short, but it is ambiguous when there are several files with the same name in the project. I got intro trouble with this especially with ``tester.nim`` and ``ropes.nim``. While I was at it, I also took a look if there were other confliciting file names. I did not touch conflicting file names in the tests like ``foobar.nim`` or ``a.nim``, but those that were relevant and trivial to change I did change.

The rules I picked to rename something were the following:

 * Don't rename public API
 * If one of the ambiguous files is an included file, rename that one, because it does not affect a module name.
 * try to keep the file name of files that are edited often (keep names I go used to)

```
compiler/ropes.nim → compiler/compilerRopes.nim
lib/system/atomics.nim → lib/system/systemAtomics.nim 
lib/genode/alloc.nim → lib/genode/allocGenode.nim
nimdoc/tester.nim → nimdoc/testerNimdoc.nim 
nimpretty/tester.nim → nimpretty/testerNimpretty.nim 
nimsuggest/tester.nim → nimsuggest/testerNimsuggest.nim 
testament/htmlgen.nim → testament/htmlgenTestament.nim 
```

the names `compilerRopes` and `systemAtomics` are somewhat inconsistent (reverse order). But I've chosen them anyway. `systemAtomics` just sounds nicer than `atomicsSystem`, and `ropesCompiler` would just sound like a compiler for ropes which it isn't.

### CODE REVIEW

**Comment by Araq** [comment]
We don't use camelCased filenames though because Unix is case sensitive, we use snake_case for filenames.

**Comment by alehander42** [comment]
This would duplicate folder name into the filename: which is just not very cool and adding a lot of noise
Can't we just find duplicate filenames and add the folder for them in traceback? Let's fixt the internal feature to work in a better way with various codebases and not change a bunch of filenames which people are used to

**Comment by arnetheduck** [comment]
would this scheme be dependent on order of inputs? if yes, that's a bit sad, because then you can't predict the name and you can build a tool that reliably supports two-way mapping. a deterministic/order-independent scheme here would be good - at the end of the day, this is the same problem as coming up with a unique packange-module name..

**Comment by krux02** [comment]
@arnetheduck What scheme? I just renamed files. Predict tha name? What name and from what? Conflicting file names are not illegal in Nim. I have no idea what you are talking about.

**Comment by arnetheduck** [comment]
oh, sorry, I thought you renamed them automatically with some clever scheme in the compiler so the debug output would be better, not that you manually renamed files (didn't occur to me as it's not very scalable, and forgot to look at the diff :) )

**Comment by arnetheduck** [comment]
looking at it closer, it's the exact same issue we've been having - when a project grows, it inveitably starts having these conflicts.. seems a bit sad to have to repeat it manually like that in the filename, it's what namespaces are for.

**Comment by krux02** [comment]
> ..., it's what namespaces are for.

Filenames are not in namespaces. They are in folders. Folders allow the have the same file name multiple times. But folder names are often hidden in nim error messages. I think this can be improved.

**Comment by dom96** [comment]
> In nim, printed file-line-information is usually printed with just the file name

So why not change it to print more than that? Most people will run into this, renaming these files is a workaround. I second what @alehander42 said, even if it is just a few files, could we fix this some other more permanent way?

**Comment by krux02** [comment]
@dom96 Be careful when you say "most people". Do you really mean "most"?

**Comment by Araq** [comment]
There is `` --listFullPaths:on|off`` and `` --excessiveStackTrace:on|off``.

**Comment by krux02** [comment]
I am aware of ``--listFullPaths:on|off``  and ``--excessiveStackTrace:on|off``, but they are annoying to use. Usually it is much more of a hassle to recompile with those flags attached, than it is to just open the other file and go to the right location manually.

Apart from that, I thought it was a problem to you as well that all the ``tester.nim`` files are called ``tester.nim``.

**Pull request closed without merging**
