### PR TITLE
Fix: #11068 exposing procs

### PR DESCRIPTION
**Pull request by Bennyelg**

### CODE REVIEW

**Comment by Araq** [comment]
Ok, but the docs need to mention clearly that this is Windows specific functionality. Oh and please add doc comments.

**Comment by Bennyelg** [comment]
@Araq There are any docs explain about these procs at all ?

**Comment by Araq** [comment]
Well, no. :-)

**Comment by Bennyelg** [comment]
Since Im not familiar with add docs, can you please refer me to guide or something Ill write them down.
thanks.

**Comment by Araq** [comment]
Ok, will take over.

**Pull request merged**
