### PR TITLE
Remove install.txt and readme.txt

### LINKED ISSUE #4934: Clean up root of repo and release archives
There is far too many files in the root of the repo. IMO the following files should be removed/moved:
- bootstrap.sh
- build_tools.sh
- contributing.txt
- docstyle.rst
- finish.nim
- install.txt
- install_nimble.nims
- install_tools.nims
- readme.txt
- start.bat

Similarly I will need to look at the release tarballs/zip, I'm sure there is room for improvement there too.

### PR DESCRIPTION
**Pull request by Utwo**
Resolve #4934

### CODE REVIEW

**Comment by dom96** [comment]
Looks like there are tests that use these files... https://travis-ci.org/nim-lang/Nim/jobs/446785096#L3875

That's really poor, these tests should only load files that are inside the ``tests`` subdir.

**Comment by krux02** [comment]
take a look at the tests. They open readme.txt just for the sake of opening a file. You can fix the tests by letting them open the markdown version of the readme. I really approve the removal of these files because two different readme files with different content is just confusing.

**Comment by dom96** [comment]
> You can fix the tests by letting them open the markdown version of the readme. 

or they could just open their own source code... opening files from a relative parent directory is error prone as you can see here.

**Comment by krux02** [comment]
@dom96 but the tests don't open from a relative parent directory: https://github.com/nim-lang/Nim/blob/devel/tests/threads/threadex.nim#L31

**Comment by krux02** [comment]
@Utwo great solution

**Comment by timotheecour** [comment]
@Utwo 
> The rest of the tests now open their own source code

using `var inp = memfiles.open("tests/stdlib/tmemlinesBuf.nim")` in tests/stdlib/tmemlinesBuf.nim (+ all other similar changes in this PR) is not DRY, and will fail on any refactoring (such as the ones @narimiran is doing)
how about using `currentSourcePath` instead?
`var inp = memfiles.open(currentSourcePath())`

**Pull request merged**
