### PR TITLE
Clarifies experimental / parallel example on manual.rst

### PR DESCRIPTION
**Pull request by UNIcodeX**
Details:
Calling `useParallel()` in example fails with compiler error
  Error: 'parallel' section without 'spawn'

Adding `spawn` causes error:
  Error: internal error: (filename: "ccgexprs.nim", line: 1032, column: 17)
  No stack traceback available
  To create a stacktrace, rerun compilation with ./koch temp c <file>

Therefore a separate proc, `threadedEcho`, is added for the echo'ing
of the string, which allows the example to build, however, `sync()`
must be added so that the "echo in parallel" strings will actually
be shown on the terminal. Otherwise, the program will spawn of the
threads and exit before they can return to the main thread.

### CODE REVIEW

**Comment by UNIcodeX** [comment]
Observation: Sometimes without `sync()` all threads echo as expected, and sometimes they don't. I'm unsure if this is an issue with my machine(s).

**Comment by Araq** [comment]
``parallel`` does **not** require ``sync``! If it doesn't work, that's a bug, ``sync`` is wrong here.

**Comment by UNIcodeX** [comment]
I've ran it several more times without the `sync()` and did not have the issue. Chalking that one up to some wierdness.

**Comment by UNIcodeX** [comment]
Removed `sync()`.

Added output of thread number.

```nim
import threadpool
  {.experimental: "parallel".}

  proc threadedEcho(s: string, i: int) =
    echo(s, " ", $i)

  proc useParallel() =
    parallel:
      for i in 0..4:
        spawn threadedEcho("echo in parallel", i)

  useParallel()
```

example output:
```
echo in parallel 0
echo in parallel 3
echo in parallel 4
echo in parallel 1
echo in parallel 2
```

**Pull request merged**
