### PR TITLE
fix #13797

### LINKED ISSUE #13797: DateTime initializes to invalid state by default
DateTime initializes to invalid state by default

This makes it necessary to perform manual initiation to have valid data, something which nim is designed to avoid.

Without manual initialization, the common programming pattern of comparing a value to a default value is not possible, because the default value cannot be reproduced without the hackily creating another empty mutable datetime

### Example
```nim
var a:DateTime
import times

var d:DateTime

for k, v in fieldPairs(d):
  echo "k: ", k, " v: ", v

```

### Current Output
```
k: nanosecond v: 0
k: second v: 0
k: minute v: 0
k: hour v: 0
k: monthday v: 0
k: month v: 0 (invalid data!)
k: year v: 0
k: weekday v: Monday
k: yearday v: 0
k: isDst v: false
Traceback (most recent call last)
/home/carlo/a.nim(7)     a
/usr/lib/nim/pure/times.nim(1039) $
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output

output equivalent to a valid zerodate, similar to zeroduration

### Possible Solution

I currently manually initialize to fromUnix(0) as a workaround, but it would be good to have a valid nim-specific zero date to initialize from, such as the actual beginning of the gregorian calendar (Jan 1 0000)

### Additional Information

Minor inconsistency but these do consume brain cycles during application development, and these do add up

```
Nim Compiler Version 1.0.6 [Linux: amd64]
Compiled at 2020-02-08
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches: -d:release -d:nativeStackTrace


```

### PR DESCRIPTION
**Pull request by timotheecour**
* fix https://github.com/nim-lang/Nim/issues/13797
* failure unrelated (see https://github.com/ba0f3/telebot.nim/issues/49)

### CODE REVIEW

**Comment by Clyybber** [comment]
This is not a fix for #13797.
This merely "fixes" the repro snippet.
From the issue:

> Without manual initialization, the common programming pattern of comparing a value to a default value is not possible

**Comment by timotheecour** [comment]
> Without manual initialization, the common programming pattern of comparing a value to a default value is not possible

from my comment in that same bug report https://github.com/nim-lang/Nim/issues/13797#issuecomment-606378646
this works:
```nim
when true:
  import times
  var d:DateTime
  if d == DateTime.default:
    echo "unchanged"
```
(which is why i wanted to add `isDefault` to stdlib (maybe in `sugar`) which would just be: if `d.isDefault` , see https://github.com/nim-lang/Nim/pull/13526)

**Comment by Clyybber** [comment]
The issue here is that the default is bogus.

**Comment by timotheecour** [comment]
> The issue here is that the default is bogus.

in what sense? because the month is 0, which is invalid?
one way to fix that would be ot make months 0-based using an implicit offset of 1 (transparent change for users). But I'm not convinced yet thats needed; having an invalid default value is actually useful to check whether a value was initialized or not

**Pull request merged**
