### PR TITLE
logging: don't crash on nil strings

### PR DESCRIPTION
**Pull request by yglukhov**

### CODE REVIEW

**Comment by dom96** [comment]
Isn't it better to fail fast rather than continue with an invalid log?

**Comment by zielmicha** [comment]
Logging is frequently used for debugging. It is frustrating to add logging rarely visited branch only to see your process crashes after several hours.

**Comment by yglukhov** [comment]
What @zielmicha said, plus `logging` logic is not the one to decide whether nil string is an invalid value, because the code going further may treat nil string as totally valid.

**Comment by dom96** [comment]
oh well, alright. Merging.

**Pull request merged**
