### PR TITLE
VM: add int <-> float casts of the same size

### PR DESCRIPTION
**Pull request by cooldome**
Ability to cast float64 to/from int64  and float32 to/from int32 is very important . You can't implement exp, log operations without this cast. Ability to access exponent and mantissa separately, construct 2^N float where N is integer is fundamental block in many scientific operations. Therefore I have extended the vm casting capability to cast int to float and back if int and float are of the same byte size.

### CODE REVIEW

**Comment by skilchen** [comment]
but beware that the float32 handling in the VM is problematic as can be shown using your PR:
```nim
static:
  var a: float32 = 0.1'f32
  var b = cast[int32](a)
  echo b
  var c = cast[float32](b)
  echo a, " ", c, " ", a == c
```
prints:
```
1036831949
0.1 0.1000000014901161 false
```
the expected output would be:
```
1036831949
0.1000000014901161 0.1000000014901161 true
```
the cast of `a` to int32 gives the correct number 1036831949 for the bit-pattern of `0.1'f32`. I don't know why and where the VM is converting `0.1'f32` back to a float64 in the stringification and in the equality test.

**Comment by krux02** [comment]
The vm does not distinguish ``float32`` and `float64`. Every float is `float64` internally.

**Comment by krux02** [comment]
@skilchen I just looked at your code snippet. As I said ``float32`` is internally ``float64`` and that won't change. I don't want to support a style of programming that relies on lower precision that specified in order to work correct. I see three things that could be done to fix it.

- When parsing a float32 liternal, mask away the additional precision. So that 0.1'f32 actually has a different value than 0.1'f64.
- mask away the additional precision when printing. So that 0.1'f32 and 0.1'f64 appear to be slightly different, even if they are not.
- Warn about float32 usage in macros/static context. It's pretty pointless to use ``float32`` when everything is ``float64`` anyway. Using ``float32`` on the VM provides a false impression to save 4 bytes.

**Comment by skilchen** [comment]
Are you telling me that:
```nim
static:
  echo sizeof(0.1'f32)
```
giving:
`4`
is actually a lie?
The variable `c` in my code snippet seems to be a float32 in every respect.

But another beware: I don't really care about `float32` issues. This is just another entry in my list of Nim features marked as: _don't use_

**Comment by Araq** [comment]
> is actually a lie?

No, but the compiler can evaluate float32 with more precision than a float32 has, which is also true in Ansi C fyi.

**Comment by krux02** [comment]
@skilchen I am actually quite interested in that list. @cooldome I want to merge this PR I really like it. Can you please add an entry to the changelog?

**Comment by cooldome** [comment]
@krux02  alll done, I have update the changelog

**Pull request merged**
