### PR TITLE
Fixed spelling in os module.

### PR DESCRIPTION
**Pull request by Stromberg90**
Fixed two spelling errors I noticed when coding.

### CODE REVIEW

**Comment by GULPF** [comment]
It's not misspelled: https://en.m.wikipedia.org/wiki/If_and_only_if

**Comment by GULPF** [comment]
This is not the first time someone has thought that it's an error though, so maybe the wording should be changed.

**Comment by Araq** [comment]
Maybe, but I still think people can learn new things.

**Comment by Stromberg90** [comment]
Fair enough, not heard about it before, but always fun to learn something new 👍

**Pull request closed without merging**
