### PR TITLE
[superseded] Remove confusing <//>

### PR DESCRIPTION
**Pull request by ringabout**
According to this:
```nim
    if n.len > 0 and n[0].kind == nkIdent and n[0].ident.s == "<//>":
      discard "XXX Remove this hack after 0.20 has been released!"
```

### CODE REVIEW

**Comment by ghost** [comment]
AFAIK the problem is that csources are frozen at 0.20 so it's still required, although I might be wrong.
Also <//> actually means owned

**Comment by ringabout** [comment]
Yea, `<//>` is still required. It should be removed after `newruntime` is removed.

**Comment by ringabout** [comment]
https://forum.nim-lang.org/t/6440#39735

**Comment by timotheecour** [comment]
revisit pending https://github.com/nim-lang/Nim/pull/16282

**Pull request closed without merging**
