### PR TITLE
move assertions out of system: alternative way

### PR DESCRIPTION
**Pull request by ringabout**
image

### CODE REVIEW

**Comment by ringabout** [comment]
Hello @Araq 

Is something below fine or any advice?

- [x] `compiler/` uses `import std/assserts` direct
- [x] `lib/` uses `since (1, 7): import std/assserts` for `--useVersion:1.6`
- [x] `tests/` uses `import std/assserts` direct
- [x] patch nimble and c2nim using `--useVersion:1.6`
- [x] important packages use `--useVersion:1.6`
- [x] `runnableExamples` uses `import std/assserts` direct
- [x] patch docs and code-blocks

ref https://github.com/nim-lang/Nim/pull/19599#discussion_r823082933

**Comment by Araq** [comment]
Solid solution. I worry a bit about point

> runnableExamples or code-examples uses import std/assserts direct

But I have no better solution either, so it's probably fine.

**Comment by ringabout** [comment]
I see, thanks

**Comment by ringabout** [comment]
It seems to need to patch nimble and c2nim using `--useVersion:1.6` in this PR.

**Comment by ringabout** [comment]
This pr will focus on simply addition of `import std/assertions`. Other changes will move into separate PRs.

**Comment by ringabout** [comment]
- [x] make `--useVersion:1.6` work for `.nimble` file of important packages or something

some nimble files of important packages contain assert/doAssert

**Comment by ringabout** [comment]
- [x] it breaks the `runnableExamples` of important packages

I'm considering importing `std/assertions` automatically for `runnableExamples` for this PR transiently.

- [x] it breaks the building of important packages

**Comment by ringabout** [comment]
>  import std/assertions

gives `D:\a\1\s\lib\pure\collections\sequtils.nim(585, 12) Error: undeclared identifier: 'std'` strangely.

**Comment by ringabout** [comment]
The tests seem fines (CI failures are unrelated). After the final cleanup, I will split the key changes into separate PRs.

**Pull request closed without merging**
