### PR TITLE
fix #6472 Typed template arguments are substituted directly if they a…

### LINKED ISSUE #6472: Typed template arguments are substituted directly if they are compatible with parameter type
Consider the following example:

`
import typetraits

template foo(name: untyped, w: int8) =
  let name = w

foo(x, 0x00)
echo x.type.name   # prints 'int'
`

The argument passed into _foo_ is of type _int_, not _int8_. Since _int_ is convertible to _int8_, the template will accept the argument. However, the argument is then substituted directly, so that _name_ (and hence _x_) will receive the type _int_. I would have expected them to be of type _int8_ instead.

We can actually provoke a compiler error by using the template parameter in a way that is not convertible, i.e. by assigning it to an array as follows:

`
import typetraits

template bar(name: untyped; b1, b2: int8) =
  let name: array[2, int8] = [b1, b2]

bar(y, 0x11, 0x22)  # Error: type mismatch: got (array[0..1, int]) but expected 'array[0..1, int8]'
`

Note that the two integer parameters _b1_ and _b2_ are substituted as _int_, which results in _[b1, b2]_ to be of type _array[2, int]_, which is incompatible with _array[2, int8]_.

### PR DESCRIPTION
**Pull request by bung87**
…re compatible with parameter type

fix #6472  

after CI fails it seems need fix exists code for this.

### CODE REVIEW

**Comment by Araq** [comment]
I don't understand this fix.

**Comment by bung87** [comment]
have you check the issue? before this arguments will pass template's arguments type check, however when construct array will throw type mismatch. which means it passed as `int`.

**Comment by bung87** [comment]
also mentioned here https://github.com/nim-lang/Nim/issues/18667#issuecomment-896096078

**Comment by metagn** [comment]
While this looks like a hack at first glance, it's a special cased version of doing `argNode = semExpr(argNode, expectedType = paramType)` for integers. The issue is a consequence of `fitNode` not being called on template parameters.

Maybe this is too special cased, and I'm not sure if it works with varargs. Since this breaks code, it could be made an experimental feature, but I'm not sure who would opt in to it.

**Comment by bung87** [comment]
> While this looks like a hack at first glance, it's a special cased version of doing `argNode = semExpr(argNode, expectedType = paramType)` for integers. The issue is a consequence of `fitNode` not being called on template parameters.
> 
> Maybe this is too special cased, and I'm not sure if it works with varargs. Since this breaks code, it could be made an experimental feature, but I'm not sure who would opt in to it.

I dont think it's "special cased" or "made an experimental feature", it break packages code that depends on odd behavior, that can be fixed in user code, the problem is obvious to me, it doesn't respect concret param type user specified. I think whether it fixed like this or in other way.

**Comment by bung87** [comment]
template arguments not check right now, it may do check someday, at that time no need handle this case. so I'll close now.

**Pull request closed without merging**
