### PR TITLE
Improve sequtils

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Improve `sequtils`, use `result = newSeqOfCap[T](s.len div 4)` instead of `result = @[]`. Tiny diff.

### CODE REVIEW

**Comment by Araq** [comment]
What if my data is such that in practice `filter` produces a seq with 2 elements. Then we waste a ton of space. You cannot know these things in advance, all you can do is something obvious so that the reasonable programmer cannot complain. I know there are a couple of these people out there.

**Comment by arnetheduck** [comment]
the right thing to do here would be to remove the `newSeq` call altogether - ie if filter returns no items, no allocation or anything else should happen

**Comment by Araq** [comment]
`newSeq` for 0 doesn't allocate. At least not with ORC.

**Comment by arnetheduck** [comment]
> newSeq for 0 doesn't allocate. At least not with ORC.

but why bother calling it? it's just a pointless noop / relic from the `nil` past - that's the "anything else" part..

**Pull request closed without merging**
