### PR TITLE
docgen: don't create compiler's docs + cleanup

### PR DESCRIPTION
**Pull request by narimiran**

### CODE REVIEW

**Comment by timotheecour** [comment]
not sure why you removed compiler docs, I miss https://nim-lang.github.io/Nim/compiler/ast.html etc; it helps when working on compiler

**Comment by genotrance** [comment]
Nightlies on windows has been broken since this was added.

**Comment by timotheecour** [comment]
hmm, do you have a link? maybe `when not defined(windows): ...` would be less drastic?

**Comment by narimiran** [comment]
> I miss https://nim-lang.github.io/Nim/compiler/ast.html etc; it helps when working on compiler

...and there is no other way for you to build those docs locally to help you?? :roll_eyes:

**Comment by timotheecour** [comment]
that would require me to keep patching the compiler to locally revert you PR when working on compiler code (and then remembering to un-patch it when pushing a new PR) ; not exactly convenient.
Many nimble packages have nim doc generated pages available online, eg https://nitely.github.io/nim-regex/regex.html or http://c-blake.github.io/cligen/parseopt3.html
This makes it easy to both get a quick overview and as a reference.
`compiler` is itself a nimble package, and a rather important one; so I'm not sure why having online docs wouldn't make sense

**Comment by Araq** [comment]
Generated docs for Nim compiler itself do make sense, yes. However, it makes no sense these identifiers end up in theindex.html etc. We either should do it properly or not at all.

**Pull request merged**
