### PR TITLE
Remove deprecated sets.isValid, sets.toSet

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Remove Deprecated Set `sets.isValid`, `sets.toSet`.
- Changelog updated.

I tried to remove this long Deprecated unused proc in the past already,
but been told that needs to be kept for backwards compatibility with older pre-1.0 versions,
now that Breaking changes are allowed, I was thinking is time to remove the dead code.

### CODE REVIEW

**Comment by arnetheduck** [comment]
this seems to go a bit too far - the `initXxx` are prevalent in lots of working, well-written code and there's no reason to remove all that code from the "working" codebase available to the average Nim user.

**Comment by konsumlamm** [comment]
> this seems to go a bit too far - the `initXxx` are prevalent in lots of working, well-written code and there's no reason to remove all that code from the "working" codebase available to the average Nim user.

@arnetheduck note that this is about `initSet` which has been deprecated since 0.20, `initHashSet` still exists.

**Comment by juancarlospaco** [comment]
Ok, `initSet` is kept for now, because reasons, feel free to check again @konsumlamm

**Review by konsumlamm — APPROVED** [review]

**Comment by arnetheduck** [comment]
> note that this is about

I think the broader question here is why exactly these functions need to be removed - ie they are pretty harmless, even if they're not what you would use in new code: why specifically do they need to be removed? "can break things" does not mean "must break things".

**Comment by konsumlamm** [comment]
> I think the broader question here is why exactly these functions need to be removed - ie they are pretty harmless, even if they're not what you would use in new code: why specifically do they need to be removed? "can break things" does not mean "must break things".

I don't see any reason *not* to remove functions that have been deprecated since before 1.0 even was released.

**Comment by juancarlospaco** [comment]
It is literally a one-liner proc, if someone needs it, just type it.

**Comment by arnetheduck** [comment]
> I don't see any reason not to remove functions that have been deprecated since before 1.0 even was released.

because it's a cost for Nim: it tells people that if they create a project in Nim, it's likely to stop working for reasons the contributors to Nim cannot articulate, beyond "but it was deprecated" - keep in mind that anything using these functions was working just fine before.

Being able to articulate the rationale for breaking somebody elses code is a good first step: then you can start reasoning about the relative cost for keeping the function vs removing it.

> It is literally a one-liner proc, if someone needs it, just type it.

No, it's really not: it's a blog post about Nim from which a beginner copy-pastes, that used to work and now breaks. It's a project that's been running flawlessly and would want to rely on their code to continue working when their distro updates Nim behind the scenes. It's a CTO looking to decide if Nim is a viable candidate for their next project, and trying to estimate the maintenance cost of just having to keep up with the language.

The cost of breaking things is asymmetric: there is little to no cost maintaining these functions but the cost to users is multiplired by the number of users.

**Comment by konsumlamm** [comment]
> > I don't see any reason not to remove functions that have been deprecated since before 1.0 even was released.
> 
> because it's a cost for Nim: it tells people that if they create a project in Nim, it's likely to stop working for reasons the contributors to Nim cannot articulate, beyond "but it was deprecated" - keep in mind that anything using these functions was working just fine before.

Breaking changes are to be expected for a new major release. `initSet` was deprecated because it's a bad name (there is the builtin `set`, `HashSet` and `OrderedSet`), at least that's what I would expect. If a project using `initSet` works fine, ignoring deprecation warnings for almost 3 years, then idk what to tell the author(s) other than to update their code. Alternatively, they're free to continue using Nim 1.x.

**Comment by arnetheduck** [comment]
> bad name

a bad name sounds like a reasonable reason to deprecate something: new code will use the newer, prettier, much shinier name and will therefore be so much better. 

But what is it a reason to _remove_ it from Nim? what is the benefit to Nim that is blocked by the non-removal of the function that motivates breaking things, beyond "let's break things because we changed a number".

**Comment by Vindaar** [comment]
Case in point, I'm one of the people who apparently didn't replace instances of `toSet`. `toSet` is just nice and short (why write `toHashSet` each time?).

@juancarlospaco It's used for the docgen in ggplotnim as well as arraymancer. I'm at fault for both I fear.

**Comment by Araq** [comment]
In principle, we can also un-deprecated things that we don't intend to remove. Not sure if we should do it for these names though.

**Comment by juancarlospaco** [comment]
An interesting thing to think about is why you keep so much Deprecated stuff in your code,
even after several releases and years passed by, and deprecated has `Use FOO instead` usually,
because at least some of those can be bugs and vulns basically, 
how can `{.deprecated.}` be improved and more """enforcing""" ?. 🤔

**Comment by arnetheduck** [comment]
> because at least some of those can be bugs and vulns basically,

Because you checked that your code is not affected by the deprecation, then let it be: this allows you to use the same code on your side with a wider range of upstream versions, maintaining greater flexibility - this is absolutely critical for any kind of progress in terms of making more nim libraries available to users: you can't go breaking the existing ones every year,: the standard library is unique in it's ability to take down large amounts of working Nim code because it sits at the root of every dependency.

The question is better asked in the other direction: if it's not a critical security issue, why would you go about breaking someone else's code for trivial reasons such as a rename, when the old name is not blocking any new functionality? This is strictly worse than leaving it there, for the whole community - again: are you able to articulate why it's so important to remove these functions? This is a good litmus test.

> we can also un-deprecated things

Generally, I think it's better to keep them deprecated: new code is better off using the more consistent naming - the deprecations also give us the option to remove the functions in the future, should we have an actual reason to do so (say, because they interfere with some other functionality).

**Pull request closed without merging**
