### PR TITLE
Prevent memory re-initialisation for complex values with GC'ed refs

### PR DESCRIPTION
**Pull request by mbaulch**
Fixes https://github.com/nim-lang/Nim/issues/4168.

### CODE REVIEW

**Comment by mbaulch** [comment]
Have looked into the effects of this patch when buliding the Nim compiler. It removes ~10 unnecessary memset calls from the C output (debug and release builds). Using a recent version of GCC, the final output is unaffected for both debug and release builds.

Maybe we can just rely on peephole optimisations in our C-compilers? I have a feeling that TinyC won't be quite so clever—particularly for debug builds.

There are other similar opportunities for optimisation in the Nim compiler. For instance, memcpy often follows memset: completely overwriting every byte originally cleared.

Should the Nim compiler, ideally, output reasonably compact and efficient C; or are we happy to ignore an easy optimisation if our favourite (or most) C compilers perform it anyway?

**Comment by Araq** [comment]
> Should the Nim compiler, ideally, output reasonably compact and efficient C; or are we happy to ignore an easy optimisation if our favourite (or most) C compilers perform it anyway?

More optimizations are always nice, but in the longer run I would rewrite the code generators by AST to AST transformers so that optimizations are way easier to perform.

**Comment by mbaulch** [comment]
AST to AST transforms. That'd allow higher level optimisations, but obviously not target-specific ones. I agree that they'd be much easier to perform. Unless you're considering representing the C output as an AST before generation? That might be another helpful option.

Would an optimisation pass (that obviously doesn't run on debug builds) be a suitable way forward? Otherwise, I suppose the alternative is incremental optimisation '_on the go_'. I don't have a strong opinion. Both approaches have pros and cons.

My only strong view is that optimisation specific to C/C++ is where most of the opportunity lies. The reason is it's quite easy to generate good high-level code, since Nim has such powerful metaprogramming capabilities.

Once an optimisation strategy is agreed upon, I'd be happy to spend some time on it. There seems to be quite a bit of low hanging fruit.

**Comment by Araq** [comment]
> Unless you're considering representing the C output as an AST before generation? That might be another helpful option.

Yes, but I would re-use the existing AST for this, so that all the debugging helpers continue to work. Not sure if that's entirely feasible though.

> Would an optimisation pass (that obviously doesn't run on debug builds) be a suitable way forward?

Sure, but I would always enable it for our end users, making the compiler more deterministic and thus easier to get right.

**Comment by mbaulch** [comment]
Good point about the debugging helpers. With a C specific AST, that information would have to be back-propagated somehow. On the other hand, incorporating C (and C++, js?) type information into the existing AST might be messy. Maybe it's managable?

Anyway, thanks for sharing your thoughts.

I'll have a look for a (relatively) easy way to test some of these ideas.

This PR is obviously a step in the wrong direction.

**Comment by Araq** [comment]
> This PR is obviously a step in the wrong direction.

Hmm, I really like it though. Big rewrites shouldn't prohibit incremental improvements.

**Comment by mbaulch** [comment]
I suppose that's true. We want Clang, TinyC and others to generate good binaries too.

That being the case, I'll see whether I can optimise the (quite common)
```
memset((void*)(&T), 0, sizeof(T));
chckNil((void*)(&T));
memset((void*)(&T), 0, sizeof(T));
```

chain with a similar technique.

**Comment by Araq** [comment]
Can you also look into this please?

https://github.com/nim-lang/Nim/issues/4354

**Comment by mbaulch** [comment]
Ok

**Comment by dom96** [comment]
What shall we do with this PR? Cleanup?

**Comment by Araq** [comment]
We need to resolve conflicts, it's fine.

**Comment by yglukhov** [comment]
What is the status of it? Still actual?

**Comment by Araq** [comment]
Sorry, this needs to be fixed differently. We are telling ``getTemp`` what to do, it shouldn't return what it really did do.

**Pull request closed without merging**
