### PR TITLE
Add styledWrite macro

### PR DESCRIPTION
**Pull request by kaushalmodi**
Also:

- Move the tests block to the end of the file
- Fix the older tests
- Convert styledEcho from a macro to a template, add tests for that.
- Convert styledWriteLine from a macro to a template, add more tests for that.
- Add new tests for styledWrite

Fixes https://github.com/nim-lang/Nim/issues/8046.

---

This commit works, but I don't understand the macro syntax, and would like `styledWriteLine` to reuse `styledWrite` that I added. 

Let me know if that optimization needs to be made before this can be committed.. or if someone can optimize that after this gets committed.

Also, need to fix these warnings:

> terminal.nim(706, 11) Warning: use varargs[untyped] in the macro prototype instead; callsite is deprecated [Deprecated]
> terminal.nim(740, 11) Warning: use varargs[untyped] in the macro prototype instead; callsite is deprecated [Deprecated]

Thanks!

### CODE REVIEW

**Comment by kaushalmodi** [comment]
This was my naive approach for refactoring `styledWriteLine`, but if of course doesn't work..

```nim
macro styledWriteLine*(f: File, args: varargs[typed]): untyped =
  ## Similar to ``writeLine``, but treating terminal style arguments specially.
  ## When some argument is ``Style``, ``set[Style]``, ``ForegroundColor``,
  ## ``BackgroundColor`` or ``TerminalCmd`` then it is not sent directly to
  ## ``f``, but instead corresponding terminal style proc is called.
  ##
  ## Example:
  ##
  ## .. code-block:: nim
  ##
  ##   proc error(msg: string) =
  ##     styledWriteLine(stderr, fgRed, "Error: ", resetStyle, msg)
  ##
  result = newCall(bindSym"styledWrite")
  result.add(f)
  for arg in children(args):
    result.add(arg)
  result.add(newCall(bindSym"write", f, newStrLitNode("\n")))
```

**Comment by Vindaar** [comment]
You can fix the refactored approach like so:
```nim
macro styledWriteLine*(f: File, args: varargs[typed]): untyped =
  # result should be a statement list
  result = newStmtList()
  # create new call with `f` as first argument
  result.add newCall(bindSym"styledWrite", f) 
  for arg in children(args):
    # append all arguments to the `nnkCall` node
    result[^1].add(arg)

  result.add(newCall(bindSym"write", f, newStrLitNode("\n")))
```

**Comment by kaushalmodi** [comment]
@Vindaar Actually I just converted the 2 unnecessary? macros to templates.. can you check this PR in entirety?

/cc @krux02

**Comment by kaushalmodi** [comment]
Earlier when `styledWriteLine` was a macro, below:

```nim
stdout.styledWriteLine(fgRed, "red text ")
stdout.styledWriteLine(fgWhite, bgRed, "white text in red background")
stdout.styledWriteLine(" ordinary text ")
stdout.styledWriteLine(fgGreen, "green text")
```

resulted in:

image

Now the same test, with `styledWriteLine` now being a template, and the newline added **after** the `resetAttributes` call in `styleWrite`, results in this:

image

**Comment by kaushalmodi** [comment]
Except for the "callsite is deprecated" warning that was already there, I am happy with this PR now.

Would be great if someone can review this further.

**Comment by krux02** [comment]
just my two cents for the example, you changed ``stderr.styledWrite`` to ``stdout.styledWrite``.  There is a convention in unix systems, that output on stdout can be further processed by another application if you pipe it into that program, and stderr the actual text the user is supposed to see. processed text in other appications should better not have colors in them. So I prefer if the example of styleWrite remains on stderr. Apart from that I think it's ok.

**Comment by kaushalmodi** [comment]
> you changed stderr.styledWrite to stdout.styledWrite

> So I prefer if the example of styleWrite remains on stderr. 

Just to clarify, the `styledWrite` wasn't there at all to begin with. It was added in this PR.

As `styledWriteLine` had an *stderr* example, I decided to throw in a variety and set the new `styledWrite` example to have *stdout*.

> There is a convention in unix systems, that output on stdout can be further processed by another application if you pipe it into that program, and stderr the actual text the user is supposed to see. 

I completely agree with that. But this example is just about displaying colorful text on stdout.

> processed text in other appications should better not have colors in them.

I believe, the application developer should consciously prevent adding colors based on `terminal.isatty`? ([my related blog on that][1])

[1]: https://scripter.co/nim-check-if-stdin-stdout-are-associated-with-terminal-or-pipe/#using-terminal-dot-isatty

**Comment by krux02** [comment]
I mean there are things that are obviously still wrong, but they have never been in a better state either. When two threads call styledWriteLine at the same time, the lines can be interleaved. With for example printf, this can't happen. Neither can it happen with ``echo`` afaik.

**Comment by dom96** [comment]
Looks good :)

**Pull request merged**
