### PR TITLE
fix mime types data

### PR DESCRIPTION
**Pull request by bung87**
generated via https://github.com/bung87/mimetypes_gen

source data: http://svn.apache.org/viewvc/httpd/httpd/trunk/docs/conf/mime.types?view=co

### CODE REVIEW

**Comment by Araq** [comment]
How come this removes more lines than it adds?

**Comment by bung87** [comment]
it removes something like below
```nim
"a": "text/plain",
"asc": "text/plain",
"bas": "text/plain",
"brf": "text/plain",
"cc": "text/plain",
"cxx": "text/plain",
"def": "text/plain",
.....

```

I have no idea where these come from, and never seen this in my real life.
the most important thing to me is I don't want `getExt("text/plain")` gives me "a".

**Comment by Araq** [comment]
CI failure seems to be unrelated, merging.

**Comment by ire4ever1190** [comment]
These extensions got removed
```nim
  "nim": "text/nim",
  "nimble": "text/nimble",
  "nimf": "text/nim",
  "nims": "text/nim",
```
Was that expected?

**Comment by Araq** [comment]
Nope, we need to bring these back! :-)

**Pull request merged**
