### PR TITLE
Add logical AND-assignment and logical OR-Assignment

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Added [logical AND-assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND_assignment) and [logical OR-Assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment) for JavaScript targets.
- https://caniuse.com/mdn-javascript_operators_logical_and_assignment 
- https://caniuse.com/mdn-javascript_operators_logical_or_assignment

### CODE REVIEW

**Comment by Araq** [comment]
Why? Nim programmers should write Nim code that we compile to JS, not JS code.

**Comment by juancarlospaco** [comment]
For interop purposes with the browser, it is useful for big heavy objects.
I mean there's `emit` for C targets and people don't go emit'ing whole modules.

**Comment by juancarlospaco** [comment]
@Araq Would you prefer to use a name like `andAssign` instead of `&&=` ? 🤔

**Comment by Araq** [comment]
No, I don't get the point at all, it's not about the name. Javascript uses `+` for string concats, should we also import its plus operator then? It just makes no sense...

**Pull request closed without merging**
