### PR TITLE
std/tasks: fix spelling

### PR DESCRIPTION
**Pull request by arnetheduck**
why aren't these not being caught by style check options?
--styleCheck:usages finds it.

### CODE REVIEW

**Comment by arnetheduck** [comment]
needs 1.6 backport pls!

**Comment by ringabout** [comment]
> why aren't these not being caught by style check options?

Because there is no style check for stdlibs. I may revive my PRs enabling styleCheck:usages for tests if I have time (#19319; #19356)

**Comment by arnetheduck** [comment]
> Because there is no style check for stdlibs. 

isn't this part of the nep-1 requirement? 

> I may revive my PRs enabling styleCheck:usages for tests if I have time.

much appreciate! errors of this kind in the std lib prevents the feature from being used downstream (and causes the same kinds of security / audit problems as we've faced)

**Comment by ringabout** [comment]
> why aren't these not being caught by style check options?

`nim c -r --styleCheck:error test.nim` can catch the inconsistency

Error: 'newcall' should be: 'newCall' [proc declared in C:\Users\blue\.choosenim\toolchains\nim-#devel\lib\core\macros.nim(687, 6)]

> isn't this part of the nep-1 requirement

Yeah, compiler enfores `styleCheck:error` (https://github.com/nim-lang/Nim/blob/devel/compiler/nim.cfg#L18) which checks nep1 style. However, the option is not applied to stdlibs or tests.

**Pull request merged**
