### PR TITLE
Added FileSeekPos

### PR DESCRIPTION
**Pull request by yglukhov**

### CODE REVIEW

**Comment by dom96** [comment]
I would honestly prefer a separate procedure for this. Using ``setFilePos`` with a ``FileSeek`` that is ``fspCur`` or ``fspEnd`` contradicts the name.

**Comment by yglukhov** [comment]
I don't mind putting this into a different proc, but I can see 2 reasons to keep it in one.
1. This is a pretty conventional functionality. It even maps to C one-to-one.
2. The `setFilePos` name looks fine and logical to me. Setting cursor pos doesn't necessarily imply that the pos is absolute (but its the default anyway). It may be relative to beginning, current or end. Also I could rename `whence` to `relativeTo` and it would be read almost like human language =)

**Comment by dom96** [comment]
> Also I could rename whence to relativeTo and it would be read almost like human language =)

I like this idea. Do it :)

**Comment by yglukhov** [comment]
there

**Comment by dom96** [comment]
Thanks :)

**Pull request merged**
