### PR TITLE
stats.nim pure library (moved from math lib to new lib)

### PR DESCRIPTION
**Pull request by jlp765**
As discussed in issue #3512

Removal of RunningStat stuff from pure lib math.nim
Addition of new pure lib stat.nim

Extended RunningStat
Added RunningRegress for linear regression and correlation of two data sets

### CODE REVIEW

**Comment by mjoud** [comment]
While a separation of `stats` and `math` makes perfect sense, this PR does not include procs for `openArray`s (eg. `variance` is still in `math.nim`). Any possibility of including this as well?

**Comment by jlp765** [comment]
Shouldn't we remove the openarray stats fuinction of mean and variance, so that the "one source of truth" is the RunningStat.push() method ?

The RunningStat now has the procs to push an openarray of data values.

```
var rs: RunningStat

rs.push(@[1,2,3,4,5,6,7,8,9,10])
echo rs.varianceS()
```

**Comment by Araq** [comment]
> The RunningStat now has the procs to push an openarray of data values.

That is fine but a version of 'variance' that directly works on an openarray is suggested by our guidelines: "Ease of use is measured by the number of calls to achieve a concrete high level action."

http://build.nim-lang.org/docs/apis.html

**Comment by c-blake** [comment]
Floating point division is one of the most expensive CPU instructions out there.  If there is even a _slight_ chance that users may push multiple times between queries of the running stats then you should really use mean=sum/n, not the incremental formula.  Similar comments apply for the other moments and regression.  You probably want the sums to be float64, but other than that there should be no accuracy issues.

**Comment by c-blake** [comment]
Also, an "unpush()" or "pop()" proc to undo the effect of a prior push (adjusting both the running sums and n) would make it easy to have RunningStats be usable in a "moving window" over the data context (at no extra cost for people not using it that way).

**Comment by jlp765** [comment]
When calculating the 3rd and 4th moment, those floating point calculations are needed anyway, so I don't think you will save much, but by all means do a PR.

The difference between this and the previous version (on my PC) is 0.5 seconds for 1.0e8 pushes of data.
I argue that being able to provide the 3rd & 4th moment outway the slow down  (all for the same O(1) processing).

Also the helper procs that provide the stats for standalone seq[] could be faster by doing non-running stats, but by using the same RunningStat mechanism, provides a single source of truth.

**Comment by c-blake** [comment]
Not true - all push() needs to do is sum += x; sq = x*x; sumsq += sq; sum3 = x*sq; sum4=sq*sq; n += 1.  That's it! (and an unpush/pop would just reverse those totals).  There are divisions in queries for the moments, of course.  And regression needs a cross-term (like x*y).   If there are several/many pushes per query you should be able to save a lot of work.

It is also true that a vectorized array processor would be faster still, though, especially with avx256 or avx512 on the backend.  That could come later, though, with the incremental implementation as a comparison point and just some unit test to check they produce similar answers to within round-off.  I may do a pull request shortly.  Just replying quickly here to make my proposal more clear.

**Comment by c-blake** [comment]
Damn... my asterisks got dropped.  Sorry.  I'm not so used to quoting markdown, but I am sure you get the gist.

**Pull request merged**
