### PR TITLE
fixes #20865; [backport]

### LINKED ISSUE #20865: Missing range check in `toOpenArray`
### What happened?

```nim
var p: pointer
var x: array[0, int]
# echo toOpenArray(x, 0, 1)[0] # Raises IndexDefect
echo toOpenArray(cast[ptr array[0, int]](p)[], 0, 1)[0] # Does not raise IndexDefect
```

Both `toOpenArray` should raise an index defect but the latter doesn't.

### Nim Version

1.6, devel

### Current Standard Output Logs

_No response_

### Expected Standard Output Logs

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Araq**

### CODE REVIEW

**Comment by Araq** [comment]
This breaks nimcrypto ...?

**Comment by ringabout** [comment]
https://github.com/cheatfate/nimcrypto/pull/61 will fix the nimcrypto test.

**Comment by arnetheduck** [comment]
still relevant I'm guessing

**Comment by ringabout** [comment]
https://github.com/nim-lang/Nim/issues/20865 has been fixed

**Pull request closed without merging**
