### PR TITLE
Fixed when nimvm in generics.

### PR DESCRIPTION
**Pull request by yglukhov**
Prevent transformation of nimvm magic in generic code.

### CODE REVIEW

**Comment by Araq** [comment]
Why is this necessary? It seems wrong, 'nimvm' is a symbol like any other symbol.

**Comment by yglukhov** [comment]
If "when nimvm" is used inside a generic proc, nimvm ident here gets transformed to sym, which is later semfolded. Currently "when nimvm" semantics expects nimvm node to be nkIdent, and resolves it only to check its magic.

**Comment by Araq** [comment]
Well so fix your nimvm detection logic to account for nkSym too.

**Comment by yglukhov** [comment]
Fixed.

**Pull request merged**
