### PR TITLE
Add Example code to Documentation comment of wordWrap proc.

### PR DESCRIPTION
**Pull request by jiro4989**

### CODE REVIEW

**Comment by Araq** [comment]
Patch ``std / wordwrap`` instead and make use of ``runnableExamples``.

**Comment by jiro4989** [comment]
@Araq 
Thx. I changed.

**Comment by Araq** [comment]
Please patch the file ``lib/std/wordwrap.nim`` instead.

**Comment by Araq** [comment]
wordwrap_examples1.nim(7, 24) Error: attempting to call undeclared routine: 'repeat'

**Comment by jiro4989** [comment]
@Araq oh, very sorry.
I didn't know detail of 'runnableExample'.
I read documents of 'runnableExample', and I did 'nim doc'.
I confirmed generating wordwrap.html and no error.

**Pull request merged**
