### PR TITLE
Add new hashing algorithms (SHA2, SHA3, bcrypt) to pure stdlib

### PR DESCRIPTION
**Pull request by chmod222**
This is a followup to implement (part of) #19863.

This sequence of commits adds the following new modules to the stdlib:

 - std/sha2
 - std/sha3
 - std/bcrypt

In total, the following algorithms are implemented for the C, C++ and JS backends:
 - SHA2-224, SHA2-256, SHA2-384 and SHA2-512
 - SHA3-224, SHA3-256, SHA3-384 and SHA3-512
 - SHAKE128, SHAKE256 and SHAKE512 of the SHA3 extendable-output family
 - bcrypt with hash verification support for `$2a`, `$2b` and `$2y` hashes, as well as generation of `$2b` hashes.

The SHA2 and SHA3 families have been verified against the Cryptographic Algorithm Validation Program response files provided by NIST, specifically, the "ShortMsg" and "LongMsg" testcases (1632 tests in total). I would have liked to turn them into unit tests, had I found any licensing information on these files that would permit me to do this.

As discussed further in #19863, the MD5 and SHA-1 modules are left in place as they are fully functional, but hints have been added noting their issues while referring to the newer families of cryptographic hashing functions.

The bcrypt implementation is based on the OpenBSD reference implementation and also validated correctly against outside produced hashes as well as producing hashes acceptable to other implementations.

---

Now with the technical details out of the way, this being my first proper pull request adding more than just a bugfix, feel free to correct me on issues pertaining to code style and API design, as I don't particularly have much experience in standard library design.

### CODE REVIEW

**Comment by arnetheduck** [comment]
I'd strongly recommend against these algorithms in the std lib - they are available in various forms in (nimble) libraries already, and there is no need to tie their implementation to the nim release cycle - in particular, these algorithms are used in security-sensitive places where tradeoffs between performance (assembly code effectively) and security (constant-timeness) must often be made.

Typical for secure hash algorthms is that they come with significant test suites as well (ie lots of "known" hashes, fuzzing, etc), which is not the case here.

**Comment by chmod222** [comment]
> they are available in various forms in (nimble) libraries already

That was the question I raised in #19863 as well, but the consensus was that having secure algorithms in the standard library is the point, whereas now there are only insecure options and a lot of people will, out of convenience, jump to what's available *now* rather than what they'd have to research first. These implementations are absolutely no replacement for nimcrypto, but they are a big improvement in default security over what's currently there.

> Typical for secure hash algorthms is that they come with significant test suites as well (ie lots of "known" hashes, fuzzing, etc), which is not the case here.

As noted in the description, while I haven't fuzzed the implementations, they did run through the validation files provided by NIST. If I was absolutely sure that those could be distributed in the form of unit tests, I'd have done so, but alas I couldn't find any licensing information. Although I can certainly push the validation script I used.

As for bcrypt, before this is actually seriously considered I'd like to add some unit tests in addition to the `runnableExamples` that go through a large amount of hashes.

**Comment by arnetheduck** [comment]
nevertheless, _because_ better alternatives exist in libraries, moving the existing std lib implementations to standalone libraries is all that's needed to avoid the convenience pitfall - the way to reach there is simple:

* create nimble libraries that are copies of the existing libraries
* deprecate the ones in std, noting that they are insecure and that people that _explicitly_ want to keep using them without modifying their existing code should use the non-deprecated version in the newly exported library - people using std won't see their code break but will get deprecation warnings - people using the library version can continue to do so (for example those that are implementing protocols that need these old algos)
* point people to more secure alternatives in libraries

adding these algos to the std lib means we'll be repeating this same conversation in 2-3 years when they become obsolete - libraries are structurally better equipped in all ways to deal with change like this (and can receive improvements more quickly).

**Comment by Araq** [comment]
These must be moved to the new nim-lang/checksums package. @ringabout

**Comment by ringabout** [comment]
> These must be moved to the new nim-lang/checksums package

@chmod222 Hey, thanks for your excellent work! I have moved the changes by https://github.com/nim-lang/checksums/pull/2 using command `git commit --amend --author="chmod222 <304922+chmod222@users.noreply.github.com>" -m "Add new hashing algorithms (SHA2, SHA3, bcrypt) to pure stdlib"`.

**Pull request closed without merging**
