### PR TITLE
Use 0 as default socket protocol

### PR DESCRIPTION
**Pull request by iacore**
This will make `newSocket(net.AF_INET, net.SOCK_DGRAM)` work.

### CODE REVIEW

**Review by dom96 — COMMENTED** [review]
This is a breaking change, right? If so I don't think we should make it, we can support IPPROTO_DEFAULT though.

**Comment by iacore** [comment]
Not particularly breaking. Existing code using TCP will continue to work.

**Comment by dom96** [comment]
I'm not sure what repercussions this will have so I would prefer if we didn't change the default.

**Comment by iacore** [comment]
> I'm not sure what repercussions this will have so I would prefer if we didn't change the default.

Creating UDP sockets would be need explicit `UDP` as protocol.

**Comment by dom96** [comment]
> Creating UDP sockets would be need explicit UDP as protocol.

You mean without this change that would be necessary? I don't think this is a problem.

My concern is if `IPPROTO_DEFAULT` isn't available on some operating systems or older Linux kernels.

**Comment by iacore** [comment]
This is from [POSIX.1](https://pubs.opengroup.org/onlinepubs/9699919799.2008edition/) (can't find older specs)

```
NAME

    socket - create an endpoint for communication

SYNOPSIS

    #include <[sys/socket.h](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_socket.h.html)>

    int socket(int domain, int type, int protocol);

DESCRIPTION

    The socket() function shall create an unbound socket in a communications domain, and return a file descriptor that can be used in later function calls that operate on sockets. The file descriptor shall be allocated as described in [File Descriptor Allocation](https://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html#tag_15_14).

    The socket() function takes the following arguments:

    domain
        Specifies the communications domain in which a socket is to be created.
    type
        Specifies the type of socket to be created.
    protocol
        Specifies a particular protocol to be used with the socket. Specifying a protocol of 0 causes socket() to use an unspecified default protocol appropriate for the requested socket type.
```

**Comment by Araq** [comment]
If you want Posix compatibility, use posix.nim, the Nim stdlib tries to provide good defaults, not historic defaults.

**Pull request closed without merging**
