### PR TITLE
[nep1] Use `std` prefix for standard library modules

### PR DESCRIPTION
**Pull request by ringabout**

### CODE REVIEW

**Comment by Araq** [comment]
Can be done in this PR or a different PR: Please also update the examples in our tutorials to use `import std / [...]`

**Comment by ringabout** [comment]
will update tutorials in the following prs.

**Comment by ghost** [comment]
on the topic if `std` imports, what syntax is preferred? `import std / [a, b, c]` or `import std/[a, b, c]`?

**Comment by timotheecour** [comment]
* since we usually write `std/a` (not `std / a`) IMO it should be `std/[a,..` not `std / [a,...`
* between `std/[a,b]` and `std/[a, b]` I'm agnostic, but `std/[a, b]` seems more consistent with rest of style guide

In future work we should make sure that `nimpretty` follows those guidelines

**Review by timotheecour — APPROVED** [review]

**Review by dom96 — APPROVED** [review]

**Pull request merged**
