### PR TITLE
arc devel

### PR DESCRIPTION
**Pull request by Araq**
more ARC related bugfixes and refactorings

### CODE REVIEW

**Comment by Araq** [comment]
@cooldome please test this branch with your codebase.

**Comment by cooldome** [comment]
Sure, can do it on Monday

**Comment by cooldome** [comment]
I wanted to try this one today but I have found that thanks to the #12766 fix, the code now compiles
with latest Nim devel but I get crashes at the runtime. Need to chase them down. 
One was very weird, when I compile the whole  project a simple proc in one module:
```nim
proc add(c: Container, x: sink MyValue)
```
didn't get the destructor injection for `x` argument. But when I compile just this module it gets destructor injection. No generics, no inline. 

Will keep on debugging and compare generated code.

**Comment by Araq** [comment]
@cooldome If the current devel cannot compile your projects we might as well go ahead and merge this PR, right?

**Comment by cooldome** [comment]
Yes, looks like is going to take some time to trace it down. Please submit and we can fix it later.

**Comment by narimiran** [comment]
Note to the person who will merge this: beware that _some_ of the commits have `[backport]` tag. Merge carefully :)

**Pull request merged**
