### PR TITLE
fix #2614 improve error message when array of proc calling convention…

### LINKED ISSUE #2614: sigmatch error confusing when (inferred) pragmas mismatch (eg;  {.locks.}; or {.closure.} calling convention)
``` nimrod
proc g
proc f =
  if false: g()
proc g =
  if false: f()

var a = [f, g] # This works
var b: array[2, proc()] = [f, g] # Error
```

I'd like to specify the array type of `b`, but am unable to. It fails with:

```
x.nim(8, 27) Error: type mismatch: got (Array constructor[0..1, proc (){.locks: <unknown>.}]) but expected 'array[0..1, proc (){.closure.}]'
```

### PR DESCRIPTION
**Pull request by bung87**
… mismatch

apply to seq as well, no idea how to handle tuple, kinda mess.

fix #2614

related:  
https://github.com/nim-lang/Nim/issues/12511

### CODE REVIEW

**Comment by Araq** [comment]
Too arbitrary.

**Comment by Varriount** [comment]
@Araq So should this be closed?

**Comment by Araq** [comment]
It should be made to work for tuples and objects too.

**Comment by bung87** [comment]
> It should be made to work for tuples and objects too.

It requires iterate fleds, and point out one field mismatch other. maybe change the default behavior (omit proc callconv when is `nimcall`) is simple.  so it wil solve user common mistake.

**Comment by Araq** [comment]
Fair enough.

**Pull request merged**
