### PR TITLE
allow destructors to accept non var parameters; deprecate `proc =destroy(x: var T)`

### PR DESCRIPTION
**Pull request by ringabout**
supersades https://github.com/nim-lang/Nim/pull/22108

### CODE REVIEW

**Comment by Araq** [comment]
But now the builtin types need to make use of this too. :-)

**Comment by ringabout** [comment]
I think non-container types can make use of this because the prototype needs to be decided in advance. We cannot know a field in a tuple has a var or non-var destructor in `symPrototype`.

**Comment by Araq** [comment]
> I think non-container types can make use of this because the prototype needs to be decided in advance. We cannot know a field in a tuple has a var or non-var destructor in symPrototype.

I think we can know this but even if not, the version where the destructor uses `var T` should be considered deprecated.

**Comment by ringabout** [comment]
Deprecating destructors taking a `var T` parameter seems to be a good option.

**Comment by Araq** [comment]
Any progress on this shall be made in a following PR.

**Pull request merged**
