### PR TITLE
hotfix: buffer handling for makeUnixAddr [backport:1.0]

### PR DESCRIPTION
**Pull request by Araq**
Note that my networking knowledge is only a little above 0, so this needs to be carefully reviewed. Ping @dom96, @FedericoCeratto

### CODE REVIEW

**Comment by dom96** [comment]
Did you test it? Is there code that fails that this fixes?

**Comment by Araq** [comment]
I have no test case.

**Comment by dom96** [comment]
Then what's the bug that you are fixing? How was it described? :)

**Comment by Araq** [comment]
Well maybe somebody out there knows if the buffer handling had an off-by-one bug...

**Comment by Araq** [comment]
Wrong patch.

**Pull request closed without merging**
