### PR TITLE
Install uncaught exception handler in cpp (#6512)

### PR DESCRIPTION
**Pull request by RedBeard0531**
I tried to match the behavior of the c codegen. Let me know if there is a better place to put this code.

### CODE REVIEW

**Comment by Araq** [comment]
This requires a test case.

**Comment by RedBeard0531** [comment]
@Araq is there a good example test of fatal behavior I can base it on? Also, how do I mark the test as c++ only?

**Comment by dom96** [comment]
You can probably base it on this: https://github.com/nim-lang/Nim/blob/devel/tests/exception/tunhandledexc.nim

And these C++ tests show how to target the ``cpp`` backend https://github.com/nim-lang/Nim/tree/devel/tests/cpp :)

**Comment by RedBeard0531** [comment]
@Araq test added

**Comment by dom96** [comment]
Tests fail. Also, this doesn't work on assertion failures (I tested it).

**Comment by Araq** [comment]
Merged manually.

**Pull request closed without merging**
