### PR TITLE
rm zero-extension and uint conversions deprecated since 0.19.9

### PR DESCRIPTION
**Pull request by tersec**
https://github.com/nim-lang/Nim/releases/tag/v0.20.0 was in 2019, several releases and a 1.0 version ago.

### CODE REVIEW

**Comment by metagn** [comment]
This was tied to `nimPreviewSlimSystem` for this reason as in [changelog](https://github.com/nim-lang/Nim/blob/devel/changelogs/changelog_2_0_0.md) which would also have to be updated

[PR to update sdl1](https://github.com/nim-lang/sdl1/pull/4) is now merged, so CI should be fine on restart

**Comment by tersec** [comment]
> This was tied to `nimPreviewSlimSystem` for this reason as in [changelog](https://github.com/nim-lang/Nim/blob/devel/changelogs/changelog_2_0_0.md) which would also have to be updated
> 
> [PR to update sdl1](https://github.com/nim-lang/sdl1/pull/4) is now merged, so CI should be fine on restart

CI is, indeed, fine now.

That changelog appears to be specifically for 2.0, which would be nice, but would depend on whether this would go into `version-2-0` and/or `devel`. And, as you note,
> Legacy unsigned conversion operations: ze, ze64, toU8, toU16, toU32

is already listed. So should this PR be closed, or?

I had viewed the already extant deprecation as longstanding enough, and hadn't particularly considered whether a no, this time for real, deprecation would be worthwhile, but there's evidently already an ongoing plan for these.

**Comment by metagn** [comment]
It's fine if we remove it now too given it's pre-1.0. It was a snap decision in #20355 since it broke packages, maybe some packages updated since. It would just be a little asymmetric with the other delayed deprecations.

**Comment by Araq** [comment]
> It would just be a little asymmetric with the other delayed deprecations.

We also use empiricism. While it was deprecated a long time ago, it was still used. On the other hand, it's good enough for 2.0.

**Pull request merged**
