### PR TITLE
Always use httpclient in nimgrab

### PR DESCRIPTION
**Pull request by ghost**
Previously, nimgrab used the [URLDownloadToFile function](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/ms775123(v=vs.85)) which seems to be quite old and, on another note, antiviruses seem to be really suspicious towards any applications using this API.

Also changed imports to use `std` and removed an unneeded `asyncdispatch` import as nimgrab always uses synchronous HttpClient.

### CODE REVIEW

**Comment by juancarlospaco** [comment]
What is actively using this?, is it the Windows installation process ?. 🤔

**Comment by ghost** [comment]
> What is actively using this?, is it the Windows installation process ?. 🤔

Yes, it's used for downloading mingw. The discussion was in #internals on Discord

**Comment by Araq** [comment]
Who can test the resulting `finish.exe` on Windows?

**Comment by ringabout** [comment]
> Who can test the resulting finish.exe on Windows?

Tested on Win 11:

image


I changed the code to show the new nimgarb is actually used:

image

**Review by ringabout — APPROVED** [review]

**Comment by ringabout** [comment]
@narimiran can this PR be backported to 1.6.x? This PR seems to be harmless and helps newcomers on windows.

1.6.6

image


devel

image

**Comment by narimiran** [comment]
> @narimiran can this PR be backported to 1.6.x? 

Sorry, I have missed this.

Should I backport it now?

**Comment by ringabout** [comment]
Yes, please, thanks!

**Pull request merged**
