### PR TITLE
stateless code for substituelog function

### PR DESCRIPTION
**Pull request by lightness1024**
it was just so ugly to see this way of coding my eyes couldn't stand it.
also, logging doesn't support $time etc. substitution in normal log messages. it's only supported in the format header. So by exposing the expandLogVar function, now we can explicitely enable support for them in any string. Most importantly: the filenames for the log. those variables are useful to name the files.

### CODE REVIEW

**Comment by Araq** [comment]
Your code is much uglier IMO. Beauty aspects aside, I bet it's also vastly slower.

**Comment by dom96** [comment]
> Your code is much uglier IMO

I couldn't disagree more. You are probably right about speed though.

**Comment by dom96** [comment]
Unfortunately this PR breaks the JS target: https://travis-ci.org/nim-lang/Nim/jobs/363503980#L3240

**Comment by dom96** [comment]
Speed, and beauty aside. This version is more maintainable.

**Comment by hlaaftana** [comment]
It also behaves differently, for example `log nil, "abcdef$unknowntag", nil` would output `nilabcdef` in the original, and `abcdef$unknowntag` in this PR. Then again that's fixable in the original, like

```nim
case v
...
else:
  result.add('&')
  result.add(v)
```

Something unfixable in this version is that the replacements load unlazily and every time. Unless there was a macro for multiReplace that took a `varargs[(string, typed)]` instead, which would need adding of new unnecessary ugly code.

**Comment by Araq** [comment]
> Something unfixable in this version is that the replacements load unlazily and every time

Yup, that too.

**Pull request closed without merging**
