### PR TITLE
Doc fix: startProcess() raises OSError not EOS (plus tiny English improvement)

### PR DESCRIPTION
**Pull request by mark-summerfield**
…mprovement)

### CODE REVIEW

**Comment by Araq** [comment]
Don't merge into master. Use devel instead.

**Comment by mark-summerfield** [comment]
Sorry, but I don't know how to do that!

**Comment by Araq** [comment]
Well you did it correctly for all the PRs that I merged. When you create a branch, branch from 'devel', not from 'master'.

**Comment by mark-summerfield** [comment]
That was just luck. But I now see on this page https://github.com/nim-lang/Nim that there's a combobox for choosing the branch. For some reason it must have been master this time; I'll try to remember to set it to devel in future.

**Pull request closed without merging**
