### PR TITLE
add custom literals for `times.Duration`

### PR DESCRIPTION
**Pull request by derekdai**
To ease usage of `times.Duration`, add some custom literal for it.

### CODE REVIEW

**Comment by Araq** [comment]
This is great but needs to be put inside a `when nimHasCustomLiterals: include custom_literals` block. And the literals need to be in an include file.

**Comment by konsumlamm** [comment]
Note that the SI symbol for seconds is s, not sec. Using sec is arguably clearer though.

**Comment by derekdai** [comment]
> This is great but needs to be put inside a when nimHasCustomLiterals: include custom_literals block. And the literals need to be in an include file.

Good suggestion, I was just thinking about why CI failed~

> Note that the SI symbol for seconds is s, not sec. Using sec is arguably clearer though.

Got it.

**Comment by timotheecour** [comment]
related discussion: https://github.com/nim-lang/RFCs/issues/383

**Comment by juancarlospaco** [comment]
Would be better to use plural names ?, like `'days`, etc. 🤔

**Comment by timotheecour** [comment]
No, would lead to confusion (see std/times)

**Comment by juancarlospaco** [comment]
True, I am wrong.

**Comment by Varriount** [comment]
I'm not sure this is a good idea. `minute`, `second`, etc. procedures for ~~`int -> TimeDuration`~~ `int -> TimeInterval` already exist. Having custom literal procedures that return `Duration` instead is very confusing and unexpected.

Unless the old ~~`TimeDuration`~~ `TimeInterval`-returning procedures are being deprecated, the custom literal procedures should have the same behavior as their regular procedure counterparts.

**Comment by Araq** [comment]
The times module does not have a `TimeDuration` type and I find no procs for doing `int -> Time` either. What are you talking about?

**Comment by Varriount** [comment]
Sorry, not `TimeDuration`, rather `TimeInterval`.
For example, https://nim-lang.org/docs/times.html#seconds%2Cint

**Comment by Araq** [comment]
Ah yeah, good point.

**Comment by Varriount** [comment]
@timotheecour Why would creating both plural and singular forms be bad?

**Comment by metagn** [comment]
IMO, if you are going to use long names, just use `.days`. `'d` is faster to write and does not take up the name `d` in the scope. If there are cases where it can be ambiguous, like `'m` (can mean minute, month; and meter in other libraries), you can make it just a little longer like `'min` and `'mo`. This also reflects real world usage.

**Comment by Varriount** [comment]
> IMO, if you are going to use long names, just use `.days`. `'d` is faster to write and does not take up the name `d` in the scope. If there are cases where it can be ambiguous, like `'m` (can mean minute, month; and meter in other libraries), you can make it just a little longer like `'min` and `'mo`. This also reflects real world usage.

The problem I have with this is that "m", "d", etc. aren't common abbreviations/symbols, unlike "us", "ms", etc.  
Yes, these lesser known abbreviations/symbols are in use, but it's not going to be understandable to the average reader in the way the more common abbreviations/symbols are. The decision of what symbols to use was based on the [SI symbols](https://en.m.wikipedia.org/wiki/International_System_of_Units) - where there's an SI symbol, use it, otherwise use the full word.

**Comment by metagn** [comment]
`d`, `h` and `min` are [recommended in the SI](https://en.m.wikipedia.org/wiki/Non-SI_units_mentioned_in_the_SI) despite not being part of it. `y`/`yr`, `mo`, `w` are also common, but not official.

However I found out `'abc` is completely case insensitive as the first char to check for case sensitivity is `'`, so `w` and `h` would conflict with SI symbols, not that many people would use custom literals for watts and henrys

**Comment by Varriount** [comment]
Huh, I missed that. Nevertheless, I would prefer to err on the side of readability. Shorter abbreviations for less-common units can always be added later, but can't be readily deprecated if they clash with something else.

**Comment by Araq** [comment]
> However I found out 'abc is completely case insensitive as the first char to check for case sensitivity is ...

That's a bug we might want to fix. :-)

**Pull request closed without merging**
