### PR TITLE
fix #14339

### LINKED ISSUE #14339: nimvm: CritBitTree does not work: "limited VM support for 'addr'"
The CritBitTree type does not work at compile time.

### Example
```nim
import critbits
static:
  var strings: CritBitTree[int]
  discard strings.containsOrIncl("foo", 1)
  echo strings["foo"]
```

### Current Output
```
stack trace: (most recent call last)
C:\prog\dali\q_ct01.nim(5, 15) q_ct01
C:\Users\Mateusz\.choosenim\toolchains\nim-1.2.0\lib\pure\collections\critbits.nim(196, 3) []
C:\Users\Mateusz\.choosenim\toolchains\nim-1.2.0\lib\pure\collections\critbits.nim(196, 3) Error: limited VM support for 'addr'
```

### Expected Output
```
1
```

### Additional Information

* I am [using CritBitTree][dali] in my project [dali][], which allows emitting Android .dex files from Nim. I would like to be able to emit .dex files at compile time, when writing Android apps in Nim. Currently, I have to instead:
  - generate strings with Nim code and emit them to a helper file,
  - [compile and run this auxillary file separately](https://github.com/akavel/hellomello/blob/531e869dd7c04ba6622a23a56c70dada6b0cd49d/hellomello.nimble#L24-L25) to generate the final .dex file.

[dali]: https://github.com/akavel/dali/blob/911fea3b41ca4f9bc8eb2013f7456dff38a65af0/src/dali/dex.nim#L60

*Nim version:*
```
C:\prog\dali>nim -v
Nim Compiler Version 1.2.0 [Windows: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 7e83adff84be5d0c401a213eccb61e321a3fb1ff
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by ringabout**
ref: https://github.com/nim-lang/Nim/issues/14339

### CODE REVIEW

**Comment by Varriount** [comment]
- Why does this work?
- Wouldn't a better solution be to change the implementation, or extend the VM? I don't think introducing functionality in the standard library that's solely meant to work around compiler issues is a good idea. One the issue is fixed (hopefully) the functionality becomes pointless.

**Comment by ringabout** [comment]
The `get` in `CritBitTree` returns `var T` which somehow can't be used in VM.
So there are three solutions: 
1. Make a version of `get` which doesn't use `var T` as return type.
2. Extend VM which is hard for me :)
3. Make `get` return `T` which is a break change, namely change to `proc []*[T](c: var CritBitTree[T], key: string): T {.inline.}`.

```nim
proc `[]`*[T](c: var CritBitTree[T], key: string): var T 
```
I will try to find the reason which cause this problem.

**Comment by xflywind** [comment]
It seems that using templates has caused this problem. I move templates to `staticGet` and use `var T`.
Maybe change templates to inline function?
```nim
proc staticGet*[T](c: CritBitTree[T], key: string): var T {.inline.} =
  let n = rawGet(c, key)
  if n == nil:
    when compiles($key):
      raise newException(KeyError, "key not found: " & $key)
    else:
      raise newException(KeyError, "key not found")
  result = n.val
```

**Comment by ringabout** [comment]
It seems to be related to generics templates. Moving codes in templates to `[]` proc seems to work. I don't know how to deal with it.

```nim
# template get[T](c: CritBitTree[T], key: string): T =
#   let n = rawGet(c, key)
#   if n == nil:
#     when compiles($key):
#       raise newException(KeyError, "key not found: " & $key)
#     else:
#       raise newException(KeyError, "key not found")
#   n.val

proc `[]`*[T](c: var CritBitTree[T], key: string): var T {.inline.} =
  # get(c, key)
  let n = rawGet(c, key)
  if n == nil:
    when compiles($key):
      raise newException(KeyError, "key not found: " & $key)
    else:
      raise newException(KeyError, "key not found")
  result = n.val
```

**Comment by timotheecour** [comment]
> It seems to be related to generics templates.

no, see https://github.com/nim-lang/Nim/issues/14339#issuecomment-728275784

(always minimize examples to maximum extent before jumping to conclusions / bugfixes ;-) )

**Comment by timotheecour** [comment]
superseded by https://github.com/nim-lang/Nim/pull/16002 (which makes VM support this)

**Pull request closed without merging**
