### PR TITLE
[WIP] New threadpool

### PR DESCRIPTION
**Pull request by yglukhov**

### CODE REVIEW

**Comment by narimiran** [comment]
Hey @yglukhov, any news on this one? Is it still WIP or have you abandoned it?

**Comment by yglukhov** [comment]
There were some complications to support `parallel` statement, because it relies on threadpool. Iirc @Araq was going to look into it, but I no longer remember the details, and there seems to be little interest overall. So I dunno what should we do with it. @Araq?

**Comment by Araq** [comment]
I still want it, the old threadpool is far too complex.

**Comment by Araq** [comment]
Well it's available as a Nimble package too.

**Pull request closed without merging**
