### PR TITLE
Fix for async ssl

### PR DESCRIPTION
**Pull request by leemorgan-mobile**
ie at call site....
```
    let client = await server.accept()
    await sslContext.wrapAcceptedSocket(client)
```
the problem is that accept is not itself async so this can't be done in accept without bigger changes (AFAIK!)

### CODE REVIEW

**Comment by leemorgan-mobile** [comment]
I notice that python makes you explicitly wrapSocket so perhaps its not so bad

**Comment by dom96** [comment]
Needs to be consistent with ``net`` so I can't accept this, sorry. But thank you for giving it a shot.

**Comment by leemorgan-mobile** [comment]
no worries - I look forward to async working with ssl ;-)

**Comment by Araq** [comment]
@dom96 So close it if it's not good enough.

**Comment by lcm337** [comment]
Shall I create a new issue for this instead?

**Comment by dom96** [comment]
Yes please

**Comment by leemorgan-mobile** [comment]
https://github.com/nim-lang/Nim/issues/3778

**Pull request closed without merging**
