### PR TITLE
implements overloadable enum values; WIP

### PR DESCRIPTION
**Pull request by Araq**
My results of the developer meeting. Feel free to take over.

Todo:

- Testing in template/generics/macros contexts.

### CODE REVIEW

**Comment by Araq** [comment]
In a follow-up PR I'll document it.

**Comment by disruptek** [comment]
Who cares about documentation when the tests are still missing.  Does the feature even work?  Can you prove it?

**Comment by Araq** [comment]
Test is tests/enum/toverloadable_enums.nim and will be expanded.

**Comment by disruptek** [comment]
If you're not

> Testing in template/generics/macros contexts.

what language are you writing your tests for?

**Pull request merged**
