### PR TITLE
fix #3748 methods can't have same names as fields if UFCS is used

### LINKED ISSUE #3748: Confusing error message (methods can't have same names as fields if UFCS is used)
```
type
  Argument*[T] = ref object
    defaultValue: T

proc defaultValue(arg: Argument[bool], v: bool): Argument[bool] =
  discard

proc addArgument*(arg: int): Argument[bool] =
  let v = Argument[bool]()
  return v.defaultValue(false)

when isMainModule:
  let quix = addArgument(5)
```

produces

```
foo.nim(12, 11) Error: identifier expected, but found 'v.defaultValue'
```

It took me 20 minutes to figure out what's wrong (in a larger program)

### LINKED ISSUE #7523: Improvement of error message in case of ambiguous call
Condition:

```nim
type
  Foo = object
    bar: int

proc bar(cur: Foo, val: int) =
  discard cur.bar

proc does_fail(): Foo =
  result.bar(5)

can_fail()
```

This results in the following error message:
```
Error: in expression 'result.bar(5)': identifier expected, but found 'result.bar'
```

This error message needs some improvement, because it does not state, that the actual problem is, that there's an ambiguous call to `bar`. 
The compiler cannot know whether the member `bar` of `Foo` is wanted, or whether the function `bar` should be called with `result` (of type `Foo`) as first argument.

### PR DESCRIPTION
**Pull request by bung87**
fix #3748

fix #7523

### CODE REVIEW

**Comment by Araq** [comment]
Code similar to this has been compiled successfully thousands of times without this additional logic. We need to understand why that is and then fix it. Don't just add code to random places to make things compile, there is an existing structure in the compiler.

**Comment by juancarlospaco** [comment]
Maybe it can be fixed via documentation, with examples and how to do it properly...

**Comment by bung87** [comment]
if you mean fix the previous dont match proc call problem , it because it first `pickBest(f)` , where `f` is `n[0]` in this case `result.bar`, 
the code exits for years, so am worry about touch it.  and I thought it pick property first by design. when I first face this conflict problem, I just rename the proc, so problem gone. I think other users do this as well. as u see these two issues labeled as error message, so I tried improve the error message in previous PR.

**Comment by bung87** [comment]
no idea so far, give up.

**Pull request closed without merging**
