### PR TITLE
cleaned up the internal documentation

### PR DESCRIPTION
**Pull request by Araq**

### CODE REVIEW

**Comment by timotheecour** [comment]
@araq this PR causes dead-links referring to `rebuilding the compiler` and removed references to `pathto/nim c --lib:lib -d:release -o:bin/nim_temp compiler/nim.nim` which is useful during development and apparently not well known, refs https://github.com/nim-lang/Nim/pull/14477#issuecomment-635119339

**Comment by ZoomRmc** [comment]
What's the reason for deleting a big chunk of useful info? Is it obsolete?
The removed "debugging-the-compiler" section is still mentioned in a couple of places, including a compilation error message:

https://github.com/nim-lang/Nim/blob/06232b7f2e230a46beea982f172087e9da51814a/compiler/msgs.nim#L408
https://github.com/nim-lang/Nim/blob/devel/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by timotheecour** [comment]
it's not obsolete; I had added `nim c [options] compiler/nim` because the alternatives (`./koch temp`, `./koch boot`) seem to suggest it's somehow hard to rebuild the compiler, and they're less flexible:
* `./koch boot` is slower (compiles 3 times, it's intended specifically for booting and checking it gives a fixed point in CI)
* `./koch temp` has magic options that may not be what user wants (eg building from bin/nim instead of explicitly giving the nim binary; or -d:leanCompiler that prevents using it to debug js codegen, or --stacktrace:on in case user wants -d:libbacktrace, etc)

I don't have anything against `./koch temp`, but it doesn't replace  `nim c [options] compiler/nim`, which apparently people aren't unaware of as a possibility

**Comment by Araq** [comment]
> @Araq this PR causes dead-links referring to rebuilding the compiler and removed references to pathto/nim c --lib:lib -d:release -o:bin/nim_temp compiler/nim.nim which is useful during development and apparently not well known, refs #14477 (comment)

So where is the source that targets "rebuilding the compiler"?

**Comment by timotheecour** [comment]
rg1 -i 'rebuilding the compiler'
```
.github/ISSUE_TEMPLATE/bug_report.md:24:6:see [rebuilding the compiler](https://nim-lang.github.io/Nim/intern.html#rebuilding-the-compiler).
doc/intern.rst:158:58:`./koch temp`:cmd: by explicit compilation command, see `Rebuilding the compiler`_.
readme.md:90:11:See also [rebuilding the compiler](doc/intern.rst#rebuilding-the-compiler).
```
(and `doc/intern.rst:181:2:`Rebuilding the compiler`_ if you need more control.` from before that PR)

why can't we simply bring back (and update whatever needs to be updated) the section `Rebuilding the compiler` that was removed with this PR? people found it useful and `koch temp` doesn't replace it.

**Pull request merged**
