### PR TITLE
fix #8925 by using `getTypeInst` instead of `getType`

### LINKED ISSUE #8925: scanf Invalid node kind nnkBracketExpr for macros.`$`
Nim Compiler Version 0.18.1 [MacOSX: amd64]
Compiled at 2018-09-07
git hash: 91b37311d9974ae30745946a52c9a971da1616f4
``` 
lib/system.nim(2818, 7) Error: unhandled exception: /Users/bung/Nim/lib/core/macros.nim(1109, 17) `false` Invalid node kind nnkBracketExpr for macros.`$`
```
``` nim
import times
import strscans
var 
    hour:HourRange
    minute:MinuteRange
    time_str:string

if scanf(time_str, "$i:$i", hour,minute):
    discard

```

### PR DESCRIPTION
**Pull request by Vindaar**
The error in #8925 is a result from `getType `being used on a non base type. Using `getTypeInst` we get the named type instead, which should be more helpful as an error message (and won't let us crash in `macros.nim`).

Of course in this case e.g. `HourRange` can actually be converted using `parseInt`, but allowing `ntyRange` in https://github.com/nim-lang/Nim/blob/54d22d7cdc53c8b700d717c5924e0c588d56748e/lib/pure/strscans.nim#L359 seems wrong, if we don't check the base type of the range. At least in principle it doesn't have to contain `SomeInteger`, yes?

Does this warrant a test case?

### CODE REVIEW

**Comment by Araq** [comment]
> Does this warrant a test case?

Oh you bet.

**Comment by Vindaar** [comment]
Hm, I'm having some trouble with the test case using `discard ... errormsg:`, due to `'$i'` in the expected line. For some reason that screws up testament. Either getting rid of `$` or the `'` before it, makes it work (except that then of course the error message doesn't match anymore). 
I'll get back to this in a few days.

**Comment by Vindaar** [comment]
Ok @Araq, I saw that you already fixed #8925 yourself. I still just added a test case here and in my opinion using `getTypeInst` provides the better error message for the user. 
E.g. in the test I added just using `getType.repr` will give `range[0, 23]` of course. But the user might be confused by that if not aware that `HourRange` is actually just an alias for that.

Still, if you wish to leave it as it is now on devel, I can remove that change and modify the test accordingly.

What I was struggling with before: so the `file` directive in the test file header needs to point to the module in which the error occurs? I thought it was just some hint for better parsing, but was greeted by `reFilesDiffer`.

**Comment by Araq** [comment]
> What I was struggling with before: so the file directive in the test file header needs to point to the module in which the error occurs? I thought it was just some hint for better parsing, but was greeted by reFilesDiffer.

Well, yes.

**Comment by Vindaar** [comment]
> I don't mind either way.

Cool, so feel free to merge, if it comes out green! :)

> > What I was struggling with before: so the file directive in the test file header needs to point to the module in which the error occurs? I thought it was just some hint for better parsing, but was greeted by reFilesDiffer.
> 
> Well, yes.

Haha thanks. In hindsight it makes a lot of sense of course.

**Pull request merged**
