### PR TITLE
changed "encodeUrl" in lib/pure/uri.nim.

### PR DESCRIPTION
**Pull request by LeafChage**
I failed to access API with OAuth.
I want to "%20".

### CODE REVIEW

**Comment by andreaferretti** [comment]
Seems to make sense according to this discussion https://stackoverflow.com/questions/1634271/url-encoding-the-space-character-or-20

**Comment by data-man** [comment]
PHP has [rawurlencode](http://php.net/manual/en/function.rawurlencode.php) and [rawurldecode](http://php.net/manual/en/function.rawurldecode.php) according to [rfc3986](http://www.faqs.org/rfcs/rfc3986).
> Note:
rawurldecode() does not decode plus symbols ('+') into spaces. urldecode() does.

Maybe we should also add similar functions.
Or to add ```raw``` parameter.

**Comment by LeafChage** [comment]
@data-man 
I see.  

encodeUrl(s: string, rawOn = false)
false => '+'
true => "%20"
like this?

**Comment by data-man** [comment]
Yes.
The Curl also does this: [escape.c](https://github.com/curl/curl/blob/master/lib/escape.c)
But using iconv: [tool_convert.c#L49](https://github.com/curl/curl/blob/master/src/tool_convert.c#L49)

**Comment by data-man** [comment]
And wget's code: [url.c#L240](https://github.com/mirror/wget/blob/master/src/url.c#L240)

**Comment by dom96** [comment]
Python also uses ``+`` by default (as described here: https://stackoverflow.com/a/1634314/492186). Gotta love these quirks.

For the best of both worlds this should indeed be customisable. But call the parameters ``plus`` (it should be ``true`` by default) instead of ``rawOn``.

**Comment by data-man** [comment]
@dom96 
> it should be true by default

Why?

**Comment by data-man** [comment]
I vote for ```false```

**Comment by dom96** [comment]
> Why?

Two reasons:

1. Consistent with Python
2. Doesn't break backwards compatibility

**Comment by Araq** [comment]
> Therefore, it is preferable to add two new procs, rather than add a new parameter.

I prefer a new parameter.

**Comment by data-man** [comment]
@Araq 
true or not true, that is the question. (Inspired by W. Shakespeare)

**Comment by Araq** [comment]
@data-man what @dom96 said.

**Comment by LeafChage** [comment]
How is this?

**Comment by data-man** [comment]
@LeafChage
I prefer
```nim
proc encodeUrl*(s: string, rawOn = false): string =
  ## Encodes a value to be HTTP safe: This means that characters in the set
  ## ``{'A'..'Z', 'a'..'z', '0'..'9', '_'}`` are carried over to the result,
  ## a space is converted to ``'%20'`` and every other character is encoded as
  ## ``'%xx'`` where ``xx`` denotes its hexadecimal value.
  result = newStringOfCap(s.len + s.len shr 2) # assume 12% non-alnum-chars
  if rawOn:
    for c in s:
      case c
      of 'a'..'z', 'A'..'Z', '0'..'9', '_', '-', '.', '~': add(result, c)
      else:
        add(result, '%')
        add(result, toHex(ord(c), 2))
  else:
    for c in s:
      case c
      of 'a'..'z', 'A'..'Z', '0'..'9', '_': add(result, c)
      of ' ': add(result, '+')
      else:
        add(result, '%')
        add(result, toHex(ord(c), 2))
```

**Comment by data-man** [comment]
And maybe to rename ```rawOn``` to ```asRaw```.

**Comment by dom96** [comment]
How did we end up here? I asked for ``usePlus`` and you're making completely unrelated changes.

**Comment by dom96** [comment]
Once again, revert back to the original. Then simply add a ``usePlus`` parameter, add an if that checks whether it's true and add ``+`` or ``%20`` when it's not.

**Comment by data-man** [comment]
Maybe asRFC3986?

**Comment by dom96** [comment]
If other characters need to be handled differently as well then please state what they are so we can decide what to do about them.

**Comment by LeafChage** [comment]
@data-man 

I guess so.
It is is easy to understand.

**Comment by LeafChage** [comment]
@dom96 
Should I add usePlus for changing only '+' to "%20"?

**Comment by LeafChage** [comment]
I add only usePlus for now.

**Comment by LeafChage** [comment]
Which is good?
```nim
proc encodeUrl*(s: string, usePlus = false): string =                                                                                                                                                                                                                                                                                                                                                                            
  result = newStringOfCap(s.len + s.len shr 2) # assume 12% non-alnum-chars                                                                                                                                                                                                                                                                                                                                                      
  for i in 0..s.len-1:                                                                                                                                                                                                                                                                                                                                                                                                           
    case s[i]                                                                                                                                                                                                                                                                                                                                                                                                                    
    of 'a'..'z', 'A'..'Z', '0'..'9', '_': add(result, s[i])                                                                                                                                                                                                                                                                                                                                                                      
    of ' ': add(result, if usePlus: "%20" else: "+")                                                                                                                                                                                                                                                                                                                                                                             
    else:                                                                                                                                                                                                                                                                                                                                                                                                                        
      add(result, '%')                                                                                                                                                                                                                                                                                                                                                                                                           
      add(result, toHex(ord(s[i]), 2))     
```
or 
```
proc encodeUrl*(s: string, usePlus = false): string =                                                                                                                                                                                                                                                                                                                                                                            
  result = newStringOfCap(s.len + s.len shr 2) # assume 12% non-alnum-chars                                                                                                                                                                                                                                                                                                                                                      
  for i in 0..s.len-1:                                                                                                                                                                                                                                                                                                                                                                                                           
    case s[i]                                                                                                                                                                                                                                                                                                                                                                                                                    
    of 'a'..'z', 'A'..'Z', '0'..'9', '_': add(result, s[i])                                                                                                                                                                                                                                                                                                                                                                      
    of ' ':
        if usePlus:
            add(result, "%20")
        else:
            add(result, '+')  
    else:                                                                                                                                                                                                                                                                                                                                                                                                                        
      add(result, '%')                                                                                                                                                                                                                                                                                                                                                                                                           
      add(result, toHex(ord(s[i]), 2))     
```

I like the former.

**Comment by data-man** [comment]
Well, the benchmarks: :)

GlobalBenchmark              |      |                        263.80ps  |  3.79G
------|------|-----|-|
bench.nim                               |        relative | time/iter |  iters/s |
encodeUrlWithTrue                           |            |   135.66ns |   7.37M |
encodeUrlFormerWithTrue                       |    91.09%  | 148.92ns   | 6.71M |
encodeUrlWithFalse                         |             |   114.58ns   | 8.73M |
encodeUrlFormerWithFalse                       |   77.63%  | 147.59ns |   6.78M |

**Comment by LeafChage** [comment]
Thank you:)
Well...... 
Is it better than encodeUrlWith?
```
proc encodeUrl*(s: string, usePlus = false): string =                                                                                                                                                                                                                                                                                                                                                                            
  result = newStringOfCap(s.len + s.len shr 2) # assume 12% non-alnum-chars                                                                                                                                                                                                                                                                                                                                                      
  for i in 0..s.len-1:                                                                                                                                                                                                                                                                                                                                                                                                           
    case s[i]                                                                                                                                                                                                                                                                                                                                                                                                                    
    of 'a'..'z', 'A'..'Z', '0'..'9', '_': add(result, s[i])                                                                                                                                                                                                                                                                                                                                                                      
    of ' ': add(result, if usePlus: "%20" else: "+")                                                                                                                                                                                                                                                                                                                                                                             
    else:                                                                                                                                                                                                                                                                                                                                                                                                                        
      add(result, '%')                                                                                                                                                                                                                                                                                                                                                                                                           
      add(result, toHex(ord(s[i]), 2)) 
```

**Comment by data-man** [comment]
I compare with https://github.com/nim-lang/Nim/pull/7700#issuecomment-385237160

**Comment by LeafChage** [comment]
I edited #7700 (comment)
Do you compare A to B?

**Comment by LeafChage** [comment]
@data-man 
OK! Thank you.
I rewrite code more speedy and easy to understand.
I refer to #issuecomment-385242771

**Comment by data-man** [comment]
Also, I continue to prefer on compliance with RFC3986.
You can compare our implementation with https://www.url-encode-decode.com, e.g.

Results with dots differ!

>The unreserved characters can be encoded, but should not be encoded. The unreserved characters are:
A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
a b c d e f g h i j k l m n o p q r s t u v w x y z
0 1 2 3 4 5 6 7 8 9 - _ . ~

> The reserved characters have to be encoded only under certain circumstances. The reserved characters are:
! * ' ( ) ; : @ & = + $ , / ? % # [ ]

**Comment by LeafChage** [comment]
@data-man 
> But why you left if usePlus: in the loop?
Exactly, I think too that my code is not good.

**Comment by LeafChage** [comment]
@data-man 
> Also, I continue to prefer on compliance with RFC3986.
I prefer too.
But, Can I continue it in this pull request?

**Comment by LeafChage** [comment]
How is this?

**Comment by dom96** [comment]
I did some reading on this. Here is how I think this should work:

* ``usePlus`` parameter should determine how `` `` (Space) is encoded.
  * ``true`` - encode as ``+`` (default).
  * ``false`` - encode as ``%20``.
* Comply with RFC3986 regardless of the ``usePlus`` value.

So this PR is almost ready.

**Comment by LeafChage** [comment]
@dom96 
Ok, I will try it.

**Comment by LeafChage** [comment]
I referred to [escape.c](https://github.com/curl/curl/blob/master/lib/escape.c).

**Comment by dom96** [comment]
I ended up merging this manually and making some other changes too.

**Pull request closed without merging**
