### PR TITLE
remove find optimization [backport: 1.6]

### LINKED ISSUE #19500: `strutils.find` uses cstring optimization that stops after \0
### Example
```nim
import strutils

echo "abc \0 def".find("def")
```

### Current Output
```
-1
```

### Expected Output
```
6
```

### Possible Solution

* Remove [this cstring optimization in strutils.find](https://github.com/nim-lang/Nim/blob/6b302bb71b6d9aab708b91f8d68957652ec30480/lib/pure/strutils.nim#L1875-L1880) and maybe move it as an overload to `cstrutils`.

### Additional Information

* From forum thread https://forum.nim-lang.org/t/8874

```
$ nim -v
Nim Compiler Version 1.6.2
```

### PR DESCRIPTION
**Pull request by ringabout**
close #19500

### CODE REVIEW

**Comment by Araq** [comment]
The optimization is nice though and maybe it can be saved somehow.

**Comment by RSDuck** [comment]
wouldn't it be better in long term to have our own SIMD optimisations?

**Comment by Araq** [comment]
Sure but it's quite some effort to write this portably. There is also [memmem](https://man7.org/linux/man-pages/man3/memmem.3.html)

**Comment by RSDuck** [comment]
this is getting a bit off topic, but do you have any idea where to start with that? It would probably be necessary to add atleast a basic wrapper for SSE/NEON intrinsics into the stdlib, right?

**Comment by Araq** [comment]
Take a look at https://gist.github.com/Araq/ea3ef89780dcbeb5730f4b058f016218

**Comment by metagn** [comment]
> The optimization is nice though and maybe it can be saved somehow.

Maybe add to cstrutils?

Edit: `memmem` seems fine to use here actually, `strstr` can be used in cstrutils

**Pull request closed without merging**
