### PR TITLE
fix #10632 `out of memory` during megatest compiling/linking

### LINKED ISSUE #10632: megatest linking fails on local travis because it consumes too much memory
As shown here: https://travis-ci.com/timotheecour/Nim/branches the last time megatest linking succeeded on my local appveyor was ~20 days ago around jan 20 2018

fix: see https://github.com/nim-lang/Nim/pull/10611

note: closing because of issue count limit but issue is valid

### PR DESCRIPTION
**Pull request by timotheecour**
* fix #10632 megatest linking fails on local travis because it consumes too much memory

This PR splits megatest in nSplits (=2 for now) chunks to avoid out of memory on CI.

before this PR, my own travis instance would always (since 18 days ago) end up erroring (with no helpful msg) during the megatest link phase, probably because it would run out of memory (maybe Nim's travis has more memory than my travis instance, i don't know; i don't have any special config).

After this PR, it finally is green for the 1st time in 18 days on my own travis instance, see [1]

[1]
image

### CODE REVIEW

**Comment by krux02** [comment]
Can you please analyze the problem a bit more, before you "fix" it? How much memory does it consume before this patch? How much does it consume after this patch? Are the single tests in the megatest that have a very significant impact on memory usage? Would it be wiser to just disable the joining for these few tests. Why don't you just give your local travis more memory?

**Comment by timotheecour** [comment]
> How much memory does it consume before this patch
> How much does it consume after this patch?

on my machine (OSX):
```
# tests 0 - 468
gtime -v nim c -f -d:testing --listCmd megatest.nim
Maximum resident set size (kbytes): 608032

# tests 0 - 468/2
gtime -v nim c -f -d:testing --listCmd megatest.nim
Maximum resident set size (kbytes): 470364

# tests 468/2 - # tests 0 - 468
Maximum resident set size (kbytes): 229196
```

note: gtime via brew: /Users/timothee/homebrew//bin/gtime

> Are the single tests in the megatest that have a very significant impact on memory usage?

it's hard to go that route for many reasons; eg run in parallel (`execCmdsInParallel`) and memory usage is not deterministic.
I reproduced the same issue outside of travis (to make sure it's not related to travis) on my own VM (ubuntu 16.04) running on low memory (eg 1GB). See stacktrace below [1] showing indeed it's a "Cannot allocate memory" error.
I did binary search to find the max number of tests that passes without running out of memory; from that point, adding or removing an individual test does not deterministically increase / decrease Maximum resident set size, nor does it deterministically make the the overall compilation pass/fail. 
Furthermore, memory usage of running tests in conjunction is not linear (ie not sum of mem usage of individual tests)

> Would it be wiser to just disable the joining for these few tests

I don't see how; first you'd have to identify which tests these are (see note above), and 2nd, you'd end up with (1+numRemoved) compilations instead of 2 as I'm doing in this PR, so it may even be slower.

> Why don't you just give your local travis more memory?

I don't see how, see https://docs.travis-ci.com/user/reference/overview/ ; please let me know if you find out how.

Here's the typical example I'm seeing each time: https://travis-ci.com/timotheecour/Nim/builds/99710085 shows OSX passes but linux fails with these logs: https://travis-ci.com/timotheecour/Nim/jobs/175272154
```
gcc -c  -w  ...
megatest compilation failed
```

@krux02 I'm not seeing an account at https://travis-ci.com/krux02 ; please try and see whether you can reproduce the above issue.

[1]
```
Error: invocation of external compiler program failed. Cannot allocate memory 12
Traceback (most recent call last)
/home/parallels/git_clone/Nim/compiler/nim.nim(109) nim
/home/parallels/git_clone/Nim/compiler/nim.nim(73) handleCmdLine
/home/parallels/git_clone/Nim/compiler/cmdlinehelper.nim(92) loadConfigsAndRunMainCommand
/home/parallels/git_clone/Nim/compiler/main.nim(174) mainCommand
/home/parallels/git_clone/Nim/compiler/main.nim(84) commandCompileToC
/home/parallels/git_clone/Nim/compiler/extccomp.nim(818) callCCompiler
/home/parallels/git_clone/Nim/compiler/extccomp.nim(733) execCmdsInParallel
/home/parallels/git_clone/Nim/compiler/msgs.nim(427) rawMessage
/home/parallels/git_clone/Nim/compiler/msgs.nim(424) rawMessage
/home/parallels/git_clone/Nim/compiler/msgs.nim(345) handleError
/home/parallels/git_clone/Nim/compiler/msgs.nim(330) quit
```

**Comment by krux02** [comment]
Megatest is called megatest for a reason. Using more than 1 GB of memory during compilation is not an issue for this test. If your testing environment does not have more than one GB of memory, than you need to fix that. Ask travis for support.

**Comment by timotheecour** [comment]
> What exactly do you mean with "local travis", pleas elaborate. I don't use that service. A few words on how it works won't harm.

by local travis I mean using your own travis account (eg https://travis-ci.com/timotheecour/Nim/branches) to test PR's by running CI, instead of the shared one https://travis-ci.org/nim-lang/Nim/branches), so as to avoid wasting shared travis resources which results in long queuing times for everyone.

> It seems like you want the megatest to use less than 1 GB during compilation. Is that correct?

Not necessarily `< 1GB` but less memory than it currently uses so that your own travis instance doesn't fail.

**Comment by krux02** [comment]
I don't want this change. I like the test to be not splitted if possible. As I noted, this seems to fix the problem at the wrong end, you should fix your "local" (personal) travis instance instead of fixing something that isn't broken.

**Pull request closed without merging**
