### PR TITLE
store full definition AST for consts, fix noRewrite

### LINKED ISSUE #9331: deprecation syntax inconsistent for objects, not possible for const/let/var
* {.deprecated: "msg" .} works for routines/types but not for const/let/var:
```nim
block:
  # works
  const Foo {.deprecated.}  = 1

block:
  # Error: annotation to deprecated not supported here
  # const Foo {.deprecated: "bla".}  = 1
```

* deprecated for object type inconsistent all other deprecated forms:
for pretty much everything, `{.deprecated: "blabla".}` goes before the `=` but not for object type:
```nim
block:
  # object type: deprecated goes after `=`
  type Foo = object {.deprecated: "blabla".}
    a: int

block:
  # every thing else: deprecated goes before `=`: enum, routines, const/let/var
  type Foo {.deprecated: "asdf" .} = enum
    a
```

### LINKED ISSUE #19766: Nim doc doesn't keep the var / let pragmas
### Example
```nim
template tddd {.pragma.}
let hey* {.tddd.} = 5
```

### Current Output
image

### Expected Output
`hey {.tddd.} = 5`

### Additional Information

nim devel 83dabb69ae0f6c0bb269594a5b73af964b809bc7

### LINKED ISSUE #20114: Typed `const` AST deletes pragmas
Might be a duplicate. In any case, I know and have the fix for this, just opening to document.

### Example
```nim
import macros

expandMacros:
  # any pragma, not just strdefine
  const foo {.strdefine.} = "abc"
```

### Current Output
```
const
  foo = "abc"
```

### Expected Output
```
const
  foo {.strdefine.} = "abc"
```

### Possible Solution

I am about to PR the solution. [Bad line](https://github.com/nim-lang/Nim/blob/528b6d1c3f001944a7a7754c8884178e365e6871/compiler/semstmts.nim#L805)

```
$ nim -v
Nim Compiler Version 1.7.1
528b6d1c3f001944a7a7754c8884178e365e6871
```

### PR DESCRIPTION
**Pull request by metagn**
closes #9331, fixes #20114, fixes #19766

Stores full definition AST for consts (continuing #9582). Also moves extractPragma to ast for later convenience. Also had to fix `noRewrite` (#16620, probably not fully ready to close yet) and use it because storing `var` pragma AST somehow unlocked a broken term rewriting macro in a test. Genuinely no idea how, don't care to investigate.

Unsure about compile option like #9582 or something like `nimHasConstDefImpl`. Users should check for `nnkConstDef` anyway since sometimes it's still not `ConstDef`.

### CODE REVIEW

**Comment by Araq** [comment]
We should instead or in addtion to that refactor the compiler transformation pipelines.

**Comment by metagn** [comment]
Is there any way of checking if this is backportable? It would help to be able to see `{.strdefine.}` in docs for consts on stable versions, but I'm unsure if the patch is compatible.

**Comment by metagn** [comment]
I now believe this should be backported, there might be minor conflicts but I can help resolve them if needed.

**Comment by Araq** [comment]
While the PR itself is fine, this seems way too risky for a backport. What do you think?

**Comment by metagn** [comment]
I can just make another PR for the 1.6 branch, so I'll unmark as backport. 

As for the PR content, on second thought it is possible this will break code, so by principle it shouldn't be backported. But it can very well be considered a bugfix. 

So no backport probably.

**Comment by metagn** [comment]
Can someone point me to why CI is failing after the rebase but it wasn't a couple days ago? I'm guessing it has to do with https://github.com/nim-lang/Nim/commit/7739e23420c9a7a4ec7eccdddc0a39df9e905aa8 but I have no idea how the error messages relate to this PR specifically.

Edit: Never mind, I think I found it

**Comment by metagn** [comment]
At this point I don't think this can be backported as-is anyway. So I don't think there's anything left to do.

**Pull request merged**
