### PR TITLE
[WIP] Testament refactor

### PR DESCRIPTION
**Pull request by krux02**
this PR is work in progress. I try to simplify the tester. At the moment it is slightly uglier, and wrong. This PR is for me to see the full diff.

### CODE REVIEW

**Comment by krux02** [comment]
tests run trough locally.

**Comment by krux02** [comment]
I thought I disabled appveyor logging. Aparently whatever I disabled, it wasn't the AppVeyor logging.

**Comment by dom96** [comment]
Some feedback from me:

* It would be much easier to review this if you split the testament refactoring and the vast amount of test changes into separate PRs. I can understand if that's not possible though (if so, why does this need so many changes?)

* Please consider using more meaningful commit messages, "WIP" is noisy and uninformative.

* Any chance you could see the diff in your local git client? Getting constant notifications for a PR that you've submitted for yourself is a little annoying.

**Comment by Araq** [comment]
Took over and merged it.

**Pull request closed without merging**
