### PR TITLE
Allow TR, TH, TD tags inside THEAD and TFOOT

### PR DESCRIPTION
**Pull request by rgv151**

### CODE REVIEW

**Comment by dom96** [comment]
Could we have some tests for this?

**Comment by rgv151** [comment]
Please take a look on this snippet: https://gist.github.com/rgv151/fbb05d50e02b80ecd41b

**Comment by reactormonk** [comment]
@rgv151 I think @dom96 is talking about a file somewhere in tests/ we can automatically run.

**Comment by rgv151** [comment]
yep I think so, but I don't know how to make a test for this case yet.

**Pull request merged**
