### PR TITLE
make nil string behave like empty string

### PR DESCRIPTION
**Pull request by krux02**

### CODE REVIEW

**Comment by dom96** [comment]
Wow. This sure is a wide reaching change.

I'm pretty sure this will cause a lot of breakage.

**Comment by krux02** [comment]
Well yes it does, but it is a wanted change in the language as I discussed it often with Araq in the irc chat. (sorry again for no link, but you can ask if you have doubt). There is one thing that causes problems though, and that is the '\0' termination of strings. At the moment all strings have an extra byte for the '\0' terminator. And some code relies on the fact that when there is a string, there will always be an extra '\0' character at the end. The empty string breaks this. 

```Nim
var s: string  # is should now behave like an empty string
echo s[0]      # on an empty '\0' terminated string this should be '\0', 
               # but here it reads the nil pointer and crashes.
```

**Comment by krux02** [comment]
I don't have any knowledge about the javascript, nor the javascript backend, so I would need help for that part. Even better if someone would take that part over.

**Comment by Araq** [comment]
> Even better if someone would take that part over.

Only compiler frontend issues are affected, the JS backend knows about it already.

**Comment by kobi2187** [comment]
Is there an advantage to the \0 char? a string here is basically a seq of chars.
and there is a cstring type. Is that just a relic from c? it might be worth removing this. my 2c

**Comment by krux02** [comment]
wow, that was a tough one I guess.

**Pull request closed without merging**
