### PR TITLE
WebAPI for Nim [WIP]

### PR DESCRIPTION
**Pull request by lcrees**

### CODE REVIEW

**Comment by dom96** [comment]
I don't think these modules belong in the stdlib. What's the rationale here?

**Comment by lcrees** [comment]
- JavaScript is a first-class target for Nim, having its own backend as part of the main compiler.
- The _standard_ target for a JavaScript supporting _standard_ library, which presumably includes Nim, is the _standard_ [Web API](https://developer.mozilla.org/en-US/docs/Web/API) found in the browser. 
- It could be argued for purity's sake that Nim's stdlib for JavaScript should implement complete mapping for [every standard DOM interface](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts) to fully live up to the Nim stdlib *dom* module's claim to be a "declaration of the Document Object Model for the JavaScript backend". WebSockets have been a part of the Web API (or DOM if you're Microsoft and think DOM rhymes with Web API).
- Most of the _dom_ modules procs deal with HTML/XML manipulation and events like you'd expect a pure DOM mapping to do. However, it also includes the minimum JavaScript builtins (_ parseFloat_, _parseInt_, etc.) it shares with a standardized environment like the browser as well non-standard JavaScript environments like Node.js as well as non-HTML/XML procs from the Web API like _ requestAnimationFrame_ so its purity as a pure DOM module is already compromised. 
- Any implementation of most JavaScript Web API procs in Nim are only a proc mapping without a proc body and little more than an importcpp pragma. Adding them the the stdlib involves minimal size, minimal maintenence, and, if properly modularized, minimal updates in the future. 
- The heuristic for stdlib inclusion may only rise to the "I know a stdlib module when I see it" threshold, which is an tenuous threshold to meet. That a module should have more general applicability than converting roman numeral modules to integers and back seems a good minimum threshold. However, the Web API, being one of the largest development and, with an ecumenical definition of the word, standard targets in use, has a broader claim to broad and deep stdlib support than many modules whose presence in the stdlib is uncontroversial.

Including Araq's modules from karax strikes a nice balance between Microsoft's 14865 line mapping of the "DOM" used for another JavaScript transpiling language (TypeScript) and Nim's 1,107 lines of JavaScript support (if _jsconsole_, _jsffi_, and _dom_ are clumsily counted as the same thing). I'm more than happy to translate the 14,865 lines in to Nim modules if you wanted to reach all inclusiveness but I don't know if that's a goal for Nim's JavaScript support.

**Comment by Araq** [comment]
You make good arguments but ``jwebsockets`` is not even complete. (Btw ``languages.nim`` from karax needs to go into the stdlib :-) ) Add the missing things if you want it in the stdlib. Also the ``j`` prefix for JS based modules wouldn't be necessary if ``js`` were not in the --path making programmers write

```nim

import js / [strutils, dicts, websockets]
```

which seems to be more modern Nim. 

> I'm more than happy to translate the 14,865 lines in to Nim modules if you wanted to reach all inclusiveness but I don't know if that's a goal for Nim's JavaScript support.

That's a nice offer and I wouldn't mind more JS support but I think we can spend your valuable resources on more important things. :-)

**Comment by dom96** [comment]
Thank you for this thorough explanation.

I've gotten a bit conservative when it comes to the stdlib, in particular because we are in the run up to the magical 1.0 version. That said, you do make convincing arguments.

Although I would personally prefer a single wrapper module ala posix.nim which wraps all the Web APIs. I think some of the procs in the ``dom`` module that you mentioned could be moved into this ``webapi`` (or maybe there is a better name?) module. I suppose this module could also support Node, although there are many constructs that only Node supports (sockets and file operations for example) which would benefit from a dedicated module (but on the other hand, I don't think we should even support Node if not for the fact that it's useful for testing the JS backend). If you are interested in spearheading that then please do, I think it would be a good use of your time.

@Araq might have other ideas for you (it would be incredibly useful if he listed those ideas)

**Comment by dom96** [comment]
As for [``languages.nim``](https://github.com/pragmagic/karax/blob/master/karax/languages.nim), isn't that something that should be read from the OS instead of being hardcoded?

**Comment by Araq** [comment]
> As for languages.nim, isn't that something that should be read from the OS instead of being hardcoded?

No, these are the languages Nim knows about as a common denomitator for interop. Later we will add ``getLanguageFromOS`` with a JS specific implementation.

**Comment by lcrees** [comment]
As @dom96 suggests, I'm working on a _webapi_ module that follows the lead of the _posix_ module in that it's just a comprehensive platform wrapper and not mapping of Nim native idiom onto JavaScript native idiom. _jsffi_ does that already.

- All types will inherit from jsffi's _JsRoot_, _JsObject_, or _JsArray_ as needed.
- There will be a _jsglobal_ module containing the core [JavaScript globals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects). This would allow some limited compatibility in the stdlib with non-browser JavaScript environments like node.js or duktape without incorporating features specific to those environments like Node's Buffers, etc.

I'll make this PR the working marker for this for now and close the other PRs I opened.

**Pull request closed without merging**
