### PR TITLE
Fixed seq.insert and seq.delete for js.

### PR DESCRIPTION
**Pull request by yglukhov**

### CODE REVIEW

**Comment by yglukhov** [comment]
Thinking further, I'd probably use JS splice function to insert.

**Comment by yglukhov** [comment]
Ready to go.

**Comment by nanoant** [comment]
@yglukhov Do we really need 2 commits with same subject?

**Comment by Varriount** [comment]
@nanoant They don't have the same message?

**Comment by nanoant** [comment]
@yglukhov @Varriount Yeah they don't. Take my apologies for the noise. I am getting blind, need to buy :eyeglasses:

**Comment by Araq** [comment]
This needs to use 'when nimvm'.

**Comment by yglukhov** [comment]
Done.

**Comment by Araq** [comment]
Er ... sorry, I should have caught this way sooner, but how come the generic implementation doesn't work for the JS target? Shouldn't instead the JS codegen be fixed so that generic code dealing with seqs actually works?

**Comment by yglukhov** [comment]
Well, the main problem is that shallowCopy is fast assignment in JS. And it just copies references within the array. So after moving the elements, the Ith element will refer to (i+1)th. Last assignment by writing to Ith element effectively alters (i+1)th element. One simple solution would be to just assign null to Ith element so that nimCopy will create a new object. But anyway I think that JS's splice function would be a more robust implementation.

Please note, that the behavior wtill remains incorrect in regards to pointers, to members of seq elements. The correct solution I can think of, is doing full nimCopy on nkFastAsgn. But I suspect that would hit performance severely, so I'm really not sure what to do about it.

**Comment by Araq** [comment]
> *The correct solution I can think of, is doing full nimCopy on nkFastAsgn.*

No, but you need to check the involved types and do a "deeper" copy for objects but not for ref objects. Or something like that.

**Pull request merged**
