### PR TITLE
Compile pragma. Recompile on external file compilation failure

### PR DESCRIPTION
**Pull request by cooldome**
This PR makes sure that if OBJ file does not exist compile the external file once again. This happens when compilation has failed on the previous run and Nim does not try to compile external file anymore as it hasn't changed.

### CODE REVIEW

**Comment by krux02** [comment]
Is there a test that shows that your changes are correct? Otherwise I can approve this PR.

**Comment by cooldome** [comment]
It is difficult to test except of doing it manually once. You need to compile external file using {.compile: ",=myfile".} pragma block. While file should exist, its compilation should fail with some error. Next time when you are going to run nim you should see the same compilation error. Currently Nim will skip file compilation and fail on linkage step as obj file never existed in the first place.

**Comment by Araq** [comment]
At least it looks better than before.

**Comment by Araq** [comment]
At least it looks better than before.

**Comment by Araq** [comment]
At least it looks better than before.

**Pull request merged**
