### PR TITLE
Fixes #6853

### LINKED ISSUE #6853: Impossible to create an empty const array
The following line fails to compile:
  `const required_fields: array[0, tuple[f1: int, f2: string]] = []`

with Error
```
Error: type mismatch: got (array[0..-1, empty]) but expected 'array[0..-1, tuple[f1: string, f2: stri
ng]]'
```

Empty const arrays can be useful in macros for example

### PR DESCRIPTION
**Pull request by cooldome**
Fixes empty array don't compile problem. The logic to handle empty array was already present in `tyOpenArray` part of `typeRel`, just taken it from there.

### CODE REVIEW

**Comment by cheatfate** [comment]
@cooldome, just want to ask is it support something like:
```nim
  const emptyArray = []
```

**Comment by cooldome** [comment]
@cheatfate: 
`const emptyArray = []` does work, I have added it to my test.

For clear reason `let emptyArray = []` does not work, codeGen gives a nice error saying empty type can't be generated

**Comment by dom96** [comment]
Hrm, what's the reason for allowing ``const emptyArray = []``?

**Comment by cooldome** [comment]
Actually, I was wrong regarding ``const emptyArray = []``. My PR has no effect on it, it was allowed previously.
Discard my last comment. My PR only helps with case when `array[0..-1, EmptyType]` needs to be assigned to ``array[0..-1, SomeRealType]``.

**Pull request merged**
