### PR TITLE
Fix nimscript regression

### PR DESCRIPTION
**Pull request by nc-x**
Fixes https://github.com/nim-lang/Nim/issues/9965

### CODE REVIEW

**Comment by Araq** [comment]
This causes lib/pure/nimprof.nim to fail.

**Comment by Araq** [comment]
Too convoluted. Tables with one element in it? Come on.

**Comment by nc-x** [comment]
I did it because there may be other options incompatible with nimscript. So when they are found, it would be easy to just add it into the table without changing anything else.

I can remove the one element table if you want? @Araq

**Comment by Araq** [comment]
But don't worry, I'm taking over.

**Pull request closed without merging**
