### PR TITLE
Add error checking to newAsyncNativeSocket()

### PR DESCRIPTION
**Pull request by endragor**
And remove code duplication.

### CODE REVIEW

**Comment by dom96** [comment]
I still don't think ``newAsyncNativeSocket`` should raise exceptions.

See the discussion here: https://github.com/nim-lang/Nim/pull/4936.

**Comment by endragor** [comment]
1. I think newAsyncNativeSocket is not that low-level, every other asyncdispatch procedure can raise.
2. It can already raise from setBlocking() and setsockopt() (and this is how I discovered that the error checking is missing one step before).
3. There are 27 occurrences of `raiseOSError` in nativesockets.nim, which contradicts with the point that "close-to-the-system" API shouldn't raise.

**Comment by endragor** [comment]
Hm, and due to the point (2) we should also do `try..except` and close the socket if setBlocking/setsockopt raise. But then `checkCloseError` helper from #5300 is needed - could you please review it?

And, given the points above, do you still think it shouldn't raise? I think it'd be too easy for the user to forget to check the value returned by newAsyncNativeSocket, and any subsequent call would raise anyway - so why not raise early?

**Comment by dom96** [comment]
Now that I thought about it again I think that it should do the following:

* Return an ``InvalidSocket`` AsyncFD if the socket creation fails (just like ``newNativeSocket``).
* Raise an error if setBlocking/register fails.

The main reason is that I want to keep it consistent with ``newNativeSocket``.

**Comment by cheatfate** [comment]
I think both `newNativeSocket` and `newAsyncSocket` must returns `osInvalidSocket` on error, no exceptions must be raised.

`newNativeSocket` calls `socket` only. So application code which uses `newNativeSocket()` and got `osInvalidSocket` can obtain information about error via `osLastError()`.

`newAsyncNativeSocket` calls `socket` and `setsockopt`. Because `setsockopt` is called only after `socket`, so we can return `osInvalidSocket` too, and application will obtain most usefull information about error via `osLastError()`.

Also i think `newAsyncNativeSocket` must not call `register` automatically, as `acceptAddr` call must not register accepted socket automatically, because in different scenarios of multithreaded servers,  server must have ability to dispatch accepted/newly created socket to other thread and don't handle this socket in current thread dispatcher.

Automatic `register` operation can be made in `newAsyncSocket`.

**Comment by dom96** [comment]
> Also i think newAsyncNativeSocket must not call register automatically

Good point. I agree.

But please make sure to document this change in the news as it is a breaking change.

**Comment by endragor** [comment]
I, too, agree that newAsyncNativeSocket() shouldn't call register(), but I don't agree with the rest.

So this turned into a larger refactoring from what initially was a small and meaningful change given the existing behaviour (which is "newAsyncNativeSocket raises exception on socket creation error").

By the way, just making `newAsyncNativeSocket` not raise when socket creation fails is already a breaking change, because any code that did 
```nim
let sock = newAsyncNativeSocket()
```
will have to do
```nim
let sock = newAsyncNativeSocket()
if sock == osInvalidSocket:
  raise newException(OSError, osLastError())
```
I still don't understand why this burden has to be moved on the user and why `newAsyncNativeSocket` has to be the only proc from `asyncdispatch` that requires this, so I'll let you do the change.

**Comment by Araq** [comment]
``newNativeSocket`` is misnamed then, usually ``new*`` procs are not checked for success. Likewise ``newAsyncNativeSocket`` is either misnamed or should throw.

**Pull request closed without merging**
