### PR TITLE
fix #16736 assign closure proc to const should be CT error

### LINKED ISSUE #16736: `const` proc in `let` array causes invalid codegen
### Code
```nim
type ProcType = proc()
const something: ProcType = proc() = discard
let arr: array[1, ProcType] = [something]

```

### Current Output

```
/home/anuke/.cache/nim/bug_d/@mbug.nim.c: In function ‘NimMainModule’:
/home/anuke/.cache/nim/bug_d/@mbug.nim.c:413:99: error: request for member ‘ClE_0’ in something not a structure or union
  413 | lzADdspe4KtMwjNjbL8g[0].ClE_0), colonanonymous___DxAxlW4RjxKP1O7MGX2PnQ.ClE_0);
      |                                                                        ^

/home/anuke/.cache/nim/bug_d/@mbug.nim.c:414:80: error: request for member ‘ClP_0’ in something not a structure or union
  414 | tMwjNjbL8g[0].ClP_0 = colonanonymous___DxAxlW4RjxKP1O7MGX2PnQ.ClP_0;
      |                                                              ^

Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3   -I'/home/anuke/.choosenim/toolchains/nim-#devel/lib' -I/home/anuke -o /home/anuke/.cache/nim/bug_d/@mbug.nim.c.o /home/anuke/.cache/nim/bug_d/@mbug.nim.c' failed with exit code: 1

```

### Expected Output
```
successful compilation, or at least a nim compilation error
```

### Workarounds

- Declaring both the proc and the array as `const` fixes the problem.

### Additional Information

- Occurs in 1.4.2 as well as latest HEAD
- Occurs with and without `--gc:arc`

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-01-16
Copyright (c) 2006-2021 by Andreas Rumpf

44ceefa9fefca58ba32e9638f754d7f4ca8a2b82 (current git head)
```

### LINKED ISSUE #16737: `const` procs in `const` array are nil in half of array
### Code
```nim
type ProcType = proc()

const a: ProcType = proc() = discard
const arr: array[8, ProcType] = [a, a, a, a, a, a, a, a]

for i in 0..<arr.len:
  echo "[", i, "]: ", arr[i].isNil
echo "\nwith constant index:\n[7]: ", arr[7].isNil
```

### Current Output

```
[0]: false
[1]: false
[2]: false
[3]: false
[4]: true
[5]: true
[6]: true
[7]: true

with constant index:
[7]: false
```

### Expected Output
```
[0]: false
[1]: false
[2]: false
[3]: false
[4]: false
[5]: false
[6]: false
[7]: false

with constant index:
[7]: false
```

### Workarounds

- Declaring both the proc and the array as `var` fixes the problem in this test case. In my codebase, it leads to invalid codegen that I have been unable to isolate.

### Additional Information

- Occurs in 1.4.2 as well as latest HEAD
- Occurs with and without `--gc:arc`
- Likely related to #16736

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-01-16
Copyright (c) 2006-2021 by Andreas Rumpf

44ceefa9fefca58ba32e9638f754d7f4ca8a2b82 (current git head)
```

### PR DESCRIPTION
**Pull request by bung87**
fix #16736
fix https://github.com/nim-lang/Nim/issues/16737

### CODE REVIEW

**Comment by bung87** [comment]
CI fails cause by #14340 related test case  , if this PR accepted , should remove that test case.
``` nim
proc opl3EnvelopeCalcSin0() = discard
type EnvelopeSinfunc = proc()
# const EnvelopeCalcSin0 = opl3EnvelopeCalcSin0 # ok
const EnvelopeCalcSin0: EnvelopeSinfunc = opl3EnvelopeCalcSin0 # was bug
const envelopeSin = [EnvelopeCalcSin0]
var a = 0
envelopeSin[a]()
```

**Comment by top-master** [comment]
@bung87 You basically cause the error:
```
tvmmisc.nim(358, 11) Error: const 'EnvelopeCalcSin0' cannot be assigned to proc of calling convention 'closure'
```

And why do you think setting to a `const` should be forbidden?

Like:
* `const` just means that the internal state is not modifiable by outsiders,
* and that such attempts should cause compile-error,
* but as it is a closure, I doubt anything "outside" has even access, hence closure is truly const even without const-keyword use.

>**Update;** Above I am confusing `const` with `let` (to be expected, for someone with C/C++ experience).
>
>The **only** difference with `let` is that, Nim's `const` expressions are evaluated at compile-time, just like `constexpr` in C++.
>
>Nim-lang Example:
>```
>var x = 123
>let y = x+4 # Works.
>const z = x+4 # Throws error.
>```

**Comment by beef331** [comment]
*Bung pinged me in realtime chat I assume to respond* 

`const` is not a `let` as such it has different semantics. The way I see it is a const closure does not make much sense as `ref`s are presently not capable of being used for const, This is a problem for a `closure` as it has a heap allocated environment. 

Not only that but presently the following errors:
```nim
const a = proc() {.closure.} = echo "Hello"
a()
```
`Error: VM problem: dest register is not set`

Since it's attempting to evaluate `a` at CT and not runtime.

> but as it is a closure, I doubt anything "outside" has even access, hence closrure is truly const even without const-keyword use.

[This Exists.](https://nim-lang.org/docs/system.html#rawEnv%2CT)

Another example to explain how odd it is of a concept to me:
```nim
proc makeMyClosure(r: ref int): proc() =
    result = proc() =
      inc r[]
      echo r[]

var myRef {.compileTime.} = new int # This makes a reference in VM since it needs to be accessible at CT, but we can make a closure to capture it.

const a = makeMyClosure(myRef)
let b = a

b()
```

**Comment by bung87** [comment]
Thanks beef's response, am not a native english speaker and not capble to explain this, so I pinged beef, as we discussed yesterday about this. now am pretty sure this should be CT error.

**Comment by Araq** [comment]
Patch the existing `typeAllowed` code for this.

**Comment by arnetheduck** [comment]
Why shouldn't const be allowed to be a proc? It makes proc's less of first-class citizens in the language, which prevents some code and generic constructs, as well as renamed function pointers and other use cases

**Comment by bung87** [comment]
> Why shouldn't const be allowed to be a proc? It makes proc's less of first-class citizens in the language, which prevents some code and generic constructs, as well as renamed function pointers and other use cases

today's news is it is planed to support, but for now it may causes users mis-use, which we dont like to see.

**Comment by arnetheduck** [comment]
Example use case: https://github.com/status-im/nim-chronos/pull/319

**Comment by bung87** [comment]
since chronos used as a real use case, that can't be patched in a easy way, I decide partially support it or wait real const closure implementation.

**Comment by metagn** [comment]
>Since it's attempting to evaluate a at CT and not runtime.

Can't we find a way to only allow calling non-closures converted to a closure type at runtime? i.e. if the closure environment is nil, or whatever that would correspond to for the compile time VM (I'm guessing all procvars at compile time are stored as symbols, so we would check if the symbol type is a closure).

**Pull request closed without merging**
