### PR TITLE
Add `cursor` to lists iterator variables

### PR DESCRIPTION
**Pull request by AmjadHD**
* followup #21507

### CODE REVIEW

**Comment by AmjadHD** [comment]
The CI failures semm unrelated.

**Comment by Araq** [comment]
Better rerun the CI though.

**Comment by AmjadHD** [comment]
How to rerun it ?

**Comment by ringabout** [comment]
weird, I cannot reopen.

image

**Comment by metagn** [comment]
This is causing CI failures

**Comment by AmjadHD** [comment]
@ringabout, Why is this causing SIGSEGV ?

**Comment by metagn** [comment]
Investigate it yourself. The error is happening in the markdown package. If I had to guess the culprit is the change to `remove` because it's more complex than the cursor example in the docs and might not be the intended use ([used once in markdown](https://github.com/soasme/nim-markdown/blob/e6379e25a33d1d79bb62ee285574e41a395ae2d7/src/markdown.nim#L1558)). Or it's a bug with cursor. You would have to understand the cursor feature to decide, I personally don't

**Comment by Araq** [comment]
Given how simple the cursor feature is a bug in its implementation seems rather unlikely. ;-)

**Pull request merged**
