### PR TITLE
Add proc hash for HashSet and for OrderedSet

### LINKED ISSUE #7772: Feature request: proc hash for HashSet
It would be nice if there is `proc hash[T](x: HashSet[T]): Hash` and `proc hash[T](x: OrderedSet[T])` in the module `sets`.

### PR DESCRIPTION
**Pull request by loloiccl**
close #7772

### CODE REVIEW

**Comment by data-man** [comment]
I think that direct use of ```data``` and ```hcode``` will be much faster.

**Comment by loloiccl** [comment]
Thanks @data-man.
That sounds like good idea!
I'll fix to use hcode of data.

**Comment by data-man** [comment]
And don't forget to add tests, please. :)

**Comment by Araq** [comment]
Since this is so expensive to support IMO it's not wise to make it work.

**Comment by loloiccl** [comment]
I think it is expensive too.
But, I think the module `sets` should support types like `HashSet[HashSet[T]]` without user defined `proc hash` of `HashSet[T]`.
What do you think about it @Araq ?

(And, sorry for that I don't have a good idea to implement better `hash`)

**Comment by twetzel59** [comment]
@loloiccl Is there a way of accumulating the hashes that is commutative? If so, that could make it order-agnostic.

**Comment by Araq** [comment]
@twetzel59 yeah, we could ``xor`` the values.

**Comment by loloiccl** [comment]
thanks for @twetzel59 and @Araq.
I pushed a commit with hash for HashSet using xor to mix hashes.

**Pull request merged**
