### PR TITLE
times: use posix constant instead of import

### PR DESCRIPTION
**Pull request by arnetheduck**
#10208 revamped

### CODE REVIEW

**Comment by Araq** [comment]
Note: I need to test this manually on my old OSX machine.

**Comment by arnetheduck** [comment]
don't think the osx code paths are affected, looks like everything osx and time is gated..

it's `nintendoswitch` that's making trouble all the time, weird closed-source platform

**Comment by Araq** [comment]
Fails for me with:

```
/Users/andreasrumpf-mac/projects/nim/nimcache/d_macosx_amd64/stdlib_times.nim.c:369:1: error: unknown type name 'clockid_t'; did you mean 'clock_t'?
clockid_t realTimeClockId_4AFMpGs1xGTBujmpBLazHA;
```

**Comment by arnetheduck** [comment]
ok, realised there's an even better way by not even declaring that variable - then it never appears on non-osx code paths

**Comment by Araq** [comment]
That one worked for me.

**Pull request merged**
