### PR TITLE
Fix strutils.unescape's handling of hex numbers

### PR DESCRIPTION
**Pull request by def-**
Also added a test for a formerly failing string.

Found by solving today's Advent of Code in Nim: https://github.com/def-/nim-advent-of-code-2015/blob/master/day8.nim

### CODE REVIEW

**Comment by Araq** [comment]
What is wrong with  parseutils.parseHex and why not fix that one instead?

**Comment by def-** [comment]
The problem is that we know that there will be exactly 2 characters to read in `"\xFF"`, but the old implementation would read further and also skips a few characters afterwards.

**Comment by Araq** [comment]
That means parseutils.parseHex is error prone and should grow an additional 'exactLen=0' (or similar) parameter.

**Comment by def-** [comment]
Ok, now with parseutils.parseHex. Adding exactLen doesn't seem that reasonable in general.

**Comment by Araq** [comment]
Well we made this mistake because parseutils.parseHex makes this mistake easy to make, so IMO it's more reasonable to support it directly than your workaround is.

**Comment by Araq** [comment]
Fixed it my way.

**Pull request closed without merging**
