### PR TITLE
Fix #17755 (OpenSSL 1.0.x library naming issue on windows) [backport:1.4]

### LINKED ISSUE #17755: OpenSSL 1.0.x library naming issue on windows
The library/dll naming on windows for OpenSSL 1.0.x is incorrect. There's a `nimOldDlls` switch, but it tries to load OpenSSL 1.1.x libraries first.

I read multiple times that old dll names are `ssleay32.dll` and `libeay32.dll`; and changed with OpenSSL 1.1.x.
I read that 64bit builds are named with 32-suffix too (at least when compiling with mingw: https://github.com/openssl/openssl/issues/2383).
I would like to create a pull request which checks if `openssl10` is defined and remove the `nimOldDlls` switch.

I'm currently on branch [version-1-4](/nim-lang/Nim/tree/version-1-4), therefore I need a backport and don't know how you do this and if breaking changes are allowed (removing `nimOldDlls` switch); I guess it's not?

### Current code
```nim
elif useWinVersion:
  when not defined(nimOldDlls) and defined(cpu64):
    const
      DLLSSLName* = "(libssl-1_1-x64|ssleay64|libssl64).dll"
      DLLUtilName* = "(libcrypto-1_1-x64|libeay64).dll"
  else:
    const
      DLLSSLName* = "(libssl-1_1|ssleay32|libssl32).dll"
      DLLUtilName* =  "(libcrypto-1_1|libeay32).dll"
```

### Possible Solution 1
```nim
elif useWinVersion:
  when defined(openssl10):
    const
      DLLSSLName* = "ssleay32.dll"
      DLLUtilName* = "libeay32.dll"
  elif defined(cpu64):
    const
      DLLSSLName* = "(libssl-1_1-x64|ssleay64|libssl64).dll"
      DLLUtilName* = "(libcrypto-1_1-x64|libeay64).dll"
  else:
    const
      DLLSSLName* = "(libssl-1_1|ssleay32|libssl32).dll"
      DLLUtilName* = "(libcrypto-1_1|libeay32).dll"
```

### Possible Solution 2
```nim
elif useWinVersion:
  when defined(openssl10):
    when defined(cpu64):
      const
        DLLSSLName* = "(ssleay32|ssleay64).dll"
        DLLUtilName* = "(libeay32|libeay64).dll"
    else:
      const
        DLLSSLName* = "ssleay32.dll"
        DLLUtilName* = "libeay32.dll"
  elif defined(cpu64):
    const
      DLLSSLName* = "(libssl-1_1-x64|ssleay64|libssl64).dll"
      DLLUtilName* = "(libcrypto-1_1-x64|libeay64).dll"
  else:
    const
      DLLSSLName* = "(libssl-1_1|ssleay32|libssl32).dll"
      DLLUtilName* = "(libcrypto-1_1|libeay32).dll"
```

### Possible Solution 3
```nim
elif useWinVersion:
  when defined(openssl10) or defined(nimOldDlls):
    when defined(cpu64):
      const
        DLLSSLName* = "(ssleay32|ssleay64).dll"
        DLLUtilName* = "(libeay32|libeay64).dll"
    else:
      const
        DLLSSLName* = "ssleay32.dll"
        DLLUtilName* = "libeay32.dll"
  elif defined(cpu64):
    const
      DLLSSLName* = "(libssl-1_1-x64|ssleay64|libssl64).dll"
      DLLUtilName* = "(libcrypto-1_1-x64|libeay64).dll"
  else:
    const
      DLLSSLName* = "(libssl-1_1|ssleay32|libssl32).dll"
      DLLUtilName* = "(libcrypto-1_1|libeay32).dll"
```

### PR DESCRIPTION
**Pull request by Dankr4d**
Fixes #17755 

Fixed OpenSSL 1.0.x library names in openssl module.

### CODE REVIEW

**Comment by Araq** [comment]
The patch itself is very good, but why should we support OpenSSL 1.0.x at all?

**Comment by Dankr4d** [comment]
I'm writing a software (https://github.com/Dankr4d/BF2142Unlocker) which runs required servers for an abandoned game. This game uses OpenSSL 1.0.x SSLv3, therefore I'm forced to use it.
For my next release I want to build 32 bit builds, but the naming messed it up. I wonder why it didn't mess up on 64 bit builds too, but I didn't check it. Maybe just luck because it couldn't find the 1.1 DLLs.

**Comment by Araq** [comment]
Good enough of a reason.

**Comment by Dankr4d** [comment]
@narimiran, could you do a backport of this?

**Comment by narimiran** [comment]
Thanks for notifying me, the merged commit didn't contain `[backport:1.4]`, so I've missed it.

EDIT: It is backported now. It will be part of the next 1.4.x release.

**Comment by Dankr4d** [comment]
> Thanks for notifying me, the merged commit didn't contain `[backport:1.4]`, so I've missed it.

Sadly I just read afterwards how to create a pull request with a backport request. Next time I'll take care of it.
Thank you!

**Pull request merged**
