### PR TITLE
fixes #23445; [backport]

### LINKED ISSUE #23445: Invalid generic type deduction with distinct, static
### Description

A variation on https://github.com/nim-lang/Nim/issues/23419, where the workaround of adding an empty field cannot be used.

As a bonus on top, this shows how it breaks with a `static int` generic parameter - an important use case for several of our libraries.

```nim
import sequtils

type F[T; I: static int] = distinct int

proc start(v: int): F[void, 22] = discard
proc stop(v: int): F[void, 33] = discard

var a = mapIt([1, 2, 3], start(it))

assert $type(a) == "seq[F[system.void, 22]]", $type(a)

var b = mapIt([1, 2, 3], stop(it))

assert $type(b) == "seq[F[system.void, 33]]", $type(b)
```

### Nim Version

1.6, devel

### Current Output

```text
testit.nim(14, 8) `$type(b) == "seq[F[system.void, 33]]"` seq[F[system.void, 22]] [AssertionDefect]
```

### Expected Output

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Araq**

### CODE REVIEW

**Comment by Araq** [comment]
@narimiran please backport.

**Comment by Araq** [comment]
Irrelevant CI failure, merging.

**Comment by narimiran** [comment]
> @narimiran please backport.

`underspecifiedPairs` iterator is not available in 2.0.x.

I tried to do it manually like this (please check if I did it wrong and introduced a bug):

```nim
  of tyGenericInst:
    # BUG #23445
    # The type system must distinguish between `T[int] = object #[empty]#`
    # and `T[float] = object #[empty]#`!
    cycleCheck()
    for i in 1 ..< min(a.sons.len, b.sons.len) - 1:
      if not sameTypeAux(a.sons[i], b.sons[i], c): return false
    result = sameTypeAux(a.lastSon, b.lastSon, c)
```

But the `twrong_same_type.nim` test kept failing.

**Comment by Araq** [comment]
Your manual inlining of the iterator looks correct to me. That means there is another bugfix we should have backported?

**Pull request merged**
