### PR TITLE
Update bug_report.md

### PR DESCRIPTION
**Pull request by krux02**
I think it is valuable information to know where an issue causes problems. I hope this project information will make it easier for us to distinguish real problems and important problems from hypothetical problems.

### CODE REVIEW

**Comment by dom96** [comment]
How many people actually follow this template? Every time I want to create an issue I have to do two clicks thanks to it, I'm not sure that its benefits outweigh this annoyance.

**Comment by narimiran** [comment]
> How many people actually follow this template? Every time I want to create an issue I have to do two clicks thanks to it, I'm not sure that its benefits outweigh this annoyance.

Some of them do, but I wish more people did: bug reports which follow the template are much easier to understand the problem and to reproduce, saving us non-trivial amount of time.

So yes, "having to do one extra click" is greatly outweighed.

**Comment by krux02** [comment]
@dom96 Just think about what you are writing. We spend hours on fixing issues and you complain about an extra click when creating them. And yes, the quality of reported issues has been improved a lot since we have the issue template. Especially first issue reports.

**Comment by dom96** [comment]
@krux02 please don't dismiss feedback like that. I understand that you spend hours fixing bugs, but all feedback should be precious. If issue quality has improved a lot then that's good, I didn't notice that happening but I don't look at many issues nowadays anyway, so fair enough.

**Pull request merged**
