### PR TITLE
lib/pure/times: Make initTimeFormat endianness-agnostic

### LINKED ISSUE #9690: Tests failing on MIPS on Debian
Nim 0.19.0 fails to build on MIPS.

### Current Output
```
Hint: operation successful (29691 lines compiled; 6.857 sec total; 31.891MiB peakmem; Debug Build) [SuccessX]
Hint: /&lt;&lt;PKGBUILDDIR&gt;&gt;/.cache/nim/times_d/runnableExamples/times_examples6  [Exec]
times_examples6.nim(5)   times_examples6
system.nim(3790)         failedAssertImpl
system.nim(3783)         raiseAssert
system.nim(2830)         sysFatal
Error: unhandled exception: /&lt;&lt;PKGBUILDDIR&gt;&gt;/.cache/nim/times_d/runnableExamples/times_examples6.nim(5, 12) `$utc(fromUnix(0)) == "1970-01-01T00:00:00Z"`  [AssertionError]
Error: execution of an external program failed: '/&lt;&lt;PKGBUILDDIR&gt;&gt;/.cache/nim/times_d/runnableExamples/times_examples6 '
[Examples] failed: see /&lt;&lt;PKGBUILDDIR&gt;&gt;/.cache/nim/times_d/runnableExamples/times_examples6.nim
```

### PR DESCRIPTION
**Pull request by glaubitz**
fixes #9690

### CODE REVIEW

**Comment by GULPF** [comment]
I don't understand why the old code wasn't endian-agnostic, or how this change fixes it. Based on @skilchen's comment in the issue it sounds more like there is an endianness issue in the VM's implemention of conversions. Relevant part:
https://github.com/nim-lang/Nim/blob/bce908f6ee9f24346641310d8f7f8971e92ffe01/compiler/vm.nim#L422-L432

From what I understand, bit shifting shouldn't depend on endianness, so perhaps this part is wrong?

**Comment by glaubitz** [comment]
Oh, I'm not an expert in Nim at all. I can only say that the fix I pushed fixes the builds for me on all big-endian targets. If anyone has a cleaner solution, feel free to ignore my PR.

**Comment by Araq** [comment]
Thank you! This seems to be a workaround for a VM/compiler bug. We need to investigate further.

**Comment by glaubitz** [comment]
@Araq You're welcome. Thanks for looking into this. FWIW, I just noticed that 0.18.0 built fine on big-endian in the past, so it must be a regression with 0.19.0. I can bisect the the problem in the weekend unless you have found the offending commit before me.

**Comment by glaubitz** [comment]
Hmm, looks like bisecting Nim is harder than I thought because of the two repositories, ```Nim``` and ```csources```.

**Comment by krux02** [comment]
I just checked the code generator. 
The generated C code for both ``result.patterns.add(FormatPattern.Lit.byte)`` and ``result.patterns.add(ord(FormatPattern.Lit).byte)`` is identical. I doubt that this PR at least with the current version of Nim fixes the Problem.

**Comment by glaubitz** [comment]
That might be the case. I haven't tested with a current version of Nim but anyone interested in fixing this bug can get access to a big-endian Linux machine through the gcc compile farm. There is a fast SPARC machine running Debian, for example.

**Comment by Araq** [comment]
Invalid way to fix the problem, closing.

**Pull request closed without merging**
