### PR TITLE
An unnamed break in a block now gives an `UnnamedBreak` warning

### PR DESCRIPTION
**Pull request by ringabout**
ref https://github.com/nim-lang/Nim/pull/20785
ref https://github.com/nim-lang/RFCs/issues/451

```nim
for i in 1..2: # works
  break

block: # works
  for i in 1..2:
    break

block: # works
  block:
    discard 12 + 3
  for i in 1..2:
    break


for i in 1..2: # errors
  block:
    break

block: # errors
  break
  ```

### CODE REVIEW

**Comment by c-blake** [comment]
You may want to add a test for a working "named block break", like:
```Nim
block named: # works
  if true:
    break named
  echo "not reached"
```

**Comment by ringabout** [comment]
Sure thing, I will add tests later. As a bonus, it seems to reveal a bug in nitter

https://github.com/zedeus/nitter/blob/6272297d64d4cc8f1268626bee31a0e3d5899f51/src/parser.nim#L175
```nim
for typ in imageTypes:
  block:
     if vals{typ & "_large"} != nil:
       result.image = img.getImageVal
       break
```

**Comment by Araq** [comment]
> As a bonus, it seems to reveal a bug in nitter

Wow. :-)

**Comment by c-blake** [comment]
Recommendation of using `block:` for a scope is pervasive and the problem origin here (@ringabout did not elaborate, but the `nitter/src/parserutils.nim` defines a `with` template with `block:` used as a scope). { This is why I thought making `block:` work how people "always thought it did" was The Best Of All Possible Worlds, with apologies to Voltaire.. :-) }

**Comment by zedeus** [comment]
Oops, luckily it doesn't affect anything

**Comment by arnetheduck** [comment]
rather than error, this seems like the kind of thing that should be a warning?

**Comment by arnetheduck** [comment]
ie it has a well-defined meaning that applications _could_ rely on, just  that it catches some people by surprise

**Comment by c-blake** [comment]
Related: https://github.com/nim-lang/Nim/pull/20785#issuecomment-1317374858 (but presumably @ringabout & @Araq also have private comms).

Personally, I think finding (latent) bugs as the `nitter` one in this thread argues for at least the warning making it into Nim2.0, maybe with a note that it "is planned to become an error someday".  Maybe it also argues for the warning being "on" by default...

**Comment by Araq** [comment]
@arnetheduck Yes but this is research work for now, "let's see what it would break". In the final version it will be a warning.

**Comment by Araq** [comment]
> one in this thread argues for at least the warning making it into Nim2.0 

Which is why we're doing it *now*. ;-)

**Comment by juancarlospaco** [comment]
I like the idea of the warning. :+1:


> apologies to Voltaire.

Voltaire used Nim?, interesting.

**Comment by c-blake** [comment]
Leibniz originated [BOAPW[(https://en.wikipedia.org/wiki/Best_of_all_possible_worlds) and Voltaire made it (maybe?) more famous with his satire in *Candide*. { More famous to me, personally, anyway. ;-) } I know you weren't serious, but I also know [@Araq likes Leibniz](https://github.com/nim-lang/RFCs/issues/207#issuecomment-610304597)..So, it deserved a little "errm, technically" elaboration.

That might be one of the first philosopher arguments similar to modern day benchmarking arguments..."Wait, wait..'best' measured *how*?!" :-)

**Comment by ringabout** [comment]
Now that testament tests have passed and there are no severe damage on important packages, I will proceed to make it a warning.

**Comment by ringabout** [comment]
Made a PR for https://github.com/status-im/nim-testutils

https://github.com/status-im/nim-testutils/pull/40

**Pull request merged**
