### PR TITLE
Fixes #7738

### LINKED ISSUE #7738: Unexpected import required
Building this program:

```
import xmltree

type
        Drawing* = tuple[fname: string, document: XmlNode]

proc NewDrawing*(fname: string, height:string="100", width:string="100"): Drawing =
        result = (
            fname: fname,
            document: <>svg(width=width, height=height)
        )

when isMainModule:
        var d = NewDrawing("foo.svg")
```

Fails with this error:

```
svg1.nim(9, 19) template/generic instantiation from here
lib/nim/core/macros.nim(556, 26) Error: undeclared identifier: 'newStringTable'
```

This is with both git HEAD and with latest release:

```
nim --version                                           
Nim Compiler Version 0.18.1 [Linux: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 9d77f61038ddabeb4b59847d709e6d722e743082
active boot switches: -d:release -d:nativeStackTrace
```

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by data-man** [comment]
It's simple way and works fine.
And the ```deadCodeElim``` option is now always turned on.

**Comment by dom96** [comment]
No, it doesn't work fine. It exports everything from strtabs into various stdlib modules, which means if I import them I'll have strtabs imported implicitly. I don't want that.

**Comment by andreaferretti** [comment]
You may not want that, but most beginners do! :-)

It **is** puzzling for begginers to get a `strtab` as result of some other stdlib function and not be able to do anything with the result, such as calling `myStrTab["foo"]`.

I know the reason, you know the reason, yet it makes some sense to just exports strtabs for everyone

**Comment by yglukhov** [comment]
Better fix: #7760

**Comment by dom96** [comment]
Yeah, I prefer #7760. Sorry.

**Comment by Araq** [comment]
> It is puzzling for begginers to get a strtab as result of some other stdlib function and not be able to do anything with the result, such as calling myStrTab["foo"].

Yes but a better solution would be my "scope extension idea" that I outlined here: 
https://forum.nim-lang.org/t/3783

**Pull request closed without merging**
