### PR TITLE
openssl 3 support (1.6)

### PR DESCRIPTION
**Pull request by metagn**
#20668 adapted to 1.6, see also https://github.com/nim-lang/Nim/pull/19814, https://github.com/nim-lang/Nim/pull/20324, https://github.com/nim-lang/Nim/pull/20341

### CODE REVIEW

**Comment by metagn** [comment]
CI failure is pre existing since https://github.com/nim-lang/Nim/commit/8e04112762d5f24b641dfb69bc232cc933cd1a40 (or c9df6cfd92b3de3e62f1dc6c9b05d712a90308ee or 203c18352a7c51a01e9a08a70105377b26f19238)

**Comment by metagn** [comment]
Cherry picked #20701 as well

**Comment by ringabout** [comment]
> CI failure is pre existing

It should be fixed now https://github.com/mratsim/weave/pull/188

**Comment by ringabout** [comment]
Hold on, https://github.com/nim-lang/Nim/pull/20701 is not enough which fixes a part of the issue, I will push a fix for 

```
/home/runner/work/nightlies/nightlies/nim-1.7.3/lib/wrappers/openssl.nim(844, 23) Error: undeclared identifier: 'sslSymNullable'
```

**Comment by ringabout** [comment]
Here you are https://github.com/nim-lang/Nim/pull/20722

**Comment by metagn** [comment]
Added

**Pull request merged**
