### PR TITLE
tfdleak: fix flakyness on Windows

### PR DESCRIPTION
**Pull request by alaviss**
Based on the idea explained in https://github.com/nim-lang/Nim/pull/14548#issuecomment-637789249

Closes #14548
Refs #14090

### CODE REVIEW

**Comment by alaviss** [comment]
Restarting CI to verify that the test will fail everytime

**Comment by timotheecour** [comment]
* this may cause subtle, rare issues because tests run in parallel (so you'd have tfdleak_multiple.nim and tfdleak.nim running) 
=> rename tfdleak.nim to mfdleak.nim
* maybe just use N < 200 iterations for OS other than windows since it's the only problematic OS (netbsd is not yet running in CI), unless you can make sure extra time is negligible
* did you see my notes in https://github.com/nim-lang/Nim/pull/14548#issue-426544097 ?
eg getHandleInformation etc

**Comment by alaviss** [comment]
> * this may cause subtle, rare issues because tests run in parallel (so you'd have tfdleak_multiple.nim and tfdleak.nim running)
>       => rename tfdleak.nim to mfdleak.nim

Don't worry, tests in the same directory are run sequentially.

> * maybe just use N < 200 iterations for OS other than windows since it's the only problematic OS (netbsd is not yet running in CI), unless you can make sure extra time is negligible

It's negligible.

> * did you see my notes in [#14548 (comment)](https://github.com/nim-lang/Nim/pull/14548#issue-426544097) ?
>       eg getHandleInformation etc

Yes, in my knowledge `getHandleInformation` is correct, and it's one of the few procs that work across all handle types. Our false positive likely stems from the fact that `winlean` uses `dynlib` and the loading of them can create handles that collide with the non-inherited handle.

Now that I have a reliable case to test for failure, I can try to employ a different strategy: purposefully leak a duplicated handle, then use `CompareObjectHandles` to verify whether the handle we're testing leaked. This should remove any possible false positives.

Of course, the most reliable way would be to split the leak tester out, but just about every corner of the stdlib imports `winlean` on Windows, so this strategy won't work.

**Comment by timotheecour** [comment]
> eg getHandleInformation

I meant `GetFileInformationByHandle`, mentioned here https://wiki.sei.cmu.edu/confluence/display/c/WIN03-C.+Understand+HANDLE+inheritance

I think I may see the problem + potential solution: look at how python does it in https://github.com/python/cpython/blob/317bab0bf61e4cbab37c81baf185d8b57ca62a6b/Python/fileutils.c#L1084

`int _Py_get_inheritable(int fd)`
=> it starts from `int fd` (which is our `cint` or `FileHandle`), not from a `Handle` (our `int`). I think you can only reliably pass a FileHandle across process boundary, not a Handle.

Then it calls 
```
handle = (HANDLE)_get_osfhandle(fd);
if (!GetHandleInformation(handle, &flags)) {
        if (raise)
            PyErr_SetFromWindowsErr(0);
        return -1;
    }
    return (flags & HANDLE_FLAG_INHERIT);
```

so maybe the test should be updated to pass around a FileHandle instead of a Handle

**Comment by alaviss** [comment]
> I meant `GetFileInformationByHandle`, mentioned here https://wiki.sei.cmu.edu/confluence/display/c/WIN03-C.+Understand+HANDLE+inheritance

We also test sockets, so this wouldn't work

> I think you can only reliably pass a FileHandle across process boundary, not a Handle.

It's the opposite, you can only pass a `Handle` across the boundary, since the `FileHandle` is managed by CRT and is only valid for that one process.

**Comment by timotheecour** [comment]
ok let's see; since you're attempting to fix this properly, can you fix in this PR the 2 things I mentioned here https://github.com/nim-lang/Nim/pull/14548#issue-426544097

```
# in lib/system/io.nim => bug
proc getOsfhandle(fd: cint): FileHandle {.importc: "_get_osfhandle", header: "<io.h>".}
# in lib/windows/winlean.nim => ok
proc get_osfhandle*(fd:FileHandle): Handle {.importc: "_get_osfhandle", header:"<io.h>".}
```

and
```
proc setHandleInformation(handle: FileHandle, mask, flags: culong): cint {.importc: "SetHandleInformation", header: "<handleapi.h>".}
is also incorrect according to docs.microsoft.com/en-us/windows/win32/api/handleapi/nf-handleapi-sethandleinformation
=> 1st param should be Handle not FileHandle
```
the rest (`winlean should really use distinct types eg BOOL, DWORD etc, which would make it much safer to use those bug prone window APIS`) can be done later as that's not a bug 


the types are wrong(in particular FileHandle.sizeof != Handle.sizeof)

**Comment by timotheecour** [comment]
@alaviss 

30s is not negligible
```
PASS: tests/stdlib/tfdleak.nim C                                   ( 1.83 sec)
PASS: tests/stdlib/tfdleak.nim C                                   ( 3.69 sec)
PASS: tests/stdlib/tfdleak_multiple.nim C                          (26.33 sec)
```

**Comment by alaviss** [comment]
You can dial the iteration count down, but it's currently the number that brings out the bug on Windows, and if the number were to be dialed down, it should keep this property.

Also, I'd like that this test use the same number of iterations between all OS, since that would ensure consistency between all of them.

**Comment by timotheecour** [comment]
but OSX+linux never caused an issue ; if they ever start flaking we can just bring that number up for OSX+linux. This was only for windows.
So I suggest to only have the high number for windows in tests/stdlib/tfdleak_multiple.nim

**Comment by alaviss** [comment]
In theory the flakiness shouldn't manifest on any *nix based system due to the fact that FDs are allocated pretty deterministically (in the increasing order), so maybe we can even disable the test for anything that's not Windows.

Or we can take the 48s (or lower if we reduce the iteration count) hit on *nix (according to Azure Pipelines analytics).

**Pull request merged**
