### PR TITLE
use older nims to build newer nims

### PR DESCRIPTION
**Pull request by disruptek**
Let's see if this passes CI.

### CODE REVIEW

**Comment by timotheecour** [comment]
Just use --lib:lib for that, also, what bug is this fixing?

**Comment by disruptek** [comment]
The bug is that a stable nim binary in your path cannot be used to build an unstable compiler.

**Comment by timotheecour** [comment]
> The bug is that a stable nim binary in your path cannot be used to build an unstable compiler.

can you provide a concrete example (ideally with git hashes pointing to stable vs unstable)? And for this example, why would `--lib:lib` not work?

**Comment by Araq** [comment]
Nim v1 lacks e.g. ``std/private/since`` and so cannot compile a compiler that uses this file under this path because Nim v1 uses its own stdlib and not devel's stdlib. ``--lib`` could also work though.

**Comment by timotheecour** [comment]
I use `--lib:lib` all the time for exactly this purpose (compiling a local Nim repo from an external nim binary that's not under ./bin/); it's much cleaner than having to copy over the binary via `cp /external/nim bin/xxx` (and in particular doesn't overwrite bin/xxx). I haven't had a problem with that

**Pull request closed without merging**
