### PR TITLE
Write some tests for streams module

### PR DESCRIPTION
**Pull request by konqoro**
Right now, they all fail... I can move the tests from the module here, if that is okay. Also tests for FileStream need to be added. (will do asap)

### CODE REVIEW

**Comment by data-man** [comment]
@konqoro 
Please, add:
```nim
var s = newStringStream("The quick brown fox jumped over the lazy dog. The lazy dog ran.")
write(s, "123")
echo s.peekLine
```

**Comment by konqoro** [comment]
@data-man ok but peekLine should output just "The quick brown fox jumped over the lazy dog." or  "" depending if its called before or after readAll.

**Comment by data-man** [comment]
By implementation, ss should be equal to "123 quick brown fox jumped over the lazy dog.\nThe lazy dog ran"

**Comment by konqoro** [comment]
Wtf why they are green?

**Comment by konqoro** [comment]
@Yardanico I think the tester is broken.

**Comment by Yardanico** [comment]
@konqoro yes, someone has reported that too

**Comment by Araq** [comment]
Please rebase, the tester has been fixed.

**Comment by Araq** [comment]
Well don't add tests that fail. Re-open when you have decent tests. :-)

**Comment by konqoro** [comment]
Yeah sorry for that.

**Pull request closed without merging**
