### PR TITLE
EnumUtils, speed up findStr in compiler

### PR DESCRIPTION
**Pull request by cooldome**
New functions in strutils parseEnumRange.
I plan to use them in compiler itself, likely useful in other places too.

### CODE REVIEW

**Comment by Araq** [comment]
One idea: Move ``strutils.parseEnum`` to ``std / enumutils`` and then add your ``parseEnumRange`` to ``std / enumutils`` and add an ``export`` statement to strutils for backwards compat.

**Comment by cooldome** [comment]
@Araq, I have tried moving to enumutils. Unfortunately, it creates the circular dependency problem. nimIdentNormalize from strutils is used in enumutils.

Test failure is unrelated.

**Comment by Clyybber** [comment]
Can't we simply use
```nim
proc parseEnumRange*[T: enum](s: string, a, b: static[T]): T =
  result = parseEnum[T](s)
  if result < a or result > b: raise newException(ValueError)
```
in the compiler instead?
It seems much simpler and doesn't require changes to the stdlib.

**Comment by cooldome** [comment]
Tried it, doesn't work. ParseEnum complains at compile time:
```
 Error: Ambiguous enums cannot be parsed, field User appears multiple times!
```

It is really ambiogius, some warnings and hints have the same string representation in the compiler's enum.
It does work with parseEnumRange as expected since ambiguities are chopped off, hints are parsed separately from warnings.

Seems parseEnumRange is also useful tool to deal with ambiguities

**Comment by Araq** [comment]
> It is really ambiogius, some warnings and hints have the same string representation in the compiler's enum.

Ok, but I think the way this message enum is used inside the Nim compiler is really hardly idiomatic and so almost nobody (except from us inside the Nim compiler) needs it.

**Comment by cooldome** [comment]
parseEnumRange doesn't work either because it is using `nimIdentNormalize` instead of `normalize`.
I have not a bad idea how to organize everything. `genEnumStmt` macro goes into `std / enumutils`.
Macro accepts normalization function as argument this helps with breaking circular dependency.

`genEnumStmt` is used directly by `findStr` in `wordrecg`. `parseEnumRange` is no longer required.


Does it sound good?

**Comment by juancarlospaco** [comment]
Needs changelog.

**Comment by cooldome** [comment]
Added changelog entry. Also found a way how to pass normalizer to macro only once

**Pull request merged**
