### PR TITLE
thamming_orc test created/destroyed counts match

### PR DESCRIPTION
**Pull request by GordonBGood**
The thamming_orc.nim code now counts all created objects being tested, not just the ones following the "first 20" test, and the position of the `destroyed += 1` counter has been adjusted so it counts all the calls that are as a result of `=trace` tracing and not just the original destruction calls.

### CODE REVIEW

**Comment by Araq** [comment]
Why the `[skip ci]`? seems like a bad idea, please change the commit message.

**Comment by GordonBGood** [comment]
@Araq:
Normally I wouldn't add the `[skip ci]` but I was reading in the "Contributing" document: "Continuous Integration is by default run on every push in a PR; this clogs the CI pipeline and affects other PR's; if you don't need it (e.g. for WIP or documentation only changes), add [skip ci] to your commit message title.";   As this isn't a very essential update, I thought it might apply here.

I've removed it from the title of the PR, but I can't find any way to edit the embedded commit title, other than to perhaps close the PR and resubmit the commit as a new PR.  Should I do that?

**Comment by Vindaar** [comment]
> I've removed it from the title of the PR, but I can't find any way to edit the embedded commit title, other than to perhaps close the PR and resubmit the commit as a new PR. Should I do that?

You'd have to reword the commit message locally and then force push. On the command line it can be a bit confusing (can only recommend magit for emacs here), something like this:

https://stackoverflow.com/a/1186549

During the `amend` call you can change the commit message.

And then just
```
git push <yourRemoteName> devel --force
```

(as you pushed to your `devel` fork).

**Comment by GordonBGood** [comment]
@Vindaar:
Thanks very much for your help.  Suffered a power failure for a day so a bit slow.  For reference, it just required two commands when the commit is the latest, as follows:

1. `git commit --amend -m "New Commit Message"`
2. `git push <yourRemoteName> devel --force`

The second was just as you said, but I didn't use it and force pushed directly from VS Code instead.

**Comment by Vindaar** [comment]
> Thanks very much for your help. Suffered a power failure for a day so a bit slow. For reference, it just required two commands when the commit is the latest, as follows

No worries! And yes, if it's the latest commit it's really easy. For some reason I thought there was more than one commit, but I think I got confused by the title change, sorry. :smile:

**Pull request merged**
