### PR TITLE
fixes  #20397; fixes stylecheck regression

### LINKED ISSUE #20397: --styleCheck:off does not work (and --styleCheck:hint is now the default?)
### What happened?

```nim
var a_b = 1
```
Compiling the above code gives -
```
t.nim(1, 5) Hint: 'a_b' should be: 'aB' [Name]
```
Using `--styleCheck:error` I get -
```
t.nim(1, 5) Error: 'a_b' should be: 'aB'
```
Using `--styleCheck:off` I still get -
```
t.nim(1, 5) Hint: 'a_b' should be: 'aB' [Name]
```

It should not give this hint when styleCheck:off is given
Also styleCheck:hint should not be the default (if that was an intentional change and not just this bug itself)

### Nim Version

```
Nim Compiler Version 1.7.1 [Windows: amd64]
Compiled at 2022-09-20
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 4a1bda667c74361c121460ca7d80cfcbf003d8d7
active boot switches: -d:release -d:danger
```

### PR DESCRIPTION
**Pull request by ringabout**
fixes #20397

### CODE REVIEW

**Comment by ringabout** [comment]
The CI seems to have some connection issues.

**Comment by metagn** [comment]
It seems #19822 was backported but this was not. Does this mean 1.6.8 has #20397?

**Comment by ringabout** [comment]
My bad, I reported the issue yesterday. Hopefully there would be a hotfix.

**Comment by ringabout** [comment]
@narimiran could you please make a hotfix?

While we're at it, https://github.com/nim-lang/Nim/commit/fd76c004794e1cd163450465fa6e493735e6dee4 is too risky for 1.6.8 and it is not actually needed. Changing belongsToStdlib to partOfStdlib should make the CI green.

**Comment by narimiran** [comment]
> could you please make a hotfix?

What exactly would that be? 1.6.10 or some "new 1.6.8"?

(Why is nobody paying attention to the release candidates? :'( 1.6.8RC was available for more than two weeks and there wasn't a single remark....)

**Comment by metagn** [comment]
I would say 1.6.10, but only after a couple of days in case more issues are found.

I would suggest making blog posts for the release candidates or posting on Reddit/Discord/more places. It gets buried easily on the forum.

**Comment by narimiran** [comment]
This is now backported, and it will be part of 1.6.10.

> While we're at it, https://github.com/nim-lang/Nim/commit/fd76c004794e1cd163450465fa6e493735e6dee4 is too risky for 1.6.8 and it is not actually needed. Changing belongsToStdlib to partOfStdlib should make the CI green.

Could you please make a PR (targeting the `version-1-6` branch) which reverts and/or changes the stuff you mention?

**Pull request merged**
