### PR TITLE
macros warning and hint now also has the node argument

### PR DESCRIPTION
**Pull request by krux02**
No Idea why these were not included in the initial version they would have been straight forward.

### CODE REVIEW

**Comment by Araq** [comment]
Seems convoluted and I fail to see the reason why ``opcError`` needs to be written in your style.

**Comment by krux02** [comment]
Well I did the rewrite of ``opcError`` to better understand it. I personally think that ``message`` and ``nodeForLineInfo`` are beffer variable names than ``a`` and ``b``. But I don't have any claims that this is the nicest code, but it get's the job done, and it's not too long.

**Comment by Araq** [comment]
Extract the common logic to a template perhaps? ``vm.nim`` is already so messy, every opcode becomes full of special cases and while that's not your fault, I don't want to make it worse all the time.

**Comment by krux02** [comment]
so what is preventing this PR from being merged?

**Comment by krux02** [comment]
The test fails with the error message "not unused", but I have no idea what that should tell me.

```
terminal.nim(313, 16) template/generic instantiation from here
lib/core/macros.nim(377, 28) Error: not unused
Traceback (most recent call last)
nim.nim(121)             nim
nim.nim(77)              handleCmdLine
main.nim(173)            mainCommand
main.nim(77)             commandCompileToC
modules.nim(242)         compileProject
modules.nim(182)         compileModule
passes.nim(250)          processModule
passes.nim(139)          processTopLevelStmt
sem.nim(576)             myProcess
[...]
msgs.nim(891)            handleError
msgs.nim(876)            quit
```

**Comment by krux02** [comment]
this is now already implemented by @LemonBoy

**Pull request closed without merging**
