### PR TITLE
try to fix "Error: internal error: genAssignment: tyUncheckedArray" for arc/orc

### PR DESCRIPTION
**Pull request by derekdai**

### CODE REVIEW

**Comment by Araq** [comment]
Well with this patch things don't crash anymore but the real problem remains: The compiler does not know how to copy an UncheckedArray, only `ptr UncheckedArray` can be copied.

**Comment by derekdai** [comment]
If annotate `UncheckedArray[T]` this way, will it help?
```nim
type
  Obj = object
    c: int
    a {.caps: "c".}: UncheckedArray[string]
  Tup = tuple
    v: int
    a {.zeroTerminiated.}: UncheckedArray[char]

proc flexibleNew[T](caps: int, zeroTerm: bool): ref T = discard
```

Then compiler can auto generate `=copy`/`=sink`/`=destroy`, and help to check index boundary at runtime.

Maybe some limitations could also apply to `UncheckedArray[T]`, for example, field with `UncheckedArray[T]` type can appear in a `object`/`tuple` type once and only once, and it must be the last field. With `object` type, compiler will mark it as `final` automatically, etc.

**Comment by Araq** [comment]
This could work but the idea is that you provide `=copy` and `=sink` etc on your own.

**Comment by beef331** [comment]
Given the compiler has 0 idea how the UncheckedArray is supposed to be used, would it be too invasive to just require user defined hooks if a hook is needed? At least a warning on usage of a default hook seems sensible to me.

**Comment by Araq** [comment]
Yes, an UncheckedArray should have a builtin .error =copy etc.

**Comment by derekdai** [comment]
> Given the compiler has 0 idea how the UncheckedArray is supposed to be used, would it be too invasive to just require user defined hooks if a hook is needed? At least a warning on usage of a default hook seems sensible to me.

Even we adding pragma like the above example and the compiler refers to `Obj.c` to generate corresponding checks can't ensure memory safety?

**Comment by beef331** [comment]
Thinking about it further, I might be missing something. Nim's hooks only work on `object` and `distinct`.  Given this and the fact that `UncheckedArray[T]` cannot live on the stack, how can the following possibly compile?

```nim
proc `=copy`(a: var Obj, b: Obj) =
  a = b # What is the sizeof(a) and sizeof(b)? How is `a` allocated to match the sizeof `b`?
```

**Comment by derekdai** [comment]
> 

Ah, you are right, `UncheckedArray[T]` won't fit into hooks.

~~Maybe compiler could handle `UncheckedArray[T]` just like `array[I; T]` (if caps is given)?~~

**Pull request closed without merging**
