### PR TITLE
fixes #19332; fixes #19942; drop support for multiple varargs which never work well

### LINKED ISSUE #19332: Functions with multiple varargs compete over the parameters
When declaring a function that takes multiple vararg parameters, preferably of different types, they will share one address. This means the same vararg array is interpreted with multiple different types, leading to weird coercion.

Example:
```nim
proc thing(a: varargs[string], b: varargs[int]) = 
  echo a
  echo b

thing("a", 0)
```
Output:
```
["a", ""]
[94561930070512, 0]
```

This also means it will deref an invalid location when the int parameter is non-zero

### LINKED ISSUE #19942: Second unused `vararg` equals to first used `vararg`
**Test**
```nim
proc test(a: varargs[int], b: varargs[int]) = doAssert a != b

test(1)       # Correct
test([1, 2])  # Correct
test(1, 2)    # BUG
```
***
```nim
>nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-06-29
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 8a344cb25b9b9d1b185ba6e5a8e1cf14421fedb4
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by ringabout**
fixes #19332
fixes #19942

Even a simple case for multiple varargs breaks

```nim
proc thing(a: varargs[string], m: int, b: varargs[float]) = 
  discard

thing("1.0", "2.0", 0, 1.0) # compiles
thing("1.0", 0, 1.0, 2.0) # broken
thing("1.0", "2.0", 0, 1.0, 2.0) # broken
```

### CODE REVIEW

**Comment by ringabout** [comment]
I will revisit it later.

**Comment by ringabout** [comment]
It seems that https://github.com/mratsim/Arraymancer uses this feature.

**Comment by ringabout** [comment]
made a PR to arraymancer https://github.com/mratsim/Arraymancer/pull/572

**Comment by metagn** [comment]
For the package failures you can use what I did in #20199 [here](https://github.com/nim-lang/Nim/pull/20199/files#diff-536ce5b720c0d86d37341fb21a90eb4f23b408da9003f1aa8bb9704de74e8972) and add `nimble install -y arraymancer@#HEAD;` before the test commands of the packages that depend on arraymancer.

**Comment by Araq** [comment]
I still think we should simply fix sigmatch instead so that it can handle multiple varargs.

**Comment by ringabout** [comment]
Sure.

**Pull request closed without merging**
