### PR TITLE
helper to convert tests to doAssert instead of echo

### PR DESCRIPTION
**Pull request by timotheecour**
/cc @narimiran @Araq 

This will make it easier to simplify a number of tests run by testament, replacing `echo` + `discard` magic by `doAssert`'s 
I picked `tcomputedgoto.nim` as an example of resulting transformed test in reply to https://github.com/nim-lang/Nim/issues/9581#issuecomment-434990987

This will also enable applying the optimization https://github.com/nim-lang/Nim/issues/9581 to more tests.

* I put the helper module in `lib/pure/testhelpers.nim` but happy to move it somewhere else; the requirement is that it should be importable by tests without adding dependencies that would prevent using it in many tests

* happy to change name `echoToResult` to some other name

### CODE REVIEW

**Comment by timotheecour** [comment]
ping

**Comment by krux02** [comment]
I will answer, because I worked on computed goto last. Generally I agree, but in this concrete example I disagree. This is a bad pattern and I don't want to start with it. Do you know the testing with "should" instead of assert. It is basically the same as assert, but it doesn't cause a crash in the test, only a test failure at the end of the test.

**Comment by timotheecour** [comment]
@krux02 just to clarify:
your concern with running multiple tests in 1 compilation unit (instead of individual compilation units, 1 per file) is that the test will stop on 1st error (because of doAssert) instead of giving you all the errors?
ie, you want something like `unittest.check` instead of `unittest.require`?

if so, we can probably do something similar as done in `unittest.require` in `lib/pure/testhelpers.nim` and keep going until the end, reporting all failures as they happen and make the whole test pass or fail depending on whether there are 0 or at least 1 error. (for some reason @Araq doesn't want `import unittest` in testament; my guess is he wants something with less dependencies; I think that can be done, maybe as follows:

testhelpers.nim:
```nim
# pseudocode:
var numFailures=0
proc check(cond):
  if not cond: numFailures.inc
  ...
```
and at the very end, in testament, check that `numFailures==0`

**Comment by krux02** [comment]
I don't see an improvement for the test case you touched. I don't like the changes. If you can apply changes for multiple test cases with measurable performance improvements then it is a different story, but I have my doubts that your approach works. So I am closing it for now.

**Comment by timotheecour** [comment]
@krux02 please re-open;  did you read the motivation for this ? please read the full thread here: https://github.com/nim-lang/Nim/issues/9581#issue-375766740 including @Araq 's comment here https://github.com/nim-lang/Nim/issues/9581#issuecomment-435461719

I measured a 15X speedup (~50 seconds to ~3 seconds) and have a test PR where you can verify the speed difference

the helper I'm introducing here allows the technique in https://github.com/nim-lang/Nim/issues/9581 to be applied to more tests, directly answering the concerns raised in that thread here https://github.com/nim-lang/Nim/issues/9581#issuecomment-434571999 and here https://github.com/nim-lang/Nim/issues/9581#issuecomment-434990987 

I don't understand your concern besides "you don't like it"

> I don't see an improvement for the test case you touched.

this allows the test to be bundled with other tests as described https://github.com/nim-lang/Nim/issues/9581

**Comment by krux02** [comment]
You managed to add 6 links to locations that should support your PR, but you forgot the only one that I care about, your PR with the measurable 15X speedup.

**Comment by timotheecour** [comment]
thanks for re-opening ; 
> but you forgot the only one that I care about, your PR with the measurable 15X speedup.

this was mentioned in top-level msg of that thread; here's the WIP PR : https://github.com/nim-lang/Nim/pull/9580 (it's not ready for review, but it's there in case someone wants to experiment with it or reproduce timing results) ; 
here's the bundled file from that PR: https://github.com/nim-lang/Nim/pull/9580/files#diff-7bc741ba5965b85ab8ebcb36fe256812

**Comment by krux02** [comment]
tester can be adjusted to collect the output of several tests. You don't need a fake echo for that. I am closing this as rejected.

**Pull request closed without merging**
