### PR TITLE
Clean out oldast

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Clean out old Deprecated CLI switch, previous to v`0.19`.
- 1 third party package failing CI, but already fixed and merged https://github.com/Vindaar/ginger/pull/20#issue-441001792

### CODE REVIEW

**Review by dom96 — APPROVED** [review]
Nice. Removal looks good.

**Comment by timotheecour** [comment]
either comment out ggplotnim or send a PR to fix https://github.com/Vindaar/ggplotnim/issues/85 would unblock this PR

**Comment by ghost** [comment]
@timotheecour @Vindaar already fixed everything, see https://github.com/Vindaar/ginger/commit/a5b3c5f8d4387bf50ca6e282e69f2aeb8cab6c20

**Comment by juancarlospaco** [comment]
https://github.com/Vindaar/ggplotnim/search?q=oldast ?. :confused:

**Comment by ghost** [comment]
@juancarlospaco please force-push to restart CI

**Comment by timotheecour** [comment]
@Yardanico @juancarlospaco 
> please force-push to restart CI

see https://github.com/timotheecour/Nim/issues/327 first; I've just restarted CI for just what needs to be restarted, no need to force-push

**Pull request merged**
