### PR TITLE
remove some deprecated pre-1.0 stdlib modules

### PR DESCRIPTION
**Pull request by metagn**
The modules LockFreeHash, events, parseopt2 are removed. 

previous attempts to remove these modules:
* parseopt2 #16812 (closed because laziness/wrong suggestion to add to graveyard or failed, but seems to work here)
* LockFreeHash and events #16819 (closed because of laziness and wrong suggestion to add to graveyard)

not included pre-1.0 stdlib deprecations:
* ze, toU8 etc in system/arithmetics. some very old packages might use these, most of all though they are common in the repo, it might be smoother if they are just moved to a std/private module
* macros procs, failing #19775
* sets procs, rejected #19520
* simple import/export modules that don't really need to be removed
  * securehash, #19790
  * oswalkdir, failing #19642
  * ospaths, rejected #14887
  * future, used in:
    * ~~karax~~ (merged https://github.com/karaxnim/karax/pull/228)
    * ~~httpbeast~~ (https://github.com/dom96/httpbeast/pull/77)
    * ~~iterutils~~ (merged https://github.com/def-/nim-iterutils/pull/16)
    * classy (~~https://github.com/nigredo-tori/classy/pull/7~~ this module is meant to work on 0.15 so this PR is not good enough)

### CODE REVIEW

**Comment by ringabout** [comment]
See also
https://github.com/nim-lang/Nim/pull/19775 which takes care of `std/macros`.
https://github.com/nim-lang/Nim/pull/19642 Remove deprecated oswalkdir
https://github.com/nim-lang/Nim/pull/19643 Remove deprecated isvalidfilename
https://github.com/nim-lang/Nim/pull/19644 Remove deprecated httpclient.request
https://github.com/nim-lang/Nim/pull/19790 Remove deprecated module: securehash

**Comment by metagn** [comment]
Oops, thanks

**Comment by metagn** [comment]
PR is now self contained and has changelog entry.

**Comment by juancarlospaco** [comment]
@metagn
I never really liked the "Graveyard" thing, 
but it was suggested to me at that time, because it is in fact abandoned. 🤷

If the PR were merged more quickly I will contribute a lot more,
but if you check the dates, PRs went months and years waiting, I am all up for faster merging.

For the Changelog conflicts, a long time ago, I already proposed a solution,
use multiple files instead of 1 file, `changelog.md` ➡️ `/changelog/*.md`, but got ignored.

**Comment by metagn** [comment]
The reason the suggestion to add those modules to graveyard was wrong is that it says graveyard is only for "non-deprecated modules", and those modules were deprecated for good reason. I think graveyard is good for modules like mersenne that are unlikely to break but are unnecessary.

It's fine, I have 15 mergeable open PRs, I'm fine with waiting for reviews as long as they do get reviewed at some point. (Though I will be away for 3 weeks after next week)

**Comment by juancarlospaco** [comment]
I dont know what can be done to improve the situation,
on other projects Ive seen some users have permissions,
but only for review and triage PRs, ping and check issues and PRs,
Github dont have fine grained permissions only for that,
but is done "by word" of such trusted user. 🤔

**Comment by Varriount** [comment]
@juancarlospaco Another reason for slow merges is because certain contributors only feel comfortable merging certain things - for example, I will hapilly merge in bug-fixes and documentation improvements, but I leave anything touching the compiler to @Araq. In this case, I would review and possibly merge this PR, but I don't know if it's been concluded that all these modules should be deprecated.

**Comment by juancarlospaco** [comment]
@Varriount
I agree, I do not want to merge my own PRs, nor touch the compiler,
just misc stuff like docs and stdlib, I am just trying to help but is hard to contribute.

**Comment by ringabout** [comment]
Nim lacks authorities who can merge pull requests. If it were small diffs or documentation changes, I could have merged it.

**Pull request merged**
