### PR TITLE
Weekday parse/format (replacement)

### PR DESCRIPTION
**Pull request by capocasa**
Replacement for auto-closed PR #21855. Original description:

The Iso weekday functions were not supported by the datetime parse/format proc yet.

The less-than-trivial code is kept in a seperate proc toDateTimeByWeek, the extra cost for regular date parsing is one if isSome(X) call.

Got this rustled up (hopefully) in time for 2.0 since it's possible a (minimally) breaking change!

### CODE REVIEW

**Comment by capocasa** [comment]
Standing by for CI checks
Edit: Found error message looking into it

**Comment by capocasa** [comment]
So the culprit is

`pure/times.nim(1805, 19) Error: undeclared field: 'getIsoWeekAndYear' for type times.DateTime`

Those tests work for me though. But why does the test action say Nim Version 1.0?

`tests/system/tuse_version.nim c -d:NimMajor=1 -d:NimMinor=0 -d:NimPatch=100`

**Comment by Araq** [comment]
The test tuse_version is outdated and should be removed. Should be done as part of this PR.

**Comment by capocasa** [comment]
> The test tuse_version is outdated and should be removed. Should be done as part of this PR.

Done, waiting for CI

Edit: Tests work fine now

**Pull request merged**
