### PR TITLE
Use `.. warning::`

### PR DESCRIPTION
**Pull request by konsumlamm**

### CODE REVIEW

**Comment by konsumlamm** [comment]
CI failure seems to be unrelated.

**Review by timotheecour — APPROVED** [review]

**Comment by timotheecour** [comment]
merging, similar PR was approved and merged before.

## future work
for reference CI errors were:
```
PASS: glob c                                                       ( 8.43 sec)
  PASS: ggplotnim c                                                  (45.66 sec)
  FAIL: gnuplot c
  Test "gnuplot" in category "nimble-packages-1"
  Failure: reInstallFailed
  git clone dvolk/gnuplot.nim pkgstemp/gnuplot
  Cloning into 'pkgstemp/gnuplot'...
  fatal: unable to access 'dvolk/gnuplot.nim': Could not resolve host: github.com
  
  FAIL: hts c
  Test "hts" in category "nimble-packages-1"
  Failure: reInstallFailed
  git clone brentp/hts-nim pkgstemp/hts
  Cloning into 'pkgstemp/hts'...
  fatal: unable to access 'brentp/hts-nim': Could not resolve host: github.com
  
```

if i type: `git clone dvolk/gnuplot.nim` on cmdline, I get (expectedly): `fatal: repository 'dvolk/gnuplot.nim' does not exist`

so there's a bug in testament (it could simply be a bug in how cmd is rendered, but still a bug)

**Comment by a-mr** [comment]
@konsumlamm 

consider starting `warning` from a capital letter, it reads a bit better IMHO:
```RST
.. Warning::
```

Also, for most critical messages like `danger` or `caution` it would even make sense to spell it all-capital
```RST
.. DANGER::
```

**Comment by ringabout** [comment]
Hi @a-mr
you can write the best practice to https://nim-lang.github.io/Nim/contributing.html#documentation
or https://nim-lang.github.io/Nim/contributing.html#best-practices

**Comment by konsumlamm** [comment]
> @konsumlamm
> 
> consider starting `warning` from a capital letter, it reads a bit better IMHO:
> 
> ```
> .. Warning::
> ```
> 
> Also, for most critical messages like `danger` or `caution` it would even make sense to spell it all-capital
> 
> ```
> .. DANGER::
> ```

I don't see a reason to not use lowercase letters, when they render as the same message anyway... The leading `..` is good enough as indicator IMO.

**Pull request merged**
