### PR TITLE
Lexbase compatible with JS

### PR DESCRIPTION
**Pull request by yglukhov**
This effectively enables `parsexml` on JS.

### CODE REVIEW

**Comment by Araq** [comment]
Looks ok, but in the past @def- XML parsing test which parses Wikipedia detected most bugs for lexbase, so somebody should please rerun it with this patch.

**Comment by yglukhov** [comment]
You were right. The changes introduced performance degradation (presumably) because of gc.grow instead of realloc. I've left cstring in native impl, so now it's good.

I've run the test with file from https://dumps.wikimedia.org/frwiki/20151226/frwiki-20151226-pages-articles-multistream.xml.bz2 (3.2 GB) with def's test code from http://forum.nim-lang.org/t/897.

**Comment by Araq** [comment]
Hmm, what is this performance degradation? Any numbers?

**Comment by yglukhov** [comment]
defs sample. with realloc:
```
0.3655691146850586
0.3170061111450195
0.2910261154174805
0.2940878868103027
0.3394508361816406
0.2643229961395264
... etc the figures dont really change much til the end
```
with string.setLen:
```
4.021450042724609
3.268204927444458
3.252074003219604
2.922152042388916
2.973442077636719
3.500805139541626
3.987571001052856
4.06194806098938
3.978539943695068
# ... did not wait til the end
```

**Comment by Araq** [comment]
Ouch. That's pretty bad and we should look into that further at some point.

**Pull request merged**
