### PR TITLE
Add newlines

### PR DESCRIPTION
**Pull request by alehander42**
Adding newlines before nodes which are usually top level: const sections, methods, procs, macros, templates etc as discussed with Araq

### CODE REVIEW

**Comment by krux02** [comment]
any examples of the change?

**Comment by alehander42** [comment]
e.g. 

```
checker:
  ## 
  const
    A = 0
  method b:
    ..
```

is now rendered as

```
checker:
  ##
  
  const
    A = 0
  
  method ..
```

**Comment by alehander42** [comment]
basically its ensured now that there is an empty line before such constructs: however i am not sure if renderer doesnt add empty lines between them currently

**Comment by alehander42** [comment]
I'll add `needsEmptyLine` primitive which checks if something is not on top (i guess this happens in the errors in travis) or after another empty line and adds an empty line then

**Comment by krux02** [comment]
Generally speaking, I am OK for top level statements to have a new line before them. But this is a change we should better have a good reason to change something, nut just because of personal preference. Are there any objective advantages to this change?

**Comment by Araq** [comment]
Red tests, unclear benefit, no updates, closing.

**Pull request closed without merging**
