### PR TITLE
Enable Oid usage in hashtables [feature]

### PR DESCRIPTION
**Pull request by hiteshjasani**
Add `hash` function so we can use `Oid` in tables.

### CODE REVIEW

**Comment by Araq** [comment]
Commit message requires the ``[feature]`` tag.

**Comment by hiteshjasani** [comment]
Is changing the title to this pull request good enough or do I need to do another commit with  `[feature]` in it?

**Comment by narimiran** [comment]
> Is changing the title to this pull request good enough

It doesn't change the default commit message when we try to do merge, but it can/should be manually added by us when merging.

**Comment by Araq** [comment]
Unrelated CI failure, merging.

**Pull request merged**
