### PR TITLE
workaround bug in sharedtables.withValue to unblock frozen CI on OSX

### PR DESCRIPTION
**Pull request by ringabout**
With the help of @timotheecour , this PR corrects a wrong example.

Ref https://github.com/nim-lang/Nim/runs/2733501387

Debug report from @timotheecour 
> ^CTraceback (most recent call last)
/Users/timothee/git_clone/nim/Nim_devel/koch.nim(672) koch
/Users/timothee/git_clone/nim/Nim_devel/tools/kochdocs.nim(337) buildDocs
/Users/timothee/git_clone/nim/Nim_devel/tools/kochdocs.nim(322) buildDocsDir
/Users/timothee/git_clone/nim/Nim_devel/tools/kochdocs.nim(277) buildDoc
/Users/timothee/git_clone/nim/Nim_devel/tools/kochdocs.nim(214) mexec
/Users/timothee/git_clone/nim/Nim_devel/lib/pure/osproc.nim(391) execProcesses
SIGINT: Interrupted by Ctrl-C.
Traceback (most recent call last)
/Users/timothee/.cache/nim/sharedtables_d/runnableExamples/sharedtables_examples2.nim(22) sharedtables_examples2
/Users/timothee/git_clone/nim/Nim_devel/lib/pure/collections/sharedtables.nim(57) []=
SIGINT: Interrupted by Ctrl-C.
Error: execution of an external program failed: '/Users/timothee/.cache/nim/sharedtables_d/runnableExamples/sharedtables_group0_examples '

https://github.com/nim-lang/Nim/pull/18154 is the cause of CI failure.

Because the same lock is acquired twice in a row, and neither of them is released. So it causes dead lock.

### CODE REVIEW

**Comment by konsumlamm** [comment]
Maybe add a doc comment why this is necessary, because it seems unnecessary?

**Comment by Araq** [comment]
That indicates a severe problem with `withValue`'s implementation. It should be fixed instead.

**Comment by timotheecour** [comment]
> That indicates a severe problem with withValue's implementation. It should be fixed instead.

@Araq yes, but in the meantime, this PR unblocks broken nim CI (affecting all PRs), so we should IMO merge this now, and open an issue and fix `withValue` after (EDIT: https://github.com/nim-lang/Nim/issues/18176)

**Review by timotheecour — APPROVED** [review]
LGTM to unblock nim CI and other PRs but after that we should file a bug and fix the implementation of withValue (and then revert that diff in this example) (EDIT: https://github.com/nim-lang/Nim/issues/18176)

**Comment by timotheecour** [comment]
I've merged this to unblock majorly broken CI affecting all PRs, we can revert my merge if needed but in meantime this unbreaks things.

**Pull request merged**
