### PR TITLE
Add none[T]() as alias to none(T)

### PR DESCRIPTION
**Pull request by hlaaftana**
It's a direct alias in case there are PRs that change none(T), and deprecating or removing none(T) would be a bit of an off move

Could be used for using `none[T]` as a direct proc value instead of `proc: auto = none(T)`

### CODE REVIEW

**Comment by GULPF** [comment]
Does those examples work? I don't think Nim has that kind of type inference. E.g this doesn't compile:
```nim
var s: seq[int] = newSeq()
```

**Comment by hlaaftana** [comment]
Oh, you're right

**Comment by Araq** [comment]
Please add test cases.

**Comment by hlaaftana** [comment]
Added

**Pull request merged**
