### PR TITLE
Implemented basic macro expand functionality

### PR DESCRIPTION
**Pull request by yyoncho**
- it can handle single macro call or expand whole function/proc/etc and it

- In addition, I have altered the parser to provide the endInfo for the node.
The usefulness of the `endInfo` is not limited to the `expandMacro`
functionality but also it is useful for `ideOutline` functionality and I have
altered the ideOutline functionality to use `endInfo`. Note `endInfo` most of
the time is lost during the AST transformation thus in `nimsuggest.nim` I am
using freshly parsed tree to get the location information.

### CODE REVIEW

**Comment by Araq** [comment]
/nimsuggest/tests/tv3_ranges.nim does not work on some configurations.

**Comment by yyoncho** [comment]
> tv3_ranges

That is leftover (I cover it in tv3_outline.nim).

**Comment by yyoncho** [comment]
> > tv3_ranges
> 
> That is leftover (I cover it in tv3_outline.nim).

I deleted it and force pushed.

**Comment by yyoncho** [comment]
Friendly ping

**Comment by yyoncho** [comment]
@narimiran can you backport?

**Pull request merged**
