### PR TITLE
Fix #4275: Argument count not checked in importcpp

### LINKED ISSUE #4275: Argument count not checked: importcpp
This code crashes the compiler. 0.13.0 and devel. Both "nim cpp" and "nim c". It doesn't matter whether foo.h exists or not.
```nim
proc f() {.header: "foo.h", importcpp: "f(#)".}
f()
```
```
Traceback (most recent call last)
nim.nim(115)             nim
nim.nim(71)              handleCmdLine
main.nim(257)            mainCommand
main.nim(64)             commandCompileToC
modules.nim(227)         compileProject
modules.nim(172)         compileModule
passes.nim(203)          processModule
passes.nim(137)          processTopLevelStmt
cgen.nim(1220)           myProcess
ccgstmts.nim(1120)       genStmts
ccgexprs.nim(2048)       expr
ccgcalls.nim(529)        genCall
ccgcalls.nim(421)        genInfixCall
ccgcalls.nim(392)        genPatternCall
ccgcalls.nim(263)        genOtherArg
system.nim(2527)         sysFatal
Error: unhandled exception: index out of bounds [IndexError]
```
Easy to see the problem here. Not so easy in a large codebase when the compiler crashes before reporting any errors.

### PR DESCRIPTION
**Pull request by mbaulch**
The deleted line will mostly (if not always) crash when executed. Replace it with a localError; as specific as possible.

### CODE REVIEW

**Comment by Araq** [comment]
This fix seems wrong. genInfixCall also calls genOtherArg for which the index may be out of the type bounds because of ``varargs`` support. You need to add some index check in a different place.

**Comment by mbaulch** [comment]
I totally forgot about the varargs case. Will have another look. Thanks.

**Comment by Araq** [comment]
Ping. Any updates on this?

**Comment by mbaulch** [comment]
Sorry. Have been distracted with other work—in Nim, at least!

Thanks for the reminder. Having a look now. I can't see why it should be
too tricky.

**Comment by mbaulch** [comment]
Varargs is now supported, though the check still occurs at the call, not the definition.

The drawbacks I can see are: (1) slightly greater overhead due to repeated `notin` checks, (2) error is reported at callsite, which is _potentially_ misleading.

Is this okay for now, or should I find a way to check at the definition?

NB. Syncing was a bad idea. Sorry. Didn't realise it would fill this page with so much garbage! Still learning the infrastructure.

**Comment by dom96** [comment]
I think you're going to have to redo the PR, not sure how these commits got here.

**Pull request closed without merging**
