### PR TITLE
Make tests parallel  [WIP]

### PR DESCRIPTION
**Pull request by singularperturbation**
If Travis or other CI have multiple cores, then we should be able to use
those to run the tests (by category) in separate processes.

This is an experiment.

### CODE REVIEW

**Comment by singularperturbation** [comment]
Need to find a better workaround for SQLite - should have separate DBs / process and then merge?
Should also find a way to stream test output as tests are being run - use `awaitAny` and print results until finished?

**Comment by singularperturbation** [comment]
Travis doesn't like that I don't write anything out - need to find way of doing incremental output while the tests are completing.

**Comment by singularperturbation** [comment]
FWIW, this *does* seem to make the tests faster - measured ~ 26 minute build time on travis (with 2 cores) vs. ~44 minute build time on vanilla devel branch (as of c39e202 see [here](https://travis-ci.org/nim-lang/Nim/builds/261426041)).  This could be faster with a beefier instance with more cores.

Still need to;
  - Fix SQLite stuff
  - Make Appveyor use tester_parallel as well
  - Figure out why whitespace in between test chunks (tried to strip when doing `output.recv` but didn't work)

**Comment by Araq** [comment]
I think we can disable/remove the SQLite stuff, the dependency is also a bit annoying.

**Comment by TiberiumN** [comment]
Seems to be pretty fast for me (4-core i5 4460):
tests/testament/tester_parallel  268,56s user 25,25s system 213% cpu 2:17,90 total.

But I've seen a lot of exceptions raised because database is locked

**Comment by couven92** [comment]
As far as I can tell, we only use the DB for HTML/JSON generation right? I suggest that we just produce on-the-fly generated JSON, maybe with an array as root, and each test run overwriting the final `]` with a `,` to add a new test-run object.

Then we could rewrite `tests/testament/tester html` to simply generate HTML from the JSON instead of the DB. With pretty-HTML coming in #6058 this would separate each test run in their own tabpane.

#6058 is ready to go, but I think it better to merge it in after we have support for parallel test execution, just to make things easier for merging.

**Comment by singularperturbation** [comment]
I don't want to hold you up @couven92 - I probably won't get a chance to work on this until this weekend.

My strategy for dealing with SQLite was going to have the thread "workers" have testament record in one SQLite DB per worker and then merge them at the end.

**Comment by dom96** [comment]
> As far as I can tell, we only use the DB for HTML/JSON generation right? I suggest that we just produce on-the-fly generated JSON

Hehe. We need a Nim sqlite implementation to satisfy @Araq's love for sqlite :)

But yeah, disable it. It isn't used nowadays AFAIK. It was fairly useful when the build farm was running but I doubt that will come back any time soon.

**Comment by singularperturbation** [comment]
Sorry for the delay, I haven't had t

I did a little clean up of the way that the test_parallel program launches workers / waits for work.  I'm taking a look at how the JSON is currently generated and trying to figure out a way to combine the results for each 'worker'.

It might be easier to merge the results at the end (with / without SQLite) for creating the JSON, but I might be able to hook into `tester.addResult` to get this to output incrementally.

**Comment by dom96** [comment]
@singularperturbation No worries, thank you for your work so far :)

**Comment by Araq** [comment]
Tests now run in parallel and the tester doesn't use a database anymore.

**Pull request closed without merging**
