### PR TITLE
Add enum->set proc

### PR DESCRIPTION
**Pull request by ephja**
is `toSet` a good name?
I've been told that the system module is getting too big. Should I refactor?

### CODE REVIEW

**Comment by zielmicha** [comment]
What the function does is completly non-obvious from the name. I would vote against inclusion in `system.nim` - you can easily accomplish what it does using a macro.

Something like this:
```
macro setWithAllItemsBody(enumType: typed) =
  let r = newNimNode(nnkStmtList)
  for name in getType(enumType):
    r.add(quote do: result.incl `enumType`.`name`)
  return r
proc setWithAllItems[T](m: typedesc[T]): set[T] =
  setWithAllItemsBody(T)
```

**Comment by ephja** [comment]
@zielmicha What else can it mean?
Anyway, I do something similar in #5947. Is it possible to get the ordinal values that way? I dunno if it's necessary in order to provide feedback in case any of the values are too large.

**Comment by zielmicha** [comment]
`proc` with the same name could return empty set or maybe a set containing a single item (if it wouldn't take `typedesc` argument).

**Comment by ephja** [comment]
It's only necessary to implement an iterator that can handle holes in the compiler, right? But this was a nice exercise.

**Pull request closed without merging**
