### PR TITLE
Add `proc find` to `heapqueue`

### PR DESCRIPTION
**Pull request by c-blake**
https://github.com/nim-lang/Nim/issues/14617

### CODE REVIEW

**Comment by c-blake** [comment]
I think those failing `tioselectors` tests have nothing to do with this PR and it's probably fine to merge.  Let me know if otherwise.

**Comment by Araq** [comment]
Needs a ``.since`` annotation and a changelog entry.

**Comment by c-blake** [comment]
The 2 test failures remain about other things.  Anything else?

**Review by dom96 — APPROVED** [review]
LGTM.

**Pull request merged**
