### PR TITLE
WIP :fix #18583

### LINKED ISSUE #18583: Bug in `$` for collections
### Example
```nim
import std/deques

type
  Test = object

proc `$`(x: Test): string = ""

echo [Test(), Test()].toDeque
```

### Current Output
```
[]
```

### Expected Output
```
[, ]
```

### Possible Solution
The reason for this bug is that the `$` implementation for most collections checks `result > 1` to see wether or not the current element is the first element. This can be fixed by having a `firstElement` flag, like in [`collectionToString`](https://github.com/nim-lang/Nim/blob/5f7db652577523bdbb4e9b9157b4fb3bed25e01c/lib/system/dollars.nim#L134). Alternatively, `collectionToString` could be exported to be used by all the collection modules (and modified, so that it works).

### Additional Information
At least the following modules are affected by this (found by grepping for `result.len > 1`):
* `tables`
* `deques`
* `sets`
* `lists`
* `heapqueue`
* `critbits`
* `strtabs`
* `packedsets`

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-07-19
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 73ce40aaf71196faa08072216bd826a94b5d40b1
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by wanghenshui**
fix https://github.com/nim-lang/Nim/issues/18583

### CODE REVIEW

**Comment by konsumlamm** [comment]
Note that this doesn't fully fix the issue; `tables`, `critbits`, `strtabs` and `packedsets` are still affected.

**Comment by wanghenshui** [comment]
> Note that this doesn't fully fix the issue; `tables`, `critbits`, `strtabs` and `packedsets` are still affected.

ok, i'm trying figure it out

**Comment by c-blake** [comment]
I am not sure I agree that https://github.com/nim-lang/Nim/issues/18583 is really a "bug" to be fixed.  `{,}` looks pretty weird.  `{}` is how most people would spell "the empty set", for example, and tables should probably inherit that.  Same for `[]`.  Maybe this should be an RFC first to get more feedback?

**Comment by konsumlamm** [comment]
@c-blake I'm not sure what `{}` being the empty set has to do with this issue? The bug is that something may be printed as `{}` eventhough it isn't actually empty.

**Comment by c-blake** [comment]
@konsumlamm - Fair enough & apologies.  I withdraw my RFC suggestion.

Your "expected output" looking pretty weird combined with the `$`="" (that Araq already critiqued on the issue) threw me off.

FWIW, I would have written the bug report:
```Nim
when defined(ok):
  proc `$`(x: Test): string = "1"
else:
  proc `$`(x: Test): string = ""
var x: Deque[int]
echo x
echo [Test()].toDeque
echo [Test(), Test()].toDeque
```
where in the `-d:ok` branch you get
```
[]
[1]
[1, 1]
```
and otherwise you get `[]` for all 3 cases when it is only correct for the first. (But this is just what I think would have blocked my misunderstanding.)

**Comment by wanghenshui** [comment]
ok i'll leave it for RFC conclusion

**Comment by Araq** [comment]
Before we have an RFC, let's see if maybe we can agree on something here:

Assuming the string representation of T is empty then `[T(), T()]` should produce `[, ]`. Then the fix must be put behind a feature switch I guess for backwards compat but apart from that it's ok.

**Comment by konsumlamm** [comment]
> Then the fix must be put behind a feature switch I guess for backwards compat but apart from that it's ok.

Do you really wanna tell me that someone might rely on `$[Test(), Test()].toDeque` being `[]`? That behaviour was neither documented, nor does it make any sense whatsoever. Also note that `$` already works correctly for the builtin collection types (`seq`, `set`, etc.).

**Comment by c-blake** [comment]
If `$T == ""` then even with the proposed fix you get `[]` for both `collection.len==0` and `collection.len==1`, right?

Some (many?) might also call *that* still a bug (if maybe a lesser one?), the resolution probably being to forbid `$T==""`.  Alternatively, you could make there *always* be a trailing comma *except* for the empty collection { i.e. empty => `[]`, unary => `[,]`, binary=>`[,,]` }, but that definitely breaks back.compat -- and is ugly IMO.  A third resolution might be to use a special symbol (@, %, some unicode thing) for the empty collection so that it was rendered distinguishably from the unary collection.  (I am not sure, but this may cover all the choices?)

So, another "fix" might be to side-step choosing one of the above 2 alternates and just decide `$T==""` is simply unsupported, and document that somehow.

**Comment by Araq** [comment]
> If $T == "" then even with the proposed fix you get [] for both collection.len==0 and collection.len==1, right?

Huh, good point.

**Comment by Araq** [comment]
> Do you really wanna tell me that someone might rely on $[Test(), Test()].toDeque being []? That behaviour was neither documented, nor does it make any sense whatsoever. Also note that $ already works correctly for the builtin collection types (seq, set, etc.).

Well these things usually end up as unit tests, so yes, somebody might "rely" on it in this sense.

**Pull request closed without merging**
