### PR TITLE
Add reversed overload for array

### PR DESCRIPTION
**Pull request by Clyybber**

### CODE REVIEW

**Comment by Araq** [comment]
Why do we need this? And no, programming competitions are not use cases. ;-)

**Review by dom96 — APPROVED** [review]
Consistency seems like a good enough reason to have this ;)

Tests need to pass for merge though.

**Comment by Araq** [comment]
> Consistency seems like a good enough reason to have this

No, "consistency" is not a value in itself and a recipe for endless bloat.

**Comment by Araq** [comment]
Rejected, one is usually better off with ``countdown``.

**Pull request closed without merging**
