### PR TITLE
newStringOfCap now won't initialize all elements anymore

### PR DESCRIPTION
**Pull request by ringabout**

### CODE REVIEW

**Comment by arnetheduck** [comment]
if `newString` remains zero:ing, it seems like `newStringOfCap` also must zero else `setLen` will result in uninitialized bytes being exposed, no?

**Comment by arnetheduck** [comment]
ie `newStringOfCap` + `setLen` should be functionally equivalent to `newString` in terms of zeroing contents

**Comment by ringabout** [comment]
> if newString remains zero:ing, it seems like newStringOfCap also must zero else setLen will result in uninitialized bytes being exposed, no?

Yes, there seems to be only one case that should be covered for refc.

```nim
var x = ""
setLen(x, 10)
```
I had it fixed in https://github.com/nim-lang/Nim/pull/22562. I will include it in the following PRs.

**Comment by ringabout** [comment]
Actually, I didn't even touch refc. So this PR should be safe. Because in ARC/ORC, setLen will initialize every potential newly slot.

**Pull request merged**
