### PR TITLE
Add warning about log flushing. Related to #3269 and #3270

### PR DESCRIPTION
**Pull request by FedericoCeratto**

### CODE REVIEW

**Comment by yglukhov** [comment]
IMO it would be better to just always flush. That's what usually expected from logging.

**Comment by FedericoCeratto** [comment]
@yglukhov - see comments in #3270

**Comment by yglukhov** [comment]
Oh thats unfortunate :(. But maybe we could still appeal to @Araq? Here's my 2 cents. Standard API should certainly provide both a convenient and performant way to do a task, but when the choice has to be made, it should be in favor of convenience/idiot-proofness/usability/consistency to satisfy 99% users (maybe with some non-default optimizing options). Current decision went the opposite way. I've got a bit of programming experience but some time ago I wasted about an hour just to find that logging doesn't work as I intuitively assumed it to.

**Comment by FedericoCeratto** [comment]
> I wasted about an hour just to find that logging doesn't work as I intuitively assumed it to.

Same here. I've generated or parsed logs from a lot of languages and never seen libs that buffer logs indefinitely (and lose them on crash).

**Comment by dom96** [comment]
@Araq What potential problems do you foresee if we flush on every log? I guess you're worrying about performance?

I think opt-in is a good idea. As I've mentioned in the previous issues, we should introduce a ``BufferSettings`` enum.

**Comment by Araq** [comment]
> Same here. I've generated or parsed logs from a lot of languages and never seen libs that buffer logs indefinitely (and lose them on crash). 

That seems to suggest it should use ``addQuitProc`` and do some flushing in there. Not that it should perform no buffering out of the box. See this for example what others do:

https://www.grobmeier.de/log4j-2-performance-close-to-insane-20072013.html

**Comment by yglukhov** [comment]
`addQuitProc` doesn't help in case of crash. But my pain was different. I was "debugging" a deployed server and observed its syslog, and it was really frustrating to observe empty syslog on requests. So after I understood this logging "feature" I just added a "flushlogs" route that logs "Error: not actually an error :)".
As for your article. Note that "not flushing" is not the solution the article recommends. Logs still should flush as soon as they can, probably by means of message queues and background thread consumer/flusher. Given that currently noone cares about Nim logging performance I'd better focus on API consistency and usability, leaving performance questions until someone has mood to take care of them. As a quick and dirty solution we could introduce a not-flushing option, but again, it should not be the default.

**Comment by FedericoCeratto** [comment]
Various libraries/languages provide choices between logging everything immediately or flushing low-priority buffers frequently (usually within hundreds of milliseconds) using threads or other means. As discussed before, more advanced logging could be done in an external library.

Anyhow, in the short term, adding the warning would prevents some confusion for the users.

**Pull request merged**
