### PR TITLE
upcoming fixes

### LINKED ISSUE #5331: Cannot unregister/close AsyncEvent from within its handler
This was introduced by recent changes. It was possible to unregister/close AsyncEvent from its handler (which makes sense, similar to sockets) and now you get `Descriptor [N] is not registered in the queue!` raised by poll(). Sample:
```nim
import upcoming.asyncdispatch

let e = newAsyncEvent()
addEvent(e) do (fd: AsyncFD) -> bool:
  e.unregister()
  e.close()

e.setEvent()
poll()
```

/cc @cheatfate

### LINKED ISSUE #5332: Write event subscription is not removed from selector after connect() is completed in upcoming.asyncdispatch
This issue leads to poll() burning CPU and switching OS/user contexts for no reason. The sample below could be used to reproduce the issue. Tested on macOS that it works fine with current asyncdispatch and incorrectly with upcoming.
```nim
import upcoming.asyncdispatch
import nativesockets, os

proc setupServerSocket(hostname: string, port: Port): AsyncFD =
  let fd = newNativeSocket()
  setSockOptInt(fd, SOL_SOCKET, SO_REUSEADDR, 1)
  var aiList = getAddrInfo(hostname, port)
  if bindAddr(fd, aiList.ai_addr, aiList.ai_addrlen.Socklen) < 0'i32:
    freeAddrInfo(aiList)
    raiseOSError(osLastError())
  freeAddrInfo(aiList)
  if listen(fd) != 0:
    raiseOSError(osLastError())
  setBlocking(fd, false)
  result = fd.AsyncFD
  register(result)

const hostname = "localhost"
const port = Port(4812)

proc acceptTimes(serverFd: AsyncFD, count: int) {.async.} =
  var acc = newSeq[AsyncFD]()
  for i in 1..count:
    try:
      let clientFd = await serverFd.accept()
      acc.add(clientFd)
      echo "Accepted!"
    except:
      echo "Accept failed: ", getCurrentException().msg
  serverFd.closeSocket()
  for client in acc:
    client.closeSocket()

let clientFd = newAsyncNativeSocket()
asyncCheck setupServerSocket(hostname, port).acceptTimes(2)
waitFor clientFd.connect(hostname, port)

var i = 0
while true:
  echo "poll ", i
  inc i
  # the line below should "sleep" for 10 secs, but instead
  # immediately completes because of Write event coming to
  # the connected socket
  poll(10000)
```

/cc @cheatfate

### PR DESCRIPTION
**Pull request by cheatfate**
Fix #5331.
Fix #5332.
Added test case for #5331.

### CODE REVIEW

**Comment by endragor** [comment]
Could you please also add a test case for #5332? I think it could do something like this:
```nim
# first, do various operations that add/remove subscriptions in the selector,
# but such that there should be no subscriptions in the end.

# now ensure the poll doesn't complete immediately
let before = epochTime()
poll(15)
let diff = epochTime() - before
if diff < 0.010:
  raise newException(ValueError, "poll completed too fast")
```
I know it's not great to depend on real time, but I'm not sure if we can do better without exposing more from asyncdispatch. I think the subscription lifecycle is an important thing to be tested.

**Comment by cheatfate** [comment]
Tests based on time is not possible to run inside of VMs and containers, they fails in 50% of runs .

**Comment by cheatfate** [comment]
Also this test is very very condition specific. Sometimes you can get `connect` completed immediately (and bug not appears, as i saw this on FreeBSD11), and sometimes it never completed immediately (and bug appears, as i saw this on MacOS).

**Comment by dom96** [comment]
It looks like this was merged? How come it's still open?

**Comment by Araq** [comment]
Yeah github is strange sometimes.

**Pull request closed without merging**
