### PR TITLE
fix min/max for float numbers

### PR DESCRIPTION
**Pull request by krux02**
This PR makes min max on floating point number [IEEE](https://www.wikiwand.com/en/IEEE_754-2008_revision#/Clause_5:_Operations) complient. The behavior of min/max is specified to not propagete the ``NaN`` state when the other argument is a Number (the only operation where NaN does not automatically spread). Then min, max and also abs was only defined for `float64`, not for `float32`. This resulted in unnecessary implicit ``float32``/``float64`` conversions (costing performance). Also fixed (related issue: https://github.com/nim-lang/Nim/issues/12056#event-2587254393).

The magics ``mMinF64``, ``mMaxF64``, ``mAbsF64`` have been removed. The question was to either also introduce ``mMinF32``, ``mMaxF32``, ``mAbsF32`` or get rid of all of them at once. I decided to remove them all as I don't think they still provide us enough value to justify their complexity.

For the js code generator ``nimMin`` was used for ``mMinF64``. ``nimMin`` is only defiend for on integer arguments. A pretty dirty hack for the javascript code generator.

### CODE REVIEW

**Comment by Araq** [comment]
If you remove these magics that means that the new Nim cannot build older Nims. Which is already the case, but something to be aware of anyway.

**Comment by cooldome** [comment]
Latest IEEE standard came out this year and now min/max do propogate NaN
https://www.agner.org/optimize/blog/read.php?i=1012

**Comment by krux02** [comment]
Well I guess then it is not IEEE compliant. But it is still an improvement and at least it is symmetrical, matches the behavior of C++ and the unnecessary float conversion is fixed.

**Comment by bluenote10** [comment]
What @krux02 has implemented is much better from a practical perspective than the updated IEEE standard. Propagating NaNs in min/max is illogical, the "maximum number" of  `[1.0, 2.0, NaN]` is 2.0 and not `NaN`, because `NaN` is "not a number", so certainly not the "maximum number".

**Comment by Clyybber** [comment]
I'd say take whatever is faster.
@bluenote10 NaN is indicating some error, so  it should be propagated.

**Comment by bluenote10** [comment]
@Clyybber I never saw a benefit from NaN propagation in min/max. There are already dedicated functions to detect NaNs and it doesn't help much that min/max degenerate into yet another way to detect NaNs. To me it is much more common to be aware of missing numbers already and still need to find a min/max "number". For instance in Numpy, usage of `np.max` instead of `np.nanmax` is a quite common bug, because beginners don't expect NaN propagation and the majority use case is the opposite.

**Comment by krux02** [comment]
> I'd say take whatever is faster.

The fastest implementation is the asymmetric implementation that ignores the existence of NaN values.

**Pull request merged**
