### PR TITLE
fixed shr documentation

### PR DESCRIPTION
**Pull request by mjoud**
Changed apparent typo, to reflect intended behavior.

### CODE REVIEW

**Comment by dom96** [comment]
Increasing the indentation of the example should fix it.

Yeah, ``shr`` will fill with zeros for signed ints. If you could document it, that would be great.

**Comment by mjoud** [comment]
@dom96 Good to know, updated.

**Comment by dom96** [comment]
Could you also indent the example under the ``code-block``?

**Comment by mjoud** [comment]
Well, I've indented the code block a few times back and forth but without any effect on the generated doc. However, changing the `0b..` to `1b...` (which obviously makes no sense) will render the intended result. So I suppose this is a bug, will be reported separately.

**Comment by dom96** [comment]
I see. Thank you for investigating.

**Pull request merged**
