### PR TITLE
Don't consider concept types as non-complex during codegen

### LINKED ISSUE #7125: Compiler crash caused by codegen from concepts
```
type
  Thing = concept x
    x.hello is string
  Cat = object

proc hello(d: Cat): string = "Meow"

proc sayHello(c: Thing) = echo(c.hello)

var a: Thing = Cat()
a.sayHello()
```

This crashes on compilation with the following error:

> Error: execution of an external compiler program 'clang -c  -w  -I/usr/local/Cellar/nim/0.17.2/nim/lib -o /Users/rbreen/Dev/nim/test/nimcache/concepts.o /Users/rbreen/Dev/nim/test/nimcache/concepts.c' failed with exit code: 1
>
>/Users/rbreen/Dev/nim/test/nimcache/concepts.c:145:8: error: used type 'tyObject_Cat_cxAS31s7gVkqKcpYVzkF3Q' (aka 'struct tyObject_Cat_cxAS31s7gVkqKcpYVzkF3Q') where arithmetic or pointer type is required
        T1_ = (tyObject_Cat_cxAS31s7gVkqKcpYVzkF3Q)0;
              ^                                    ~
>/Users/rbreen/Dev/nim/test/nimcache/concepts.c:146:8: error: used type 'tyObject_Cat_cxAS31s7gVkqKcpYVzkF3Q' (aka 'struct tyObject_Cat_cxAS31s7gVkqKcpYVzkF3Q') where arithmetic or pointer type is required
        T1_ = (tyObject_Cat_cxAS31s7gVkqKcpYVzkF3Q)0;

It compiles correctly if I change one line to:

```
var a: Cat = Cat()
```

This was tested in Nim 0.17.2.

### PR DESCRIPTION
**Pull request by LemonBoy**
Fixes #7125

CC @zah since I'm not 100% sure this is sound for every case

### CODE REVIEW

**Comment by Araq** [comment]
Please add this test case to some existing concept based test. Travis and appveyor timeouts are common and to be avoided.

**Comment by slangmgh** [comment]
@LemonBoy @zah 

Is it the following code possible:
```nim
type
  ThingType = enum tyCat, tyDog
  Thing = concept x
    x.hello is string
  Cat = object
  Dog = object

proc makeThing(typ: ThingType): Thing =
  if typ == tyCat:
    Cat()
  elif typ == tyDog:
    Dog()
  else:
    raise newException(ValueError, "no such type")

proc hello(d: Dog): string = "Wang"

proc hello(d: Cat): string = "Meow"

proc sayHello(c: Thing) = echo(c.hello)

var a: Thing = makeThing(tyCat)
a.sayHello()

a = makeThing(tyDog)
a.sayHello()
```

I think it is not possible, but I wish it is possible, so we can use 'Concept' to replace the 'method'.

**Comment by zah** [comment]
@slangmgh, no, but something similar will be possible with the upcoming concept "VTable types".

The code will have to be changed to:

``` nim
proc makeThing(typ: ThingType): vtref Thing = # changed the return type to `vtref Thing`
  if typ == tyCat:
    new Cat # the objects have to be heap allocated
  elif typ == tyDog:
    new Dog # the objects have to be heap allocated
  else:
    raise newException(ValueError, "no such type")
```

**Comment by LemonBoy** [comment]
@Araq done.

This also fixes #6396, noice.

**Pull request merged**
