### PR TITLE
Update iup

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Update `iup` module from IUP `3.0` (Deprecated, year 2010) to IUP `3.30` (Latest, year 2020).
- Add 10 examples to the documentation.
- Changelog, `since`, style checked, examples with links and screenshots.
- Use `{.push.}` and `{.pop.}` for smaller code base DRY.
- Still a direct wrapper with just proc definitions, no logic to maintain, all names are same as IUP.

:)

### CODE REVIEW

**Comment by ringabout** [comment]
Is it better to contribute to this(Or you can also contribute to both)?
https://github.com/nim-lang/iup

from iup readme

> The wrapper was originally part of the standard library. This project was created to remove it from the standard library, update it to the latest version of IUP and integrate it with nimble.

Could iup be removed from stdlib?

**Comment by juancarlospaco** [comment]
@xflywind 
Can it be moved to Fusion instead ?.

**Comment by ringabout** [comment]
I don't know :) I think it could. And it is just my personal suggestion.
cc @araq @narimiran

**Comment by Araq** [comment]
It is in nim-lang/iup so please update it there.

**Pull request closed without merging**
