### PR TITLE
fix allocator corruption for large sizes

### PR DESCRIPTION
**Pull request by jcosborn**
This prevents fl from overflowing either from coalescing or just being in the largest bin.

### CODE REVIEW

**Comment by Araq** [comment]
Pure gold. :-)  Can we have a test case for this too?

**Comment by Araq** [comment]
You cannot coalesce huge blocks, they are returned back to the OS immediately and must not be merged into larger blocks.

**Comment by jcosborn** [comment]
It's not coalescing HugeChunk's, just large BigChunk's, but being careful to split them if they exceed MaxBigChunkSize.

**Comment by Araq** [comment]
Ok, my bad.

**Comment by Araq** [comment]
Unrelated test case failure. Ready to merge? Sure it's correct now? ;-)

**Comment by jcosborn** [comment]
Yes, please merge.  There may be room for improvement with the coalescing, but at least I think it won't crash.

**Pull request merged**
