### PR TITLE
Add drchaos, ssostrings, cowstrings to important packages

### PR DESCRIPTION
**Pull request by planetis-m**

### CODE REVIEW

**Comment by ringabout** [comment]
FAIL: [9/43] drchaos c                                                    ( 4.58 sec)

>   ld: file not found: /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/lib/darwin/libclang_rt.fuzzer_osx.a

**Comment by planetis-m** [comment]
ready

**Comment by planetis-m** [comment]
The =dup PR broke ssostrings. NVM missing =dup hook.

**Comment by Araq** [comment]
Merging under the assumption that these tests don't take long, but these are not "Important packages" as they are not widely used (yet) afaict.

**Comment by planetis-m** [comment]
No they don't take long, regardless of usage these packages can help you track regressions as they use destructors.

**Pull request merged**
