### PR TITLE
Add deques.peekFirst/Last(var Deque[T]) -> var T

### PR DESCRIPTION
**Pull request by metagn**

### CODE REVIEW

**Comment by Araq** [comment]
Please add a ``.since`` annotation and it's ready to go.

**Comment by metagn** [comment]
Done

**Comment by metagn** [comment]
Actually done this time

**Comment by Clyybber** [comment]
The pragma way should work too. The issue here is something else..

**Comment by metagn** [comment]
updated for 1.3, pragma way works now

**Pull request merged**
