### PR TITLE
This PR resolves Issue 3477

### PR DESCRIPTION
**Pull request by c-blake**
Somehow in porting this not easy to read optimized editDistance code from the python-levenshtein package, the linear scan for the singleton a[] was never right/complete.  That case being eliminated is important to the correctness of the later unusual/hard-to-follow corner-cutting optimization.  This PR corrects it.  An alternative fix would be a fix inside the loop, of course, using b[s+j].

### CODE REVIEW

**Comment by kirbyfan64** [comment]
So...many...merges...

**Comment by c-blake** [comment]
Yeah, yeah.  I just auto-merge the main devel repo most mornings.  They are all just trivial pulls except for the last one, though.  Really, it's literally a 1-line patch (few characters, really).

**Comment by Varriount** [comment]
Could you perhaps squash the commits? (Also, rebasing would prevent this)

**Comment by c-blake** [comment]
Fine, fine.  Ignore this PR.  Sorry for the messy history.  It is superceded by the simpler https://github.com/nim-lang/Nim/pull/3563   Continue any comments there, please.

**Pull request closed without merging**
