### PR TITLE
Remove deprecated tables.allValues

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Remove deprecated `tables.allValues`.

### CODE REVIEW

**Comment by metagn** [comment]
If we didn't remove `add` this should be done when that happens

**Comment by Araq** [comment]
@arnetheduck why the thumbs down? Dedeprecate it instead? Keep it around regardless?

**Comment by arnetheduck** [comment]
* remove something deprecated as part of an effort to simplify the code or bring a concrete benefit, ie performance improvement: :+1: 
* remove something blindly because it says "deprecated" and thus break code that depended on it, without any actual benefit: :-1:

no particular opinion on whether it should be dedeprecated or not - it's not the biggest problem with the tables module in general - ie single-value tables are easier to reason about, sure, but then the table should also be reflect that 100% in both implementation, documentation and so on - if this were part of _that_ overhaul and there was a clear plan, it would make sense to remove it.

**Comment by metagn** [comment]
We don't even have a MultiTable or something yet as an alternative to `add`. Don't know of any nimble package with it either.

**Comment by Araq** [comment]
There is @c-blake's tables that do support it iirc and it's generally the better thought-out library. :-)

**Comment by arnetheduck** [comment]
> We don't even have a MultiTable or something yet as an alternative to add. Don't know of any nimble package with it either.

`Table[key, seq[Value]]` and two helper templates for add and iteration

**Comment by arnetheduck** [comment]
ie multitable makes sense iff the implementation is optimized for it (as hash tables tend to be, because they "naturally" support it) - but then *everything* about the Table module should be geared towards multi-tables - ie the api, docs, implementation and so on. It's the in-between that is problematic.

**Comment by Araq** [comment]
> It's the in-between that is problematic.

We did remove the in-between. `add` is deprecated too for the same reason.

**Comment by c-blake** [comment]
As to this PR, removal of `add` & `allValues` should definitely be synchronized.  This exposes a very minor weakness in Nim's deprecation system - some way outside the raw string of creating a dependency between otherwise independent deprecations to help people sync (but deprecation is rare and should be thoughtful anyhow..).

As to deprecation, removal & general optimization more generally..it's a large topic that has been discussed before in several places - multiple GH threads & forum threads.  I've always felt like this was always "only a documentation bug".  The top of the module does not explain the data structure is a multimap/multitable.  So, people brought/bring assumptions from stdlibs of other prog.langs.  The docs also do not explain that the strategy is only efficient for "few" dups.

It is a nice little optimization, analogous to "small string optimization" SSO or "inline strings" -- embedding the `seq`.  Here how "few" is overflowed is more gradual not discrete like "8 bytes" and so maybe more hazardous.  I've since seen at least a few real code applications of such "few dups" case (my hldiff, http headers, and something else I forget at the moment)..at least the hldiff one saw notable efficiency improvement vs. a `Table[key,seq[val]]`.  My vote has always been to de-deprecate and fix the docs.

That said, feeling I was being out-voted was what led to the module @Araq refers to - https://github.com/c-blake/adix/blob/master/adix/lptabz.nim. That module has quite a few diffs - providing both multiset & multimap in one module via generic parameter switching, enabling Robin-Hood re-org and many other controllable "knobs" like hash code saving|not based on user direction, auto-resize based on a direct search depth measurement (not "load factor + its statistical model"), which doubles as an easy way to detect DOS {and maybe salt hashes} and implement RH, and a Python-like compact, insertion-ordered mode, an `editOrInit` template, and maybe several other things I'm forgetting.  It is not possible to eliminate fully the "2nd edge" to the sword of giving users knobs - they need to learn them, and I doubt I achieved perfection in either the knob set or how to twist them, to strain the metaphor.

Forcing people to learn package managers & build systems is a friction when first encountering languages (above & beyond "learn the stdlib"). "Performance" is often a kind of "advertising hook".  So, but for Nim-core not wanting to maintain it, it would not be crazy to make `lptabz` more autonomous from `adix/` and include it in the stdlib.  Were there a collective will, I'd be happy to co-assign copyright/whatever, but it smells like maybe too big a move just pre-2.0.

**Comment by arnetheduck** [comment]
> build systems is a friction when first encountering languages

this is friction only if you make it friction - ie when the tooling is adequate and the documentation integrates the pm in the process (with appropriate curation), it's just a natural first-class citizen of language use and primes the user for the more flexible world that awaits them.

**Pull request closed without merging**
