### PR TITLE
Added zip macro

### PR DESCRIPTION
**Pull request by b3liever**

### CODE REVIEW

**Comment by b3liever** [comment]
runnableExambles fails to compile because the generated file is wrong:
```
...
for (x, y) = in zip(a, b, c):
  res.add (x, y, z)
...
```
This is before my macro is run and all tests run normally.

**Comment by Araq** [comment]
This is useful but we need to decide how to grow the stdlib.

**Comment by b3liever** [comment]
Until it is figured repository is [here](https://github.com/b3liever/looper)

**Comment by krux02** [comment]
As far as I can tell, it doesn't solve the problem of zipping two iterators. For everything else I would actually prefer to have simple overloads of the ``zip`` iterator. Yes it isn't generic for an arbitrary amount of arguments, but it is much simpler and won't cause unknown problems.

```nim
iterator zip[T1](arg1: openarray[T1]): (T1,) =
  var i = 0
  let N = arg1.len
  while i < N:
    yield (arg1[i],)
    inc i

iterator zip[T1,T2](arg1: openarray[T1], arg2: openarray[T2]): (T1,T2) =
  var i = 0
  let N = min(arg1.len, arg2.len)
  while i < N:
    yield (arg1[i], arg2[i])
    inc i

iterator zip[T1,T2,T3](arg1: openarray[T1], arg2: openarray[T2], arg3: openarray[T3]): (T1,T2,T3) =
  var i = 0
  let N = min(min(arg1.len, arg2.len), arg3.len)
  while i < N:
    yield (arg1[i], arg2[i], arg3[i])
    inc i

iterator zip[T1,T2,T3,T4](arg1: openarray[T1], arg2: openarray[T2], arg3: openarray[T3], arg4: openarray[T4]): (T1,T2,T3, T4) =
  var i = 0
  let N = min(min(arg1.len, arg2.len), min(arg3.len, arg4.len))
  while i < N:
    yield (arg1[i], arg2[i], arg3[i], arg4[i])
    inc i
```

**Comment by Araq** [comment]
Available as a Nimble package, good enough.

**Pull request closed without merging**
