### PR TITLE
Fix nimsuggest/#117

### LINKED ISSUE #117: Nimsuggest crashes when run without a backend specified
Happens on [this file](https://github.com/liquid600pgm/rapid/blob/1a819aafa4424177da127de1b42dc4a0b705f57d/tests/tchipmunk.nim), I haven't been able to reproduce it on a smaller example but that shouldn't matter.

Since Nim 1.4 nimsuggest hits an assertion when run like this:
```
❯ nimsuggest tests/tchipmunk.nim
Hint: used config file '/home/daknus/.choosenim/toolchains/nim-1.4.0/config/nim.cfg' [Conf]
Hint: used config file '/home/daknus/.choosenim/toolchains/nim-1.4.0/config/config.nims' [Conf]
Hint: used config file '/home/daknus/.config/nim/nim.cfg' [Conf]
Hint: used config file '/home/daknus/.config/nim/config.nims' [Conf]
Hint: used config file '/home/daknus/Coding/Nim/rapid/tests/config.nims' [Conf]
fatal.nim(49)            sysFatal
Error: unhandled exception: extccomp.nim(631, 31) `false`  [AssertionDefect]
```

It doesn't crash however when the backend is specified explicitly:
```
❯ nimsuggest -b:c tests/tchipmunk.nim
Hint: used config file '/home/daknus/.choosenim/toolchains/nim-1.4.0/config/nim.cfg' [Conf]
Hint: used config file '/home/daknus/.choosenim/toolchains/nim-1.4.0/config/config.nims' [Conf]
Hint: used config file '/home/daknus/.config/nim/nim.cfg' [Conf]
Hint: used config file '/home/daknus/.config/nim/config.nims' [Conf]
Hint: used config file '/home/daknus/Coding/Nim/rapid/tests/config.nims' [Conf]
usage: sug|con|def|use|dus|chk|mod|highlight|outline|known|project file.nim[;dirtyfile.nim]:line:col
type 'quit' to quit
type 'debug' to toggle debug mode on/off
type 'terse' to toggle terse mode on/off
> 
```
And also doesn't crash on Nim 1.2.6.

My hunch is that the compiler itself initializes the backend to C by default, but not nimsuggest, hence the assertion is hit because the default backend is `backendInvalid`.

### PR DESCRIPTION
**Pull request by Clyybber**
Fixes https://github.com/nim-lang/nimsuggest/issues/117

### CODE REVIEW

**Comment by alaviss** [comment]
Should add `[backport:1.4]` if this is accepted.

**Comment by alaviss** [comment]
Looks like the `--backend` switch triggers some magic like defining the symbols corresponding to the backend:

https://github.com/nim-lang/Nim/blob/d66e274e1ac8e86266151ad0c48f7705b3bd1582/compiler/main.nim#L178-L201

And only the main compiler has it... We should move some of this over to the compiler library.

**Comment by timotheecour** [comment]
hard to pinpoint where error started without git bisect but this commit also seems relevant: https://github.com/nim-lang/Nim/pull/15549

**Comment by Clyybber** [comment]
Error disappeared after clearing nimcache, going to close this for now then.

**Comment by Clyybber** [comment]
@timotheecour Its caused by this change https://github.com/nim-lang/Nim/commit/9502e39b634eea8e04f07ddc110b466387f42322#diff-2179cfe66f0e3b26b6475c540e7af193fcaef3ccad352b45f43ecb488e99cc8bL629, although arguably we could/should? prevent the call to `externalFileChanged` without a backend specified in the first place, but that is preexisting behaviour, improving that counts as an optimization.

**Comment by Clyybber** [comment]
@narimiran Should be backported to 1.4, LMK if I should make a PR for the 1.4 branch

**Pull request merged**
