### PR TITLE
Fix `getAppFilename` exception handling

### PR DESCRIPTION
**Pull request by arnetheduck**
avoid platform-dependendent error handling strategies

### CODE REVIEW

**Comment by Araq** [comment]
I'd rather write down explicitly that getAppFilename can raise OSError, regardless of the platform.

**Comment by arnetheduck** [comment]
> I'd rather write down explicitly that getAppFilename can raise OSError, regardless of the platform.

this would be a significant regression on most platforms since it introduces a new exception into their working applications - removing the exception however is a non-breaking change (assuming it ever worked on some platforms) - ie it would mean that there are two ways of reporting errors: empty string _or_ exception and it's kind of random which one is chosen - code that uses `getAppFilename` would thus have to write two error handling control flows which seems like a poor outcome.

**Comment by arnetheduck** [comment]
basically, if you look at the getAppFilename code, it already sets the string to empty in _most_ erroring control flow branches .. as usual with exceptions, the author(s) of the current version likely had no clue that some of the called functions can raise while others don't.

**Comment by arnetheduck** [comment]
mac ci unrelated

**Comment by Araq** [comment]
> code that uses getAppFilename would thus have to write two error handling control flows which seems like a poor outcome.

Correct, it should not return the empty string.

**Comment by arnetheduck** [comment]
> Correct, it should not return the empty string.

but it does for the vast majority of errors, and does so explicitly with comments saying it's the way to return errors - raising a new exception is a breaking change in that world.

We can do a `getAppFilename2` that always raises and leave `getAppFilename` to not raise (which is a convenient behavior anyway..)

**Comment by juancarlospaco** [comment]
Overload that uses `Option`.

**Comment by Araq** [comment]
You're right.

**Pull request merged**
