### PR TITLE
Make rstgen work with gcsafe

### PR DESCRIPTION
**Pull request by ghost**
Before this change, this code would fail to compile with `--threads:on`:

```nim
import packages/docutils/[rstgen, rst]
 
proc documentToHtml*(doc: string, isMarkdown: bool = false): string {.gcsafe.} =
  var options = {roSupportMarkdown}
  if isMarkdown:
    options.incl roPreferMarkdown
  result = rstToHtml(doc, options, defaultConfig())
```

I'm not 100% sure if it's a bug in the compiler or it's just because the forward declared proc (`renderRstToOut` in this case) is used in a proc (`renderAux`) that is then used in the actual implementation of that (`renderRstToOut`) proc.

Error before this change:
```
/home/dian/Stuff/nim/lib/packages/docutils/rstgen.nim(1214, 6) Warning: 'renderRstToOut' is not GC-safe as it calls 'renderAux' [GcUnsafe2]
/home/dian/Stuff/nim/lib/packages/docutils/rstgen.nim(1579, 6) Warning: 'rstToHtml' is not GC-safe as it calls 'renderRstToOut' [GcUnsafe2]
/mnt/d/Projects/NimExperiments/test/tta.nim(4, 6) Error: 'documentToHtml' is not GC-safe as it calls 'rstToHtml'
```

### CODE REVIEW

**Comment by ghost** [comment]
Looks like some CI errors are related

**Comment by ghost** [comment]
Seems like this won't really work in all cases because RstGenerator has a `onTestSnippet` which can potentially be gc unsafe :( Would it be okay to make `onTestSnippet` gcsafe? It seems to only be used in two places in the compiler, but it'll be a potential breaking change (if someone did use onTestChange)

**Comment by ghost** [comment]
It kinda *does* work if I mark the `onTestSnippet` as `{.gcsafe.}` and also mark all 3 anonymous procs where the compiler uses it as `{.gcsafe.}`, but then when you compile the compiler there are a lot of warnings about them actually not being gcsafe. Is it worth adding this to the PR or it won't be accepted?

This is the additional diff:
```diff
diff --git a/compiler/docgen.nim b/compiler/docgen.nim
index ecf98d0b6..e54a111bc 100644
--- a/compiler/docgen.nim
+++ b/compiler/docgen.nim
@@ -313,7 +313,7 @@ proc newDocumentor*(filename: AbsoluteFile; cache: IdentCache; conf: ConfigRef,
   result.jEntriesFinal = newJArray()
   initStrTable result.types
   result.onTestSnippet =
-    proc (gen: var RstGenerator; filename, cmd: string; status: int; content: string) =
+    proc (gen: var RstGenerator; filename, cmd: string; status: int; content: string) {.gcsafe.} =
       if conf.docCmd == docCmdSkip: return
       inc(gen.id)
       var d = (ptr TDocumentor)(addr gen)
@@ -1651,7 +1651,7 @@ proc commandJson*(cache: IdentCache, conf: ConfigRef) =
   if ast == nil: return
   var d = newDocumentor(conf.projectFull, cache, conf)
   d.onTestSnippet = proc (d: var RstGenerator; filename, cmd: string;
-                          status: int; content: string) =
+                          status: int; content: string) {.gcsafe.} =
     localError(conf, newLineInfo(conf, AbsoluteFile d.filename, -1, -1),
                warnUser, "the ':test:' attribute is not supported by this backend")
   d.hasToc = true
@@ -1675,7 +1675,7 @@ proc commandTags*(cache: IdentCache, conf: ConfigRef) =
   if ast == nil: return
   var d = newDocumentor(conf.projectFull, cache, conf)
   d.onTestSnippet = proc (d: var RstGenerator; filename, cmd: string;
-                          status: int; content: string) =
+                          status: int; content: string) {.gcsafe.} =
     localError(conf, newLineInfo(conf, AbsoluteFile d.filename, -1, -1),
                warnUser, "the ':test:' attribute is not supported by this backend")
   d.hasToc = true
diff --git a/lib/packages/docutils/rstgen.nim b/lib/packages/docutils/rstgen.nim
index c6e26aa4d..a8a164ece 100644
--- a/lib/packages/docutils/rstgen.nim
+++ b/lib/packages/docutils/rstgen.nim
@@ -87,7 +87,7 @@ type
     ## for hyperlinks. See renderIndexTerm proc for details.
     id*: int               ## A counter useful for generating IDs.
     onTestSnippet*: proc (d: var RstGenerator; filename, cmd: string; status: int;
-                          content: string)
+                          content: string) {.gcsafe.}
     escMode*: EscapeMode
     curQuotationDepth: int
 ```

Additional warnings (they make sense, since the procs I marked as gcsafe aren't actually gcsafe):
```
/home/dian/Stuff/nim/compiler/msgs.nim(357, 7) Warning: 'liMessage' is not GC-safe as it performs an indirect call here [GcUnsafe2]
/home/dian/Stuff/nim/compiler/docgen.nim(316, 5) Warning: ':anonymous' is not GC-safe as it calls 'liMessage' [GcUnsafe2]
/home/dian/Stuff/nim/compiler/ropes.nim(114, 6) Warning: 'insertInCache' is not GC-safe as it accesses 'cache' which is a global using GC'ed memory [GcUnsafe2]
/home/dian/Stuff/nim/compiler/ropes.nim(126, 6) Warning: 'rope' is not GC-safe as it calls 'insertInCache' [GcUnsafe2]
/home/dian/Stuff/nim/compiler/msgs.nim(45, 6) Warning: 'makeCString' is not GC-safe as it calls 'rope' [GcUnsafe2]
/home/dian/Stuff/nim/compiler/msgs.nim(59, 6) Warning: 'newFileInfo' is not GC-safe as it calls 'makeCString' [GcUnsafe2]
/home/dian/Stuff/nim/compiler/msgs.nim(97, 6) Warning: 'fileInfoIdx' is not GC-safe as it calls 'newFileInfo' [GcUnsafe2]
/home/dian/Stuff/nim/compiler/msgs.nim(126, 6) Warning: 'fileInfoIdx' is not GC-safe as it calls 'fileInfoIdx' [GcUnsafe2]
/home/dian/Stuff/nim/compiler/msgs.nim(141, 6) Warning: 'newLineInfo' is not GC-safe as it calls 'fileInfoIdx' [GcUnsafe2]
/home/dian/Stuff/nim/compiler/docgen.nim(1653, 21) Warning: ':anonymous' is not GC-safe as it calls 'newLineInfo' [GcUnsafe2]
/home/dian/Stuff/nim/compiler/ropes.nim(114, 6) Warning: 'insertInCache' is not GC-safe as it accesses 'cache' which is a global using GC'ed memory [GcUnsafe2]
/home/dian/Stuff/nim/compiler/ropes.nim(126, 6) Warning: 'rope' is not GC-safe as it calls 'insertInCache' [GcUnsafe2]
/home/dian/Stuff/nim/compiler/msgs.nim(45, 6) Warning: 'makeCString' is not GC-safe as it calls 'rope' [GcUnsafe2]
/home/dian/Stuff/nim/compiler/msgs.nim(59, 6) Warning: 'newFileInfo' is not GC-safe as it calls 'makeCString' [GcUnsafe2]
/home/dian/Stuff/nim/compiler/msgs.nim(97, 6) Warning: 'fileInfoIdx' is not GC-safe as it calls 'newFileInfo' [GcUnsafe2]
/home/dian/Stuff/nim/compiler/msgs.nim(126, 6) Warning: 'fileInfoIdx' is not GC-safe as it calls 'fileInfoIdx' [GcUnsafe2]
/home/dian/Stuff/nim/compiler/msgs.nim(141, 6) Warning: 'newLineInfo' is not GC-safe as it calls 'fileInfoIdx' [GcUnsafe2]
/home/dian/Stuff/nim/compiler/docgen.nim(1677, 21) Warning: ':anonymous' is not GC-safe as it calls 'newLineInfo' [GcUnsafe2]
```

**Comment by Araq** [comment]
More `.gcsafe` annotations are fine as long as this is not backported to the 1.6.x line.

**Comment by Araq** [comment]
Ping @Yardanico, anything left to do here?

**Comment by ghost** [comment]
@Araq no, it's basically done, the original snippet from the PR now works fine. But now anyone who wishes to overload that proc will have to mark it as `gcsafe`, and, as I showed, the compiler bootstrap will show quite a lot of GcUnsafe2 warnings because the procs that I've marked as `gcsafe` in the compiler aren't actually gcsafe.

**Comment by konsumlamm** [comment]
What even is the point of `gcsafe` if we're marking procs that aren't `gcsafe` as `gcsafe` all the time?

**Comment by Araq** [comment]
> What even is the point of gcsafe if we're marking procs that aren't gcsafe as gcsafe all the time?

There is none.

**Comment by ringabout** [comment]
Succeeded by https://github.com/nim-lang/Nim/pull/20534

**Pull request closed without merging**
