### PR TITLE
extend findExe to find cmd and bat 

### PR DESCRIPTION
**Pull request by Tormund**
Extend findExe to find windows script.
Priority: exe -> bat -> cmd.

```
import os

echo "findExe ", findExe("emcc")     
echo "findExe ", findExe("rodasset")
echo "findExe ", findExe("gcc")        

```
C:\Program Files\Emscripten\emscripten\1.35.0\emcc.bat
C:\Users\tormund\.nimble\bin\rodasset.cmd
D:\MinGW\bin\gcc.exe

### CODE REVIEW

**Comment by dom96** [comment]
I'm not sure whether this is a good idea. The procedure is called ``findExe``.

**Comment by dom96** [comment]
Perhaps a procedure named ``findInPath`` which takes a string and a list of extensions would be more appropriate.

**Comment by yglukhov** [comment]
@dom96, following your logic, should not it always fail on unix, because unix doesn't have any exes? ;)

**Comment by dom96** [comment]
Good point. But where do we draw the line? Should we look for .py and .sh files on Unix?

**Comment by dom96** [comment]
To me ``findExe`` means find files with the OS-native executable extension (i.e. files with an extension of ``os.ExeExt``).

**Comment by yglukhov** [comment]
IMHO, for unix that is pretty straightforward. The path is "executable" only if it has +x flag. On windows given that you have `a.exe`, `b.bat`, `c.cmd`, you can execute any of those files **without providing extension**. All of them will work if you type `a`, `b` or `c` respectively. For me that means a real platform-blessed executable. Also there's currently an ironic fact that `findExe` doesnt work with nim ecosystem because nimble installs cmd files and not exes.

**Comment by jibal** [comment]
"exe" is short for "executable" ... it isn't a literal file extension. The documentation says (in broken English) that " On DOS-like platforms" (an unnecessary restriction), " the ExeExt file extension" is appended to the file name if it doesn't have an extension. The documentation for ExeExt says "The file extension of native executables. For example: "" for POSIX, "exe" on Windows. " The problem here is that ExtExt is a single string ... it should be a list of extensions, and findExe should try each one in turn.

In any case, not finding .bat or .cmd files is just wrong. If findExe isn't going to be the name of the function that finds an arbitrary Windows executable, then it should be deprecated and replaced with whatever function does. But I think findExe is fine; any program surprised that the extension isn't .exe is broken ... it shouldn't count on a specific extension, which is platform-specific.

**Comment by Araq** [comment]
> The problem here is that ExtExt is misdesigned.

No, it's not. You can exec binary executables, you cannot exec shell scripts in any kind of sense. You can exec a "shell binary" (sh) with the given script but that then depends on your machine setup. For example, I can have a "foo.py" with exec rights on Unix but without Python installed and thus cannot exec foo.py at all!

**Comment by jibal** [comment]
"No, it's not. You can exec binary executables, you cannot exec shell scripts in any kind of sense. "

First, this is simply false. The Linux kernel executes scripts containing a #! line by executing the interpreter and passing the script as input. And Windows executes .bat files similarly.

Second, even if there were some reason not to execute .bat files, ExeExts on Windows should contain both "exe" and "cmd", which are both binary formats (not that there's anything magical about binary formats when it comes to execution), and it should be empty on Linux. I never suggested putting "sh" or  "py" in ExeExts.

"For example, I can have a "foo.py" with exec rights on Unix but without Python installed and thus cannot exec foo.py at all!"

And a binary can be missing a magic number or have one for the wrong CPU and it won't execute, in a very similar fashion. Binary formats aren't magical so matter how many exclamation points you use.

Anyway, I didn't really expect my good ideas to be taken up. But the result will be that Nim users will either roll their own equivalent to findExe that correctly handles the various sorts of Windows programs (exe, cmd, and bat), as other high quality Windows programs do, or they will use the Nim standard version and subject their users to its limitations.

**Comment by Araq** [comment]
Whatever man, continue to live in your world where CPUs can run text files, I don't feel like debunking your points.

**Comment by Araq** [comment]
Back to the topic: I think the idea behind the PR is good and findExe should deal with .exe, .bat, .cmd via an optional parameter "supported extensions".

**Comment by jibal** [comment]
"Whatever man, continue to live in your world where CPUs can run text files, I don't feel like debunking your points."

Of course that's not what I said, "man".  Your idea of "debunking" seems to be to invent a claim that no one made and then ridicule it. An *OS* can run text files, and it does so by invoking an interpreter. For that matter, even binary "executables" are processed by the OS, not the CPU directly. The OS has to read the file from disk, interpret the header, lay out pages in memory, handle shared library references, zero BSS pages, initialize the IP, and field system calls. Regardless of the format of the file, the end result is data and instructions in memory ... it isn't essential whether the instructions came out of the file referenced by the string returned by findExe, or out of an interpreter that is referenced by that file ... and I think you know that. Certainly everyone else does.

**Comment by dom96** [comment]
> Back to the topic: I think the idea behind the PR is good and findExe should deal with .exe, .bat, .cmd via an optional parameter "supported extensions".

I will repeat what I said, such a parameter belongs in a new ``findInPath`` procedure.  I don't want people to start using ``findExe("foo", [".txt"])``.

**Comment by Tormund** [comment]
ExeExts - list of supported extensions, and now we can path custom list as optional parameter in findExe.
For example:
echo findExe("emcc", extensions = @["py", ""])
echo findExe("emcc")

**Comment by Araq** [comment]
> Of course that's not what I said, "man". Your idea of "debunking" seems to be to invent a claim that no one made and then ridicule it. 

An OS cannot "run" text files and the provided shebang mechanism is very different from running an ELF binary. You seem to argue that it's a great Unix abstraction, I argue it's just as broken as everything else and you only need to run "top" or OSX's process manager to see it's nothing more than a hack.

More to the point, if my program looks for "gcc.exe" then I am not necessarily happy with finding a "gcc.bat" script somewhere in my PATH and to assume it does the same as "gcc.exe". ;-)

**Comment by Araq** [comment]
> I will repeat what I said, such a parameter belongs in a new findInPath procedure. I don't want people to start using findExe("foo", [".txt"]).

Well but it uses the PATH environment variable which contains paths to executables, so the chances are slim people will use it to find 'txt' files. I think 'findExe' is still a perfectly fine name for this.

**Comment by dom96** [comment]
> > I will repeat what I said, such a parameter belongs in a new findInPath procedure. I don't want people to start using findExe("foo", [".txt"]).

> Well but it uses the PATH environment variable which contains paths to executables, so the chances are slim people will use it to find 'txt' files. I think 'findExe' is still a perfectly fine name for this.

The PATH environment variable is also used to find DLLs for example, and who knows what else. I don't think DLLs can be considered executables.

IMO we should create a ``findInPath`` proc, and alias ``findExe(name)`` to ``findInPath(name, [ExeExt])``.

**Comment by jibal** [comment]
"An OS cannot "run" text files"

You keep saying this, but it is simply wrong ... or rather, it is only made right by tendentiously insisting on a definition of "run" narrowed just to make you right. The fact is that you can pass the path of a shebang script to execv and it will **run** it. All abstractions are leaky, and the fact that /proc shows the interpreter running doesn't mean that shebang is "broken"; that's absurd. But this mini-rant of yours against shebang and the running of scripts totally misses the point ... if there is a shebang script in your path on Linux, all versions of findExe will find it. There is no distinction between shebang scripts and executables on Linux when it comes to path search, and it would take invoking the <file> command to detect the difference. No one expects to run foo.py or foo.sh on Linux by just typing "foo".

"More to the point, if my program looks for "gcc.exe" then I am not necessarily happy with finding a "gcc.bat" script somewhere in my PATH and to assume it does the same as "gcc.exe". ;-)"

If I ask to run gcc on Windows, and I have gcc.bat in my PATH before gcc.exe, then I would expect gcc.bat to run. If not, then it's impossible to create scripts that wrap commands on Windows -- a common and easy thing to do on Linux, which wisely doesn't distinguish scripts from binaries by name. But others may have other expectations, so "not necessarily" is quite right. But my suggestion of ExeExts solves that, because it provides one central place where that decision is made -- DRY. Requiring every call of findExe to explicitly specify Windows-specific extensions is a formula for inconsistency.

"The PATH environment variable is also used to find DLLs for example, and who knows what else. I don't think DLLs can be considered executables."

Then don't put "dll" into your list of extensions (however it is specified). You're working hard to create a problem where there isn't one.

I've said my bit and am unsubscribing. Good luck.

**Comment by yglukhov** [comment]
+1 to what @jibal said. Maybe we need findInPath or smth, but thats a completely different story and subject to a different pr. IMO findExe should anyway find exes, bats and cmds no matter what because they are all treaded as executables from a lot of standpoints, including scripting, winapi (you can start a process with bat), cmd prompt, etc.

**Comment by jibal** [comment]
You folks should take a look at https://bugs.python.org/issue2200 and http://environmentvariables.org/PathExt ... that is what you should be using on Windows (which by default contains a lot more than exe, bat, and cmd), not ExeExt or ExeExts. It's always a good idea to look into how others have addressed the issue  you're trying to address. I should have done some googling myself before suggesting ExeExts. %PATHEXT% leaves the decision as to whether to run gcc.bat  when given "gcc" up to the user or whatever the OS defaults to. Not only shouldn't Nim developers make this decision, but there's no need for them to.

 "IMO findExe should anyway find exes, bats and cmds no matter what because they are all treaded as executables from a lot of standpoints, including scripting, winapi (you can start a process with bat), cmd prompt, etc."

Exactly. It's about what is accepted by the API that the result of findExe will be passed to, not red herrings like whether a CPU can execute text or complete irrelevancies like whether POSIX #! handling is "a hack". Using %PATHEXT% makes this whole discussion moot. I strongly encourage you to implement that.

**Comment by jibal** [comment]
I missed a response that noted that Windows doesn't have an executable attribute, which is a problem for my comment: "this is problematic for filenames that contain '.' -- instead, the given filename should be checked to see if it exists and is executable, and the extension should only be added if not". It should be enough to just check whether the file exists in the path. You could do that by pretending that %PATHEXT% contains an empty extension before all other extensions. This seems to be what <cmd> does, as you can run gcc by either typing gcc or gcc.exe, and if you type, say, foo.com and foo.com.exe exists in your path, it will run it, unless foo.com exists earlier in your path or in the same folder, in which case it will run that.

**Comment by dom96** [comment]
> You folks should take a look at http://environmentvariables.org/PathExt ... 

This will work for the scripts that cmd.exe can execute, but who knows what the user will have in that environment variable. The screenshot in that page itself shows ``.js``. Executing that will surely just fail on Windows.

But I guess that's fine. I'm okay with this, and it makes the separation of ``findExe`` and ``findInPath`` make even more sense. ``findExe`` then becomes an alias for essentially ``findInPath(name, getEnv("PATHEXT").split(";")`` and if you want to be explicit you can just call ``findInPath(name, [ExeExt])``.

As for Unix, should it just return the first file that has the executable attribute set?

**Comment by yglukhov** [comment]
> As for Unix, should it just return the first file that has the executable attribute set?

yes, but for the sake of simplicity I don't think we have to check for the attribute until someone comes up with a sane usecase.

**Comment by yglukhov** [comment]
> Executing that will surely just fail on Windows.

Or it may pick up the correct interpreter (nodejs) using document type association. Otherwise customizing this var would become useless.

**Comment by jibal** [comment]
Windows has a FindExecutable() function that finds the interpreter for a script; it also has a GetBinaryType() function that tells you whether a file is a native executable. You can use these together to run anything. Or maybe, as @yglukhov suggests, there's an API that does that for you ... all I know comes from a little bit of googling. Whoever is designing this NIM API should look into such things and figure out what is available in and needed by the API of the target OSes.

On Linux, functions like this usually check that the file is executable _and a regular file_ ... I think that's what Python's distutils.spawn.find_executable does. I think that's advised, since without specific extensions there is a bigger chance of a false hit. Consider that someone might well have a gcc directory in $HOME or the current directory, and it would be a big mistake to return that.

**Comment by Araq** [comment]
Has been implemented differently.

**Pull request closed without merging**
