### PR TITLE
getTypeImpl now returns pragmas for object types

### PR DESCRIPTION
**Pull request by jcosborn**

### CODE REVIEW

**Comment by krux02** [comment]
Don't you test the pragmas on the type members?

**Comment by jcosborn** [comment]
I didn't add pragmas to the field members since that was more of a breaking change (it changes the field name symbol node to a PragmaExpr node), which macros would now have to handle, whereas the object pragma was just filling in an empty spot on the tree.  This keeps the fields easier to access in macros, if that is all you want.

I could easily add the field pragmas too, but wasn't sure if that was desired.  Right now you can get those with getImpl.  If I added them to getTypeImpl, then they would essentially be returning the same thing, except getImpl returns the full TypeDef tree while getTypeImpl only returns the ObjectTy part (see example below).

Note that this also means that this patch only grabs the pragma from the ObjectTy and not the one on the left side of the TypeDef attached to the symbol, ``myAttr`` below, (which is actually what hasCustomPragma looks for).  This is a potential source of confusion, but I didn't want to try merging the two.

Let me know what you prefer.

code:
```
  type
    MyObj {.myAttr.} = object {.myAttr2.}
      myField {.myAttr3.}: int
```

getTypeImpl (with this patch):
```
ObjectTy
  Pragma
    Sym "myAttr2"
  Empty
  RecList
    IdentDefs
      Sym "myField"
      Sym "int"
      Empty
```

getImpl:
```
TypeDef
  PragmaExpr
    Sym "MyObj"
    Pragma
      Sym "myAttr"
  Empty
  ObjectTy
    Pragma
      Sym "myAttr2"
    Empty
    RecList
      IdentDefs
        PragmaExpr
          Ident "myField"
          Pragma
            Sym "myAttr3"
        Sym "int"
        Empty
```

**Comment by cooldome** [comment]
IMO, it makes sense to keep field pragmas in getImpl only as jcosborn was saying.
I have reviewed, looks good to me. Ready for merge as far as I can tell.

**Comment by Araq** [comment]
> Ready for merge as far as I can tell.

Good, because the ``getType`` family of proc is now beyond me. We should probably clean it up and deprecate some variants later.

**Pull request merged**
