### PR TITLE
Update appveyor.yml

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by Yardanico** [comment]
@data-man I don't really know, but I think that this old GCC version is used to ensure compatibility with older compilers.
I'm not really sure though, @Araq can give you better answer :)

**Comment by Araq** [comment]
The mingw version should match the version the Nim website offers.

**Comment by data-man** [comment]
@cheatfate What do not you like? Any comments?

A mingw 4.9.2 headers outdated and does not contains many API for new versions of the Windows.

**Comment by Yardanico** [comment]
@data-man as @Araq mentioned, you should update website too, so it would provide the exact same MinGW ans sqlite versions

**Comment by data-man** [comment]
@Yardanico @Araq 
What I should do, make a PR to [website](https://github.com/nim-lang/website)?
But then a new version of MinGW should already be available for downloading from Nim website.

**Comment by Araq** [comment]
@data-man You can't help with that for now. Sorry. I would also like to do some benchmarks before using a newer GCC. Newer doesn't mean "Produces better code".

**Comment by data-man** [comment]
@Araq 
Ok.
But Nim site offers MinGW 6.3.0.
Maybe, to update to same version?

**Comment by Araq** [comment]
Hmmm.

**Comment by data-man** [comment]
Also, it's unlikely that Travis uses the old version of gcc.

**Comment by dom96** [comment]
Ideally we should be testing Nim on multiple GCC/Clang/other C compiler versions. But I guess we can't do that easily.

**Comment by data-man** [comment]
> we can't do that easily.

No, it's easy.

**Comment by data-man** [comment]
See, for e.g., how this is done in the [Zstandard](https://github.com/facebook/zstd) project:
[circle.yml](https://github.com/facebook/zstd/blob/dev/circle.yml)
[appveyor.yml](https://github.com/facebook/zstd/blob/dev/appveyor.yml)
[.travis.yml](https://github.com/facebook/zstd/blob/dev/.travis.yml)

**Comment by dom96** [comment]
ooh, we should do it then :)

**Pull request closed without merging**
