### PR TITLE
opensym for templates + move behavior of opensymchoice to itself

### LINKED ISSUE #15314: Injected symbols aren't resolved properly in expression passed to inner template
In the example below:
* We are using `applyIt` from inside some template
* A symbol called `it` already exists at the top level

The program doesn't compile, because the compiler thinks we are referring to the existing `it` rather than the one injected by the `applyIt` template.

### Example
```nim
import sequtils

var it: string
var nums = @[1,2,3]

template doubleNums() =
  nums.applyIt(it * 2)

doubleNums()
echo nums
```

### Current Output
```
...
Hint: main [Processing]
Hint: sequtils [Processing]
Hint: macros [Processing]
/home/exelotl/nim/test/it_conflict/main.nim(9, 11) template/generic instantiation of `doubleNums` from here
/home/exelotl/nim/test/it_conflict/main.nim(7, 19) Error: type mismatch: got <string, int literal(2)>
but expected one of: 
proc `*`(x, y: float): float
  first type mismatch at position: 1
  required type for x: float
  but expression 'it' is of type: string
proc `*`(x, y: float32): float32
  first type mismatch at position: 1
  required type for x: float32
  but expression 'it' is of type: string
...
proc `*`[T](x, y: set[T]): set[T]
  first type mismatch at position: 1
  required type for x: set[T]
  but expression 'it' is of type: string

expression: it * 2
```

### Expected Output
```
@[2, 4, 6]
```

### Additional Information

A workaround is to use a macro that forces `it` to be an ident, preventing the compiler from making the wrong assumptions about what `it` could be.

```nim
import sequtils, macros

var it: string
var nums = @[1,2,3]

macro doubleNums() =
  let it = ident("it")
  quote do:
    nums.applyIt(`it` * 2)

doubleNums()
echo nums
```
----
```
$ nim -v
Nim Compiler Version 1.2.6 [Linux: amd64]
```

### LINKED ISSUE #24002: Parameter not matched in template following symchoice changes
### Description

```nim
type Result[T, E] = object

func value*[T, E](self: Result[T, E]): T {.inline.} =
  discard

func value*[T: not void, E](self: var Result[T, E]): var T {.inline.} =
  discard

template unrecognizedFieldWarning =
  echo value

proc readValue*(value: var int) =
  unrecognizedFieldWarning()
```

Regression likely caused by #23892 

### Nim Version

Nim Compiler Version 2.0.9 [Linux: amd64]
Compiled at 2024-08-22
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: d6f7625626e4e19b9dd57147d2c8527a40fd4a03
active boot switches: -d:release

(version-2-0 branch)

### Current Output

```text
testit.nim(13, 27) Error: type mismatch
Expression: echo value
  [1] value: proc (self: Result[value.T, value.E]): T{.inline, noSideEffect.} | proc (self: var Result[value.T, value.E]): var T: not void{.inline, noSideEffect.}

Expected one of (first mismatch at [position]):
[1] proc echo(x: varargs[typed, `$`])
```

### Expected Output

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by metagn**
fixes #15314, fixes #24002

The OpenSym behavior first added to generics in #23091 now also applies to templates, since templates can also capture symbols that are meant to be replaced by local symbols if the context imports symbols with the same name, as in the issue #24002. The experimental switch `templateOpenSym` is added to enable this behavior for templates only, and the experimental switch `openSym` is added to enable it for both templates and generics, and the documentation now mainly mentions this switch.

Additionally the logic for `nkOpenSymChoice` nodes that were previously wrapped in `nkOpenSym` now apply to all `nkOpenSymChoice` nodes, and so these nodes aren't wrapped in `nkOpenSym` anymore. This means `nkOpenSym` can only have children of kind `nkSym` again, so it is more in line with the structure of symchoice nodes. As for why they aren't merged with `nkOpenSymChoice` nodes yet, we need some way to signal that the node shouldn't become ambiguous if other options exist at instantiation time, we already captured a symbol at the beginning and another symbol can only replace it if it's closer in scope and unambiguous.

### CODE REVIEW

**Comment by metagn** [comment]
Should we have separate `--experimental:genericsOpenSym` and `--experimental:templateOpenSym` switches for the behavior of the respective routines, or should there be one general `--experimental:openSym` switch that enables them both? Because now the node makes a lot more sense as a general construct, since it just contains one sym node, as an analogue to `nkOpenSymChoice`.

For now adding `--experimental:templateOpenSym`

**Comment by arnetheduck** [comment]
> Should we have separate 

doesn't feel immensely useful, what would be the use case for it? ie this basically brings the two behavior in line with each other, no?

**Comment by metagn** [comment]
Yeah this makes it more universal but I figured maybe one of them can cause more breaks and people might want to pick which ones to enable. I also didn't want to remove `genericsOpenSym` since it's been around for a while. The error messages and documentation really suffer from having 2 options though, I'll add `--experimental:openSym` that enables both and only mention the other 2 options as an alternative.

**Comment by arnetheduck** [comment]
lgtm, good to backport as well with any potential dependencies cc @narimiran

**Pull request merged**
