### PR TITLE
fix for Regression that the introduction of BackwardsIndex introduced

### PR DESCRIPTION
**Pull request by krux02**
Before the introduction of `BackwardsIndex` the following code worked. `BackwardsIndex` broke it and with this PR it works again:

```nim
type
  MyType = object

proc `[]`(arg: MyType; idx: int): int =
  idx

proc len(arg: MyType): int = 100

var mt: MyType
echo mt[^1] # 99
```

The idea is: When I have a type that supports both ``len`` and `` `[]` ``, then backwards indexing should just work out of the box. It did work, and now it works again. And while I was fixing this, it just happened to also allow for custom BackwardsIndex conversion functions:

```nim
type
  MyType = object

template `^^`(a: MyType, b: BackwardsIndex): int =
  ## my conversion of `BackwardsIndex` for `MyType`
  1000 + int(b)

proc `[]`(arg: MyType; idx: int): int =
  idx

var mt: MyType
echo mt[^1] # 1001
```

As you can see, I do not overload `len` for `MyType` here. And it just works out of the box. While it is still possible to overload the ``[]`` operator for BackwardsIndex to support it, it is not needed anymore. 

And last but not least. The code in `system.nim` is shorter now.

### CODE REVIEW

**Comment by Araq** [comment]
Brilliant solution, fails for

- tests/compiles/trecursive_generic_in_compiles.nim
- tests/array/troof3.nim

**Comment by krux02** [comment]
that's what the tests are for, aren't they. I will see what I can do.

**Comment by krux02** [comment]
Well I would like to comment on your snorky remark. I think your sarcasm is inapropriate. I try to fix a bug and I did not get it right the first time. That is what test are there for. I could also have reacted the same way when the BackwardsIndex was introduced, but I did not.

But thanks for pointing out the tests that failed. Actually digging though the logs of Travis and AppVeyor is very tedious, because it is so slow.

And last but not least, I would like to write a comment on the `troof3.nim` test. My question is, why should it work? An array with enums as index don't even support a forward index, so why then should it support a backwards index?

```nim
var a: array['a'..'c', string] = ["a", "b", "c"]

echo a[0]      # <- this isn't allowed
echo a[^1]   # So then why should this be allowedS It doesn't make a lot of sense to me.
```

**Comment by Araq** [comment]
> Well I would like to comment on your snorky remark. I think your sarcasm is inapropriate. 

No sarcasm involved here! I really like this solution! :-) Sorry.

**Comment by Araq** [comment]
Once it works we need to decide if ``^^`` should really be the symbol to use. Previously it wasn't exported and I wanted a binary operator for my personal readability.

**Comment by Araq** [comment]
> And last but not least, I would like to write a comment on the troof3.nim test. My question is, why should it work? An array with enums as index don't even support a forward index, so why then should it support a backwards index?

Good point, I agree.

**Comment by krux02** [comment]
I write an entry in the changelog, that backwards index for non-int indexed types does not compile anymore. And I remove the test.

**Comment by krux02** [comment]
@Araq: No you can't really use it for generic programming either, because tere is no generic way to access the first element.

**Comment by notTito** [comment]
For everyone's info [here](https://github.com/notTito/nim-100days/blob/master/structures/ringbuffer_concurrent.nim) is a data structure that won't work with these changes.

**Comment by krux02** [comment]
@notTito: It was very confusing to me that you used head and tail with that semantic. normally head is the first element of a list and tail everything but the first element. In your case both were indices. I think `getIndex` and `putIndex` would have been better names. But I will now take a deeper look into it.

**Comment by krux02** [comment]
@notTito I just tried moved the backwards index to the newest version of Nim and tested it with your example. There was a bug in line 53 where a normal index and a backwards index get subtracted. That operator is not defined. But when line 52 and 53 are removed, the automatically generated backwards index will work just fine. I tested it.

**Comment by krux02** [comment]
well there is nothing I can do with the concepts part. It seems like the concepts are broken, because my changes should not affect concepts at all.

**Comment by Araq** [comment]
> well there is nothing I can do with the concepts part. It seems like the concepts are broken, because my changes should not affect concepts at all.

Unfortunately, yes. :-(

**Comment by hlaaftana** [comment]
This has been postponed a little too long, tmapconcept has worked for a while

**Pull request closed without merging**
