### PR TITLE
Redirects support in request proc

### PR DESCRIPTION
**Pull request by yglukhov**
@dom96, please have a look.

### CODE REVIEW

**Comment by dom96** [comment]
My main concern is that there may be cases where you do not wish to follow redirects. But now that I think about it: could we just set ``client.maxRedirects`` to 0 for that use case?

**Comment by yglukhov** [comment]
Sure, thats exactly how it works. If you're ok with it, let me give it a couple of spins, and i'll write back when its ok.

**Comment by dom96** [comment]
Sure, I'm happy with this. Please also add it to the news (you might need to create a new news entry for it).

**Comment by yglukhov** [comment]
Added a fix to `getNewLocation` proc.

**Comment by yglukhov** [comment]
And done.

**Comment by dom96** [comment]
Thanks :)

**Pull request merged**
