### PR TITLE
strmantle: include => import

### PR DESCRIPTION
**Pull request by timotheecour**
/cc @xflywind (we discussed this)

### CODE REVIEW

**Comment by ringabout** [comment]
The CI failure is same as `include sth` in `strmantle.nim`.

**Comment by timotheecour** [comment]
> The CI failure is same as include sth in strmantle.nim.

the fact that HCR doesn't work on OSX (https://github.com/nim-lang/Nim/issues/13999 + `tests/dll/nimhcr_integration.nim` + disabled for osx + others) doesn't help with investigating the obscure CI failure here...

**Comment by timotheecour** [comment]
* made some progress on HCR issue: see https://github.com/timotheecour/Nim/pull/424
* the other issue here seems the same as https://github.com/nim-lang/Nim/issues/15081 and https://github.com/nim-lang/Nim/issues/11974

**Comment by ringabout** [comment]
Maybe continue this PR, Or I take over(make a new PR)?

Since tests/dll/nimhcr_integration.nim is disabled :P

**Comment by ringabout** [comment]
This PR can be closed, no special need to import strmantle now.

**Comment by timotheecour** [comment]
includes complicate things, but I'll revisit this after https://github.com/nim-lang/Nim/pull/18592 is merged

**Pull request closed without merging**
