### PR TITLE
followup #17398: `getTempDir`, `getConfigDir` now do not have trailing DirSep

### PR DESCRIPTION
**Pull request by timotheecour**
followup #17398

### CODE REVIEW

**Comment by Araq** [comment]
This breaks the "inim" package... Do we really want to break people's code because one guy on the forum found an inconsistency that prevented him from using a bad solution? I think it's a terrible way to develop a project.

**Comment by vercingetorx** [comment]
@Araq That was just a test case to highlight the inconsistencies between the procs. My argument against keeping it inconsistent because it "discourages bad code" is that the inconsistency itself is bad code.

**Comment by timotheecour** [comment]
I'm fixing inim in https://github.com/inim-repl/INim/pull/117; 
using:
```
getTempDir() & "inim_" & $uniquePrefix & ".nim"
```
is just asking for trouble

**Comment by Varriount** [comment]
I have to wonder if randomly adding/removing separators as part of the actual logic wouldn't lead to more reliable code... 
Whenever I've have written logic that depended on the presence/absence of trailing separators, it usually broke *at some point*...

**Comment by 0atman** [comment]
Thank you for your consideration @timotheecour & @Araq! The PR's merged in (thank you for that), that's a go from our side!

**Review by 0atman — APPROVED** [review]

**Pull request merged**
