### PR TITLE
Update tables.nim and parsecfg.nim

### PR DESCRIPTION
**Pull request by lihf8515**
Update tables.nim 

Ordered table also needs to delete function.

Update parsecfg.nim 

Added a number of features, including the creation of the configuration file, read, modify, delete operations.

### CODE REVIEW

**Comment by Araq** [comment]
unfortunately the 'del' for ordered table is wrong. 'del' is much harder to implement than it looks.

**Comment by Araq** [comment]
Update to use the new 'del' for ordered tables that @yglukhov gave us. :-)

**Comment by lihf8515** [comment]
Where can I download the version he provides

**Comment by yglukhov** [comment]
Just rebase your branch to latest upstream/devel. It's already there. #4081

**Comment by lihf8515** [comment]
OK

**Pull request closed without merging**
