### PR TITLE
Json serialization for openarrays and objects

### PR DESCRIPTION
**Pull request by yglukhov**
Revamp of #4014 with some bonus.

### CODE REVIEW

**Comment by Araq** [comment]
I like it but are you sure this doesn't break anything?

**Comment by yglukhov** [comment]
Maybe, lets ask dom96 to merge this in, he's not afraid of breaking changes in json :stuck_out_tongue_winking_eye:

Seriously though, I'm not 100% sure but I also can't see a case for which it would break anything.

**Comment by yglukhov** [comment]
@Araq, @dom96. Do you guys have more ideas of breakage cases? If not, let's get this in. Anyways, even if there is a breakage, it should be noticeable in compile time and should be easy to fix.

**Comment by dom96** [comment]
> Maybe, lets ask dom96 to merge this in, he's not afraid of breaking changes in json

[I like to live dangerously](http://images.memes.com/character/meme/i-too-like-to-live-dangerously-austin-powers) ;)

This is an awesome PR. Especially for my current project :D
Can't think of any breaking cases. What would be really nice is if we could reuse the `%` operator for our own data formats, but this can't work because there is no return type overloading.

**Pull request merged**
