### PR TITLE
[review after #18149] fix partially #18158 + higher precision `getMonoTime()` (for linux only, windows still broken)

### PR DESCRIPTION
**Pull request by timotheecour**
fix partially #18158

## EDIT
CI still fails on linux; `CLOCK_MONOTONIC_RAW` made things work locally on osx, not sure what differs with linux

## links
* see my justification here: https://github.com/nim-lang/Nim/issues/18158
* see also https://reviews.llvm.org/D74341
* https://stackoverflow.com/questions/3657289/linux-clock-gettimeclock-monotonic-strange-non-monotonic-behavior

### CODE REVIEW

**Comment by Varriount** [comment]
As mentioned in #18158, I'm not sure this is something that getMonoTime should guarantee, as it may not be feasible on all platforms.

**Comment by alaviss** [comment]
`CLOCK_MONOTONIC_RAW` might have performance implications: https://github.com/atdt/monotonic/issues/1#issuecomment-461610201

Also, a monotonic clock only have to guarantee that the time not go backwards, we don't have to guarantee that it always go forward because it might not always be the case (ie. instructions executed in parallel at the same clock tick).

**Comment by Varriount** [comment]
As a side note, I have been unable to find any mention for Java, Python, or C++ of a "strictly monotonic" counter, where "strict" means "never returns the same value". Wherever I read it, people seem to use "strict" to imply that the frequency of the clock is constant.

See:
  - [Python PEP 4180](http://staging.python.org/dev/peps/pep-0418/)
    A counter is defined as "strictly" monotonic, however the PEP indicates that both monotonic and perf_counter use QueryPerformanceCounter or GetTickCount behind the scenes. The documentation for QueryPerformanceCounter and GetTickCount make no mention of never returning the same value.
  - [This comment](https://stackoverflow.com/questions/40250112/fastest-way-to-measure-elapsed-time-in-java#comment67763511_40250112) in StackOverflow
    nanoTime is backed by QueryPerformanceCounter, which may return the same value for two subsequent calls.
  - [std::chrono::steady_clock](https://en.cppreference.com/w/cpp/chrono/steady_clock) and https://reviews.llvm.org/D74341
    The documentation states that the clock is monotonic, always increases, and has a constant frequency. The LLVM ticket says that CLOCK_MONOTONIC_RAW (which is to be used for `steady_clock`) is "monotonic, increas[es]
during sleep, and also has nanosecond precision", but makes no mention of never returning the same value.

**Comment by Araq** [comment]
No, please... Let's not open this rabbit hole. Most people have a finite amount of time on planet Earth.

**Pull request closed without merging**
