### PR TITLE
Simplify addInt, remove digits10

### PR DESCRIPTION
**Pull request by Clyybber**
This is the alternative PR to https://github.com/nim-lang/Nim/pull/18324, see the discussion on that PR.

### CODE REVIEW

**Comment by timotheecour** [comment]
IMO we shouldn't merge either this PR or https://github.com/nim-lang/Nim/pull/18324 until a clear picture comes out; see https://github.com/nim-lang/Nim/pull/18324#issuecomment-868684436; right now it looks more likely that digits10 is faster and that a gc:arc bug causes some 3.5X slowdown (even with digits10 out of the picture)

**Comment by Clyybber** [comment]
This PR is far less controversial than #18324 though...

**Comment by timotheecour** [comment]
see update in https://github.com/nim-lang/Nim/pull/18324#issuecomment-868713422; IMO a clear picture now comes out:
* digits10 is useful and `addIntDigits10OpenArray` is faster than `addInt3OpenArray` in all settings according to that benchmark (gc, OS, distribution of inputs, reordering of code in the benchmark, commenting out, etc), by up to 1.7X. AFAIK, the benchmark is fair, and the same optimizations are used (minus digits10).
* there is a 3.5X factor performance bug with gc:arc that is entirely unrelated to digits10 (occurs without it being called and affects addInt3OpenArray just as well) and should be investigated independently

> far less controversial

ignoring benchmark results that tell a clear story (A is faster than B in all cases) is controversial

**Comment by disruptek** [comment]
We don't have to choose.  Merge this one and continue to consider the other.

**Comment by c-blake** [comment]
Doesn't yield consistent benchmarks for me.  The last 2 posts you link to in the other PR are either A) wildly internally varying by 4X for the whole bin->dec calculation (1.48 -> 5.56) due to arc effects as you elaborate or B) unelaborated (no numbers, no CPU detail from xfly) as to ratios - literally supporting *no* story or benchmarks to even ignore, never mind a story where https://github.com/nim-lang/Nim/pull/18324 is consistently faster. (EDIT: and as others have noted, simpler is more futureproof, more likely to have portable performance, and is easier on the eyes.)

**Comment by Araq** [comment]
The code got slightly worse, now 3 ways to copy chars around because of JS and Nim's VM etc. Since the performance differences are non-conclusive I'm rejecting this.

**Comment by c-blake** [comment]
Is there a good reason Nim lacks a portable, terse abstraction for something as simple as copying chars around?  With such, this PR would become "mostly deleting unneeded, shared `digits10`".

**Comment by Clyybber** [comment]
> The code got slightly worse, now 3 ways to copy chars around because of JS and Nim's VM etc.

It's two ways, not three. The branching is exactly the same as here https://github.com/nim-lang/Nim/blob/devel/lib/pure/streams.nim#L245

**Pull request merged**
