### PR TITLE
Renamed writeln to writeLine. Issue #2958

### LINKED ISSUE #2958: readLine/writeLn procedure nameing inconsistancy
the method naming for line reading and writing is inconsistent:
readLine to read and wrtieLn to write.
They should either be named 
readLine/writeLine
or readLn/writeLn

### PR DESCRIPTION
**Pull request by Perelandric**
Fixes #2958.

In `lib/js/dom.nim` and `lib/system/jssys.nim` there are objects with a `writeln` property. I didn't touch those.

`writeln` is deprecated and uses of it have been updated.

Broke the commits down into groups. The first commit is the actual proc renaming and deprecation. The rest are the usage updates.

### CODE REVIEW

**Comment by Perelandric** [comment]
Do we add a note to "breaking changes" for items marked as deprecated or is the deprecation sufficient?

**Comment by yglukhov** [comment]
Aren't writeln/readln more conventional? ;)

**Comment by Perelandric** [comment]
@yglukhov I'm proud to be unconventional. ;-)

**Comment by reactormonk** [comment]
Deprecation should be good enough, it's not breaking yet.

**Comment by dom96** [comment]
Did you deprecate it? All I see is the rename in the diff, not the original deprecated ``writeLn``.

**Comment by Perelandric** [comment]
@dom96 

I'll make the changes. Didn't realize you wanted to keep the old version in the docs. 

May be a good idea to make a note in the new contributor's guide. That's what I referenced before doing this change (though it hadn't been committed at the time, I see it is now).

**Comment by Perelandric** [comment]
@dom96:  I followed other examples in the lib that duplicated the body of the old proc instead of having the old one call the new one (or vice versa) and using `{.push warning[deprecated]: off.}` and `{.pop.}`.

**Comment by dom96** [comment]
@reactormonk could you include this in the contributors guide?

**Comment by nanoant** [comment]
@dom96 I am sorry, but how has this commit got your acceptance? Did you actually bother to look at the diffs? The half of the changes are whitespace changes having absolutely nothing to do with the subject of the commit! Do we really need to fuck up the whole history with each single commit, so thanks to that we no longer can blame on the lines?

Moreover the whole change is absolutely and utterly ridiculous, changing half of the code because of simple stylistic change. Not at this point before 1.0 release!

@Perelandric @dom96 You also (deliberately?) ignored statistics, where `writeln` (and other `prefixWriteln`) are used much more often than `readLine` across the Nim vital core's source code. So if you really wanted so hard consistency you should rename `readLine` -> `readln` and the impact would be much smaller.

> @yglukhov: Aren't writeln/readln more conventional? ;)
> @Perelandric: @yglukhov I'm proud to be unconventional. ;-)

WTF attitude is that? You all wanted to Nim be professional project, this makes it NOT.

@dom96 Merging such a big change in the weekend, just within one day of the PR was submitted, you have absolutely gave no chance to anyone to at least get some awareness what is going to happen.

Finally if you really want to stay consistent now change  `msgWriteln` -> `messageWriteLine`, want it even more change `len` -> `length`.

Honestly I just lost my faith and interest in this project looking what you did.

@Araq I am humbly ask you to reset `devel` back to last commit (SHA) before this change, so the git history gets unscrewed on these whitespace changes, and not to accept such a disasters anymore in such short term.

**Comment by kirbyfan64** [comment]
@nanoant

> The half of the changes are whitespace changes having absolutely nothing to do with the subject of the commit!

But most PRs already are like that...

**Comment by Perelandric** [comment]
@nanoant 

The reason for the white-space changes was this: http://forum.nim-lang.org/t/1292 I do think it would be better to do a cleanup all at once if one was desired but there seems to be resistance to that idea. If there should be a different policy, then it needs to be discussed and documented.

The reason I changed `writeln` instead of `readLine` was simply that there were more `readLine`  procs in the std lib than `writeln`. I did it knowing that it could be rejected.

The reason for my light-hearted "unconventional" comment was my confidence that any real objection would be presented as such. None were forthcoming at that moment.

Let me know if you have any other questions specifically for me pertaining to this PR.

**Comment by Perelandric** [comment]
@yglukhov If your comment was meant as an objection to the naming, then I apologize. I didn't mean to be dismissive; it just didn't come across that way phrased as a question with a wink.

@dom96 Sorry for the trouble. In the future, I'll not be so proactive in submitting a change that may be upsetting to some. Had a little free time, so I just dove in. I'll wait for someone's blessing next time.

**Comment by reactormonk** [comment]
@Perelandric Fixing it globally will break ALL PRs. So just fix them whenever you change a file.

**Comment by nanoant** [comment]
> But most PRs already are like that...

@kirbyfan64 Honestly I don't think most of PRs have ~800 changed lines where 400 are whitespace changes.

> The reason for the white-space changes was this: http://forum.nim-lang.org/t/1292

@Perelandric And you just got response from single Nim contributor @def-, no response from code owner @Araq.

We had another discussions about that on IRC, and I had really impression that we should either fix them all by once (to not annoy @Araq anymore) or just keep changing only the stuff that was actually subject of the change and just make sure that new changes don't bring any whitespace changes, to not pollute diffs, either/or.

@def- Correct me if I am wrong, but I don't think "fix whitespace whenever you alter file" is official Nim PR policy, so your advise to @Perelandric apparently cause the whitespace trouble. Make @Araq and other contributors to agree on that, put that into `contributing.rst` and I will gladly shut-up.

But allowing whitespace alternation (even it is "fixing") that has nothing to do with subject is worst choice, unless you don't really care that there are some others wanting to use `git blame` when doing some heavy work.

> The reason I changed writeln instead of readLine was simply that there were more readLine procs in the std lib than writeln. I did it knowing that it could be rejected.

Probably you counted it wrong including GNU `readline` wrapper (removed recently) that bumped your `readLine` statistics a lot, but this was not the Nim's `readLine`, so not the `readline` you would rename.

Also you probably skipped `msgWriteln` which is compiler internal function, calling `writeln` or/and so extra callbacks. There are also other functions such as `ewriteln` etc. etc.

My stats are `readLine\b` RegEx (excluding GNU readline) **140 matches**, `writeln\b` (includes all other internal functions with custom prefix) **270 matches**, `\bwriteln\b` (excluding functions with custom prefix) **200 matches**. So `writeln` was used more across the code.

Now to be honest I am really mad on @Perelandric, because everyone has a right to submit PR, and expect it gets accepted or rejected. In fact I am mad on @dom96 for quickly merging such a big change in the weekend within one day without blink of an eye, even I think we had this discussions about `git blame` quite recently.

FYI @Perelandric Like you I was really concerned about these whitespaces, so much I once managed really to upset @Araq. But the proposed strategy was: fix it once with one commit named "Fix trailing whitespace / from now on we don't accept any trailing whitespace", and **then** set the editors to cut the whitespace on save.

**Comment by Araq** [comment]
> I am humbly ask you to reset (not revert) devel back to last commit (SHA) before this change,

Sorry, it's too late for that.

> so the git history gets unscrewed on these whitespace changes, and not to accept such "disasters" anymore in such short term.

Yeah I agree with that.

> @def- Correct me if I am wrong, but I don't think "fix whitespace whenever you alter file" is official Nim PR policy, so your advise to @Perelandric apparently cause the whitespace trouble. Make @Araq and other contributors to agree on that, put that into contributing.rst and I will gladly shut-up.

I think that's actually our PR policy, but I will be happy and change it.

> But allowing whitespace alternation (even it is "fixing") that has nothing to do with subject is worst choice, unless you don't really care that there are some others wanting to use git blame when doing some heavy work.

True, but frankly, in my opinion all of git's output needs to go though a filter/script that ignores whitespace changes for good. Nobody should have to care about trailing whitespace or Unix/Windows line endings.

**Comment by dom96** [comment]
> @dom96 I am sorry, but how has this commit got your acceptance? Did you actually bother to look at the diffs? The half of the changes are whitespace changes having absolutely nothing to do with the subject of the commit! Do we really need to fuck up the whole history with each single commit, so thanks to that we no longer can blame on the lines?

I can assure you that I did look at the diffs. The whitespace changes in the diff are in line with how we should be treating whitespace at this point in time: remove all of it from the file you have edited. This is what text editors do already so it makes sense.

> Not at this point before 1.0 release!

A large majority of changes will still likely happen before 1.0 because after 1.0 these changes simply can't happen (well, actually, they can because we have deprecated ``writeLn`` in this case).

> @dom96 Merging such a big change in the weekend, just within one day of the PR was submitted, you absolutely gave no chance to anyone to at least get minimal awareness what is going to happen.

You're right. Perhaps I merged it too early. In all honest I assumed this PR was older than it was. That said, @Araq has told me in private that he wanted this change (not this specific PR, but he wanted the rename from ``writeLn`` to ``writeLine``) so it had his blessing.

I always run under the impression that these things can always be undone, because they can. In this case however you argue that it causes damage to our history because of the whitespace changes, something which I did not consider.

I can tell you that if Araq touched these files, he would also have changed the whitespace in this manner.

**Comment by nanoant** [comment]
> I can assure you that I did look at the diffs. The whitespace changes in the diff are in line with how we should be treating whitespace at this point in time: remove all of it from the file you have edited. This is what text editors do already so it makes sense.

@dom96 Then I have completely different experience, I have worked on some big projects such as llvm, Qt, Julia and none would allow whitespace or formatting change not related with subject.

I am not against fixing whitespace errors, but these shall go with separate commits called "Fix whitespace", ideally one single commit fixing the mess everywhere possible.

The rule of thumb is **not to**:
1. introduce whitespace errors in the changes (eg. require developers to `git diff --check` prior commit)
2. introduce changes not related to subject (this has to be unfortunately checked by the maintainer accepting PR)

> You're right. Perhaps I merged it too early. In all honest I assumed this PR was older than it was. That said, @Araq has told me in private that he wanted this change (not this specific PR, but he wanted the rename from writeLn to writeLine) so it had his blessing.

@dom96 If so then we just have scratched top of the iceberg. Now you need to change `msgWriteln` too, and any other functions having `Writeln` suffix, otherwise things will become terribly confusing.

@Perelandric Therefore I ask you to prepare next PR replacing `Writeln` suffix in various Nim places with `WriteLine`, eg. `msgWriteln` -> `msgWriteLine`. (no need to deprecate that, since this is part of internal compiler code)

I will soon send some PR regarding Git commit policy (these 2 points above) updating `contributing.rst`.

**Comment by kirbyfan64** [comment]
@nanoant Uhhh...yes they have. Both PRs *and* regular commits. Just pull up some of Araq's "fix XXXX" commits; some of them have a 2-line change and at *least* 30 lines of whitespac. changes.

**Comment by Perelandric** [comment]
@nanoant Just to be clear, I wasn't trying to put this on @def-. After his response, I searched github and found an old issue from def- that attempted to do the cleanup, which included a note from dom96 that made reference to Araq's opinion on the matter. (Working from memory here.)

So it was that and the fact that I received no counter opinion in the forum.

**Comment by Perelandric** [comment]
I'd be happy to do a PR for additional `...Writeln` procs but I'll wait for the official go-ahead and some definite instruction regarding whitespace.

**Comment by nanoant** [comment]
@kirbyfan64 wrote:
> Uhhh...yes they have. Both PRs and regular commits. Just pull up some of Araq's "fix XXXX" commits; some of them have a 2-line change and at least 30 lines of whitespac. changes.
This is true. Fortunately @Araq acknowledges this is a problem.

Now knowing that this all came from some previous decisions and discussions, I do realize I've been probably too mean to @dom96 & @Perelandric, since these PR's changes were not their sole decision. Therefore pleas accept my apologies. I should probably stop reading commit logs late night ;)

Still I insist to stop this whitespace madness, and commit only what is necessary and related to the commit subject.

@Araq & @dom96 I am perfectly aware it is really hard to force everyone to carefully craft their commits chunk by chunk. So you should reconsider and rethink ultimate solution fixing that with one *"Fix trailing whitespace"* commit, and start writing clean & lean Nim's history afterwards.

FYI there are 516 files affected doing:

    find . -name '*.nim' -exec sed -i '' -E "s/[[:space:]]+$//" {} +

So sittuation is no good, and keeping current workflow we can expect more noisy commits coming.

**Comment by reactormonk** [comment]
@nanoant You could make a PR against whitespace changes in files that don't have a PR.

**Pull request merged**
