### PR TITLE
Improve getDataUri

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Improve `std/uri.getDataUri`.

### CODE REVIEW

**Comment by ire4ever1190** [comment]
(Edited from original comment since original benchmarks didn't test properly)

```nim
import benchy
import base64

template getDataUriImpl(useSetLen: bool, body: untyped) {.dirty.} =
  for _ in 0..<10_000:
    let 
      data = "Nim"
      mime = "text/plain"
      encoding = "utf-8"
    var result: string
    let base64encoded: string = base64.encode(data)
    when useSetLen:
      result.setLen(22 + mime.len + encoding.len + base64encoded.len)
    else:
      result = newStringOfCap(22 + mime.len + encoding.len + base64encoded.len)
    body
    doAssert result == "data:text/plain;charset=utf-8;base64,Tmlt"
    keep result

proc main() =
  # Have warmup or else first item will always be slowest
  timeIt "warmup":
    getDataUriImpl false:
      for str in ["data:", mime, ";charset=", encoding, ";base64,", base64encoded]:
        result &= str

  timeIt "naive concatenation":
    getDataUriImpl false:
      result = "data:" & mime & ";charset=" & encoding & ";base64," & base64encoded
      
  timeIt "Copy using add":
    getDataUriImpl false:
      for str in ["data:", mime, ";charset=", encoding, ";base64,", base64encoded]:
        result &= str

  timeIt "Copy manually":
    getDataUriImpl true:
      var index = 0
      for str in ["data:", mime, ";charset=", encoding, ";base64,", base64encoded]:
        for chara in str:
          result[index] = chara
          inc index

  timeIt "Unrolled loop":
    getDataUriImpl false:
      result &= "data:"
      result &= mime
      result &= ";charset="
      result &= encoding
      result &= ";base64,"
      result &= base64encoded

main()
```


`nim -d:release --threads:off r bench.nim` (with latest devel nim)
results
```
name ............................... min time      avg time    std dv   runs
warmup ............................. 2.302 ms      3.077 ms    ±0.681  x1000
naive concatenation ................ 0.632 ms      0.678 ms    ±0.069  x1000
Copy using add ..................... 1.219 ms      1.316 ms    ±0.165  x1000
Copy manually ...................... 1.554 ms      1.658 ms    ±0.118  x1000
Unrolled loop ...................... 0.672 ms      0.731 ms    ±0.118  x1000
```

Seems the C code generated for just joining the strings is better than the unrolled
**Just joining strings**
```c
				T4_ = rawNewString(mime.len + encoding.len + base64encoded.len + 22);
appendString((&T4_), TM__ipcYmBC9bj9a1BW35ABoB1Kw_15);
appendString((&T4_), mime);
appendString((&T4_), TM__ipcYmBC9bj9a1BW35ABoB1Kw_19);
appendString((&T4_), encoding);
appendString((&T4_), TM__ipcYmBC9bj9a1BW35ABoB1Kw_21);
appendString((&T4_), base64encoded);
				eqsink___system_3560((&result), T4_);
```
**Unrolling loop**
```c
				prepareAdd((&result), 5);
appendString((&result), TM__ipcYmBC9bj9a1BW35ABoB1Kw_15);
				prepareAdd((&result), mime.len + 0);
appendString((&result), mime);
				prepareAdd((&result), 9);
appendString((&result), TM__ipcYmBC9bj9a1BW35ABoB1Kw_19);
				prepareAdd((&result), encoding.len + 0);
appendString((&result), encoding);
				prepareAdd((&result), 7);
appendString((&result), TM__ipcYmBC9bj9a1BW35ABoB1Kw_21);
				prepareAdd((&result), base64encoded.len + 0);
appendString((&result), base64encoded);
```

So maybe keep the set len but use old way of making string?

Sorry for this long comment, just got pretty interested in what the fastest way was

**Comment by juancarlospaco** [comment]
@ire4ever1190 You should put your code inside a `main()` proc for bench, 
because too many global variables, and your solution have missing chars, 
please `doAssert` the `string` result and you will see you are not producing the correct results.
Also try with `--threads:off` too.

It is a nice observation whatsoever.

**Comment by ghost** [comment]
Have you tried newStringOfCap + just using `&=` (it's qutie efficient), maybe that would be comparable performance and much simpler code?

**Comment by juancarlospaco** [comment]
```nim
import std/assertions
import benchy

proc getDataUri0(base64encoded, mime, encoding: string): string =
  result = newStringOfCap(22 + mime.len + encoding.len + base64encoded.len)
  result.add("data:" & mime & ";charset=" & encoding & ";base64," & base64encoded)
  benchy.keep(result)

proc getDataUri1(base64encoded, mime, encoding: string): string =
  result.setLen(22 + mime.len + encoding.len + base64encoded.len)
  var index = 0
  for str in ["data:", mime, ";charset=", encoding, ";base64,", base64encoded]:
    for chara in str:
      result[index] = chara
      inc index
  benchy.keep(result)

proc getDataUri2(base64encoded, mime, encoding: string): string =
  result = newString(22 + mime.len + encoding.len + base64encoded.len)
  var index = 0
  for str in ["data:", mime, ";charset=", encoding, ";base64,", base64encoded]:
    for chara in str:
      result[index] = chara
      inc index
  benchy.keep(result)

proc getDataUri3(base64encoded, mime, encoding: string): string =
  result = newStringOfCap(22 + mime.len + encoding.len + base64encoded.len)
  result.add "data:"
  result.add mime
  result.add ";charset="
  result.add encoding
  result.add ";base64,"
  result.add base64encoded
  benchy.keep(result)

proc getDataUri4(base64encoded, mime, encoding: string): string =
  result = newStringOfCap(22 + mime.len + encoding.len + base64encoded.len)
  result.add 'd'  # This can be done by macro, but we keep simple here.
  result.add 'a'
  result.add 't'
  result.add 'a'
  result.add ':'
  result.add mime
  result.add ';'
  result.add 'c'
  result.add 'h'
  result.add 'a'
  result.add 'r'
  result.add 's'
  result.add 'e'
  result.add 't'
  result.add '='
  result.add encoding
  result.add ';'
  result.add 'b'
  result.add 'a'
  result.add 's'
  result.add 'e'
  result.add '6'
  result.add '4'
  result.add ','
  result.add base64encoded
  benchy.keep(result)

proc main() =
  let
    base64encoded = "SGVsbG8gV29ybGQ="  # "Hello World" in base64.
    mime          = "text/plain"
    encoding      = "utf-8"

  timeIt "getDataUri0":
    doAssert getDataUri0(base64encoded, mime, encoding) == "data:text/plain;charset=utf-8;base64,SGVsbG8gV29ybGQ="

  timeIt "getDataUri1":
    doAssert getDataUri1(base64encoded, mime, encoding) == "data:text/plain;charset=utf-8;base64,SGVsbG8gV29ybGQ="

  timeIt "getDataUri2":
    doAssert getDataUri2(base64encoded, mime, encoding) == "data:text/plain;charset=utf-8;base64,SGVsbG8gV29ybGQ="

  timeIt "getDataUri3":
    doAssert getDataUri3(base64encoded, mime, encoding) == "data:text/plain;charset=utf-8;base64,SGVsbG8gV29ybGQ="

  timeIt "getDataUri4":
    doAssert getDataUri4(base64encoded, mime, encoding) == "data:text/plain;charset=utf-8;base64,SGVsbG8gV29ybGQ="

when isMainModule:
  main()
```

**Comment by ire4ever1190** [comment]
Thanks @juancarlospaco I've updated my comment with a those fixes. Turns out using `&=` wasn't using the preallocated string memory so fixed that up.
But seems now that copying across the string character by character is slower  than the other options

**Review by Varriount — APPROVED** [review]

**Pull request merged**
