### PR TITLE
Return error message in output of gorge/staticExec.

### PR DESCRIPTION
**Pull request by dom96**

### CODE REVIEW

**Comment by Araq** [comment]
This changes the behavior of these procs.

**Comment by dom96** [comment]
Of course, what else do you expect a PR to do? :)

**Comment by Araq** [comment]
Well it's a breaking change, previously you could use `s == ""` and know there's been an error (depending on the program you called).

**Comment by dom96** [comment]
Would you? What if a program has no output? It's ambiguous.

But why check the output when you can check the error code?

**Comment by Araq** [comment]
It's not about me, it's a breaking change; it needs some `nimPreviewStaticExecErrorReport` switch. Or maybe something else.

**Comment by dom96** [comment]
I won't waste time arguing, so just to confirm: will you merge if this is behind a switch?

**Comment by arnetheduck** [comment]
> behind a switch

in general, the switches and compatibility periods are really an escape hatch and a last resort when all options have been exhausted - if breaking code frivolously is the norm, the switch indeed isn't a helpful tool (it's meant to give people time to adapt to very important and pragmatically inevitable breakages for really bad historical choices)

**Comment by dom96** [comment]
Ready for review.

**Comment by dom96** [comment]
Still ready for review

**Pull request merged**
