### PR TITLE
arrays with non-zero lower bound cannot convert to openarray

### LINKED ISSUE #184: deprecate array with low != 0
array with low != 0 (eg: `array[2..4, int]`) seems like a bad idea in hindsight, it causes complications and edge cases and doesn't seem provide any benefit.

## example of such complications
see https://github.com/nim-lang/Nim/pull/12993#issuecomment-576434537 /cc @Araq 
> doubt the code really was correct for e.g. array[-3..10, T].
> The rest of the stdlib uses openArray and doesn't bother with weird arrays either. We cannot accept the resulting factor of 2 in API surface and the maintainability effort it implies.

## proposal
* array with enum index is useful, not bug-inducing and is not deprecated:
```nim
type Days = enum
  monday, tuesday
var a: array[Days, string] = [monday: "lundi", tuesday: "mardi"]
echo a
echo a[monday]
```

it's not bug-inducing because it's type safe: a misuse would cause a CT error.

* array with range index starting at non-zero is not really useful, source of bugs (eg: you used `0` instead of `low`) and should be deprecated.
unlike the enum index case, the type system can't help you if you mis-used 0 for `low`

one possible way to deprecate would be to:
* not deprecate array[N: int, T]
* deprecate array[R, T] where R is an range of ordinal except enum

### PR DESCRIPTION
**Pull request by metagn**
closes https://github.com/nim-lang/RFCs/issues/184

### CODE REVIEW

**Comment by Araq** [comment]
Is that really wise? What if the proc does no harm like `sort`. It's a special case that prohibits the `find` example from compiling but it also prevents other things which used to work. Maybe we should just reject the RFC instead.

**Comment by beef331** [comment]
I know concepts are not really encouraged but the solution to me seems to be adding things like
```nim
type NonZeroArray[Idx, T] = concept arr
  arr.low.ord != 0
  arr.low is Idx
  arr[Idx] is T
  

proc find*[Idx, T](arr: NonZeroArray[Idx, T], val: T): (bool, Idx) =

  for i, x in arr.pairs:
    if x == val:
      return (true, i)
   
var 
  a: array[-3..5, int]
  b: array[4, int]
assert a.find(0) == (true, -3)
assert a.find(10 == (false, 0)
assert b.find(0) == 0
assert b.find(10) == -1
```

**Comment by Araq** [comment]
You got the concept wrong btw but it's a good idea. So this RFC is rejected.

**Comment by metagn** [comment]
> proc find*[Idx, T](arr: NonZeroArray[Idx, T], 

This is the same solution you would use with this PR, the difference is you would be forced to use it which prevents bugs early, or you could opt in with `array[0..len-1](arr)`.

Also we can do this now if we don't use a concept and just overload for `array`.

**Pull request closed without merging**
