### PR TITLE
Fix #21532: Check if template return is untyped

### LINKED ISSUE #15833: range passed to template gives: Error: wrong number of arguments
template inside generic gives: Error: wrong number of arguments

### Example
```nim
when true:
  template elementType*(a: untyped): typedesc = # from typetraits.nim
    typeof(block: (for ai in a: ai))
  # proc fn(a: int) = # ok
  proc fn[T](a: T) =
    type T1 = typeof(block: (for ai in 0..2: ai)) # ok
    type T2 = elementType(0..2) # Error: wrong number of arguments
```

### Current Output
Error: wrong number of arguments

### Expected Output
works

### Additional Information
* devel 1.5.1 28bbcd9d45f15247af347785a46d0c2e2750b8ca
- [ ] 2nd problem is that `Error: wrong number of arguments` should show: got X expected Y

### LINKED ISSUE #21532: `elementType` from `std/typetraits` doesn't work in generic procs
### Description

Not able to use `typetraits.elementType` in generic procs, which defeats the purpose of this template.

Example code:
```nim
import typetraits

func thisWorks(v: seq[int]) =
  doAssert elementType(v) is int

func thisDoesNot[T](v: T) =
  doAssert elementType(v) is int

@[1,2,3].thisDoesNot
```
Compilation fails with `Error: wrong number of arguments`.

### Nim Version

Nim Compiler Version 1.6.10 [Linux: amd64]
Compiled at 2022-11-21
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f1519259f85cbdf2d5ff617c6a5534fcd2ff6942
active boot switches: -d:release

### Current Output

```text
Error: wrong number of arguments
```

### Expected Output

```text
works
```

### Possible Solution

_No response_

### Additional Information

Probably related to #15833

### PR DESCRIPTION
**Pull request by SirOlaf**
Close #21532
Close #15833

### CODE REVIEW

**Comment by Araq** [comment]
This is a potentially breaking change, we have to be careful here...

**Comment by SirOlaf** [comment]
You're right, had that concern too. This change *should* only delay template expansion though, and only for special templates invoked inside of generic procs. So unless I'm missing something it should only make more code work but I don't know the compiler internals enough to see the consequences here.

[This](https://github.com/nim-lang/Nim/blob/a4781dc4bcdf6e76076af80d0b21cb09865b3d44/compiler/semgnrc.nim#L256) is where I got that idea, so I'm just hoping the comment is still accurate :stuck_out_tongue:

**Comment by SirOlaf** [comment]
On a sidenote, macros probably have the same limitation (does pretty much same [loop](https://github.com/nim-lang/Nim/blob/a4781dc4bcdf6e76076af80d0b21cb09865b3d44/compiler/semstmts.nim#L2479)). Didn't add a check for those so could do that too if it seems safe enough

**Comment by metagn** [comment]
This seems reasonable, in the worst case we can let templates/macros opt in to `allUntyped` and early generic evaluation with some pragma.

**Pull request merged**
