### PR TITLE
fix #17325 unrbreak CI i386

### LINKED ISSUE #17325: CI fails on azure 32 bit linux Linux_i386: sudo apt-fast install fails
I'm seeing:
`nim-lang.Nim (packages Linux_i386) Failing after 58s — packages Linux_i386 failed`
in several unrelated PRs (eg https://github.com/nim-lang/Nim/pull/17257#issuecomment-796247652)

eg https://dev.azure.com/nim-lang/255dfe86-e590-40bb-a8a2-3c0295ebdeb1/_apis/build/builds/14075/logs/38

```
2021-03-10T21:10:24.0269335Z CC: stdlib_assertions.nim
2021-03-10T21:10:24.0288424Z CC: stdlib_dollars.nim
2021-03-10T21:10:24.1410956Z Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3  -I/home/vsts/work/1/s/lib -I/home/vsts/work/1/s -o /home/vsts/.cache/nim/koch_d/stdlib_assertions.nim.c.o /home/vsts/.cache/nim/koch_d/stdlib_assertions.nim.c' failed with exit code: 1
2021-03-10T21:10:24.1412125Z 
2021-03-10T21:10:24.1412666Z In file included from /usr/include/limits.h:25:0,
2021-03-10T21:10:24.1413573Z                  from /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/limits.h:168,
2021-03-10T21:10:24.1414497Z                  from /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/syslimits.h:7,
2021-03-10T21:10:24.1415407Z                  from /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/limits.h:34,
2021-03-10T21:10:24.1416047Z                  from /home/vsts/work/1/s/lib/nimbase.h:268,
2021-03-10T21:10:24.1416680Z                  from /home/vsts/.cache/nim/koch_d/stdlib_assertions.nim.c:9:
2021-03-10T21:10:24.1417570Z /usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
2021-03-10T21:10:24.1418154Z compilation terminated.
2021-03-10T21:10:24.1472789Z ##[error]Bash exited with code '1'.
2021-03-10T21:10:24.1576588Z ##[section]Finishing: Build koch
```

(refs https://github.com/nim-lang/Nim/issues/3123#issuecomment-122125096)
refs:
* sudo apt-get install g++-multilib https://stackoverflow.com/questions/51765069/fatal-error-sys-cdefs-h-no-such-file-or-directory-while-compiling-openssl-1-1
* libc6-dev-i386 https://itectec.com/ubuntu/ubuntu-fatal-error-sys-cdefs-h-no-such-file-or-directory/

### PR DESCRIPTION
**Pull request by timotheecour**
* fix #17325 by upgrading from ubuntu-16.04' to ubuntu-18.04' for just i386 (for now)
* add `set -e` in bash sections to avoid bugs like in #17325 where CI would keep going after a failing cmd in a bash section
* add `ci/funs.sh` (which may grow in future, to avoid code duplication, eg amongst several CI files or CI commands, or to help identify csources2 url/tag etc), and for now contains `echo_run` which echos a command before running it (very useful for understanding logs, whether or not in CI)

## example
see effect of `echo_run` in logs:
image

## future work
* check whether we want to support ubuntu-16.04 again in CI, but at least this PR improves the situation

### CODE REVIEW

**Comment by timotheecour** [comment]
@alaviss in reply to https://github.com/nim-lang/Nim/issues/17325#issuecomment-796388775

> If you want to upgrade the ubuntu version @timotheecour, please upgrade it for all architectures.

I'm not sure it's a good idea to upgrade on both 64 and 32 bits, if anything it increases coverage by ensuring we can still work with ubuntu16.04. The azure CI code for 64bit is clean (unlike the one for 'ubuntu-16.04' which has complexity due to azure not having 32 bit VM's). If there's some concrete limitation from using ubuntu 16.04 instead of ubuntu 18.04 on 64 bit (or if CI would be slower etc), we could re-consider this but I don't think that's the case.

> In the future I'll enginner a docker image as CI for nim, which should avoid all of these stupid issues with apt.

ya that'd be great; it doesn't have to be an either/or thing also; a docker-based job could be added to existing ones eg to bundle extra dependencies for running certain tests

**Review by ringabout — APPROVED** [review]
may not hurt

**Comment by timotheecour** [comment]
merging this to unbreak nim CI; followup PR's can be made if we find a better way to support i386 with keeping ubuntu 16.04

**Comment by narimiran** [comment]
@timotheecour We now have:

```
sudo apt-fast update -qq

sudo apt-fast install --no-install-recommends --allow-downgrades -yq g++-multilib gcc-multilib libcurl4-openssl-dev:i386 libgc-dev:i386 libsdl1.2-dev:i386 libsfml-dev:i386 libglib2.0-dev:i386 libffi-dev:i386
[apt-fast 09:42:55]
[apt-fast 09:42:55]Working... this may take a while.
E: Unable to correct problems, you have held broken packages.
[apt-fast 09:42:55]Package manager quit with exit code.
```

Any idea what's going on, i.e. how to fix it?

**Comment by timotheecour** [comment]
IIUC Upstream packages for i386 were broken for multiple days; the upstream problem ~~may have~~ has been fixed in the meantime, in any case this I don't think those problems are/were caused by this PR

**Pull request merged**
