### PR TITLE
Don't clobber the callbacks in withTimeout

### PR DESCRIPTION
**Pull request by yyoncho**
If this PR is accespted I will fix `or` as well

### CODE REVIEW

**Comment by planetis-m** [comment]
Both versions are essentially the same, maybe you forgot something?

**Comment by yyoncho** [comment]
> Both versions are essentially the same, maybe you forgot something?

No, `callback=` is calling `future.clearCallbacks`

**Comment by zah** [comment]
The idea here is that one can use `withTimeout` on a `Future` that already has some callbacks installed. The previous version of the code would essentially erase these callbacks, while the new version will preserve them.

**Comment by juancarlospaco** [comment]
Add some comment explaining that IMHO. I like the change.

**Comment by arnetheduck** [comment]
This is a significantly breaking change that silently changes runtime behavior - the way to go about it is to add a second function and potentially deprecate this one.

**Comment by yyoncho** [comment]
> This is a significantly breaking change that silently changes runtime behavior - the way to go about it is to add a second function and potentially deprecate this one.

@arnetheduck I am fine with this approach too(although I am a bit skeptical that someone will depend on this odd side effect). Should I proceed with implementing this or better wait for more input?

**Comment by arnetheduck** [comment]
> odd side effect

code that didn't run before will run now meaning that the order of operations and which operations are performed (closing socket, writing to file, releasing locks etc) will change - it would be difficult to use the function in a library and support "both" versions of it correctly meaning that an application / library wouldn't be able to support two nim versions (pre/post change), which makes migrations and upgrades hard. I believe it's better to not create these situations unless strictly necessary (we recently introduced a stability guarantee for Nim for this reason)

**Comment by yyoncho** [comment]
@arnetheduck I see your point, no need to convince me. I just want to have an agreement on the approach before investing more effort into the PR.

**Comment by zah** [comment]
I'm also not quite convinced that a "stability guarantee" should be a commitment to preserve buggy behavior. Maintaining a buggy version in the standard library also has a cost that will be paid by all future users of Nim (who will be confused with regard to which function they should use). Even with deprecating `withTimeout`, people will continue to copy/paste code that is using it for some time. IMO, Nim simply doesn't have enough users using older versions of the compiler to justify such a strong guarantee regarding preserving behavior.

**Comment by arnetheduck** [comment]
> Nim simply doesn't have enough users using older versions

This is a chicken-and-egg problem: as long as Nim keeps breaking existing code for existing users, these existing users / libraries will go away as their code breaks and will have to be replaced with fresh users / libraries, and the  cycle repeats - the policy was implemented so that Nim can gain a reliable long-term user-base as well as a consistent set of working libraries.

**Comment by Araq** [comment]
In addition to that we should never forget "breaks your code at compile-time" and "secretly changes the behavior of your code at runtime" are very different.

**Pull request closed without merging**
