### PR TITLE
Simpler complex division implementation

### PR DESCRIPTION
**Pull request by rotu**

### CODE REVIEW

**Review by ringabout — DISMISSED** [review]
Wrong branch, contribute to the devel branch please.

**Comment by Varriount** [comment]
@rotu Have you done any performance tests between the old and new versions? I'd be interested to know why this implementation wasn't used in the first place.

**Comment by rotu** [comment]
The existing implementation is “Smith’s Algorithm”, which is more accurate when the real and imaginary parts both have very positive or very negative exponents.

I prefer the naive approach for being more straightforward and easy to check.

I think the [LLVM implementation](https://github.com/llvm/llvm-project/blob/b69086e6c76c87b13dbd120ea04a4f5f6a7d6d67/libcxx/include/complex#L666) is even better, but still less readable than the naive. It dissects the out the exponent from the floating point representation, performs the naive division, then reintroduces the exponent.

**Comment by Varriount** [comment]
While this new implementation is simpler, the existing implementation isn't *that* complex. I'd prefer seeing an objective technical benefit (such as performance or accuracy), before merging a minor change like this. That being said, I'm not experienced with mathematical algorithms like this, so perhaps I'm missing something?

Perhaps a better approach here would be to enhance the procedure's documentation:
```nim
func `/`*[T](x, y: Complex[T]): Complex[T] =
  ## Divides two complex numbers.
  ## 
  ## More specifically, this implementation uses Smith's Algorithm (though this may change in the future).
  ## Equivalent to `x * conjugate(y) / abs2(y)`.
```

**Comment by Araq** [comment]
I agree with @Varriount

**Comment by Varriount** [comment]
Additionally, purely out of curiosity, do you have any links on complex number division algorithms? The only content I can find relating to "Smith's Algorithm" seems to be related to artificial intelligence.

**Comment by rotu** [comment]
> Additionally, purely out of curiosity, do you have any links on complex number division algorithms? The only content I can find relating to "Smith's Algorithm" seems to be related to artificial intelligence.

I think it was first introduced in “Communications of the ACM” Volume 5, issue 8
https://dl.acm.org/doi/10.1145/368637.368661

Here’s a paper with some more discussion: https://www.scilab.org/sites/default/files/scilabisnotnaive.pdf#page30

Part of the reason I proposed this change is that floating point division is painfully slow on some systems (specifically the PIC24 MCUs), so I thought the extra division was decadent.

Also, the Smith algorithm isn’t used for `inv`, nor is a fast algorithm used for`*` like https://hal.archives-ouvertes.fr/hal-02001080/file/MultConstComplex.pdf

I’ll think on this a bit more.

**Comment by rotu** [comment]
@Araq was there any reason to implement this in pure Nim as opposed to the importing from the C standard https://en.cppreference.com/w/c/numeric/complex (like much of `std/math`?

**Comment by Varriount** [comment]
> @Araq was there any reason to implement this in pure Nim as opposed to the importing from the C standard https://en.cppreference.com/w/c/numeric/complex (like much of `std/math`?

Likely because a non-Nim implementation won't work on targets such as Javascript.

**Comment by Araq** [comment]
> was there any reason to implement this in pure Nim as opposed to the importing from the C standard https://en.cppreference.com/w/c/numeric/complex (like much of std/math?

The C standard had no complex types when the code was written.

**Pull request merged**
