### PR TITLE
Multiple borrow improvements, fixes multiple issues

### PR DESCRIPTION
**Pull request by cooldome**
The following PR fixes issues #6026, #3082 and likely a couple of other borrow related issues.  Change allows generic functions to borrow. Also fixes borrowing issue of some var string magics. Please see added tests for examples. It is far from solving all borrowing problems, but is a definitely an improvement.

I should say my understanding of Nim type system internals are rather low, mistakes are plausible.

### CODE REVIEW

**Comment by dom96** [comment]
@Araq ping

**Comment by Araq** [comment]
This seems convoluted. :-( What's wrong with the current solution that you have to introduce these symbol rewriting hacks in different places?

**Comment by cooldome** [comment]
There are multiple changes, different motivation:

1. Changes  in compiler/semexprs.nim
This is just the bug fix to the problem that the following magics can't borrowed, because they have fake var arguments.:
```
   FakeVarParams = {mIncl, mExcl, mSetLengthStr, mSetLengthSeq, mAppendStrCh,
                               mAppendStrStr, mSwap, mAppendSeqElem, mNewSeq}
```
semBorrow in successful, but C code generated does not compile.  Please see my latest comment to issue #3082. This change is not related to the the next item.

2. Changes to semcall.nim. Previous implementation of borrow semantic only allowed ordinary proc to borrow another ordinary proc. There was no way for generic proc to borrow since proc instantiation mechanism was not aware of such thing as borrow at al. I made semResolvedCall aware of the borrowing, in efficient way skip proc body instantiation step in favor of borrowed symbol. The only thing that need to be instantiated is the result type, this was done. searchForBorrowProc required minor modification to be able to skip generic types.

Warning: I have implemented generic proc borrows ordinary proc, case generic proc borrows another generic proc remains unimplemented.

**Comment by cooldome** [comment]
Hi Araq. If there is a still a problem with this PR, please let know if there is better way to implement borrowing by generic proc.

**Comment by Araq** [comment]
Sorry I really loathe yet another rewrite rule in ``semResolvedCall``, there's got to be another way.

**Comment by andreaferretti** [comment]
@Araq Any chance this can be considered again? If this fixes the borrowing for generic types, it would be great!

**Comment by Araq** [comment]
The ``borrow`` implementation should simply fill out the missing proc body. I don't understand why it needs all these rewrite rules. In fact, it can probably be implemented as a macro.

**Pull request closed without merging**
