### PR TITLE
Fixes #7121

### LINKED ISSUE #7121: Windows large filesize
## Problem
Nim doesn't report correct file size when using getFileSize(f: File),  but does with os module's getFileSize(filename: string).

There are three behaviors:
<2Gb OK
2GB<4GB Throws
>4GB returns 0

## Setup:
Windows 10, 64bit
Nim devel 45c02af2

## Code:
```
import os, osproc, strformat
  
proc foo(fn: string; sz: int64) =
  echo "File: " & fn & " size: " & $sz

  # Windows, create file
  discard execProcess(&"fsutil file createnew {fn} {sz}" )

  echo "OS string file size: ", os.getFileSize(fn)

  var f = open(fn)
  try:
    echo "handle file size: ", f.getFileSize()
  except:
    echo "handle file size err: ", getCurrentExceptionMsg()
  f.close()

  # Remove tmp file
  # os.remove(fn)

foo("notlargefile", 50_000)
echo ""
foo("largefile1", 3_000_000_000)
echo ""
foo("largefile2", 5_000_000_000)
```

## Output:
File: notlargefile size: 50000
OS string file size: 50000
handle file size:50000

File: largefile1 size: 3000000000
OS string file size: 3000000000
handle file size err:cannot retrieve file position

File: largefile2 size: 5000000000
OS string file size: 5000000000
handle file size:0

### PR DESCRIPTION
**Pull request by pqflx3**
Fixes #7121: Windows was unable to report file sizes > 2Gb, and incorrectly for >4Gb.

When tested on linux (Arch, x64), clong was of size 8, which allowed ftell to correctly report filesize, but it seems appropriate to switch to ftello anyway.

Replace ftell and fseek with (windows) _ftelli64, _fseeki64 and (posix) ftello, fseeko

### CODE REVIEW

**Comment by Yardanico** [comment]
I changed "Fixes issues 7121" to "Fixes #7121" so it will be automatically closed when merged :)

**Comment by Araq** [comment]
Nice but the test should be disabled:

- it's unlikely we introduce regressions here.
- it's likely the testing environments will fail to create these huge files.

**Comment by Tormund** [comment]
I am getting problems with this pr.
nim c koch.nim 
failed with 
`nim\nimcache\stdlib_system.o:stdlib_system.c:(.text+0xb76e): undefined reference to `_ftelli64'`
My env:
Windows 10 64bit
MinGW 32bit
and nim compiled with build.bat (32bit)

**Comment by pqflx3** [comment]
Do you happen to know which mingw / GCC version? I just tried with the latest mingw 32bit GCC 7.2 and _fseeki64 and _ftelli64 are both defined

**Comment by Tormund** [comment]
gcc (MinGW.org GCC-6.3.0-1) 6.3.0

**Pull request merged**
