### PR TITLE
Remove /unmaintained

### PR DESCRIPTION
**Pull request by Clyybber**
Files are saved in history anyways, should one need them, and having a folder named "umaintained" on the repo page doesn't look too good :)

### CODE REVIEW

**Comment by juancarlospaco** [comment]
This produced a "Bug" in the changelog: https://github.com/nim-lang/Nim/blame/devel/changelog.md#L60

**Comment by ringabout** [comment]
@juancarlospaco

feel free to make a PR  and remove that item

**Comment by timotheecour** [comment]
> Files are saved in history anyways, should one need them, and having a folder named "umaintained" on the repo page doesn't look too good :)

meh; this was my reasoning: https://github.com/nim-lang/Nim/pull/17828#issuecomment-825984750

once they're removed, they're not discoverable anymore; the point of `unmaintained/` was to make it easy for people to revive them should they need it, either for this repo or their own project. unmaintained was meant for files that have some potential of being useful for revival.

> feel free to make a PR and remove that item

if we're still insisting of keeping unmaintained removed, instead of removing this from changelog:
```
- Moved `.travis.yml`, `appveyor.yml.disabled`, `.github/workflows/ci.yml.disabled` to `unmaintained/`.
```

it should be changed to:
```
- Removed `.travis.yml`, `appveyor.yml.disabled`, `.github/workflows/ci.yml.disabled`.
```
(for discoverability, so that at least those files leave a permanent trace in changelog)

(oh, and use `[skip ci]` for that, which now works since https://github.com/nim-lang/Nim/pull/17561)

**Comment by timotheecour** [comment]
=> https://github.com/nim-lang/Nim/pull/17870

**Pull request merged**
