### PR TITLE
Fix typo in docs

### PR DESCRIPTION
**Pull request by yyyc514**

### CODE REVIEW

**Comment by yyyc514** [comment]
Grrr, I meant 'typo'

**Comment by timotheecour** [comment]
u can change the title of your PR... otherwise your typo fixing has a typo lol

**Comment by yyyc514** [comment]
Is that possible from the web UI?

**Comment by timotheecour** [comment]
for PR title: u just did
for commits titles: locally, `git rebase -i`

**Comment by yyyc514** [comment]
LOL, yeah I know how to do it from the console... I just did this quickly on the web.  Awesome to see it merged.

**Comment by timotheecour** [comment]
keep em coming ;-)

**Pull request merged**
