### PR TITLE
Restore compatibility with old vcc versions

### LINKED ISSUE #10352: Generated c code is not compile with the vcc cl.exe before 2012 after v0.19
After the v0.19, the module init function contains code "{TFrame FR_; FR_.len = 0;}" before c variable define, and this is not allowed with classical c compiler.

This is code generated after v0.19:
```nim
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void) {
{
	TFrame FR_; FR_.len = 0;
}
	int T1_;
	int T2_;
	int T3_;
nimRegisterThreadLocalMarker(TM_Q5wkpxktOdTGvlSRo9bzt9aw_17);
	genericReset((void*)(&strDesc_D0UzA4zsDu5tgpJQ9a9clXPg), (&NTI_TuG1vdYwChKtx4TOkRnAjw_));
	strDesc_D0UzA4zsDu5tgpJQ9a9clXPg.size = ((NI) 4);
	strDesc_D0UzA4zsDu5tgpJQ9a9clXPg.kind = ((tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A) 28);
	strDesc_D0UzA4zsDu5tgpJQ9a9clXPg.flags = 2;
	T1_ = (int)0;
	T1_ = _fileno(stdin);
	_setmode(T1_, _O_BINARY);
	T2_ = (int)0;
	T2_ = _fileno(stdout);
	_setmode(T2_, _O_BINARY);
	T3_ = (int)0;
	T3_ = _fileno(stderr);
	_setmode(T3_, _O_BINARY);
	initAllocator_IZ2oOmqdsYQ7vixQGKSDcAsystem();
	initStackBottom();
	initGC_njssp69aa7hvxte9bJ8uuDcg();
	registerSignalHandler_njssp69aa7hvxte9bJ8uuDcg_2();
}
``` 

And this is the code generate before v0.19
```nim
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void) {
	int T1_;
	int T2_;
	int T3_;
nimRegisterThreadLocalMarker(TM_Q5wkpxktOdTGvlSRo9bzt9aw_17);
	genericReset((void*)(&strDesc_D0UzA4zsDu5tgpJQ9a9clXPg), (&NTI_qQQlSworN6w6Qnxtmq0s5Q_));
	strDesc_D0UzA4zsDu5tgpJQ9a9clXPg.size = ((NI) 4);
	strDesc_D0UzA4zsDu5tgpJQ9a9clXPg.kind = ((tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A) 28);
	strDesc_D0UzA4zsDu5tgpJQ9a9clXPg.flags = 2;
	T1_ = (int)0;
	T1_ = _fileno(stdin);
	_setmode(T1_, _O_BINARY);
	T2_ = (int)0;
	T2_ = _fileno(stdout);
	_setmode(T2_, _O_BINARY);
	T3_ = (int)0;
	T3_ = _fileno(stderr);
	_setmode(T3_, _O_BINARY);
	initAllocator_IZ2oOmqdsYQ7vixQGKSDcAsystem();
	initStackBottom();
	initGC_njssp69aa7hvxte9bJ8uuDcg();
	registerSignalHandler_njssp69aa7hvxte9bJ8uuDcg_2();
}
```

### PR DESCRIPTION
**Pull request by LemonBoy**
Local variables are declared before anything else.

Fixes #10352 

Marked as backport because it's a regression.
@slangmgh can you try this patch?

### CODE REVIEW

**Comment by slangmgh** [comment]
@LemonBoy 

OK, The patch is fine.

I don't know the compiler logic well, but I think we can just add '{' and '}' around the code after the TFrame, which doesn't change anything, just make the c compiler works.

I create a pr before I find you have fixed this issue.

**Comment by slangmgh** [comment]
@LemonBoy still problem with some file

```nim
N_LIB_PRIVATE N_NIMCALL(void, compiler_stock_dataInit000)(void) {
	tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw* T1_;
{
	TFrame FR_; FR_.len = 0;
	EMPTY_DATE_29bPbNs1RkaQ5RRFFecB32w.Sup.m_type = (&NTI_d9cK9cyKZPJJxFXUmx8dSpPw_);
}
	nimfr_("stock_data", "stock_data.nim");
nimRegisterGlobalMarker(TM_MFQ41p5Rlwq6TW4ubcDw4g_2);
	nimln_(484, "stock_data.nim");
	T1_ = (tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw*)0;
	T1_ = utc_iX2Ltm3Mj5gsgJ5hFxUKgQ();
	initDateTime_qf1NugU9bsahSTtx9aMSE83g(((NI) 1), ((tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw) 1), ((NI) 1970), ((NI) 12), ((NI) 0), ((NI) 0), T1_, (&EMPTY_DATE_29bPbNs1RkaQ5RRFFecB32w));
	popFrame();
}

```

I think my solution is more reliable, so I reopen it.

**Comment by LemonBoy** [comment]
So, what's the error message?

**Comment by slangmgh** [comment]
The error message is same, macro 'minfr_' define an variable 'TFrame FR_; ', which is not allowed in classic c compiler, it must be in the start of the a block.

**Comment by slangmgh** [comment]
Here is the compiler error message:
```nim
N_LIB_PRIVATE N_NIMCALL(void, compiler_pyplotInit000)(void) {
{
	TFrame FR_; FR_.len = 0;
	nimln_(4355, "system.nim");
	alreadyExecuted_yA9a5a1VojMDexgw7KV6LzA = NIM_FALSE;
}
	nimfr_("pyplot", "pyplot.nim");
nimRegisterGlobalMarker(TM_SRJv6LGRhNMJOxqNy9bnl5g_2);
nimRegisterGlobalMarker(TM_SRJv6LGRhNMJOxqNy9bnl5g_3);
nimRegisterGlobalMarker(TM_SRJv6LGRhNMJOxqNy9bnl5g_4);
nimRegisterGlobalMarker(TM_SRJv6LGRhNMJOxqNy9bnl5g_5);
	popFrame();
}
```
```nim
compiler_pyplot.c
d:\tmp\nimcache\d\compiler_pyplot.c(519) : error C2275: 'TFrame' : illegal use of this type as an expression
        d:\Tool\Nim\lib\nimbase.h(429) : see declaration of 'TFrame'
d:\tmp\nimcache\d\compiler_pyplot.c(519) : error C2146: syntax error : missing ';' before identifier 'FR_'
d:\tmp\nimcache\d\compiler_pyplot.c(519) : error C2065: 'FR_' : undeclared identifier
d:\tmp\nimcache\d\compiler_pyplot.c(519) : error C2224: left of '.procname' must have struct/union type
d:\tmp\nimcache\d\compiler_pyplot.c(519) : error C2224: left of '.filename' must have struct/union type
d:\tmp\nimcache\d\compiler_pyplot.c(519) : error C2224: left of '.line' must have struct/union type
d:\tmp\nimcache\d\compiler_pyplot.c(519) : error C2224: left of '.len' must have struct/union type
```

**Pull request merged**
