### PR TITLE
Simplify cgen forward proc

### PR DESCRIPTION
**Pull request by arnetheduck**

### CODE REVIEW

**Comment by krux02** [comment]
I like these kind of changes, but the tests are still failing:
```
lib/nimrtl.nim --app:lib -d:createNimRtl --threads:on dll 1 sec 187 ms
tests/dll/client.nim -d:useNimRtl --threads:on dll 1 sec 359 ms
tests/ccgbugs/twrong_method.nim ccgbugs 187 ms
lib/nimrtl.nim -d:release --app:lib -d:createNimRtl --threads:on dll 1 sec 125 ms
tests/dll/client.nim -d:release -d:useNimRtl --threads:on dll 1 sec 750 ms
tests/generics/tforwardgeneric.nim generics 281 ms
```

**Comment by arnetheduck** [comment]
and I don't like them - every time a needle is moved, the stack of cruft falls apart.

looks like `prc.position` can't be relied upon (sigh) - it's just a dead field for proc syms.

and yeah, I tend to use the travis ci instead of running the suites locally (too unreliable on my local setup, specially since I don't really have osx/win machines) - just haven't found a good way to launch them without creating a PR.

**Comment by sid-code** [comment]
There is a regression here. I can't reproduce it in a minimal environment, but if you pull my code:

```
git clone git@github.com:sid-code/nmoo
git checkout 6992604
nimble test
```

The nim compiler will happily emit the C code but then gcc will spit out an error. This commit causes the issue, which I discovered by bisecting.

**Comment by timotheecour** [comment]
@arnetheduck 
>  just haven't found a good way to launch them without creating a PR.

no PR needed, just connect your github to travis (done once) and then any `git push` on any of your local branches will trigger a travis build

**Pull request merged**
