### PR TITLE
added extended msg for failed library loads w/ incorrect DLL formats

### PR DESCRIPTION
**Pull request by awr1**
Common issue that I've seen in the Nim IRC is the `could not load:` error with DLLs with the wrong architecture, hopefully this pushes people in the right direction.

### CODE REVIEW

**Comment by awr1** [comment]
Message box works:
image

**Comment by Varriount** [comment]
Hm, keep in mind that (as paradoxical as it may seem) there _are_ circumstances where "GUI" applications can't/shouldn't create windows. The most common situation is when an application is running as a Windows service (Linux daemon equivalent).

**Comment by ghost** [comment]
@Varriount but the code only shows MessageBox with "when defined(guiapp):", otherwise it's just "cstderr.rawWrite(badExe)"

**Comment by awr1** [comment]
> 
> 
> Hm, keep in mind that (as paradoxical as it may seem) there _are_ circumstances where "GUI" applications can't/shouldn't create windows. The most common situation is when an application is running as a Windows service (Linux daemon equivalent).

The message boxes on fatal crashes aren't new and only show up with `--app:gui` for Windows

**Pull request merged**
