### PR TITLE
Fix #11684 For loops over a hardcoded empty array crash the compiler

### LINKED ISSUE #11684: For loops over a hardcoded empty array crash the compiler.
A for loop over a hardcoded empty array, which is meaningless, causes the compiler to have an internal error.

### Example
```nim
for _ in []:
  discard
```

### Current Output
```
Error: internal error: getTypeDescAux(tyEmpty)
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp c <file>
```

### Expected Output
```
```

This occurs on the latest devel and stable.

### PR DESCRIPTION
**Pull request by bung87**
fix #11684

### CODE REVIEW

**Comment by ghost** [comment]
What happens if you try it with the JS backend? Shouldn't that error be caught in the front-end generally?

**Comment by bung87** [comment]
what I thought is it should throw during ast processing , but it not , it reach to ccgtypes.nim . it reach there should be handled in there or down stream, otherwise it shouldn't reach there.

**Comment by Araq** [comment]
This needs to be fixed in the frontend.

**Comment by bung87** [comment]
> This needs to be fixed in the frontend.

where's frontend related files located?

**Comment by Araq** [comment]
sigmatch.nim proc ``concreteType``. It needs to say that openArray[empty] is invalid too. I think.

**Comment by bung87** [comment]
give up

**Pull request closed without merging**
