### PR TITLE
Rename `=` to `=copy` in stdlib

### PR DESCRIPTION
**Pull request by Clyybber**

### CODE REVIEW

**Comment by timotheecour** [comment]
good but `=` should issue a deprecation warning

**Comment by Clyybber** [comment]
> good but `=` should issue a deprecation warning

Yep, eventually.

**Comment by ringabout** [comment]
Yeah, I would like that `prco `=`(a, b) {.error.} ` can disable assignment because some objects are not moveable especially multiple threads scope.

**Comment by timotheecour** [comment]
@xflywind but can't we do that with `=copy` procs ? 

what i was suggesting was giving a warning for `=` so users migrate to the more explicit `=copy` variants

**Comment by ringabout** [comment]
Some objects are non-copyable, but moveable, so `=copy {.error.}` should be used.
And some objects are non-moveable,

**Comment by timotheecour** [comment]
but nim compiler doesn't distinguish between `=` and `=copy` IIRC, eg:
> The `=` hook is now called `=copy` for clarity. The old name `=` is still available so there
...
> let k = if name == "=" or name == "=copy": attachedAsgn else: attachedSink

**Comment by ringabout** [comment]
I knew it. not yet I hope.

can be deprecated first in case of others using it.

**Pull request merged**
